### ISSUE TITLE
Feature: Set password on new account inside dialog

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1000]
This is a tracking bug for an experiment for @skinny97214 

The create account flow is quite confusing - mix in unverified emails and there is a lot of room for "WTF" with regards to account completion.  The purpose of this experiment is to put the "set password" flow inside of the dialog.

**Comment by shane-tomlinson** [comment]
@skinny97214 - if we do the set password flow inside the dialog for new users, are we going to do the same for reset-password?

**Comment by lloyd** [comment]
I've deployed the latest on https://issue1000.hacksign.in and http://issue1000.myfavoritebeer.org

@shane-tomlinson I've installed your public key so you can update the server.

**Comment by lloyd** [comment]
@shane-tomlinson `git remote add issue1000 app@issue1000.hacksign.in:git`
