### ISSUE TITLE
cancel from "forgot password" does not remember entered email address

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1001]
Steps to reproduce:

1) Go to beta.myfavoritebeer.org
2) Open BID dialog.
3) If logged in, click "this is not me"
4) Enter in known email address
5) click "Forgot your password?"
6) Click cancel

The email address entered before is not remembered.

**Comment by shane-tomlinson** [comment]
Linking to #984

**Comment by jrgm** [comment]
verified as fixed on stage train-2012.02.02 on all browsers winxp(ie8),win7(ie9),ubuntu,osx and with stock browser android 2.1
