### ISSUE TITLE
cancel from "verify primary" address does not remember previously entered email address

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1002]
Steps to reproduce:

1) If authenticated, go to eyedee.me and logout
2) Go to beta.myfavoritebeer.org
3) Open BID dialog.
4) If authenticated, log out.
5) Enter known eyedee.me address.
6) Click Next
7) Click Cancel

Where'd the address go?  BOO!

**Comment by jrgm** [comment]
verified
