### ISSUE TITLE
Clicking on "Use another address" for new user registration does not remember previously filled in email.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1003]
Steps to reproduce:

1) Go to beta.myfavoritebeer.org
2) Open BrowserID dialog.
3) If logged in, log out.
4) Enter unknown secondary supported address
5) Click "Use another address"

Check out the empty email address.

Expected:
Pre-filled in email address.

**Comment by jrgm** [comment]
verified on stage
