### ISSUE TITLE
Clicking on "Use another address" for adding an email to account does not remember previously filled in email.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1004]
Steps to reproduce:

1) Go to beta.myfavoritebeer.org
2) Open BID dialog.
3) Sign in, go to email picker.
4) Click "Add a new address"
5) Add a new secondary address that needs validated.
6) Click "Use another address"
7) Wait for previous screen to appear.

Uh oh, email address is not remembered.

Expected: Previous email address is already filled in.

**Comment by jrgm** [comment]
verified on a bunch of browser/os combinations
