### ISSUE TITLE
Account creation needs to clarify "password"

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#101]
See the writeup at http://www.yesodweb.com/blog/2011/07/browserid-support , and note the confusion about passwords:

"The initial login window was unclear, asking for email and password. This implied that she was supposed to provide the password for her email account, which made her even more concerned."

**Comment by lloyd** [comment]
discussion and proposals:

http://irclog.gr/#show/irc.mozilla.org/identity/1506

**Comment by benadida** [comment]
I believe this is now fixed with the new UI flow.
