### ISSUE TITLE
bin/browserid on stage webhead dies on network issue

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1011]
on one of the webheads in stage, the browserid restarted at 30 Jan 12:38:19; @fetep notes that there was a '"networking event" at almost exactly that time.'

These are the last messages on browserid.log. Note the long pause before the error, and then the restart messages

{"level":"info","message":"127.0.0.1 - - [Mon, 30 Jan 2012 20:37:43 GMT] \"GET /wsapi/session_context HTTP/1.0\" 200 193 \"-\" \"-\"","timestamp":"30 Jan 12:37:43"}
{"level":"error","message":"error forwarding request: Error: socket hang up","timestamp":"30 Jan 12:38:19"}
{"level":"info","message":"browserid server starting up","timestamp":"30 Jan 12:38:19"}
{"level":"info","message":"code version (from ver.txt) is: 4acea5f","timestamp":"30 Jan 12:38:19"}

**Comment by lloyd** [comment]
STR locally:
1. fiddle keysigner to bind the wrong port
2. `npm start`
3. log into `127.0.0.1:10001`, creating an account along the way
4. notice at the moment a request is attempted to be forwarded to keysigner, things go boom:
   
   browserid (3707): info: forwarding request: /wsapi/cert_key -> http://127.0.0.1:10003/wsapi/cert_key
   browserid (3707): error: error forwarding request: Error: connect ECONNREFUSED
   browserid (3707): error: uncaughtException pid=3707, uid=1000, gid=100, cwd=/home/lth/dev/browserid, execPath=/usr/bin/node, version=v0.6.11, argv=[node, /home/lth/dev/browserid/bin/browserid], rss=41639936, heapTotal=30801856, heapUsed=17445352, loadavg=[0.09033203125, 0.07080078125, 0.05126953125], uptime=11850.10393312, trace=[column=13, file=/home/lth/dev/browserid/lib/wsapi/cert_key.js, function=null, line=33, method=null, native=false, column=5, file=/home/lth/dev/browserid/lib/http_forward.js, function=, line=56, method=null, native=false, column=17, file=events.js, function=ClientRequest.emit, line=67, method=emit, native=false, column=11, file=http.js, function=, line=1137, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=67, method=emit, native=false, column=25, file=net.js, function=Array.0, line=319, method=0, native=false, column=40, file=node.js, function=EventEmitter._tickCallback, line=192, method=_tickCallback, native=false], stack=[TypeError: Object #<ServerResponse> has no method 'sendHeader',     at /home/lth/dev/browserid/lib/wsapi/cert_key.js:33:13,     at ClientRequest.<anonymous> (/home/lth/dev/browserid/lib/http_forward.js:56:5),     at ClientRequest.emit (events.js:67:17),     at Socket.<anonymous> (http.js:1137:11),     at Socket.emit (events.js:67:17),     at Array.0 (net.js:319:25),     at EventEmitter._tickCallback (node.js:192:40)]
