### ISSUE TITLE
UI confusing for password change when using primary and secondary accounts

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1015]
A minor point about the UI for a password change, when you have accounts
for both primary and secondary on the same diresworb account.

1) get set up so you have two accounts associated with each other for
   beta.myfavoritebeer.org (e.g., foo@example.com and bar@example.com).

2) sign out of beta.myfavoritebeer.org, and then sign in. In the dialog
   select 'Use a different email' and enter an email address for a
   primary (e.g., baz@eyedee.me). Complete the signup process.

3) Go the http://diresworb.org. The page shows the three accounts (foo, bar,
   and baz) listed under 'Your Email Addresses', and then the section for
   a password change. 

The UI is sort of suggesting that a password change would apply to all  
three email addresses (which is not the case). Needs some thought about
how to present this to the end user so it's clear what password change
will apply to what addresses. /cc @skinny97214

**Comment by shane-tomlinson** [comment]
@jrgm - the password change only applies to accounts that have secondaries.  If an account only has primaries, the password change area is not displayed.  I agree that we should probably have some explanation for this.

**Comment by jrgm** [comment]
Yes, I know it only applies to secondaries.

**Comment by jrgm** [comment]
I'm retracting my nit and closing this issue. Real end user testing is better for deciding whether this is an issue.
