### ISSUE TITLE
eyedee.me provisioning appears to be case-sensitive

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/persona#1018]
Platform: Mobile Safari on iOS4.3.

I signed into eyedee.me as Mikeh.

I attempted to login to beta.myfavoritebeer.org with mikeh@eyedee.me.  I was asked to verify (and cancelled out).

I attempted to login to beta.myfavoritebeer.org with Mikeh@eyedee.me and it worked.

**Comment by lloyd** [comment]
fixed!
