### ISSUE TITLE
Make secondary "cancel" style buttons have a smaller font.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1020]
See screen shot from feature branch 1000.

https://skitch.com/set117/g7i8y/cancel-button-new-style

**Comment by shane-tomlinson** [comment]
@jbonacci, @jrgm, @ioanab 

Look for this update in the dialog by verifying the cancel button is similar to the above screenshot in the following locations:
1) Forgot password
2) Add email to authenticated account.
3) Screen stating you must verify with Primary

**Comment by jrgm** [comment]
verified as fixed on stage train-2012.02.02 on all browsers winxp(ie8),win7(ie9),ubuntu,osx and with stock browser android 2.1, in the three locations noted above.
