### ISSUE TITLE
Enhancement request: Add a name to the BrowserID popup window

### ISSUE THREAD

**Issue by davehunt** [mozilla/persona#1023]
Using Selenium to test a site with BrowserID currently has to cycle through all windows to find one with the title 'Browser ID'. It would be possible to switch directly to the window if it had a name assigned to it.

Current:

```
for handle in selenium.window_handles:
    selenium.switch_to_window(handle)
        if selenium.title == 'Browser ID':
            break
```

Ideal:

```
selenium.switch_to_window('browserid')
```

**Comment by tonychung** [comment]
improving support to our automation needs is always a good thing.   Help us, help you.

**Comment by shane-tomlinson** [comment]
@lloyd - what do you think of adding this to WinChan?

**Comment by shane-tomlinson** [comment]
Pull request to WinChan issued to allow window.name to be specified. https://github.com/lloyd/winchan/pull/26

@lloyd - can you review the WinChan change?

@benadida - in auth_with_idp/main.js, you set the window.name to auth_with_primary.  I spoke to @davehunt about opening the window with another name so they they can get a reference to the window, something like persona_dialog.  Once the Selenium has a handle to the window, the window name can be changed without ill effect.

**Comment by jrgm** [comment]
verified train-2012.08.17
