### ISSUE TITLE
Split compress.sh into compress-locales.sh

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1024]
Per @fetep,
Some artifacts are built on code in browserid.rpm and others will be built from browserid-locale.rpm.

browserid-locale.rpm will change every 10 minutes if there are new strings in SVN.

We need compress.sh to be split into:
scripts/compress.sh
scripts/compress-locales.sh

That way each RPM can run and generate artifacts at the appropriate time.

compress-locales.sh will depend on compress.sh having run already, as it slurps in files like template.js.

@lloyd sorry, this will cause updates to some of your AWS and other scripts. 
@shane-tomlinson @benadida @jbonacci @jrgm - we will now have to run both of these compress scripts for production like local deployments.

**Comment by lloyd** [comment]
no problem from my side.  

I think we need to rewrite all this gunk in javascript anyway, so we we can go ahead and do a quick split now, then revisit and figure out code sharing, how many modes we need, and optimization path when we go and rewrite in .js

**Comment by ozten** [comment]
First stab at fixing this:
https://github.com/mozilla/browserid/pull/1025

**Comment by ozten** [comment]
This was merged to dev. Closing, please re-open if there are any issues.
