### ISSUE TITLE
"translated text" in test

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1031]
VIA IRC
 there's string "translated text" in resources/static/dialog/views/testBodyTemplate.ejs:7 resources/static/dialog/views/test_template_no_input.ejs:6 resources/static/dialog/views/test_template_with_input.ejs:7

This looks like a unit test. Can I remove gettext, so localizers don't see this string? or is that the purpose of the unit test?

CC @mathjazz @shane-tomlinson

**Comment by jrgm** [comment]
verified code is gone on train-2012.02.02 and dev branches.
