### ISSUE TITLE
Slightly confusing copy on browserid.org login workflow.

### ISSUE THREAD

**Issue by skorokithakis** [mozilla/persona#1037]
When trying to log in to example.com via BrowserID, you are presented with the text:

> Enter your email address to sign in to example.com

From user feedback, this is somewhat confusing, as many users think they need to sign _up_ before they can sign _in_ and leave the workflow. I propose the addition of a sentence to the effect of:

> "If you do not already have an account with example.com, one will be created now."

**Comment by skorokithakis** [comment]
I was going to change this myself and issue a pull request, but I can't find the relevant template :/ Is this not the same code as the one that runs on browserid.org, or am I just incompetent?

**Comment by shane-tomlinson** [comment]
@skorokithakis - We did a complete overhaul of the dialog since you filed this issue.  Are your uses still finding this a problem, or have we cleaned things up suitably?  Thanks!

**Comment by skorokithakis** [comment]
@shane-tomlinson Hmm, I still see the same copy there, which will confuse someone who thinks they need to create an account first. Therefore, I still propose the addition of the above sentence to the workflow, to clarify that accounts will be created if they do not exist yet.

Also, a short sentence explaining what Persona is would be beneficial, in my opinion, as the users are unaware at that point that this is a single sign on solution, and think they're creating an account on the corresponding site.

**Comment by jrgm** [comment]
Hey @ryanfeeley, can you look at this while you're looking at copy changes (and close if this is covered by those changes)? Thanks.

**Comment by ryanfeeley** [comment]
Amazingly, we are reintroducing something close to the original copy although the context is changing slightly (we're likely targeting to become the "sign in with your email" option), and the absence of the accompanying password field resets the expectations somewhat. Let's see how it tests. I definitely agree users need access to information about what Persona is (and why it exists).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
