### ISSUE TITLE
tweak primary IdP API to make it possible for primaries to pre-generate certs

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1038]
We've seen requests from potential primaries for this.

**Comment by shane-tomlinson** [comment]
@benadida - reassigning back to you - is this needed still?

**Comment by benadida** [comment]
downgrading.

**Comment by shane-tomlinson** [comment]
@benadida, @ozten - are we going to handle this? If not, we could close this down.

**Comment by benadida** [comment]
Not anytime soon I don't think, so I think closing down is right.
