### ISSUE TITLE
ensure that when a primary comes up, existing certs by secondary are invalidated in the dialog

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1039]
otherwise it's a fail for the user.

**Comment by zaach** [comment]
@benadida this will matter for big-tent, yes?

**Comment by benadida** [comment]
@zaach yes, given the way we're now doing bigtent with non-chained public keys, we should indeed fix this.

**Comment by shane-tomlinson** [comment]
@benadida - where would the failure be in this case, at the verifier?

Do we have to worry about the reverse situation as well, if a primary functionality for a domain goes down and Persona thinks a domain is a secondary (from the conversation happening in the mailing list)?

**Comment by callahad** [comment]
The reverse seems like a reasonable concern. Maybe the broader principle is that the UA shouldn't send an assertion unless the backing IdP is the same one that would be resolved as per normal?

We'd lose the cool story about how eyedee.me could do down, yet users could still log in to sites that had eyedee.me's pubkey cached, but that kind of seems like a mess anyway...

**Comment by lloyd** [comment]
this is not a beta1 req. moving.  (bigtent will launch post-beta1 and we have other idp related issues)

**Comment by lloyd** [comment]
This has been taken to the mailing list to determine a more holistic solution to handling IdP's coming online and going offline - https://groups.google.com/forum/?fromgroups=#!topic/mozilla.dev.identity/ArXmGF3OnW4

This issue discusses a single component of the problem and is not useful.  Closing down and will open specific issues to get this done and make the world safe for bigtent.
