### ISSUE TITLE
two screens shown at same time in db_LB on dev

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1045]
There are CSS or other issues on the homepage of dev.diresworb.org that cause the account manager and the splash page to be shown at the same time.

Steps to Reproduce
1) Clear cookie or log out of dev.diresworb.org
2) Set Language to it-CH
3) Go to https://dev.diresworb.org/

Actual:
Both the account manager and splash page are shown, stack on top of each other.
Note: You are not logged in, but there is an "edit" account info button

Expected:
Splash page explaining that BrowserID is dope.

@shane-tomlinson any ideas? I think a recent commit is causing this as the behavior isn't on https://temporary_preview.hacksign.in/

**Comment by lloyd** [comment]
this appears to happen when a language is configured that is missing javascript.

if you can reproduce, should we make the check at startup also check for the presence of javascript for the enabled locales and go down hard if not present?

**Comment by shane-tomlinson** [comment]
@lloyd's diagnosis is correct.

If ther user's locale is not there (even if enabled) - should we log it as an error and serve up the English JS?

**Comment by ozten** [comment]
Thanks for help with troubleshooting!

Fixed in http://git.io/ocHNpg
