### ISSUE TITLE
'hacksign.in' not compatible with user testing.

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1046]
because we use the domain `hacksign.in` for ephemeral deployments, which we use for user testing, users in the test are getting confused and uncomfortable.  we should try to migrate to *.dev.diresworb.org` for this purpose.

**Comment by shane-tomlinson** [comment]
Comment from Asa on my blog - "Can I make the suggestion that if you want people testing this you not use a domain like hacksign.in. I can’t think of a worse possible experience playing with a new login system for the web than being asked to trust something called hacksignin."

**Comment by lloyd** [comment]
resolved in dev.  personatest.org ftw.

**Comment by jrgm** [comment]
Yep done.
