### ISSUE TITLE
User with both primary and secondary accounts is incorrectly re-challenged for password

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1049]
1) Start with a new browser profile. Go to myfavoritebeer.org and sign-in with email1@gmail.com (going through the normal 'Check your email' steps).

2) Logout from myfavoritebeer.org. Click sign-in again and choose 'Use a different email'.  Use a primary email address, e.g., email2@eyedee.me (either an existing account or a new one).

3) Stop the browser, and start again with a new browser profile. (Or alternatively, clear the entire cache/cookies/etc.).

4) Go to myfavoritebeer.org and use email1@gmail.com to sign-in, entering the
password for that account. Make sure email1@gmail.com is the selected account
and click 'sign in'. You are now logged in again to mfbeer OK.

5) Logout of myfavoritebeer.org, and then click 'Sign in' again. From the sign_in dialog, choose email2@eyedee.me. You get the 'Verify with email provider' screen. Click Verify. Enter password at eyedee.me. You are now logged in to myfavoritebeer.org again OK.  Sign out. 

Now the bug:

6) Click 'Sign in'. Select email1@gmail.com and click 'sign in'. 

Expected:
  I should just be signed in with no further action.

Actual:
  I am challenged for the password for email1@gmail.com again.

After this, though, I can login and logout with either account with no further challenges.

**Comment by jrgm** [comment]
Repro for chrome 16 osx, FF 10 osx, IE8 winxp, so not browser-specific.

**Comment by lloyd** [comment]
reproduced here!  fantastic find.  trying to narrow.

**Comment by lloyd** [comment]
so simplified STR:
1. set up an account with one primary and one secondary email address
2. go to my favorite beer, logout if needed, click sign in
3. log in with your secondary email address
4. log out of my favorite beer
5. click sign in
6. log in with your primary email address (it doesn't matter wether you're already signed into eyedee.me or not)
7. now log out
8. now try to log in with your secondary

Technically, the front end is calling `auth_with_assertion` after provisioning always, which is wrong.  But I have a trivial fix on the backend /cc @shane-tomlinson

**Comment by lloyd** [comment]
fix available on dev right now.

**Comment by jrgm** [comment]
verified on opera/safari/ie{8,9}/chrome/firefox on osx,win7,winxp,ubuntu. Network down at moment for mobile.

**Comment by jrgm** [comment]
Works for me on android 2.2 stock browser and FF10. But the native builds are unusable on this Droid2 (keyboard freezes, general unstable browsing behaviour).
