### ISSUE TITLE
l18n: DE-de

### ISSUE THREAD

**Issue by Falco20019** [mozilla/persona#105]
I could translate it into german

**Comment by benadida** [comment]
we'll keep you posted once the framework's in place. Thanks!

**Comment by ozten** [comment]
Fantastic. Please coordinate with @mathjazz.
Here is de progress:
https://localize.mozilla.org/de/browserid/

**Comment by mathjazz** [comment]
German is at 100% right now, but I'm sure it needs proof-reading & testing. We'll add new strings soon, so stay in touch.

**Comment by Falco20019** [comment]
I'll proof-read it next week :) I'll contact you then.

**Comment by lloyd** [comment]
closing down all internationalization issues. l10n has begin, @mathjazz is coordinating the show, contact him directly to learn about contributing.

For now you can inspect current progress by updating your browser settings and visiting http://temporary_preview.myfavoritebeer.org/. (click sign in to see the localized dialog)

NOTE: this url is temporary, and we will transition to "test.myfavoritebeer.org" in the coming weeks.
