### ISSUE TITLE
Some locales such as zh-TW have stale cancelVerify css class

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1052]
There is something wrong with the version of the build script on http://temporary_preview.myfavoritebeer.org/

"If this is a mistake, just ignore the sent email and <a href=\"#\"
id=\"cancel\">cancel</a>."  is showing up in English instead of 

   "若這是個錯誤，請忽略這封信並 <a href=\"#\" id=\"cancel\">取消</a>。"

STR
language json file has the wrong msgid, so it fails to find string...

1) Request  https://temporary_preview.hacksign.in/production/zh_TW/dialog.js

Actual
'If this is a mistake, just ignore the sent email and <a href="#" class="cancelVerify" id="back">use another email address</a>.'

Expected:
'If this is a mistake, just ignore the sent email and <a href="#" class="cancel" id="back">use another email address</a>.' 

CC @mathjazz

**Comment by ozten** [comment]
@mathjazz - Heads up, I found po files that still had an old CSS class.

Fixed in cs, lij, pl, ru, and sr
http://viewvc.svn.mozilla.org/vc?view=revision&revision=101192

Don't know if we need to warn them to avoid SVN conflicts...

**Comment by ozten** [comment]
Okay, I've rebuild all the languages and this fixed this issue.

Please have zh_TW, zh_CN and other locales re-test.

thanks!

**Comment by mathjazz** [comment]
Thank you @ozten! I'll let zh_TW and zh_CN know!

Some locales, including cs, pl, ru, and sr, haven't worked on their translations after we added new and modified strings. When that happened, their old translations were marked as fuzzy, so they know they have to change them.

But lij obviously forgot to update their classes and ids, so thanks for pointing that out.
