### ISSUE TITLE
Provide info to user about last-used email at current site.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#106]

**Comment by 21echoes** [comment]
disagree-- order consistently, have the default selection based on last email used for the site.

**Comment by lloyd** [comment]
everyone seems to agree we can be smart about default selection, and I'm guessing that the average user has fewer than three emails anyway, which makes this issue mostly moot.  

How about we start with consistent ordering and a smart default, then refine from there as needed?

**Comment by shane-tomlinson** [comment]
I can agree with these statements, we will have to think about scrolling issues if the user has many email addresses and the default selection is off the screen.

**Comment by lloyd** [comment]
just to link the two threads, there are some interesting comments about approaches other than reordering attached to the ux post: http://lloyd.io/improving-browserid-ux#comment-267526891

**Comment by shane-tomlinson** [comment]
We highlight the last used email.  Closing this issue.
