### ISSUE TITLE
instrument site in preparation for a/b testing of UX experiments

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1060]
I will be needing metrics to tweak copy, button text, alternate flows through the UI, etc. I need to be able to track the effects of design decisions so we can fine-tune the site.

**Comment by lloyd** [comment]
ball is in my court, repinged our privacy folks, next step is to write up a privacy assessment

**Comment by ozten** [comment]
Capturing our work in https://wiki.mozilla.org/Privacy/Reviews/KPI_Backend

That includes a bunch of technical details.

**Comment by shane-tomlinson** [comment]
@ozten, @lloyd - since KPI has been added to the front end, can this be closed?

**Comment by ozten** [comment]
@skinny - Do we need the A/B aspect?

What we've built so far should allow us to see release over release if a change was good or not.

It does not give us any way to A/B test two flows at the same time.

**Comment by lloyd** [comment]
fwiw, the router that @zcarter is working on gives us a natural place to introduce real world
A/B testing when the time comes.  KPI data + router splitting off a decided %age of users, give
us the tools to make this a reality, afaict.

**Comment by ozten** [comment]
Wouldn't we need to record weather the KPI blob is for A or B?

**Comment by lloyd** [comment]
yes, good point.

we could:
1. have a different KPI destination for tests
2. append code sha to the blob as previously discussed.

If kpi backends are easy to spin up (AWS VPC), I slightly favor #1.  Otherwise, 
#2.

What were the objections with sha?  just that it wasn't stricly necc?

**Comment by ozten** [comment]
1 - this is more complicated than submitting to a user data review to add a new A/B field. You eventually have to merge the two steams or maintain N KPIggybanks
2 - I assumed the SHA would be for a codebase that includes A/B codepaths, so same SHA regardless. If it's branched based, that could work. We'd need a map of SHA to A/B tests which seems kind of opaque but also kind of attractive.

My pushback on including SHA is that we can use statsd during deployments to record when code changes, instead of bloating every KPI blob with this opaque string.

**Comment by lloyd** [comment]
you're always uncovering my assumptions, @ozten.

It seems like the first thing we have to figure out here is how we want to manage A/B testing.  Do we want to have this done via distinct branch?  I rather like that idea, but it's def a question for deeper discussion.  

I was imagining that we have a couple servers set aside for A/B testing, and we can directly push code to them.  We'd roll a train, and then create a branch off of it.  deploy that to testing servers.  QA would do some vetting of the test servers.  Pending approval, we'd route a %age of traffic to these new servers for 24 hours.  The %age shift would be a puppet controlled config param.

during the A/B period we'd have a fast rollback path to turn off the traffic routing.  The routing could be managed by code in router that selectively sets cookies on a portion of traffic.

that's a strawman stream of conciousness exploration, rife with issues...

**Comment by ozten** [comment]
Cool.

I think the main conclusion is:

a) let's ship KPI Dashboard and get some feedback loops going
b) leave this bug open to design an end to end A/B testing method (KPI will be affected among other components)

**Comment by jedp** [comment]
@kparlante is leading the charge on this and tracking elsewhere.  I've checked with her and she favors closing this bug.
