### ISSUE TITLE
error styles

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1062]
mock of the error window

http://cl.ly/1N2i212b1H47322F1525

Changes

CSS
background #FFE4D5;
text red;

COPY
- "To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below."
- "To retry, you will have to close this window and try again."

**Comment by shane-tomlinson** [comment]
@ozten - yo, are we good to start modifying strings again?

**Comment by ozten** [comment]
> yo, are we good to start modifying strings again?

We need to have a team meeting and decide on a release process around string freeze.

**Comment by ozten** [comment]
Can we take care of https://id.etherpad.mozilla.org/18 in this Issue?

**Comment by shane-tomlinson** [comment]
@ozten - I think we can take care of it concurrently, but should leave both issues open for tracking.

**Comment by jrgm** [comment]
verified chrome/FF/safari/opera osx, chrome/FF/opera/IE9 win7
