### ISSUE TITLE
Add new locales: Hebrew (he) and Hungarian (hu)

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1065]
@ozten: two more locales.

**Comment by ozten** [comment]
Updated on temporary_preview.

**Comment by ozten** [comment]
he is RTL and needs BIDI support, right?

Filing Issue#1066 for CSS support. Note l10n-bidi has all the bugs which affect RTL locales.

**Comment by mathjazz** [comment]
Indeed, it is RTL based, thanks for pointing this out and filing the issue.

**Comment by ozten** [comment]
he and hu enabled on temporary_preview, other Issues filed to track RTL work. Closing.

**Comment by mathjazz** [comment]
Only Hebrew is RTL, whereas Hungarian is LTR.

They are both at 0%.
