### ISSUE TITLE
 text baseline alignment of 'cancel' and 'reset password' are a little off on android 2.1 stock

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1072]
Minor nit followup to GH-1020 - the text baseline alignment of 'cancel' and 'reset password' are a little off on android 2.1 stock.

See http://img.skitch.com/20120208-dxpeany6gaqyqcs7ubkgn12c36.jpg

**Comment by shane-tomlinson** [comment]
Thanks @jrgm - fixed.

**Comment by jrgm** [comment]
verified. Looks aligned on either android 2.1 or desktop
