### ISSUE TITLE
silent assertions on domains with `_` in the name fail - JSChannel

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1074]
I came across this today while experimenting with the login DOM event for @skinny97214.  This only manifests itself when trying to get silent assertions.  

My test domains are named https://netflix_test_a.hacksign.in, https://netflix_test_b.hacksign.in.

When trying to get silent assertions on dom load, the __ready event would never correctly complete in the main page.  After doing some digging, I came to:

jschannel.js line 254 - the RegExp to match the origin does not allow for the `_` character.

The RegExp is:
`/^https?:\/\/(?:[-a-zA-Z0-9\.])+(?::\d+)?/`

I modified this to be
`/^https?:\/\/(?:[-a-zA-Z0-9_\.])+(?::\d+)?/`

Note the `_` before the `\.`

After giving this treatment to both include.js and jschannel.js, silent assertions were received on the test domains.

**Comment by lloyd** [comment]
this sucks, but do we really want a hotfix for it?  I'll fix in JSChannel and integrate into dev now.

**Comment by shane-tomlinson** [comment]
@jbonacci, @lloyd - I'd say no hotfix.  @lloyd, what do you think about @jbonacci's comment of other internationalized names?
