### ISSUE TITLE
Email/password should persist when creating new account

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#108]
If you enter an email/password in the login box and realize you don't have an account, pressing "Don't have a BrowserID yet?" shouldn't clear those fields. Instead, the contents should remain and the user should only need to fill in the "Verify" box.

**Comment by lloyd** [comment]
have a look at the current proposed UX iteration and weigh in here: http://lloyd.io/improving-browserid-ux

That proposal changes things.

**Comment by ghost** [comment]
There is still a case with the new UI where the email should persist:
1. Open https://diresworb.org/signup.
2. Enter an email address already associated to BrowserID.
3. Click on the "Verify email" button.
4. Click on the "sign in" link in the "<email> is already registered. Would you like to sign in instead?" message.

**Comment by ghost** [comment]
Verified on IE9 and Firefox 7.0.1 (Win 7).

The email address is now persisting with the steps from my previous comment.
