### ISSUE TITLE
*myfavoritebeer.org sites giving SSL security warning in Firefox

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1086]
All of the myfavoritebeer.org sites are giving an SSL security warning in Firefox.

**Comment by lloyd** [comment]
yeah yeah, ok, I'll buy another couple certs and move this all to AWS.

lloyd

**Comment by shane-tomlinson** [comment]
Dup of #751.  @jbonacci - this still happens on https://*myfavoritebeer.org

Closing this one in favor of #751.
