### ISSUE TITLE
The "Don't have a BrowserID yet?" link needs to be more visible

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#109]
To new users, the "Don't have a BrowserID yet?" link may be too small/difficult to find/ignorable. Perhaps it should be a button with the same gray as the Cancel button, positioned in the lower left.

**Comment by lloyd** [comment]
have a look at the current proposed UX iteration and weigh in here: http://lloyd.io/improving-browserid-ux

That proposal changes things.  Specifically, look at **Streamline first use**.  I'd love your thoughts.
