### ISSUE TITLE
provide a depressed, inactive state of the sign-in button

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1092]
Signal system state once the sign-in button has been depressed by ghosting it and making it unclickable.

**Comment by shane-tomlinson** [comment]
@skinny97214 - which sign in button is this for?

**Comment by skinny97214** [comment]
All button states are provide for in smartell's mocks. 
http://cl.ly/3t1Q020s1D0k2s2a3f2M

full image at
http://f.cl.ly/items/05000H292r113N2g3n3q/flow.png

The button I was referring to is the [sign in] in the popup.
