### ISSUE TITLE
buttons that could be potentially slow should have a spinner

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1093]
Especially for mobile, we need to signal that the button press was recorded.

**Comment by sawyerh** [comment]
@shane-tomlinson - I've added styles and a loader.gif asset, but wasn't sure what buttons this should be applied to or which .js file to implement that functionality in. All that really needs done is to apply a `loading` class to the `button`

https://github.com/sawyerh/browserid/commit/e7a3f0145e33987ff4f6a6db3efc65c528965339

**Comment by jrgm** [comment]
spinner looks good in train-2012.07.06 when applied with dev tools. Leaving this issue open to actually make use of it where appropriate.

**Comment by jrgm** [comment]
Okay, I've been using current dev with PR GH-2214 on multiple desktop browsers and I do see the spinner appear when clicking through buttons. I'll get to mobile later. Offhand, with a fast browser on a reasonable speed connection, it's a bit of a distraction, but I'll let other folks kick the tires, and see if they think the same.

**Comment by jrgm** [comment]
verified train-2012.08.17
