### ISSUE TITLE
[API] need logo of RP

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1098]
Using the logo of the RP in the popup assures users that they correctly clicked and are not being phished.

**Comment by ozten** [comment]
Existing sources of site logos:
- `<link rel="shortcut icon"` will often have a 48x48 pixel .ico file.
- [Open Web Apps Manifest](https://developer.mozilla.org/en/Apps/Manifest)
- [iOS Webapp Icon Support](https://developer.apple.com/library/ios/#DOCUMENTATION/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)

Android didn't have much official documentation, but supports iOS's method. 48x48 pixel png seems like the baseline.

It would be good to survey traditional some websites and apps in the wild and see what is available.

Notes: We should check a sites SSL cert. If invalid or the hostname doesn't match, then we **do not** show their logo and instead show a generic image.

**Comment by skinny97214** [comment]
If there's no image, we should just show the RP name as we do currently.

**Comment by ringe** [comment]
Maybe the /.well-known/browserid document could point to a logo as well?

**Comment by ozten** [comment]
`/.well-known/browserid` is only relevant to email providers (aka BrowserID Primaries).

We'll want customizing this logo to be available to websites (RP) as well as Primaries (IdP).

**Comment by skinny97214** [comment]
@lloyd What's the status of getting the logo of sites?

**Comment by skinny97214** [comment]
It could look something like this http://cl.ly/2j0o3i2e1T0p0Q401s1C

**Comment by jrgm** [comment]
verified for stage and awsbox train-2012.06.22 - either siteName or siteLogo or both can be speciifed, etc., and using siteLogo on a non-https RP will produce the "mproper usage of API: only https sites can specify a siteLogo" error in the dialog.
