### ISSUE TITLE
use flexible css to improve layout on tablets

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1101]
http://cl.ly/342G401g1b2l3t2G1Z3J

**Comment by skinny97214** [comment]
mock of tablet layout

http://cl.ly/0e3J0F2O3V1n0W1k3E0d

**Comment by jrgm** [comment]
(Closing this issue based on PR GH-1392 which is in train-2012.04.27)

Okay, so I've been using up-to-date versions of these OS/browser combinations:

OSX                    FF FF_Beta Chrome Opera Safari 
WinXP                  FF FF_Beta Chrome Opera Safari IE8 IE7 IE6
Win7                   FF FF_Beta Chrome Opera Safari IE9
Ubuntu                 FF FF_Beta Chrome Opera 
Android4.0/Nexus       FF10(XUL) Aurora Stock ChromeBeta 
Android4.0/Asus_Tablet FF10(XUL) Aurora Stock ChromeBeta 
Android2.3/Droid2      FF10(XUL) Aurora Stock 
IOS5/iPhone4s          Safari

Going through general usage and specific focus on @shane-tomlinson's notes to commit https://github.com/shane-tomlinson/browserid/commit/8329893507b1a2ed6b49d6ca39f52d2bc4a1fd01, I haven't had any major issues, but did note GH-1548 (which isn't a big deal). So, looks good to me but any other mobile device testing would be appreciated. Marking verified for stage train-2012.04.27 with the caveat that I'm a poor judge of UI/UX ;-)
