### ISSUE TITLE
Creating an email with a different case removes the old email

### ISSUE THREAD

**Issue by graingert** [mozilla/persona#1104]
Behavior:
having an existing email address:
user@example.com
then authenticating
User@example.com
causes user@example.com to be removed

Expected Behavior:
having an existing email address:
user@example.com
then authenticating
User@example.com
Should allow both emails to be selected at the email choice stage

**Comment by shane-tomlinson** [comment]
@graingert - Thanks for the feedback - in this case we made an explicit decision to stick with convention instead of the RFC.  The majority of email providers ignore case on both the local and domain portions of the address so we decided to do the same.

**Comment by graingert** [comment]
@shane-tomlinson That's the issue, you don't ignore case all the time.  Browserid's allows a user to authenticate a differently cased email.

It will initially treat them differently - it will send a new verification email, and it will then overwrite the old differently cased email. Meaning you can no longer use that email to sign in to other sites.

Things that need fixing:

1 BrowserID should say that "the user has already added that email" when the same email, differently cased is offered
2 BrowserID reference implementations for sites should ignore case when signing in (eg the django implementation)

A better solution would be to force lowercase throughout the stack.

**Comment by lloyd** [comment]
related to issue #2049

**Comment by lloyd** [comment]
@callahad TAKE A STAND MAN, tell use what approach we should apply and we will.

**Comment by callahad** [comment]
Oh jeebus, I'm assigned to this one? Will take a stand tomorrow.

**Comment by seanmonstar** [comment]
If this needs to be in beta1, take a stand and re-apply the tag. Otherwise, tossing this into beta2.

**Comment by lloyd** [comment]
+1

**Comment by shane-tomlinson** [comment]
Link to #1350

**Comment by csuciu** [comment]
Test case added https://moztrap.mozilla.org/manage/caseversion/23756/

**Comment by jaredhirsch** [comment]
fixed by #3078
