### ISSUE TITLE
Remove altering copy case via CSS

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1113]
As mentioned in https://github.com/mozilla/browserid/issues/1105#issuecomment-3960781

It's a best practice not to mess with changing the case of strings via CSS. Sounds like some buttons we force the case to all lowercase.

We should change to lower case in English by editing the po file. We should remove any CSS that alters copy in this way.

**Comment by mathjazz** [comment]
Thanks for opening this one, @ozten!

AFAIK, English already uses lowercase.

**Comment by shane-tomlinson** [comment]
@mathjazz, @ozten - Thanks for the tip and sorry for my ignorance here - Why is it considered bad form to force lowercase in CSS?

**Comment by mathjazz** [comment]
@shane-tomlinson No problem. Some locales don't like all-lowercase text in buttons etc. 

My suggestion: remove the text-transform: lowercase property from the CSS rule and use all-lowercase text in strings. That way most of the locales will still use all-lowercase text, but others will be able to change the case.

**Comment by jrgm** [comment]
verified.
