### ISSUE TITLE
gzip compress include.js

### ISSUE THREAD

**Issue by lookfirst** [mozilla/persona#1115]
This is a re-opening of #207 as it seems to have regressed. I'd expect a Content-Encoding header in there.

![foo](https://img.skitch.com/20120214-m32djuc5t577ehiu9bhjs2tnaf.jpg)

PageSpeed is reporting:

![bar](https://img.skitch.com/20120214-jpycsjme5hktcfx4quqt94ym6q.jpg)

Load of the FB js in the same session (showing correct headers):

![ack](https://img.skitch.com/20120214-etbdx2upm6p456w14ecb2nd9pp.jpg)

**Comment by lloyd** [comment]
nice find, @lookfirst.

@fetep, handle this at the nginx level? something like https://gist.github.com/1830700

**Comment by lloyd** [comment]
bump.  we should fix this, related to issue #1351

**Comment by lloyd** [comment]
this has not been forgotten.  

this fix should roll to production with `train-2012.04.27` - on or around may 9th.  see https://bugzilla.mozilla.org/749756

**Comment by lloyd** [comment]
verified.  done a while ago.
