### ISSUE TITLE
diresworb.org broken under zh_CN (/opt/browserid/resources/static/production/zh_CN/browserid.js)

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1119]
Duplicated in FF10(OSX), IE9(Win7), Chrome16(Win7,OSX).

1) Set the browser language preference for zh-CN. (In Chrome, pick Simplified
   Chinese which will be zh-CN).

2) Load https//diresworb.org

Results:

IE9:
  SCRIPT1009: Expected '}'
  browserid.js, line 9 character 11473

FF10:
  Error: missing } after function body
  Source File: https://diresworb.org/production/zh_CN/browserid.js
  Line: 9, Column: 11472
  Source Code: ...

Chrome16:
  Uncaught SyntaxError: Unexpected end of input

And the page doesn't function as it should.

The file (as downloaded by FF10 as to have a few Chinese characters mangled and replace by I think 0xfffd, and the file is missing  6 characters at the end 'n u}()'. The browserid.long on the server claims to have sent the number of bytes in the file, and the Content-Length header says 276354

**Comment by jrgm** [comment]
ah, this is just https://github.com/mozilla/browserid/issues/1057

**Comment by ozten** [comment]
Good call.

**Comment by jrgm** [comment]
closing as duplicate of GH-1057, duh.
