### ISSUE TITLE
mixed content cause YouTube video

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#112]
https://browserid.org/users

**Comment by lloyd** [comment]
we could locally host the video and use HTML5 to render it, but some people would be alienated.  The fallback html could be just a plain ol' link over to the video on youtube?

**Comment by shane-tomlinson** [comment]
I have changed the Youtube request to be https, issuing pull request momentarily.

**Comment by shane-tomlinson** [comment]
Pull request is issue #113
