### ISSUE TITLE
Locale: [any/all] The error dialog is only partially translated

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1122]
The error dialog is only partially translated. E.g. for French: 
"We are very sorry, there has been an error!

To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below.

Action: Établissement de relais

Le relais n'a pu être trouvé

BrowserID est un moyen rapide et sûr de s'identifier — en apprendre plus"

This issue reproduces no matter what the error is. Might be related to bug #1085

**Comment by shane-tomlinson** [comment]
This is by design, anything that is shown when the user opens the "see more information" button should be in English.
