### ISSUE TITLE
When the user has 2 email addresses, he can cancel his BID account by removing the same address twice

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1123]
OS: Windows 7
Browser: Firefox 11.0

STR:
1. Open https://diresworb.org/ in the browser.
2. Sign in with an account that has 2 email addresses associated to it.
3. Leave the page open on the Account Manager page.
4.  Open https://diresworb.org/ in another tab of the browser (the user may have multiple tabs and groups of tabs open so he might forget he already opened the page).
5. Remove the 2nd email address from this account and close the tab you removed it from.
6. Go to the diresworb.org tab that remained open. Don't reload it.
7. Try to remove the same email.

The following error message is displayed:
"Removing the last address will cancel your BrowserID account.
Are you sure you want to continue?"

If the user doesn't pay enough attention to the message and clicks "OK", his BID account is canceled although he never selected to remove the first email address associated to the account.

This issue only reproduces when the user has exactly 2 email addresses associated to BID.

**Comment by jrgm** [comment]
verified fixed in stage on train-2012.04.11 chrome/osx, FF/osx, ie9/win7, ie8/winxp
