### ISSUE TITLE
Locale: [any/all] The "The selected email is invalid or has been deleted" message is not localized

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1124]
OS: Windows 7
Browser: Firefox 11.0

STR:
1. Open a BID client in the browser.
2. Sign in with an account that has multiple email addresses associated to it.
3. Leave the BID dialog open on the emails list.
4. From the main site (https://diresworb.org/), remove an email address associated to the account from step 2.
5. Return to the BID dialog with the emails list.
6. Select the removed email and click the Sign In button.

The "The selected email is invalid or has been deleted" message is not localized.

**Comment by ghost** [comment]
The screen shot with this issue reproducing: http://bit.ly/wpgfof

**Comment by ozten** [comment]
Found missed string. Wrapped in gettext:
http://git.io/CQGBTg

**Comment by jrgm** [comment]
The string is localizable in train-2012.03.14, but waiting on its translation on many languages (e.g., nl, fr, es, de...).
