### ISSUE TITLE
Locale: [sv, sr] The diresworb.org home page displayed both the Account Manager section and the "Connect with BrowserID..." section 

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1125]
OS: Windows 7
Browser: Firefox 11.0, IE9
Language: Swedish

STR:
1. Load https://diresworb.org/ in the browser.

The diresworb.org home page displayed both the Account Manager section and the "Connect with BrowserID..." section when in Swedish. This issue didn't reproduce with French nor with English. http://bit.ly/wzqDHq

**Comment by ghost** [comment]
This issue also reproduces when the language is set to Serbian.

**Comment by ozten** [comment]
That environment is missing some JavaScript build files.

Although 'sv' is enabled,  https://diresworb.org/production/sv/dialog.js
 is 404.

@fetep - Any ideas?

SV looks good on the auto-updating environment:
http://temporary_preview.myfavoritebeer.org/

**Comment by jrgm** [comment]
Serbian (sr) does exist on the webheads and does download, but there is a javascript error (and that is the same as GH-1057)

**Comment by ozten** [comment]
Dup 1057
