### ISSUE TITLE
iOS - must click on radio button to select email address.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1133]
Expected - should be able to click the email address to select the radio button.

**Comment by tonychung** [comment]
i'm still experiencing this issue.   I have not been able to click on any of the email addresses to get the selection.  The highlight on the address shows, but no radio selected.

iOS 5.1, iphone 4.
tested on beta.myfavoritebeer.org and beta.myfavoritebooze.org

**Comment by tonychung** [comment]
reopening for investigation

**Comment by jrgm** [comment]
Yeah, it's flaky for me. One thing I've found is that if you are very careful to click at the very far left of the radio, it will work.

**Comment by jrgm** [comment]
My results are android 2.2 (Droid2) and 4.0 (Nexus), for ff 10-13, and stock browser.

**Comment by nhirata** [comment]
I can reproduce the issue that tchung saw with just two email addresses.
nh.test.002@gmail.com, nh.test.004@gmail.com; I can give you the password on request.

**Comment by shane-tomlinson** [comment]
@tonychung - can you create a screen cast of this?  I am unable to reproduce on an iOS 5.1 device for an account with a mix of gmail and mozilla addresses.

**Comment by shane-tomlinson** [comment]
@tonychung - Can you confirm that non-clickable addresses in gmail contain the + or some other non-alpha numeric character?

**Comment by shane-tomlinson** [comment]
Checkin 80e3ddb is against the wrong branch.  72ac85f is against origin/train-2012.03.01

**Comment by tonychung** [comment]
@shane-tomlinson, my gmail account does not contain any +'s or special characters.   At the same time, i can click my gmail address's name and it will select the radio.  Maybe because its sitting 4 spots down, near the TOC and privacy?   

Screencast of issue:  http://youtu.be/_b3DTiN4Bus
