### ISSUE TITLE
"frozen" error dialog shown on error in account manager page.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1139]
This can be reproduced based on @ioanab's STR in GH-1123. This bug, though, is
just about the error dialog. (Reproduced in FF10/OSX, Chrome16/Win7,
IE9/Win7).

1) have an account with two non-primary email addresses on it.
2) open two browser windows and load https://diresworb.org in each.
3) in window #1 remove email address #1
4) in window #2 remove email address #2 (which will cancel the browserid account).
5) Back in window #1 remove email address #2, which is still shown there.

An error dialog is now shown:
  "We are very sorry, there has been an error!
   To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below.
   <a>See more info</a>"

![img](https://img.skitch.com/20120216-psdybh5h7dffrfpfefyngna7t6.png)

Clicking on the link 'See more info' does nothing. There is no way to dismiss
the dialog and return to the page. (Or is this intentional beaviour? Even if
it is intentional to "lock" the user out of the page, the moreInfo link should
work as advertised.)

The text in the DOM for moreInfo (that the user cannot get to) is:
  "Network Info: POST: /wsapi/account_cancel
   Response Code - error
   Response Text: Bad Request: requires authentication
   Error Type: Bad Request"

**Comment by shane-tomlinson** [comment]
@jrgm - thanks for finding this.  When the error screen is displayed, the user cannot close just it but must reload the entire window/tab.

**Comment by stomlinson** [comment]
Easy test case:

1) Load up Firefox
2) Go to https://dev.diresworb.org/signin
3) Select "Work Offline"
4) Enter your email address and type "enter"
5) When error screen opens, click "See more info"

**Comment by ghost** [comment]
Verified as fixed on Dev using Firefox 11.0 + Windows XP. The issue still reproduces on Stage but I suppose the fixed hasn't gotten there yet. Please let me know if I'm wrong.

**Comment by jrgm** [comment]
fix is verified on stage train-2012.03.03
