### ISSUE TITLE
add ability to change password

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#114]

**Comment by lloyd** [comment]
reassigned to @shane-tomlinson

we need some UX feedback here.

**Comment by skinny97214** [comment]
We'll need to re-auth. This form has old pass/new pass. I'm omitting the confirm password field.

http://cl.ly/1N2G2a2K1l143F0j1F1e
http://cl.ly/0l3Q0j3N3x381T3D2b3i

**Comment by shane-tomlinson** [comment]
@lloyd - update_password is returning "success: true" no matter what the oldpass is.  Bad jiji.

POST:

```
csrf    f588271cf2aa2228afaa82ad96d0f511
newpass newpassword
oldpass jibberish
```

RESPONSE:

```
{"success":true}
```

POST:

```
csrf    f588271cf2aa2228afaa82ad96d0f511
newpass anothernewpass
oldpass morejibberish
```

RESPONSE:

```
{"success":true}
```

**Comment by shane-tomlinson** [comment]
Reopening, passing to @lloyd for above comment - https://github.com/mozilla/browserid/issues/114#issuecomment-3216307

**Comment by ghost** [comment]
Verified on Windows XP + IE8.

When there are multiple email addresses associated to a BID account, only the email address used to reset the password is kept after changing the password from the a client.

**Comment by ghost** [comment]
Verified as fixed on Windows XP + IE8 when using the manage page.
