### ISSUE TITLE
Customize Login Error if Primary is not available

### ISSUE THREAD

**Issue by ibai** [mozilla/persona#1140]
In the login process UI it's important to point to the user to the failure point.

Once primaries are implemented, if a user tries to log in with one that is not available (i.e. Gmail is down), we should prompt them with a message explaining that they should check their Identity provider: For example: "Your Identity provider is not responding so we can't grant you access to this site. Try with other of your identities or contact Gmail's support for more information".

Some UX input will be welcome here.

**Comment by benadida** [comment]
two cases:
- host unreachable
- host reachable but buggy JS in provisioning/authentication

@skinny97214 can you think through error message in both cases?

**Comment by skinny97214** [comment]
What should the user do? Wait and try again?

**Comment by shane-tomlinson** [comment]
One of the many cases dealing with primaries.

Link to #1039.  Adding beta-2 req.

**Comment by shane-tomlinson** [comment]
This has been taken care of by @ozten, @seanmonstar and @lloyd as part of the BigTent push. Closing.
