### ISSUE TITLE
Static resources should not generate 304s in server logs

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1141]
With Issue 620, we've improved our caching for static assets.

Unfortunately, UA still check to see if a resource is up to date, generating a 304 response.

per @lloyd - for js/css resources, don't sent ETag or Last-Modified (should fix upstream)

Actual: /produciton/en-US/dialog.js 304 in firebug / node server logs

Expected: No HTTP traffic for this resource after first 200 request.

**Comment by lloyd** [comment]
I was wrong on this.  I now believe ETag and Last-Modified should be served even with long future expiration.  mea culpa.

The case that this improves is bytes transfered on a normal (non-force) refresh.  when ETag is present, the client will revalidate rather than refetching.

**Comment by ozten** [comment]
Dev should pick this up, I've bumbed package.json to cachify 0.0.7.

**Comment by jrgm** [comment]
I went through the http logs on web{1,2,3} in stage, and the content is correctly served with Etag, Date, and Cache-Control
of one year for the perma-url resources /v/<md5sum>/....(css|js). So verified. 

HTTP/1.1 200 OK
Vary: Accept-Encoding,Accept-Language
Cache-Control: public, max-age=31536000
Content-Type: application/javascript
Strict-Transport-Security: max-age=2592000; includeSubdomains
Date: Tue, 06 Mar 2012 23:01:04 GMT
Accept-Ranges: bytes
Etag: "284043-1331058798000"
Connection: keep-alive
X-Frame-Options: DENY
Last-Modified: Tue, 06 Mar 2012 18:33:18 GMT
Content-Length: 284043

However, despite 'Cache-Control: public, max-age=31536000' both IE8/winxp and IE9/win7 revalidate the URL every time the /sign_in dialog is opened. I will open that as a separate issue.
