### ISSUE TITLE
stage env for train-2012.02.16 not working

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1142]
stage seems broken. Can't sign up a user -- 
  CSRF validation failure, token mismatch. got:eDNOlcM3XYzpKyt6fgbQjQ== want:qKZrkhFABWWNt1BRAZ0W0w==

Two different browsers, multiple tries.

**Comment by lloyd** [comment]
tl;dr; looks like code isn't fully deployed on stage - passing off to @fetep

**Comment by lloyd** [comment]
resolved.  this was a deployment issue.
