### ISSUE TITLE
Default email displayed should be the same email as authenticated email

### ISSUE THREAD

**Issue by chrismore** [mozilla/persona#1146]
Description:

When logging into a site using BrowserID and you don't have an active session open with BrowserID, you have to enter an email address and password. After you authenticate on BrowserID, you are presented a list of email addresses that you registered with BrowserID.

Expected:

After authenticating on BrowserID on a website using it, the radio button should be auto selecting the email address matching the website you typed in to first authenticated.

Actual:

If you do not have an active BrowserID session, the radio button defaults to the email first in the list.

BrowserID does remember the email you logged in on with a given website, but it does not remember it the first time you authenticated on a website using BrowserID. If you do not have an active BrowserID session, it should default to the email address you used when first authenticating since the user will more likely know the email address associated with the site they are about to use.

**Comment by shane-tomlinson** [comment]
Thanks for the feedback @chrismore - we are going one step further than this in issue #198.  With this change (once merged - see pull request 1162 - https://github.com/mozilla/browserid/pull/1162) we will skip the "email picker" screen and log the user in to the RP directly.

Thanks again!

Closing as superseded by issue #198.
