### ISSUE TITLE
on cancel account, clear up the UI

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#115]
canceling a cancel action is weird.

**Comment by AndrewBarrettCa** [comment]
I agree. At https://browserid.org/manage clicking the "cancel your account" link results in the prompt "Are you sure you want to cancel your account?" with options "Cancel" and "OK". This results in an odd situation: If you _don't_ want to cancel your account then you need to press "cancel". Perhaps, the link and the prompt should replace the word "cancel" with "delete" but keep the "Cancel" and "OK" options.

**Comment by benadida** [comment]
duplicate bug, 122. closing.
