### ISSUE TITLE
Logging in to myfavoriteshow.org with an already registered e-mail address when logged in with another triggers a verification email

### ISSUE THREAD

**Issue by davidillsley** [mozilla/persona#1150]
Logging in to myfavoriteshow.org with an already registered e-mail address when logged in with another triggers a verification email, and hence fails to log me in.

Specifically, if I'm logged in to browserid.org as davidillsley@eyedee.me and enter david@illsley.org on http://myfavoriteshow.org/ I get a pop-up with a fixed e-mail address of david@illsley.org with a verify email button which sends an e-mail.

While I'm probably unusual in having separate, non-linked browserids, this is a flow which would be seen on a shared computer where e.g. different family members have different browserids and someone may be left logged in.

**Comment by davidillsley** [comment]
Thinking about it, it's a pretty confusing experience in the case that someone mis-typed their e-mail address

**Comment by shane-tomlinson** [comment]
@davidillsley - Thanks for the input here David.  The behavior we have now is "as design" though I agree with you that the behavior is confusing.

Other reference issues (order of relevance):
https://github.com/mozilla/browserid/issues/814
https://github.com/mozilla/browserid/issues/607
https://github.com/mozilla/browserid/issues/669

**Comment by davidillsley** [comment]
Kinda... but not really... the issue was about the UX of requriedEmail, rather than of myfavoriteshow.org specifically.
