### ISSUE TITLE
To retry, try again

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1154]
These two strings should be changed probably.
# : resources/static/dialog/views/error.ejs:18

msgid "To retry, you will have to reload the page and try again."
# : resources/static/dialog/views/error.ejs:20

msgid "To retry, you will have to close this window and try again."

/cc @ozten, @skinny97214

**Comment by ozten** [comment]
Changed how? Make them the same string?

@shane-tomlinson do these serve two different purposes?

**Comment by ozten** [comment]
Ah from dev-l10n-web Julen Ruiz Aizpuru says:

Hi,

I have some doubts regarding two strings:

"To retry, you will have to close this window and try again."
"To retry, you will have to reload the page and try again."

From my understanding, "retry" and "try again" means the same thing,
so unless the context is shown (which is not) I'm not sure what does
this exactly mean.

Any hints?

**Comment by mathjazz** [comment]
No no, it sounds kind of funny, doesn't it?

Retry and try again is the same thing.

**Comment by shane-tomlinson** [comment]
@ozten, @mathjazz - These strings DO serve different purposes - "close the window" is used for errors within the dialog, "reload the page" is for errors within the main site.

Better copy needed yes, but I think we should keep two distinct strings.

**Comment by mathjazz** [comment]
Absolutely, these are two different things.

I was talking about using "to retry" and "try again" in the same sentence.

**Comment by shane-tomlinson** [comment]
See bug #1167, closing as duplicate.

**Comment by shane-tomlinson** [comment]
"To retry, ... try again" is shown in all the error messages _except_ the cookies disabled message.  Because of this, reopening this issue.

**Comment by lloyd** [comment]
merged.
