### ISSUE TITLE
Failing front end test 'controllers/pick_email: click on an email label - select corresponding radio button'

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1156]
This only fails when running all tests - running a subset does not cause the problem to manifest.

**Comment by jrgm** [comment]
verified on train-2012.03.01 in IE8, IE9, Opera, Safari, FF Beta and Nightly on Android 4, FF11, Chrome. IE8 had 3 failures
where JS took longer that tolerated by the test, and FF Beta has one failure due to clock skew of the device.
