### ISSUE TITLE
FF Mobile Beta (11.0) on droid2(2.2) cannot signin on myfavoritebeer or myfavoritebooze

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1169]
This is very specific to FF 11.0 (the final XUL mobile version) and perhaps this particular motorola/verizon droid2 android 2.2; I don't have another android to test with (loaned for MWC)).

STR:
1) load beta.myfavoritebeer.org or myfavoritebeer.org (or s/beer/booze/)
2) touch 'Sign in' button

Expected: 
Window for /sign_in comes up

Actual:
'Sign in' button jumps up towards left and top, and then back to original position in disabled style. No /sign_in window is shown. 

This works fine with FF10 mobile on the same droid2(2.2), and with the stock browser. (The native aurora and nightly are unusable for anything on this phone, which is not this issue).

Nothing obvious in adb logcat while trying this (but there is a warning for "Unknown property 'box-sizing'.  Declaration dropped" which usually shouldn't matter. No JS errors or other telltales.)

**Comment by benadida** [comment]
we think this is fixed: check and close.
