### ISSUE TITLE
review cookie-sessions

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#117]
the cookie value is encrypted, but not authenticated, so need to explore potential issues there.

**Comment by benadida** [comment]
moving to connect-cookie-session, this should be better.

**Comment by benadida** [comment]
reviewing connect-cookie-session:
- not super happy about overriding of res.writeHead, seems unnecessary. Why not just setHeader?
- cookie is signed, but not encrypted. For now, this isn't a serious problem, but it might eventually become a problem if our code forgets this assumption. Move to encrypted?
- no tests :(
- no logging when invalid signature on cookie.

**Comment by tj** [comment]
I'd like to get a cookie store back in Connect core at some time too, I'll let you know if/when that happens. It took quite a while for node to get a header manipulation API, core ppl didn't think we needed it so the writeHead thing might have been due to that old limitation.

**Comment by benadida** [comment]
added some tests that pound on connect-cookie-session a bit in 7e99da8faa173f8cb27545f0717a44c7545b7e1d

added issue #416 to track cookie encryption.

As for this issue, I believe it is good to go, I'm happy with this module.
