### ISSUE TITLE
Make client.pot & messages.pot empty file at the beginning of extract_po.sh

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1170]
When I extract new strings using extract_po.sh, I get different POTs generated if I leave existing POTs in the templates directory than if I empty the old POTs.

The difference is that strings that we remove for the new releae don't get removed from the POT if I keep the old POTs, but they do get removed if I empty the POTs before running extract_po.sh. So what I do now is every time before I run extract_po.sh, I empty messages.pot and client.pot in the templates folder.

See: https://github.com/mozilla/browserid/issues/1132#issuecomment-4053122

@ozten

**Comment by lloyd** [comment]
4stars, @ozten, please advise

**Comment by ozten** [comment]
https://github.com/mozilla/browserid/pull/1194

**Comment by ozten** [comment]
@mathjazz this was merged. Let me know if you have any issues with it.

**Comment by mathjazz** [comment]
Works great, thanks!
