### ISSUE TITLE
Passwords larger than 80 chars can be used all through BID

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1173]
OS: Windows XP
Browser: Fx 11.0

STR:
1. Load a BID sign in/up page in a browser (any dev, stage or prod server page or BID dialog).
2. Sign up with an email address and set as password a string longer than 80 chars.
3. Sign in with the account with the password longer than 80 chars.
4. Change the password though the Forgot Password feature. Set a new password longer than 80 chars.
5. Change the password from the Account Manager page. Set a new password longer than 80 chars.

Although the user should not be allowed to use passwords larger than 80 chars, he can do that in all the BID windows/dialogs where the option of entering a password exists.

**Comment by shane-tomlinson** [comment]
@ioanab - Several things to be aware of:
1) The password fields have a maxlength=80, so unless people are removing this attribute manually, the browser will stop them from typing extra characters without giving them any hint that they have reached the end.  If this happens, only 80 characters will be in the input field.
2) The password max length check is only done when the user sets a password, NOT when a user enters a password for authentication.  
3) The only check that is done when a user enters a password to authenticate is to make sure the user typed A password. If the user DOES remove the maxlength attribute while authenticating, I think we should just tell them "can't log in with those credentials."

I am going through each of the "set your password" flows and manually setting the passwords to be 81 characters.  All of these are done on Firefox 11/OSX.

1) Manage page - shows a tooltip, does not allow form submission.
2) Forgot password verification page - shows a tooltip, does not allow form submission.
3) Sign up verification page - Same as #2, it is the same page/same code
4) Verification for add a secondary email to an account with only primary addresses - shows a tooltip, does not allow form submission.

Adding pull request 1175 for extra checks in verify_email_address.
https://github.com/mozilla/browserid/pull/1175

**Comment by lloyd** [comment]
fringe case, we'll address this when we revisit user feedback during password selection GH-755

**Comment by jrgm** [comment]
verified shane's notes above in chrome adjusting the dom
