### ISSUE TITLE
wsapi/set_key failing with "attempt to write to readonly database"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#118]
https://browserid.org/wsapi/set_key

POST info:

csrf    282f6f5c5f531779ee689131d6e5a09b
email   set117@yahoo.com
pubkey  -----BEGIN PUBLIC KEY----- MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL8UjJ3AXNHf+puuJM44kwNrVwkjHsyW WuZJOjjQRHFWALnYaGy5AQ1w22xYdq4CDWX8p9Zvv+s60/rOb7lLWuECAwEAAQ== -----END PUBLIC KEY-----

RESPONSE:

{"stack":"Error: attempt to write a readonly database","message":"attempt to write a readonly database"}

BUT - the HTTP status code is "200 OK" and it thinks everything is fine.

**Comment by shane-tomlinson** [comment]
Steps to reproduce:

1) Open a browserid login dialog
2) Logout
3) Log back in - in the browserid login dialog, open firebug or similar - check out your wsapi/set_key requests.

**Comment by lloyd** [comment]
should be fixed now.  I "improved" deployment on the production machine as part of todays push.  in the process I neglected to give user/group www-data write access to the database.  

@shane-tomlinson: please confirm the issue is fixed for you!

**Comment by stomlinson** [comment]
@lloyd - this is now fixed for me, thanks for the update!
