### ISSUE TITLE
figure out strategy for iOS 5 reject all cookies

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1181]

**Comment by shane-tomlinson** [comment]
Some light reading:
http://support.apple.com/kb/HT1677

The second two are complaints:
https://discussions.apple.com/thread/3566208?start=0&tstart=0
https://discussions.apple.com/thread/3551205?start=0&tstart=0

Do this search:
https://www.google.com/search?hl=en&client=firefox-a&rls=org.mozilla%3Aen-US%3Aofficial&q=site%3Aapple.com+ios5+cookies+never&oq=site%3Aapple.com+ios5+cookies+never&aq=f&aqi=&aql=&gs_sm=3&gs_upl=42033l42033l0l42509l1l1l0l0l0l0l264l264l2-1l1l0

**Comment by benadida** [comment]
reached out to folks for contacts at Apple to understand if this is a bug or feature

**Comment by benadida** [comment]
appears to be a bug, looking for more info on timeline.

**Comment by benadida** [comment]
so far, our contacts are telling us there is no estimated fix date as the problem does not appear to be clearly reproducible. No clear workaround exists, either.

**Comment by benadida** [comment]
we have a SUMO article for this: 

https://support.mozilla.org/en-US/kb/how-enable-cookies-iphone/revision/22356

can't figure out what conditions cause this specifically, so hard to report to Apple. Moving this to 4-star

**Comment by seanmonstar** [comment]
Is this still an issue? We have the SUMO link in if cookies are disabled and on iOS, right?

**Comment by lloyd** [comment]
nothing to be done here.  closing
