### ISSUE TITLE
Error UI instead of Login Screen  with raiseAuthenticationFailure

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1182]
As reported in http://groups.google.com/group/mozilla.dev.identity/browse_thread/thread/ea00cf0bac16b1ca# 
`navigator.id.raiseAuthenticationFailure` doesn't show the login screen.

http://skitch.com/oztenskitch/8rey2/error-on-success

Steps to reproduce:
0) https://vinz.clortho.org/browserid/ - accept SSL cert exception
1) Make sure you don't have a session with https://vinz.clortho.org (clear cookies)
2) http://dev.myfavoritebeer.org/ click Sign in
3) Enter any username @vinz.clortho.org

Example: ozten@vinz.clortho.org

Actual: Error screen (see skitch)

Expected: Login screen

All three urls work properly:
- https://vinz.clortho.org/.well-known/browserid
- https://vinz.clortho.org/browserid/provision
- https://vinz.clortho.org/browserid/sign_in

**Comment by ozten** [comment]
To Repro locally:
https://github.com/ozten/vinz-clortho

**Comment by ozten** [comment]
Through much head desking I've found the root cause:

raiseAuthenticationFailure cannot be used with arbitrary error messages. 
https://github.com/mozilla/browserid/blob/dev/resources/static/shared/user.js#L450

Both http://browserid-i5y.herokuapp.com/browserid/provision and my IdP treat this like a place to accept an arbitrary string:

herokuapp should change `fail('need to sign in');` to `fail('user is not authenticated as target user');`

**Comment by ozten** [comment]
Should the dialog be more lenient?

Should have an enumeration of error codes?

Other ideas?

**Comment by davidillsley** [comment]
Interesting. What are the other valid codes?

**Comment by shane-tomlinson** [comment]
@ozten, @davidillsley - I feel we should not make our policy more lenient but instead should enumerate possible error codes and define the expected outcome for each.  Any error codes that do not fit into the scheme are treated as unknown and the error screen should be shown.

At the moment the only accepted error code that does anything meaningful is "user is not authenticated as target user" - which will return the user back to the "authentication" screen allowing them to enter in a new email address.

**Comment by ozten** [comment]
It feels too verbose and suggests programmer input, instead of something that is part of a standard.

I've updated [the spec](https://wiki.mozilla.org/Identity/BrowserID#Certifying_Users), but I suggest we use something shorter like

`WRONG_USER` or `AUTHED_UNKNOWN`

/cc @benadida  to review my addition to the spec.

**Comment by davidillsley** [comment]
I agree with both of you, though if we're not aware of other imminent error codes, why not remove the param completely for the moment?

**Comment by ozten** [comment]
Filed Issue 1207 to refine this API.
