### ISSUE TITLE
Almost identical strings

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1188]
As pointed out by localizers, these two strings are almost identical:

resources/static/dialog/views/offline.ejs:9
We are sorry, but we cannot communicate with BrowserID while you are offline.

resources/static/shared/error-messages.js:83
Unfortunately, BrowserID cannot communicate while offline!

I think we should pick (the first) one and use it everywhere.

**Comment by shane-tomlinson** [comment]
@mathjazz - @lloyd actually disconnected the "offline" check quite a while back, this code should probably be removed all together.  Let me make sure this is the case, and if so, I'll do a pull request.  If the check is still active, I will combine the strings.

**Comment by lloyd** [comment]
looks fixed!  please test

**Comment by jrgm** [comment]
looks gone to me
