### ISSUE TITLE
logout all devices from all websites

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1196]
Building the remember-this-computer feature necessitates us being able to un-remember it. Here's first cut at nuking all saved devices. Once the user logs back in from that device, they should be reprompted with "is this your computer" so they can save it again.

 http://cl.ly/2B1P1N43252v0t270c2s

**Comment by jaredhirsch** [comment]
@skinny97214 do we still want to try to implement this feature? was #1400 maybe deciding we don't? if we don't want it, let's close and reduce that bug count ^_^

**Comment by skinny97214** [comment]
Closing. #1400 resolved.
