### ISSUE TITLE
Port blobastorus to browserid

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#12]
blobastorus is a perfect candidate for a hack that would be better with improved authentication.  We should port it to browserid.

**Comment by toolness** [comment]
+1!!!!!!!!!!

**Comment by toolness** [comment]
Sorry, that comment probably wasn't very helpful.

**Comment by lloyd** [comment]
I don't know that there is anything _more_ helpful than enthusiasm.  Friday is a good day to hack on this!

**Comment by lloyd** [comment]
ok, this needs to get done because it would be awesome, but doesn't belong here as an issue.
