### ISSUE TITLE
BrowserID becomes unresponsive when trying to use it in Firefox with all the cookies disabled

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1200]
OS: Windows 7
Browser: Firefox 11.0 (beta 4), Firefox 13.0 (Nightly)

In other browsers (e.g. IE9, Opera 11.61), either the "We are sorry, BrowserID requires cookies" dialog or an error dialog with the Response Text "Forbidden: no cookie" are opened when trying to perform different actions on BID with all the cookies disabled. The following happens in Firefox:

Case 1:
1. Disable all the cookies.
2. Try to sign in/up on diresworb.org.

When the user tries to sign in/up from the server, the email is removed from the textbox and then nothing else happens.

Case 2:
1. Sign in on diresworb.org.
2. Disable all the cookies.
3. Try to remove an email or cancel the account.
4. Try to sign out or change the password.

At step 3, the buttons (and link) are unresponsive.
At step 4, an error message is displayed but the "See more info" link on it is unresponsive.

Case 3:
1. Disable all the cookies.
2. Try to sign in/up from a client/RP.

The "Communicating with server" dialog is opened and it stays like that until the user enables cookies and reopens the dialog.

Case 4:
1. Open a BrowserID client/RP and sign in . Leave the dialog open on the emails list.
2. Disable all the cookies.
3. Select an email an try to sign in.

The Sign In button is unresponsive.

**Comment by lloyd** [comment]
fixed in stage. see GH-835
