### ISSUE TITLE
Only the headers and footers of most diresworb.org pages are displayed when opening them in Chrome with all the cookies disabled

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1202]
OS: Windows 7
Browser: Chrome 17.0.963.56

STR:
1. Disable all the cookies (the issue doesn't reproduce when only 3d party cookies are disabled).
2. Load https://diresworb.org/ in the browser.

Only the headers and footers of all the diresworb.org pages are displayed, except for the Sign In page. This issue doesn't reproduce on other browsers (tried IE9, Fx11 and 13, Opera 11.61).

**Comment by lloyd** [comment]
still an issue despite fix for GH-835

**Comment by jrgm** [comment]
Specifically for chrome, marking verified for stage train-2012.04.11 (but issues remain in GH-1418 (all), GH-1484 (chrome)). 
More detailed summary will be in GH-1201.
