### ISSUE TITLE
The "We are very sorry, there has been an error!" message with an unresponsive "See more info" link is displayed in several cases when all the cookies are disabled in the browser

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1203]
OS: Windows 7
Browser: Chrome 17.0.963.56, IE9, Opera 11.61

The "We are very sorry, there has been an error!" message with an unresponsive "See more info" link is displayed in several cases when all the cookies are disabled in the browser:

Case 1:
1. Disable all the cookies in the browser.
2. Load https://diresworb.org/signin in the browser.
3. Enter an email address associated to BID and click on the "Sign In" button.
4. Enter a password and sign in.

Case 2:
1. Disable all the cookies in the browser.
2. Load https://diresworb.org/signup in the browser.
3. Enter an email address not associated to BID yet and click on the "Verify email" button.

Case 3:
1. Disable all the cookies in the browser.
2. Load https://diresworb.org/signin in the browser.
3. Enter an email address associated to BID and click on the "Sign In" button.
4. Click on the "forgot your password?" link.
5. Click on the Reset Password button.

Case 4:
1. Load https://diresworb.org/signin in the browser.
2. Sign in with a BID account.
3. Disable all the cookies in the browser.
4. Try to perform any action (remove email, cancel account, sign out, change password).

All these cases reproduce on IE9 and Opera 11.61 but only the first one reproduces on Chrome too (because of issue 1202).

**Comment by lloyd** [comment]
fixed in stage.  see GH-835
