### ISSUE TITLE
Include.js returns a 304 even though it takes a while to load

### ISSUE THREAD

**Issue by Marlena** [mozilla/persona#1204]
Steps to reproduce:
1. open firefox
2. go to http://addons-dev.allizom.org
3. log in with BrowserID/Persona
4. open Firebug or something else that will show server responses
5. In the header, click on username -> my profile

The call for include.js is returning a 304 error code which indicates it's pulling information from cache.  It doesn't seem to matter if the cache has been cleared, it always returns a 304.  This should be returning a 200 unless it actually is getting information from the cache.

Here is a screenshot:
https://skitch.com/e-marlenac/8fftq/browserid-homepage-viewprofile

**Comment by jrgm** [comment]
In the screenshot https://skitch.com/e-marlenac/8fftq/browserid-homepage-viewprofile note that the color is green which
is 'Connection - elapsed time required to create a TCP connection' per Jan Odvarko - http://www.softwareishard.com/blog/firebug/introduction-to-firebug-net-panel/

So, this time appears to be all in negotiating the socket connection. Which is odd. 

What does `sudo tcpdump -i en1 host 63.245.209.246` say when you do this again in the browser.

**Comment by jrgm** [comment]
@Marlena and I went through this a bit today. 
- @Marlena's test account with addons-dev is quite sluggish, and I was thinking that was maybe the explanation
- but couldn't explain the firebug images, so I looked how chrome/firefox behave if browserid.org/include.js is sluggish (with ipfw induced high latency), and I could reproduce the same firebug views (and the chrome dev tools equivalent).

So, @Marlena's test account aside, I think that there are some transient network issues that are at root of this issue (perhaps only on the internal/test networks). 

Note: I think @Marlena and I ruled out that this is anything like network routes/vpns, browser versions, addons, etc. today

**Comment by lloyd** [comment]
@fetep what do stats look like for the last month on include.js in terms of min/max/avg latency?

**Comment by lloyd** [comment]
http://people.mozilla.com/~petef/includejs.png

that's an average from geographically dispursed clients

If you can reliably reproduce this issue, please reopen.  Given that our monitoring has seen acceptable response times worldwide over the last month, I'm closing this down.
