### ISSUE TITLE
BrowserID dialog does not use the mobile layout

### ISSUE THREAD

**Issue by st3fan** [mozilla/persona#1210]
We run the BrowserID process in a modal presented UIWebView on iOS.

The size of this modal view is fixed and defined by iOS and cannot be changed manually. It is 540 points wide.

Here is a screenshot: https://moo.mx/grabs/38465568.png

Is it possible to modify the CSS of browserid so that it will use the mobile layout when it is run in the above modal view?

**Comment by lloyd** [comment]
not deeply familiar with the CSS mechanism to switch views.  I'd prefer to wait for @shane-tomlinson to return to handle this.  Is there any time pressure?

**Comment by st3fan** [comment]
No extreme time pressure. Things work, just don't look great. But we can live with that for a bit.

**Comment by lloyd** [comment]
ok, the strategy for solving this is in issue #1101 - this one is a dup!
