### ISSUE TITLE
Enhance our use of EJS so we can keep templates DRY

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1212]
In fixing Issue 841, I wanted to use `include` or `partial` in a template to include a new `tos_pp.ejs` template. This would keep us from duplicating work across 6 templates.

I see this can't work with our current template framework of using EJS outside of express/connect.

We should fix this so partial templates can be used client or server side.

**Comment by shane-tomlinson** [comment]
This WORKS as of PR #2455. Closing
