### ISSUE TITLE
Uppercase characters shown as lowercase characters on buttons of signin dialog

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/persona#1213]
The uppercase characters in the German strings of the browserid signin dialog are shown as lowercase characters. For German, this is wrong, e.g. "mail address" is a subject and so has to start with uppercase (and parts starting next to "-" also).
The issues seems to be caused by https://github.com/mozilla/browserid/pull/1136 and https://github.com/mozilla/browserid/pull/1138
The localization shows that it is correct: https://localize.mozilla.org/de/browserid/translate.html?unit=1127597

**Comment by jrgm** [comment]
Thanks Archaeopteryx. The pull requests you mention are not yet in production; that will happen tomorrow, but in the 
stage environment with the text-transform removed, if the localizer chooses upper-case, they will get upper-case. 

Does this look correct to you? That should be what you will see sometime tomorrow afternoon PST.
https://img.skitch.com/20120228-ft7mhqk35b4y9affwxs2f8w6mm.png

**Comment by Archaeopteryx** [comment]
Thank you for the answer, the screenshot looks correct.
