### ISSUE TITLE
Authentication using smartcard

### ISSUE THREAD

**Issue by cbiesinger** [mozilla/persona#1214]
So this is probably sort of an edge case, but I would really like to be able to log in to my browser ID account with the smartcard I have (issued by a-trust in my case).

This would be much more secure than a password. Firefox supports using this card, and there are also DOM APIs for it:
https://developer.mozilla.org/en/JavaScript_crypto

**Comment by lloyd** [comment]
this is something that would be fantastic to explore in the context of a custom primary (should be possible right now), but isn't something we're ready to build into the core platform at the moment.
