### ISSUE TITLE
Locales ready for February 29, 2012 release

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1223]
The list o locales ready for a push to production today is available here:
https://etherpad.mozilla.org/localize-browserid-shipping

We have 30 locales + en-US. Do I need to add en-US to the list?

/cc @ozten

**Comment by fetep** [comment]
en-US is good to include, since it needs to be in the deploy config to enable.

**Comment by mathjazz** [comment]
Thanks!

**Comment by fetep** [comment]
new code out to prod, new locale list live.
