### ISSUE TITLE
Apply as a mentoring Organization to GSoC

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1224]
http://www.google-melange.com/document/show/gsoc_program/google/gsoc2012/faqs#timeline

We would have to submit an application by march 9th as a mentoring organization to participate.

**Comment by Skalman** [comment]
I'd be interested in doing a non-JS implementation of BrowserID.

**Comment by lloyd** [comment]
Another interesting project came up regarding debugging tools for node.js.  Basically a contribution to community efforts to improve tooling in the form of some smart dude working on the problems at mozilla.

**Comment by benadida** [comment]
I think we may have missed the deadline for this, sadly.
