### ISSUE TITLE
it-CH (debug) translation broken in dev env

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1230]
steps to reproduce:
1. change your language to it-CH
2. go to dev.myfavoritebeer.org and click sign-in
3. notice that "BrowserID is the fast and secure way to sign in" is not "translated"

**Comment by lloyd** [comment]
labeling this five stars, understanding what's broken and why should block rolling `train-2012.03.01`

**Comment by ozten** [comment]
This is not a bug.

A string was changed, but we haven't extracted and merged strings yet.
