### ISSUE TITLE
bail on primary because of network latency?

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1231]
What to do when fetching primary .well-known takes forever?

**Comment by fetep** [comment]
In production, all of these requests go through a proxy which times out and returns a 5xx after 5s.  It's probably worth having support for a local timeout, too, for cases when you're not going through a proxy.

**Comment by shane-tomlinson** [comment]
@benadida, @fetep - in the dialog, while fetching .well-known is occurring, all user input is disabled.  If the request takes longer than 10 seconds, the "this request is taking a long time" wait screen is displayed.

**Comment by zaach** [comment]
It sounds like @shane-tomlinson has answered this. Reopen if we're still iffy on the current behavior.
