### ISSUE TITLE
password reset flow is confusing

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1232]
Shane's addition:
We have seen a lot of confusion around the password reset flow. Many users do not understand why we are asking for their password when they click "forgot password".

Skinny's original:
Currently
1. get user's email
2. send verification email
3. set password

Desired
1. get user's email
2. create password
3. send verification email

**Comment by lloyd** [comment]
here's a cap of the current UI in progress: https://img.skitch.com/20120417-r6pey6jq31fmfp14xnhfmbgg2q.png

/cc @shane-tomlinson

**Comment by lloyd** [comment]
now deployed here for your previewing pleasure: http://issue1232.myfavoritebeer.org/

**Comment by shane-tomlinson** [comment]
Closing as dup of #1000

**Comment by shane-tomlinson** [comment]
@skinny97214 - Did you mean to re-open this?

**Comment by skinny97214** [comment]
Not sure about the status of this feature. I checked on dev and the flow was reversed from how it's specified.

**Comment by shane-tomlinson** [comment]
@skinny97214 - am I missing something?

```
Desired
1. get user's email
2. create password
3. send verification email
```

That flow should be followed in both the dialog and main site.

**Comment by skinny97214** [comment]
Ubmmm... Did I write that backwards. This is embarrassing.

I want our flow to be the same as 99% of the other sites.

Desired
1. get user's email
2. send verification email
3. create password

**Comment by shane-tomlinson** [comment]
@skinny97214 - I am confused what the request is here.

For new account flow, we intentionally put the initial "set password" on a new account in the dialog so the user would not have to type anything once they click on the verification link.

Do you want this changed back to the former state?

Or is this related to "forgot password"?

Even in the forgot password case, I thought we did not want the user to type anything when they open the verification link.

**Comment by skinny97214** [comment]
Unfortunately, the conventions for creating and account and resetting the password opposite each other. Sorry we can't reuse that code. We did intentionally reverse the account creation. I didn't realize that was going to mess up the password reset as I had no way of knowing that used the same code.

**Comment by shane-tomlinson** [comment]
@skinny97214 - When we flipped the order of the reset password, the stated goal/assumption we were working under was to have 0 typing after the user clicks the verification link unless it was absolutely necessary. Code re-use was not on our minds, it just shook out that way. 

We do need to make _some_ change since we have already seen a fair amount of confusion around this flow. Instead of changing the entire flow, are there any wording changes we can make that would achieve the same goal? Before proceeding with an entire flow re-work, I'd like to mentally explore alternatives. @lloyd also mentioned wanting examine the security repercussions.

Changing the title of this from "flip the order of account creation flow : password <-> verify email" to "password reset flow is confusing" so that we keep track of the actual problem.

**Comment by benadida** [comment]
Let me try to jumpstart this issue, since it seems important.

Reset password link followed by password entry is quite typical. I suggest we do this unless we have a good reason not to. @shane-tomlinson @lloyd you have concerns about a potential security issue: can you elaborate?

**Comment by shane-tomlinson** [comment]
@lloyd and @jrgm both had concerns about changing this flow. @jrgm had concerns about bad acting email providers reading user's emails, but I do not remember the particulars.

**Comment by jrgm** [comment]
@vthunder pointed out that my argument was moot since the bad acting email provider could initiate the flow itself.

**Comment by benadida** [comment]
@jrgm cool. @lloyd any remaining concerns? I think @skinny97214 is right, so unless we have an unexpected complication, we should probably move forward on this.

**Comment by Brigit** [comment]
Lloyd,
This came up in my check-in with Skinny.  Can we look at resources and ascertain if we can get this completed before the end of the calendar year?

**Comment by shane-tomlinson** [comment]
@zaach and I are going to hash out a basic plan on Tue 12/11/12.

**Comment by lloyd** [comment]
merged.  scheduled for production on 3/13 http://personatra.in/#2013.03.01
