### ISSUE TITLE
Lock down locales and verify them 24 hours before prod release

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1233]
We had a hiccup in our prod push, because invalid config was manually entered.

To fix the root cause we shoud:
- Capture final locales in a new config `config/l10n-prod.json`
- Create a prod config verification script
- Freeze locales 24 hours before the planned push

@mathjazz once config/l10n-prod.json exists, you could edit it,  instead of filing bugs and doing etherpad for the final set of locales.

@mathjazz At least 24 hours before push to production, once you've edit that file for the last time, you would ping the l10n community and ask them to verify their locale is working on stage.

How does that sound?

**Comment by mathjazz** [comment]
This sounds cool, updating the config file is actually easier for me than filing bugs and editing Etherpad.

Why do we need this file 24 hours before push to production?

**Comment by ozten** [comment]
It has to be 24 hours, because @fetep builds RPMs that far in advance and QA does a final pass.

Okay, @mathjazz, @fetep please review 
https://github.com/mozilla/browserid/pull/1296

New config - https://github.com/mozilla/browserid/commit/5a6b9dd658c9342a26afb7ab1a9d80ea107eb020#diff-1

Starting with https://github.com/mozilla/browserid/commit/5a6b9dd658c9342a26afb7ab1a9d80ea107eb020#diff-2
will explain the two new scripts.

**Comment by ozten** [comment]
Landed on dev.
