### ISSUE TITLE
The "sys" module is now called "util". It should have a similar interface.

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1234]
any time you see this error on the console, it's because we're using libraries that use deprecated APIs.  We should hunt down all these cases and upgrade the underlying libraries, if we can do so without moving to versions we're uncomfortable with.

**Comment by jrgm** [comment]
node-temp is one offender (the noisy one in the unit tests). There is a v0.4.0 tag now that removes the use of sys and a few other relatively small changes.

Note: if you didn't already know (probably do) but if you set NODE_DEBUG=sys in the environment, node will dump the 
stack of the caller to require('sys')

(p.s., do you want separate bugs for each lib that needs upgrading? Or just this one bug)

**Comment by lloyd** [comment]
Let's just use this bug, I'll knock them off one by one.

--lloyd

**Comment by jrgm** [comment]
verified in stage and my dev environment. I get none of these warnings. (Still a few places in docs and test code that come entrained by other modules in node_modules, of course, but not called code by us.)
