### ISSUE TITLE
product benefits for 1st time user inside popup

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1237]
Currently, the link to the tour goes to browserid.org. This has two issues. Some users have a hard time locating the popup again and get confused. Second, this tour makes sense in the broader context of how you'll use the service ultimately, but is a bit contradictory for what they're about to do.

For the sign in screen that shows to a user we don't have cookied
http://cl.ly/2w3t2a2w1D0f133O0Z0b

I'm working on new copy and layout for the rest.

**Comment by zaach** [comment]
What's the status of this?

**Comment by skinny97214** [comment]
resolved in GH-1874
