### ISSUE TITLE
link to home site should look more actionable

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1238]
- add a hover state

Needs testing to see if users can find out how to manage their account, reset password, etc. Possibly need a gear icon in the top right corner of the popup.

**Comment by jaredhirsch** [comment]
@skinny97214 still a good first bug?

**Comment by callahad** [comment]
Closing as invalid thanks to #3196 landing

**Comment by callahad** [comment]
(Unless this is about the popup. If so, please re-open @skinny97214)
