### ISSUE TITLE
mismatch of PP/TOS text and button text ('next' vs. 'sign in')

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1240]
1) Go to beta.myfavoritebeer.org and click signin
2) click 'This is not me' if signed in
3) Enter either the email of an existing user or something new (adsfiowerui@example.com)

The text says "By clicking next ...", but the button is either 'sign in' or 'verify email'

![img](https://img.skitch.com/20120302-n2yqx5dggjiupmgfac9m4wsnmb.png)

**Comment by lloyd** [comment]
@skinny97214 will give us a chart, @ozten will do a first pass, after we change the world we will do another pass.

**Comment by skinny97214** [comment]
Only show on screens where the button is the last click. It shouldn't show next to the [next] button.

**Comment by shane-tomlinson** [comment]
@skinny97214 - there is a problem with only showing the tos/pp message only at the last click.  If the user is logged in to their primary whenever they initially enter their email address into the email field, no "next" button is shown.  

A second source of weirdness is when a user goes to add an email to an existing account.  More on this to follow.

User signing in/up to BrowserID:

```
 primary is an address supported by a Primary IdP.
 secondary is an address that must be verified using BrowserID as the secondary authority.

* Email is already registered with BrowserID:
       - primary, user not logged in with IdP - show at the "next" button.
       - primary, user logged in with IdP - No "next" button is ever shown.
       - secondary - show when the password field and "sign in" buttons are shown.
* Email is not registered with BrowserID (new user):
       - primary, user not logged in with IdP - show at the "next" button.
       - primary, user logged in with IdP - No "next" button is ever shown.
       - secondary - show when the "verify email" button is shown.
```

If the user is signed in to BrowserID:

```
* at the email picker.
```

Add Email Screen - If new email is:

```
* secondary - verification screen is shown without a second button being displayed.
* primary, user is signed in with IdP - email is added without a second button being displayed.
* primary, user is not signed in with IdP - show with the "verify" button.
```

As you can see, with the add email flow, two of the 3 flows do not display a second button, and one does.  We only know which of the three states the user will be in once the user clicks the first button.  Should we add button clicks or show the tos/pp statement for all 3?

**Comment by skinny97214** [comment]
Ok, we can show it on the first sign-in screen next to [next] 

... IFF we reduce when users see this. It shouldn't show if their local storage indicates they've already acknowledged the TOS. Nice to have: It also shouldn't appear if they site indicates to us the user already has an account.

**Comment by shane-tomlinson** [comment]
From Jishnu:
1. on the first screen, when the user has not indicated email address at all, remove the TOS/PP string - no need to have it here.
2. Once a user has indicated a valid browserID email and the password form shows up, then put in the TOS/PP string for tosfix.myfavoritebeer.org. But consider changing it to "By clicking next, you confirm that you accept tosfix.myfavoritebeer.org's Terms of Use and Privacy Policy." to make it extra clear that it's not BrowserID's TOU/PP they are assenting to.
3. If the email address is new, then after "Welcome to BrowserID! This email looks new, so let's get you set up." put "By clicking next, you confirm that you accept BrowserID's Terms of Use and Privacy Policy." and link to the BrowserID TOU/PP.

**Comment by jishnu** [comment]
Hiya -

Just to clarify - my comments were trying to differentiate between the Persona TOU/PP (soon to be revamped) which users need to agree to when creating a Persona account vs the site to which they are logging in to's TOU/PP. I def think each should only be shown right before the user assents to the appropriate interaction (sign-up/sign-in to site) and not multiple times as that would be even more confusing. 

If there are any ideas on how to differentiate the two of these use cases more fully that would be awesome to hear.

**Comment by shane-tomlinson** [comment]
I am proposing a hybrid approach which combines both Jishnu's and Skinny's proposals to be both unobtrusive and provide a large area of coverage.

From my understanding, we need two sections of TOS/PP - one for the RP, and one for BrowserID.  The BrowserID TOS/PP only needs shown to new users.  Users who are already authenticated only need to see the RPs TOS/PP.

Proposal:
1) If the user is not signed in to BrowserID:
    \* show both BrowserID and RP TOS/PPs only when the user is typing in their email address.
2) If the user is signed in to BrowserID and this is the first time the user is visiting a site:
    \* show the RP's TOS/PP under the list of email addresses
    \* show the RP's TOS/PP in the "add email address" before the user clicks "next"
3) If the user is signed in to BrowserID but they have visited the site before:
    \* Do not show any TOS/PP

**Comment by shane-tomlinson** [comment]
Once the TOS/PP changes are merged, this will no longer be an issue as the text has changed to "By proceeding"

**Comment by shane-tomlinson** [comment]
It just got MERGED.  closing.
