### ISSUE TITLE
[stage] The option to check 'Always keep me signed in' is missing in the simplified sign-in flow for a returning user

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1241]
The option to check 'Always keep me signed in' is missing in the simplified
sign-in flow. Perhaps this was intentional to drop  that button.

The old flow (on prod now) was:

1) Go to beta.myfavoritebooze.org and click signin
2) In the dialog, click 'This is not me' if signed in
3) Enter the email of an existing user. Click 'next'
4) Enter the password, click 'select email'
5) User is show a screen where they can select the button
   'Always keep me signed in'
6) Click sign in.

In the new flow, 1-3 are the same, 4 now says 'sign in', and 5-6 have been
dropped removing the opportunity to choose 'Always...'

**Comment by lloyd** [comment]
wontfix, we're going to run after reworking persistence with the new api
