### ISSUE TITLE
change default tests run

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1245]
once 1242 is merged, `npm test` will only run backend unit tests with the json database driver.  instead we should run:
1. backend tests with json driver
2. backend tests with mysql driver (or a nice message if not available)
3. frontend tests with phantomjs (or a nice message if not installed)

**Comment by jrgm** [comment]
verified with train-2012.03.14. front, back, back_mysql all run by default with error messages for not having mysql or phantomjs installed/configured.
