### ISSUE TITLE
Give feedback to users who don't accept cookies

### ISSUE THREAD

**Issue by brettgaylor** [mozilla/persona#1247]
Tried to log in to openbadges.org but I manage my cookies.  when cookies are not except, browserid has no effect.  information to the user (ie please accept cookies) would be useful.

**Comment by lloyd** [comment]
@brettgaylor - we have a fix that may solve your request in our staging environment due to go into production in two weeks.  Please try logging into http://beta.myfavoritebeer.org and let us know if you think the messaging is more reasonable, and if so, please close this issue!

**Comment by brettgaylor** [comment]
yes, perfect thank you Lloyd!
