### ISSUE TITLE
'/manage|/users|/primaries' in browserid/views.js redirect to unreachable internal hostname in stage/prod                                               

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1248]
A very minor issue but these URL's redirect to the internal hostname (e.g., web1) of the host that handled the request.                     

Could either just remove the redirects since they don't work anyways, or fix them to use the load-balanced public hostname of the site. (I suppose option #3 is to have zeus handle them, but does anyone ever hit these URL anymore?).

**Comment by jrgm** [comment]
Ping. With the router in place on stage train-2012.06.08, these URLs redirect to http://127.0.0.1:PORT/ which is even uglier than redirecting to a blackhole unreachable 10.x.x.x IP. 

I vote for a zeus rule to redirect them all to '/' for the next prod push, and then just remove the redirect code entirely (these URL haven't been reachable for months now). 

/cc @zaach, @jbonacci

**Comment by lloyd** [comment]
reopened, the remaining work is the production redirect.

**Comment by jrgm** [comment]
I know I'm the one who suggested to remove these redirects and add a zeus rule to handle these redirects. 

So great, the futile redirects in the code are removed. 

I was about to flie the ops bug for the zeus rule, and I know I suggested it, but I don't think it's worth it to add that overhead to zeus for URL that have been dead for months now. I'll close this bug tomorrow unless anyone feels strongly about adding the redirect /cc @fetep

**Comment by lloyd** [comment]
+1 for close, I don't feel strongly about maintaining redirects.  @vthunder @callahad ?

**Comment by callahad** [comment]
I don't feel strongly either...

**Comment by jrgm** [comment]
Ok, closing. These will now be 404 if they are ever actually requested, which I doubt.

**Comment by jrgm** [comment]
verified on stage train-2012.06.22
