### ISSUE TITLE
undescriptive error message when requiredEmail field is not an email address

### ISSUE THREAD

**Issue by michielbdejong** [mozilla/persona#1249]
if i pass 'michiel@unhosted' or null in the requiredEmail option, i get:
    We are very sorry, there has been an error!
    To retry, you will have to close this window and try again.

instead, to help RPs have an easy debug experience, it could say something more descriptive like:
    Required email address 'michiel@unhosted' not recognized!
    To retry, you will have to close this window and try again.

**Comment by skinny97214** [comment]
Agreed that we need a more descriptive verbose error message. All debugging info for developers and RPs belongs in the [read more] section.

**Comment by shane-tomlinson** [comment]
Since requiredEmail has been deprecated, I am closing this.
