### ISSUE TITLE
server logs should record millisecond resolution timestamps (i.e., the time of day)

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1254]
Helps when trying to corelate requests spread across multiple servers, and in determining order of failing sequences of requests.

**Comment by ozten** [comment]
Okay, I've added @milliseconds after the UTC time, not wanting to break any parsers that currently scrape [<UTC time>]

dev_bid
browserid (26068): info: [Sat, 10 Mar 2012 00:15:03 GMT]@3786 GET /shared/modules/page_module.js 304 - ms

default_bid
browserid (26000): info: 10.0.1.41 - - [Sat, 10 Mar 2012 00:14:13 GMT]@3517 "GET /shared/modules/page_module.js HTTP/1.1" 304 - "http://10.0.1.32:10002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:12.0a2) Gecko/20120308 Firefox/12.0a2"

Pull request
https://github.com/mozilla/browserid/pull/1291

**Comment by ozten** [comment]
Done on dev. Let's file a new bug for any logging tweaks. Thanks.

**Comment by jrgm** [comment]
Verified. The timestamp field in the output to /var/browserid/log/*.log is now a javascript toISOString() on stage servers with train-2012.03.14
