### ISSUE TITLE
http log format should record connect's :response-time millis

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1255]

**Comment by ozten** [comment]
I don't know how this works, but would something like pid be useful?

In previous lives we'd use server ip/thread id to help with tracing logs.

**Comment by jrgm** [comment]
The log line formatting lives in https://github.com/senchalabs/connect/blob/master/lib/middleware/logger.js

We use `default` in stage and production, `dev` in dev. I'm just thinking we'd define our own custom formats `default_bid` and `dev_bid` to include the built-in :response-time token in the format string. The time it took to process the request is useful in logs. 

pid doesn't mean much with node (except to post-facto locate a restart in the logfiles, or if you have workers like verifier where the pid is recorded in the logs already).

**Comment by ozten** [comment]
Thanks for all the detail!

Added :response-time to the format:

dev_bid
browserid (26068): info: [Sat, 10 Mar 2012 00:15:03 GMT]@3786 GET /shared/modules/page_module.js 304 - ms

default_bid
browserid (26000): info: 10.0.1.41 - - [Sat, 10 Mar 2012 00:14:13 GMT]@3517 "GET /shared/modules/page_module.js HTTP/1.1" 304 - "http://10.0.1.32:10002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:12.0a2) Gecko/20120308 Firefox/12.0a2"

Pull request:
https://github.com/mozilla/browserid/pull/1291

**Comment by ozten** [comment]
Done on dev. Let's file a new bug for any logging tweaks. Thanks.

**Comment by jrgm** [comment]
verified done on dev. I'lll file a followup to add :response-time to format 'default_bid'
