### ISSUE TITLE
possible race between /sign_in dialog and /verify_email_address page?

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1256]
This is reproducible in automation with an actual browser about 1 in 50 to 100 times. It may well be a bug on my part, but it 
could also be for real. The user experience of the failure case though isn't so bad and they can complete signup with a couple of extra steps that don't seem that unusual to the user, so it might have not been identified as an issue yet.

Steps to reproduce manually (repeat 100 times or until it fails ;-) )
0) start with a clean profile, or just blow away cookies for diresworb.org and beta.myfavoritebeer.org
1) load beta.myfavoritebeer.org and click 'sign in'
2) in the /sign_in dialog enter an email address never used before
3) click next; click verify email
4) Go to email client and find the /verify_email_address email and open that link in the same browser (new window/tab)
5) fill in a password twice and click finish

Excepted:
The verify_email_address page transitions to show 'Thank you for signing up with BrowserID'. The /sign_in dialog detects that user is now authenticated and closes. Myfavoritebeer now appears in a logged-in state.

Ocasionally:
The verify_email_address page transitions to show 'Thank you for signing up with BrowserID'. The /sign_in dialog though
shows the dialog with the chosen email address and a next button.

The user can continue from this by clicking next, entering the chosen password and clicking on 'sign in'. The sign_in dialog witll now complete its work and the user is signed in to myfavoritebeer.

**Comment by lloyd** [comment]
assigning to self, @jrgm gave me context in a video chat.

**Comment by jrgm** [comment]
I let this run in the background till it happened again, and looked in the about:cache (firefox of course).

The entry for https://diresworb.org/wsapi/user_creation_status?email=blah%20example.com has headers:

HTTP/1.1 200 OK 
Cache-Control: no-cache, max-age=0 
Content-Type: application/json; charset=utf-8 
Strict-Transport-Security: max-age=2592000; includeSubdomains 
Date: Tue, 06 Mar 2012 20:46:07 GMT 
X-Frame-Options: DENY 
Content-Length: 21

with body of:
  {"status":"mustAuth"}

**Comment by skinny97214** [comment]
How will #1232 affect this?

**Comment by jrgm** [comment]
closing this in favour of GH-1451 which has the same STR and "not always reproducible".
