### ISSUE TITLE
UglifyJS dies on some locales

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1257]
In rebuilding tempoary_preview on train-2012.03.01

I did svn update in locales, then 

```
    cd /home/app/code/locale
    svn up
    ./compile-mo.sh .
    ./compile-json.sh . ../resources/static/i18n/
            CONFIG_FILES=config/aws.json ./scripts/compress
```

It seems like `es` might have some syntax issues

https://gist.github.com/1981092

compress should log such errors, but continue to run.

**Comment by ozten** [comment]
Looks like es was an invalid js file.

I'm not sure if  I have a bug in my cron or how it got squashed.

To repro the uglify issue, just edit a resources/static/i18n/es/client.json and make it have a syntax error.

**Comment by lloyd** [comment]
how about log such errors, continue to run to completion, and return a non-zero exit code if any errors were detected?

**Comment by ozten** [comment]
Sounds great!

**Comment by jrgm** [comment]
verifed for train-2012.03.14 and my dev env. Corrupted json file does not stop the whole build, with non-zero exit status of scripts/compress.
