### ISSUE TITLE
method to probe dbwriter's database connection health

### ISSUE THREAD

**Issue by fetep** [mozilla/persona#1258]
for webheads, we query /wsapi/have_email from nagios.

it would be nice to have something similar to detect the health of the dbwriter's db connection we could probe in nagios.

**Comment by lloyd** [comment]
approach is to patch in `have_email` to the current rolling train, then in dev we'll expose an explicit ping method that uses the mysql protocol's ping functionality.

**Comment by lloyd** [comment]
fixed with 1971ecc
