### ISSUE TITLE
perma-url /v/<md5sum>/... are revalidated each time by IE8/IE9

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1268]
See GH-1141. The other browsers appear to be doing the right thing with a response like the below.

HTTP/1.1 200 OK
Vary: Accept-Encoding,Accept-Language
Cache-Control: public, max-age=31536000
Content-Type: application/javascript
Strict-Transport-Security: max-age=2592000; includeSubdomains
Date: Tue, 06 Mar 2012 23:01:04 GMT
Accept-Ranges: bytes
Etag: "284043-1331058798000"
Connection: keep-alive
X-Frame-Options: DENY
Last-Modified: Tue, 06 Mar 2012 18:33:18 GMT
Content-Length: 284043

However, despite 'Cache-Control: public, max-age=31536000' both IE8/winxp and IE9/win7 revalidate the URL every time the /sign_in dialog is opened. (I can't see the exact headers that IE is sending (i.e., If-None-Match, If-Modified-Since) but a 304 is recorded in the server logs).

**Comment by jrgm** [comment]
Note both the IE versions I used are configured for "Check for newer versions of stored pages" to be "Automatically", which is the default and the one that should be using the cache (Choices are "Every time I visit a web page", "Every time I start IE", "Automatically", "Never").

**Comment by jrgm** [comment]
I spun up a fresh VM with Vista and IE9 and here are the requests I see when opening the /sign_in dialog from beta.myfavoritebeer.org for a second time. (Note: do we have an separate issue already for turning e.g., /i/bg.png into a perma-URL? This bug is just about the requests for dialog.js and dialog.css and similar).

[Wed, 07 Mar 2012 02:57:03 GMT] "GET /i/arrow.png HTTP/1.0" 304 - "https://diresworb.org/sign_in" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0)"
[Wed, 07 Mar 2012 02:57:03 GMT] "GET /i/bg.png HTTP/1.0" 304 - "https://diresworb.org/sign_in" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0)"
[Wed, 07 Mar 2012 02:57:03 GMT] "GET /i/icon.png HTTP/1.0" 304 - "https://diresworb.org/sign_in" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0)"
[Wed, 07 Mar 2012 02:57:03 GMT] "GET /sign_in HTTP/1.0" 304 - "-" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0)"
[Wed, 07 Mar 2012 02:57:03 GMT] "GET /v/761c613c75/production/en_US/dialog.js HTTP/1.0" 304 - "https://diresworb.org/sign_in" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0)"
[Wed, 07 Mar 2012 02:57:03 GMT] "GET /v/c8286c5651/production/dialog.css HTTP/1.0" 304 - "https://diresworb.org/sign_in" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0)"
[Wed, 07 Mar 2012 02:57:03 GMT] "GET /wsapi/session_context HTTP/1.0" 200 193 "https://diresworb.org/sign_in" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0)"

**Comment by shane-tomlinson** [comment]
AHA!  I found the (potential) reasons why on MSDN: http://blogs.msdn.com/b/ie/archive/2010/07/14/caching-improvements-in-internet-explorer-9.aspx

```
If a response contains a Vary directive that specifies a header other than Accept-Encoding, 
Host, or User-Agent (or any combination of these) then Internet Explorer will still cache the 
response if the response contains an ETAG header. However, that response will be treated
as stale and a conditional HTTP request will be made before reuse to determine if the 
cached copy is valid.
```

We specify the Accept-Encoding and Accept-Language headers.

Second:

```
A few months ago, I mentioned that Internet Explorer will not reuse a previously-cached 
resource delivered over HTTPS until at least one secure connection to the target host has
been established by the current process. This can cause previously-cached resources to
be ignored, leading to unconditional network requests for content that was already in the 
local cache.

In IE9, the unnecessary cross-host HTTPS requests are now conditional requests, so the 
server can simply return a HTTP/304 Not Modified response for unchanged content. While
a round-trip cost is still incurred, significant performance improvements are gained 
because the server does not need to retransmit the entire resource.
```

**Comment by lloyd** [comment]
Are you "reloading" the page, or revisiting it?  Afaik most browsers treat the reload button differently than hitting enter in the URL bar...

--lloyd

**Comment by shane-tomlinson** [comment]
@lloyd - I am revisiting

1) Start at https://vary-header.123done.org
2) Go to another site (mine is slashdot)
3) type in again https://vary-header.123done.org

**Comment by jaredhirsch** [comment]
Hmm. @shane-tomlinson 's comment above suggests that this will always be a problem, as it's a bug in IE implementation and we're going to use Vary headers that trigger the bug.

Closing as wontfix, perhaps a little quick on the trigger. Reopen if I'm wrong (and set to Beta 3 milestone).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
