### ISSUE TITLE
minor cleanup issue for l10n remove <a href='...'> from gettext

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1269]
Small point but two stragglers from GH-1161
# : resources/static/dialog/views/confirm_email.ejs:18

msgid ""
"If this is a mistake, just ignore the sent email and <a href=\"#\" id="
"\"cancel\">cancel</a>."
msgstr ""
# : resources/static/dialog/views/confirm_email.ejs:20

msgid ""
"If this is a mistake, just ignore the sent email and <a href=\"#\" id=\"back"
"\">use another email address</a>."
msgstr ""

**Comment by shane-tomlinson** [comment]
fixed with checkin 0e80cced.  Closing

**Comment by jrgm** [comment]
verified in code
