### ISSUE TITLE
Add caching service

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1270]
We need to add a caching service as a dependency.

Candidates:
- memcached
- redis

Requirements:
For fetching public keys, we'd like to set expiration times on objects, and have the caching service manage cache cleanup.

**Comment by fetep** [comment]
something to think about: how wide should this cache be shared? between webheads & dbwriters per datacenter? globally across all datacenters?

**Comment by lloyd** [comment]
how far can we get with squid?

**Comment by fetep** [comment]
btw, squid (which we send all pubkey fetching traffic through) is effectively this cache, today. it caches/expires based on http headers.

**Comment by ozten** [comment]
LOL, now I know and knowing is half the battle. Doesn't sound like we have any short term needs for this. Closing.
