### ISSUE TITLE
Support Primary Authority Delegation

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1271]
An organization should be able to delegate Primary authority to another domain.

Example: Mozilla.com could create the following file at `https://mozilla.com/.well-known/browserid`

```
{
    "authority": "browserid.mozilla.org"
}
```

BrowserID should retrieve `https://browserid.mozilla.org/.well-known/browserid` to determine if mozilla.com is a primary.

browserid.mozilla.org should be able to serve as the IdP for several domain names, such as mozilla.com, mozilla.org, mozilla.co.jp, etc.

**Comment by ozten** [comment]
Pull Request:
https://github.com/mozilla/browserid/pull/1281

**Comment by ozten** [comment]
Merged to dev.

**Comment by lloyd** [comment]
this feature should make it to production 2012/03/28

**Comment by ozten** [comment]
We don't currently have an environment.

We could setup a new website, say clortho.org that delegates to vinz.clortho.org. Can we file a bug, if we want that? This will happen naturally with the Mozilla IdP project.

MAX_AUTHORITY_DELEGATIONS has a unit test, but same answer. You'd setup a series of webservers on different domains that delegate to each other. Might be worth testing once outside of the unit tests, but I don't think we want to maintain these servers.
