### ISSUE TITLE
Locale: (e.g., de,ca) 'Use a different email' overlaps TOS/PP

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1275]
Follow on from GH-1105. Even with the number of emails limited to 4 shown, the 'Use a different email' can overlap the TOS/PP
text in some languages.

![img](https://img.skitch.com/20120308-f6k84p1uy2138jdjjdcnp8yif9.png)

**Comment by ozten** [comment]
@mathjazz here is an example of the two new strings.

**Comment by mathjazz** [comment]
@ozten I'm afraid this is more of a web design issue than localization. It's evident that we don't have enough space for e.g. de translation, which is known for extensive use of long words.
