### ISSUE TITLE
trivial error formatting throw message in lib/load_gen/common.js:48

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1278]
There's a extra '+' in this statement at lib/load_gen/common.js:48

```
        if (resp.code !== 200) throw "non-200 status: " + resp.code +
          + " - " + resp.body;
```

-> "can't certify key: non-200 status: 500NaNServer Error: can't contact keysigner"

Harmless really. Maybe wontfix.

**Comment by lloyd** [comment]
thank you @jrgm.  this was incredibly annoying.

**Comment by jrgm** [comment]
verified
