### ISSUE TITLE
http://beta.myfavoriteshow.org/ looks bad on the Maple build

### ISSUE THREAD

**Issue by xti** [mozilla/persona#1282]
Steps to reproduce:
1. Open Fennec
2. Browse to http://beta.myfavoriteshow.org/
3. Check if opened page has layout issues

Expected result:
No layout issues after step 3.

Actual result:
The opened page looks badly: http://img805.imageshack.us/img805/3904/device20120309183846.png
## 

Maple (2012-03-08)
Device: HTC Desire
OS: Android 2.2

**Comment by tonychung** [comment]
Hey nicolae,
I Think That's a maple build issue, not Browserid.  Can u double check on nightly also?

You can create a bug on fennec side, tag maple, and cross post the buglink if you want.

Tony

**Comment by xti** [comment]
Hi Tony,

Sure, I will check on the Nightly as well. I guess that I can copy the comment #0 from here and move it to bugzilla

Nicolae

**Comment by xti** [comment]
I can confirm this for the regular Nightly too.

**Comment by ozten** [comment]
Marking as good first bug, we'd love some CSS <3 with this.
