### ISSUE TITLE
Referrer info logged to browserid.json should be stripped to origin only.

### ISSUE THREAD

**Issue by deinspanjer** [mozilla/persona#1283]
https://github.com/mozilla/browserid/blob/dev/lib/metrics.js#L77-87

Not stripping causes distinct counts on the "rp" field to not match up with the validator.json "rp" field which is based on the Audience attribute.

**Comment by lloyd** [comment]
more importantly, we don't need the full referrer, we just need the origin.  so we should not put the former into our logs.

**Comment by jrgm** [comment]
veriified on stage train-2012.03.14 - the http referer in the request is stripped to just to scheme + hostname when it's recorded to the metrics log.

**Comment by deinspanjer** [comment]
Just to make sure, does this include the port number for URLs that run on a nonstandard HTTP or HTTPS port?

**Comment by jrgm** [comment]
Yes, if the Referer: for example is 'https://foo.com:8080/bar.js?arg=val' then we would log 'https://foo.com:8080'. 

Note that we don't normalize, so if the Referer is 'https://foo.com:443/bar.js?arg=val' then we log 'https://foo.com:443', not 
'https://foo.com'. 

(Or did you want it to not include the port number?)

**Comment by jrgm** [comment]
Also bogus inputs for Referer: will be logged as 'undefined://' or in the worst case 'null'.

**Comment by deinspanjer** [comment]
This sounds good to me.  The most important thing from our point of view is that this value matches perfectly with the value given in the verifier under the "audience" attribute.  Audience and referrer both get written to the logs as "rp" which is what we take a distinct count of.  If there are mismatches, our distinct counts will be off and we can't do a lot to correct that.
