### ISSUE TITLE
Attempting to log-in with primary i5y.org offers to 'verify e-mail' rather than re-route to log in with e-mail provider

### ISSUE THREAD

**Issue by davidillsley** [mozilla/persona#1284]
I've spun up an instance of my primary on an EC2 instance using a cert from startcom. When I attempt to log in with it, browserid.org doesn't appear to recognise that the domain - i5y.org - is a primary.

This is the same code that's running on heroku, so I'm suspicious that it's something to do with the cert or the AWS ELB I'm using as the https endpoint, but of course I can't see the logging from primary.js to know what's going on.

**Comment by davidillsley** [comment]
Hrrrm.

https://www.browserid.org/wsapi/address_info?email=david@browserid-i5y.herokuapp.com
{"auth":"https://browserid-i5y.herokuapp.com/","prov":"https://browserid-i5y.herokuapp.com/provision","type":"primary"}

https://dev.diresworb.org/wsapi/address_info?email=david@browserid-i5y.herokuapp.com
{"type":"secondary","known":false}

https://dev.diresworb.org/wsapi/address_info?email=david@i5y.org
{"type":"secondary","known":false}

https://www.browserid.org/wsapi/address_info?email=david@i5y.org
{"type":"secondary","known":false}

**Comment by ozten** [comment]
I ran `/scripts/check_primary_support i5y.org` from my desktop and the output looks good. No issues detected.

**Comment by ozten** [comment]
Next steps, I'll get access to dev and troubleshoot why that server doesn't believe it's a primary.

**Comment by ozten** [comment]
Ran our check primary support tool from dev.diresworb.org and it passes, which is surprising.

```
./check_primary_support i5y.org
info: process type is check_primary_support
info: i5y.org is a valid browserid primary
Priary domain:  i5y.org
Public Key:  { rsa: 
   { n: { _bigint: <BigInt 1806084745004...030468864154859> },
     e: { _bigint: <BigInt 65537> },
     d: null,
     p: null,
     q: null,
     dmp1: null,
     dmq1: null,
     coeff: null },
      keysize: '256',
      algorithm: 'RS' }
```

**Comment by davidillsley** [comment]
According to http://www.sslshopper.com/ssl-checker.html#hostname=i5y.org

"The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate."

So I've slightly misconfigured the server, but in a way that seems fine in browsers and the script when run by hand.

If this is the problem, I can't think why it wouldn't be consistent between the server and the script, but it seems like something I should fix anyway, so I'll do that at some point in the next couple of hours.

**Comment by davidillsley** [comment]
Updated and now all clean on http://www.sslshopper.com/ssl-checker.html#hostname=i5y.org

Still not showing up as a primary on https://dev.diresworb.org/wsapi/address_info?email=david@i5y.org but I guess there could be DNS and other caching to wait for

**Comment by ozten** [comment]
I don't think the SSL cert is the issue.

http://vinz.clortho.org is a self-signed cert.
https://dev.diresworb.org/wsapi/address_info?email=david@vinz.clortho.org is detected as a primary.

**Comment by ozten** [comment]
I'm sorry for the run around.

dev.myfavoritebeer.org should work for you now.

The solution - lock down our outbound requests and domains with numbers such as i5y.org were being blocked.... sigh.

**Comment by davidillsley** [comment]
Awesome. Thanks. That's definitely worth a beer if our paths ever cross.

Out of interest, do you know why numbers were locked down? To prevent non-domain-name primaries?

**Comment by davidillsley** [comment]
This seems to have regressed :(

https://dev.diresworb.org/wsapi/address_info?email=david@i5y.org
{"type":"secondary","known":false}

https://dev.diresworb.org/wsapi/address_info?email=david@id.illsley.org
{"auth":"https://id.illsley.org/","prov":"https://id.illsley.org/provision","type":"primary"}

Both i5y.org and id.illsley.org point at the same server instance, so it seems pretty likely this is a straight regression.

I don't seem to be able to reopen this issue - if the process is to raise a new issue, let me know, and I'll do that.

Cheers,
David

**Comment by ozten** [comment]
Sigh. Fixed. I don't think this will regress again.

Let me know if you see any issues.
