### ISSUE TITLE
Unable to select other accounts on Android

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#1286]
This is against beta, tested on beta.myfavoritebeer.org.    Clicking any of the other 

see screenshot: http://i.imgur.com/c7VZq.png
I also made a video screencast:  http://www.youtube.com/watch?v=UOVh2g8n3xA&feature=youtu.be
Notes: @jbonacci says it seems to work on stock browser.  I'll be trying that now.

Repro:
1) created 5 different email accounts on diresworb.org
2) open android device, fennec nightly build (03-09-2012) bulld, and visit beta.myfavoritebeer.org
3) click sign in , and sign in with one of your accounts
4) when you get to the screen to choose which account to associate with, click another radio that's not already selected
5) Verify none of the other radios's accounts can be selected (highlights when you tap it, but does actually select it)

Expected:
- able to select a different account

Actual:
- tapping the account highlights, but it never selects a different account.

**Comment by tonychung** [comment]
here's a screencast when running against Stock browser, beta.myfavoritebeer.org.

http://youtu.be/gE7JeSov4HI

Android 2.3.5 motorola Droid Razr

**Comment by nhirata** [comment]
Ya, gmail email addresses seem to cause an issue.  I was able to replicate with 2 email addresses.
