### ISSUE TITLE
User Feedback needed after hitting next/verify email

### ISSUE THREAD

**Issue by nhirata** [mozilla/persona#1290]
1. go to beta.myfavoritebeer.org on an android device
2. type in a new email address
3. hit next

Expected: some sort of user feedback letting the user know that the email is being processed
Actual: nothing seems to change.

**Comment by skinny97214** [comment]
Is this from slow keygen?

**Comment by skinny97214** [comment]
Put a spinner on it.

**Comment by lloyd** [comment]
we need a spinner.

we to upper bound allotted time slow failures in squid, let's check @fetep

**Comment by skinny97214** [comment]
Can we also say "We've never seen this domain before. Hang on a sec while we look into it."

**Comment by shane-tomlinson** [comment]
@skinny97214 - the slowness here is actually in the check to see whether we have seen the domain before.  While the check is running, I have no idea whether we have.  I can put in a message that says "Checking whether we have seen this domain before" or something to that effect and show it after a second or two, which should be enough time for most domains that we have previously checked.

**Comment by jrgm** [comment]
Oops. Forgot to mark this as verified on stage for train-2012.04.11.
