### ISSUE TITLE
does browserid support unicode email addresses?

### ISSUE THREAD

**Issue by anaaktge** [mozilla/persona#1294]
If it does not, it should.

Usecase: users in locales where unicode is common cannot use browserid, and soon that will mean they cannot use firefox sync either.

**Comment by lloyd** [comment]
let's assess the state of standards, and relax our matching if we find meaningful adoption of unicode.

what's a email provider where we can get a unicode email address?

**Comment by graingert** [comment]
This also brings up issues where `test@xn--hxajbheg2az3al.xn--jxalpdlp` must be considered the same as `test@παράδειγμα.δοκιμή` throughout the BrowserID stack

**Comment by ctalbert** [comment]
This seems important given our history of how we do i18n and l10n at Mozilla. What is the status of this? Is this the only place to track this issue?  Thanks.

**Comment by fantasai** [comment]
> let's assess the state of standards

Issue #1370 links to RFC6530. That seems like a good place to start. What "state" information are you looking for? RFC6530 is an IETF Proposed Standard, which seems equivalent to W3C Candidate Rec. The RFCs for IDNs (which Firefox already supports) are all IETF Proposed Standards.

> and relax our matching if we find meaningful adoption of unicode.

Let me turn this around. Is there a reason _not_ to support them? Internationalization is (was?) one of the fundamental principles of software design at Mozilla. [1] And it tends to be a lot of work to re-architect in later if you don't set it up at the beginning, so not something that lends itself well to putting off.

> what's a email provider where we can get a unicode email address?

Where you can get a unicode email address (for testing purposes) or where a potential user could get a unicode email address (to demonstrate we need to support them)? For the latter case, I suggest considering the employees of any company whose domain name uses non-ASCII characters. A number of registrars for non-English-speaking countries allow this already.

[1] http://www-archive.mozilla.org/docs/refList/i18n/

**Comment by fmarier** [comment]
Relevant discussion in GH-1995.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
