### ISSUE TITLE
Login, sign-in, sign in, registration

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1297]
The following is the email we send people when they sign in to a website using BrowserID with a non-verified email address:

---

[TITLE: Complete Login to %s using BrowserID]

Thanks for verifying your email address. This message is being sent to you to complete your sign-in to %s.

Finish registration by clicking this link: LINK

If you are NOT trying to sign into this site, just ignore this email.

Thanks,
BrowserID
(A better way to sign in)

---

The title talks about completing "login", the first sentence asks to complete "sign-in" and the footer describes BrowserID as the better way to "sign in".

I guess "sign-in" (noun?) and "sign in" (verb?) should be used everywhere and should replace "login", "log in", "log out" wherever we use them.

The email also asks reader to finish "registration". Registration to what? Website (no, we're a sign-in service) or BrowserID (yes)? Shall we make this less confusing by saying something like "Finish registration to BrowserID by..."?

Also, what does "Thanks for verifying your email address." mean? Have I already verified my email? Am I supposed to do this by following the instructions in this email?

Below is my proposal for the improved email wording.

---

[TITLE: Complete sign-in to %s using BrowserID]

This message is being sent to you to complete your sign-in to %s.

To do that, please verify your email address with BrowserID by clicking this link: LINK

If you are NOT trying to sign into this site, just ignore this email.

Thanks,
BrowserID
(A better way to sign in)

**Comment by lloyd** [comment]
done with site wide copy update, closed by issue #1889
