### ISSUE TITLE
privacy policy and tos in-dialog doesn't work in all locales

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1303]
This is one of two issues, introduced in `train-2012.03.01` that motivates derailing that train.

Because non-english languages weren't considered in the initial implementation, there are many cases where the dialog looks terrible or is simply unusable (esp in german and sweedish).  This is a rollup issue that we'll use to track the underlying issue, and dependent issues will be closed down as dups and linked here.

**Comment by shane-tomlinson** [comment]
close with checkin 8e5a3cce6cf5b86e8f7ae726a83ff1b00434ac62

**Comment by ghost** [comment]
I've verified this issue on Windows 7 + Firefox 12.0 beta 2:
Issues 1300, 1292, 1275, 1274, 1272 aren't reproducing anymore. 
Issues 1301, 1276 and 1240 are still reproducible.

I couldn't verify the iOS bugs due to lack of an iOS device.
