### ISSUE TITLE
not possible to select email addresses

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1304]
This is one of two issues, introduced in `train-2012.03.01`, that motivates derailing that train.

The fixes to issue #1133 introduced a regression that makes it impossible to select email addresses in many scenarios, as well as making it imposible to use email addresses with certain legal but uncommon characters.  This is a rollup issue that addresses the core problem, and all specific variations will be closed down as dupes and linked to this issue.

**Comment by zvalteau** [comment]
Issue #1133: I concur with James, the only way to select a email address is to click on the radio button with IOS

**Comment by zvalteau** [comment]
Retest in Stage: beta.myfavritebeer.org 
You are able to select the email address with the name of the email. It works well
Sorry about the confusion.
