### ISSUE TITLE
wordpress plugin so that URL can be a primary

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1305]
For wordpress blogs that live on the root of the URL, set the IDP that will act as primary.

e.g. skinnywhitegirl.com has a blog that lives at the TLD. Installing this plugin lets me set eyedee.me as the primary I want to do auth though so that crystal@skinnywhitegirl.com can be a primary address.

**Comment by stomlinson** [comment]
@jbonacci - Looks like I closed the wrong one.

**Comment by lloyd** [comment]
assigning to @callahad to think about, propose an approach, and prioritize.

**Comment by callahad** [comment]
I'm turning this over in my head. I want to make it easy for sites to become IdPs, but... maybe not until after the Q2 Event? Hm... Will ruminate more.

**Comment by skinny97214** [comment]
What's your concern why we should wait until after beta?

**Comment by tantek** [comment]
Where's the +1 for issues?

This is a key #indieweb use-case. Plug-ins/libraries are available to currently implement consuming of on personal sites:
- OpenID
- RelMeAuth and IndieAuth

but not (yet): 
- BrowserID

BrowserID is behind in this regard.

**Comment by ozten** [comment]
One possible implementation of the Wordpress plugin is that it creates the `/.well-known/browserid` file and content-type properly. The contents would delegate authority to another service.

I did this [on my personal site](http://ozten.com/.well-known/browserid) which is commodity hosting. Then I [built a Node.js](https://github.com/ozten/hostedpersona) hosting service https://hostedpersona.me

So clusters of independent people on the web could share a self-hosted service on a more expensive/high tech hosting environment which does fancy crypto stuff, while their Wordpress blogs have a dead simple PHP plugin which delegates authority.

**Comment by callahad** [comment]
I'm going to close this. We'd love to have a WordPress primary, but I don't see where on the schedule that I'd be able to dedicate the time to building it. Plus, it's probably best left to the community.
