### ISSUE TITLE
Fennec: window.open of site with untrusted certificate fails quietly

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1308]
While using the temporary setup tosfix.myfavoritebeer.org, I was running into something similar to what I had reported in GH-1169 (perhaps the same; it just magically went away at some point). 

STR:
- Clear all data and cache for a Fennec browser
- Go to http://tosfix.myfavoritebeer.org
- Click the 'Sign in' button

Actual: Button bounces up and left and then back to disabled state
Expected: https://tosfix.hacksign.in/sign_in tab dialog opens

I'm not complaining about using this particular certificate for this test instance. This issue is about the user feedback provided when doing window.open to a site with an untrusted certificate. 

It's really an upstream bug but documenting it here. With Fennec (XUL or native) there is no certificate warning when going to tosfix.myfavoritebeer.org (presumably for pulling in /include.js from tosfix.hacksign.in), but with Stock Browser there is a warning and you have to make the decision upfront about whether to trust it.

For Fennec, when you click 'sign in' it tries to window.open tosfix.hacksign.in and silently fails leaving the user with no /sign_in dialog, and a diabled 'sign in' button on tosfix.myfavoritebeer.org. In Stock, you've already made the choice to accept or not, so /sign_in is loaded.

Anyways, simple workaround for testing is to just load https://tosfix.hacksign.in/ directly in Fennec and accept the cert there. I'll see if there's an upstream bug already related to this on mobile.

**Comment by jrgm** [comment]
Hmm, actually, Chrome Beta on ICS behaves the same as Fennec.

**Comment by lloyd** [comment]
lloyd to look for simple fix involving credit cards and such

**Comment by shane-tomlinson** [comment]
@lloyd, @jrgm, @jbonacci - since we now using personatest.org and are no longer using hacksign.in, this particular issue is no longer relevant.  The certificate is accepted on Fennec for personatest.org with no problem.  Closing.
