### ISSUE TITLE
Add new locale: Bulgarian (bg)

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1312]
Please add a new locale.

/cc @ozten

**Comment by ozten** [comment]
Added.

**Comment by ozten** [comment]
There is no 'bg' locale directory.

https://bugzilla.mozilla.org/show_bug.cgi?id=735882

**Comment by mathjazz** [comment]
Just commited to SVN.

**Comment by jrgm** [comment]
@ozten are we shooting to get this back into train-2012.03.14?

**Comment by ozten** [comment]
Hotfixed (bg) to stage/production

http://git.io/AKrGUA
