### ISSUE TITLE
Clean up the CSS.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1317]
It's got a lot of cruft and overrides of overrides.

Start with some true common CSS.

Make a stylesheet each for mobile, tablets, and desktop.

**Comment by shane-tomlinson** [comment]
Link to issue #1101

**Comment by jrgm** [comment]
Closing and verifying for train-2012.04.27 - see https://github.com/mozilla/browserid/issues/1101#issuecomment-5524916
