### ISSUE TITLE
Clean up the code to write the TOS/PP in the templates

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1318]
There is a whole bunch o copy/paste code.  Not very DRY.

Create a template helper function for writing the initial TOS/PP that takes the name of the "next" button.  Create another helper function that inserts the closing `</p>` if needed.

**Comment by ozten** [comment]
The more general issue is a duplicate of Issue 1212. Maybe track the general work there and the specific work for TOS/PP here.

**Comment by shane-tomlinson** [comment]
Closing, TOS/PP code is only done in two places now.
