### ISSUE TITLE
Email must be lowercase

### ISSUE THREAD

**Issue by boinggg** [mozilla/persona#1328]
I think emails should always be sent back as lowercased. This is standard, emails are not case sensitive. You can show them to users as however they entered them but under no circumstance should emails be returned with any upper case letters in the assertion api.

**Comment by callahad** [comment]
Hi, thanks for the suggestion!

Unfortunately, RFC 2821 explicitly states that "the local-part of a mailbox MUST BE treated as case sensitive." Thus, we're planning on preserving the case as provided by the user. You can always perform additional normalization on your end. :)
