### ISSUE TITLE
Definitions for vars

### ISSUE THREAD

**Issue by boinggg** [mozilla/persona#1329]
Where can I see the definitions for the response vars?
For instance, the expires time makes no sense, turned to a date it is
Wednesday 9th of March 1994 02:51:33 PM

Also, where can I see all the allowed options for browseridArguments?
I came across privacyURL and tosURL, what else is there?

**Comment by lloyd** [comment]
all yours @callahad !  This seems to be a request for better docs on JS apis and verifier call.

**Comment by callahad** [comment]
Yeah, I've totally run into this issue (along with figuring out what our verifier returns, as mentioned in #1362). Our docs can definitely be better in this regard, and I'm working on it.

Though specifically resolving this issue might take a little longer -- I want to consolidate all of our docs first, then start working on updating them. Thanks for prodding me on that, @boinggg!

**Comment by callahad** [comment]
This is resolved.

The verifier API is documented at https://developer.mozilla.org/en-US/docs/Persona/Remote_Verification_API

The `navigator.id` API is documented at https://developer.mozilla.org/en-US/docs/DOM/navigator.id
