### ISSUE TITLE
BigTent - build a proxy IdP for gmail

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1332]

**Comment by BYK** [comment]
Anything in mind like using an SMTP backend or the OAuth like OpenID support of Google? SMTP sounds like the right direction though.

**Comment by ozten** [comment]
Project page to track this feature - https://wiki.mozilla.org/Identity/BrowserID/BigTent

**Comment by shane-tomlinson** [comment]
@ozten, @callahad - since BigTent is built, can this be closed?

**Comment by ozten** [comment]
Ship It!

Good call @shane-tomlinson
