### ISSUE TITLE
The "Add another email" string is not localized

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1333]
OS: Windows 7
Browser: Firefox 12.0 beta 2
Language: German, Finnish (probably more languages)

STR:
1. Load http://beta.myfavoritebeer.org/ in the browser.
2. Click on the Sign In button and sign into an account.
3. Observe the emails list dialog.

The "Add another email" string is not translated.

**Comment by ozten** [comment]
http://temporary_preview.myfavoritebeer.org/ does have the latest code - this is my bad.

in svn
locale/es/LC_MESSAGES/client.po:msgid "Add another email"
locale/es/LC_MESSAGES/client.po-msgstr "Agregar otro correo"

Stage looks good:
https://diresworb.org/i18n/es/client.json has the string
I see it on http://beta.myfavoritebeer.org/

Production:
https://browserid.org/i18n/es/client.json - missing strings

Next steps... Do we need to evaluate if we should do an out of cycle release to pick up the latest strings? Are all the affected locales ready?

**Comment by mathjazz** [comment]
I will make a list of all the affected locales.

Yes, I we should do an out of cycle release ASAP.

**Comment by mathjazz** [comment]
This is the list:
"ca", "el", "es", "fr", "fy", "ga", "gl", "hr", "hu", "it", "lt", "pa", "sl", "tr"

**Comment by mathjazz** [comment]
Works for me in production.
