### ISSUE TITLE
Let users manage their username

### ISSUE THREAD

**Issue by kracekumar** [mozilla/persona#1334]
Browserid only provides email id after authentication, it will great if users can manage their username for particluar email id.
## Example

Emailid                 Username
john@john.com      john
john@gmail.com    johnyman

This helps users to use their desired name in the site.

Shortcoming
If the site allows other ways to login apart from browserid, there will be conflict in username, this is solvable though,

**Comment by boinggg** [comment]
no, username is set on consuming site, browser id is only verified email. period. I will not support another openid disaster, NO profiles!

**Comment by shane-tomlinson** [comment]
@kracekumar - Thanks for the feedback, closing as a dup of #880.

@boinggg - Profiles are coming, perhaps not as a core part of BrowserID, but they are coming.  If you'd like to be a part of the discussion on how we can make it as awesome as possible, we'd love to hear your suggestions.
