### ISSUE TITLE
/signin should not be accessible for authenticated users

### ISSUE THREAD

**Issue by cvan** [mozilla/persona#1345]
Steps to reproduce:
1. Log in @ https://browserid.org/signin
2. Load https://browserid.org/signin

Expected:
https://browserid.org/signin should redirect to https://browserid.org/ for authenticated users

Actual:
https://browserid.org/signin is still accessible even for authenticated users

**Comment by lloyd** [comment]
we should probably address this when we rebrand browserid.org

**Comment by shane-tomlinson** [comment]
Link to #1511
