### ISSUE TITLE
case study with RPs

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1346]
Work with at least two different RPs to 
- converting account over wholesale
- present NASCAR style in context with legacy auth and/or Facebook Connect

Collect metrics on 
- how many users are retained after Persona implementation
- reduced password resets
- higher engagement due to longer length of sessions

**Comment by lloyd** [comment]
is this issue useful?

**Comment by skinny97214** [comment]
Pascal and I are working on gydhido.com for this purpose.
