### ISSUE TITLE
dev: dialog cancelation is not conveyed properly to RPs

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1348]
STR:
1. go to dev.myfavoritebeer.org
2. click sign in
3. cancel the dialog

notice that the sign in button is still disabled.  The new backwards compat functions built on top of the event API are not properly invoking the user's callback function with a null assertion value to indicate the user canceled the dialog.

**Comment by lloyd** [comment]
blocked by issue #1354

**Comment by jrgm** [comment]
veriified windows (safari/chrome/firefox/ie8/ie9), osx (safari/chrome/firefox), android2.2(stock/firefox)

Note: opera does not work from before, which is GH-1263.
