### ISSUE TITLE
dev: prolong session when user confirms ownership of a computer

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1349]
there is a new backend api: `/wsapi/prolong_session` - it takes no arguments, must be invoked via POST, and requires the user to be authenticated.

This API should be invoked when the user answers "YES" to the question "is this your computer".  it will reset the cookie on the user's computer to have a long duration (2 weeks).  

Making this change will let a user who uses browserid a couple distinct times within an hour, and answers the "is this your computer" question, to not be prompted for re-auth within an hour.

**Comment by jrgm** [comment]
verified in stage train-2012.04.11
