### ISSUE TITLE
New API does not work with IE8 - IE8 does not have document.createEvent('Event');

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1357]
in include.js, IE8 is trying to create an event using `document.createEvent("Event")`  IE8 does not have this.

We have to do some feature-query event-fu:

http://stackoverflow.com/questions/827716/emulate-clicking-a-link-with-javascript-that-works-with-ie

We could:

```
var evt;
if(document.createEvent) {
      evt = document.createEvent('Event');                                                                                  
      evt.initEvent(type, true, true);
}
else if(document.createEventObject) {
      evt = document.createEventObject();
}

if(evt) {
     if (params) {
     ....
```

If the user is using IE8 to sign in to beta.myfavoritebeer.org, an error is shown in the developer tools, but the user can still sign in.

**Comment by lloyd** [comment]
blocked by issue #1354

**Comment by jrgm** [comment]
Verified with IE8 on train-2012.04.11 on stage. No errors and successful signup, signin.
