### ISSUE TITLE
BrowserID verify should return the correct status codes

### ISSUE THREAD

**Issue by graingert** [mozilla/persona#1362]
400 Bad Request and 415 Unsupported Media Type should be returned as appropriate

eg {"status":"failure","reason":"Content-Type expected to be one of: application/x-www-form-urlencoded, application/json"} should not be 200 OK

**Comment by jrgm** [comment]
This was pull request GH-1363. Closing and verified on stage from train-2012.04.11 with quick and dirty script. 200 OK but status: failure, reason: malformed for a bad assertion, 200 OK for valid assertion/audience, 415 for invalid CT, 400 for missing audience or assertion.

**Comment by seanmonstar** [comment]
Why can't the status code be returned on this line: https://github.com/mozilla/browserid/pull/1363/files#L0R107

It's certainly not 200 OK. It's either 5xx, or if we sent the wrong info, at least call it a 4xx.

**Comment by graingert** [comment]
no it's a 200 OK if the certificate is invalid, because this is a validator.
A failure due to an invalid assertion is OK because it's the expected behaviour of a validator:

Neither the calling party nor the web server have made an error, nor is it a redirect. ergo 2xx.

**Comment by graingert** [comment]
We need logic to confirm if it's a valid format certificate but not valid for that user: 200 ok
OR an badly formatted document: 400 Bad Request
OR a server error 5xx
