### ISSUE TITLE
BrowserID does not support internationalized emails RFC 6530

### ISSUE THREAD

**Issue by graingert** [mozilla/persona#1370]
Using an email with unicode characters fails, eg `test@example.бг` or `Rδοκιμή@gmail.com` the JS shim alerts that "This field must be an email address."

https://tools.ietf.org/html/rfc6530

At some point the domain should be converted to punycode, at what point is this?

**Comment by graingert** [comment]
This also brings up issues where `test@xn--hxajbheg2az3al.xn--jxalpdlp` must be considered the same as `test@παράδειγμα.δοκιμή` throughout the BrowserID stack

**Comment by shane-tomlinson** [comment]
@graingert - thanks - this is a duplicate of #1294, closing this one and keeping the original open.
