### ISSUE TITLE
Account selection is skipped

### ISSUE THREAD

**Issue by st3fan** [mozilla/persona#1378]
When logging in, the account (email) selection is skipped. Here is the flow that I now get:

1) Enter Email
2) Hit Next
3) Enter Password
4) Hit Login
5) BrowserID is now done and the app (Pancake in this case) is logged in.

Previously there was a step after logging in where you could select the account to be used. (I have two)

When I logout of the app and then login again through BrowserID, I do get the screen that allows me to choose the specific email address.

This happens both on Desktop and iOS for me.

**Comment by jrgm** [comment]
@jbonacci There is https://github.com/mozilla/browserid/issues/1241 about having a chance to check the (soon to be obsolete) "keep me signed in" checkbox. 

But as for this bug, this is, I believe, the designed UX.

**Comment by shane-tomlinson** [comment]
@jrgm, @jbonacci, @st3fan - thanks for writing this up & subsquent comments - skipping the email picker is indeed "By Design."  The original issue is #198, the pull request is https://github.com/mozilla/browserid/pull/1162.
