### ISSUE TITLE
Logging in on iOS is slow

### ISSUE THREAD

**Issue by st3fan** [mozilla/persona#1379]
On an iPad 3, logging in takes about 20 seconds in the 'Finishing Sign In...' screen. On older iPads this this more than 30 seconds. Is there a way to speed this up?

**Comment by benadida** [comment]
really? That seems quite slower than what I've seen. ipod touch test just now runs in 5 to 7s. Maybe this is a webview thing where the optimized JS engine doesn't kick in?

**Comment by st3fan** [comment]
Yeah that could very well be the cause. We've seen 4x slowdowns in UIWebView.

**Comment by benadida** [comment]
so this should be a good bit better when we move back down to 1024-bit DSA keys. Soon.

**Comment by benadida** [comment]
@jbonacci this is likely a webview issue. Testing this will require pancake, in all likelihood.

**Comment by zvalteau** [comment]
I just signed in and there was nothing slow about it with a iPad 2.

**Comment by lloyd** [comment]
please try again in dev.diresworb.org, we've moved to 1024 keys there.  This should address the problem, please reopen if timing still unacceptable.

**Comment by skinny97214** [comment]
Sign in has to be under 10 seconds or it's a no go.

**Comment by st3fan** [comment]
@jbonacci It is super fast on the iPad now. However, I have not been able to test the full login yet because I get stuck on issue #1395
