### ISSUE TITLE
IE6 and IE7 errors in communication frame

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1390]
STR

1) Open IE6
2) Go to local dev RP
3) Double click error icon in bottom left of browser chrome.

Many errors:

```
Line: 245
Char: 34
Error: Exception thrown and not caught
Code: 0
URL: http://10.246.29.67:10001/
```

```
Line: 3347
Char: 12
Error: Expected identifier, string or number
Code: 0
URL: http://10.246.29.67:10002/communication_iframe
```

```
Line: 9
Char: 7
Error: 'localStorage' is undefined
Code: 0
URL: http://10.246.29.67:10002/communication_iframe
```

```
Line: 233
Char: 38
Error: Exception thrown and not caught
Code: 0
URL: http://10.246.29.67:10002/communication_iframe
```

**Comment by lloyd** [comment]
I'm going to ignore this issue for now, it looks like shane's pull request would cover it.  If it looks like that PR (issue #1392) will not land, please reassign this back to me and I'll craft a patch targeted at dev.

**Comment by jrgm** [comment]
I still have two errors (either ie6 or ie7):

Line: 3347
Char: 12
Error: Expected identifier, string or number
Code: 0
URL: http://10.250.4.157:10002/communication_iframe

Line: 233
Char: 38
Error: Exception thrown and not caught
Code: 0
URL: http://10.250.4.157:10002/communication_iframe

However, I see from https://github.com/mozilla/browserid/pull/1411#issuecomment-5038350 that the presence of some errors is expected? Are the above a concern? The dialog does show the unsupported screen when popped.

**Comment by shane-tomlinson** [comment]
@jrgm - I can verify there are errors in IE6/IE7 on myfavoritebeer.org from prod, but they are not the same as these.  Which branch are you testing from?

**Comment by shane-tomlinson** [comment]
Also issued pull request to myfavoritebeer.org: https://github.com/lloyd/myfavoritebeer.org/pull/56

**Comment by jrgm** [comment]
I was on train-2012.04.11

**Comment by shane-tomlinson** [comment]
This was merged in to dev with PR-1506.  Closing.

**Comment by jrgm** [comment]
So, GH-1530 is closed/verified as WONTFIX for myfavoritebeer, so I'll take @jbonacci's comment above and my testing as verified for stage train-2012.04.27
