### ISSUE TITLE
Communication frame does not check for min browser requirements

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1391]
This causes exceptions to be thrown and not caught in IE6/IE7 or IE8+ in Quirks mode.

See issue #1390

**Comment by lloyd** [comment]
Reassigning to @shane-tomlinson as I expect this is related to pull request #1392.  If I'm wrong, please reassign back to me and I'll fix in dev.

**Comment by shane-tomlinson** [comment]
@lloyd - one problem with IE6/IE7 and IE8 in quirks mode is that the communication frame is doing a Channel.build, which checks for the existence of window.localStorage, window.postMessage and window.JSON.  These items do not exist in the older IEs and an exception is thrown.

Since the communication iframe was not included by default before, we did not run into this problem.  We would have seen it on myfavoriteshow, but it looks like nobody checked.

#1392 does not cover this.

I would take care of this by putting a try/catch around the Channel.build, but you often times have a more elegant solution. I am assigning back to you to get the notice, can you either take care of it or assign back to me?

There may be other problems on top of this, but I am fairly certain this is the main problem.

**Comment by lloyd** [comment]
@shane-tomlinson cool!  thanks for the clarification, I'll fix it and offer up a PR for your review.

**Comment by jrgm** [comment]
As noted in https://github.com/mozilla/browserid/issues/1390#issuecomment-5253093, I still have errors about 
communication_iframe on ie6/ie7

**Comment by shane-tomlinson** [comment]
Closing, PR-1506 fixes this issue.
