### ISSUE TITLE
dev: .logout() function missing a callback argument

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1399]
One feature of the current API is that .logout() accepts a single, optional callback argument.  Currently in dev this argument is not present, and breaks myfavoritebooze.org.

**Comment by jrgm** [comment]
verified stage train-2012.04.11 works fine with all browsers on winxp/win7/osx/ubuntu/android2.2(droid2)/android3(tablet)/android4(nexus) for beta.myfavoritebooze.org
