### ISSUE TITLE
remove 'Logout from all websites' from management page

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1400]
This feature (visible at time of writing at https://dev.diresworb.org/ when you're logged in) was added as a partial implementation of issue #1196.

@skinny97214 has advised that this is actually a misfeature, and in its partially implemented state it's confusing.  Also, because the new APIs it requires are experimental, it's inappropriate to add this feature at this time.  

We should remove the partial implementation from the management page.

**Comment by jrgm** [comment]
verified. train-2012.04.11, feature is gone.
