### ISSUE TITLE
dev: error shown in dialog after confirming your computer

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1405]
reported via email:

"I got this when I clicked "Yes" in response to "Is this your computer?" while signing up for the first time.
http://d.pr/9BLk"

reproduced via 123done.org

**Comment by Zarel** [comment]
I was the one who reported this on the ML, so I might as well add myself to the issue. Hello!

I got this issue while signing up with a Gmail address.

**Comment by lloyd** [comment]
successfully reproduced via STR in issue #1406

**Comment by jrgm** [comment]
verified on ff/chrome/safar/ie8/ie9/android2.2(stock,FF)/android4.0(stock,FF) not getting this error with train-2012.04.11
