### ISSUE TITLE
dev: "Is this your computer" should not be asked during first sign-up

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1406]
report: "When I click the confirmation e-mail, it tells me something along the lines of "You've been logged in, you can now go back to 123done.org". But when I go back to the 123done.org tab, I'm not logged in yet; I need to go find the popup and respond to the "Is this your computer?" question before it logs me in."

@shane-tomlinson - any ideas how to elegantly surpress the question during initial sign-up?

steps to reproduce:
1. open a clean profile or enter private browsing / incognito mode
2. click signin on 123done.org
3. go get a cup of coffee for more than 60s
4. now click the verification link in your email and enter a username and password
5. notice that rather than signing you in, the dialog asks you The Question

This sucks because the user has to find the dialog post verification, and this was not our design intent.

**Comment by jrgm** [comment]
verified on stage from train-2012.04.11. The user is not asked the question on initial signup/signin. A signin 60 seconds 
subsequent to the first appearance of the user will cause the user to be asked 'is this your computer'.
