### ISSUE TITLE
Give jbonacci and tchung more access

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#142]
Hey team,  Identity QA would like to request more access and permissions to this site.   Currently, neither James or I receive any emails or notifications when issues are created and updated.

Please grant access to us.  
Thanks!  Tony

**Comment by lloyd** [comment]
check this: https://github.com/account/notifications

under _issues_ are several knobs to toggle notification options.  I think the interesting one is "new emails for issues in _my_ repositories".  I'll add you and jbonacci as owners of the repo, you guys check that, and we should be good, right?

**Comment by lloyd** [comment]
Hey @tonychung,

I created a new github team, `identity-qa` and gave you guys push and pull access on the repository.  This combined with "new emails for issues in my repositories" _should_ get you guys emails for issues.  Please test it out and re-open if anything is not right!

Here's the new team for reference: https://github.com/organizations/mozilla/teams/78529

**Comment by lloyd** [comment]
@jbonacci - you're getting notifications now for new issues opened by people other than yourself?

**Comment by lloyd** [comment]
reopened.  created **[a new issue to test that theory](https://github.com/mozilla/browserid/issues/143)**, please close this issue if you got an email.  please comment if you didn't

**Comment by lloyd** [comment]
cool! tony reports it's fixed: https://github.com/mozilla/browserid/issues/143#issuecomment-1768100

For the record, in order to get notifications for a repository owned by an organzation, you must have at least push & pull access to the repository and have notifications enabled for "new issues in my repositories".

closing.
