### ISSUE TITLE
consider never revealing userid

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1421]
we implemented new features around shared computers, and while implementing that we needed a stable identifier for users on the client (to record whether they had confirmed that this is their own device).  For the first time we reveal a user's own integer "userid" to them via the WSAPI.

There are alternate implementation tactics that we should explore to see if we can not reveal our internal userids.  While no known weakness is really introduced by this, why expose internal identifiers if there is another viable implementation tactic that works just as well?

/cc @benadida

**Comment by lloyd** [comment]
@benadida if you think of a real weakness this introduces, up prio.

**Comment by shane-tomlinson** [comment]
Dup or #1993, closing
