### ISSUE TITLE
better error reporting for bad email/origin in stage_user, stage_email

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1423]
From a quick IRC conversation. If the input email or origin in a request to stage_user or stage_email is invalid an exception is throw in process(), and ultimately logged as a 500. The suggestion is to report/respond as something less than Internal Server Error, or as @fetep said "5xx == page ops". (I realize though, that the current way is the most expedient). 
STR: use scripts/create_account.js to send in invalid content for email or site.

**Comment by jrgm** [comment]
@fetep also mentioned that "it might be worth a CEF log"

**Comment by jedp** [comment]
I've opened #2131 for the overall CEF logging that @jrgm refers to

**Comment by lloyd** [comment]
Ok, I think everything in this issue has been addressed, with the CEF logging bug, and the new API param validation we've implemented.  closing.
