### ISSUE TITLE
Posssible incomplete string

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1425]
One of the new strings in train 2011.04.11 ends with a whitespace:
"If you're at a public computer such as a library or internet cafe, we'll ask you "

Is it possible that this string is not complete?

Should it end with "we'll ask you to log in every time"?

/cc @ozten @shane-tomlinson @lloyd @jbonacci

**Comment by lloyd** [comment]
we'll get this fixed today.

**Comment by lloyd** [comment]
@mathjazz it will take a couple hours to deploy this, stay tuned

**Comment by mathjazz** [comment]
OK, I'm extracting and merging strings now...

**Comment by jrgm** [comment]
verified in code for branch train-2012.04.11, and it is available and already translated as a single line in at least de and el
at https://localize.mozilla.org/projects/browserid/
