### ISSUE TITLE
Update preview server

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1427]
The preview server has to be updated for train-2012.04.11.

Currenlty, http://temporary_preview.myfavoritebeer.org/ still shows the old code.

/cc @fetep @ozten

**Comment by lloyd** [comment]
we'll get this fixed by EOD so localizers can test!

**Comment by lloyd** [comment]
working on this now...  sorry for the delay, was hoping I could get access to the current preview server, but I'll just deploy a new one.

**Comment by ozten** [comment]
I thought that https://bugzilla.mozilla.org/show_bug.cgi?id=723775 would be fixed last week, which makes temporary preview obsolete. I've pinged for status on that bug.

**Comment by ozten** [comment]
Ran into a non-ff issue with updating. Destroying and re-creating. I'll update this issue when temporary_preview is ready.

lloyd: I'll add you to the new VM ssh keys. Sorry about that.

**Comment by lloyd** [comment]
Np, I tried to get this done before/over the weekend and failed.

--lloyd

**Comment by ozten** [comment]
http://temporary_preview.myfavoritebeer.org/ is ready.
Please let me know if there are any issues with it.

I haven't added lloyd yet, will ping him out of band.
