### ISSUE TITLE
'Add new email address' screen should show user notification while getting 'email_info' being called.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1433]
This would be similar to how it is done on the sign in page, otherwise the user is left in the dark as to what is occurring.

**Comment by seanmonstar** [comment]
Should that be `address_info`? Also, I don't even see notification on the sign in page; perhaps the request is too quick.

**Comment by shane-tomlinson** [comment]
@seanmonstar - you are right, it should be address_info.  The notification I am talking about here is in the add_email address screen of the dialog, see resources/static/dialog/controllers/add_email.js.  As a reference, this is done in the authentication screen, see resources/static/dialog/controllers/authentication.js

**Comment by jrgm** [comment]
verified in train-2012.07.06
