### ISSUE TITLE
Clear the email field when adding a different email address

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#1435]
We should clear the email field when adding a different email address to the sign in box.   Currently, it retains the last email you typed, and then the user clicks "Verify email", they'll get the popup notice saying an email was just sent.

Screenshot: http://i.imgur.com/rUyPx.png

Repro:
1) log onto beta.myfavoritebeer.org or www.myfavoritebeer.org
2) Click sign in, type in an email, click Next
3) click Verify email.   check your email screen appears.  click " use another email address. "
4) Verify sign in screen refreshes, but your last email address still remains in the textbox.   

Expected:
- clear the textbox when adding another email address

Actual
- email field is prefilled with last email address you used.

**Comment by lloyd** [comment]
this is as designed, assuming that the case that the user mistyped the password is sufficiently common, and deleting the email is sufficiently easy.

```
 11:10 < skinny> stomlinson: 1435 is fine as designed
```
