### ISSUE TITLE
load_gen no longer works against stage due to new 'ephemeral' post argument

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1436]
I briefly started up a load_gen from client5 against stage, but immediately aborted when it spewed these errors:
    error: (signin) can't authenticate: SyntaxError: Unexpected token B

On the stage webhead, it was reporting this sort of thing on each request for /wsapi/authenticate_user:

{"level":"warn","message":"bad request received: missing 'ephemeral' argument","timestamp":"2012-04-14T03:13:33.631Z"}
{"level":"info","message":"127.0.0.1 - - [Sat, 14 Apr 2012 03:13:33 GMT] \"POST /wsapi/authenticate_user HTTP/1.0\" 400 41 \"-\" \"-\"","timestamp":"2012-04-14T03:13:33.632Z"}

I hacked around that, but hit other related errors, so I'm punting to @lloyd  for a refresh of load_gen to do this the right way. 

(Note: may be 5-star, but doesn't necessarily need a new push of train-2012.04.11 as this could be fixed on dev for just load_gen).

**Comment by lloyd** [comment]
fixed in dev and `train-2012.04.11` - @jrgm please confirm!

**Comment by jrgm** [comment]
verified works now with either train-2012.04.11 or current (as of 8 hours ago) dev branch.
