### ISSUE TITLE
[Safari/Win32] frontend unit tests flaky on second or later run 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1441]
I bumped into this oddity. Reproduced on Safari/5.1.5/Win7 and Safari/5.1.2/WinXP but not on any other OS/Browser combination, and to clear not with Safari/5.1.5/OSX. 

If I "reset Safari" and then load the front-end tests, they pass everytime on first run. But on a reload of the page, there are consistently some failures like the below (sometimes more than than 3, sometimes less). But always about "There is no template at ...". 

If I click the link to "Rerun", those always pass. Dunno. Some kind of caching issue? Or a bug in ejs.js?

Probably not a high priority.

---

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.5 Safari/534.55.3

Tests completed in 103567 milliseconds.
998 tests of 1001 passed, 3 failed.

controllers/check_registration: user validation with mustAuth result (1, 0, 1)Rerun
Died on test #1: There is no template at /dialog/views/confirm_email.ejs - { "type": "EJS", "message": "There is no template at /dialog/views/confirm_email.ejs", "line": 71, "sourceId": 2142725152, "sourceURL": "http://10.0.129.2:10002/lib/ejs.js" }

controllers/verify_primary_user: create with privacyURL and tosURL defined - show TOS/PP (1, 0, 1)Rerun
Died on test #1: There is no template at /dialog/views/verify_primary_user.ejs - { "type": "EJS", "message": "There is no template at /dialog/views/verify_primary_user.ejs", "line": 71, "sourceId": 2142725152, "sourceURL": "http://10.0.129.2:10002/lib/ejs.js" }

controllers/primary_user_provisioned: start controller with `add: false` and XHR error displays error screen (1, 0, 1)Rerun
Died on test #1: There is no template at /dialog/views/primary_user_verified.ejs - { "type": "EJS", "message": "There is no template at /dialog/views/primary_user_verified.ejs", "line": 71, "sourceId": 2142725152, "sourceURL": "http://10.0.129.2:10002/lib/ejs.js" }

**Comment by seanmonstar** [comment]
It looks like Apple dropped Windows support with Safari 6. Will it remain part of our browser support?

**Comment by jrgm** [comment]
Well, I can't reproduce this anymore with safari 5.1.7 on win7, so I'm closing this issue. 

As for what we will support, I think we will want to try to support safari5 in the short run. If Apple makes a more official statement that safari5 is unsupported (as in no security fixes) we would drop it.
