### ISSUE TITLE
"is this your computer" can show when adding a new email address

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1446]
STR:

1) Create a new account.
2) Wait 60 seconds
3) Open dialog, add a new secondary address.
4) Verify address after 60 more seconds.
5) Uh oh.  "Is this your computer?" is displayed.

**Comment by jrgm** [comment]
verified on stage train-2012.04.27 for the above STR the 'is this your computer' is not displayed when adding the second
email address to the account. The question will be displayed the next time the dialog is used >60 seconds from then.
