### ISSUE TITLE
Assertion should be generated AFTER the "is this your computer" screen.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1460]
Right now, we generate the assertion THEN ask "is this your computer?"  Since the assertion is only valid for 2 minutes, this introduces an opportunity for the assertion to be invalid by time it reaches the RP and verifier.

Link to #1446

**Comment by jrgm** [comment]
@stomlinson is this distinct from GH-1446?

**Comment by shane-tomlinson** [comment]
@jrgm - this is a different problem than GH-1446.  This issue manifested itself when the user waited on the "is this your computer"? screen for more than 2 minutes, the user's assertion was expired before it was ever passed to the RP.

**Comment by jrgm** [comment]
Okay, I see now what I was missing when trying against current production (which does not have this fix).

Just noting these STR for posterity:
1) signup a new email address via myfavoritebeer.org
2) logout and wait >60 seconds
3) click sign in on myfavoritebeer.org and use that email address
4) When you get the screen with "Is this your computer". Wait >120 seconds.
5) Click yes or no

Against train-2011.04.11 (current prod) the login to myfavoritebeer.org does not succeed. With train-2011.04.27 on beta.myfavoritebeer.org and diresworb.org, the login will succeed.

**Comment by jrgm** [comment]
So, I've been through the above STR on Win7/WinXP (IE9/IE8,Chrome,FF,Opera,Safari), OSX (Chrome,Safari,Opera,FF), Ubuntu (Chrome,FF,Opera), Android4.0 (Stock,FF,Aurora), Android2.2 (Stock,FF), IOS5 (Safari) and don't have a problem (and also no problems in general with signup/signin/the-question when not waiting out the 2 minutes in answering the question). verified for train-2012.04.27
