### ISSUE TITLE
[ie8/ie9] IE reporting a problem with test check_registration: user validation with mustAuth result

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1464]
On both ie8(winxp) and ie9(win7) the browser detects an uncaught exception for
http://host:port/test/?filter=controllers%2fcheck_registration%3a%20user%20validation%20with%20mustAuth
The test itself reports as passed.

**Comment by jrgm** [comment]
This is of course related to GH-1440

**Comment by jrgm** [comment]
And just to be clear, the fix for GH-1440 for those STR does work in ie8 and ie9 (and other).

**Comment by shane-tomlinson** [comment]
@jrgm - are you seeing the following:

```
SEC7111: HTTPS security is compromised by http://testmob.org/include.js 
index.html?filter=controllers%2fcheck_registration%3a user validation with mustAuth
```

**Comment by jrgm** [comment]
I didn't notice that. In MS dev tools console? I'll look again.

**Comment by jrgm** [comment]
This is on train-2011.04.11 branch

**Comment by shane-tomlinson** [comment]
@jrgm - I am now seeing:

```
SCRIPT5022: authenticate triggered more than once 
helpers.js, line 28 character 9
SCRIPT5022: authenticate triggered more than once 
helpers.js, line 28 character 9
```

**Comment by shane-tomlinson** [comment]
@jrgm - excellent catch, thanks!

**Comment by jrgm** [comment]
Okay, so I don't have this error now with ie8 or ie9 and a local pull of the latest for train-2012.04.11. @stomlinson did you mean to close this, or has the fix not been merged back to dev branch yet?

**Comment by jrgm** [comment]
Ah, so, duh, I see in https://github.com/mozilla/browserid/pull/1490#issuecomment-5308907 that this does not need to 
backported to dev. So I'm going to close and call it verified
