### ISSUE TITLE
clicking the sign-in button in dialog doesn't always work

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1471]
when I pop up the sign in dialog, and click on the sign in button as fast as I can, 1/5 times the first click does not register, and I must click the sign in button again.

STR:
1. log in with browserid to the in-tree example rp
2. repeatedly sign into example RP as fast as you can, clicking in-rp then sign-in in dialog

I believe that this might be what is causing our automated selenium tests to fail sometimes.

**Comment by stephendonner** [comment]
+1

**Comment by shane-tomlinson** [comment]
is this related to #1581?  If so, I put in a fix today with pull request 1583

**Comment by lloyd** [comment]
I believe this is a duplicate of issue #1581
