### ISSUE TITLE
Scroll bar shows in dialog in FF for Windows

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1473]
As reported by Zac Campbell

https://skitch.com/set117/8wu5b/scrollbar-windows

**Comment by shane-tomlinson** [comment]
My Firefox for Windows 7 looks like:

![Firefox for Windows - Without Scroll Bar](https://img.skitch.com/20120605-k989diudd8jqcfk18purjr31c6.png)

**Comment by zacc** [comment]
I can't replicate this anymore either.

**Comment by shane-tomlinson** [comment]
Closing, thanks @zacc for confirming.
