### ISSUE TITLE
The items under the list on the emails list dialog should not be scrollable

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1476]
OS: Win 7
Browser: Firefox 13.0

STR:
1. Load http://beta.myfavoritebeer.org/ in the browser.
2. Sign into an account with more than 5 email addresses.
3. Observe the emails list dialog.
4. Click the scrollbar displayed on the dialog and scroll it up and down.

The links, text and buttons displayed under the emails list are scrolled with the list. Only the emails list should be scrollable.

**Comment by shane-tomlinson** [comment]
@ioanab - This is by design. On a mobile device in landscape mode keeping the buttons on screen means the user can only view 2 email addresses at a time in their scroll window.
