### ISSUE TITLE
optimize all browserid images

### ISSUE THREAD

**Issue by lookfirst** [mozilla/persona#1477]
Freely available tools like [ImageOptim](http://imageoptim.com/) should be in every web developers toolkit and should be used to optimize all of the images that browserid serves up.

For example, [sign_in_orange.png](https://browserid.org/i/sign_in_orange.png) got a 2.2% reduction by simply dragging and dropping it onto this application.

**Comment by lloyd** [comment]
+1  after we rebrand we should optimize all images.

**Comment by fmarier** [comment]
Other relevant tools:

pngcrush -q -rem gAMA -rem alla -rem text example.png example.crushed.png
optipng -o9 -q example.png
advpng -z -4 -q example.png

gifsicle -O2 -b example.gif

jpegoptim -p --strip-all example.jpg

**Comment by lookfirst** [comment]
@fmarier ImageOptim is just a wrapper around all those tools with a nice drag/drop interface.

**Comment by shane-tomlinson** [comment]
Done with 64d83af.  Closing.
