### ISSUE TITLE
[chrome/win7] tiny cosmetic pixel gap in arrow in /sign_in dialog

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1478]
![img](https://img.skitch.com/20120421-qdfydqtxhcip9fnpnwueqrc49b.png)

**Comment by shane-tomlinson** [comment]
@jrgm - Thanks for the report - I am unable to reproduce this in Chrome on Win7, WinXP or OSX.  Is this a specific version of Chrome?

**Comment by jrgm** [comment]
This is with Chrome 18.0.1025.162, which is just whatever Chrome has pushed out recently to release channel.

**Comment by shane-tomlinson** [comment]
@jrgm - I am still unable to reproduce this on the same version of Chrome - https://skitch.com/set117/8ay6b/chrome-win7.  Is this still occurring?  Are you on 32 or 64 bit Win7?  Does this happen with dev?
