### ISSUE TITLE
should 24-hour expiry on 'denied' state trigger 'is this your question' immediately or just set to 'seen'?

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1479]
I'm not sure whether this is a bug, or actually intended to be the way it works. Anyways, I'd expect to be re-challenged for 'is this your computer?' immediately after 24 hours have elapsed after saying no on the initial challenge. (But since the 24-hour expiry sets the browser up for an eventual 'is this your question?', this is probably just a nit).

STR:
1. Use a clean profile (or private browsing, but didn't use that for this STR).
2. Load beta.myfavoritebeer.org and click sign in; complete signin process.
3. Wait >60 seconds, and then sign in via beta.myfavoritebeer.org. Click No to 'is this your computer?'.
4. Logout of beta.myfavoritebeer.org. 
5. Advance the system clock by 24 hours. (I was on ubuntu as the client so `sudo date -s tomorrow`).
6. Load beta.myfavoritebeer.org and click sign in; complete signin process.

Expected: I should be asked the 'is this your computer?' question. 

Actual: Signin completes without the question.

Notes:
- The browser has switched from the 'denied' state to the 'seen' state at step 6 (visible by inspecting localStorage on FF; sqlite3 webappsstore.sqlite "select \* from webappsstore2 where key = 'usersComputer'").
- Following on from the above STR; wait >60 seconds and try to sign in again. Now the dialog presents the 'is this your computer?' question and the user can choose yes or no.

**Comment by skinny97214** [comment]
The spec is

You should only see the challenge screen if you log into a new computer and then log in again more than 24 hours later. You should only see it one time per computer (unless you've cleared all saved devices, which is a feature we'll implement in the future.)

**Comment by seanmonstar** [comment]
I can't tell if that means this is working correctly or not. @jrgm?

**Comment by lloyd** [comment]
working as designed
