### ISSUE TITLE
[Chrome] exceptions thrown on /signup page when cookies disabled 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1484]
This is basically already covered in GH-1418, but chrome throws 'Uncaught Error: QUOTA_EXCEEDED_ERR:
DOM Exception 22' in two places when using the /signup page on diresworb.org (at lines 123 and 180
of resources/static/shared/storage.js).

**Comment by jrgm** [comment]
The reason I filed this bug as separate from GH-1418 is that this is a core problem with storage.js with cookies disabled in chrome.

**Comment by shane-tomlinson** [comment]
Labeling a 5\* because this is a regression.

**Comment by shane-tomlinson** [comment]
Closing, this issue is avoided entirely with PR 1489 which has been merged.

**Comment by jrgm** [comment]
verified on stage train-2012.04.27 specifically for Chrome (this issue was just about Chrome). Loading /signup (or any other path at diresworb.org) shows no js exception in the console.
