### ISSUE TITLE
dev rp throws exception if there is no requiredEmail

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1488]
STR
1. Load up dev RP in Chrome
2. Clear the requiredEmail field
3. Click "Get an assertion"
4. Check out the error.

The error is on line 174 of the sample RP's index.html, if there is no requiredEmail, there can be no requiredEmail.indexOf

**Comment by jrgm** [comment]
This was just a transient fix for GH-1437. Not a problem in stage train-2012.04.27 or prev train.
