### ISSUE TITLE
IE6/IE7: unsupported dialog shows unecessary scroll bar (and sometimes two!)

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1496]

**Comment by jrgm** [comment]
verified fixed on stage train-2012.04.11 for IE6 and IE7 (winxp).

**Comment by shane-tomlinson** [comment]
Closing since @jrgm has already verified.

**Comment by jrgm** [comment]
I was aware of the pull request to fix myfavoritebeer - https://github.com/lloyd/myfavoritebeer.org/pull/56 so I used 
beta.myfavoriteshow.org to bring up the dialog with cookies disabled on IE6 and IE7  -- there is no double scrollbar. 
There is a disabled scrollbar that looks acceptable to me.
