### ISSUE TITLE
invalid verification link error message is does not match other error messages

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1497]
https://skitch.com/set117/8ixsu/box-simpleshare

Should we make this the same style as other error messages?

**Comment by skinny97214** [comment]
Good catch. Yes, please make it match.

**Comment by lloyd** [comment]
kinda related to GH-218

**Comment by shane-tomlinson** [comment]
link to #1734

**Comment by jrgm** [comment]
veriified stage train-2012.06.22 - re-using a token, or using an invalid token bring up the new style error message.
