### ISSUE TITLE
Welsh not picked up for train-2012.04.11 release

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1503]
I see that Welsh (cy) was added for config/l10n-prod.json in GH-1498. However while https://localize.mozilla.org/cy/browserid/LC_MESSAGES/client.po/translate/ shows translated strings, a pull of http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/cy/LC_MESSAGES does not contain any for cy. And so this release will not have localized strings for Welsh. 

/cc @ozten, @mathjazz, @milossh

**Comment by milossh** [comment]
I can push this via Verbatim, the strings that are in there but not in SVN. What's the plan on this? Do we fix this now and push, or do we wait for the next train?

**Comment by ozten** [comment]
Sorry, we have to wait for the next train.

**Comment by lloyd** [comment]
blocker for dev

**Comment by jrgm** [comment]
Okay, welsh is now visible in production (or will be in about 30 minutes when we flip datacenters).
