### ISSUE TITLE
Make BigTent whitelist configurable

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1513]
On the bigtent branch, we need two pieces of configuration:
- proxy domain whitelist
- BigTent server

The proxy domain whitelist will initally be ['gmail.com', 'hotmail.com', 'yahoo.com']. We should also be able to have this be an empty list, so that the code can land on dev and be pushed to stage, but will be inert. This is effectively 'feature preferenced' off.

BigTent server is the endpoint that proxyidp emails will be sent to.

**Comment by ozten** [comment]
Fixed in the `bigtent` branch.
http://git.io/PkeipA

Leaving open till it lands on `dev`.

**Comment by shane-tomlinson** [comment]
@ozten, @callahad - Since BigTent is built, can this be closed?
