### ISSUE TITLE
/tos, /privacy no longer available with cookies disabled

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1514]
I hate to note this since closing off /signup, etc. is so much better. But it's a bit paradoxical that you have to enable cookies to view the Terms of Service and Privacy Policy.

STR:
- disable all cookies in the browser
- load https://dev.diresworb.org/tos

Expected: TOS text is shown
Actual: 'BrowserID requires cookies' is shown

Notes:
- Probably should also allow /about
- UA with no JS, can view with or without cookies (of course).

**Comment by shane-tomlinson** [comment]
This affects the staging with version:

```
1e49b9b update ChangeLog for train-2012.04.27
locale svn r104885
```

**Comment by jrgm** [comment]
Closing and verifying for stage train-2012.05.14 - /tos, /about, /privacy are viewable with cookies disabled, /signup, /signin, /forgot, /add_email_address, /verify_email_address display the 'BrowserID requires cookies' error screen.
