### ISSUE TITLE
code cleanup: move statsd measurement of bcrypt time into bcrypt

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1524]
currently we've got statsd timing for bcrypt scattered throughout wsapi/*.js.  Instead we should move this into the bcrypt module.

**Comment by shane-tomlinson** [comment]
Closing this as no longer a problem, the only place statsd.timing for bcrypt is called is `lib/wsapi.js`.

**Comment by shane-tomlinson** [comment]
I closed this because the code is in one place. It's not in bcrypt, but in /lib/wsapi.js, and not sprinkled throughout the various wsapis.
