### ISSUE TITLE
verifier doesn't recognize delegation of authority

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1527]
Using a test setup on delegator.org that points to dev.clortho.mozilla.org, everything goes fine until 
we go to check the assertion in https://github.com/mozilla/browserid/blob/dev/lib/verifier/certassertion.js#L137

We get
'dev.clortho.mozilla.org' may not speak for emails from 'delegator.org'"

I had manually tested this earlier, but I must have improperly tested it (?!?) or recent code changes in Vinz Clortho have broken this, which doesn't make as much sense.

**Comment by warner** [comment]
@ozten: this sounds familiar :). Maybe we can close this next week when we land that fix.

**Comment by ozten** [comment]
Note: Delegato.org and dev.clotho.mozilla.org are out of date.

delegat.es added in issue #2538

**Comment by ozten** [comment]
I would vote for 5 stars on this issue. We want to get this fixed by Wed AFAIK.

**Comment by ozten** [comment]
I am seeing this work in dev now with delegat.es. I didn't see that before because of clock drift blocking me from seeing the behavior.
