### ISSUE TITLE
Create KPI Backend Datastore

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1531]
As fleshed out in https://id.etherpad.mozilla.org/38

Create a data store capable of receiving interaction data in the form of JSON formatted blobs.

Phase I
Write API
Simple Read API over time period

Phase II (will do in another GH Issue)
Read API over time period with filtering support

BrowserID webheads will write to this Datastore

**Comment by jedp** [comment]
Started KPIggyBank (har har)
https://github.com/jedp/kpiggybank

**Comment by ozten** [comment]
Great work Jed!
