### ISSUE TITLE
clear password field if user changes email address in /sign_in dialog

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1540]
1. Go to 123done.org and click 'Sign in with Persona'
2. If already authed, click 'This is not me...'
3. Enter secondary email address that is known to diresworb.org and hit next.
4. In the password field enter 4 random characters. 
5. User now "realizes" they entered the "wrong" email address (albeit one that is known to diresworb.org)
6. User goes back and fixes the email address to be the "correct" one and hits next.

Expected: Password field is shown and empty
Actual: Password field is shown but contains the four previously typed characters.

This obviously is a very rare scenario and I can see an argument for leaving the previously typed characters should be kept
and letting the user decide what to do.

**Comment by lloyd** [comment]
blank it, shane!

**Comment by jrgm** [comment]
verified in current dev; still waiting for stage but lgtm.
