### ISSUE TITLE
implement password requirements

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#155]
Currently we have limited requirements on password quality.  We should pick some baseline password requirements and enforce them.  @jbonacci proposes:
1. 8 - 12 characters 
2. at least one capital
3. at least one number
4. at least one special character

I feel like this proposal is overly restrictive.  it would prevent a user from, for instance, using a four word phrase as a password.

other proposals?

**Comment by Natanael90** [comment]
Demanding certain characters will make things worse. I can match the above with this as password:

P4$$word

Now what we INSTEAD should do is to suggest longer passwords. See: https://www.xkcd.com/936/

**Comment by benadida** [comment]
I agree that the recommendations above are incorrect, _especially_ the maximum length.

Let's instead look into password entropy measurements that simply say "weak/good/strong".

**Comment by lloyd** [comment]
Given the response, I would propose that the only restriction we want to impose is a _minimum_ length.  I would propose we make this 8 chars.  This bug is about making that change, and we can open another to give the user weak/good/strong feedback.

**Comment by Natanael90** [comment]
8 characters is too little. I'd say +12. In a few years we might even have to set it to ~15.
If you really use passphrases anyway, that's not going to be a problem at all.

**Comment by ianb** [comment]
So paternalistic!  How many Chinese characters are necessary to make a strong password?  Is there an entropy detector that is good enough that we could simply say "not a weak password"?  Is it even our responsibility to thwart the user's attempt to create an account if we've informed them about the security level of their password?

**Comment by benadida** [comment]
@ianb yes I do think it's our responsibility to enforce that users choose a secure password. The other points you make are important though, e.g. Chinese characters.

**Comment by ianb** [comment]
Not actually being sure how passwords were used, I asked: https://plus.google.com/104537541227697934010/posts/aJ3p3bECD7V -- seems that ASCII passwords are the norm in other countries.

**Comment by stloyd** [comment]
I'm just curious. Why do you restrict user to have password lenght limit ? I understand why you require min. length but max. ? Do you wanna store them in plain text ? If not you **shound not** restrict max length or maybe just around 255 chars to not got system DDoSed.

**Comment by lloyd** [comment]
Hi @stloyd - Practically speaking do you believe there is a meaningful difference between 255 and 80 as an upper bound?

**Comment by Natanael90** [comment]
@lloyd: There's a chance people might have actual phrases as passphrases that could be +80 chars, but (more than) 255 is not just plausible. Sure, there's those people too, but it's not much to ask of them to cut their passwords down just a bit.
