### ISSUE TITLE
Chrome popup hangs on "Communicating with server"

### ISSUE THREAD

**Issue by ForbesLindesay** [mozilla/persona#1551]
This happens indefinitely and the console shows the error "Uncaught SyntaxError: Variable 'i' has already been declared"
To reproduce, simply sign into http://myfavoritebeer.org/ on chrome and press F12 to the the error

**Comment by shane-tomlinson** [comment]
@Tuskan360 - Thanks for the report - I too am unable to reproduce this, which version of Chrome are you using?  Which language do you have set?  Are your cookies enabled?

**Comment by ForbesLindesay** [comment]
I'm using version `18.0.1025.168 m`
cookies are enabled 
I've got the Last Pass extension installed
The error shows up in https://browserid.org/v/7e0b441f54/production/en_US/dialog.js

**Comment by jrgm** [comment]
I've also tried with chrome 19 and 20 builds, but I can't reproduce either.

**Comment by lloyd** [comment]
@jrgm please investigate and decrement priority at your discression

**Comment by jrgm** [comment]
@Tuskan360 can you enter about:flags in the urlbar in Chrome, and then search for 'Experimental JavaScript'? Does it show Enable or Disable? If it shows Disable, click that, restart Chrome and see if the error goes away. 

If I enable that flag and restart Chrome, I can reproduce this error. This pattern will trigger it:

```
<script>
(function(x) { "use strict"; var x = 1 })();
</script>
```

In my local build loading http://127.0.0.1:10002, I get two instances of this error, one in micrajax line 119, and another in shared/renderer.js line 16 that both have the above pattern. Whether Chrome interpretation of the spec is correct or not, I'll leave to the spec lawyers. I suppose our code could work around this bug, but not sure if we should.

**Comment by jrgm** [comment]
Okay, found the actual chromium bug report, which says it's a bug and fixed Feb 27, 2012, so probably in Chrome 19 builds. I think we can close this when @Tuskan360 confirms he had that flag enabled. http://code.google.com/p/v8/issues/detail?id=1942

**Comment by ForbesLindesay** [comment]
Yeh, sorry, forgot I'd enabled that a while back.  All now works fine :)
