### ISSUE TITLE
IE/dev: bidbundle.js uses 'const' which causes exception to be thrown

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1554]
line 2621 of bidbundle.js contains:

```
const jwcrypto = require("./jwcrypto"),
```

All variants of IE throw an exception here which makes both the main site and dialog unusable.

Link to #1552

**Comment by lloyd** [comment]
taking this

**Comment by benadida** [comment]
didn't @shane-tomlinson already fix this?

**Comment by benadida** [comment]
I distinctly remember merging a PR from him :)

**Comment by lloyd** [comment]
no, what needed to happen is jwcrypto needed to be published.  that's done, ths is fixed, IE has other problems..

**Comment by jrgm** [comment]
verified. At this time, jwcrypto 0.3.2 which is used with train-2012.07.30 and jwcrypto 0.4.1 which is with dev branch both contain no 'const' references (expect for a test in 0.3.2).
