### ISSUE TITLE
If user types wrong password in verify email screen, error dialog is displayed

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1557]
If the user types the wrong password in the verify_email_address screen, instead of getting a second chance to type their password, the user is shown the error dialog.  The user has to re-load the page to try again.

STR requires two browsers

1) In browser 1, open dev.myfavoritebeer.org.  Sign in to BrowserID with a new secondary account that must be verified.
2) In browser 2, open verification email.
3) Type incorrect password
4) Instead of a tooltip that displays "incorrect password", the user is shown an error screen.

**Comment by jrgm** [comment]
verified for stage train-2012.05.25. A tooltip is show to the user in browser 2 when they enter a password that does not match the password that was used in staging the user. 

Also closing this bug, since the code is there and works correctly.
