### ISSUE TITLE
ensure uncaught exceptions are logged

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1558]
we should make sure uncaught exceptions are properly logged, reported, and monitored.

**Comment by ozten** [comment]
Lloyd shared this scary blog post http://debuggable.com/posts/node-js-dealing-with-uncaught-exceptions:4c933d54-1428-443c-928d-4e1ecbdd56cb

**Comment by ozten** [comment]
Webdev is standardizing on [Sentry](http://sentry.readthedocs.org/en/latest/developer/client/index.html#a-working-example) for server side crash aggregation and analysis.

**Comment by lloyd** [comment]
we should get petef to set an alarm on .uncaught_exception statsd counters, which are implemented in 3d2ca1f

**Comment by lloyd** [comment]
https://bugzilla.mozilla.org/759251

**Comment by jrgm** [comment]
Confirmed with train-2012.06.08 on an awsbox and installing a sighup handler to generated uncaught exceptions (since I don't have  real way to force an uncaught exception).
