### ISSUE TITLE
[ie8] red line at top of screen for /signin

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1566]
Don't know how I didn't notice this little line before:

![img](https://img.skitch.com/20120510-8nqg9hqcwba4sek2x5gwn5wj48.png)

That is with IE8 in standards mode on a freshly created user account on winxp. Minor cosmetic thing.

**Comment by jrgm** [comment]
@lloyd I'm giving this to @shane-tomlinson  to consider fixing for final polish.

**Comment by seanmonstar** [comment]
This looks like it was with previous design. I don't see it in IE9 Compat Mode...

**Comment by jrgm** [comment]
This is still there with a real IE8 browser looking at login.dev.anosrep.org/signin. 

It's the &lt;noscript&gt; element styled here https://github.com/mozilla/browserid/blob/dev/resources/static/pages/css/style.css#L6

**Comment by jrgm** [comment]
Hmm, IE3. It did have the first CSS support ;-)

But no XP/IE8. I doubt it's VM v. PC issue. Could be subtle DLL differences, but the as I read the computed style with ie8 devtools, that red line should be there. 

Anyways, this was always a minor issue. 

(p.s., to be clear, you have to look at /signin, not just /).

**Comment by shane-tomlinson** [comment]
@jrgm, @jbonacci - Have I mentioned that you two have some awesome bug finding and debugging prowess?  I'll have a look as soon as I have access to my laptop again (the HD has taken a turn for the worse).

**Comment by shane-tomlinson** [comment]
Closing as fixed.
