### ISSUE TITLE
copy for screen that asks you to re-enter password

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1568]
If you're you set up a new account on one UA and verify your email, you see an extra screen that asks you to re-enter your password. This screen needs copy.

@lloyd can you post screenshot?

**Comment by lloyd** [comment]
case 1: creating a new account: https://skitch.com/lloydhilaiel/83rnm/browserid-complete-registration

case 2. adding an email to an existing account: https://skitch.com/lloydhilaiel/83rn2/browserid-verify-email-address

**Comment by lloyd** [comment]
target 5/9 sprint for copy
