### ISSUE TITLE
Certificate provisioning doesn't time out

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#1570]
When using primary IdPs on various demo sites which use diresworb I've seen a hang during provisioning.

It should not hang - if IdPs don't respond the way we expect (e.g., because they are using a shim that talks to a different domain), it should time out and fail.

**Comment by callahad** [comment]
Wow, I missed when this got fixed. Thanks @seanmonstar!

**Comment by seanmonstar** [comment]
@jbonacci i believe so. this merged a month ago, so 07.30 should have it, right?
