### ISSUE TITLE
Bad failure mode (hang) for production IdPs on dev/beta RPs

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#1571]
IdPs must be used with matching shim domains. Meaning a production IdP can't be used to sign in to a site pulling `include.js` from `dev.diresworb.org` or `diresworb.org`. The failure mode is a hang after typing in an email address, rather than an error, timeout, or fallback to the email dance.
#### Steps to Reproduce:
1. Visit http://123done.org/
2. Click "Sign in with Persona"
3. Type `foo@mockmyid.com`
4. Click "Next"
#### Expected Results:

"Address Verified! Your identity has been verified with your email provider, we will now try to sign you in."
#### Actual Results:

Hang at "Please hold on while we get information about your email provider." The "Next" button is still active, but clicking it has no visible effect.

**Comment by callahad** [comment]
Eyedee.me had to add special casing to support use across all environments: https://github.com/lloyd/eyedee.me/blob/master/bin/eyedeeme#L83-112

**Comment by callahad** [comment]
...And both myself and @vthunder have botched demos because we forgot about this. :)

**Comment by lloyd** [comment]
the portion of this bug about a graceful failure when provisioning doens't complete is captured in #1570

this bug then is specifically about making it clear what hosts you can rely on for demonstrations.

**Comment by seanmonstar** [comment]
with #1831 closed, what is outstanding for this?

**Comment by callahad** [comment]
I think at this point, it's just noting somewhere on MDN that:

When testing,

eyedee.me can be used against these Persona instances: ?

mockmyid.com can be used against these Persona instances: Production only.

**Comment by shane-tomlinson** [comment]
Both mockmyid.com and eyedee.me work with dev/beta now. Closing.
