### ISSUE TITLE
Can't login @ www.browserid.org due to Firefox security exception

### ISSUE THREAD

**Issue by AxelNennker** [mozilla/persona#1573]
I created an account at eyedee.me and tried to use it at https://www.browserid.org/.
I now find this error message 
"Sicherheitsfehler: Inhalt auf https://browserid.org/ darf keine Daten von https://www.browserid.org/signin laden." 
in Firefox 12 error console.
The UI experience is such that nothing happens when I press "Sign In". I am still not logged in.
The translation of the error message is: 
“security error: content from https://browserid.org/ is not allowd to access data from https://www.browserid.org/signin“

The "Sign In" works on "https://browserid.org/" although the error message is still in the error console.
It does NOT work on https://www.browserid.org/

I just retried this on a different computer (same Firefox version) and get these error message in the console (no login).
Sicherheitsfehler: Inhalt auf https://eyedee.me/ darf keine Daten von https://www.browserid.org/signin laden.
Sicherheitsfehler: Inhalt auf https://browserid.org/ darf keine Daten von https://www.browserid.org/signin laden.

My User Agent string is:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0

**Comment by lloyd** [comment]
we need www.browserid.org to cname to browserid.org

I'll open a ticket for this today or tomorrow.

**Comment by lloyd** [comment]
(user facing workaround for now is to use browserid.org, omit www.)

**Comment by AxelNennker** [comment]
Or do some mod_rewrite magic if you control the httpd but not the DNS?
I guess there is something like mod_rewrite for node.js

-----Original Message-----

**Comment by seanmonstar** [comment]
now that we use https://login.persona.org, this doesn't seem like it's still valid. reopen if it is.
