### ISSUE TITLE
IE8 don't work on dev

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1574]
At the moment we attempt to generate an assertion from within the dialog (after signing in), an error is displayed: "we're sorry, but an error has occured".

This affects IE8 on winxp, but not IE9, nor IE9 in IE8 mode.

**Comment by lloyd** [comment]
blocked on this upstream fix in jwcrypto: https://github.com/mozilla/jwcrypto/pull/17

/cc @benadida

**Comment by jrgm** [comment]
verified stage train-2012.05.14 - I can use xp ie8 without errors.
