### ISSUE TITLE
IE8 warning dialogs on dev: unresponsive script

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1575]
STR:
1. cause IE8 (not simulated IE8, the real one) on winxp to generate an assertion.  notice the unresponsive script errors.
2. that is all

we need setTimeouts, and I got just the spot.  /cc @shane-tomlinson @benadida 

@benadida did you test the relative performance of jwcrypto before and after your latest changes?

**Comment by benadida** [comment]
@lloyd I did not, but I didn't change the crypto algs either.

**Comment by benadida** [comment]
@lloyd I wonder if one of the timeouts got squashed somewhere...

**Comment by lloyd** [comment]
problem is inside getAssertion in user.js

loadSecretKeyFromObject() is taking 2.2s on my virtualbox winxp vm using IE8

everything else (assertion.sign, cert.bundle) takes about 1.1s in the same env.

If I insert a `setTimeout` between these two operations, in my env at least, I don't see the unresponsive script errors.

**Comment by lloyd** [comment]
```
$ git diff origin/train-2012.04.27..origin/dev -- resources/static/shared/user.js
```

@benadida - we just borked the port and dropped the setTimeout.  That's not to say we haven't regressed in performance, but it says we haven't _significantly_ regressed.

**Comment by jrgm** [comment]
verified in stage train-2012.05.14 - ie8 on winxp is not showing significant delays in generating the assertion.
