### ISSUE TITLE
prefill name and photo when setting up second email

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1577]
For the additional emails that a user adds, the name and photo will be prefilled. If the user closes the dialog, those values should not be associated with that account. Grab the name and photo from the first account. If the first account doesn't have values, grab from the second and so on.
#880 is the tracking bug

**Comment by skinny97214** [comment]
Initial state 
http://cl.ly/0I390s2D1l2J2v1W3f3R

On hover, the X on the corner of the picture is black
http://cl.ly/0I390s2D1l2J2v1W3f3R

When X is clicked, ajax fade to default picture and show an {undo} link that undoes the delete. 
http://cl.ly/2D3y08363r3x2n0g0o3J

**Comment by callahad** [comment]
As per #880, closing this until we decide to begin work on name-and-photo.
