### ISSUE TITLE
/forgot page needs some copy to explain why you need to enter a password when you've forgotten your password

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1578]
This dialog will be a bit confusing to most users. I just said I forgot my password and now it wants my password? What password? This is pretty much the same as GH-1568, but I'll make this separate since this is a much less commonly seen page on the main site and as a separate issue it can have a different priority for this train (or next). @jrgm

![img](https://img.skitch.com/20120511-nd2nkqcsec9nxygj7iff71c8ir.png)

It's even more curious if I try to continue with 'Reset Password':

![img](https://img.skitch.com/20120511-cq4ut4kdmkp3effdcjqkxbs4ja.png)

**Comment by shane-tomlinson** [comment]
Dup of #2023 which is the new tracker.  Closing.
