### ISSUE TITLE
(dev/next-train) dialog 'forgot password' screen missing some context about which email

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1580]
STR:
1. go to http://myfavoritebeer.org/ or http://dev.myfavoritebeer.org/, and click 'Sign in'
2. enter an email secondary address that is previously known to (browserid.org|dev.diresworb.org)
3. when you get prompted for a password, click 'forgot password'
4. Here's the difference. In prod 'reset password' shows the email address that will be reset; in dev, it lacks that context (perhaps this is intended, but it just struck me as curious).

In prod:
![img](https://img.skitch.com/20120511-fax8k3mirckfhm35atytfberne.png)

In dev:
![img](https://img.skitch.com/20120511-x6minenkihwdy96qrxjm34pdkf.png)

**Comment by skinny97214** [comment]
Agreed, we need a short bit of copy that says this is a password reset

**Comment by jrgm** [comment]
Actually, I was thinking that showing the email address (as it was before) would be good (what email address am I resetting).

**Comment by jrgm** [comment]
Actually, sorry, yeah, you're right. Both copy and what email should be there.

**Comment by billder** [comment]
The tricky thing here is overly associating a specific email address with the password. I'd like for people to associate the password with Persona, and not with one specific email address.

**Comment by shane-tomlinson** [comment]
closed by issue #1889.
