### ISSUE TITLE
dev/webkit: clicking on "sign in" in email picker causes button to shift right.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1581]
STR

1) Open Chrome or Safari
2) Go to dev.myfavoritebeer.org
3) Sign in with an account with multiple email addresses
4) Sign out of MFB
5) Click on an email address
6) Click on the left hand side of the "Sign In" button.
7) Watch the button shift - user must now click "Sign In" again.

I thought there was another issue about clicking the button twice, but I am unable to locate it.

**Comment by shane-tomlinson** [comment]
The button is shifted left by the width of the scroll bar that shows whenever there are too many email addresses.

**Comment by lloyd** [comment]
merged in, tested, so much better.  thank you shane.

**Comment by jrgm** [comment]
verified no shift as described in stage train-2012.05.14
