### ISSUE TITLE
"Is this your computer" screen is not keyboard navigable.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1582]

**Comment by fmarier** [comment]
In my desktop Firefox (12), it is kinda navigable but in a fairly painful way:
- I need to tab until the end of the page (then it wraps around)
- Eventually the focus ends up on the Yes button
- I can press Enter there and it works

**Comment by shane-tomlinson** [comment]
@jbonacci - This was only merged into dev last week, so this has not made staging yet.  In dev, I'm not seeing the behavior with Safari that you.  I go from the "Yes" button to the "No" button.  If I tab out from there, I have to hit tab once to get out of the URL bar, then once through each of the bookmarks, but I get back in.

**Comment by shane-tomlinson** [comment]
@jbonacci - I'm not sure where I was looking for the dates, this _is_ in stage.  I am still not seeing the Safari issues that you are writing about.

**Comment by shane-tomlinson** [comment]
@jbonacci - is this still a problem?  Safari for OSX is showing no signs of a problem for me.

Also, read http://stackoverflow.com/questions/2292016/is-there-a-workaround-to-safaris-operas-bug-that-you-cant-tab-through-hyperli?answertab=votes#tab-top

**Comment by shane-tomlinson** [comment]
Closing in favor of #869, which as @jbonacci points out, is more general than this.
