### ISSUE TITLE
add name and photo to manage page

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1588]
MOCK http://cl.ly/1n332N1V2s3Y2L2T3s18
#880 is the tracker

**Comment by skinny97214** [comment]
A little tweak to make it consistent with the upload UI that I used in the lightbox

USE THIS MOCK
http://cl.ly/2S0n0I2V463l0s423C3J

**Comment by shane-tomlinson** [comment]
@skinny97214 - we are starting off with a single name/photo combination for all email addresses to avoid too many changes in the dialog with contact cards.  The mock implies that each email address is getting its own name/photo.  Let's make contact cards stage two to go along with the backend sync once we get beta out of the way.

**Comment by shane-tomlinson** [comment]
@fmarier is now working on this experimentation, reassigning.

**Comment by skinny97214** [comment]
@fmarier Is this a 20% project for you? I have some date we collected in Sawyer's study that relates to this. Feel free to schedule me in on a Friday and I'll give you the debrief.

**Comment by fmarier** [comment]
The "spec" for what I started working on (backend only for now) is here ("card server"):

  https://wiki.mozilla.org/Identity/Architecture/IDAttachedServices#.22Card.22_server_.28used_by_the_dialog.29

and the code is here:

  https://github.com/fmarier/cardserver

**Comment by shane-tomlinson** [comment]
Closing this until we actually decide whether we are going to tackle this. We can re-open then.
