### ISSUE TITLE
(dev/train-2012.05.11) /signup: during signup, change from secondary to primary email is not handled correctly in UI

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1590]
STR (I was using dev for the upcoming 2012.05.11 train):
1. Go to the management site dev.diresworb.org and click signup
2. Enter a secondary email address that is not known to dev.diresworb.org
3. Click 'Verify Email'
4. Enter password twice. Do not click 'Verify Email' a second time (yet)
5. Realize you mistyped the email address; Edit the email address to now be a primary email address.
6. Click 'Verify Email'

Expected: primary email address is detected on the edit and flow changes to that path ("To verify that you own foo@example.com you must sign in with your provider. A new window will be opened"...

Actual: Email is sent to the primary email address to be confirmed on dev.diresworb.org (presumably).

**Comment by shane-tomlinson** [comment]
@jrgm This should be taken care of with PR #2161

**Comment by shane-tomlinson** [comment]
Close with merge of #2161
