### ISSUE TITLE
New train branched notice

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1591]
@lloyd Please let me know when the new train (train-2012.05.08?) is branched, so I can extract the strings.

**Comment by lloyd** [comment]
I'll branch today.

--lloyd

**Comment by mathjazz** [comment]
Hey @lloyd, any progress?

**Comment by lloyd** [comment]
branched `train-2012.05.14`.  I apologize for the delay, it's my fault, and mine alone :/.
