### ISSUE TITLE
train-2012.05.14 will break outstanding verification emails

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1592]
This train includes a fix for issue #1000, which will prompt users for their password inside the dialog, as opposed to after they click the verification link from their email.

As it stands right now, at the time we roll the train, all outstanding verification links will not work properly.

We must assess exactly how they will fail, and determine the impact and amount of user confusion that will ensue.  Depending on that assessment we should fix it, or derail.

**Comment by lloyd** [comment]
Dreaming up potential solutions:
1. make it so these users are prompted in the verification page for password.  
2. make it so signin succeeds, but users have to figure out reset password later 
3. invalidate verification links

**Comment by lloyd** [comment]
@shane-tomlinson and I assessed the cost of #1 - 

```
10:38 < lloyd> stomlinson: so me sending down a new bit in email_for_token is trivial
10:38 < lloyd> stomlinson: 10ish lines, max

10:39 < stomlinson> lloyd: the front end is going to require some HTML, some CSS, and some JS, plus a test or two.
10:40 < stomlinson> CSS - ~ one line addition.  JS - ~ 10 lines.  HTML - ~20-30 lines - enough to take care of the validation password and all of its tooltips in add_email_address and verify_email_address
```

**Comment by lloyd** [comment]
details of #1 captured here: https://id.etherpad.mozilla.org/41

**Comment by lloyd** [comment]
implementation is complete, tests pass, manual testing of the features looks good to me.  Here are the steps required to fully test this fix in the staging environment:
1. deploy `train-2012.04.27`
2. open dialog in myfavoritebeer
3. add an email or create a new user (depending on the case you're testing, described below)
4. PAUSE javascript execution - if the dialog encouters an error while polling it will stop polling
5. deploy `train-2012.05.25` (or whatever train this goes out in)
6. RESUME javascript execution
7. click on the deployment link in your email
8. verify behavior is as expected.  see below.

## test cases

There are several different cases that need to be tested for this one.  they can all be done in parallel

### new acct / same browser

For this case, you try to sign into mfb with a new email address that isn't registered yet.

Desired outcome: You are prompted for password in the verification screen, and can later log in using that password.  Once you sign in, you're authenticated to the browserid service.

### new acct/ different browser

For this case, you try to sign into mfb with a new email address that isn't registered yet, and you perform the verification in a different browser than you start out in.

Desired outcome: You are prompted for password in the verification screen, and can later log in using that password.  After you pick your password on the verification screen, that session is authenticated to BrowserID.  The dialog transitions and you have to re-enter your password in the dialog, after which you're authenticated to browserid.

### new secondary to primary only acct / same browser

In this case, you create an acct with only a primary user (the acct has no password), then you add a secondary user to the account.

Desired outcome:upon clicking on the verification link, you should be asked to create a password.  Once you create the password, you should be signed in to the site, and browserid.

### new secondary to primary only acct / different browser

In this case, you create an acct with only a primary user (the acct has no password), then you add a secondary user to the account.  You open the verification link in a different browser than the one that starts the transaction

Desired outcome: same as before, but both browsers should be authenticated to browserid.

**Comment by shane-tomlinson** [comment]
@lloyd - Logically, the code makes sense.  I have been trying to test both locally and using a remote instance and keep getting a "database unavailable" error whenever "/wsapi/email_for_token" is called after doing the upgrade from train-2012.04.27 to issue1592.   I am sure missing something extremely obvious.

**Comment by jrgm** [comment]
Just noting that when testing as described above and using the mysql impl (not the db/json), there is a bug with the case 'new acct / same browser'. You are challenged to enter a password, but upon submitting the from, you get back an error screen 'We are very sorry, the server is under extreme load' which really means "the webhead got a 503 from the dbwriter". 
@lloyd is looking into this and can repro; I think @shane-tomlinson hit this earlier this morning. (Note: I do have the correct updated schema for browserid.staged table which adds the 'passwd char(64) default null' column).

**Comment by jrgm** [comment]
On the other scenarios, when backed by mysql on an awsbox:

2) new acct/ different browser:
- I am prompted for a password in the verification screen, but get a 503 when I submit that form. (errors in logs about 'unknown secret', and NULL is set as the password). So basically the same as 1.
- the dialog does transition to prompt for a password, but the password I had tried to submit is not valid (of course). 

For 3 and 4, they seem to work but my EC2 instance had bad network speed for a while so I'll check again tomorrow

**Comment by lloyd** [comment]
hi.  so commit eef9e22 should fix the problems in this branch.  let's retest the four cases and if the pass, get this merged.

**Comment by jrgm** [comment]
Okay basically the above 4 scenarios work with that most recent change on issue1592, in that there are no errors and ultimately the user is authenticated. 

However, in the 'new acct/same browser' and 'new sec to pri only acct/same browser', I have had occasions where the dialog still challenges for a password even though the verify_email_address|add_email_address completes ok. I'll look more tomorrow to narrow that down. But if the worst case is a redundant password challenge, we can merge and test more with that.

**Comment by lloyd** [comment]
closed with extreme prejudice, btw.

**Comment by jrgm** [comment]
I had generally good results. (I had one failure case, but I think that was a valid failure: I was adding a secondary to a secondary, but at some point since I first made these emails, I had deleted that account from diresworb). Marking verified for stage train-2012.05.25
