### ISSUE TITLE
lloyd/eyedee.me needs to be documented

### ISSUE THREAD

**Issue by graingert** [mozilla/persona#1595]
Currently the documentation is empty

It would also be good for lloyd/eyedee.me to be forked to mozilla/something

**Comment by callahad** [comment]
Closing as a duplicate of https://github.com/lloyd/eyedee.me/issues/2

We're holding off on forking it to mozilla until we figure out if it should be a long-lived example project, or if more "real world" production services (like https://github.com/mozilla/vinz-clortho) might better fill that role.
