### ISSUE TITLE
update load_gen for the changes to jwcrypto

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1596]
The browserid/bin/load_gen stuff needs updating to match the changes to the jwcrypto api. On the train-2012.05.14, starting load_gen fails with "Error: Cannot find module 'jwcrypto/jwk.js'". 

The train-2012.04.27 also doesn't work running against current stage with train-2012.05.14 (many 400 errors like "error: (signup) can't stage user, non-200 response: 400") which I assume(?) would be expected?

This can just be fixed on dev (i.e., not necessay to do it on train-2012.04.27, unless you'd like to).

**Comment by lloyd** [comment]
Roger.  And it's high time I add a test so this stops happening.

--lloyd

**Comment by jrgm** [comment]
-> me to try it and close

**Comment by lloyd** [comment]
nice, @jedp merged.  I'm going to close this, @jrgm please re-open if things don't work as advertised.

**Comment by jrgm** [comment]
I had run a load_gen against stage with the previous train and running a short one now with train-2012.05.25. Tool works fine. Verified.
