### ISSUE TITLE
uploaded interaction data not always sending lang, timestamps, etc.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1597]
1. Delete all history from a browser profile (or in web console with dev.diresworb.org loaded `delete localStorage.interactionData`).
2. Load http://dev.myfavoritebeer.org/ and click sign in.
3. Close the dialog
4. Click sign in to bring up the dialog and close it again.
5. Click sign in to bring up the dialog and close it again.

On the second load of the dialog at step 4, a blob like this is posted to /wsapi/interaction

```
{
  "data":[{
    "event_stream":[["xhr_start",0],["xhr_complete",90], ...],
    "sample_rate":1,
    "timestamp":1337041079466,
    "local_timestamp":"Mon May 14 2012 17:17:59 GMT-0700 (PDT)",
    "lang":"en-us",
    "screen_size":{"width":1680,"height":1050}
  }],
  "csrf":"VglIjckP3pzoB6a738EIRw=="
}
```

On the third load of the dialog at step 5 (and all subsequent loads), the blob that is sent does not have the lang, screen_size, timestamps, etc.

```
{
  "data":[{
    "event_stream":[["window_unload",218093]]
  }],
  "csrf":"VglIjckP3pzoB6a738EIRw=="
}
```

**Comment by jedp** [comment]
Thanks, I'll take a look at this.

**Comment by jrgm** [comment]
I should note that I was doing this with FF12 and the extension HttpFox which shows all network traffic from all browser windows. Not sure how to see the same thing (specifically the network IO in the /sign_in dialog) in other browsers, but should be the same.

**Comment by jedp** [comment]
Thanks for the steps to reproduce - very clear!

**Comment by shane-tomlinson** [comment]
This is is closed with PR 1612 and checkin 428e6eb2aa11a6f57cc7c7b8e94cc526abde6a1d

**Comment by jrgm** [comment]
So, on diresworb.org /session_context is returning "data_sample_rate":0. Need to get that turned on (set to 1). /cc @fetep

**Comment by jrgm** [comment]
For the specific STR listed here and also for some other scenarios and a little ad hoc testing, I am seeing a struct like

{ "csrf": "2+3ebToPUmcXTB1YHqyxOA==",
  "data": [{
    "event_stream": [ ... ],
    "lang": "en-us",
    "sample_rate": 1,
    "screen_size": {
      "height": 1050,
      "width": 1680,
    },
  }]},
passed on every open of the dialog (after completion of the /wsapi/session_context request). Verified for train-2012.05.25 (but not on stage, as it's disabled there, at least for the moment).

**Comment by jrgm** [comment]
... (Where in some error cases, the list for "data" can be greater than 1.)
