### ISSUE TITLE
[ie8] dialog, signing up new secondary, password field not focused

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1598]
Total UI/a11y nit. I only see this on IE8, not on other desktop browsers.

STR:
1. Load beta.myfavoritebeer.org and click sign in
2. Enter an unknown secondary address (e.g., foo@example.com) and click 'next'

Expected: the first password field should now have focus for typing

Actual: focus doesn't appear to set anywhere in content

**Comment by jrgm** [comment]
Actually, there's a few other places where initial focus seems wrong. There are bigger fish to fry than this ui nit. 2-star.

**Comment by seanmonstar** [comment]
There has been some autofocus code that has landed recently, so is this still happening?

**Comment by seanmonstar** [comment]
closing this. if it's still a problem, please reopen.

**Comment by jrgm** [comment]
Reopening. Original STR apply for IE8 on XP.

**Comment by shane-tomlinson** [comment]
@jrgm - I am unable to reproduce this on IE8 on XP. Are you still seeing this?

**Comment by jrgm** [comment]
@shane-tomlinson I cannot reproduce now either. Closing. THanks.
