### ISSUE TITLE
code cleanup for old existing field in stage table

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1599]
at the time we migrated from using email addresses in sessions to user id's, we introduced some transitional code to handle outstanding verification emails.  That code is now unnecesary, and should be cleaned up.

This cleanup is low risk, and should happened before we attack issue #1592, to reduce complexity and craziness

**Comment by jrgm** [comment]
Code cleanup. Testing done for GH-1592. Marking this verified for train-2012.05.25
