### ISSUE TITLE
Unable to retrieve forgotten existing passwords

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#160]
Maybe this is by design of BrowserID, but its not what common user flow would expect.  If i forgot my password for a particular email account, i would think i'd be able to click the forgot password link, enter in my email address, and get the old one sent to me through email.   

The current UI asks the user to just fill in your email, and add and verify and new one right there in the window.   My immediate reaction is, is this safe to change it here?  Will it update my password on my email server?   

It makes more sense if i can traditionally get a note in my mail, and then change it on the mail client.   

Repro
1) goto http://beta.myfavoritebeer.org/
2) click sign in, and goto i forgot my password
3) the forgot password tells the user "Forgot your password? No problem! Enter your email address, pick a new password, and we'll get you set up again!"
4) Type in your email and new password, and notice it goes to your email carrier
5) My problem here is it's not really asking me to retrieve my forgotten password.  what if i wanted to know what it was before, instead of having to create a new one?   If its going to be create a new passowrd, we need to change the wording of it.

Expected:
- forgotton password shouldnt allow you to type in a new one there, but instead try to retreive it via emails like what a user would expect traditionally

ActuaL:
- forgot your password just means create a new one right away.   this can confuse a user if they want to retrieve their old one, or maybe even think they are changing their password for that email account (which isnt true)

**Comment by joshtriplett** [comment]
Any system which can send you your password via email is insecure.  No service should _ever_ store your password, only a safely hashed version of it that it can use for verification.

That doesn't mean the "forgotten password" flow couldn't become clearer.  If you have suggestions for how to improve it that don't require storing the user's password insecurely, please mention them.

**Comment by benadida** [comment]
we do not store passwords in plaintext, so we won't fix this.
