### ISSUE TITLE
The user is requested to enter his password twice when adding a non-primary email to a primary account

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1605]
Browser: Firefox 13.0
OS: Windows 7

STR:
1. Load http://beta.myfavoritebeer.org/ in the browser.
2. Sign up with a primary email.
3. Logout from the website and click on the Sign In button.
4. Click on the "Add another email" link.
5. Enter a non-primary email and click "add".
6. Enter a password in both required fields and click the "verify email" button.
7. Open your email client in another tab of the browser and click on the BID verification link.

After confirming his email, the user is requested to enter his password on the Sign In dialog, although he entered his password on the same dialog at step 6.

Note: This issue doesn't reproduce when simply signing up with a non-primary email.

**Comment by shane-tomlinson** [comment]
@ioanab - I just tested this on dev and all is working as expected.  I believe this was fixed as part of issue #2088 where we did a lot of work to clean this up.

Can you verify this is still a problem?  If not, can you close this issue?

Thanks for being such an awesome bug finder!

**Comment by ghost** [comment]
@shane-tomlinson Thanks for your support!

I verified this issue on the same environment (Win 7 + Firefox) and it doesn't reproduce anymore.
