### ISSUE TITLE
It's not possible to add a non-primary email to a primary account after all non-primary emails have been removed from it

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1606]
Browser: Firefox 13.0
OS: Windows 7

STR:
1. Load http://beta.myfavoritebeer.org/ in the browser.
2. Sign up with a primary email.
3. Add one or more non-primary emails to this account.
4. Load https://diresworb.org/ in another tab of the browser.
5. From https://diresworb.org/, remove all the non-primary emails from your account.
6. Go back to http://beta.myfavoritebeer.org/ and try to a non-primary email to your account again.

The following message is displayed no matter what email address the user tries to add to his primary account at step 6:
"We just sent an email to that address! If you really want to send another, wait a minute or two and try again. ".

**Comment by seanmonstar** [comment]
I'm not able to reproduce. This is what I did exactly:
1. Load http://beta.myfavoritebeer.org/ in the browser.
2. Sign up with a primary email.
3. Logout.
4. Login, but select add another email.
5. Confirm new secondary email, which logs me in.
6. Load https://diresworb.org/ in another tab of the browser.
7. From https://diresworb.org/, remove all the non-primary emails from your account.
8. Go back to http://beta.myfavoritebeer.org/ and logout.
9. Login, and select add another email again, using a different secondary.
10. Received confirmation email to my 2nd secondary email, and was able to login.

**Comment by jrgm** [comment]
I just realized this is the same as GH-1677. I can reproduce this as described here in either current stage (which is train-2012.06.22 at the moment), or in current dev. I was using FF ESR 10.0.6, but the browser should not matter here because this is a backend issue.
