### ISSUE TITLE
dbwriter did not auto-reconnect to mysql master

### ISSUE THREAD

**Issue by fetep** [mozilla/persona#1608]
We had a networking incident that impacted scl2<->phx1 traffic, and the dbwriters in phx1 lost their connection to the mysql master (in scl2) and did not reconnect on their own.

lsof shows no :3306-related open FDs.  dbwriter.log doesn't have any clues.

**Comment by lloyd** [comment]
do we have actual user visible impact associated with this?  the way the code is constructed, connections are lazy based on requests that require database writes.  It appears based on other writeups of the issue that we did in fact have attempted requests that failed.

it would be helpful to see the relevant subset of the dbwriter logs durring the period immediately preceding the outage to slightly after its resolution.  at least I'll be able to try to piece together what _didn't_ happen that should have.

A skim of the code in place (`lib/db/mysql_wrapper.js`) doesn't reveal any obvious regression.  it should handle this type of outage, and there should be information in logs.

**Comment by fetep** [comment]
It wasn't re-connecting, and our nagios probes that theoretically should be causing a database connection were also failing (they hit /wsapi/ping)

**Comment by ozten** [comment]
Based on @fetep's thorough writeup (via email) I think these are the STR

1) Startup services backed by MYSQL
2) Stop mysqld
3) Go through login flow manually (or potentially many times via load_gen or whatever)
4) Start mysqld
5) Go through login flow

To fix this, I'll need a way to reproduce our code failing to reconnect consistently.

**Comment by ozten** [comment]
Manual testing stopping and starting mysql during various steps doesn't repro.

I see expected behavior: 
Error screen
browserid (25592): warn: database is down, cannot process request: Error: connect ECONNREFUSED
dbwriter (25581): warn: database connection down: Error: connect ECONNREFUSED
Recover once msyql is started.

Will read code more closely as well as look at using load_gen to repro.

**Comment by fetep** [comment]
The actual scenario is losing our TCP link.  So if you can run your
mysqld on another machine, and add an iptables block that will force
existing and new connections to timeout, that would be best.

**Comment by ozten** [comment]
I guess a custom node proxy be a simple route, which points at the real MySQL port sometimes and a non-MySQL port other times.

If I can't get that working, I'll try iptables or a second VM. Thanks Pete!

**Comment by ozten** [comment]
Running this simple single-connection oriented proxy and things work as expected, after 12 operations we emit a timeout...

https://gist.github.com/2770854

**Comment by ozten** [comment]
Okay, I've spent a few hours exploring this and can't repro.

I got @lloyd on the horn and he explained the initial testing that jrgm and he did on the current production codebase, which matched your recommendations. They found and fixed many issues with networking at that time.

Without logs and with the email showing fixing replication as the main source of recovery, I'm going to close this for now.

If this occurs again, can you confirm that you can query the DB in question outside of Node, but that dbwriter or browserid processes don't re-establish their connection?

Maybe using `mysql` client and a simple read on stage table... or whatever to know that mysqld is accepting connections on 3306.

Closing, needs STR

**Comment by fetep** [comment]
The problem is node wasn't issuing db queries; we reproduced this a ton last Friday in production as we were doing datacenter maintenance in scl2. lsof on the process showed _no_ 3306 connection, no attempt seen to make one in tcpdump, and /wsapi/ping was failing. The db replication delays were a different issue; that's just weird application behavior, MySQL has no idea the data is actually out of date.

**Comment by jrgm** [comment]
Yes, I will be finishing this today/tonight.
