### ISSUE TITLE
Forgot my password flow busted in production

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1609]
Steps to Repro

1) Go to http://myfavoritebeer.org/ and signin
2) (Optional) If already logged in, click this is not me
3) Enter BID email
4) Click 'Forgot my password' and click Reset Password

Note: No feedback screen is shown indicating that you should check your mail

5) Check mail and click reset link

Example:  https://browserid.org/verify_email_address?token=qrWHuLiaVGW7F-48-char-string-0Zr8HgUCv6qJ69HUmC

Actual
In a new browser window, error message

```
There was a problem with your signup link. Has this address already been registered?
```

Expected:
Change password form

**Comment by jedp** [comment]
I get the same result.  I do think the 'check your email' feedback screen appears for a fraction of a second

**Comment by ozten** [comment]
@fetep is on the scene.

FYP flows working agan. Closing, assuming we'll evaluate elsewhere.

**Comment by shane-tomlinson** [comment]
@ozten - All seems fine at 08:54 GMT on 05.18.2012.  Is this related to the PHX1 DB change Jeff Viers wrote about yesterday?

**Comment by fetep** [comment]
@shane-tomlinson slightly related. One of the three databases in phx1 had replication lag (the master was in scl2 for most of the day) because of some network blips; we failed over the master to phx1 to avoid being impacted by any more networking work happening in scl2 yesterday + today.
