### ISSUE TITLE
Consider adding the current webhead commit sha to session_context and interaction_data for kpi

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1611]
This is from a brief irc chat with @jedp and @fetep
1. Add the current commit sha of the webhead to the response of `/wsapi/session_context`
2. Return that commit sha value in the blob sent back to `/wsapi/interaction_data`

This would help in understanding of how releases improve usability.

**Comment by jedp** [comment]
I think that's an excellent idea.

**Comment by ozten** [comment]
I'm assuming the graphs would integrate our statsd ping's when we do a release, so we could have a vertical bar denoting each release.

Are 1 and 2 needed to deliver the data technically (code migration or whatever), or just to record the release?

**Comment by lloyd** [comment]
have a look at the 'enable_code_version' configuration option.  We can default this on and it should solve the first half of the problem.

this was introduced to solve a different problem, but we went a different way.  we left in the functionality and config tho, and can use it now.

lloyd

**Comment by lloyd** [comment]
I wrote my response via email, before reading ozten's followup.  He's right.  because we have precise release times, and because they only happen once every two weeks, it could be perfectly viable to encode those separately somewhere and draw lines on graphs.  I like that approach better.

**Comment by jrgm** [comment]
Yeah, this isn't necessary. Retracting my suggestion. There is a tiny bit of slop at the time we ship and the blob returned is from the release prior to the current one, but this is just a tiny bit of noise.
