### ISSUE TITLE
whitelist which fields are sent to backend in KPI data.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1613]
Right now we are sending things like local_timestamp which are used internally but should not be sent to the backend as they could be used to fingerprint users.

**Comment by lloyd** [comment]
+1 - "id" concerns me too.  and generally we should make every addition to this blob require explicit action.  whitelist, not blacklist.  @stomlinson++

**Comment by jrgm** [comment]
verified for train-2012.05.25 running on awsbox (kpi sampling not enabled in stage). The only keys that are sent by the client are  'event_stream', 'lang', 'screen_size', 'sample_rate' (also checked fully on IE8).
