### ISSUE TITLE
KPI event stream names should follow <namespace>.<event_name> format

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1614]
Right now we sending the internal message names that are sent to the mediator. This is not useful for the backend as the mediator is full of extraneous data and does not directly say which screens a user sees.

**Comment by jrgm** [comment]
Confirmed in dev for train-2012.06.08. A typical event stream now looks like 

"event_stream": [  
 [ "screen.rp_info", 2203 ],  
 [ "screen.authenticate", 2229 ],  
 [ "screen.set_password", 20728 ],  
 [ "user.user_staged", 31452 ],  
 [ "screen.check_registration", 31458 ],  
 [ "user.user_confirmed", 63940 ],  
 [ "generate_assertion", 63941 ],  
 [ "screen.generate_assertion", 63960 ],  
 [ "assertion_generated", 64252 ],  
 [ "window.unload", 66049 ]  
]
