### ISSUE TITLE
More than one tooltip can be displayed at once

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1615]
STR

1) Open the dialog.
2) If logged in, click "this is not me"
3) put cursor in email field
4) Press "enter" multiple times.
5) Watch the tooltip get darker after each click.

**Comment by seanmonstar** [comment]
Still happens, but the tooltip doesn't get darker since they're no longer transparent.

**Comment by jrgm** [comment]
veriified train-2012.08.17
