### ISSUE TITLE
From GH-1567 - consider not recording repetitive polling XHR requests 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1619]
From GH-1567, the most critical point (#3) in https://github.com/mozilla/browserid/issues/1567#issuecomment-5656953 is fixed. I'm splitting out the remaining 3 points as separate issues.

This is point #1 - "@lloyd - we're collecting a ton of data during polling that is not valuable. perhaps we should not be doing this. this would suggest surpressing xhr events (only capture xhr errors)".

For example, the event stream for a sequence of popping the dialog with one already authed user, and then begin adding a second secondary email address to the account looks like this:

[u'pick_email', 243]
[u'authentication_checked', 243]
[u'add_email', 2126]
[u'xhr_start', 8787]
[u'xhr_complete', 8916]
[u'add_email_submit_with_secondary', 8930]
[u'xhr_start', 14560]
[u'password_set', 14562]
[u'xhr_complete', 15010]
[u'xhr_start', 15019]
[u'email_staged', 15021]
[u'xhr_complete', 15109]
[u'xhr_start', 18112]     <-- the dialog is now in a polling loop of GET /wsapi/email_addition_status?email=...
[u'xhr_complete', 18197]  <-- every 3 seconds, it adds one xhr_start/xhr_complete
[u'xhr_start', 21200]
[u'xhr_complete', 21289]
[u'xhr_start', 24292]
[u'xhr_complete', 24376]
... and so on for as long as the dialog is open (until in a about 12 minutes the blob > 10K).

**Comment by shane-tomlinson** [comment]
This will be fixed with #1614

**Comment by jrgm** [comment]
Yep, verified in dev instance of train-2012.06.08, no more xhr_\* repitition. A typical event stream is now like

"event_stream": [ 
 [ "screen.rp_info", 2203 ], 
 [ "screen.authenticate", 2229 ], 
 [ "screen.set_password", 20728 ], 
 [ "user.user_staged", 31452 ], 
 [ "screen.check_registration", 31458 ], 
 [ "user.user_confirmed", 63940 ], 
 [ "generate_assertion", 63941 ], 
 [ "screen.generate_assertion", 63960 ], 
 [ "assertion_generated", 64252 ], 
 [ "window.unload", 66049 ] 
]
