### ISSUE TITLE
From GH-1567 - interactionData accumulates when working offline 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1620]
From GH-1567, the most critical point (#3) in https://github.com/mozilla/browserid/issues/1567#issuecomment-5656953 is fixed. I'm splitting out the remaining 3 points as separate issues.

This is point #2 - "@lloyd - interaction blobs accumulate when you're offline. Maybe we should have a max backlog? we need some way to deal with this".

STR:
1. Go to dev.myfavoritebeer.org and click signin.
2. Close the dialog
3. Set Firefox to 'File->Work Offline' (or in another browser where feature available)
4. Click signin and dismiss the dialog. Repeat a few times.

Each dialog open adds another item to interactionData in localStorage. (NOTE: This does not happen when the computer is disconnected from the network, at least in FF; in that case the dialog tries to GET /sign_in and cannot; the browser changes the window to display "Server not found" and normal javascript execution does not happen).

**Comment by shane-tomlinson** [comment]
@jrgm - this will be fixed along with the fix to #1597, which is under review.

**Comment by shane-tomlinson** [comment]
@jrgm - Something interesting is going on here - When I click "work offline", Firebug still shows GET requests as completing their lifecyle.  Since session_context completes, it collects data.

So, is this an upstream issue where "Work Offline" still does GET's but not POST's?

![Requests Still Happening](https://img.skitch.com/20120523-qeerhdw89gbmaesytfkyp1f853.png)

**Comment by jrgm** [comment]
@shane-tomlinson the firebug UI is a bit misleading. ngrep shows me that nothing is sent on the wire when FF is in Work Offline. I guess if Work Offline by content can be served from the cache, then firebug shows it as a successful GET (which in a sense it is). A POST though when offline should be shown as a failure.

**Comment by jrgm** [comment]
Hmm, @shane-tomlinson, I am still seeing data accumulate while popping and closing the dialog with FF 12 in 'Work offline' (train-2012.05.25 branch). 

(Of course, this is a very corner case user scenario, since there's not much reason to use Browserid when offline, and data accumulation will ultimately be cleared (or discarded of >10K) on next connect to the network).
