### ISSUE TITLE
consider upping the 10K limit on HTTP POST 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1621]
From GH-1567, the most critical point (#3) in https://github.com/mozilla/browserid/issues/1567#issuecomment-5656953 is fixed. I'm splitting out the remaining 3 points as separate issues.

This is point #2 - "@lloyd - if the above explorations do not solve the problem, then we need to consider upping the 10k limit"

The limit was introduced in GH-822 and GH-878, but ISTR that node has been fixed for this. On the other hand, aside from GH-1619, blobs will typically be well below 10K anyways, and perhaps there is no need to up the limit.

**Comment by shane-tomlinson** [comment]
@jrgm - is this 10K total size or 10K JS string characters?  JS strings are encoded using UCS-2 or UTF-16 with each character taking up 2 bytes.

**Comment by shane-tomlinson** [comment]
@jrgm - secondly, is this total size per blob or total aggregate size of all blobs sent?

**Comment by jrgm** [comment]
On the first question, the limit is on bytes transmitted in the POST (including the headers). Actually, the KPI payloads we send only contain 7-bit characters (sent as UTF-8 if it actually ever mattered). 

On the second question, the limit applies on the total size of any POST (see GH-822).

**Comment by lloyd** [comment]
I think we first need to clean up the event stream with stable event names and meaningless states ommitted.  Then dev will stream blobs to kpiggypank and well get a mean size. If anywhere near 10k we can double the limit.

--lloyd

**Comment by lloyd** [comment]
resolution is same as issue #1622
