### ISSUE TITLE
Limit the size of posts to /wsapi/interaction_data on the client side

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1622]
One other point from GH-1567 - "@lloyd - perhaps we should introduce a client side upper bound as well, and if blobs are above that, don't even try to post?".

I think that's a good idea. For example, when I do accumulate a blob > 10K, even though the server returns 413, there is still a noticeable pausing in beginning the /sign_in dialog (more noticeable on a slower network).

**Comment by lloyd** [comment]
@petef, can we get sensitive alerts on 413s and only react to this bug if necc?

**Comment by jedp** [comment]
Resolved with #1621 and #1622

**Comment by jrgm** [comment]
Actually I file https://bugzilla.mozilla.org/show_bug.cgi?id=775742 just now to request monitoring/graphing for HTTP 413

**Comment by jedp** [comment]
Sounds good.  Thanks!
