### ISSUE TITLE
Minified javascript missing license and link to source

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#1624]
https://browserid.org/include.orig.js has the following header:

```
/**
 * Uncompressed source can be found at https://browserid.org/include.orig.js
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
```

but that header is missing from https://browserid.org/include.js which I think is the place where it was intended to show up.

**Comment by lloyd** [comment]
we probably broke this when we reworked our compression many moons ago.  we should determine what if anything we want at the header of this file and repair it.  `scripts/compress` is a good place to look for the gunk that does the compressin'.

**Comment by lloyd** [comment]
I dug into this.  When we moved to programmatically interfacing UglifyJS, we lost copyright preservation, as that code is not included in the UglifyJS library, but rather the command line program.  patch coming to add this functionality back to `scripts/compress*`

**Comment by jrgm** [comment]
verified for stage train-2012.06.08 comment is preserved for /include.js. @shane-tomlinson has an open issue GH-1655 for whether license and reference to source code repo is needed in other minified prod. resources. The answer seems to be no, for the most part, with caveats.
