### ISSUE TITLE
How to add email address from Account Manager page?

### ISSUE THREAD

**Issue by briandorsey** [mozilla/persona#1626]
On the BrowserID Account Manager page, the text implies that I can add
multiple email addresses, but I couldn't figure out how to do it. 

The edit button reveals an option to remove addresses, but not add. I expected a
button somewhere to add a new address to the account.

Marked up UI examples here:
http://imgur.com/a/O9xxG

Thanks for looking at it!

Take care,
-Brian

**Comment by ozten** [comment]
Background Question:
Where you able to find and use the 'Add another email' link in the dialog, from https://myfavoritebeer.org or another website?

**Comment by ozten** [comment]
@skinny97214 what is the long term plan for the account manager page? Will it get this feature with the rebranding?

**Comment by briandorsey** [comment]
Yes indeed. I didn't see that issue in my first search.

@ozten: I haven't actually _used_ BrowserID on a real site yet. Just poking around to see how it works so far. :/

Closing as a duplicate.

**Comment by skinny97214** [comment]
@ozten We've tossed around some different ideas. Ideally I'd like to not have two code paths/UIs to maintain. In any case, it's not going in for beta though since the primary use of the feature is via the popup.
