### ISSUE TITLE
Reset password flow 

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1629]
From a conversation that @skinny97214 and I had, setting the password after a reset password should be on the main site.

@skinny97214 - can you weigh in on this?

Link this to #1580, #1578, #730, #1474

**Comment by skinny97214** [comment]
Here's a diagram of the flow. Everything happens in the dialog and email.

http://cl.ly/160P0w1e051T293t0x2d

**Comment by shane-tomlinson** [comment]
@skinny97214 - One of the original reasons for putting the password in the dialog before sending the verification email is because we cannot re-focus the dialog in all browsers on all devices.  Re-focusing the dialog here post verification link click will suffer from the same problem.

As an alternative, we can put the set password back on the main site and redirect to the RP after the user sets the password.

**Comment by shane-tomlinson** [comment]
We just merged.  Any remaining problems/changes can be opened as separate issues.
