### ISSUE TITLE
Stuck after trying to reset my password

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#163]
Forgot password -> fill out new account info -> screen that says it should only take a couple of seconds (and it's stuck there).

It might be that it's trying to use the expired cookie I still had for something (which, because it's expired, would cause an auth error).

**Comment by shane-tomlinson** [comment]
I am able to verify that this is a problem.  When I click on the link in the email verification, I receive the following error in the page that is opened:

```
Email Verification
Error encountered while attempting to confirm your address. please try again. (error message: unknown)
```

**Comment by shane-tomlinson** [comment]
@vthunder - is this still a problem?  @lloyd added a fix last week to check for csrf tokens that may have fixed this.

**Comment by lloyd** [comment]
yeah.  I hit this case before revisiting all of the CSRF stuff.  I claim its fixed now.  @vthunder reopen if you can reproduce the issue on beta.
