### ISSUE TITLE
extend the session cookie on browserid.org/persona.org

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1632]
Make the session cookie 4 weeks.

(/me hides)

**Comment by lloyd** [comment]
+1  - @benadida ?

**Comment by benadida** [comment]
this is after the user has said this is their computer? If so, sounds good to me.

**Comment by shane-tomlinson** [comment]
Link this to #1572

**Comment by jrgm** [comment]
Verified on stage train-2012.06.08. 
- If I start with a clean profile and bring up the dialog from an RP, before I am authenticated I get a cookie with an embedded duration of 2419200000 (4 weeks) and an expires value of 4 weeks from now. 
- When I signin as a known secondary with a password, the cookie is changed to have embedded duration of 3600000 (1 hour), and an expires value of 4 weeks from now.  
- After waiting >60s and answering Yes to "is this your computer" the call to prolong_session returns a cookie with an embedded duration of 2419200000 (4 weeks) and an expires value of 4 weeks from now. 

However, I'll note the values for the same steps in current production train-2012.05.25 branch:
- before authenticated: embedded duration of 604800000 (1 week) and an expiry value of 2 weeks from now.
- after signin: embedded duration of 3600000 (1 hour) and an expiry value of 2 weeks from now.
- after Yes to 'is this your computer': embedded duration of 1209600000 (2 weeks) and an expiry value of 2 weeks from now.

So, it seems that the duration was only controlling the value for a non-authenticated session.
