### ISSUE TITLE
Consider putting link to complete registration in email header

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#1639]
When stage_user is called, browserid responds by mailing back a link for the user to click to finish his or her registration.

To make it easier to automate the registration process, it would be handy not to have to parse the link out of the body of an email, but instead simply to pull it from a header like X-BrowserID-Registration-Link.

nu?

**Comment by fmarier** [comment]
Crazy idea: Thunderbird could parse that header and present something nice to the user :)

**Comment by jedp** [comment]
fmarier++

**Comment by lloyd** [comment]
let's do this when we redesign email!

**Comment by shane-tomlinson** [comment]
PR #2174 manually merged with commit ce47dd5bf3e64d30e3b7ca5fdcb6afa894a8bd1a.  Closing.

**Comment by jrgm** [comment]
verified train-2012.08.17

One quirk to note is that when doing e.g., signup on the main site X-Browserid-Relyingparty lists the hostname of the main site e.g., login.dev.anosrep.org, since there is no actual relying party in this case.
