### ISSUE TITLE
locking the email field between pressing next and password field showing up

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#1661]
This is a very minor suggestion but it would make the login form a bit nicer to fast (impatient?) typists:
1. click signin
2. type your email
3. press enter
4. type your password
5. press enter

The problem occurs between steps 3 and 4. Depending on how soon the password field appears (and steals the focus), part of your password will end up in the email field (and be visible to anybody looking at your screen).

If we were to lock (i.e. make read-only) the email field after you press enter and before the password field steals the focus, then this problem would go away.

**Comment by lloyd** [comment]
+1
