### ISSUE TITLE
static-resource-test.js is failing

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1662]
STR

1) Run ./tests/static-resource-test.js

Expected:
Test passes

Actual:
✗ 

  All resources expand
    ✗ We get stuff
      » expected 16,
    got  10 (==) // static-resource-test.js:35
✗ Broken » 1 broken (0.003s)

**Comment by shane-tomlinson** [comment]
@lloyd took care of this with c7e84298b24c015d759a527850141d6dfe3d90c0

**Comment by jrgm** [comment]
belated verify that that test is not failing in local dev for train-2012.07.30
