### ISSUE TITLE
Abandonment KPI

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1668]
@jbonacci was thinking an abandonment KPI would be an important report.

**Comment by lloyd** [comment]
Here we have to define what abandonment means.  Isn't abandonment just a special case of cancelation?  or do we just count ALL explicit cancelation as abandonment to start, and then refine from there?

**Comment by seanmonstar** [comment]
Is this covered by the "orphaned" KPI?

**Comment by nmalkin** [comment]
From my side of things, I think _orphaned_ takes care of this, but I'll defer to @ozten on the final call.

**Comment by ozten** [comment]
I'm not tracking this stuff in detail, I trust you guys to make sure it works.

**Comment by nmalkin** [comment]
The current reports that have to do with abandonment are fulfilled by the present KPIs, and the _orphaned_ flag seems to account for both scenarios @jbonacci mentioned originally, so I think we're good.

**Comment by shane-tomlinson** [comment]
Closing this since @nmalkin and @jbonacci report that we can get this info from the current KPI set.
