### ISSUE TITLE
Prevent "development" service from starting in prod.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1669]
This service is meant to facilitate development and testing, it should not be enabled in prod.

**Comment by lloyd** [comment]
say more?  what code are you specifically referring to?  depending on that, we should aggressively prevent non-production code from even being evaluated in production.  Without more context I can't say how to do that here.

**Comment by shane-tomlinson** [comment]
@lloyd - this is in reference to the development menu in the client.  It should either be very difficult to get to or not be started in staging and prod.  Until we have a good solution for this, I am removing the HTML and preventing the "development" service from starting.

**Comment by shane-tomlinson** [comment]
Closing in favor of #1733
