### ISSUE TITLE
BrowserID popup not compatible with LastPass Addon?

### ISSUE THREAD

**Issue by brianwc** [mozilla/persona#167]
It doesn't seem like BrowserID's registration pop-up is compatible with the Firefox plugin LastPass, a password manager I use, as it didn't ask me to save the BrowserID password(s) I created. Perhaps this is LastPass' problem, but it'd be nice if the BrowserID registration pop-up just worked with the various password managers that are out there.

**Comment by lloyd** [comment]
Hey brianwc!  This issue should be resolved in our latest beta that's due for launch into production on thursday.

I'm closing this issue, please test on http://beta.myfavoritebeer.org (you'll have to create a new account there) and re-open this issue if that doesn't fix your problem!

**Comment by lloyd** [comment]
sorry, updated the last comment, that's http://beta.myfavoritebeer.org - and not https://beta.myfavoritebeer.org
