### ISSUE TITLE
Update Readme -- VEP is dead; long live BID

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#1672]
"Here lives the BrowserID implementation. BrowserID is an implementation of the verified email protocol."

That's not really accurate anymore.

I'll try to come up with better language later today, but suggestions welcome.

Filing the bug so I don't forget to go back and fix this...

**Comment by callahad** [comment]
Scope creep: Review the whole Readme as we get ready to go to Beta :)

**Comment by seanmonstar** [comment]
still valid?

**Comment by callahad** [comment]
Still valid. The trigger I'm waiting for is "the train in stage _is_ going to be the the Beta" to do my final pass over the readme.

**Comment by lloyd** [comment]
the train in stage IS going to be the beta, or extremely close to it.  let's do a final doc pass now and close this down.  I can take it if you like.

**Comment by callahad** [comment]
@lloyd I'll do a pass now, and assign the PR to you to review once I'm done.

**Comment by lloyd** [comment]
awesome

**Comment by callahad** [comment]
@lloyd Here you go: #2262

Closing this issue.
