### ISSUE TITLE
second password field in flow is labelled 'reset password'

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1675]
1. Create a secondary email address on browserid
2. Clear all profile data in a browser
3. Go to an RP click 'sign in' to bring up the dialog. 
4. Enter the known secondary email address and then click password. 

Expected: 
Prompted to enter a new password twice 

Actual: 
Prompted to enter a new password twice, but the second one is labelled 'reset password', which seemed to me and @tonychung  to be a confusing way to label that field. (Reset? What's a reset password? Is this supposed to be the same as the first, or is it something different?). 

![img](https://img.skitch.com/20120601-gq6d59w6c6q1n4jgi3ag9gm56n.png)

**Comment by jrgm** [comment]
actually, this is shown for either forgot password, or in signing up a new account. Funny how I looked right past it until Tony mentioned it. :-/

**Comment by jrgm** [comment]
Ping. Any chance of getting this phrase fixed for the pending train. Just "Password" would be better than 'reset password'. 
See http://irclog.gr/#show/irc.mozilla.org/identity/113028 for @AutomatedTester's comments.

**Comment by jrgm** [comment]
By the way, this is how dev currently appears, with focus tabbed to the 'done' button. 

![img](https://img.skitch.com/20120703-xe5345td314pus217gpyegdkp2.png)

**Comment by lloyd** [comment]
this issue is the same as GH-1905 - it is a problem with our english language "translations" we need to get this sorted as it's visible in stage too.

**Comment by lloyd** [comment]
fixed in dev.

rolling out to stage: https://bugzilla.mozilla.org/show_bug.cgi?id=767708#c26

will be in production monday.

closing down this issue.
