### ISSUE TITLE
cannot add secondary back to a primary-only account that previously had a secondary email in the account

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1677]
This is a relatively rare but valid thing to do.

STR:
1. Start out with a fresh profile state, and use beta.myfavoritebeer.org or beta.123done.org to sign up as a primary email address.
2. Sign out of the RP, and click sign in again. Click 'add another email' and enter a secondary email address not known to diresworb.org. (Enter the password twice, collect the email link and load it in the same browser, enter the password a 3rd time). 
3. Add another secondary address to the account. (Not necessary for STR, but just to show that you can add more secondaries to this account). 
4. Go to diresworb.org and delete the two secondary email addresses. 
5. Go back to the RP and try to add another secondary email address. The dialog takes the email address then asks for a password twice, but when you click 'verify email' the dialog says 'We just sent an email to that address' and will not proceed. 

(Note: The response to /wsapi/stage_email is '200 OK {"success":false,"reason":"a password may not be set at this time"}'; usually that tooltip fires on '429 "Too Many Requests: Too many emails sent to that address, try again later."')

(Note 2: If it's a secondary that is the last email remaining from an account, this works fine and secondary/primary email addresses can added/re-added to the account. It's just the case where the primary is the only email left and it now has a password and the dialog wants to add a password that it doesn't work. This does not happen in current production train-2012.04.27).

**Comment by stephendonner** [comment]
+1

**Comment by jrgm** [comment]
Noting that the discussion in triage was that currently primaries have only been for testing. But this will become a problem with bigtent.

**Comment by shane-tomlinson** [comment]
Verified that this is still a problem.

**Comment by zaach** [comment]
The client and server are inconsistent in how they check if the user needs a password during staging. The client requires the user enter a password during staging [if they don't currently have any secondary email addresses](https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/user.js#L1004). Meanwhile, the server [checks if the user account has a password hash](https://github.com/mozilla/browserid/blob/dev/lib/wsapi/stage_email.js#L42). When the user tries to stage a new secondary, the client makes them supply a password, which the server sees as unnecessary, and [throws and error](https://github.com/mozilla/browserid/blob/dev/lib/wsapi/stage_email.js#L48).

**Comment by jaredhirsch** [comment]
I can't repro this any longer; closing. Please reopen if anyone can repro.

**Comment by jrgm** [comment]
No, I can't repro either now.
