### ISSUE TITLE
navigator.id.genKeyPair should call back with string, not object

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#1678]
@benadida discovered that the current IdP API makes it hard to marshal data across the native code boundary.  

Propose that genKeyPair should call back with a json string, not object

Benefits:
1. Easier to interface with native code
2. Consistent with rest of IdP API, in which we deal with strings, not objects

This would affect IdPs.  It would not affect the RP API at all.

**Comment by zaach** [comment]
Was this addressed with #1789?

**Comment by callahad** [comment]
Verified. By temporarily adding log messages to mockmyid. I feel dirty.
