### ISSUE TITLE
logger.js api is unnecessarily difficult to use.

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#168]
Currently, the logger api requires a 'category' which is the general area of the software that the log message is related to (i.e. database, security, etc).  This is specified as a parameter to the log function.  Next up, a message has an 'entry', which is a json object.  Finally, that json object must contain a 'type' property, otherwise a _runtime_ error is raised in the software.

API here: https://github.com/mozilla/browserid/blob/dev/libs/logging.js#L77

I propose we redesign the system a bit:

```
log(<string> level, <object> msg);
```

That is level is one of logger.INFO, logger.DEBUG, logger.WARNING, logger.FATAL.  Instead of manually providing the component from which the log message originates, we use the file and line number (when combined with the sha of the software, this could be used to generate links into github with the line where the message was omitted highlighted).

I believe this is better, because the conscious decision the developer must make at the time they write a log message is "how important is this?"...  Which is much more meaningful (both when reading logfiles AND when writing code that logs) than "what abstract part of the software is this log message coming from?".

The other change here is that breaking logs up into separate files at the time they're created is not useful.  it's harder to merge and correlate logs than it is to split them up using unix tools.  We should be logging all messages for a single process to one file.

This work takes about 30 person minutes, the hard part is getting folks to agree.

**Comment by benadida** [comment]
Lloyd: I disagree, because that's not the goal of this logging api. The goal of this logging API is to create explicit logs of behavior for metrics to look at. That's why objects are JSON serialized, etc.

I can see adding a separate log for this kind of developer logging, which would be stored separately and cleared very aggressively on a regular basis (for privacy).

**Comment by lloyd** [comment]
(took a walk, thought about it, and changed my response).

Then we need to change the name of the abstraction you added.  it's not about logging, but about metrics.  I suggest we call it metrics.js.  I still suggest the following changes to the "logging" stuff:
1. clearly document the purpose of the module at the top of the file.
2. change the name
3. all of a processes logs should be put into a single file
4. rather than imposing restrictions on structure of logged objects we should make all required fields proper parameters that are obvious upon inspection of the signature of the log function.

**Comment by benadida** [comment]
ok, I like that approach. Then we can easily say that logs need to be cleared regularly (except for security purposes), and metrics need to be very carefully handled for privacy. Sounds good to me.

**Comment by lloyd** [comment]
ok, I can make this change tomorrow.  reassing the bug to yourself you want to do it before then.
