### ISSUE TITLE
Ukranian (uk) not showing on l10n preview

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1686]
Why is Ukranian (UK) not showing up on http://ozten.com/random/browserid/bid_test.html?

@ozten @fetep

**Comment by ozten** [comment]
uk/LC_MESSAGES/messages.mo and
https://l10n-preview.diresworb.org/v/fa0ecc8892/production/uk/dialog.js look good

I see 'uk' in config/l10n-all.json but not in config/l10n-prod.json.

l10n-preview **should** be running off of config/l10n-all.json.

**Comment by jrgm** [comment]
Is this fixed? I am showing uk when I pop the dialog from the above URL.

**Comment by ozten** [comment]
It is fixed. I see non-English strings on Aurora with Ukrainian 'uk'

**Comment by shane-tomlinson** [comment]
@ozten, @mathjazz - is this still an issue?

**Comment by mathjazz** [comment]
@shane-tomlinson No.

**Comment by shane-tomlinson** [comment]
@mathjazz - thanks.  closing.
