### ISSUE TITLE
ensure that navigator.id behaves like a true DOM API

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1689]
In particular,

```
 var watch = navigator.id.watch;
 ...
 watch(...);
```

should _fail_, because of a bad <tt>this</tt> pointer. This is because all DOM APIs in all modern browsers fail when this happens (try it with your favorite DOM API call). So, when we move to having a native implementation, we don't want web sites to start failing. Instead, we'd rather they start failing now, fix their code, and then have a smooth transition once a native implementation exists.

**Comment by shane-tomlinson** [comment]
@benadida - this change has been checked in already with checkin 565ad859, no?  Can this be closed?
