### ISSUE TITLE
new layout main site: even if content fits on screen, scroll bar appears.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1693]
![Main site showing scroll bar](https://img.skitch.com/20120606-epm8miw4r19pq1hued4qjspbt3.png)

**Comment by jrgm** [comment]
verified on stage train-2012.06.22 -- the scrollbar does not appear on all other browser/os combinations, except for Opera on Windows.

Filed GH-1866 specifically for Opera on Windows
