### ISSUE TITLE
Host fonts locally.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1695]

**Comment by shane-tomlinson** [comment]
The new fonts are hosted locally by several Mozilla properties.  We should get a copy of these and stop relying on Google to provide us with the fonts.

**Comment by callahad** [comment]
This looks like a dupe of #908 and/or #769. @shane-tomlinson should you reassign those to yourself and close this one?

**Comment by shane-tomlinson** [comment]
Good call @callahad.  I closed the other two in favor of this one.
