### ISSUE TITLE
provide "this is not my computer" checkbox at signin

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#17]
this should be done with a logout button that comes up in a popup when user doesn't check "remember me on this computer"

**Comment by benadida** [comment]
we should think very carefully about making logout convenient in all cases.

**Comment by benadida** [comment]
darn github makes it too easy to close issues. This was never closed.

**Comment by lloyd** [comment]
bump.  At this point it looks like we have a remember me checkbox on https://browserid.org/signin - does that do anything?

/cc @stomlinson

**Comment by lloyd** [comment]
I've begun to feel that we should provide a _default off_ option anytime the user provides their browserid password: "this is not my computer"

It's interesting to think about the interplay with issue #490.

**Comment by jrgm** [comment]
Found this in a search by accident. We have this functionality for a while now. Closing this issue.
