### ISSUE TITLE
Password change doesn't require password confirmation

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#1702]
When you sign up for a new account, you need to confirm your new password by typing it **twice**. On the other hand, when you log into browserid.org and change your password, you only type the new one **once**.

It's not a huge deal because you can always do a password reset if you screw up, but it seems a bit strange that we're not consistent on that point.

**Comment by skinny97214** [comment]
@jbonacci Assigning 4 stars bc you think it's easy to fix?

**Comment by skinny97214** [comment]
My thought was to move to only one password field everywhere.

/me ducks.

**Comment by jedp** [comment]
I hit this again doing DDT this morning.  Instinctively, it felt bad.  But it's true that if you get your password wrong, you can just reset it again with minimal effort.  So I'm beginning to think @skinny97214 's idea of having one-password fields everywhere would actually be nice!

**Comment by fmarier** [comment]
I don't know if you can really "reset it with minimum effort" if we disable all of your other emails when you do a password reset via email.

That typo you made is then pretty annoying because it means you need to click links in 5 different emails...

**Comment by skinny97214** [comment]
One password field everywhere it is.

**Comment by lloyd** [comment]
Oh so opinionated!  Last typed character is visible, yeah?

+1

--lloyd

**Comment by jrgm** [comment]
Also reported in https://bugzilla.mozilla.org/show_bug.cgi?id=790989
