### ISSUE TITLE
BrowserID completely broken in MIUI ROM Android stock browser 

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#1709]
Droid X running MIUI. Opening any BrowserID login will result in a "there has been a problem" window.

**Comment by shane-tomlinson** [comment]
@mattbasta - Can you provide further information?  What is the RP, are cookies enabled, is localStorage enabled, what version of Android is this, which version of the browser?

**Comment by mattbasta** [comment]
Are you in MV? I can do you one better and let you see my phone.
On Jun 8, 2012 3:11 AM, "Shane Tomlinson" <
reply@reply.github.com>
wrote:

**Comment by shane-tomlinson** [comment]
@mattbasta - I'm in London.  Maybe if you can get ahold of @benadida?

**Comment by jrgm** [comment]
I'm here in MV. Where are you? (I am on 3rd floor near Warp Core).

**Comment by mattbasta** [comment]
I start full time in a couple weeks, but I can drop by next week, if that
would work.
On Jun 8, 2012 11:10 AM, "John Morrison" <
reply@reply.github.com>
wrote:

**Comment by jrgm** [comment]
@mattbasta cool. @stephendonner told me that. Yeah, it would be cool if you could. Although I now have a Tegra board running Android 2.2 that shows this error. 

@matbasta did you have any certificate warnings when using this device with browserid (perhaps in the past and now remembered as accepted decisions).

**Comment by mattbasta** [comment]
No, I don't think I have used BrowserID yet on this device.

Fyi - cookies enabled, android 2.3
On Jun 8, 2012 11:49 AM, "John Morrison" <
reply@reply.github.com>
wrote:

**Comment by jrgm** [comment]
@mattbasta what do you have set as the default browser for this action? Can you try it with stock browser set as the default?

**Comment by mattbasta** [comment]
Stock browser is what I have set for everything.
On Jun 8, 2012 12:54 PM, "John Morrison" <
reply@reply.github.com>
wrote:

**Comment by benadida** [comment]
let's figure out exact STR and then adjust priority if need be.

**Comment by mattbasta** [comment]
I'm basing my experience on http://munchylunchy.com/ (see mattbasta/munchylunchy-frontend and mattbasta/munchylunchy-api).
1. Visit munchylunchy.com, press "Just Me"
2. Press "Let's Do This" (login button, triggers BrowserID)
3. The popup is opened with the error message "We are very sorry, there has been an error!"

The "More Info" bit says:

> Action: Establishing Relay
> Relay frame could not be found

**Comment by mattbasta** [comment]
I'm in the MV office this week. If you want to meet up, let me know.

**Comment by jrgm** [comment]
If you're in Mt. View Today or Friday, can you ping me @jrgm?

**Comment by jrgm** [comment]
I sat with @mattbasta today and his MIUI Android 2.3 phone. This is a screenshot of the windows in the error state. 

![img](https://img.skitch.com/20120621-6c5xc7tkjdb3j8yqfnjsqhmyh.png)

The Browser appears to have been set as the default, and Fennec (the only other browser) had no defaults set. I had Matt clear the default on Browser, and tried again, but 1) there's no prompt on this phone to pick a default as I see on my 2.2 and 4.0 devices, and 2) the error remains the same. 

@stomlinson perhaps you and @mattbasta can find each other tomorrow morning on IRC or via github to look at this some more. 

Oh, and I also checked logcat but that didn't show any thing interesting at the time the popup came up.

**Comment by shane-tomlinson** [comment]
@jrgm - this is an MIUI ROM, a third party aftermarket, are these common?

**Comment by mattbasta** [comment]
It's a Droid X that's been rooted/flashed with MIUI; it wasn't purchased with it installed.

**Comment by jrgm** [comment]
lowered to four-star

**Comment by mattbasta** [comment]
MIUI is on Android 4 now and uses Chrome, so this is a non-issue.
