### ISSUE TITLE
Getting 'failed to verify assertion: assertion has expired' with dev.{123done,diresworb}.org and IE9

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1710]
I was testing with ie9 and current dev.{123done,diresworb}.org which dev.diresworb.org/ver.txt says is at 'c7ff63c Merge pull request #1692 from mozilla/bugfix-clearing-expired-certs'. I had used dev.123done to sign up a secondary, add a primary, and then add a secondary. I met with @jbonacci  for a while after then, then closed my laptop and went home from the office. 

When I got home I resumed and tried to use IE9 again and got this dialog:

![img](https://img.skitch.com/20120608-xdu8pc3kw1b1i9suket5nipdcf.png)

It's repeatable. I've suspended this VM, although before that I also saved off the network traffic for one of the failures, and also saved off `JSON.stringify(localStorage)` in the context of https://dev.diresworb.org/privacy, so we can poke at this more tomorrow.

/cc @benadida, @lloyd

**Comment by jrgm** [comment]
I've been able to reproduce this from scratch conditions once (again with IE9), without anything complicating the situation like having my laptop go to sleep and change locations which might have explained something in the initial report. 

I don't, though, have a simple, reliable STR. And have only done this the two times with dev.diresworb.org and not diresworb.org.

**Comment by jrgm** [comment]
I should note though that in reproducing this the second time, I had to wait >1 hour for the cert of one of the emails to expire.

Crazy question: what if I had 3 users on the same account (2 secondary and 1 primary), and the cert on the localStorage.emails had 3 different lifetimes (1 hour (sec), 6 hour (pri), 24 hour (sec)). Is there a way the cleanupIdentities would not do the right thing in that case?

**Comment by benadida** [comment]
reproduce and provide me with assertion and localStorage, plus time plus VM time.

**Comment by benadida** [comment]
@jrgm are we downgrading this as per yesterday's conversation?

**Comment by jrgm** [comment]
@benadida Ah, yes. Didn't update it here. I have not been able to reproduce this aside from one time last against dev.diresworb.org. So, I am downgrading this to 4-star. 

Thanks.

**Comment by lloyd** [comment]
hmmm.  we had a bug related to this where assertions would be generated _before_ email verification.  I believe stomlinson fixed that.  Could this have been the same thing?

/cc @stomlinson

**Comment by jrgm** [comment]
@lloyd I don't think so, since when I got it in this state, I could then repetitively bring up the dialog, immediately pick the email to use, dialog would dismiss and this alert would come up. IOW, I wasn't delaying with the dialog up and the assertion slowly expiring.

**Comment by jrgm** [comment]
Okay. I understand what was happening. Until some recent changes to jwcrypto by @benadida, the root.cert on dev and ephemeral deployments did not have an issued at time in the certificate. [My failures both occurred against dev (which I was using because stage had not been deployed for train-2012.06.08)].

So, with no issued time in the cert, /wsapi/session_context returns 'null' for domain_key_creation_time. In user.js cleanupIdentities(), that means the actual cleanup code is never run. And so eventually, the browser winds up submitting assertions with expired certificates, and you get the alert with "assertion has expired".

Closing this issue.
