### ISSUE TITLE
Put the signup link at (or closer to) the top of main site pages

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1712]
This is not new and just a suggestion, but shouldn't "sign up" be at the top of the page somewhere. In particular, on a mobile device, signup is not "above the fold". Here's an iphone:

![img](https://img.skitch.com/20120608-bc4ydt472pjuj3f1ms6y9ep3yu.png)

**Comment by skinny97214** [comment]
Point noted. Closing since we'll be phasing this page out in favor of the new /about page.
