### ISSUE TITLE
router in tests showing 'error forwarding request: code=ECONNRESET'

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1713]
I was running `npm test` in an osx clean clone of current `dev` and noticed these warnings. So, that's about the 10k limit on POST; `router` seems to have the same check, but still the test shows the full request forwarded to browserid webhead. Perhaps this does not matter in prod/stage, but it would good to look into this. /cc @zaach

```
tests/post-limiting-test.js
·····router (63136): error: error forwarding request: code=ECONNRESET
····
✓ OK » 9 honored (5.523s)
```

**Comment by zaach** [comment]
Thanks @jrgm – I'll look into this.

**Comment by lloyd** [comment]
fixed with above mentioned merge.  see also (duplicate) issue #1745

**Comment by jrgm** [comment]
Verified stage train-2012.06.22. See https://github.com/mozilla/browserid/issues/1745#issuecomment-6639681
