### ISSUE TITLE
android: cookies disabled center area color mismatch.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1721]
![Android Screenshot](https://img.skitch.com/20120608-ny75u3hfps53r3j9hae2kfr65i.png)

**Comment by seanmonstar** [comment]
@shane-tomlinson So, the #error section ends up not stretching to the bottom, but the #wait section does. Is there a reason only #wait, #error, and #delay have the background? If it should always be there no matter what, then we could change the background to be on #content, which does properly stretch all the way down.

**Comment by shane-tomlinson** [comment]
@seanmonstar - Good examination, There are times where both a #formWrap, a #wait, and a #delay can all be shown at the same time, so this may be the reason.  This could also be a a remnant of the old design when the right hand side was white.  Try changing the background on #content to see how things look, you can open a development menu by opening the dialog and clicking the upper right hand corner 4 times. Then click on "show wait" and "show delay".  Finally, click on "show error"  If things look good, we have a winner!

**Comment by seanmonstar** [comment]
Wow, thats magic.

**Comment by jrgm** [comment]
verified stage train-2012.07.06
