### ISSUE TITLE
number_sites_logged_in not in KPI whitelist

### ISSUE THREAD

**Issue by nmalkin** [mozilla/persona#1730]
KPIs sent to the server are checked against a [whitelist](https://github.com/mozilla/browserid/blob/1a2c215461b48cb74f5ea486aa0358b015c8cf71/resources/static/shared/models/interaction_data.js#L13), but number_sites_logged_in (one of our KPIs) is not in it.

**Comment by ozten** [comment]
To finish of the KPI Backend, we need to populate all the fields of the KPI JSON blob that have been spec'd out.

Spec:
https://wiki.mozilla.org/Privacy/Reviews/KPI_Backend#Type_of_data_stored:

So we also need  number_emails, new_account, email_type, etc. Anything that is in the spec and missing from the blob.

**Comment by ozten** [comment]
@shane-tomlinson is it okay if I assign this to you? We need your magick powers.

**Comment by benadida** [comment]
@shane-tomlinson downgrade if this isn't blocking.

**Comment by shane-tomlinson** [comment]
closed with b1f30fb

**Comment by jrgm** [comment]
verified with an awsbox for train-2012.07.06

The keys in KPI_WHITELIST are sent with reasonable values:

```
email_type
event_stream
lang
new_account
number_emails
orphaned
sample_rate
screen_size
sites_signed_in
sites_visited
timestamp
```

One note, `new_account` is only sent when a new account is created. Filed as GH-2061 but may be acceptable as is.

**Comment by ozten** [comment]
@nmalkin just discovered the number_sites_logged_in was split into sites_signed_in and sites_visited.

This will be documented at https://etherpad.mozilla.org/kpi-dashboard-privacy-review-update-1-num-sites-logged-in
