### ISSUE TITLE
include jshint in unit tests

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1731]
We should create a backend unit test that ensures a clean jshint run, so we don't regress on all the cleanup @zaach did for us

**Comment by shane-tomlinson** [comment]
@lloyd - I'd like to do this on the front end too, but there is a lot of work that needs done.  I do this quite frequently on files I touch, cleaning as I go, but there are a lot of files that need treated yet.

For both the front end and the back end, we should come up with universal jshint config files so your jshint run does not yield different results from my jshint run.

**Comment by zaach** [comment]
It looks like you can supply the jshint module a custom configuration when using it from node, which would be useful if we only want to unit test for the more critical syntax mistakes and have a separate, more stylistically opinionated configuration for IDEs. Though it would be a good idea to commit common .jshintrc files for front-end and back-end code.

**Comment by jrgm** [comment]
verified for train-2012.06.22
