### ISSUE TITLE
(mobile) debug region gives feedback to end user

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1733]
STR:
1. load stage diresworb.org and tap once in the right place

Expected: nothing happens
Actual: region is highlighted (and in some mobile browsers also give click audio and/or haptic feedback).

It's hard to get it happen on an iphone, visible on ICS/ChromeBeta, and obvious on stock and fennec (ICS or 2.2)

**Comment by jrgm** [comment]
Actually, it's also visible in some desktop browsers when tab-cycling in the content (chrome win/mac, ie9, FF/win)

**Comment by benadida** [comment]
consider whether we disable in production.

**Comment by jrgm** [comment]
verified on stage train-2012.06.22
