### ISSUE TITLE
Verification screen flashes email address field before success message.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1734]
It's pretty ugly.

**Comment by lloyd** [comment]
+1  this bugs the heck outta me

**Comment by shane-tomlinson** [comment]
Link to #218

**Comment by jrgm** [comment]
verified on stage train-2012.06.22 - there is no flash of the email address either signing up new, or adding a user; re-using an already registered verify link brings up the new style dialog.
