### ISSUE TITLE
(ie8) 404 requests for background-image

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1736]
I was looking at logs on stage for a different reason, but noticed these 404 responses:

GET /v/d99a08c589/i/grain.png),%20linear-gradient(top,%20rgba(113,%20126,%20137,%200),%20rgba(113,%20126,%20137,%200.2) HTTP/1.0 404

The UA for those requests is always IE8. The 404's are not new to the current train.

**Comment by jrgm** [comment]
IE8 is IE8. That's the way it is. Closing.

**Comment by shane-tomlinson** [comment]
Re-opening, found the reason on http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax
