### ISSUE TITLE
BrowserID still in our strings

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1738]
Search for "BrowserID" here:
http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/templates/LC_MESSAGES/client.pot

And here:
http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/templates/LC_MESSAGES/messages.pot

Should we update these strings? Or remove them?

@ozten

**Comment by shane-tomlinson** [comment]
@mathjazz - That is an excellent catch.  I will update these in dev, can you update those strings before we ship the current beta->prod?

Fix checked in for string in client.pot in 0e040614f6a21975786e26334039d7c124569dc9

Fix checked in for string in messages.pot in 96b20bdbe046251cc10e2eb0f1616c9426ed77ef

**Comment by mathjazz** [comment]
@shane-tomlinson, thanks!

I guess you have to merge these changes to train-2012.06.08. Then I can extract and merge the strings again, translate them myself (simple search & replace should do the trick) and update SVN & Verbatim.
