### ISSUE TITLE
move to persona.org URLs

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1741]
production:
- browserid.org will redirect to login.persona.org for everything but verification requests
- login.persona.org will replace browserid.org
- static.login.persona.org will be the location all resources are served from
- verifier.login.persona.org will be the new verifier entry point

stage: 
- diresworb.org will redirect to login.anosrep.org for everything except verification requests
- login.anosrep.org will replace diresworb.org
- static.login.anosrep.org will be the location all resources are served from
- verifier.login.anosrep.org will be the new verifier entry point

dev:
- dev.diresworb.org will redirect to login.dev.anosrep.org for everything but verification redirects
- login.dev.anosrep.org will replace dev.diresworb.org
- dev.anosrep.org will redirect to login.dev.anosrep.org
- static.dev.anosrep.org will be where all resources are served from
- verifier.dev.anosrep.org will be the new verifier entry point

ephemeral deployments:
- *.personatest.org will be the url for everything

**Comment by jrgm** [comment]
verified for stage train-2012.06.22 for notes above and in https://bugzilla.mozilla.org/show_bug.cgi?id=767708#c5, except for "static.login.anosrep.org will be the location all resources are served from". The resources are all 200 OK, but it appears js/css come from static.login.anosrep.org, while images/fonts come from login.anosrep.org. (GH-1911 not all static resources being served from static.login.anosrep.org)

**Comment by shane-tomlinson** [comment]
@jrgm, @lloyd - Can we close this since the bulk of the work and rely on #1911 (not all static resources served from static.login) for the cleanup?

**Comment by shane-tomlinson** [comment]
@lloyd - is this work now done?

**Comment by lloyd** [comment]
thanks for finding this cruft, shane dawg.
