### ISSUE TITLE
Public URLs enabling to verify if an email is attached to a BrowserID account

### ISSUE THREAD

**Issue by Paul-da-silva** [mozilla/persona#1744]
Hi,

I looked a little at BrowserID and found something i think might cause some issues : when trying to login the process takes two steps. The first one doesn't require any anti-CRSF token and might enable people to get data from BrowserID.

The API call is a simple GET on https://browserid.org/wsapi/address_info?email=mail@domain.tld 

The answer is a simple JS object : {"type":"secondary","known":false}

Worst case scenario : 
I have a stolen database (let's say linked'in's ^^) 
I can go over all the emails i have, loop on them and curl this URL to know which one are attached to a BrowserID account (the "known" parameter will be set to true). 
If an account is known by BrowserID I save it with its pass (Linked'in's example, sha1 hash) in a new DB...
When the script is over I have a database with a few emails I'm sure are attached to BrowserID and a sha1 to try out on the login form (the next step of the login requires an anti-CRSF token and is therefore harder to script I guess - I did not look into the code though to see how said token is generated).

Knowing you already have an anti-CSRF process in the next step of the login and, as far as I saw, websites using BrowserID do not need to call this part of the API you could either add a token to this call (and switch it to POST ?) or remove this step completely and make a one step login...

I'm also concerned by the listing URL : https://browserid.org/wsapi/list_emails

As long as the browser used is compatible with the X-Frame-Options header it should be fine, but otherwise a scripting attack might be possible (source the URL in an iframe and get the data inside it using JS - using el.contentWindow.document.body.innerHTML on an outdated browser, will have to do some tests to confirm though) enabling a website to get the email address from all their (BrowserID connected, lazy-to-update-their-browser) visitors...

Regards,
Paul

**Comment by fmarier** [comment]
Here is another API call which allows the same lookup as address_info: https://browserid.org/wsapi/have_email?email=francois@mozilla.com

**Comment by warner** [comment]
Letting attackers probe for valid accounts is troublesome, yeah. I'm not sure we can do anything about it beyond rate-limiting queries, but I haven't thought deeply about it yet.

I don't think CSRF protection makes any difference to the scriptability of an attack: they just have to write a script that does a regular GET first, extracts the session cookie, then submits it with the next POST request. What it _does_ get you is protection against the attacker using your browser to submit requests of their choice.

I'd be pretty surprised if code from one domain can extract data from a frame sourced from a different domain: if so, most of the security boundaries we (and others) depend upon would be thrown out the window. If I remember rightly, the opener can _navigate_ the child frame (i.e. set its window.location= to something else), but cannot look inside unless they're from the same origin. Do you have any pointers to counterexamples?

**Comment by callahad** [comment]
If I recall correctly, @lloyd and I were thinking that the `known` parameter might be unnecessary. Eliminating it would solve this issue.

**Comment by fmarier** [comment]
@callahad the `/wsapi/have_email` endpoint would remain though, no?

**Comment by lloyd** [comment]
@fmarier correct.

As @warner said, the only reasonable tactic seems like rate limiting + captcha or some other turing test during times of abuse.

**Comment by lloyd** [comment]
link to https://bugzilla.mozilla.org/671998

**Comment by Brigit** [comment]
Curtis confirmed that he would like this changed to 4 stars and added to our beta-2 hit list so that he can close out the privacy review for browserid.  link to https://bugzilla.mozilla.org/671998

**Comment by jaredhirsch** [comment]
Valid but too big to get done before Beta 2. Bumping to Beta 3.

**Comment by jedp** [comment]
@lloyd is this something we want to pick up again?  This bug and the bugzilla bug have been quiet for some time.

**Comment by shane-tomlinson** [comment]
@lloyd, @callahad - is this something we are going to actually do? If not, can we shut 'er down?

**Comment by fmarier** [comment]
I'm guessing that some of these leaks will go away if we stop storing the list of email addresses server-side as per https://github.com/mozilla/persona/issues/4079.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
