### ISSUE TITLE
redefinition of variable in jschannel

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#1748]
The variable 'i', which stores the message id, is redefined in two for loops

First here, https://github.com/mozilla/browserid/blob/dev/resources/static/lib/jschannel.js#L161, and then again in the next block.

It doesn't seem to have any adverse effects, but at the very least it's confusing.

**Comment by lloyd** [comment]
merged, upstream patched, all unit tests and selenium tests pass.  calling this good
