### ISSUE TITLE
windows: node-statsd won't npm install

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#1751]
node-statsd package.json has an `os` property, that excludes windows from the party.

I don't know if a statsd daemon would even run on Windows, but I do see in `lib/statsd.js` that config turns it on or off, so it would be possible for a windows box to run the server with the config set to off.

**Comment by seanmonstar** [comment]
This could be fixed either upstream in node-statsd, or in browserid, by putting node-statsd as an `optionalDependencies`.

**Comment by lloyd** [comment]
is this the only known issue on windows?  I _expect_ there's going to be a _ton_ of problems getting browserid running there.  If that suspicion is true, I'd prefer we open a single big tracking ticket and assess the cost.

**Comment by seanmonstar** [comment]
Yea, I was going to go through and document each place it has issues, but I got distracted.

**Comment by jrgm** [comment]
verified on ephemeral train-2012.08.17 (and on a windows box that it punts on node-statsd fail). Leaving not marked verified because I will need to recheck this on stage.
