### ISSUE TITLE
Improve email inboxing

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#1755]
Confirmation emails (and others) are very important to have reaching people's inboxes.

They could be just getting into the spam folder, or the email provider could be blocking them from ever getting to the account. This can be improved with some good work.

**Comment by seanmonstar** [comment]
[37Signals](http://37signals.com/svn/posts/3096-giving-away-the-secrets-of-993-email-delivery) has some tips on how they do it, which include:
1. Signing the emails
2. proper RDNS
3. valid SPF records
4. others?

**Comment by lloyd** [comment]
we use socketlabs for delivery.  I have noticed (and I think @jrgm too) intermittent delays in email delivery.  

We should audit delivered emails, and work with socketlabs to improve anti-spam classification mechanisms and delivery times.

**Comment by skinny97214** [comment]
Do we have a mechanism for tracking how long it takes to deliver the verification email. Longer than about 10 seconds and we have a real UX problem.

**Comment by jrgm** [comment]
-> @lloyd to work with ops on improved monitoring of delivery

**Comment by lloyd** [comment]
personatestuser.org will give us a trivial means of understanding and auditing real roundtrip time.  we should have a first version ready in the coming weeks. /cc @jedp 

taking this issue.

**Comment by lloyd** [comment]
see: https://github.com/lloyd/personatestuser.org/issues/10

**Comment by shane-tomlinson** [comment]
@lloyd - you took care of this already, no?

**Comment by lloyd** [comment]
not yet.  we have monitoring on our outbound queue, but not of end to end delivery times.

**Comment by shane-tomlinson** [comment]
I have seen several ephemeral instance Persona HTML emails go straight to my trash in Hotmail.

**Comment by jaredhirsch** [comment]
I claim that this is no longer a significant problem. Reopen if I'm wrong, and we'll get some metrics in place to get visibility into failure rates.

**Comment by callahad** [comment]
I'm going to reopen for these specific tasks:
- [x] Add DKIM signature to outgoing mail
- [ ] publish our DKIM public key at `dkim._domainkey.persona.org` (TXT)
- [ ] publish a DKIM ADSP policy `_adsp._domainkey.persona.org` (TXT)
- [ ] publish an SPF policy at `persona.org` (TXT and SPF)

**Comment by jaredhirsch** [comment]
CHECKLIST WIN

**Comment by jaredhirsch** [comment]
@callahad ping? cc @oyiptong

**Comment by callahad** [comment]
I poked around in the SocketLabs dashboard, but I can't find our DKIM keys anywhere.

**Comment by monicachew** [comment]
Please use DMARC instead of ADSP. ADSP has no effect if, for example, a phisher decides to send from subdomain.persona.org (which could be nonexistent).

http://www.dmarc.org/index.html

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
