### ISSUE TITLE
Old version of nodemailer introduces global `util`, causes buggy side effects

### ISSUE THREAD

**Issue by zaach** [mozilla/persona#1756]
Bitten again by globals! The `layout.ejs` template file was using a reference to a global instance of `util`, which broke things when resources were served from a new static process rather than the browserid process. I tracked down the global `util` to the nodemailer module.

We should update our version of nodemailer (0.1.18) and explicitly pass `util` as a value to the views. The problem seems to be fixed in nodemailer version [0.1.24](https://github.com/andris9/Nodemailer/tree/e834625a88e3e6f8986a1df5144809ca59e556d7).

**Comment by lloyd** [comment]
verified mail is still delivered in dev environment.  No major regression.  yay.

**Comment by jrgm** [comment]
I haven't been experiencing any email issues with stage so verifying for train-2012.07.06
