### ISSUE TITLE
Create new process for serving static or "cacheable" resources

### ISSUE THREAD

**Issue by zaach** [mozilla/persona#1757]
We'll offload static files and rendered views from the browserid process and serve them from a new "static" process. This allows the browserid process to deal with white-listed WSAPI requests only. Eventually, static resources will be served from CDN.

**Comment by lloyd** [comment]
a strong +1

One note, I've been informed by QA and prod ops in no uncertain terms that before we add a new process we must consult them with an architecture overview, ideally before a line of code is written.  I will do this now, retro-actively for router.  For the static file server I think we need to respect their wishes and write it up.  I can do this, or you can @zaach...  Now /me gets to writing about router.

**Comment by zaach** [comment]
Short summary:

> We have created a new "static" process for serving the main site and associated static resources in order to reserve the browserid process for more dynamic, WSAPI requests. The router will be reconfigured to forward only WSAPI requests to the browserid process. Requests for static resources and Persona site pages will now be forwarded to the static process. The heartbeat of the router must be modified to check if the static server is responding, in addition to the browserid process.

webheads
    • /usr/bin/node bin/static

webheads: /var/log/browserid/
    • static.log
    • static-metrics.json

**Comment by zaach** [comment]
More [here](https://etherpad.mozilla.org/static-process).

**Comment by lloyd** [comment]
open?  who is open?
