### ISSUE TITLE
deprecate requiredEmail

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1760]

**Comment by lloyd** [comment]
proposal on mailing list to remove this feature: https://groups.google.com/group/mozilla.dev.identity/browse_thread/thread/ed0fe479f24f75ca#

**Comment by callahad** [comment]
If we deprecate requiredEmail in the current API, we should outright pull it from the Observer API before we announce the Observer API as stable.

**Comment by shane-tomlinson** [comment]
@callahad - that is why we are trying to do it now - we don't want to start with a feature and then yank it once beta goes out.

**Comment by jrgm** [comment]
verified in local dev train-2012.07.06
