### ISSUE TITLE
disable siteLogo from HTTP served sites.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1761]

**Comment by lloyd** [comment]
siteLogo is disabled on 123done until we can get SSL certificates:

https://github.com/mozilla/123done/commit/3bb0d38335dd0fed80b76b92864bbc265c8c515c

**Comment by jrgm** [comment]
verified against stage train-2012.06.22 with an awsbox converted to an rp. Also tried getting something not nice done with the params but didn't find a way, and tried out an oversize image, which was handled as expected by the CSS.
