### ISSUE TITLE
Simplify link to 'verified email protocol'

### ISSUE THREAD

**Issue by akumria** [mozilla/persona#1764]
README.md contains a link to 'verified email protocol', which forwards to:
- https://wiki.mozilla.org/Labs/Identity/VerifiedEmailProtocol

That link, however, states it is deprecated and suggests either:
 https://wiki.mozilla.org/Identity/BrowserID
 https://wiki.mozilla.org/Identity/Verified_Email_Protocol/Latest

The first, https://wiki.mozilla.org/Identity/BrowserID, suggests looking instead at:
- https://github.com/mozilla/id-specs/blob/master/browserid/index.md

The second,  https://wiki.mozilla.org/Identity/Verified_Email_Protocol/Latest, indicates it is deprecated and look at:
-  https://wiki.mozilla.org/Identity/BrowserID

Rather the linking to the wiki, please just link directly to the appropriate github spec.

Also, it would be good to remove / redirect as appropriate the wiki pages.

Finally, note that 'verified email protocol' is now called 'browserid spec'.

**Comment by callahad** [comment]
Thanks for the report! This is captured in #1672; waiting to resolve until pull request #1683 gets merged in. Closing this as  a duplicate.
