### ISSUE TITLE
Heartbeat of router should reflect health of browserid and static processes

### ISSUE THREAD

**Issue by zaach** [mozilla/persona#1767]
The router/browserid/static processes will live on the same box, so the health of the router process should reflect the health of those other processes. If they go down, it has nothing to route to.

/cc @lloyd

**Comment by lloyd** [comment]
I think this is the behavior right now.  router forwards 'ping' wsapi to browserid, who checks db conn, and responds.  We should make this more explicit.

**Comment by zaach** [comment]
@lloyd How about an options parameter on `setup` with a `dependencies` property:

```
heartbeat.setup(app, {dependencies: [dbwriter_url, browserid_url, static_url]});
```

Each `dependency_url+'/__heartbeat__'` is checked before the ok is given.

**Comment by lloyd** [comment]
I like dependencies.  I also think we should add a `custom` property so we can do things like check the database:

```
heartbeat.setup(app, {
    dependencies: [dbwriter_url, browserid_url, static_url],
    custom: function(cb) {
      //  first argument to cb is an err value, null or undefined on success.
      db.ping(cb);
    });
```

**Comment by jrgm** [comment]
@zaach is this work all done now? Can this one be closed.

**Comment by zaach** [comment]
Yep. Closing.
