### ISSUE TITLE
Fix load_gen to correctly send args to /verify

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1770]
I realized that the load_gen calls to /verify were ~silently failing because they were sending an assertion without the certs (correct my terminology if that's wrong). 

Sorry for having missed this earlier. load_gen itself was reporting all success due to a bug that cancelled out the first bug. It was just some chirping in the metrics log that led me to this. 

I have a PR to fix this (er, I think it fixes it). Also while I was there, I fixed the trivial issue GH-1278.

**Comment by lloyd** [comment]
@jrgm please verify things are as you expect after the merge and reopen if anything needs attention!

**Comment by jrgm** [comment]
verified
