### ISSUE TITLE
WinChan does not pick up dialog close while redirected to IdP

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1773]
STR

1) Go to myfavoritebeer.org
2) Click "Sign in"
3) Sign in with an IdP that will cause redirect to IdP.
4) Close dialog
5) Sign in button is still greyed out.

**Comment by lloyd** [comment]
how do we solve this?  tricky...  /cc @seanmonstar @shane-tomlinson

**Comment by seanmonstar** [comment]
It's an actual redirect, or just loaded in an iframe?

Wouldn't a redirect trigger the `window.onunload` from WinChan and kill it?

**Comment by lloyd** [comment]
so that's the trick!  window A opens window B.  Window B redirects to a different URL.  User closes dialog while window B has content loaded from a URL that has not loaded any winchan code.

In order to solve this I feel like we would have to detect close from the spawner of the window.

**Comment by seanmonstar** [comment]
That frankly seems like the safest place to do so anyways.

**Comment by jaredhirsch** [comment]
Ooh, this seems fairly tractable and self-contained. Ah well. Not getting in before Beta 2, that's for sure.

Bumping to Beta 3.

**Comment by seanmonstar** [comment]
taking this, as this blocks #2034

**Comment by seanmonstar** [comment]
this doesn't actually block #2304, but the fix still works for all browsers that support popup communication.
