### ISSUE TITLE
Button highlights for keyboard focus

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1774]
The buttons frequently do not have enough contrast between their active and non-active states and it can be difficult to tell which element has keyboard focus.

Should we highlight the buttons with a box-shadow in the same way we do for input boxes?

**Comment by lloyd** [comment]
on chrome I see no difference between beta and dev.  on firefox I now see buttons have a drop shadow to emphasize focus when they have it.  I think this issue was firefox specific and is fixed in dev.

**Comment by jrgm** [comment]
On stage train-2012.07.06 in all browsers x platorms I see the box-shadow when a button has focus with two exceptions:

1) winxp IE8 which doesn't have box-shadow (of course)
2) osx safari 5.17
