### ISSUE TITLE
Help pages aren't Persona branded

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1776]
OS: All
Browser: All

STR:
1. Load https://diresworb.org/ in the browser.
2. Click on the "Developers" link on the upper right side of the page.
3. Click on the "Need Help?->" link displayed on the bottom right side of https://diresworb.org/.

The pages opened are still referring to BrowserID instead of Persona: 
https://developer.mozilla.org/en/BrowserID/Quick_Setup
https://support.mozilla.org/en-US/kb/what-browserid-and-how-does-it-work.

It will be confusing for user to see "Persona" everywhere on the page, then open a help page and not see it mentioned anywhere.

**Comment by lloyd** [comment]
@callahad you got dis, right?

**Comment by callahad** [comment]
@lloyd Indeed. The wording is tricky, but Will and I are meeting up face-to-face in Bellingham, WA today to tackle a bunch of the doc polish issues. Thanks for the ping!

**Comment by shane-tomlinson** [comment]
Closing this as dup of #2186 and #2125, which are separated for MDN and SUMO.
