### ISSUE TITLE
Firefox: pressing enter key in email address on authentication page sometimes shows invalid address tooltip.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1780]
Likely introduced with PR-1729 for issue #1376

STR)

1) Load up BrowserID dialog
2) If logged in, click "this is not me"
3) In email field, partially enter an email address that has been used before.
4) From the auto-complete list, select an address, press enter.
5) Watch the tooltip be displayed.

**Comment by shane-tomlinson** [comment]
The order of events for a key press was incorrect in the unit tests.  The unit tests specify keydown, keyup, then keypress when it is in fact keydown, keypress, and finally keyup.

In Firefox, when pressing "enter" in an auto-complete box, the "keypress" key is triggered but not the "keyup" field.  In page_module, submit should be done on keyup instead of keypress.

**Comment by jrgm** [comment]
verified on stage train-2012.06.22 for FF.
