### ISSUE TITLE
IE8: Unit tests do not complete when slow script warning disabled.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1783]
STR)

1) Open an IE8 VM
2) Disabled the "A script on this page is causing Internet Explorer to run slowly" error by following the steps in http://support.microsoft.com/kb/175500
3) Reload IE
4) Start the unit tests.  They do not complete.

**Comment by jrgm** [comment]
verified I get a clean no error run on winxp/ie8 with awsbox instance of train-2012.07.20 (and of course with the registry hack to allow long scripts).
