### ISSUE TITLE
storage.retrieveTemporaryKeypair() is broken and possibly unused

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#1791]
The following code in /resources/static/shared/storage.js throws an exception:

```
function prepareDeps() {
  if (!jwcrypto) {
    jwcrypto = require("./lib/jwcrypto");
  }
}
```

It should of course be fixed like I did in 4ed942cfef0d3accf45807cd545dfd27864a9770.

It was never caught by our tests because this is the test for it:

```
test("retrieveTemporaryKeypair", function() {
  // XXX needs a test
});
```

Now, I did a quick grep of the code and could not find any uses of it in the codebase. So it looks like dead code that should probably be removed.

**Comment by shane-tomlinson** [comment]
@fmarier - store/retrieveTemporaryKeypair were taken out in b0534666e5fb16909544697bf0bb3153a88555df because it was not used.

**Comment by fmarier** [comment]
Ah! it got cleaned up the day after I rebased my branch onto the latest dev. Serves me right for not keeping up with the latest code :)
