### ISSUE TITLE
Fresh install as root didn't run ./scripts/generate_ephemeral_keys.sh 

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1795]
npm WARN skipping cannot run ./scripts/generate_ephemeral_keys.sh 

var was empty.

**Comment by jrgm** [comment]
And the answer is do `npm install --unsafe-perm` but there is a very very good reason why npm doesn't default to that ;-)

I don't see that in the npm docs, but see https://groups.google.com/forum/?fromgroups#!topic/npm-/HOr7xqNzR7k%5B1-25%5D for a hint. 

Closing.
