### ISSUE TITLE
Referring to the wrong button in TOS/PP text when typing password

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#1811]
While entering your password, the text below the text box is: "By clicking next, you confirm that you accept this site's Terms of Use and Privacy Policy."

![BrowserID](https://raw.github.com/gist/2963192/36e1ec2c185905bbfd545a30950ba060183e30ea/grant_p-s_bug.png)

However, the button at this stage is called "sign in".

This is also the case in the rebranded version of Persona that's featured on dev.myfavoritebeer.org.

![Persona](https://raw.github.com/gist/2963192/5f708ea14fbd75c28e5e95ee891c36894ce48f46/grant_p-s_persona_bug.png)

**Comment by jrgm** [comment]
See also GH-1240

**Comment by fmarier** [comment]
Dupe. Closing.
