### ISSUE TITLE
enter key causes forms to submit twice in Chrome and Firefox

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1813]
STR)

1) Open Chrome or Firefox
2) Open dialog
3) Open dev tools to network section.
4) If logged in, click "this is not me"
5) Enter in known secondary email address, press "enter" key - Address info is requested twice.
6) Enter password - "authenticate" is requested twice.

This is due to the changes implemented for #1376.

**Comment by jrgm** [comment]
verified train-2012.07.30
