### ISSUE TITLE
When running on iOS in a UIWebView, we sometimes get a Relay Frame error.

### ISSUE THREAD

**Issue by st3fan** [mozilla/persona#1822]
This does not happen always, but sometimes loading http://www.browserid.org in a UIWebView results in an error saying "Action: Establishing Relay. Relay frame could not be found".

I have only been able to reproduce this on iOS (5.1.1 and 6.0b1) when running in a UIWebView. Specifically for Pancake.

I must note that we inject the following code in the UIWebView before loading http://www.browserid.org in it:

https://bitbucket.org/mozillapancake/pancake-ios/src/750f5aee6945/Pancake/BrowserIDViewController.js

**Comment by st3fan** [comment]
I thought this could be a timing-related issue so I added a little delay between injecting the code and loading the site. Unfortunately that did not help.

**Comment by st3fan** [comment]
Another thing that I have tried is to delete all cookies from the www.browserid.org domain before showing the dialog. The code successfully deletes two cookies (one for / and one for /wsapi) but it has no effect on this problem.

**Comment by st3fan** [comment]
Another observation. I thought this could be due to some kind of state lingering around between usages of BrowserID. So to confirm that I did multiple runs of "Delete all Simulator Data. Run App. Login." - this problem still happens then. So that is on a first run without any existing cookies, cache or local storage.

**Comment by st3fan** [comment]
Tried running the latest code locally to see if that makes a difference, but it does not. Same issue happens on a fresh checkout of the browserid project.

**Comment by st3fan** [comment]
Also temporarily change the Pancake home page to skip all of our own JS code and just trigger the code that starts the BrowserID process in the modal dialog. To make sure that our own JS does not interfere with the BrowserID code. No effect.

Not sure what else to try at this point.

**Comment by st3fan** [comment]
I have fixed this with the following change https://bitbucket.org/mozillapancake/pancake-ios/changeset/499010192320

I think it is a workaround for a deeper timing problem inside the BrowserID code though. But this small 250ms delay basically makes the issue disappear. Previously probably 4 out of 10 tries would fail. With this fix I am unable to get the relay frame error at all.

**Comment by st3fan** [comment]
Hey so Stuart hinted that we should open the dialog by adding #NATIVE to the /sign_in url. And that worked great! Both the initial flashing of the error is gone and the Relay Error that would randomly happen is gone now. Even after I removed the fix that I referenced above.

Is the #NATIVE thing documented somewhere? Is it official? Can we depend on it?

**Comment by shane-tomlinson** [comment]
@st3fan - #NATIVE is official, let me check to make sure it isn't going anywhere.

**Comment by lloyd** [comment]
I mentioned this on some email thread.  But in the native case we don't need two things:
1. we don't need no jschannel
2. we don't need no winchan

What if we were to de-conflate /sign_in and have a special url dedicated to the native case that does not include winchan, and has a different, uh "main function", a different little bit of startup code.

The delta would be small, our build system handles this gracefully, and maybe this eliminates some error modes.

thoughts?

**Comment by st3fan** [comment]
On 2012-08-01, at 12:36 PM, Lloyd Hilaiel reply@reply.github.com wrote:

> I mentioned this on some email thread.  But in the native case we don't need two things:
> 1. we don't need no jschannel
> 2. we don't need no winchan
> 
> What if we were to de-conflate /sign_in and have a special url dedicated to the native case that does not include winchan, and has a different, uh "main function", a different little bit of startup code.
> 
> The delta would be small, our build system handles this gracefully, and maybe this eliminates some error modes.
> 
> thoughts?

Does the above mean that I don't have to inject any JS in the window anymore? If so, +1 :-)

Ideally at the end I just get a configurable redirect that I can intercept. Like to pancake-persona://getVerifiedEmail?status=success&assertion=DHEJKHDEJKHD

That would remove all need for custom JS to get things to work on iOS and Android.

 S.

**Comment by shane-tomlinson** [comment]
Closing in favor of #2034
