### ISSUE TITLE
Font too large when displaying rp_hostname without a siteName or siteLogo

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1826]
If the RP does not supply either siteName or siteLogo, we display rp_hostname as H2. When a siteName is given rp_hostname is an H3.

H2 is too large from a hostname (which is usually much longer than a siteName (e.g., www.mozilla.org vs. Mozilla)).

![img](https://img.skitch.com/20120621-rre5abs8ndrmsu4ws2yknpjbja.png)

**Comment by lloyd** [comment]
hey skinny, heres a thing

**Comment by skinny97214** [comment]
Follow smartell's mock 

http://f.cl.ly/items/2d3E30203E3f1d293N2W/persona-login-old.png

**Comment by jrgm** [comment]
verified on stage train-2012.07.06.
