### ISSUE TITLE
KPI data should acknowledge successful sign-in even after dialog is closed

### ISSUE THREAD

**Issue by nmalkin** [mozilla/persona#1827]
**Scenario:**
Dialog opens, new user enters email, creates password, verification email is sent. User _closes dialog_, goes to email client, clicks on verification link. Email is verified and user is logged in.

**The problem:**
When the KPI data is sent over (the next time the dialog is opened), the data contains no indication of whether the user succeeded or failed at logging in. (Our most important metric!)

(A similar problem affects other metrics, like users resetting their password or adding a second email address.)

**Proposed solution:**
When the dialog next opens, before sending over the KPI data, we should check
1. if the last event in the event stream is _user.user_staged_  
   This means the last thing we did is send a verification email
2. if the user is authenticated.

If they are, that means the user succeeded at signing in, and we modify the payload to acknowledge that.

**How?**
I think the cleanest solution is to change the _[orphaned](https://github.com/mozilla/browserid/pull/1807/files#L3R79)_ flag introduced in PR #1807. Because the dialog was closed before an assertion was generated, it would normally be _true_. But if we change it to _false_, we'll be able to tell that, even though the dialog was closed before an assertion was generated (this can be verified from the event stream), the user did manage to log in.

**Limitation**
If the user switches browsers (creates an account in one, verifies email in another, and/or logs in a different one), this method won't work. To account for this, we would probably have to wait until later in the flow to send interaction data or store some information about the user on the server. Both solutions have troubling implications, so, given that this case is generally unlikely, we should probably ignore it for now.

**Comment by nmalkin** [comment]
Thanks, Sean!

**Comment by seanmonstar** [comment]
@nmalkin is that correct? passing `{ orphaned: false}`, so you know it was orphaned and then adopted, or should I just delete the `orphaned` property out of it?

**Comment by nmalkin** [comment]
That's what I had in mind. I think it's clearer if it's set to false than if it's missing altogether.
