### ISSUE TITLE
ie6/ie7 exceptions thrown on 123done.org

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1830]
STR

1) Open IE6 or IE7
2) Load up 123done.org
3) Watch the errors flow

IE6 - JSON undefined
IE7 - localStorage undefined in state.js, then JSON undefined.

**Comment by shane-tomlinson** [comment]
I do not believe this is a regression, the unsupported dialog works fine in these browsers. The problem from what I could see is 123done does not take ie6 and 7 into account. 123done code tries to access localStorage and JSON without first checking for their existence. Even so, The new API code should be checked to make sure it at least does not except in these browsers.

Shane

**Comment by jaredhirsch** [comment]
closing in favor of mozilla/123done#4
