### ISSUE TITLE
123done.org: "Fork me on Github" button makes it difficult to click "logout" on mobile phones.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1833]

**Comment by benadida** [comment]
Highlighting the forkability is probably not our priority since this is our top demo site, and many users won't know what that means. I suggest making that subtle, on the about page.

**Comment by shane-tomlinson** [comment]
Link to mozilla/123done#64. Let's get rid of this thing and put a link in the footer.

**Comment by jaredhirsch** [comment]
mozilla/123done#64 is closed, closing this one accordingly :beers:
