### ISSUE TITLE
Android 2.3 Native: possible to focus hidden change password fields

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1837]
![Android 2.3 Native with hidden password fields focused](https://img.skitch.com/20120622-bs3mm6p23k64xcuafnbkdwnsyf.png)

**Comment by csuciu** [comment]
I am unable to reproduce on Samsung Galaxy R - Android 2.3 using stock browser and FF mobile.

@shane-tomlinson Are you still seeing this issue
