### ISSUE TITLE
Cutting the next train

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1841]
Sorry for bothering you once again, but we need the next train (train-2012.06.22) cut ASAP in order to have it fully localized in as many locales as possible.

Most of the localizers are working during weekends, so if we miss Friday target for cutting the train, localizers can end up having only one weekend for their job (50% less time).

/cc @lloyd @ozten

**Comment by lloyd** [comment]
cutting now.

**Comment by lloyd** [comment]
`train-2012.06.22` is branched - creating deployment ticket now,
