### ISSUE TITLE
Opera 12 Freezes on Signin

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#1844]
Reported via the mailing list at http://groups.google.com/group/mozilla.dev.identity/msg/caddd863207c2228

"With Opera the popup window freezes after clicking Sign In.  However, if you then close the popup and refresh the main page (123done.org) it turns out you are signed in to the site.

Opera Version 12.00
Build 1467
Platform Win32
System Windows 7"

**Comment by jrgm** [comment]
This is my failure. It turns out I have not tested Opera in a while. The dialog works fine and has a valid certificate, but the callback from navigator.id.get is not called. This also fails on the Mac, and `<strike>`for either 11.64 or`</strike>` 12. I suck.

**Comment by jrgm** [comment]
Actually correction to the above. 11.64 works on Mac, Linux, Win7. Opera 12, released Jun 14, fails on Mac, Linux, and Win7.

**Comment by seanmonstar** [comment]
I can get this happen on dev.123done.org, but not locally, and there error says "Security violation", so I assume it's because the domains differ on 123done, but not on local build.

There error is triggered in `cleanup`, specifically trying to do `w.close()`, after getting a `response` message: https://github.com/mozilla/browserid/blob/dev/resources/static/include_js/include.js#L778

**Comment by seanmonstar** [comment]
I've done several more combinations of testing, trying to isolate the error. I've tested locally with different domains, and with a redirect for the script (I had noticed 123done.org has the URL dev.diresworb.org/include.js, but it redirects), and nothing.

The only thing I haven't been able to successfully test is if the issue comes from dev.123done.org being on HTTP, and the popup is HTTPS. Are any of the test RP sites available on https?

**Comment by jrgm** [comment]
I'll switch an awsbox version of 123done.org back to https, and update here in a few minutes.

**Comment by jrgm** [comment]
I'm assuming you want this instance to use https://login.dev.anosrep.org/ (f.k.a. dev.diresworb.org), right. Anyways, https://j123done.personatest.org/ is now (hackily) using https://login.dev.anosrep.org/ for content and verifier. Let me know if you have a problem with it.

**Comment by seanmonstar** [comment]
Thanks for that. I still get a `Security violation`. 

My test case currently is a simple HTML page loading a downloaded copy of the include.orig.js. If I edit the `ipServer` variable to point at my localhost, it works fine. Pointed at https://login.dev.anosrep.org fails. I'll see what I need to do to run it locally on https in the morning.

**Comment by wrr** [comment]
Isn't the problem related to the 'Strict-Transport-Security' header?

This is a fairly new header and the new release of Opera adds support for it. The header prevents browser from sending any HTTP traffic to the domain (and optionally all subdomains). https://login.dev.anosrep.org/ sets the header (Strict-Transport-Security    max-age=2592000; includeSubdomains), maybe the behaviour you observe is intended effect of the header or a bug in  a way Opera implemented support for the header?

**Comment by seanmonstar** [comment]
The description of Strict-Transport-Security sounds like it shouldn't be affecting this at all, but I don't know for sure.

Either way, I'm having a heck of a time trying to reproduce this locally, or isolate what the exact issue is.

**Comment by karlcow** [comment]
with Opera 12 12.00 Rev 1467 Mac OS X 10.7.4,  I am unable to login on https://persona.org/
1. Go to https://persona.org/ with Opera Browser
2. Click on Sign-In. Result: a new tab is opening
3. Enter the email address in this tab. Result: Password field appears
4. Entre the password in this tab. Result: the lock appears.
5. Then a message saying to wait but nothing is happening.
6. Going back to the initial tab. Nothing has changed.
7. Reload of initial tab. Nothing changes.
8. closing browser
9. Reopening browser and going to https://persona.org/ Result: still not logged.
10. Clicking on Sign-In. Result: Open a new tab with my email id displayed and persona.org on the right.
11. clicking on identification. Answering "Yes" to the question. Result: sliding on the right and "identification" button shadowed.
12. Going to the initial persona.org tab. Reload. Result: nothing.

**Comment by seanmonstar** [comment]
the fix to this issue won't be available in production until this newest train is pushed live, in 3ish weeks?

**Comment by karlcow** [comment]
ok. understood. Thanks.

**Comment by jrgm** [comment]
verified fixed on stage train-2012.07.20 for opera 12.00 (e.g., via beta.123done.org). /sign_in dialog completes and dismisses now.
