### ISSUE TITLE
[stage] cross-origin issues with fonts

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1845]
STR
1. Start up firefox, open the error console and load https://login.anosrep.org

In the error console, there are multiple errors like:

```
Timestamp: 6/26/12 3:41:55 PM
Error: downloadable font: download failed 
    (font-family: "Open Sans" style:normal weight:300 stretch:normal src index:4): 
    bad URI or cross-site access not allowed
source: https://diresworb.org/v/1bf71be111/fonts/OpenSans-Light.ttf
Source File: https://diresworb.org/v/fb5534092a/production/browserid.css
Line: 0
Source Code:
@font-face {   font-family: "Open Sans";   font-style: normal;   font-weight: 300;   src: local("Open Sans Light"), local("OpenSans-Light"), url("https://diresworb.org/v/1112689d33/fonts/OpenSans-Light.eot") format("embedded-opentype"), url("https://diresworb.org/v/28c393ca13/fonts/OpenSans-Light.woff") format("woff"), url("https://diresworb.org/v/1bf71be111/fonts/OpenSans-Light.ttf") format("truetype"); } 
```

**Comment by warner** [comment]
From https://developer.mozilla.org/en/http_access_control and http://www.webfonts.info/resources/browser-support I get the sense that 1: this restriction is intended to discourage hot-linking of fonts (from other people's sites, without permission), and that 2: FF is the only browser which imposes this restriction.

**Comment by jrgm** [comment]
This was due to a config issue on stage with content served for diresworb.org from login.anosrep.org URL.
