### ISSUE TITLE
[stage] beta.123done.org does not finish loading the sign in button.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1846]
STR
1. Load http://beta.123done.org in FF or Chrome

The loading.gif image just continues to spin, and the sign in button is never shown. 

I notice that the iframe is written with src = 'https://diresworb.org/communication_iframe', the GET of that src returns a redirect to 'https://login.anosrep.org/communication_iframe' which then loads content that has '  <script src="https://diresworb.org/v/b7cb529baa/production/communication_iframe.js</script>' and that url is redirected to GET https://login.anosrep.org/v/b7cb529baa/production/communication_iframe.js. 

Shouldn't the built content have the new URLs?

**Comment by csuciu** [comment]
I'm still seeing this issue on mobile Firefox 14 (build from Google Play) and on Android stock browser.
The loading image continues to spin, and the sign in button is never shown.

Doesn't occur on Fennec Beta, Nightly and Dolphin

**Comment by jrgm** [comment]
Can you check that cookies are enabled in the profile for those browsers?

**Comment by csuciu** [comment]
Yes, cookies are enabled for both browsers

**Comment by jrgm** [comment]
We're morphing this bug a bit, which isn't great, but anyways. The original issue is resolved (it had to do with the content from login.anosrep.org refering to content from diresworb.org). 

I'll note that in addition to cookies disabled there are (at least) two other reasons that (beta.)?123done.org can be in a this 'permanent spinner' state. 
1. Failure to load GET /include.js from browserid.org (or login.anosrep.org or whatever host is playing that role). 
2. Failure in calling POST 123done.org/api/verify in a browser profile that is authenticated with browserid.org

Both of those conditions may be due to transient network or server errors.

/cc @lloyd 

I'm lowering this from 5 to 4-star.

**Comment by csuciu** [comment]
I'm able to reproduce this issue again on www.beta.123done.org using FF Release, FF Beta, FF Aurora and FF Nightly (Samsung Galaxy SII Android 4.0.3)

Works fine on Stock browser and on Dolphin

One thing that I noticed: On Stock browser and Dolphin, a 'Security warning' prompt is displayed when going beta.123done.org . This prompt is not displayed on FF

**Comment by jrgm** [comment]
So the current spinning is caused by an expired SSL cert which was GH-2224 but that was closed in favour of and operations ticket to get the new certificate in place -  https://bugzilla.mozilla.org/show_bug.cgi?id=780300

**Comment by jrgm** [comment]
So there are two tickets open for mozilla/123done 
1. https://github.com/mozilla/123done/issues/37 - 'javascript exception if include.js fails to load' which is the current noted reason for spinning that forever
2. https://github.com/mozilla/123done/issues/36 - 'sign in button never shown if cookies are disabled' 

I'm closing this bug. Issues specific to 123done should be filed there as distinct root causes.

**Comment by jrgm** [comment]
Also to note, since github made changes today in notifications and I'm watching 123done, I will see any new issues or changes to those issues put in for 123done. Yay, I like this change in github.
