### ISSUE TITLE
dismissing /sign_in -- Error: b.setStagedOnBehalfOf is not a function

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1848]
STR:
1. checkout and npm install train-2012.06.22
2. npm start
3. Load 127.0.0.1:10001 in FF and open Error console
4. Click 'Get an assertion' and then just close the popup window

Expected: nothing in Error console

Actual:  

```
Timestamp: 6/26/12 8:19:17 PM
Error: storage.setStagedOnBehalfOf is not a function
Source File: http://127.0.0.1:10002/dialog/resources/state.js
Line: 66
```

Missed one in https://github.com/mozilla/browserid/commit/05df1ff2aa9642c9dc82ee75318f7afbb520ea1b

**Comment by shane-tomlinson** [comment]
@jrgm - This was fixed in checkin b1f30fba on 06.20.2012.  https://github.com/mozilla/browserid/commit/b1f30fba#L3L66.  This got merged in to dev on 06.26.2012.  Closing as already fixed.

**Comment by jrgm** [comment]
@shane-tomlinson by already fixed, you mean you're cool with this problem going into production next week?

**Comment by jrgm** [comment]
belatedly marking verified for stage train-2012.07.20 and local dev train-2012-07.30 for original STR.
