### ISSUE TITLE
images on new /about page are not cachified.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1851]
They are not yet hooked up to @ozten's awesome connect-cachify so they do not have the correct caching.

**Comment by seanmonstar** [comment]
@shane-tomlinson are the other images supposed to be cached already? such as the grain.png, the logo, etc? Because those don't seem to be either...

**Comment by jrgm** [comment]
verified in stage train-2012.07.06

These /pages/i URL are served with:
  Cache-Control public, max-age=31536000 (one year) and an Etag

```
https://static.login.anosrep.org/v/9131110f23/pages/i/one-password-graphic.png
https://static.login.anosrep.org/v/aac0db543f/pages/i/flexible-graphic.png
https://static.login.anosrep.org/v/109731bcab/pages/i/developers-link.png
https://login.anosrep.org/v/4d0ad62cd5/pages/i/marketplace-header.png
https://login.anosrep.org/v/f3427f7dd5/pages/i/persona-logo-wordmark.png
```

Returning to /about from another page does not make a network request.
