### ISSUE TITLE
compress TTF font files

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1855]
I'm a total newb with webfonts, but I was looking at network logs... The TTF font files we serve to some browsers are ~250KB. Default gzip cuts that to ~125KB. 

So, either we should serve those with gzip transfer encoding, or if there is some preprocessing tool for TTF, use that.

**Comment by lloyd** [comment]
@fetep - this should just be adding a mime type to a list in nginx, right?

**Comment by fetep** [comment]
yeah. right now we have `gzip_types text/html application/javascript text/css;`

**Comment by gene1wood** [comment]
jrgm determined an example url and the mimetype in play
- https://login.anosrep.org/v/c7dcce084c/fonts/OpenSans-Italic.ttf
- application/x-font-ttf

**Comment by jrgm** [comment]
For e.g., https://static.login.anosrep.org/v/f577763f76/common/fonts/OpenSans-Bold.ttf, if requested with accept-encoding gzip, deflate, the content is served with transfer-encoding gzip. 

Oddly though, some browsers that last week were requesting ttf are no longer doing so (e.g., IE9 on win7).
