### ISSUE TITLE
windows (xp/win7) - main site font issues

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1856]
1. the 'Signup' button is on two pieces
2. the fonts have some defects (Not sure if this 3 times copied image will show this that well, though).

![img](https://img.skitch.com/20120628-fpqq65546atyh6bc9gx7nhgnad.png)

**Comment by jrgm** [comment]
Actually, the characters are also a bit jagged from Chrome, FF, Safari on this win7 VM. Not IE though.

**Comment by seanmonstar** [comment]
My google-fu tells me that IE does magic, and makes it look good, and other browsers don't. And there's no decent CSS properties you can set to make it look better (text-shadow is already set), so my only other conclusion is that the hinting isn't good? But I ran the font through both font-squirrel and ttfautohint, and got the same results.

Maybe just a different font for Windows?

**Comment by jrgm** [comment]
I split out the issue about the split signup button on Opera to GH-1885. 

So this issue is just about the font display issues on windows for non-IE browsers. 

@seanmonstar yeah, I think windows uses eot (at least in some cases) but I know zero about webfonts.

**Comment by jrgm** [comment]
I split out the issue about the split signup button on Opera to GH-1885. 

So this issue is just about the font display issues on windows for non-IE browsers. 

@seanmonstar yeah, I think windows uses eot (at least in some cases) but I know zero about webfonts.

**Comment by seanmonstar** [comment]
@jrgm Firefox debugger was showing requests for the .woff font file.

**Comment by lloyd** [comment]
@jrgm please verify that we're displaying non-latin locales legibly, and decrement priority if so.

**Comment by jrgm** [comment]
I looked at all the locales on stage and they eyeball ok for FF on Mac. Gonna try chrome and IE in a bit. Lowering to 4-star.

**Comment by seanmonstar** [comment]
If font doesn't contain a character, it will drop down the font stack to the next font. So, perhaps the locales with cyrillic or greek etc alphabet render in Lucida Sans instead?

**Comment by jrgm** [comment]
Ah, true. I poked at this in firebug, removing the Open Sans from the style for Greek and Russian, and at least for those two, it was the Open Sans that was being used. But either way, we get something legible. So, that's fine.

**Comment by jrgm** [comment]
has also been noted in https://bugzilla.mozilla.org/show_bug.cgi?id=774576

**Comment by Inkbug** [comment]
Thanks for fixing this - when will this go to the live site (the site is really unreadable)?

**Comment by jrgm** [comment]
The fix is in current stage, but it won't go live for another two weeks.

**Comment by jrgm** [comment]
verified stage train-2012.07.20 on winxp/vista/win7 x opera/safari/chrome/ff/ie(8/9) and osx safari/opera/chrome/ff, ubuntu chrome/opera/ff, android 2.2 and 4.0 stock and ff/beta/aurora, iphone/safari. Fonts look alright on all, although there still is some lack of anti-aliasing for non-IE windows browsers.

**Comment by gene1wood** [comment]
Just saw this on firefox 14.0.1 at home :

http://imgur.com/W8GSs

**Comment by seanmonstar** [comment]
Fix isn't live yet. It's in the currently staged train.
