### ISSUE TITLE
Rpm version string improvement

### ISSUE THREAD

**Issue by david-caro** [mozilla/persona#1859]
Hi,
I'm using the browserid server at work, and the version string does not adapt to the requirements of the company. I'd like to change the version string to something a little more descriptive, here's my proposal (as I explained to fetep):

_Major.branch[-num-commits_hash-of-last]_

**Version string (just modified a little):** _MAJOR.tagname/branchname_
This is the the closest tag name (or the branch name, if there are no tags before the branch) prepended with the _MAJOR_ (a custom number to reflect a major release, mandatory if the changes made result on a code that is not backwards compatible).

**Release string:** _Num-of-commits_sha_
This will be the number of commits since the tag/branch and the short sha of the last commit, to reflect that the code is different in the case of packages from different repos or a rebase (bad rebase!). This can be easily retrieved with the describe command.

Also adding the source repository on the description, to keep track of the source of the code. And the info about the translations.

A sample version string will be this:

_0.train_2012.07.15-12_fa3613f_

That means the 12th commit after the tag _train_2012.07.15_. If you commit again, the tag will be something like:

_0.train_2012.07.15-13_11fa5d_

Even if the hash is not incremental, the version string is incremental (because the number of commits is placed before the hash). And, if you use a different repo with the same tag/branch, and the same number of commits, you see that the hash has changed (that doesn't necessarily mean a bump on the version).

What do you think?

**Comment by lloyd** [comment]
@fetep what do you think about an update to rpm scripts to append sha to version?

**Comment by david-caro** [comment]
Seeing that no one complains about this, I've changed the build script and the spec file to use this new version format. Opened the Pull request https://github.com/mozilla/browserid/pull/2192

**Comment by lloyd** [comment]
@gene1wood how does this look to you guys?

**Comment by ozten** [comment]
+1

FWIW

**Comment by gene1wood** [comment]
Is the "get_ci_count" function still being used now that you're determining the number of commits with the "git describe" queries?

**Comment by david-caro** [comment]
No, it's not used here, but I've found some problems when calculating the commits when there's a branch and no tags newer, and I'm preparing a new commit (that uses this function again).
I hope to upload it today (I'm just testing it, but the new version of browserid requires node >=0.8 and I'm just installing it to check if everything is ok.

**Comment by gene1wood** [comment]
Cool

**Comment by lloyd** [comment]
I closed down the pull request referencing this because it was stale.  Do we still have people that care deeply about this issue?  @gene1wood or @6a68 - any thoughts?

**Comment by gene1wood** [comment]
I wouldn't say that I care deeply but it would be nice to get out of the business of manually incrementing the "release" value in our spec file.

This is our current model

```
browserid-server-0.2013.01.18-1.el6_112472.x86_64.rpm
name : browserid-server
version : 0.2013.01.18
release : 1.el6_112472
archiecture : x86_64
```

Until we break localization out into it's own RPM and while we continue to use a git app code and svn localization model, we would need to retain the svn revision of the localization in the release value somehow.

In summary, in it's current state I agree it should be closed but it sure would be nice to get some of this functionality.

**Comment by david-caro** [comment]
Hey, actually I changed my job and I do not need this anymore (I suppose that someone from my old company should be continuing that work :S). But If it's useful, I do not mind trying to adapt it to the project needs instead of my old company ones :)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
