### ISSUE TITLE
sync_emails->unknown_emails field full of garbage if POST's emails field is empty

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#186]
POST info:

csrf    28727cbba5db3efba5a59120f085ef43
emails  

RESPONSE:
{"unknown_emails":["bold","underline","italic","inverse","grey","yellow","red","green","blue","white","cyan","magenta","rainbow","zalgo"],"key_refresh":["testuser@testuser.com","testuser3@testuser.com","testuser25@testuser.com","testuser26@testuser.com"]}

**Comment by lloyd** [comment]
wow.  that's so... interesting.
