### ISSUE TITLE
Translate the main site

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1862]
Comes from #1824

**Comment by ozten** [comment]
Status update?

Maybe this is causing Issue #2147 ?

**Comment by lloyd** [comment]
This is done

**Comment by shane-tomlinson** [comment]
@jbonacci - https://github.com/mozilla/browserid/pull/2047/files - The entire main site was gettext'ified meaning the main site strings are now extracted and sent to localizers.  /tos and /privacy are not yet localized pending direction from the legal team.

Before PR #2047, only the main site headers and footers were localized.
