### ISSUE TITLE
identification fails on chrome for iOS (iPad/iPhone)

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1870]
When trying to do identification on chrome for iPad, we get the following error:

Action: Establishing Relay
Relay frame could not be found

**Comment by tonychung** [comment]
Can u check if your browser cookies are enabled?

**Comment by ghost** [comment]
Yes, cookies are enabled :

Menu -> Settings -> Content Settings -> Accept Cookies = On

**Comment by lloyd** [comment]
4 stars to diagnose

**Comment by seanmonstar** [comment]
I played in jsFiddle for a while, and any way you do it, `window.opener` is undefined.

At least, I've filed a bug upstream: http://code.google.com/p/chromium/issues/detail?id=136610

**Comment by shane-tomlinson** [comment]
Closing in favor of #2034
