### ISSUE TITLE
Firefox showing Unsupported Browser dialog

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#1878]
Reported by @carlacasilli on Yammer. Screenshots are attached to https://www.yammer.com/mozilla.com/#/Threads/show?threadId=187338156

It appears that she's at least using AdblockPlus, NoScript, and TrackerBlock, but I can't reproduce her failure mode.

Symptoms: The popup shows the unsupported_dialog ("We are sorry, but currently your browser is not supported.") The homepage at browserid.org loads the header (logo + how it works / developers / sign in) and the footer (PP / ToS / Need Help), but no content in the body.

**Comment by lloyd** [comment]
@jrgm plz dig in and adjust priority

**Comment by carlacasilli** [comment]
System info: Macbook Pro, Mac OS X 10.6.8, FF 14.0.1. 
Aug 03, 2012: Restarted with all add-ons disabled, still no access to Persona. Same error as screenshotted on Yammer.
Can sign in fine using Safari & Chrome.

**Comment by shane-tomlinson** [comment]
@carlacasilli - Hi! Can you check in about:config whether dom.storage.enabled is set to "true"

**Comment by benbuck** [comment]
@shane-tomlinson Thanks, I had this issue and changing dom.storage.enabled from false to true fixed it for me.

**Comment by antoniusf** [comment]
@shane-tomlinson I disabled the DOM storage for security and had the same problem. I guess I'll have to reenable it now for using persona, but I'm finally able to log in again. Thank you!

**Comment by carlacasilli** [comment]
This is still a problem for me and I do not know how to check is DOM storage is enabled. If you provide the steps to do so, I'll happily check (although I will be away from this computer for about 3 weeks as of tomorrow). Thanks!

**Comment by callahad** [comment]
@carlacasilli Could you please visit this URL and tell us what the output is?

http://lloyd.github.io/persona-troubleshoot/troubleshoot.html

**Comment by carlacasilli** [comment]
Hey Dan,

I'm attaching two screenshots:
1) NoScript enabled preventing github.io from loading
![screen-shot-2013-07-20-at-12 01 12-pm](https://f.cloud.github.com/assets/1039302/830737/396cf6ae-f170-11e2-8187-ec2a38304811.gif)

2) NoScript disabled allowing github.io to load
![screen-shot-2013-07-20-at-11 59 53-am](https://f.cloud.github.com/assets/1039302/830738/4c8484a0-f170-11e2-85b7-92554f2133d9.gif)

Not sure you need the distinction, but on the off chance it informs you just a bit more. Thx!

**Comment by callahad** [comment]
@carlacasilli Thank you!

If you could please visit about:config and change "dom.storage.enabled" to "true", I believe that would fix your issues.

How it got into that state in the first place, though...

**Comment by jrgm** [comment]
Closing, since presuming this is fixed.
