### ISSUE TITLE
Account creation does not accept pasted passwords until after a key event

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#188]
At the account creation dialog, I typed my email address, and pasted in a pwgen-generated secure password twice.  However, the dialog still said "Enter a password" until a keyboard event occurred in one of the password fields, at which point it changed to a green "Password OK".

(Note that I middle-click pasted the password; right-clicking and choosing "paste" has the same effect, but using Ctrl-V triggers a keyboard event and thus doesn't reproduce this bug.)

**Comment by lloyd** [comment]
please retest against the shiny new UI: http://dev.browserid.org
