### ISSUE TITLE
win7/opera 11.64 - main site layout issue with split signup button

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1885]
I'm splitting out this issue from GH-1856 where initially I thought both the font and signup button layout issue were just for Opera. The font issue also affects other browsers on windows; I've only seen the split signup button on Opera/windows. 

So this issue is about the "split button" layout. 

![img](https://img.skitch.com/20120628-fpqq65546atyh6bc9gx7nhgnad.png)

**Comment by seanmonstar** [comment]
I couldn't reproduce in Opera 12:

![opera 12 screenshot](https://raw.github.com/gist/f521432a9e4badfd21c6/217aba2cb24ba11edc29842fb37fd7074979e651/opera-12-signup.png)

**Comment by jrgm** [comment]
Oh, I see. It depends on the window width. Try narrowing the window and 1) the text will reduce in size, and 2) the button will split. (Not seen in the other current browsers on win7; haven't tried on the other OS's, but I think that's not relevant).

**Comment by seanmonstar** [comment]
Woops. I don't why I didn't think to shrink the window. I see it now.

**Comment by jrgm** [comment]
@seanmonstar I didn't think of it either when I reported the issue. Only when you noted it worked for you and I couldn't do the same with same version of Opera on the same box where I first saw it.

**Comment by jrgm** [comment]
Oh, and I see this on win7 for both opera 12 and 11.64.

**Comment by jrgm** [comment]
verified stage train-2012.07.20
