### ISSUE TITLE
Account creation form does not cause browser to offer to remember password

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#189]
After creating an account, I expected Firefox to prompt me to save the username and password for the newly created account, but it did not.  Please ensure that the account creation form triggers that prompt from Firefox.

**Comment by lloyd** [comment]
this is fixed on beta.  please confirm via http://beta.myfavoritebeer.org and re-open the issue if you believe that I'm lieing.

thanks for the report!
