### ISSUE TITLE
add email screen: "Checking with your email provider" message not removed after addressInfo completes. 

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1892]
STR

1) Open up dialog
2) sign in if not signed in
3) Click "add another address"
4) Add a new secondary address
5) close dialog
6) Open dialog
7) Click "add another address"
8) Enter same address - tooltip will be shown, "checking with your email provider." is not removed.

**Comment by jrgm** [comment]
verified on stage for multiple desktop/android browsers stage train-2012.07.06
