### ISSUE TITLE
layout of "assertion->password" level authentication screen needs updated to match new styles.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1896]
The screen the user enters whenever they are authenticated to the assertion level, selects a secondary address, and must enter their password needs updated to match the new authenticate screen.

**Comment by shane-tomlinson** [comment]
@skinny97214 - I started to modify the "enter password" screen, but it could use some UI love.

![Assertion->Password enter password screen](https://img.skitch.com/20120705-qcerrtrwetdt48ntr2cx8fa53x.png)

**Comment by skinny97214** [comment]
@shane-tomlinson I need more context here. I read it four times and I still don't understand wat is. What is it supposed to match to? Can you attach a screenshot?

**Comment by shane-tomlinson** [comment]
@skinny97214 - the above screen shot is for when a user has to enter their password after they have selected an email address.

This happens when a user signs in to Persona using a primary address, and then selects a secondary address.

The current main authentication page - 

![authentication page](https://img.skitch.com/20120713-r72ac32kmpe8arpt4pcnm3p1jf.png)

The current "enter your password after selecting a secondary address page":
![enter your password after selecting a secondary address](https://img.skitch.com/20120713-b1tfjxpk1ygawuia8n9hq3ipa6.png)

You can see the "enter your password after selecting a secondary address" page uses the old style with the "forgot your password" link on top of the password field.

I am trying to unify the layout between the two so there is some consistency ![proposal](https://a248.e.akamai.net/camo.github.com/44205777f2579a7b03e153a08b03e4d6962693bb/68747470733a2f2f696d672e736b697463682e636f6d2f32303132303730352d71636572727472776574647434386e74723263783866613533782e706e67)

**Comment by shane-tomlinson** [comment]
This has been taken care of, closing.
