### ISSUE TITLE
No obvious way to log out

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#190]
After discovering that the account creation form did not trigger Firefox's prompt to remember the username and password (filed as issue 189), I figured I'd log out and back in, and see if logging in triggered the prompt.  However, I did not find any obvious way to log out.

**Comment by lloyd** [comment]
I put this one in the UX bucket.

FWIW, the current way to logout is to click "this is not me" in-dialog.

**Comment by shane-tomlinson** [comment]
@lloyd - in the new design, I initially put in the "sign out" button, but the "this is not me" was re-added to the pick email screen.  I am of the opinion that we should put the "sign out" button back in so that it is obvious how to sign out for the users that want to sign out.  Thoughts?

**Comment by benadida** [comment]
@lloyd and I thought this would be confusing, because sign out of what? The site? BrowserID?

**Comment by shane-tomlinson** [comment]
@benadida @lloyd - good point.  It does seem hokey to "sign out" using the dialog just after you click a "sign in" button.

**Comment by shane-tomlinson** [comment]
@jbonacci - from the dialog it has not, we had a discussion about this and the overall comment was "it seems strange to hit a sign in button to sign out of browserid" and the conclusion was that sign out should probably be part of the manage page?  Could use some UX love with this.

**Comment by shane-tomlinson** [comment]
@jbonacci - there is an explicit way to sign out using the main site, just not in the dialog.  In the dialog it is the "this is not me" link.
