### ISSUE TITLE
Dialog displaying wrong translations

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1905]
In our dev environment we're now extracting strings on every push, with the intention of making it so we can always meaningfully debug translations against dev.

The problem is english translations are off.

![translations off](https://img.skitch.com/20120703-ch8hi7jp3wmxqf61176h8bqn2i.png)

Notice that the fields here say "reset password" rather than "create password" and "verify password".  @ozten, what is the intent of the en_US .po files, and how do we manage them in production?  

Here is what I'm doing to extract strings on every push: https://github.com/mozilla/browserid/blob/dev/scripts/awsbox/post_deploy.js

**Comment by ozten** [comment]
@mathjazz can you help with this issue?

In general - Mozilla web properties have en_US po files. What you see are the painpoints that other locales hit when we change or modify strings. It's kind of a nice warning signal as to what we'll have to give other locales a heads up on.

@mathjazz will know, but probably removing fuzzy strings will fix this.

**Comment by lloyd** [comment]
I think all we need to do to fix this is to re-initialize the .po files for en_US and extract all strings.  I don't have permissions to do this.  Can someone who does have permissions help?  

This issue affects production and makes our dialog look silly.  see also #1675.

**Comment by lloyd** [comment]
or better yet, just `rm -rf locale/en_US/`

**Comment by mathjazz** [comment]
@lloyd If I read correctly, you're now trying to ignore en-US PO/JSON files and display original strings instead? Looks good to me.

**Comment by lloyd** [comment]
@mathjazz we need a fix for this in the train we are rolling on monday, `train-2012.06.22`.

Can you _delete_ the en_US po files from svn?

I will make a patch to fix dev and ensure that en_US translations are not used from our side, but that patch is too risky to go in this train.

@jrgm - would you be ok with having @mathjazz delete the .po files before we generate strings today?

**Comment by lloyd** [comment]
fwiw, locally I checked out svn, deleted en-US, ran everything, and translations in en_US look great, other locales display as expected.

**Comment by lloyd** [comment]
fixed in dev.

rolling out to stage: https://bugzilla.mozilla.org/show_bug.cgi?id=767708#c26

will be in production monday.

closing down this issue.

**Comment by jrgm** [comment]
This particular example looks fine on stage train-2012.07.06. Verifying but will continue to look for oddities in the next train.
