### ISSUE TITLE
Date and time of signin badly formatted

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#191]
I currently see "Signed in at 1:4:26, 7/0/2011".  That seems wong. :)

**Comment by lloyd** [comment]
so we'll zero pad minutes and base 1 day.  

For reference, this is on the manage page and code is here: ./browserid/static/js/browserid.js

**Comment by lloyd** [comment]
you can test this on http://dev.myfavoritebeer.org and https://dev.diresworb.org

**Comment by shane-tomlinson** [comment]
@jbonacci: Can you check this on dev, as @lloyd put in a fix for it.

**Comment by lloyd** [comment]
thanks @shane-tomlinson,

you can the fix on http://dev.myfavoritebeer.org and https://dev.diresworb.org (and it's NOT on beta yet).

Closing, please re-open if I'm missing something.
