### ISSUE TITLE
front-end tests timing out at /dialog/views/error.ejs

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#1916]
getting this:

```
router (15324): info: forwarding request: /dialog/views/error.ejs -> http://127.0.0.1:10007/dialog/views/error.ejs
'waitFor()' timeout
✗ · · 

  frontend unit tests
    ✗ pass!
      » expected 0,
    got  1 (===) // vows.js:91
✗ Broken » 6 honored ∙ 1 broken (180.043s)

```

**Comment by zaach** [comment]
Seems to work for me:

```
router (88508): info: forwarding request: /dialog/views/error.ejs -> http://127.0.0.1:10007/dialog/views/error.ejs
'waitFor()' finished in 65519ms.
Tests completed in 65352 milliseconds.
1202 tests of 1202 passed, 0 failed.
· · · ✓ OK » 7 honored (69.607s)
```

**Comment by jrgm** [comment]
wfm phantomjs on osx

**Comment by jedp** [comment]
It's intermittent for me on Linux.  It works sometimes, times out sometimes.  I just re-ran front-end tests twice.  First time they passed; second time they timed out. :(

**Comment by jedp** [comment]
@zaach - whoah - 69 seconds?  These always take at least 170 sec on my quad i7 2.8GHz with Linux.  Dang!

**Comment by jrgm** [comment]
Offtopic but with a vmware Ubuntu 11.10 running on physical mac quad i7 2.3 I get:

Mozilla/5.0 (X11; Linux i686; rv:16.0) Gecko/16.0 Firefox/16.0
Tests completed in 30112 milliseconds.
1202 tests of 1202 passed, 0 failed.

179 seconds? Huh?

**Comment by jedp** [comment]
Nor I. :)
