### ISSUE TITLE
why do we need node-gettext?

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1917]
node gettext requires iconv, which is the slowest building native dependency we have.  The frontend uses .json files, while the backend reads directly from .mo files.

I wonder.

because our i18n flow generates both `client.json` (strings needed on the client) files, and `messages.json` (strings needed on the server), could we use the `messages.json` strings (instead of binary .mo files) on the server and have a simpler i18n process?

The reasons I'm interested in exploring this:
1. building iconv@1.1.3 accounts for **65%** of the time it takes to `npm install`
2. travis-ci often kills our tests cause they take too long (see #1)
3. this version of iconv crashes on node 0.8 - not important now, but will become important in the future
4. there will probably be a performance improvement
5. it probably will simplify our code

I think we could move off of node-gettext at very low engineering cost and remove this costly and fragile dependency, but it's worth noting that iconv@1.2.1 builds 3x faster... I don't know if there are breaking changes there...

Now if we chose to use a pure javascript implementation of gettext, would backing it with mofiles be better than backing it with the json files that we're already generating?

**Comment by seanmonstar** [comment]
if this is the only reference to iconv, then that would remove a big blocker to installing on Windows (#1769)

**Comment by lloyd** [comment]
fwiw, I tried the update to iconv@1.2.1 and it makes our build about 20% faster.  meh.  PR 1962 is moar awesome.
