### ISSUE TITLE
A way to specify in the shell which front-end tests to run

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#1921]
It would be helpful to have a way to specify smaller groups of tests or individual tests to run via the command-line.

@lloyd suggests

```
FRONTEND_TEST_FILTER=foo npm test
```

which sounds good to me

**Comment by jedp** [comment]
@jbonacci I updated the testing docs in the PR:
https://github.com/mozilla/browserid/blob/6be79a2bf974456937133668d85396ddf82b72ee/docs/TESTING.md

I'll have to look to see what options I might be missing.  Is there anything specific you're thinking about?

cheers!
j

**Comment by lloyd** [comment]
merged to dev, basic testing works as I'd expect: 

```
$ FRONTEND_TEST_FILTER=confirm scripts/test_frontend 
Setting NODE_ENV to test_json to test with the local JSON database
To test with a local mysql database, setup mysql and set NODE_ENV to test_mysql
· · · ·  'waitFor()' finished in 200ms.
Tests completed in 75 milliseconds.
5 tests of 5 passed, 0 failed.
· · · ✓ OK » 7 honored (4.561s)
```
