### ISSUE TITLE
/signup page - inconsistent "Verify Password" v. "Repeat Password"

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1923]
On the signup page the label is 'Verify Password' and the placeholder is 'Repeat Password' . Shouldn't they be the same, or is this specifically intended to read this way. (Actually maybe just Password for the placeholder). If it's intended to be this way just close this issue. 

![img](https://img.skitch.com/20120705-c84an889kquc6bitgr4igim8k5.png)

**Comment by shane-tomlinson** [comment]
@jrgm - this affects the forgot password screen as well.

**Comment by jrgm** [comment]
yeah, I just realized /forgot had the same issue. r+ to both.

**Comment by jrgm** [comment]
verified train-2012.07.06 stage /signup and /forgot verify password matches
