### ISSUE TITLE
Can't cancel out of signup with primary idp in the dialog

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1933]
STR
1. Use dev.123done.org. If already authenticated, click This is not me...
2. In the dialog, enter <someemail>@eyedee.me and click Next
3. When the 'Sign in with eyedee.me' button is shown, click it
4. Now on the eyedee.me dialog, click 'Cancel' 

Expected: dialog screen goes back to the initial screen on login.dev.anosrep.org, asking for the email address. (NOTE: this is what production and stage do, and have done for months). 

Actual: https://eyedee.me/browserid/sign_in.html?email=... page is reloaded. The only way out for a user who has changed his mind is to close the dialog window.

**Comment by benadida** [comment]
yes, this is almost certainly same as #1934.

**Comment by jrgm** [comment]
works in dev for the original STR. Will and verify when we get to stage.

**Comment by jrgm** [comment]
closing and verifying for train-2012.07.30
