### ISSUE TITLE
Signup as primary via the dialog does not work.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1934]
In GH-1933, I noted that cancelling out of primary was broken. Then had a long meeting and came back. 

Primaries in dev don't work at all for signup. 

STR
1. Use dev.123done.org. If already authenticated, click This is not me...
2. In the dialog, enter @eyedee.me and click Next
3. When the 'Sign in with eyedee.me' button is shown, click it
4. Now on the eyedee.me dialog, enter a password and try to complete signup with the primary

Expected: calls to eyedee.me work and the dialog transitions and then dismisses and you are authed with the RP

Actual: page from eyedee.me in the dialog just reloads. 

Note: After you close the dialog go directly to eyedee.me and you'll see that you are logged in with eyedee.me. You can also
bring up the dialog from dev.123done.org and re-enter the eyedee.me email address you tried to use the first time, and this time you will wind up authenticated with the RP (without having to go to eyedee.me). 

Reproduced on Chrome and FF14 on osx. 

This issue, of course will block cutting the branch, five stars.

**Comment by lloyd** [comment]
on it, first thing in the morning.

**Comment by benadida** [comment]
I think this issue has to do with the fact that eyedee.me is including the include.js from the production site, and with the protocol change, that's incompatible when run from the dev site.

@lloyd do we need to set up dev.eyedee.me for this?

**Comment by lloyd** [comment]
eyedee.me was not properly retargeting the dev env for all resources hosted on browserid.org/persona.org - now fixed.

**Comment by jrgm** [comment]
works in dev for the original STR. Will need to reconfirm when we get to stage.

**Comment by jrgm** [comment]
verified in train-2012.07.30
