### ISSUE TITLE
add the RP back to the subject line of the "Confirm ..." email message

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1935]
I think there may another issue about changes to email copy, but I noticed this while I was switching between prod tests and current dev environment. 

![img](https://img.skitch.com/20120706-dnb556946twtnd6hwu5sw5s1fs.png)

This may be intentional, but we don't the show RP that is involved in the link that is contained in the actual body. Okay, maybe a nit pick, but I prefer the former where something about the RP is in the subject line (not that any subject line in email means that much, and I'm the test dork who has an inbox with nothing but persona emails but it just seems better to me to note the RP in subject line).

**Comment by lloyd** [comment]
I think this a great point.

@skinny97214 Isn't what the user cares about the site they're logging into, and not persona?  Shouldn't the site be the prominent in the subject?

seems like a regression to me.

**Comment by skinny97214** [comment]
What's the status of site names?

**Comment by shane-tomlinson** [comment]
@skinny97214, @lloyd - are we gonna take action on this?

**Comment by callahad** [comment]
@shane-tomlinson As per comments in #3286, Skinny wanted the new subject to be, for example, "Confirm email address for Mozilla Webmaker"

**Comment by jrgm** [comment]
I still think this is better UX to name the RP in the subject line. /cc @ryanfeeley

**Comment by ryanfeeley** [comment]
Agreed! The email is close in current state, but I'll start on some improvements tomorrow.

**Comment by lloyd** [comment]
I probably should just not type anything, but I really like the site name or domain being the first thing on the line.

site name available: "Mozilla Webmaker: Complete sign-in"

site name not available: "webmaker.mozilla.org: Complete sign-in"

just saying.  Whatever we do, let's get something about the site in the subject line.  1 line patch!

**Comment by ryanfeeley** [comment]
@lloyd I prefer your solution:  "Mozilla Webmaker: Complete sign-in" .

Other conventional subject lines:
- Confirm your Mozilla Webmaker email address!
- Please confirm your Mozilla Webmaker registration.
- Mozilla Webmaker - New Account Confirmation

Would it be disingenuous and spammy to change the from name to, for example, "Mozilla Webmaker"?

Here is a screenshot of a current message, images off, in my Gmail.

![screen shot 2013-07-12 at 3 41 20 pm](https://f.cloud.github.com/assets/68213/790634/4841da86-eb2c-11e2-8df9-ecb0a177f630.png)

Even without images loading, it is very heavily Persona branded, and does not mention Mozilla/Firefox.

The only challenging mental leap we need the users to make is that they are not just signing into a website, but adding an email into "Persona". We should use this email as an educational opportunity. Will start writing.

**Comment by callahad** [comment]
@ryanfeeley Keep in mind that with our identity bridges up and running, conservatively only ~30% of users will ever see an email like that.

**Comment by shane-tomlinson** [comment]
@callahad - this is true, but we still want those 30% not covered by BigTent to have an awesome experience.

Since we now have backgroundColor as an RP option, it would be fun to experiment with setting the background color of the email to the same, to help RP brand the emails as well.

**Comment by ryanfeeley** [comment]
I shared some smaller tweaks with Shane, and figured this was a good thread for them. Thoughts?

CURRENT
![screen shot 2013-07-16 at 10 27 41 am](https://f.cloud.github.com/assets/68213/806558/0ec22ebe-ee3d-11e2-8bba-6726e7aeb083.png)

PROPOSED
![improved-email 001-001](https://f.cloud.github.com/assets/68213/806544/d56e10c4-ee3c-11e2-835a-2ad607363420.png)
![improved-email 001-002](https://f.cloud.github.com/assets/68213/806546/d9ad61da-ee3c-11e2-9769-3d7dadf90054.png)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I'm digging these changes. Would it make sense to move the massive Persona logo down into the footer and just make it a small watermark like we did with the dialog?

For RP branding, I am thinking of two changes we might be able to make: transfer both the backgroundColor and possibly the siteLogo to the email? The siteLogo may take a lot of work on our part, I am not sure what is involved in embedding images in an email.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - how should the text email look?

**Comment by ryanfeeley** [comment]
The same as the HTML version, except no logo alternative and style the footer style as a signature.

Something like:

::: Mozilla Persona
::: Simplified sign-in by the non-profit behind Firefox
::: Learn more at http://persona.org/about

Thoughts?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I dig it.

**Comment by csuciu** [comment]
Currently the sign in email says: 'beta.123done.org: Complete sign-in'
and reset password email says: 'beta.123done.org: Complete Persona password reset'

Is it ok if  'Persona' is mentioned in the subject of the password reset email?

**Comment by jrgm** [comment]
@csuciu - good question. At least, it should be consistent. Can you open a new issue? Thanks.

**Comment by csuciu** [comment]
Issue #3790: The subjects of the confirmation emails are not consitent
