### ISSUE TITLE
failed to verify assertion (JSON parse error) with dev.123done.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1936]
I was going through a sequence where I have an account with one primary and two secondaries, and I say 'This is not me' and then re-auth with the primary and subsequently try to re-auth one of the secondaries. I got this repeatable error from dev.123done.org. 

![img](https://img.skitch.com/20120706-n5i8exs3wkk6a3wej86b5p74py.png)

I had httpfox running, and can see that the POST to  http://dev.123done.org/api/verify was sending 'assertion=...' with 'application/x-www-form-urlencoded; charset=UTF-8' and getting back response body of "Something went wrong.  Someone should fix it.". Heh ;-)

I'll work on a simple STR and will update.

**Comment by jrgm** [comment]
I should note GH-1934 where I had to workaround going back again to get my primary signup to work, so this may be an oddball error due to that.

**Comment by lloyd** [comment]
This should be high priority to fully understand.  Nice find @jrgm.  

We have community complaints that may have the same underlying cause.  /cc @benadida

--lloyd

**Comment by jrgm** [comment]
Ah, forget this. I can't reproduce and I see from IRC persona_deployer that a new build was pushed out at the same time. Invalid test conditions. Closing. 

(But would be interesting to someday set up an environment where I can choose to introduce random /verify errors that don't return valid JSON which is probably what this was. @lloyd are there any logs on eyedee.me that might show anything to correlate with the period from 20:08 to 20:18).

**Comment by jrgm** [comment]
And also I see that selenium tests against dev.123done.org also failed, then recovered in the same sorta time frame.

**Comment by jrgm** [comment]
Actually @lloyd I meant logs on dev.123done.org (not eyedee.me).
