### ISSUE TITLE
l10n issue - link to 'cookies disabled' message is hard-coded to en-US despite user language

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1938]
This is from https://bugzilla.mozilla.org/show_bug.cgi?id=770851

If you load https://browserid.org/cookies_disabled in any supported localization you see localized text, but the link is hard-coded to en-US. However, I don't see a simple solution to this issue, since there is no consistent way to map the SUMO 'cookies disabled' help URL for a given language choice.

![img](https://img.skitch.com/20120706-nsy57dm3x1witfyn13e3ntw55a.png)

**Comment by ibai** [comment]
What Shane said. If the link has no locale it will load the users locale if it exists and en-US if it doesn't.

**Comment by lloyd** [comment]
link looks good now on https://login.dev.anosrep.org/cookies_disabled

Confirmed if I change my language preferences (prefer spanish) the redirect behaves correctly.  closing.

**Comment by jrgm** [comment]
verified stage train-2012.07.20 I get French help for this when accept-languages: fr,en-US,en
