### ISSUE TITLE
silent and allowPersistent not works

### ISSUE THREAD

**Issue by iron9light** [mozilla/persona#1939]
- allowPersistent

The sign up dialog do not let me select whether I wanna keep as signed up. [Chrome 20.0.1132.47 beta, mint 11-64bit]
Firefox and my android phone can see the selection screen.
And it showed the selection screen only once on my chrome.
- silent

It always give me NULL.

**Comment by callahad** [comment]
Hi, we've deprecated persistent login with the current API in favor of making persistent login happen automatically with the new "Observer" API. We'll be announcing that the Observer API is stable in production early next week, and suggest that you switch to that should you need persistent sessions.

(You should switch to it regardless, though! It's great!)

You can find docs here: https://developer.mozilla.org/en/DOM/navigator.id

Thank you for the bug report, let me know if you need help understanding or porting your code to the new API; I'd be happy to take a look at it.

(Also, I apparently let some of the docs for persistent login slip through the cracks; I'll fix that now)

**Comment by callahad** [comment]
And for what it's worth, we're working on a formal deprecation notification strategy, and will be announcing a deprecation / change notices mailing list soon (check our blog on Tuesday evening). Our communication and docs haven't kept pace with our experiments on the current and new APIs. It's my responsibility to fix that, so if you spot something or wish we had communicated something differently, please file an issue or ping me.

**Comment by iron9light** [comment]
the new "Observer" API is much easier to use.
Good job.
