### ISSUE TITLE
When going to manage page, if user is not logged in, help them log in.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#194]

**Comment by shane-tomlinson** [comment]
@jbonacci your thinking runs along the same as mine with regards to this.  I am wondering how we go about doing this cleanly with the API/system we have in place now, as it is the "authenticate" part of BrowserID without the "choose an email" part.

**Comment by lloyd** [comment]
I think the cleanest user experience might be to just have a custom inline form that bounces off the authenticate wsapi, not even use the dialog.

**Comment by shane-tomlinson** [comment]
@jbonacci - we no longer have a distinct manage page, though we probably should.
