### ISSUE TITLE
Nine test failures on IE8 on dev and train-2012.06.22 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1957]
Nine test failures on IE8 on dev and train-2012.06.22

There are test failures on IE8 for these 9 tests. This is on both dev and train-2012.06.22, but not train-2012.06.08 (except the for 'expiration date must be within').
- this one is the issue with 'expiration date must be within 5 seconds of 2 minutes from now: 7109' which I thought we had an issue about in the past few weeks, but I can't find it.
  - http://10.250.2.124:10002/test/?filter=shared%2Fuser%3A%20getAssertion%20with%20known%20primary%20email%2C%20expired%20cert%2C%20user%20authenticated%20with%20IdP%20-%20expect%20assertion
- These all report 'Teardown failed on ...: Object doesn't support this action' due to `delete window.scriptToRun` in resources/static/test/cases/dialog/js/modules/rp_info.js
  - http://10.250.2.124:10002/test/?filter=controllers%2Frp_info%3A%20neither%20siteName%20nor%20logo%20specified%20-%20show%20rp_hostname%20only
  - http://10.250.2.124:10002/test/?filter=controllers%2Frp_info%3A%20siteName%20only%20specified%20-%20show%20specified%20siteName%20and%20rp_hostname
  - http://10.250.2.124:10002/test/?filter=controllers%2Frp_info%3A%20siteLogos%20are%20allowed
  - http://10.250.2.124:10002/test/?filter=controllers%2Frp_info%3A%20both%20siteName%20and%20siteLogo%20specified%20-%20show%20siteName%2C%20siteLogo%20and%20rp_hostname
  - http://10.250.2.124:10002/test/?filter=controllers%2Frp_info%3A%20privacyPolicy%2C%20termsOfService%20specified%20-%20show%20TOS%2FPP%20info
- These three are reporting 'script was not run', but when each is run separately they pass, so seems to be a problem with test isolation.
  - http://10.250.2.124:10002/test/?filter=controllers%2Fdialog%3A%20get%20with%20script%20containing%20termsOfService%20-%20print%20error%20screen
  - http://10.250.2.124:10002/test/?filter=controllers%2Fdialog%3A%20get%20with%20script%20containing%20privacyPolicy%20-%20print%20error%20screen
  - http://10.250.2.124:10002/test/?filter=controllers%2Fdialog%3A%20get%20with%20privacyPolicy%20-%20print%20error%20screen

**Comment by shane-tomlinson** [comment]
@jrgm - this is a dup of #1783, PR #1966 issued.  I asked @lloyd to have a look at the lone failing test for assertion expiration.

Closing as dup.
