### ISSUE TITLE
backend unit tests failing on tests/static_resources.js

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1958]
Travis says (and is right)

✓ OK » 1 honored (0.008s)
1892tests/stalled-mysql-test.js
1893······································· 
1894✓ OK » 39 honored (13.250s)
1895tests/static-resource-test.js
1896✗ 
1897
1898
1899  All resources expand
1900    ✗ We get stuff
1901      » expected 12,
1902    got  9 (==) // static-resource-test.js:35
1903✗ Broken » 1 broken (0.005s)
1904
1905npm ERR! browserid@0.0.1 test: `./scripts/test`

I think https://gist.github.com/3063839 is a fix (it's really a one-line, but I also reformatted the really long line).

**Comment by lloyd** [comment]
fixed in dev and train-2012.07.06 on browserid_private.  thanks for the find, and the fix.

**Comment by jrgm** [comment]
verified on the other repo train-2012.07.06
