### ISSUE TITLE
L10n bugs in train-2012.07.06

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1960]
### A) No need to escape ' with double backslash here:

resources/static/dialog/views/rp_info.ejs:22
`By proceeding, you agree to %s\\'s <a %s>Terms</a> and <a %s>Privacy Policy</a>.`

The same string is unescaped on many other occasions: resources/static/dialog/views/authenticate.ejs:61
resources/static/dialog/views/required_email.ejs:67, resources/static/dialog/views/set_password.ejs:74...
`By proceeding, you agree to %s's <a %s>Terms</a> and <a %s>Privacy Policy</a>.`
### B) %s should not be a localizable string

resources/static/dialog/views/set_password.ejs:22
%s
### C) Double space (should be single):

resources/static/dialog/views/confirm_email.ejs:12
`Click the link in the confirmation email.  You'll then immediately be signed in to %s.`

resources/views/dialog_layout.ejs:34
`<strong>Persona.</strong> Simplified sign-in, built by a non-profit. <a %s>Learn more&rarr;</a>`

lib/browserid/email_templates/reset.ejs:1
`Forgot your password for Persona? It happens to the best of us.`
### D) It's not always clear what does %s stand for

resources/static/dialog/views/verify_primary_user.ejs:14
`Once you verify your account there, you will be signed in to %s.`

If %s stands for Persona, some languages have to add another word in front of %s to make the sentence sound right. For example in Slovenian, "boste prijavljeni v Persona" is wrong as the correct form is "boste prijavljeni v Persono". That's why we need to add "storitev" (service) in front of %s.

Before we have comments implemented, I suggested we make a list of all string replacements with explanations what do they stand for. Or, we don't use %s for replacing Persona at all, but only for things we cannot hardcode (URLs, email addresses, etc.).

**Comment by kscanne** [comment]
It would be great to allow variables to be reordered with the gettext syntax %1$s, %2$s, ...  The possessive construction in "By proceeding, you agree to %s's <a %s>Terms</a> and <a %s>Privacy Policy</a>." in particular would require this for many languages.   Until reordering is available, I'd suggest rephrasing this message in a way that is more likely to preserve variable order in translation, e.g. "By proceeding, you declare to %s that you agree to their <a %s>Terms</a> and <a %s>Privacy Policy</a>."

**Comment by kscanne** [comment]
I see this string appearing in the interface:

#~ "Cuir isteach do sheoladh ríomhphoist chun logáil isteach i ozten.com" 

with the #~ and double quotes.  This is a translation of an obsolete string
in my PO file:

#~ msgid "Enter your email address to sign in to <strong>%s</strong>"
#~ msgstr ""
#~ "Cuir isteach do sheoladh ríomhphoist chun logáil isteach i <strong>%s</"
#~ "strong>"

**Comment by lloyd** [comment]
@kscanne / @mathjazz - with respect to changing the position of variables, how would you guys feel about a syntax that looks like...

"By proceeding, you agree to {site}'s &lt;a {termsHref}&gt;Terms&lt;/a&gt; and &lt;a {privacyHref}&gt;Privacy Policy&lt;/a&gt;"

This would allow re-ordering and is more legible than `%1$s` - thoughts?

**Comment by lloyd** [comment]
actually, ignore my comment.  I see ozten has already implemented named syntax that looks like `%(foo)`.  I will use that.

**Comment by adamkalis** [comment]
I just want to add that I see the same problem with kscanne, the one with #~

Thanks also about the solution with the variables, it helps a lot :)

**Comment by mathjazz** [comment]
@kscanne, thank you for your suggestion about reordering variables. Thanks to @lloyd it seems like we'll have more meaningful string replacements ready for the next train. We'd like to avoid breaking the string freeze since 12 locales already started working on the latest train.

@kscanne, I'll send your suggestion about translating "By proceeding, you agree to %s's Terms and Privacy Policy." as something like "By proceeding, you declare to %s that you agree to their Terms and Privacy Policy." to the mailinglist, because it might help many other locales. With this suggestion, there's no need to change the original string.

@kscanne & @adamkalis: The old string is probably appearing in the interface because the l10n preview is not yet updated. Let's wait for @ozten to do that.

**Comment by lloyd** [comment]
@ozten all you, can you get the preview env up and close this bug down?

**Comment by ozten** [comment]
@mathjazz - l10n preview is owned by ops now and automatically gets update with every push to stage.

What is the URL you are hitting?

/CC @gene1wood @fetep

**Comment by mathjazz** [comment]
@ozten Seems like http://ozten.com/random/browserid/bid_test.html# work fine now.

After the train was cut, old string were still showing up.

You can cloe the bug, @lloyd.

**Comment by ozten** [comment]
Fantastic! Thanks @mathjazz.
