### ISSUE TITLE
mobile/main site: "Take the tour or sign up" is ugly (left justified)

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1967]
The text and buttons are left justified when everything else is centered:

![Left Justified Text](https://img.skitch.com/20120709-dkamw5e8wx345qqqcnf2x7r3an.png)

**Comment by jrgm** [comment]
Verified stage train-2012.07.20 - content is centered in iphone/safari, ICS stock/chrome/ff, 2.2 stock/ff and on desktop when the width is narrowed.
