### ISSUE TITLE
enable debug 'locale' in our dev env

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1970]
One should always be able to verify correct string markup via our devenv via a simple process (like switching browser languages).

previously I had tried to enable this, but it requires the addition of software that is not available via yum (translate-tooklit) to be run  on the server at deployment time.

We should figure this out and fix the feature so our debug locale is a more useful tool.

**Comment by lloyd** [comment]
note, I don't think it's useful to enable locales in our dev env either, because translations only start after we freeze a train.  curious for thoughts on that one.

**Comment by shane-tomlinson** [comment]
I think at least having db-LB is very useful, right now I am trying to add gettext to the entire main site but am having a difficult time figuring out how to enable the debug locale.
