### ISSUE TITLE
Implement age-neutral verification

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#1976]
Age-neutral verification means to verify that the age of the user is above a certain threshold (13) in a way that doesn't influence the user to answer in any specific way. The industry standard is to ask the user for their date of birth and use that to determine their age.

We need to add this step before we save information on our servers for a user. That means that at the account creation step (where we ask the user to set a password) we would add this question.

**Comment by callahad** [comment]
So this would only be for users of our fallback IdP? Meaning we can't make claims as to the age of folks coming through native IdPs?

**Comment by vthunder** [comment]
Good question. I think we have a few options for those emails, broadly two categories: a) tell RPs whether age verification took place (passing through information from the IdP), or b) guarantee it (force IdPs to assert they did the verification).

**Comment by callahad** [comment]
Something to check with Jishnu on regarding the legal requirements / exposures for RPs. For instance, MockMyID could falsely assert that all of its users are Of Age. Does trusting that information expose the RPs to any liability, or can they pass the buck to the IdP? Is an IdP that does insufficient verification (intentionally or not) exposed to any liability should an RP rely on that data?

**Comment by skinny97214** [comment]
@lloyd Do you have a screenshot of your progress?

We're adding "What year were you born in" with a dropdown underneath the password field. We'll need to eliminate the second password confirm field to make room for it. 

Can we ajax in the month / day drop downs if the year makes them possibly under 13?

I'll need guidance on the error text that should show if they are under 13 from Jishnu.

**Comment by warner** [comment]
this was beta1-req, right? or beta2-req?

**Comment by lloyd** [comment]
beta2-req

**Comment by skinny97214** [comment]
Mocks of the flow: http://cl.ly/0P401R2Y3w3s

@benadida @vthunder Please review flows and copy. See note of page 9. If it passes first muster, I'll need to loop in Jishnu for the legal review.

**Comment by benadida** [comment]
I think this is only for sites that request the verification, right? If so, great.

I suspect the one problem may be the wording that "{site name} wants to verify birthdate" That might be not quite age-neutral in its wording. But otherwise looks great.

**Comment by skinny97214** [comment]
Yes, this is only for sites that request verification.

I hope we can give some reasoning. It's really strange to just as for your birthyear with no context. I'm happy to morph the copy as needed.

**Comment by benadida** [comment]
looks like we're targeting to have this ready to launch 10/10.
