### ISSUE TITLE
update browserid version in package.json

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1977]
Small thing, but meaningful to some folks, so it's probably time to bump browserid up from version 0.0.1 for the beta ;-)

**Comment by zaach** [comment]
I suggest 0.0.1+beta1 (which is still a valid semver).

**Comment by lloyd** [comment]
1.0.0b1 ?

**Comment by zaach** [comment]
+1, though semver  wants a dash for prereleases: 1.0.0-b1.

**Comment by lloyd** [comment]
+1 w/ dash

**Comment by jrgm** [comment]
verified in current dev branch. package.json says '"version": "1.0.0-b1"'
