### ISSUE TITLE
javascript error when checking address_info for unknown secondary 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1978]
STR
1. load beta.123done.org and click sign in with persona
2. Say 'this is not me' if already authed.
3. Enter a secondary email address that is not known to the stage databases -- e.g., gyeiwonbhkbadskiowo@gmail.com
4. Click enter

Expected: dialog checks email provider (address_info) and when secondary and unknown transitions to prompt for a password x2

Actual:

```
Timestamp: 7/10/12 5:30:46 PM
Error: can't convert undefined to object 
Source File: https://static.login.anosrep.org/v/9dcee586c8/production/en_US/dialog.js
Line: 4
```

The dialog is unusable after that. 

Network response to https://login.anosrep.org/wsapi/address_info?email=gyeiwonbhkbadskiowo%40gmail.com is 200 OK with content `{"type":"secondary","known":false}`.

Blocks release => 5-star

**Comment by jrgm** [comment]
I've repro'd this in stage several times with FF on osx and with Chrome Beta on ICS. 

Curiously, I can't reproduce this with a local test environment. Possibly a network latency related thing?

**Comment by jrgm** [comment]
Reproduced with chrome on osx against stage which has a more helpful error message:

```
Uncaught TypeError: Cannot set property 'new_account' of undefined 
```

**Comment by jrgm** [comment]
The only reference to 'new_account' in train-2012.07.06 on private branch are for the KPI in GH-1807. Linking bugs.

**Comment by lloyd** [comment]
Assigning to shane to delegate as needed.  I can take a look in the morning if useful, or just merge in his PR and update deploy ticket.

**Comment by jrgm** [comment]
Bah. Not thinking. Actually an existing user fails in a similar way; the 'checking with your email provider' visually completes and prompts for a password, but on submitting the correct password, in Chrome I get this error message:

```
Uncaught TypeError: Cannot set property 'email_type' of undefined 
```

I was running with an awsbox on the weekend of train-2012.07.06 from the public repo and this worked. I'm going to redeploy an awsbox from the other repo and see if there's some difference. I'll also compare the bits in the rpm to that repo. I dunno. This is weird.

**Comment by lloyd** [comment]
I think the difference here is that in the awsbox environment, as in dev, kpi stuff is prefed ON.

In staging, we've prefed it off.

That's my guess at the delta.

I think all you have to do to try to reproduce this on aws would be to make a commit to config/aws.json

change: "kpi_backend_sample_rate": 1.0,
to:     "kpi_backend_sample_rate": 0.0,

this is wild guessing on my part, but it's the only way I can explain the data at the moment.

**Comment by jrgm** [comment]
Yeah, fricking me duh! Yes, it replicates in dev with that.

**Comment by lloyd** [comment]
merged.  should be fixed as soon as we update stage.

**Comment by jrgm** [comment]
stage is better for the js exception GH-1978 and I can sign in an existing user, or signup a new user in the dialog.

**Comment by jrgm** [comment]
closing.

**Comment by jrgm** [comment]
verified stage train-2012.07.06
