### ISSUE TITLE
improve validation of origin params to API calls

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1981]
as @fmarier pointed out in issue #1979, we can do much better with our regex in validate.js - more tightly validating incoming origins.

Not extremely high priority, but why not?

for reference, http://blog.gnukai.com/2010/06/fqdn-regular-expression/

**Comment by lloyd** [comment]
@zaach - you want?

**Comment by zaach** [comment]
That's a wicked regex. I'm on it.

**Comment by fmarier** [comment]
One thing that I'll be doing soon is refactoring the code that extract the domain from an email address (GH-1994). Once I do that, I'll validate the extracted domain, just in case.

So I would suggest that we create a domain/hostname validation function that the origin type checking code could use to check the hostname part of the origin. Or perhaps we should create a new 'hostname' type instead?
