### ISSUE TITLE
IE8 does not support max-age in cookies, making the cookie check cookie a session cookie.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1982]
http://blogs.msdn.com/b/ieinternals/archive/2009/08/20/wininet-ie-cookie-internals-faq.aspx

**Comment by shane-tomlinson** [comment]
checkin b95b1d6 fixed this.  closing.

**Comment by jrgm** [comment]
marking verified but will keep an eye for any oddities with this.
