### ISSUE TITLE
Emphermeral deployments include a broken myfavoritebeer

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1984]
Ephemeral deployments still include $hostname.myfavoritebeer.org.

This example RP is broken, since it sources $hostname.hacksign.in/include.js

I spent a lot of time greping the VM image trying to understand what is going on, and then eventually wondered if we migrated to 123done...

We should fix myfavoritebeer or remove it completely form the deployment to avoid confusion.

**Comment by stephendonner** [comment]
+1

**Comment by jaredhirsch** [comment]
since myfavoritebeer is the reference site for the old navigator.id.get API, we should probably fix it, not abandon it.

@lloyd, I can steal this if you can provide support when I inevitably get stuck

**Comment by jrgm** [comment]
@6a68 -> https://github.com/lloyd/myfavoritebeer.org/blob/master/server/main.js#L92

**Comment by jaredhirsch** [comment]
@jrgm: thanks :-)

I managed to find it on my own: https://github.com/lloyd/myfavoritebeer.org/pull/57

**Comment by jrgm** [comment]
Noted in the lloyd/myfavoritebeer.org/pull/57 that since we don't have stage and rely on an ephemeral we can't test with myfavoritebeer.org as an RP.

**Comment by lloyd** [comment]
Will fix fri...

--lloyd

**Comment by shane-tomlinson** [comment]
This was fixed with https://github.com/lloyd/myfavoritebeer.org/pull/57. Closing as fixed.
