### ISSUE TITLE
proposal: Confirm link should come first in verification emails

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#1987]
@sintaxi popped into IRC and was asking about post-verification redirects. In the process, he shared this screenshot:

![Screenshot of our confirmation email, showing two links: one to the RP, one for address confirmation.](https://img.skitch.com/20120711-ede6exckeii5ucxcer3uraai1q.jpg)

Should we make the confirmation link the first link in the message? Is having the RP linked at the very top confusing, since it won't do anything?

**Comment by callahad** [comment]
This ordering won't be as bad for sites that supply a `siteName` if we implement #1887, but still, that screenshot kind of made it jump out at me.

**Comment by skinny97214** [comment]
HTML emails and copy are in process of being implemented. Closing for now. Reopen if the new text and design do not please.
