### ISSUE TITLE
Fix list styling on Identity Blog

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#1988]
Francois made an awesome post at http://identity.mozilla.com/post/26930312162/security-fix-in-persona-verifier-and-new-mailing-list

Too bad the text in list items is almost the same color as the page background. :(

**Comment by lloyd** [comment]
@vthunder can you empower @sawyerh to improve this?

**Comment by lloyd** [comment]
@benadida can you make sure @vthunder does this?

**Comment by callahad** [comment]
Hey! I can edit the CSS! @sawyerh, could you look at the blog and decide if the list items look okay? If so, go ahead and close this issue.

(The only change: text color style now cascades down to list items from the content body. It's `rgba(0,0,0,0.75)`. Previously, list items were explicitly being set to `rgba(0,0,0,0.25)`, which is crazy.

I also added 15px of `padding-left` to `ul` tags in posts so that the bullets didn't awkwardly stick out into the margin.

**Comment by sawyerh** [comment]
Looks good to me.
