### ISSUE TITLE
helpers.extend is dupe of _.extend

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#1989]
If `underscore` is always a hard requirement (it's even used inside the helpers.js), then there is no need to keep 2 versions of the same function, that does the same thing.

**Comment by shane-tomlinson** [comment]
@seanmonstar - agreed.  I added helpers.extend before we decided _ was a hard req.  Will issue a PR to remove this.

**Comment by jrgm** [comment]
code change. tests pass train-2012.07.20
