### ISSUE TITLE
Localizing login.persona.org

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1991]
We should make login.persona.org localizable. Right now it is half in English half in another language if you visit it with a browser that speaks some other language by default.

/cc @ozten @lloyd

**Comment by seanmonstar** [comment]
dupe of #1862

**Comment by shane-tomlinson** [comment]
closing as dupe.

**Comment by mathjazz** [comment]
Sorry, let's continue discussion under #1862.
