### ISSUE TITLE
Password length is limited to 80 characters

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#1992]
While 80 character passwords are pretty long already, we should avoid punishing people that go the extra mile and have even longer passphrases.

Unless there is another limitation I'm not aware of (or a good reason performance-wise), I suggest 255 characters as the new limit, so that it still fits in a regular VARCHAR field.

**Comment by jedp** [comment]
@fmarier I like the idea of increasing this limit.  

A password of any length will be transformed into 60 characters by bcrypt, so increasing the limit would not actually have any impact on the db schema.

The only consideration I can see is maximum POST data size.  

The longest password in the Yahoo breach (and how convenient that they stored them in plain text) was something like 261 characters I think.  If that's representative of someone going the extra mile, as you say, maybe we should be totally crazy and roughly double it and go to 500 chars?

**Comment by fmarier** [comment]
@jedp Good point, I hadn't thought about the hash algorithm bringing it down to a fixed length anyways.

Maybe @warner has something to say about a reasonable limit from a password-derivation or SRP point of view.

Other than that, I guess we need to pick a number we're happy with. I have no idea why I like 255 so much :)

**Comment by warner** [comment]
Yeah, what @jedp said. The only limit, if any, should be based upon how much inbound network bandwidth we're willing to spend on the POST data size, and how much memory we're willing to (briefly) spend until it gets hashed.

I'd make it 10kB: large enough to make it effectively infinite for all sensible purposes.

**Comment by fmarier** [comment]
Ok, so should we go with a limit of 512 characters like @jedp suggested? There's probably no point in using anything bigger.

**Comment by jedp** [comment]
@fmarier @warner - I have to say, I love the idea of a 10kB limit on passwords.  It makes statements like "Your password must be between 8 and 12 characters long" sound even more hilarious.  I would _love_ to write a line in our documentation that says "Your password must be no more than ten thousand characters long."

**Comment by fmarier** [comment]
I have to agree that it would be pretty cool to have such a statement in the docs!

However, I can see a few potential issues with very long passwords:
- what encoding are they in? (in the worst case, it could quadruple the size of the string in bytes)
- how easy is it to write tests to confirm that we can support the length we advertise?
- what else will be in the POST data along with the password? (a 10k password could push that over the POST limit)

I'm not proposing we research these questions btw :)

**Comment by jrgm** [comment]
@fmarier see GH-1631

**Comment by jrgm** [comment]
Closing this. If it's worth doing, then there should have been a PR sometime in the last year ;-)
