### ISSUE TITLE
Define what a BrowserID email is and use our own regexp to enforce them

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#1995]
After discussing how to validate email addresses properly, @warner and I came to the conclusion that we need to define what types of email addresses we support.

The full range of technically valid email addresses is too big and includes many characters that we would need to be careful about when crossing type boundaries. The alternative is to be more strict about what subset of valid email addresses we allow and recognize that:
1. an email address like "Francois< Marier@"@mozilla.com is unlikely to work in practice (MTAs and MUAs don't all support these)
2. an RP receiving a weird email like that from us would probably not accept it anyways

I propose this as a good starting point: http://www.regular-expressions.info/email.html

Users can file bugs if we reject any of their email addresses and we will look at adjusting our definition based on the evidence that's presented.

Note that this will mean that we will have our own regular expression for emails and will no longer use validator's isEmail() function.

**Comment by shane-tomlinson** [comment]
@fmarier - we used http://blog.gerv.net/2011/05/html5_email_address_regexp/ as a starting point for the current regexps.

**Comment by callahad** [comment]
Yeah, the HTML5 email definition is awesome. It make me so, so happy to read [this](http://www.whatwg.org/specs/web-apps/current-work/multipage/states-of-the-type-attribute.html#e-mail-state-%28type=email%29): "This requirement is a willful violation of RFC 5322, which defines a syntax for e-mail addresses that is simultaneously too strict (before the "@" character), too vague (after the "@" character), and too lax (allowing comments, whitespace characters, and quoted strings in manners unfamiliar to most users) to be of practical use here."

**Comment by fmarier** [comment]
Thanks @shane-tomlinson, that's a really good post!

**Comment by fmarier** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=880660

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
