### ISSUE TITLE
dev/staging: /cookies_disabled content collapsed on mobile

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1998]
STR

1) In Firefox mobile or Android Native browser, open: https://login.anosrep.org/cookies_disabled

![Screen Shot of collapsed content](https://img.skitch.com/20120712-1cy5gfswmkwryqdh3jcnp38bg2.png)

**Comment by shane-tomlinson** [comment]
The unsupported_dialog suffers from this problem as well.

**Comment by shane-tomlinson** [comment]
This got merged into dev with checkin 684b785a58b8e5328ee1f0652acff8fead2f048b.  It's still not pretty, but this is back to the state that prod was in.

**Comment by jrgm** [comment]
checked on ICS Chrome, stock, ff14-ff17, iOS5 safari, 2.2 stock ff14-ff15 and looks fine on all except nightly ff17 ICS which doesn't seem to layout the right size for any site I visit.
