### ISSUE TITLE
dev/staging: /unsupported_dialog not showing the firefox logo

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1999]
STR
1) open https://login.anosrep.org/unsupported_dialog

![Where's the logo?](https://img.skitch.com/20120712-71ehpu1wekrrdrfajsiesm133.png)

**Comment by lloyd** [comment]
merged to dev.  @jrgm / @jbonacci not interested in this fix for `train-2012.07.06` (which will probably be derailed anyway)

**Comment by jrgm** [comment]
verified stage train-2012.07.20 and it is cacheable.
