### ISSUE TITLE
Font issue on Chrome/Windows

### ISSUE THREAD

**Issue by anantn** [mozilla/persona#2003]
From https://twitter.com/codinghorror/status/223359973885878272

"dear Mozilla Persona team, are you aware your login page looks like this on Windows/Chrome? Just sayin'."

Screenshot at: https://p.twimg.com/AxmItnzCIAIIJ9K.png

**Comment by anantn** [comment]
It appears to be a font issue, but I haven't verified that that's what's causing the Sign In button to flow downwards.

**Comment by shane-tomlinson** [comment]
@lloyd - @seanmonstar's font fix REALLY needs merged in.

**Comment by csuciu** [comment]
The same issue can be seen on Opera12/Win7

**Comment by seanmonstar** [comment]
dupe of #1856
