### ISSUE TITLE
Slow response when typing in the email field on FF mobile

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2010]
OS: Android 2.3.4
Browser: Firefox release from play store
Device: Samsung Galaxy SII

Steps:
1. Go to beta.123done.org
2. Tap on 'Sign in with Persona' -> Sign in dialog opens
3. Start typing in the email field using Android VKB

Expected:
The typed characters should be displayed instantaneously - this happens on Android stock browser, Dolphin....etc

Actual:
It takes almost a sec for the typed character to be displayed in the email field

**Comment by jrgm** [comment]
Yes, I can see this with any of FF, Beta, Aurora, Nightly with prod, stage or dev. A good comparison is to enter the same character 10 times as fast as you can in the email field. Then enter an email address known to browserid to bring up the password field and enter a character 10 times there. In the former case you can feel the lag and not all 10 characters are entered. In the latter case, where we're not handling keyup, the typing is responsive and all the characters are entered. 

Stock browser doesn't have this sluggishness. 

This may be a defect in Fennec -> @shane-tomlinson /cc @seanmonstar

**Comment by seanmonstar** [comment]
It's because there is a keyup event listener on email. It seems to be
animating the start hint on ever keyup, which must be beating up
Fennec.

On Jul 12, 2012, at 12:22 PM, John Morrison
reply@reply.github.com
wrote:

**Comment by shane-tomlinson** [comment]
reference checkin eed58a9542f1ac06ffcfb223d07562a173d8697e

**Comment by jrgm** [comment]
yeah, much quicker on stage train-2012.07.20

**Comment by AaronMT** [comment]
ETA for this on production?

**Comment by seanmonstar** [comment]
Its in the current staged train, so should hit production within 2 weeks.
