### ISSUE TITLE
Can't get past 'Checking with your email provider' on iOS with UIWebView

### ISSUE THREAD

**Issue by st3fan** [mozilla/persona#2013]
The following is happening on https://login.anosrep.org/sign_in#NATIVE

On iOS 5.1 while running in a UIWebView, I can't get past the 'Checking with your email provider' phase of the login process.

Clicking Next or hitting Return has no effect.

Screenshot at https://moo.mx/grabs/87445949.png

**Comment by st3fan** [comment]
On https://dev.login.anosrep.org/sign_in#NATIVE the problem does not happen and I am taken to the next step of the login process.

**Comment by lloyd** [comment]
as long as this is working on dev, we're good.  stage was derailed and won't ship into production.
