### ISSUE TITLE
list_emails loop after BigTent auth

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2014]
Using mozilla/browserid on the bigtent_with_dev branch with the latest bigtent and certifier...

I get the following:
http://192.168.186.138:10002/wsapi/auth_with_assertion
inputs:assertion: "eyJhbGciOiJSUzI1NiJ9.ey...PdU4KJpUkcqvBWrGSw8ME5Q"
csrf: "cPe9xQHGGQF9da5ZuG7K1g=="
email: "austin.ok@gmail.com"
ephemeral: true
response: {"success":true,"userid":1}

http://192.168.186.138:10002/wsapi/list_emails
response: {"austin.ok@gmail.com":{"type":"primary"}}

http://192.168.186.138:10002/wsapi/have_email?email=austin.ok%40gmail.com
Response: {"email_known":true}

then the cycle repeats:
http://192.168.186.138:10002/wsapi/auth_with_assertion
response: {"success":true,"userid":1}

http://192.168.186.138:10002/wsapi/list_emails
response: {"austin.ok@gmail.com":{"type":"primary"}}

http://192.168.186.138:10002/wsapi/have_email?email=austin.ok%40gmail.com
Response: {"email_known":true}

I don't think this should block landing bigtent_with_dev branch, but wanted to make sure others are seeing this also...

/cc @shane-tomlinson @lloyd @callahad

**Comment by callahad** [comment]
We should test this again with the branch that landed...

**Comment by shane-tomlinson** [comment]
@callahad, @ozten - Is the Yahoo proxy IdP enabled on staging?

**Comment by ozten** [comment]
No, stage is not a healthy bigtent env.

@gene1wood is BrowserID stage configured to talk to a BigTent server for @yahoo.com addresses?

**Comment by shane-tomlinson** [comment]
@ozten - I am not seeing this on dev.123done.org, is this still a problem?

**Comment by ozten** [comment]
Yes, looks fixed on dev. Closing.
