### ISSUE TITLE
log bad verifier assertions

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#2016]
and probably statsd the fact that we're seeing bad assertions at verifier.

**Comment by zaach** [comment]
It looks like there are metrics being taken of successes and failures, but I can add reasons to the failures and a statsd counter.

**Comment by jrgm** [comment]
verified for stage train-2012.07.20 for core assertion failure (e.g., no certificates on assertion submitted). 

The other cases from PR-2151 will be in the next train.
