### ISSUE TITLE
Use npm-seal to verify dependencies in production

### ISSUE THREAD

**Issue by zaach** [mozilla/persona#2022]
We can use npm-seal until npm supports it and we switch to node 0.8.x

[![seal](https://github.com/zaach/npm-seal/raw/master/npm-seal.png)](https://github.com/zaach/npm-seal)

**Comment by jedp** [comment]
I love that little guy

**Comment by zaach** [comment]
@lloyd There's an issue with having  npm-shrinkwrap.json around during development: we use a different set of dependencies for production and development, but the same shrinkwrap in both. We _could_ list all of the dependencies in the shrinkwrap, but then they would be installed in production as well.

Another alternative would be to generate/move/copy the shrinkwrap files before deploying, and only check the seal in production, post-installation. Thoughts?

**Comment by lloyd** [comment]
@zcarter and I are hacking on a new magic npm proxy thing called lockdown.  So far it looks promising and seems like it might be a lower friction way to have confidence that what we develop on is what we actually deploy, and that everyone stays on the same dependencies for local dev, and we don't break doze.

stay tuned.

saying this is a beta2 req, but really would like to see this in beta1 :ok_hand:

**Comment by ozten** [comment]
This sound like Awesomesauce that hardens to form a magick shell!

**Comment by jrgm** [comment]
Closing this as npm-lockdown is now in the tree.
