### ISSUE TITLE
Uncaught exception in auth_with_assertion

### ISSUE THREAD

**Issue by ringe** [mozilla/persona#2027]
UPDATE: See first comment.

When I go to http://dev.myfavoritebeer.org/ to log in with my users mama@rin.no or mama@underpin.no I experience a timeout at the last step of the Persona process, after login is successful and the user is certififed.

The POST to https://login.dev.anosrep.org/wsapi/auth_with_assertion fails after 4 minutes, with no error message. See the [HAR dump](http://pastie.org/4248549) - use the [HAR viewer](http://www.softwareishard.com/blog/har-viewer/).

I am working on the [browserid-provider](/ringe/browserid-provider) Ruby gem, working with the development instance of Persona at http://login.dev.anosrep.org. I don't know if this is due to the formatting of my signed certificate, so bear with me, please.

My primary is running at underpin.no (a development server), which the rin.no domain has delegated authority to:

```
rin.no/.well-known/browserid content:
    {"authority":"underpin.no"}

underpin.no/.well-known/browserid content:
    {
      "public-key": { "algorithm": "RS","n":"223...2139","e":"65537"},
      "authentication":"/users/sign_in",
      "provisioning":"/browserid/provision"
    }
```

The document structure of the signed certificate is not very clear (and not mentioned in [the guide](https://developer.mozilla.org/en/BrowserID/Guide_to_Implementing_a_Persona_IdP)).

I believe it should be like this:

``` ruby
      cert_params = {
        "public-key" => params["pubkey"],
        "principal" => { "email" => "mama@rin.no" },
        "iss" => "rin.no",
        "iat" => Time.now,
        "exp" => expiration
      }
```

which is the idea I got from tracing the format through the following js functions:
https://github.com/mozilla/browserid-certifier/blob/master/bin/certifier#L51
https://github.com/mozilla/browserid-certifier/blob/master/lib/certify.js
https://github.com/mozilla/browserid-certifier/blob/master/lib/keysigner-compute.js
https://github.com/mozilla/jwcrypto/blob/master/lib/cert.js#L11
https://github.com/mozilla/jwcrypto/blob/master/lib/assertion.js#L30
https://github.com/mozilla/jwcrypto/blob/master/lib/jwcrypto.js#L86

As a side note: In April, I used the following certificate document with success:

``` ruby
      issue = {
        "hostname" => "rin.no",
        "exp" => expiration,
        "public-key" => params["pubkey"],
        "principal" => { "email" => "mama@rin.no" }
      }
```

But with this I get `{"success":false,"reason":"bad signature in chain"}`, see the [HAR dump](http://pastie.org/4248679).

**Comment by ringe** [comment]
I realize the issue I originally posted here is just an uncaught exception in browserid. As pointed out by @benadida over IRC on #identity - the timeout problem was caused by not parsing the params["pubkey"] to JSON before stringifying the cert_params.

``` ruby
cert_params = {
        "public-key" => JSON.parse(params["pubkey"]),
        "principal" => { "email" => "mama@rin.no" },
        "iss" => "rin.no",
        "iat" => Time.now,
        "exp" => expiration
      }
```

The issue with the timeout is solved by returning an error message if the format of the "public-key" value is wrong. Maybe even point out if it is a string instead of a JSON object?

**Comment by lloyd** [comment]
assigning to @benadida as he's auditing verification code...

**Comment by lloyd** [comment]
not a regression, decrementing to 4 stars

**Comment by jaredhirsch** [comment]
Seems like the fix here is to return an informative API error right away if the public-key parameter is malformed in the request. And figure out why it's taking so long to return.

**Comment by shane-tomlinson** [comment]
Is this still a problem?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
