### ISSUE TITLE
Email address is displayed as hint text in 'create password' field

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2028]
OS: Android 2.3.4
Browser: Android stock browser,  Dolphin
Device: Samsung Galaxy SII

Steps:
1. Go to beta.123done
2. Enter an email address and tap on Next
3. Tap in 'create password' field

Expected:
 'create password' hint text should be displayed until first character is entered 

Expected: 
The email address is displayed in 'create password' field as hint text.

**Comment by shane-tomlinson** [comment]
@csuciu - Thanks for submitting this issue.  We are relying on the browser's default behavior for the placeholder attribute.  The behavior you are seeing is due to the browser's implementation.

**Comment by shane-tomlinson** [comment]
@csuciu - oh, I see this now.  Interesting.  Digging deeper.

**Comment by shane-tomlinson** [comment]
Dup of #2242 which has a photo.  Closing this in favor of that.
