### ISSUE TITLE
Please use the HTML5 email input field

### ISSUE THREAD

**Issue by st3fan** [mozilla/persona#203]
The email field in the BrowserID popup is currently a plain text input field. Can this be changed to an HTML5 email field instead? That means that mobile devices will show the appropriate keyboard (for email address entry) and that they will also turn off autocorrect and auto-capitalization.

**Comment by shane-tomlinson** [comment]
st3fan - this should be taken care of already in dev, will check again.

**Comment by st3fan** [comment]
Oh awesome. I did not look at dev. Just production as of Aug/22.

**Comment by shane-tomlinson** [comment]
@st3fan - yup, just confirmed on dev.diresword.org, all good.  Closing this.

**Comment by lloyd** [comment]
for reference, you can find out what commit is running on a particular machine by requesting the ver.txt file from the top level:
- **production**: https://browserid.org/ver.txt
- **beta**: https://diresworb.org/ver.txt
- **dev**: https://dev.diresworb.org/ver.txt

**Comment by lloyd** [comment]
and more to the point, this change is on beta and should be entering production on thursday in the wee hours of the morning pacific time.

**Comment by st3fan** [comment]
I get the correct keyboard now but iOS still does the autocapitalization and autocorrect. I thought that those would be turned off automatically for an email field but that does not seem to be the case :-(

Is it possible to add autocapitalize="off" and autocorrect="off" to the field?

**Comment by shane-tomlinson** [comment]
@st3fan, dbfe3da9c0416d7ab7ff5b28882d44375cfdec1b adds autocapitalize="off" and autocorrect="off".  Expect this to make beta next week and prod the week after!
