### ISSUE TITLE
Can't sign in to bugzilla with BrowserID

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/persona#2036]
On https://bugzilla.mozilla.org/
Trying to click 'Log In', then click 'Sign In', I get the console error:
TypeError: navigator.id.getVerifiedEmail is not a function L434

**Comment by jrgm** [comment]
That may occur if the browser had a failure in loading https://login.persona.org/include.js

**Comment by lloyd** [comment]
@jrgm - was this just a cosmic ray?  can you reproduce this?

**Comment by jrgm** [comment]
It seems to have been a transient problem and not sure why it occurred. But please reopen if this happens again @nickdesaulniers
