### ISSUE TITLE
redirect www.persona.org to login.persona.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2038]
@benadida pointed this out. You can go to www.persona.org and login and use the main site.

**Comment by lloyd** [comment]
@gene1wood could this be another candidate for a change we push next wed?

**Comment by lloyd** [comment]
adding beta1 label, this will confuse a small portion of users and waste QA and dev time

**Comment by gene1wood** [comment]
yes, we can do this with the other zeus changes. i'll stage this today but it won't get pushed to prod until Monday 8/20 (not Wed 8/15)

**Comment by lloyd** [comment]
another required change: static.login.persona.org/ -> login.persona.org

too late to pile on?

**Comment by gene1wood** [comment]
@jrgm or @lloyd can you look through my test cases and correct them so I can get all the redirects correct :

https://bugzilla.mozilla.org/show_bug.cgi?id=781838#c4

**Comment by lloyd** [comment]
ping, status?

**Comment by ozten** [comment]
Removing Zeus config from stage per https://bugzilla.mozilla.org/show_bug.cgi?id=781838#c27

**Comment by jaredhirsch** [comment]
bump. @lloyd / @gene1wood thoughts on fixing this prior to Beta 2? Makes me a little squeamish to think about so much stuff changing at once.

Pre-emptively moving to Beta 3. If y'all wants it done sooner, move the milestone back to Beta 2.

**Comment by shane-tomlinson** [comment]
The list of sites provided by @jbonacci all redirect to https://login.persona.org. Closing.
