### ISSUE TITLE
support bcrypt work factor update

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#204]
on login, regenerate bcrypt when work factor has changed.

**Comment by lloyd** [comment]
ben, what's the update with the upstream request?

**Comment by benadida** [comment]
waiting on submitted bug: https://github.com/ncb000gt/node.bcrypt.js/issues/38

**Comment by benadida** [comment]
waiting on submitted bug: https://github.com/ncb000gt/node.bcrypt.js/issues/38

**Comment by lloyd** [comment]
pull request submitted: https://github.com/ncb000gt/node.bcrypt.js/pull/39

proposed approach if the pull request isn't pulled: http://irclog.gr/#show/irc.mozilla.org/identity/11348

**Comment by lloyd** [comment]
author pulled upstream, as soon as he bumps and re-publishes to npm we can bump version in package.json and move along with this.
