### ISSUE TITLE
stage and prod does not look up .well-known on rin.no or underpin.no

### ISSUE THREAD

**Issue by ringe** [mozilla/persona#2043]
When I try to log in to http://myfavoritebeer.org/ with mama@rin.no or mama@underpin.no I expect to see a query to ./well-known/browserid on the server for each domain. This request does not take place.

On the client side, I am asked to create a password in Persona instead of seeing my server's login form.

**Comment by jrgm** [comment]
So, I have no access to production but on stage (where I have limited privs) I can see that requests to rin.no or underpin.no sit in SYN_SENT. From an external-to-mozilla host, those connections work. /cc @gene1wood

**Comment by ringe** [comment]
@jrgm - that doesn't make sense to me, is there some firewall in stage and prod doing this?

Logging in to http://dev.myfavoritebeer.org/ does produce the request on rin.no and underpin.no, but logging in to http://beta.myfavoritebeer.org/ and http://myfavoritebeer.org/ does not.

Is there something I can/should do or look for on my side?  /cc @gene1wood

**Comment by shane-tomlinson** [comment]
@ringe - Is this still a problem?  Did you and @lloyd get this figured out?

**Comment by ringe** [comment]
@shane-tomlinson This is still a problem. No requests are being made to the provider, unless I'm logging in to dev.

**Comment by warner** [comment]
Adding to beta1-req in case this indicates a firewall problem that would prevent external primaries from working (and falling back to the secondary). I think we want that working by the beta.

**Comment by jaredhirsch** [comment]
@ringe still seeing this?

**Comment by jaredhirsch** [comment]
@ringe @lloyd ping again. Still happening?

If not, feel free to close.

If so, we can't get a fix in prior to Beta 2, so I'm bumping back to Beta 3.

**Comment by ringe** [comment]
@6a68 I'm sorry I haven't been able to look into this for a very long time. I'll try to get back to you soon.

**Comment by jaredhirsch** [comment]
@ringe no worries :-) we are aiming to tackle fewer big goals for Q2 so that we can fix long-standing bugs that are lower priority. any time you can get back to us is great.

**Comment by jrgm** [comment]
I don't see a problem using either stage or production for either email address above. Closing, but reopen if you have a different result.

**Comment by ringe** [comment]
@jrgm That's because my .well-known/browserid is down. Now if you try to use either address you get to create a Persona account, which is not what it would be if the BrowserID protocol was in place and performing as it should.

Just give me some time, like @6a68 said. I'll get my provider up and going again, then see if it works.
