### ISSUE TITLE
Can't sign in in production - email case sensitivity

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2049]
OS: Win7
Browser: FF 13.01
                 Chrome 20.0.1132

Steps:
1. Go to mozillians.org, bugzilla.mozilla.org or developer.mozilla.org
2. Press on 'Sign In' with Persona
3. Enter an email address, press 'Next', enter the password then press 'Sign In' 

Expected:
User should be signed in with the new email

Actual:
Nothing happens.

**Comment by shane-tomlinson** [comment]
@csuciu - Thanks for the bug report.  I am not having a problem in any of these three sites in Win7.  Can you possibly attach a screencast/screenshots of what you are seeing, with dev tools open if possible?

**Comment by csuciu** [comment]
I got this error in the console when pressing on Sign in: 
Timestamp: 7/16/2012 12:40:03 PM
Error: [Exception... "'PopupNotifications_show: invalid browser' when calling method: [nsILoginManagerPrompter::promptToSavePassword]"  nsresult: "0x8057001e (NS_ERROR_XPC_JS_THREW_STRING)"  location: "JS frame :: resource:///components/nsLoginManager.js :: <TOP_LEVEL> :: line 971"  data: no]
Source File: resource:///components/nsLoginManager.js
Line: 971

and here is the screencast: http://www.screencast.com/t/v0ubDfWHWTc

**Comment by shane-tomlinson** [comment]
@csuciu - Thanks for the screencast, it is helpful.  If you disable all of your addons, do you still see the problem?

**Comment by csuciu** [comment]
Yes, I'm still seeing this with all addons disable

**Comment by csuciu** [comment]
Turns out that you cannot sign in if you have an account created with uppercases (e.g TEST@example.com) and you try to sign in with the same account but using lowercases (test@example.com).  
This is the issue in my case..

**Comment by callahad** [comment]
This looks like a continuation of the issue in #1350. We need to take a stance on this.

**Comment by seanmonstar** [comment]
With the influx of people trying it on at Beta launch, it seems likely we would have more instances of this case. beta1-req? I'd at least for what stance we want to take.

**Comment by lloyd** [comment]
@callahad @vthunder if you want this to get fixed by b1, please provide concrete guidance on approach

**Comment by jaredhirsch** [comment]
fixed by #3078
