### ISSUE TITLE
write up a wiki page about why we are using node.js

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#205]
given that mozilla is heavily a django shop, and we deliberated the node.js vs. django question for a while, it would be useful to put down our reasons for taking a step off the beaten path on a wiki page.

**Comment by ozten** [comment]
Created https://wiki.mozilla.org/Identity/BrowserID/ServerImplementation

**Comment by ozten** [comment]
This seems documented well enough, marking closed.
