### ISSUE TITLE
Persona website has problem with font

### ISSUE THREAD

**Issue by JasnaPaka** [mozilla/persona#2054]
Persona has problem with font. For czech (cs) some chars are not rendered correctly.
- https://login.persona.org/

**Comment by shane-tomlinson** [comment]
@JasnaPaka - thanks for filing this issue.  This is a dup of #1973 and #1856.  The fix for this is in the pipeline and should be applied within the next week.

**Comment by seanmonstar** [comment]
I'm curious if the new fonts render czech characters better. If so, then it might have been worth the increased size.

If you can, we have the new fonts staged at http://login.anosrep.org
