### ISSUE TITLE
Link to Mozilla Support from mainpage contains "en-US"

### ISSUE THREAD

**Issue by JasnaPaka** [mozilla/persona#2055]
On the main page (https://login.persona.org/) there is a link to https://support.mozilla.com/en-US/kb/what-browserid-and-how-does-it-work. This is bad because link contains "en-US" in URL. Please remove "en-US". This article is translated to many languages. Thanks.

**Comment by shane-tomlinson** [comment]
@JasnaPaka - Thanks for filing this issue!  PR #2056 fixes this.  It should be reviewed and merged this week and should make its way to prod in a couple weeks.

**Comment by jrgm** [comment]
verified stage train-2012.07.20 I get the correct language for help from sumo with en or fr
