### ISSUE TITLE
don't select any email address in the picker for a new site

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2059]
if we have no data regarding which email address a user has used for a specific site that they are logging into, we should not have anything selected by default.

```
15:46 < skinny> lloyd we shouldn't be selecting anything by default
15:46 < skinny> lloyd unless they only have one email
15:47 < skinny> lloyd anything else is yak shaving
```

**Comment by jrgm** [comment]
verified train-2012.08.17 on https://train0817.personatest.org and https://train0817.123done.org, and a little fiddling with localStorage. WIll check when I get back the other sites working with ephemeral.
