### ISSUE TITLE
update documentation for keys sent (https://wiki.mozilla.org/Privacy/Reviews/KPI_Backend#Data_Storage_Component) 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2062]
The set of keys on the kpi payload differs from the doc:

```
Change of name: 
    -language
    +lang
    -number_sites_logged_in
    +sites_signed_in
Keys not listed:
    +orphaned
    +sites_visited
Keys listed but not sent:
    -user_agent
```

Also update https://wiki.mozilla.org/Identity/BrowserID/KPI_Dashboard#Data_Glossary

**Comment by nmalkin** [comment]
This may be helpful:
https://etherpad.mozilla.org/kpi-dashboard-privacy-review-update-1-num-sites-logged-in

**Comment by shane-tomlinson** [comment]
I added these fields to the wiki. Closing.
