### ISSUE TITLE
"Remember You" button text overflows on desktop when resized to mobile device size

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2066]
STR
1) On a desktop browser, open the dialog to the email picker for an account that is older than one minute.
2) Open debug menu, select "force is this your computer"
3) Select an email and click next.
4) Resize dialog so that it is mobile size.

![Button Text Overflow](https://img.skitch.com/20120717-mug2xfnndki2y5fwag8w3s1au3.png)

**Comment by jrgm** [comment]
Reopening. I don't see this fixed for train-2012.08.17 on https://train0817.personatest.org/

osx/chrome 21.0.1180.79

![img](https://img.skitch.com/20120824-t3f6w2twxeej88in6n8u87inp5.png)

osx/ff 14.01                                     

![img](https://img.skitch.com/20120824-8dxqkqfbrbxhb6bwh93jfsasu4.png)                                                                 

I do see the change in resources/static/production/en_US/dialog.js on https://train0817.personatest.org/, but no joy.
