### ISSUE TITLE
All static resources should be gzipped and served with proper cache headers

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#207]
We should make sure that all static resources are served from node.js with proper cache headers, and that nginx on beta/dev/prod is configured to compress and cache these resources according to cache headers without a restart.

Part of provisioning new code needs to be invalidating nginx's cache.

**Comment by benadida** [comment]
this also requires cache-busting, as per Shane's comments during bug-triage.

**Comment by lloyd** [comment]
yeah, we need cache busting.  We should open that up a separate issue.  how about #226

**Comment by lloyd** [comment]
As per Richard Soderberg, compression will be handled in the load balancers.  There is no longer anything to do for this bug.
