### ISSUE TITLE
Allow `siteName` and `siteLogo` options in `navigator.id.get()`

### ISSUE THREAD

**Issue by naholyr** [mozilla/persona#2070]
We use `navigator.id.get()` on our website, why doesn't it have the same options as `navigator.id.request()` for customization ?

**Comment by naholyr** [comment]
Before you tell us to use `navigator.id.request()`, here is the situation :)

Our configuration is quite simple:
- A unique "/login" page with the login button
- A "log out" button on every page once logged in

We use `navigator.id.get()` because we just need an entrypoint to check user's identity, and then we only rely on website's session mechanism.

`navigator.id.request()` relies on `navigator.id.watch()`, which has several flaws (and is very far from being sideeffects-free…):
- It means our logout button has to trigger `navigator.id.logout()`, or user will never been disconnected, which means we have to include `browserid.js` on every single page of the website.
- it also means we have to provide the `loggedInUser` option to `watch()`, or every page will trigger the `onlogin` event. This can lead to some WTF behaviors… That implies we cannot include this code in a static JS that could be cached and minified. We have to generate some JS dynamically.

The cost becomes a bit high for a name and a logo.

**Comment by thom4parisot** [comment]
I think it works, it's just not documented ;-)

**Comment by callahad** [comment]
Hi @naholyr, we're focusing all of our new development on the Observer API, and don't have any plans to add further features to the previous API.

**Comment by callahad** [comment]
@lloyd and I are working on a blog post formally introducing the Observer API and explaining why it's worth the labor of switching. I promise there are good, non-obvious reasons! We'll try to get that online on Thursday, or, failing that, Monday.

**Comment by callahad** [comment]
Closing this issue for now. look for a blog post on http://identity.mozilla.com Monday.
Issue #2086 is tracking the problem with `.request` options getting processed when coming from `.get`.

Thanks!

**Comment by callahad** [comment]
Doh, by "on Monday" I mean "on Wednesday". On Monday, Shane is scheduled to blog about post-verification redirects.
