### ISSUE TITLE
english means english

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2076]
When I set my browser settings to prefer english first `en`, then a different language, we serve up the different language rather than `en-US`.

I would think that it would be more optimal to serve en-US in this scenario.

**Comment by seanmonstar** [comment]
dupe of #1863

**Comment by shane-tomlinson** [comment]
+1.  Is this apply universally?  Would a user from Mexico who has their Spanish set to es be alright if they were served up es-AR if we had that translation but not normal es?

**Comment by ozten** [comment]
There are unit tests to match the base part of a language code.

There are also comments around potential political issues around doing this too broadly.
