### ISSUE TITLE
allow a well-known file to let an IdP be only supported in staging, not prod

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#2077]
Make it easier for an IdP to stand up code without immediately deploying as a public IdP.

The well-known file could include a new field:

```
 "mode": "staging"
```

that would, in the case of production Persona, act like it's a 404 well-known.

**Comment by benadida** [comment]
@ozten correctly points out that this won't work well when you're pushing a new rev and already have an IdP in production. Maybe we should have alternate well-known paths:

```
 .well-known/browserid-stage


 .well-known/browserid-dev
```

**Comment by callahad** [comment]
That also becomes kind of weird, though, because you can't test your in-development IdP against stable Persona...

**Comment by ozten** [comment]
/.well-known/browserid-dev is a place where we can fix some of these issues:
- https://github.com/mozilla/vinz-clortho/blob/master/docs/PRIMARY_PAINPOINTS.md
- https://developer.mozilla.org/en/BrowserID/Primary/Developer_tips

**Comment by lloyd** [comment]
I think there are other approaches to get the same affect and we can "redesign the solution to solve multiple problems simultaneously".

I think we should solve this in a minimal fashion, as there are other cases where an IdP wants to know what persona environment is contacting it.

The most minimal thing I can think of is a new HTTP header:

  `X-Persona-Server: login.dev.anosrep.org`

**Comment by lloyd** [comment]
stale.
