### ISSUE TITLE
/signin - redirect to primary "verify" button does not match normal button style

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2082]
STR

1) Go to main site's /signin page
2) Enter a primary address that must be verified with the primary
3) Look at the ugly verify button

![Janky Verify Button](https://img.skitch.com/20120718-xhmbehxswn194wtkxxie5687sn.png)

**Comment by jrgm** [comment]
verified on train-2012.08.17 although now of course the UI for that page has changed quite a bit.
