### ISSUE TITLE
main site confirm screen - password field not automatically focused

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2087]
STR

1) In Browser A, open dialog to email picker
2) In Browser A, add a new secondary email
3) In Browser B, make sure user is logged out.
4) In Browser B, open verification email
5) In Browser B, password field should be focused.

**Comment by seanmonstar** [comment]
It's worth stating that this requires a browser that doesnt support `<input autofocus/>`, such as IE.

**Comment by jrgm** [comment]
verified train-2012.08.17 - works everywhere but ie8 (on winxp), which I punted out to GH-2395
