### ISSUE TITLE
error when verifying email addition in second browser

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2088]
STR

1) In Browser A - Create an account with a primary
2) Open dialog to email picker, click "Add Email"
3) Add the first secondary address, set password, hit enter.
4) in Browser B - Open confirmation page, enter password.
5) Go back to Browser A.
6) Watch error screen appear.

![error message](https://img.skitch.com/20120718-ri9hu76c2hxqabr2s1ph6w3qty.png)

**Comment by shane-tomlinson** [comment]
@lloyd - I brought this up while you were still here in London and remembered it again today as I was testing.  This scenario requires two browsers.  

When /wsapi/email_addition_status returns a status of "complete", Browser A's authentication level _should_ be set to "password"  Yet, when /wsapi/cert_key happens, it thinks Browser A is either no longer authenticated or authenticated to the wrong level.

**Comment by lloyd** [comment]
confirmed that pull request #2135 fixes this issue.

**Comment by jrgm** [comment]
For the initial STR in this issue, I went through this with desktop opera, safari, chrome, FF14, IE9/winxp, IE8/winxp, safari/ios5, stock/ics, chrome/ics, ff14/ics, stock-webkit/2.3.4, ff14/2.3.4 and they all have no error, the dialog dismisses and the user is logged in. Verified train-2012.07.30 and current dev for a few too. 

One oddity noted in GH-2242 (wtf? on that one).

**Comment by jrgm** [comment]
I should note that for IE8 there's a bug in adding a primary atm GH-2239. But you can work around that to get the primary added by trying to do it a second time, which is how I confirmed the IE8 case.
