### ISSUE TITLE
Train-2012.07.20 l10n issues

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#2093]
## BrowserID -> Persona
- /resources/static/pages/js/manage_account.js: 3 strings
  - `Remove %(email) from your BrowserID?`
  - `Removing the last address will cancel your BrowserID account.\n Are you sure you want to continue?`
  - `Are you sure you want to cancel your BrowserID account?`
## To much markup -> string replacement

Instead of `<a href="http://example.com" target="_blank">Link!</a>` and such, use `<a %s>Link!</a>`.
- /resources/views/about.ejs
  - `Sites such as <a href=\"http://crossword.thetimes.co.uk/\" target=\"_blank\">The Times Crossword</a>, <a href=\"http://current.openphoto.me/\" target=\"_blank\">OpenPhoto</a> and <a href=\"https://www.voo.st/\" target=\"_blank\">Voost</a> use Persona instead of usernames to sign you in.`
- /resources/views/forgot.ejs
  - `Check your email at <strong id=\"sentToEmail\"></strong>.`
- /resources/views/signup.ejs
  - `Check your email at <strong id=\"sentToEmail\"></strong>.`
  - `To verify that you own <strong id=\"primary_email\">address</strong>, you must sign in with your provider.  A new window will be opened.`
  - `<strong id=\"registeredEmail\"></strong> is already registered. Would you like to <a class=\"action\" href=\"/signin\">sign in</a> instead?`
- /resources/views/index.ejs
  - `New to Mozilla Persona? <a href=\"/about\">Learn more</a>`
  - `You may, at any time, <a href=\"#\" id=\"cancelAccount\" class=\"action\">cancel your account</a>`
- /resources/views/signin.ejs
  - `<strong id=\"unknown_email\">Email</strong> is not registered. Would you like to <a class=\"action\" href=\"/signup\">sign up</a> instead?`
  - `To verify that you own <strong id=\"primary_email\">address</strong>, you must sign in with your provider.  A new window will be opened.`
- /resources/views/unsupported_dialog.ejs
  - `Persona works with <a href=\"http://getfirefox.com\" target=\"_blank\" title=\"Get Firefox\">Firefox</a>`
  - `and other <a href=\"http://whatbrowser.org\" target=\"_blank\">modern browsers.</a>`
## Empty tag

Something must be missing inside the `<strong>` tag.
- /resources/views/signup.ejs
  - `<strong id=\"registeredEmail\"></strong> is already registered. Would you like to <a class=\"action\" href=\"/signin\">sign in</a> instead?`

**Comment by lloyd** [comment]
for the empty tags, we'll dynamically insert an email address.  fixing everything else.

**Comment by mathjazz** [comment]
Yes, you can close this one.
