### ISSUE TITLE
login.persona.org/verify can be used as a verifier

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2097]
We want people to use `verifier.login.persona.org/verify` as the URL for our verifier service. One of the reasons for the separate sub-domain is to be able to move that service to a separate server/IP later.

However, it is currently possible to use `login.persona.org/verify` to verify assertions. The fact that this works now means that RPs might start using it and will see their verifications fail later when `verifier.login` moves to a different IP address.

I suggest that we make `login.persona.org/verify` **fail** (i.e. no redirect) now so that RPs are forced to move to the right URL.

**Comment by lloyd** [comment]
+1.  also, is /verify as a path really meaningful?  or should post to https://verifier.login.persona.org work?

**Comment by fmarier** [comment]
+1 to @lloyd 's suggestion to drop `/verify` from the URL (though we need to be careful about any future redirections we make from `browserid.org/verify`)

**Comment by callahad** [comment]
People are starting to use `login.persona.org/verify`. Cf., http://www.julia.buchner.fr/mozilla-persona-en-bref/

Oops.

**Comment by fmarier** [comment]
I originally found out just in time to prevent this patch from getting merged into Mahara: https://reviews.mahara.org/#/c/1416/1/htdocs/auth/browserid/login.php,unified

**Comment by fmarier** [comment]
The Wordpress plugin [was also updated with the wrong URL](http://wordpress.org/support/topic/plugin-mozilla-persona-verification-failed-after-upgrade-of-the-browserid-plugin?replies=9).  

So how about fixing this in two parts:
1. hotfix which returns `{"status": "failed", "error": "Wrong URL for the verifier. Please ask the site administrator to use verifier.login.persona.org."}` whenever someone uses `login.persona.org/verify`
2. dropping `/verify` from the URL and redirecting from `verifier.login.persona.org/verify` to `verify.login.persona.org/`

RPs are not broken right now (despite using the wrong URL) so this would normally not be a good candidate for a hotfix. However, as soon as we fix this in production, a bunch of them will be broken. Even once the upstream Wordpress plugin is fixed, anybody using the old version will have problems. So the sooner we do that first point, the better it is.

So should we bump the priority on this and hotfix?

**Comment by lloyd** [comment]
given stats: https://bugzilla.mozilla.org/780776

I suggests we block this sooner rather than later.  next week.

@benadida thoughts?  Can we deploy a zeus change next week or not? /cc @gene1wood

**Comment by fmarier** [comment]
As per discussion with @lloyd, a warning has been sent to persona-notices: https://mail.mozilla.org/pipermail/persona-notices/2012/000002.html

**Comment by lloyd** [comment]
to be disabled wed. of next week - 8/15

@fmarier and @lloyd will send out additional announcements on monday with the specific change window once provided by @gene1wood

**Comment by lloyd** [comment]
we have a plan, this will get addressed, reducing to 4 stars.

**Comment by gene1wood** [comment]
I'll develop and stage this change tomorrow 8/10 and plan to deploy on Monday 8/20

**Comment by gene1wood** [comment]
I've made the changes in stage but I'm not sure I have the test cases correct, @lloyd can you validate them? : https://bugzilla.mozilla.org/show_bug.cgi?id=781838#c4

**Comment by gene1wood** [comment]
There is a lot of conversation in this ticket so I'm going to summarize what I've come to understand as the actionable request(s) from this conversation :
- POSTs to https://verifier.login.persona.org/verify should be passed to the verifier
- POSTs to https://login.persona.org/verify should return a 405 with a json message of "{"status": "failure", "error": "Wrong URL for the verifier. Please ask the site administrator to use verifier.login.persona.org."}"

Here are the actionable requests I'm _not_ going to act on with reasons :
- POSTs to https://verifier.login.persona.org/verify should redirect to https://verify.login.persona.org/
  - I'm assuming "verify.login.persona.org" was a typo of "verifier.login.persona.org"
- POSTs to https://login.persona.org/verify should return a 405 with a json message of "{"status": "failed", "error": "Wrong URL for the verifier. Please ask the site administrator to use verifier.login.persona.org."}"
  - I'm assuming that '"status": "failed"' is a typo of '"status": "failure"'
- POSTs to https://verifier.login.persona.org/verify should redirect to https://verifier.login.persona.org/
  - Redirecting POSTs is complicated ( http://www.alanflavell.org.uk/www/post-redirect.html ) and I want to make sure this is what we want to do before implementing

**Comment by gene1wood** [comment]
One additional element to consider is that RFC 2616 requires that when serving a 405 you provide an "Allow" header indicating what methods are allowed (since 405 indicates "Method Not Allowed")

**Comment by lloyd** [comment]
target is 9/6ish ?

**Comment by lloyd** [comment]
this has lagged so long that now it may be the case that a significant number of people are using it.  We should still try to reduce the number of urls that can be used for verification, but let's re-assess the # of affected RPs before that.

**Comment by callahad** [comment]
This has been live for a long time, and it's a _really_ easy mistake to make, given that the simple upgrade is `s/browserid.org/login.persona.org/`, which would leave users hitting `login.persona.org/verify`.

Which is bad news. This change would break things. It made sense to kill it a month ago, right after the new URLs went live, but now that it's lingered?

**Comment by gene1wood** [comment]
I'm holding and waiting to hear from @fmarier in regards to what test cases are missing, and what existing failing test cases need to pass.

https://bugzilla.mozilla.org/show_bug.cgi?id=781838#c19

@fmarier : What's your ETA to have the answers to those questions?

**Comment by fmarier** [comment]
@gene1wood I'll be reviewing this on Monday.

**Comment by lloyd** [comment]
ping?  what's the plan?

**Comment by ozten** [comment]
Removing Zeus config from stage per https://bugzilla.mozilla.org/show_bug.cgi?id=781838#c27

**Comment by lloyd** [comment]
let's get a change window set up to get this done.  @fmarier can you take point?

**Comment by fmarier** [comment]
Found another library that uses the wrong URL: https://github.com/Falco20019/php-browseridlib/pull/3

**Comment by jaredhirsch** [comment]
A bit late to handle this before beta 2 goes out the door. Bumping to beta 3.

**Comment by jaredhirsch** [comment]
moved to [identity-ops](https://github.com/mozilla/identity-ops/issues/113), closing.
