### ISSUE TITLE
Dialog email field not recognized as such in Opera Mobile

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2098]
On Opera Mobile for Android (both on tablet and phone), the email field that the dialog shows, when it asks you for your email the first time, is not recognized as an email field. The on-screen keyboard that pops up lacks the @ sign on the first screen for example, and on a Samsung device, the convenient ".com" button is also missing.

This was tested on dev.myfavoritebeer.org

**Comment by shane-tomlinson** [comment]
When testing with Opera Mobile 14 on my Android device, I see the @ sign, we are an email address!  Closing.
