### ISSUE TITLE
Confirming a new email while already logged in doesn't log you in with new identity

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2099]
Steps:
1. create a new Persona account with a secondary email, click confirmation link
2. log out of myfavoritebeer
3. add a new secondary emai
4. click confirmation email

Expected:

The email is confirmed and you get redirected to the RP where you are automatically logged in.

Actual:

The email is confirmed and you get redirected, but once on the RP page (myfavoritebeer), you're still not logged in. 

(Tested on dev.myfavoritebeer.org and Opera Mobile on an Android tablet.)

**Comment by lloyd** [comment]
this is not expected to work on myfavoritebeer, but should on 123done, please try to repro there.

**Comment by fmarier** [comment]
It does work on 123done.org, so this is not a bug. Sorry.
