### ISSUE TITLE
RP link in plain text emails is easily confused with confirmation link

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2100]
I got confused a few times by this while testing on a tablet.

In the confirmation email, there are two URLs: the RP URL and the confirmation link. Since the email is in plain text, both are converted to clickable links by your email client. They are also very close to each other and so it looks like a giant blue clickable area.

If you're not paying attention, it's easy to click on the wrong link. On a touch screen, it's even worst because you have to tap with your finger and so even if you know that there are two links, you can easily hit the wrong one.

The worst thing about this is that ultimately, the two links take you to the same place, but only one of them will confirm your email address first.

Screenshot: https://www.dropbox.com/s/ll50zijvbyhqnx4/Screenshot_2012-07-20-15-31-52.png

**Comment by nmalkin** [comment]
See #1987 for some discussion of the same issue

**Comment by fmarier** [comment]
While the new HTML emails will make this better, not everybody enables HTML emails, so we should improve the plain text version too.

**Comment by warner** [comment]
I'm also not completely convinced that having sites set an RP name will help a lot.. a lot of sites have brand names that end with ".com", so their RPname will basically look just as much like a URL as the confirmation link.

OTOH, the real problem, if I understand it correctly, is the email client being overenthusiastic about linkifying anything that looks like a domain name (I assume our HTML emails aren't going to put an `<a>` on the RP name), and there's not much we can do about that. I could imagine a text/plain email in which the RP name shows up buried at the end, but the copy would read pretty strangely: "click here to sign into something. LINK. This is for signing into (RPname)".

**Comment by lloyd** [comment]
how about a couple newlines?

**Comment by fmarier** [comment]
@lloyd I think a couple of new lines is all we need here. It would put a blank line between the RP url and the confirmation link.

**Comment by csuciu** [comment]
I still see this issue in the confirmation emails sent to yahoo mail on tablets

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
