### ISSUE TITLE
Password reset page: should the landing page redirect somewhere?

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2101]
Once you have successfully reset your password, you end up on a login.persona.org that tells you that you have done that successfully.

There is no indication of what to do next (i.e. going back to where you were when you found out you had to reset your password).

**Comment by lloyd** [comment]
what are the concrete STR here?

**Comment by skinny97214** [comment]
If there is an RP, it should redirect to the RP. If there isn't, it can go to the account management page.

**Comment by fmarier** [comment]
1. Clear all cookies
2. Go to `dev.myfavoritebeer.org`
3. Login using an existing secondary email
4. Click the "Forgot your password" link and type in new password
5. Click the link received via email

At that point, you end up on a page that just says "Your address has been verified".

**Comment by shane-tomlinson** [comment]
@fmarier - myfavoritebeer.org uses the old API.  Only RPs which use the new API will be redirected - please see PR #2109.  Logically this makes sense as sites that use the old .get API cannot be logged in after redirect.

@lloyd, @skinny97214 - thoughts?

**Comment by skinny97214** [comment]
@fmarier  It should redirect to the manage page.

**Comment by shane-tomlinson** [comment]
Fixed with #2424, closing.

**Comment by jrgm** [comment]
verified for train-2012.10.12 for an myfavoritebeer; redirects to management page.
