### ISSUE TITLE
Active input field on "Check your email" + emacs bindings + Ctrl+W in FF = weirdness

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#2112]
If you add a new secondary email, when the flow moves on to the "Check your email" panel, the (now invisible) email input is still the activeElement in the dom.

At this point, if you hit Ctrl-W, you think you will close the popup.  But in fact you probably get the emacs binding for "delete word left", because you're in editor context.

Delete word left makes firefox to want to give you suggestions for your text input, even though it's hidden, and so it causes a pop-down list of all the emails you've entered in that field to appear.  The list weirdly hovers in space where the email input used to be.

If you click outside and take the focus away from the input, Ctrl-W closes the tab.

Although I make use of emacs hotkeys (I believe everybody does by default?), it didn't even dawn on me that I could use emacs ctrl-w in a firefox input field.  I certainly wouldn't ever have tried, because I _would_ anticipate the tab to close.  But I see on the FF wiki that emacs ctrl-w is supported while you're in editor context...  (Danger, Will Robinson...)

The result as far as Persona is concerned is that a FF user who wanted to close the popup with ctrl-w will get some really weird behavior.

I'd say the fix would be to remove focus from the text input on submit.

(tested in current 14 and 15.0a2 (aurora))

**Comment by seanmonstar** [comment]
So the action is to blur the email field when it gets hidden.

On Thursday, July 19, 2012, Jed Parsons wrote:

> If you add a new secondary email, when the flow moves on to the "Check
> your email" panel, the (now invisible) email input is still the
> activeElement in the dom.
> 
> At this point, if you hit Ctrl-W, you think you will close the popup.  But
> in fact you probably get the emacs binding for "delete word left", because
> you're in editor context.
> 
> Delete word left makes firefox to want to give you suggestions for your
> text input, even though it's hidden, and so it causes a pop-down list of
> all the emails you've entered in that field to appear.  The list weirdly
> hovers in space where the email input used to be.
> 
> If you click outside and take the focus away from the input, Ctrl-W closes
> the tab.
> 
> Although I make use of emacs hotkeys (I believe everybody does by
> default?), it didn't even dawn on me that I could use emacs ctrl-w in a
> firefox input field.  I certainly wouldn't ever have tried, because I
> _would_ anticipate the tab to close.  But I see on the FF wiki that emacs
> ctrl-w is supported while you're in editor context...  (Danger, Will
> Robinson...)
> 
> The result as far as Persona is concerned is that a FF user who wanted to
> close the popup with ctrl-w will get some really weird behavior.
> 
> I'd say the fix would be to remove focus from the text input on submit.
> 
> (tested in current 14 and 15.0a2 (aurora))
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/browserid/issues/2112

## 

Sean McArthur
http://seanmonstar.com

**Comment by jedp** [comment]
Quite so.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
