### ISSUE TITLE
"Passwords don't match" field obscures first password box

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#2113]
Similar to #2106

If you create a new password, and your first and second entries don't match, the warning tooltip pops up over the first password.

This feels uncomfortable, because of course I don't know which field I made my typo in, so I immediately want to click on the first password to re-type it, and then type the second one again afterwards, but the tooltip is in my way

I think it would be better if the tooltip appeared above the first password input.

**Comment by skinny97214** [comment]
Moving to one password field. See GH-1702
