### ISSUE TITLE
"Create Account" page superfluous in sign up flow from Sign In link

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#2114]
On persona.org, there are two starting points and three routes to creating a new account: 
1. Click the "Sign up" link at the bottom of the screen -> goes right to Create Account page
2. Click the "Sign in" link at the top (where I'm used to signing up for new accounts) -> goes to Sign In page

Even though the Sign Up button is huge and blue, I don't notice it when I'm scanning the page.  Starting at the top, I think I see what I'm looking for in "Sign In" and click it right away. I assume many people react the same way, and I'd love to see KPI data for this.

So when I click "Sign In", the flow is:
1. Sign In page says Enter Email Address.  I do that.
2. I now have a choice: I can click "New to Persona? Sign up today." or I can click "Sign In".
   1.  "New to persona" takes me to the Create Account page
   2.  "Sign In" takes me to "Sign In" again, now with "foo@bar.com is not registered.  Would you like to sign up?"
      - I click "sign up" and it takes me to the Create Account page

In either case, Create Account page then prompts me for my email again.  I don't understand why this is necessary.   Sure, the email is autofilled for me, but why doesn't it just start verifying?

It seems to me like it would be smoother if, arriving at account creation via the "Sign In" link, once you had entered an email address and confirmed that you wanted to sign up, it would go straight to verification.

**Comment by skinny97214** [comment]
I want to kill this flow entirely. Let's not spend a lot of time making it better.

**Comment by shane-tomlinson** [comment]
Made much nicer with PR #2161. Closing.
