### ISSUE TITLE
Email address autopopulated for "Sign Up" and "Sign In" (safari)

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#2117]
On Safari, the email fields in "Sign Up" and "Sign In" are autopopulated with my last email used.

STR:
1. Sign Up (I used a secondary email, fwiw)
2. Verify and go to your Dashboard
3. Delete your account
4. Choose either "Sign Up" or "Sign In"

The Email field will be autopopulated with the email you used before.  

I've only seen this in Safari so far.  
Chrome on OSX populates with the "Your Email" hint
Firefox also works as expected

**Comment by shane-tomlinson** [comment]
@jedp - I have just tried this on the current dev and am unable to reproduce.  Can you check against the current dev and see if this is still reproducible?

**Comment by lloyd** [comment]
fwiw, I cannot reproduce on safari osx mountain lion against current dev.
