### ISSUE TITLE
main site - forgot password flow winds up showing /signin page

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2118]
STR
1. Go to https://login.dev.anosrep.org and click Sign in.
2. Enter a known secondary email address and the 'Sign in' button to show the password field.
3. Click 'Forgot your password?'
4. Enter the password twice and click 'Reset Password'

Expected: page transitions to show text that an email link has been sent. Email is sent out.

Actual: page briefly shows that text but then redirects itself to /signin page. Email, though, is sent OK.

Reproduced in FF and Chrome on osx

**Comment by jrgm** [comment]
Note: this does not happen on train-2012.07.06 or production. Gonna mark it 5-star.

**Comment by lloyd** [comment]
r+

**Comment by lloyd** [comment]
verified fixed on dev.

**Comment by jrgm** [comment]
verified fixed on stage train-2012.07.20. Page transitions to show Forgot Password Confirm your email address... and the email is sent and received.
