### ISSUE TITLE
determine default bcrypt work factor

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#212]
we should figure out what we want the bcrypt work factor to be by default given cost.  is it 12?

**Comment by benadida** [comment]
12 appears to be the consensus from the security team. I'll make the commit now.

**Comment by lloyd** [comment]
it's 12 and moved to libs/configuration.js.  closing this issue.

**Comment by benadida** [comment]
dude, I wanted to add the update bcrypt factor thing first. y u grab my issues? :)

**Comment by lloyd** [comment]
Oh, that's over in issue #204  

When I opened this one I meant it to be for figuring out what the work factor should be.  feel free to bump #204 to four stars?

And I steal your issues just to see if you're awake!

**Comment by benadida** [comment]
ok, cool on #204. I don't think it's 4-stars as per your definition, so I guess I'll leave it as is for now.

I'm awake, mostly :)

**Comment by lloyd** [comment]
if you _were_ to label it four stars I'd prolly go and hack a patch into upstream.  But I agree 4 stars is a bit of a stretch.
