### ISSUE TITLE
Sign In with unknown email results in lame Sign In button

### ISSUE THREAD

**Issue by warner** [mozilla/persona#2120]
environment: both staging (login.anosrep.org) and dev (login.dev.anosrep.org). Both Chrome 21 and FF 17.0a1 (nightly).

STR:
- navigate to login.anosrep.org (or login.dev.anosrep.org)
- click "Sign In"
- enter a new non-primary email address
- get "ADDR is not registered. Would you like to `sign up` instead?" dialog. Note that the largest button on the screen is still the blue "Sign In" button on the bottom right.
- ignore suggestions and click "Sign In"
- nothing happens
- click again
- nothing happens

I'd prefer to see a new non-primary email address redirect me to the Sign Up page, so I can click on the largest button on the screen and get the most useful action. Failing that, I'd prefer that the non-functional Sign In button be disabled, leaving me to follow one of the two smaller links to the Sign Up page.

**Comment by jrgm** [comment]
GH-1579 discusses the same STR and notes that the similar situation applies for the /signup page. I'm going to close GH-1579 (since finding anything old in GH is a hassle).

**Comment by jrgm** [comment]
verified train-2012.08.17. The UI has been changed such that there is no separate signup and the button is always active (checking for inputs of course).
