### ISSUE TITLE
Forgot Password dialog has confusing field names

### ISSUE THREAD

**Issue by warner** [mozilla/persona#2122]
(both dev and staging)

STR:
- navigate to login.dev.anosrep.org or login.anosrep.org
- create account with secondary email address, with password
- logout
- navigate back, start Sign In with email address
- hit "Forgot Password" link instead of providing the password
- the resulting dialog says "Forgot Password" in large letters, has three fields "Email Address", "Password", "Verify Password", and a button labeled "Reset Password"

I think the "Forgot Password" label should be "Reset Password", since this dialog is about what I'm about to do, not what I've already done (which I already feel stupid about, no need to rub it in). The Email Address field is editable, which seems pretty weird, I expect it to be immutable. The "Password" field should be labeled "New Password", otherwise it feels like I'm being asked _again_ for the password that I've already admitted that I can't remember.

The "Reset Password" button could probably be labeled "Send Confirmation Email" or "Send Password-Reset Email", since that's what will actually happen when you push it (the password won't really be reset until much later, when you follow the email link). With the current label, it looks like it will reset the password right away, without confirmation or email, which (combined with the editable email field) makes it sure seem like you could just reset _anybody_'s password to anything you want from this page.

**Comment by nmalkin** [comment]
See #2023, which is tracking the same issue.

@shane-tomlinson's PR #2085 implements this

> I think the "Forgot Password" label should be "Reset Password"

and this

> The "Password" field should be labeled "New Password"

(specifically, the new copy is _Create a new password to use with Persona_)
but not this

> The "Reset Password" button could probably be labeled "Send Confirmation Email" or "Send Password-Reset Email"

**Comment by shane-tomlinson** [comment]
@warner - Thanks for the updates, @nmalkin is correct - #2023 is the original tracker for this.  Since that already has a PR associated with it, I'm going to close this as a dup.
