### ISSUE TITLE
Cancel Account alert mentions BrowserID, not Persona

### ISSUE THREAD

**Issue by warner** [mozilla/persona#2123]
- Navigate to login.anosrep.org
- create an account, login
- hit the "cancel your account" button
- the alert() that appears says "Are you sure you want to cancel your BrowserID account?", but everything else on the site says "Persona"

Note: this is only on login.anosrep.org right now.. login.dev.anosrep.org correctly says "Persona". So it's likely that this bug can be ignored, and when dev finally makes it to staging and then production, the problem will be resolved. But I found it odd that everything else in staging seems to have been rebranded, just not this one alert() box.

**Comment by jrgm** [comment]
Yeah, @jep noted this earlier today in GH-2105 but since it's fixed in dev, closed it out. Wanna close this one too?

**Comment by jedp** [comment]
I saw that, too. I checked the code and it's fixed in dev, i think.  Lemme double-check when I get home from dinner.

---

Typed with my thumb

**Comment by jedp** [comment]
So now I'm home I see @jrgm has already checked for me.  That man has eagle eyes, I tell you.

**Comment by shane-tomlinson** [comment]
Closing as already fixed in #2075
