### ISSUE TITLE
"Remember You?" dialog has squished padding on Chrome

### ISSUE THREAD

**Issue by warner** [mozilla/persona#2124]
conditions: Chrome 21, both dev and staging
- create an account, log in to a site, log out, log back in again
- the popup asks "Remember You?", with a blue "One Month" button and a red "This session only" button
- the text to the right of the buttons is jammed up against the buttons, instead of being 10-15 pixels away

![screenshot](https://raw.github.com/gist/3148277/969948f7ff18d471a5a77e08139cfbf6f413ff0e/ddt-image-20120719-staging-chrome-1.png)

**Comment by jrgm** [comment]
This was noted in GH-1932 and should be fixed on dev with GH-1940

**Comment by jrgm** [comment]
Hmm, this is what it looks like in dev for ff14/osx and similar on chrome 20 on osx

![img](https://img.skitch.com/20120720-qhn9jfwwg69fjgmkgrtxgb7b7q.png)

Is this just chrome 21?

**Comment by shane-tomlinson** [comment]
@warner - you are showing a screen shot against staging, this has been fixed in dev with #1940.  Here is my screen shot from dev on Chrome 21 Beta for OSX:

![Chrome Beta Remember You?](https://img.skitch.com/20120720-1ff57hd5u36j86htsqtabwe3ci.png)

Closing as already fixed.
