### ISSUE TITLE
Update MDN documentation with post-rebrand URLs

### ISSUE THREAD

**Issue by nmalkin** [mozilla/persona#2125]
Our documentation on MDN hasn't been updated to reflect the new `*.persona.org` URLs. Pages for [quick setup](https://developer.mozilla.org/en/BrowserID/Quick_Setup), [Remote Verification API](https://developer.mozilla.org/en/BrowserID/Remote_Verification_API), and others still refer to `browserid.org`.

The documentation wasn't updated because the MDN wiki was stuck in read-only mode due to the software migration. This is still true of the main site:

> As we prepare to switch to our new wiki platform, we have disabled editing of the wiki for the time being.

However, the [beta site](https://developer-new.mozilla.org/en-US/docs/BrowserID) now allows edits:

> Please keep in mind your changes are not going to be reflected on the standard developer.mozilla.org site until the Kuma wiki launches, but they will be preserved.

I wanted to bring this up, because if we make the edits now, the changes will go live as early as possible (given the circumstances), when the migration is finally made.

**Comment by nmalkin** [comment]
@callahad, let me know if I can help; if, for example, it would be helpful to have a list of pages that still need to be updated.

**Comment by jrgm** [comment]
verified on train-2012.08.17 for the new links. Not gonna read through every line of the docs ;-)

But I will note that https://developer.mozilla.org/en-US/docs/Persona/Quick_Setup says at the top "This article needs technical review". Huh?
