### ISSUE TITLE
'checking with email provider' permanently shown when cancelling out of forgot password screen 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2132]
STR
1. Go to an RP and click sign in.
2. Enter a secondary email address that is known to Persona (checking with email provider flashes and you are prompted for password).
3. Click 'Forgot your password?'
4. User now remembers their password and clicks 'cancel' to go back.

Expected: screen should now show the pre-filled email address and a password field.

Actual: email is prefilled, but no password prompt is shown. Instead the 'checking with your email provider' shows and will never go away.

**Comment by jrgm** [comment]
yep, looks go on current dev.

**Comment by jrgm** [comment]
Although, note this is not on train-2012.07.30

**Comment by seanmonstar** [comment]
It sounded like the current dev will become beta1, and it will be cut to stage this Friday. Right @lloyd?

**Comment by jrgm** [comment]
verified on train-2012.08.17 (e.g., http://train0817.123done.org/ and https://train0817.personatest.org).
