### ISSUE TITLE
Sign in button hidden when using lots of emails

### ISSUE THREAD

**Issue by graingert** [mozilla/persona#2137]
On https://login.persona.org/sign_in the sign in button is hidden.

<img src="http://i.imgur.com/GETJG.png" />

arguably div.submit.add.cf should be a direct child of div.contents not div#selectEmail

**Comment by shane-tomlinson** [comment]
@graingert - this is by design.  With TOS & Privacy Policy information showing in Germanic languages, if we show the signin button where you show it, only slightly more than one email address is shown.

**Comment by shane-tomlinson** [comment]
Dup of #1325 which has a PR we are actively reviewing.  Closing.  Thanks @graingert!
