### ISSUE TITLE
move to socketlabs for email delivery

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#214]
We'll be sending 4 emails/second at 1M active users scale.  We should pick a vendor (probably socket labs) and start using them for email delivery.

**Comment by thinkingserious** [comment]
Hello Lloyd,

Have you considered SendGrid? We can handle your frequency and volume for your email delivery needs.

Feel free to contact me directly at elmer.thomas@sendgrid.com for further details.

With Best Regards,

Elmer Thomas
Developer Evangelist
www.SendGrid.com

**Comment by lloyd** [comment]
Yo @thinkingserious - I defer to others for vendor selection, but I'll mention the existence of your company to those who make such decisions.  Thanks for dropping by.

**Comment by thinkingserious** [comment]
Thanks @lloyd! I appreciate that.

**Comment by lloyd** [comment]
pushing this issue to four stars.  we need to fix email delivery.

**Comment by lloyd** [comment]
discussion here with @ozten about how to get this ball rolling:
http://irclog.gr/#show/irc.mozilla.org/identity/11564

**Comment by ozten** [comment]
Yep. I don't have any 'must read' tech docs, it's just SMTP. Supporting all the inputs for your mail library via config should do. For Django that is EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD and EMAIL_USE_TLS.

**Comment by lloyd** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=694073

**Comment by lloyd** [comment]
5d0d422252a6221c17622f169a4fb267161fb0c2 adds required code changes.

**Comment by lloyd** [comment]
fixed!  beta and dev are now on socketlabs for delivery.  prod is already configured with params in the env, when we push out train 2011.10.13 the code will look for and use these env vars.

documented on mana: https://mana.mozilla.org/wiki/display/websites/browserid.org
