### ISSUE TITLE
lots of emails causes signin button to be hidden

### ISSUE THREAD

**Issue by lookfirst** [mozilla/persona#2144]
it is pretty unclear at this point how to sign in...

http://www.evernote.com/shard/s178/sh/8dc33dc9-9511-457c-a3bd-9d0f8ea22bdd/7763c7108791687ac853f8ab88c75c15

maybe instead of having a signin button at the bottom of a hidden scrollbar, each email address becomes clickable. this would also save a step of having to select an email and then click sign in.

**Comment by shane-tomlinson** [comment]
This is a dup of #1325 which we are actively trying to sort out.  Thanks for the feedback @lookfirst!
