### ISSUE TITLE
Observer API's onlogin leads to an expensive backend call on each page load?

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2145]
Hopefully this is just me not using the Observer API properly, but if you look at the [`onlogin` code in Libravatar](https://gitorious.org/~fmarier/libravatar/fmariers-libravatar/blobs/6ad94aa3d38282c284684a65d0b390256cff3d07/static/js/libravatar.js#line75),  you will see that any `onlogin` call with a valid assertion will cause this:
1. the JS front-end does a [POST to the backend](https://gitorious.org/~fmarier/libravatar/fmariers-libravatar/blobs/6ad94aa3d38282c284684a65d0b390256cff3d07/static/js/libravatar.js#line77)
2. the backend then [receives this request](https://gitorious.org/~fmarier/libravatar/fmariers-libravatar/blobs/6ad94aa3d38282c284684a65d0b390256cff3d07/libravatar/account/views.py#line748) and does a [POST to the Persona verifier](https://gitorious.org/~fmarier/libravatar/fmariers-libravatar/blobs/6ad94aa3d38282c284684a65d0b390256cff3d07/libravatar/account/browserid_auth.py#line55)
3. the front-end then does [nothing unless the logged in user has changed](https://gitorious.org/~fmarier/libravatar/fmariers-libravatar/blobs/6ad94aa3d38282c284684a65d0b390256cff3d07/static/js/libravatar.js#line79)

Now, I can see a way to eliminate all of this: the JS front-end could [parse the assertion and extract the email](https://github.com/fmarier/browserid-tools/blob/master/unpack-assertion.py) out of it. However, I'm not sure we want to recommend that people do that.

Is there a better way to handle this?

**Comment by callahad** [comment]
How does passing `loggedInEmail` impact this? That should avoid the `onlogin` call altogether, right? Is there a reason you'd rather not use `loggedInEmail`?

**Comment by fmarier** [comment]
@callahad I'm using [loggedInUser](https://gitorious.org/libravatar/libravatar/blobs/master/static/js/libravatar.js#line95) maybe that's the problem.

So if I use `loggedInEmail` then neither `onlogin` nor `onlogout` will fire when the right user is logged in?

**Comment by callahad** [comment]
@fmarier Correct! Unfortunately, `loggedInUser` got delayed and hasn't entered production yet. Even worse, I can't update MDN to note the slip. It will go live with our next production push.

**Comment by fmarier** [comment]
As usual, @callahad was right :)

Replacing `loggedInUser` with `loggedInEmail` does prevent the unnecessary `onlogin` calls.

I'll close this bug, but we should make a mental note (if there isn't one already) to make sure that this is well documented.
