### ISSUE TITLE
runErrorDialog when Adding additional email address

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#215]
Steps to Reproduce
1) Login to BrowserId.org
2) Attempt to login to RP
3) In dialog, click 'Add a new email address'
4) enter address and click 'Add Email'

Actual:
"We're adding this email to your account, this should only take a couple seconds."
JS Error console says
Error: runErrorDialog is not defined
Source File: https://browserid.org/dialog/production.js
Line: 7

Expected:
Confirmation of new email address

**Comment by shane-tomlinson** [comment]
@ozten - this should be fixed in beta, can you confirm?  You can use beta.myfavoritebeer.com as a beta RP, you will have to create a new account on beta if you do not already have one - the databases between prod and beta are kept separate so that we can test these separately.

**Comment by ozten** [comment]
This eventually worked.

A second email confirmation was sent. I clicked the link to 
https://diresworb.org/prove?token=OkPXh6EVb5yU...Ohok1DnfFcqdT
(I added ...)
I got the error message:
Error encountered while attempting to confirm your address. please try again. (error message: unknown)

I hit Back, re-added the email, the UI was wierd and then it got the original confirmation, green flash and back to list of email with my new one there. Sorry I don't have a screencast to attach.

**Comment by ozten** [comment]
3rd addresss - config link in email opened in new page, "address confirmed" page changed to My Account.

Pop still says "We're adding this email to your account, this should only take a couple of seconds.".

Hitting refresh on dialog, it closes itself.

Going back to beta.mybeer I see all three addresses.

**Comment by shane-tomlinson** [comment]
For the "Error encountered while attempting to confirm your address. please try again. (error message: unknown)" bug, I am moving this to issue #218

**Comment by shane-tomlinson** [comment]
To reproduce the being stuck at "We're adding this email to your account..." error:

1) start with an already existing account
2) add an email address
3) without closing the browserid dialog, verify the email address
4) when it shows the list of addresses, add a second email address.
5) watch it fail

**Comment by shane-tomlinson** [comment]
Just to be clear, this bug only shows whenever you attempt to add two email addresses within the lifespan of a single dialog.  It _is_ possible to add an email address to BrowserID.
