### ISSUE TITLE
completeAuthentication should accept a limitedToRPs param

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2155]
To support the BlueVia IdP, `navigator.id.completeAuthentication` will take a dictionary of parameters.

A new one we need is `limitedToRPs` which is a list of base URLs.

Example:

```
navigator.id.completeAuthentication({
    “id”: <identifier>,
    “limitedToRPs”: [“https://pay.bluevia.com”, “https://marketplace.mozilla.org”]
});
```

Note: This is an implementation detail and should not make it into the BrowserID Spec.

**Comment by shane-tomlinson** [comment]
@ozten - the note:

```
Note: This is an implementation detail and should not make it into the BrowserID Spec.
```

I think we should open this up to broader discussion.  I had a chat yesterday with a web site operator yesterday who was interested in becoming an IdP, but they only want their email addresses to appear for a particular whitelist set of sites.

I can write more on this in an email.

**Comment by ozten** [comment]
Mailing list - great idea, thanks for doing that.

Spec change - I think we should be conservative with what goes in the spec. We can build and advertise experimental features, then measure uptake... before putting it into the spec, especially for items that don't seem essential.

Making email a hint and allows an IdP to indicated a different email seem like philosophical changes which should go into the spec early, to indicate this more widely.

**Comment by jaredhirsch** [comment]
BlueVia is gone, closing down. Please reopen if this feature is still useful/needed.

**Comment by ozten** [comment]
R.I.P.
