### ISSUE TITLE
"Need help?" page needs to be refreshed for new name

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2159]
The SUMO page we link to should be updated to use the new name and the screenshots should be replaced.

  https://support.mozilla.org/en-US/kb/what-browserid-and-how-does-it-work

Given that we link to this page from `login.persona.org`, it would be good to get this done before the beta is released.

This other page also needs to be updated:

  https://support.mozilla.org/en-US/kb/how-do-i-manage-my-browserid-account

**Comment by callahad** [comment]
I'll take this. One question: Do we want to get our own category in SUMO for Persona? Right now it's lumped under Firefox

**Comment by fmarier** [comment]
@callahad a new category might be useful given that these questions aren't necessarily coming from Firefox users.

**Comment by shane-tomlinson** [comment]
Link to #2186

**Comment by callahad** [comment]
There's some pushback from SUMO on the mechanics of getting our own section. Discussion ongoing.

**Comment by callahad** [comment]
We have a plan to get our own section up and running on SUMO. Timeline is still up in the air; I've asked for clarification.

**Comment by callahad** [comment]
SUMO's target is September 11th, so we should be good.

**Comment by fmarier** [comment]
It's now mostly updated, but the page title still uses BrowserID: https://support.mozilla.org/en-US/kb/what-browserid-and-how-does-it-work

**Comment by callahad** [comment]
SUMO pushed back their launch until next week, so we'll have to wait until then for our own section.

**Comment by callahad** [comment]
Our section on SUMO is live at http://support.mozilla.org/en-US/products/persona

Just need to update one article title

**Comment by seanmonstar** [comment]
@callahad are we good? can we hit the awesome close button?

**Comment by jrgm** [comment]
I think this is all covered except for changing the URL in layout.js for Need Help and I'll open a separate issue for that.

**Comment by fmarier** [comment]
I've submitted a new revision on SUMO to improve the URLs:
- persona.org -> login.persona.org
- myfavoritebeer.org -> 123done.org

**Comment by jrgm** [comment]
My followup for 'Fix the URL in layout.js to be the correct one at SUMO' is GH-2570
