### ISSUE TITLE
Need a RP that points to l10n-preview.diresworb.org

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2164]
Currently localizers go [here](http://ozten.com/random/browserid/bid_test.html) and click signin to launch [Persona login](https://l10n-preview.diresworb.org/sign_in).

This is weak sauce.

We need a maintained deployment of 123done.org, so they can preview and test their work.

**Comment by lloyd** [comment]
There is a new translation environment we'll be using for now.

URL to main site:  https://translate.personatest.org
URL to website that uses it: https://translate.123done.org
URL to current github SHA and SVN version deployed: https://translate.personatest.org/ver.txt

Updating details:

polls SVN at 5 minute intervals.  When change is detected, update takes about 8 minutes, that means 15 minutes is the maximum expected time between translations being committed and updates being visible.
