### ISSUE TITLE
compile-json.sh breaks stage deployment

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2165]
See http://atoll.pastebin.mozilla.org/1716147

This is blocking @floatingatoll pushing to stage.

@lloyd I think we had some l10n re-working, do we need to update shell scripts or deployment steps?

**Comment by floatingatoll** [comment]
the paste will expire; make rpm fails on train-2012.07.20 with latest locale as follows:

```
+ export PATH=/home/rsoderberg/browserid/rpmbuild/BUILD/browserid/node_modules/.bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/rsoderberg/bin
+ PATH=/home/rsoderberg/browserid/rpmbuild/BUILD/browserid/node_modules/.bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:  /usr/sbin:/sbin:/home/rsoderberg/bin
+ ./locale/compile-mo.sh locale/
+ ./locale/compile-json.sh locale/ resources/static/i18n/
syntax:
compile.sh locale-dir/ json-dir
error: Bad exit status from /var/tmp/rpm-tmp.LoFHhi (%build)
```

**Comment by ozten** [comment]
Looks like we need 

mkdir -p resources/static/i18n/

to deal with i18n existing or not existing.

This train removed it from sources and it's contents gets created via scripts.

**Comment by floatingatoll** [comment]
confirmed "mkdir -p resources/static/i18n; make rpm" works, build resumed.

**Comment by ozten** [comment]
Once https://bugzilla.mozilla.org/show_bug.cgi?id=777979 is resolved, I'll be able to commit a fix:

```
Index: browserid/locale/compile-json.sh
===================================================================
--- browserid/locale/compile-json.sh    (revision 107852)
+++ browserid/locale/compile-json.sh    (working copy)
@@ -17,6 +17,8 @@
     exit 99
 fi

+mkdir -p -v $2
+
 # check if file and dir are there
 if [[ ($# -ne 2) || (! -d "$1") || (! -d "$2") ]]; then usage; fi
```

**Comment by ozten** [comment]
LOL, haven't committed to SVN in 6 months+ so it expires.

Committed revision 107854.
