### ISSUE TITLE
Create a team-focused status page

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2166]
@ozten gave this a first shot with the (now defunct + deleted by me) project status wiki page a few months back.

Maybe we can clarify what audiences this status page would serve (moz devs? external devs looking to jump in? other ppl?) and knock something together. 

Github pages might be an easy way to get it going and keep it up-to-date with the rest of the codebase.

**Comment by ozten** [comment]
Problem: a developer wakes up, gets out of bed and … Can I commit code today? Can I merge to master? Should I be doing DDT? What is in production? what is in Stage?

How many days until code freeze?

A prior, prior attempt:
http://skitch.com/oztenskitch/8hf6d/sched2

**Comment by fmarier** [comment]
Interesting, so it's more like a team dashboard (as opposed to a status page like the one that the Services team is running).

**Comment by nmalkin** [comment]
#896 has some prior discussion of a status page.

**Comment by callahad** [comment]
Updated issue title; I think we need two things: The external-facing information from #896 and the more internal-facing / project-managementy information from this issue.

**Comment by jaredhirsch** [comment]
meh, been lingering forever. closing.
