### ISSUE TITLE
Change all wsapi calls to return JSON response

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#217]
In some places, we return strings, other areas JSON, other areas nothing.

**Comment by shane-tomlinson** [comment]
Starting with 838d7d8ffdc6b74ba576fbce5c406628cc1ae4ca on /wsapi/csrf

**Comment by shane-tomlinson** [comment]
@lloyd - for some of these calls I see that you are doing things like "resp.json(true)";  What would you think of returning a JSON object that has a `success` and possibly `reason` fields for all calls?

I am thinking something along the lines of -

in the case of success:

```
{
  success: true,
  other_fields...
}
```

in a failure case:

```
{
   success: false,
   reason: '...'
}
```

Having this would allow us to expand on possible failure modes, I am thinking in particular the prove_email_ownership call where we could return a message or an error code indicating that the email has already been registered.

**Comment by shane-tomlinson** [comment]
@lloyd - I am removing commit 838d7d8ffdc6b74ba576fbce5c406628cc1ae4ca as Ben has said that returning the CSRF token in a JSON blob can effectively eliminate CSRF protections.

**Comment by lloyd** [comment]
@shane-tomlinson please explain more of @benadida's reasoning?

**Comment by benadida** [comment]
OK, it turns out I was a bit too paranoid. Good :)

We can do this as long as we _only_ do top-level objects, e.g. {foo: "bar"}, _never_ top-level arrays. If we need to return an array, we should return it as a named array inside an object.

@shane-tomlinson: can you move this forward by ensuring that all JSON returned values are passed through a consistent check that ensures the above condition?

**Comment by shane-tomlinson** [comment]
@benadida - I am confused for the request here, what test needs to be done?  jQuery handles the decoding of JSON objects automatically unless we force the response types to "text" in which case we can analyze the strings and detect if it is a top level object or array, but this seems like overkill.  If somebody has done an XSS injection and taken control of Array.prototype.constructor, they can equally as well take hold of our $.ajax function to bypass any checks we are doing.

Would it make sense to move _all_ responses to JSON based objects regardless?

**Comment by benadida** [comment]
@shane-tomlinson I suggest that we implement a returnJSON() call on the server (or override resp.json) to ensure that we're never returning anything other than a top-level object.

Yes, I agree that it now makes sense to go to JSON-based objects for all return values.

**Comment by lloyd** [comment]
Rather than returnJSON, how about a lil tiny middleware?

--lloyd

**Comment by shane-tomlinson** [comment]
@benadida - now I get what you were saying, I misinterpreted and thought this check was to be on the front end.

**Comment by lloyd** [comment]
On Sep 30, 2011, at 7:58 AM, Ben Adida wrote:

> That will scan check content-type? This assumes we're otherwise behaving properly... I guess it's okay, we should be returning proper content types too.

no dude.  just override resp.json at early stage middleware, like this:

```
app.use(function(req, resp, next) {
    var rizneal = resp.json;
    resp.json = function(obj) {
        if (!obj || typeof obj !== 'object') {
            logger.error("INTERNAL ERROR!  *all* json responses must be objects");
            throw "omglol.";
        }
        rizneal.call(resp, obj); 
    }
});
```
