### ISSUE TITLE
IE8: exceptions thrown in bidbundle.js

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2171]
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
Timestamp: Fri, 27 Jul 2012 11:45:49 UTC

Message: Syntax error
Line: 2757
Char: 1
Code: 0
URI: http://192.168.1.88:10002/common/js/lib/bidbundle.js

@benadida - on lines 2757 and 2760, you use the const keyword.  IE8 does not support this.

**Comment by benadida** [comment]
fixed in 4f41365a5732cce2201b462a7a3526cfccac124c

**Comment by lloyd** [comment]
upgraded to published 0.4.0, closing this down

**Comment by lloyd** [comment]
(IE is happy)

**Comment by jrgm** [comment]
verified. At this time, jwcrypto 0.3.2 which is used with train-2012.07.30 and jwcrypto 0.4.1 which is with dev branch both contain no 'const' references (expect for a test in 0.3.2).
