### ISSUE TITLE
sites_signed_in and sites_visited KPI renaming

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2176]
PR #1807 introduced multiple new KPIs including sites_signed_in and sites_visited.

Neither of these names clearly convey their intent.

sites_signed_in should be number_sites_signed_in
sites_visited should be number_sites_remembered

**Comment by jedp** [comment]
I particularly like the move to `number_sites_remembered`

@nmalkin , let's not forget to do some data migration in kpiggybank

**Comment by nmalkin** [comment]
@jedp, is that how you think we should proceed? I was going to build in support for both names into the dashboard.

Now that I think about it, though, that would be _three_ different names, and the code would become irrelevant pretty soon. So, yeah, I'm liking the idea of data migration. I'll open a separate issue for that.

**Comment by jedp** [comment]
Merged PR 2177

**Comment by jrgm** [comment]
verified in local build train-2012.08.17.
