### ISSUE TITLE
validating an email a second time causes undecipherable error.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#218]

**Comment by shane-tomlinson** [comment]
6c9ff3ca7dcf1679be6de13f9a1ac93f7d386bd3 changes the error message to ask "Have you previously verified this address?"  

What is the possibility of the backend keeping track of these tokens and their status, if the token is already validated when the call is made to /wsapi/prove_email_ownership', we pass back a status saying "already validated" or something similar so that we can display an appropriate message to the user.

**Comment by lloyd** [comment]
The nice thing about how things work right now is we can purge all record of the secret after verification, or periodically (purge tokens older than 2 days?).  I like the performance/scalability properties of the current implementation.

So right now we have two possible states that a "secret token" can be in: known (and valid) or not.

If we wanted to have three states: verified, unknown, unverified - then we would increase database requirements slightly.  Given we send about 4 emails per second at 1M active, and each of those emails requires a row, we'd have about a 400k row table if we always kept tokens around for 2 days.

That's manageable, but interesting enough that I'd like to get feedback from UX as to how important the changed feedback is.  @clarkbw ?

**Comment by clarkbw** [comment]
If I'm understanding correctly the total experience seems like it's going to be the same either way, we need them to re-validate (if an old token was used) or they are all good to go (clicking on the link a second time).  

The difference there being that we could tell people a token was already used versus not knowing the difference between used or incorrect.

## incorrect token case
- link gets garbled by the users email client somehow

_Our design goal is mostly to help them verify via a new link or something else_
- landing page says "Hey clarkbw@example.com, we're still waiting for your confirmation.  Do you want us to <a>resend it</a>?"
  - Alternates are to have a text input where people could copy & paste the code sent in the email if the link isn't working, requires some additional text in the email

## previously used token
- user clicked and verified their email previously
- in trying to find their browser id information the user re-clicks the original verify email

_design goal is to get them to verify an email if they need to do that or get them to the manage page_

### needs to verify an email
- works similar to the incorrect token case

### all user emails are verified
- redirect to the main page with a quick flash of "you're already verified and good to go"

**Comment by shane-tomlinson** [comment]
@skinny97214 - since we are going gang-busters on the user completion flow, want to weigh in on this?  Action on this has gotten lost.
