### ISSUE TITLE
add a /robots.txt file 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2181]
From a chat in IRC with @floatingatoll, but it might be useful to add a /robots.txt file and enumerate just those things that are useful to users in finding us. 

For example, search google with site:login.persona.org and site:login.anosrep.org
1. both sites are indexed about the same, but the general user should never care that staging login.anosrep.org exists so ask to not be indexed on stage and dev
2. the search returns /unsupported_dialog, /verify_email_address, /sign_in, /add_email_address. Not particulary useful information to the general user especially since the latter three all show an error if you follow the link from the google search.

**Comment by lloyd** [comment]
good idea!  Let's do some SEO!

**Comment by jaredhirsch** [comment]
I guess, arguably, this could get done by Beta 2. Leaving it open & handing to @lloyd. Reassign as you will.

**Comment by jrgm** [comment]
This is still a valid issue, and not so hard to do (a view that provides different robot advice on prod vs. stage/dev/ephemeral). Good first bug.

**Comment by es** [comment]
Hey @lloyd, mind if I work on the issue?

**Comment by lloyd** [comment]
@EmilS All yours!

**Comment by shane-tomlinson** [comment]
Done! Merged with c0b2bba5b334f73b7eb340107dad4864067e2582. Thanks @Somsubhra
