### ISSUE TITLE
dynamically size domain name inside dialog

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2182]
In the sign in completion step in the browserid dialog, the domain is shown while the left-to-right arrowish animation occurs (sorry, don't know the local UX terms yet). Every time I log into bugzilla, the domain name overlaps the icon image and the edge of the arrow slider, and looks a little sloppy.

I'd suggest we do some dynamic resizing of the domain's font-size along these lines: http://stackoverflow.com/questions/4449293/fit-text-to-a-div

(Procedural question: would this be better submitted as a pull request with code attached?)

**Comment by jrgm** [comment]
So in the current train-2012.07.20, there are a couple of changes coming. One is that the font size of the domain is reduced. The other is that the animation now proceeds all the way offscreen right (i.e., the arrow head doesn't stop at the right margin).

**Comment by shane-tomlinson** [comment]
@6a68 - I would rather not dynamically resize the text until after we try out the upcoming changes.  There is also a PR outstanding that wraps long siteName's to be on multiple lines. #2172

**Comment by jaredhirsch** [comment]
@shane-tomlinson: sounds good; thanks for the pointer to #2172. Still getting up to speed on the project context :-P
