### ISSUE TITLE
Idea: Remind native IdP users to log out of their IdP after authing with us

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2188]
A user with a native IdP needs to have an active session with their IdP to authenticate with us.

If they don't have an active session with their IdP at the start of provisioning, they will by the end of it.

Thus, in cases where we redirect the user to their IdP's authenticate page, it may not be obvious to the user that authenticating _also_ sets up a session with their IdP.

Thus, we might want to remind them to log out of their IdP when they're done, before we close the dialog and let them go about their business.

Something like "Hey, you're now signed into gmail! Don't forget to sign out of gmail when you're done with this computer.

**Comment by seanmonstar** [comment]
That's kind of a terrible experience, though. I likely wouldn't even
remember that I had been logged into my IdP. Now, when I'm done surfing
from the library, I have to remember to logout of the site I was using,
Persona, and Gmail.

**Comment by lloyd** [comment]
take this to the mailing list!  we have 296 open issues, and can't really support ideas in the tracker anymore

**Comment by callahad** [comment]
I'm happy to let this die here :)
