### ISSUE TITLE
User must re-enter password in dialog post-verification

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2191]
This is the last remaining issue from the changes to fix #2088 and #2104.

STR

1) Create an account with one primary and one secondary address
2) Open dialog, sign out.  Sign in with primary address.
3) Click "Add new email"
4) Enter new secondary address
5) Verify address in same browser, but new tab.
6) User has to enter password again.

I am forcing the user to enter their password because otherwise, /wsapi/cert_key would return an error "Must Authenticate"

**Comment by jaredhirsch** [comment]
Closing; I can't repro this any longer. Please reopen if I'm wrong (and move to Beta 3 milestone).

**Comment by shane-tomlinson** [comment]
Thanks for checking @6a68 - I can no longer repro either.
