### ISSUE TITLE
IE8-10 exception on dev.123done.org

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2194]
```
SCRIPT5: Access is denied.

communication_iframe, line 1 character 1

LoggedInEmail has been deprecated

SCRIPT1002: Syntax error
communication_iframe.js, line 3 character 10191
```

This is a distinct error from #2183

**Comment by shane-tomlinson** [comment]
At character 10191 of line 3 is a "const".  The jwcrypto deps need updated.

**Comment by lloyd** [comment]
we fixed this by moving to 0.4.0

**Comment by seanmonstar** [comment]
@lloyd if we fixed this, can we close?

**Comment by lloyd** [comment]
yes we can.

**Comment by jrgm** [comment]
verified. At this time, jwcrypto 0.3.2 which is used with train-2012.07.30 and jwcrypto 0.4.1 which is with dev branch both contain no 'const' references (expect for a test in 0.3.2).
