### ISSUE TITLE
Build example IdP for Dynamic Identifiers work

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2196]
In starting the [dynamic identifiers](https://github.com/mozilla/id-specs/issues/18) work, buld out an example idP much like our example RP, delegated idP and primary IdP under the `/example` directory.

This work will be done in a branch.

This branch will be exposed to Firefox OS development, but not pushed for Beta 1.

**Comment by lloyd** [comment]
@ozten please repeat in the bug how we can help

**Comment by ozten** [comment]
Won't fix
