### ISSUE TITLE
Accepting emails to persona@persona.org?

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2197]
Emails sent by Persona use "Persona@persona.org" as the From address, but emails sent to that address bounce:

```
This is the mail system at host mx1.mail.corp.phx1.mozilla.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<Persona@persona.org>: connect to persona.org[63.245.209.241]:25: Connection refused
```

Should we accept emails sent there for statistical / debugging / support reasons?

(This may have privacy implications.)

**Comment by benadida** [comment]
doh! nice catch. We should start by replying with a reasonable response.

**Comment by lloyd** [comment]
@pfinette any ideas on a lightweight way to wrangle user email?

**Comment by jaredhirsch** [comment]
What about switching to no-reply@persona.org?

**Comment by jrgm** [comment]
Actually, the current train will send out the emails as no-reply@persona.org. @fmarier, I think, was asking if we should actually accept the emails to whatever address, and reply with something a little nicer.

**Comment by fmarier** [comment]
@jrgm is right. Regardless of the sender address that we use, I was asking: what happens to the emails that users send to it?

**Comment by seanmonstar** [comment]
Yea, no-reply is crazy talk.

**Comment by jaredhirsch** [comment]
_Sigh_. I started from the wrong end of my github notifications and saw the original bug description, but not any of the later discussion.

**Comment by jrgm** [comment]
@seanmonstar, @6a68 Well, 'no-reply@persona.org' is what is about to ship in train-2012.08.17.

**Comment by fmarier** [comment]
Emails are sent from `no-reply@persona.org` now.
