### ISSUE TITLE
gravatar in login box

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#22]
cause it's awesome

**Comment by benadida** [comment]
cause I'm an idiot and I closed the wrong bug in code comment

**Comment by johndrinkwater** [comment]
Or libravatar.org
Or if you're verifying emails, you could read the X-Face header and get a _verified_ avatar.

**Comment by lloyd** [comment]
let's defer to bryan clark and our UX homies to figure out whether/how to integrate this.

**Comment by skinny97214** [comment]
Love the idea. Closing this as we'll be doing up a complete solution to the basic profile (name+avatar) in #880
