### ISSUE TITLE
tooltip does not show arrow as specified in designs

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2200]

**Comment by jrgm** [comment]
Spiffy! verified on train-2012.08.17 incl. IE8. One note, you have a redundant border-top rule in the PR at GH-2201.

**Comment by shane-tomlinson** [comment]
@jrgm - thanks, the two rules is because IE8 doesn't support alpha transparency in CSS, so it falls back to using a color it understands.
