### ISSUE TITLE
Personal Delegated IdP works against dev, but not stage or production

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2205]
Howdy!

I created hostedpersona.me and delegate to it via ozten.com.

This works well against dev.123done.org.

Both beta.123done.org as well as 123done.org do not work.

I've created HAR snapshots, so you can see all the network traffic in a firebug like screen.

Stage:
1) Go to http://www.softwareishard.com/har/viewer/
2) Copy JSON from https://raw.github.com/gist/3231728/74a0f5eafb6a230425189661a36d5b414f5f9251/login.anosrep.org.har
3) Paste into large text area
4) Click Preview
5) Toggle POST auth_with_assertion

Production:
1) Go to http://www.softwareishard.com/har/viewer/
2) Copy JSON from https://raw.github.com/gist/3231766/148c52d8335285500c652be88d5a19fca6175515/login.persona.org.har
Steps 3, 4, 5 from above

Does this demonstrate a data format issue or ???

**Comment by ozten** [comment]
This fails at auth with assertion. Using production and Firebug, I took my assertion and ran it through jwcrypto's check-assertion.

It fails, saying the cert is good but the assertion has a malformed signature.
Then... if I run the same command 5 minutes later, it says the cert and the assertion are good.

```
./bin/check-assertion $P $A 
==== cert ====
issuer: https://hostedpersona.me
principal: {"email":"shout@ozten.com"}
iat: Sat Aug 04 2012 14:52:53 GMT-0700 (PDT) (1344117173084)
exp: Sat Aug 04 2012 15:52:53 GMT-0700 (PDT) (1344120773084)
(using a median timestamp to ensure no timestamp failure)
cert is properly signed

==== assertion ====
{ header: { alg: 'DS128' },
  payload: { exp: 1344117298789, aud: 'https://login.persona.org' },
  signature: '5f1e357d5bb434dee894e6f1628795999aedfac0859cd0343d7d56c5f7e2bc644e464b5408af07a',
  headerSegment: 'eyJhbGciOiJEUzEyOCJ9',
  payloadSegment: 'eyJleHAiOjEzNDQxMTcyOTg3ODksImF1ZCI6Imh0dHBzOi8vbG9naW4ucGVyc29uYS5vcmcifQ',
  cryptoSegment: 'BfHjV9W7Q03uiU5vFih5WZmu36wIWc0DQ9fVbF9-K8ZE5GS1QIrweg' }
audience: https://login.persona.org
expires: Sat Aug 04 2012 14:54:58 GMT-0700 (PDT)
(verifying with an expiration date that should be valid for this assertion.)
FATAL: assertion is NOT properly signed: malformed signature

==== bundle ====
assuming public key is the key for https://hostedpersona.me
bundle *seems* to verify ok!
cert chain length:  1
audience:           https://login.persona.org
domain from email:  ozten.com
certificate issuer: https://hostedpersona.me
```

**Comment by ozten** [comment]
Digging into why this fails... It looks like the check-assertion tool is busted.
https://github.com/mozilla/jwcrypto/pull/45

Fixing that, It now says cert, assertion, and bundle are all good:

```
./bin/check-assertion $P $A   
==== cert ====
issuer: https://hostedpersona.me
principal: {"email":"shout@ozten.com"}
iat: Sat Aug 04 2012 14:52:53 GMT-0700 (PDT) (1344117173084)
exp: Sat Aug 04 2012 15:52:53 GMT-0700 (PDT) (1344120773084)
(using a median timestamp to ensure no timestamp failure)
cert is properly signed

==== assertion ====
{ header: { alg: 'DS128' },
  payload: { exp: 1344117298789, aud: 'https://login.persona.org' },
  signature: '5f1e357d5bb434dee894e6f1628795999aedfac0859cd0343d7d56c5f7e2bc644e464b5408af07a',
  headerSegment: 'eyJhbGciOiJEUzEyOCJ9',
  payloadSegment: 'eyJleHAiOjEzNDQxMTcyOTg3ODksImF1ZCI6Imh0dHBzOi8vbG9naW4ucGVyc29uYS5vcmcifQ',
  cryptoSegment: 'BfHjV9W7Q03uiU5vFih5WZmu36wIWc0DQ9fVbF9-K8ZE5GS1QIrweg' }
audience: https://login.persona.org
expires: Sat Aug 04 2012 14:54:58 GMT-0700 (PDT)
(verifying with an expiration date that should be valid for this assertion.)
assertion is properly signed

==== bundle ====
assuming public key is the key for https://hostedpersona.me
bundle *seems* to verify ok!
cert chain length:  1
audience:           https://login.persona.org
domain from email:  ozten.com
certificate issuer: https://hostedpersona.me
```

**Comment by ozten** [comment]
Okay, I'm pretty sure that I'm hitting secondary to primary bugs.

I debugged a few issues and fixed them using a local BrowserID server (verifier was requesting https://https://hostedpersona.me/.well-known/browserid - fix by not including the protocol in the certificate issuer field)

I how see:

```
user logs in with a primary address that was once a secondary, not implemented (shout@ozten.com)
```

Deleting myself from my local database, I can now auth again on a local dev instance.
I am unable to delete my production 'shout@ozten.com' account.
I did delete my account via a secondary email which has a bunch of emails in it... but I don't see shout listed there.
Renaming my well known and trying to sign in to the Persona homepage gets me a 500 for address_info check.

**Comment by ozten** [comment]
As a quick sanity check, I tried to sign in with a new email address, "always@ozten.com". I was able to successfully able to auth in production.

You can try it too... any password will work on the 'always' account. I think this confirms the existing secondary user hypothesis.

**Comment by ozten** [comment]
With the beta code release, I'm again able to use shout@ozten.com as a primary address.

I cannot explain why this works now. Leaving open to be part of the "secondary <-> primary" polish bugs.

**Comment by jaredhirsch** [comment]
@ozten - are we good to close this bug, or should we target it for end of Q1? cc @callahad

**Comment by ozten** [comment]
Good call.
