### ISSUE TITLE
forgot password page is missing the email address it applies to 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2210]
See below. The signup.js page display the email address correctly in comparison.

![img](https://img.skitch.com/20120803-gbd34fdd8r1kquk5yucx5xgjy7.png)

**Comment by lloyd** [comment]
against train-2012.07.30?

**Comment by jrgm** [comment]
Yes, on train-2012.07.30. But now looking again this is not always reproducible. From inspecting localStorage when it doesn't work vs. when it gets in a state that it works, 'main_site' === '{}' for the fail case, but is '{ "signInEmail": "foo@example.com" }' when it does work (which makes sense). Not sure how I get it in the fail state. This is with FF14 on osx.

**Comment by shane-tomlinson** [comment]
@jrgm - Are there any STRs that I can try to see this, even if I have to do it many times?  I have so far not been able to.

**Comment by jrgm** [comment]
@shane-tomlinson aargh this is hard to get a reliable STR. But it has something to do with Firefox where you have used its password manager to save the password for a secondary email address and then do signin/forgot-password. (Which is a bit silly since the browser is already offering you the password). I'm gonna leave this for now and move on to other stuff.

**Comment by shane-tomlinson** [comment]
@jrgm - Are you still able to reproduce this?

**Comment by jrgm** [comment]
The /signup URL is no longer used; it happens in the dialog. Closing this issue.
