### ISSUE TITLE
on /signin and /signout two buttons have the same id

### ISSUE THREAD

**Issue by klrmn** [mozilla/persona#2211]
to reproduce:

go to https://login.dev.anosrep.org
click sign in (or sign up)
fill in email
click Next
view html

```
        <div class="submit cf forminputs start">
            <button id="signIn">Next</button>
        </div>

        <div class="submit cf forminputs password_entry">
            <button id="signIn">Sign In</button>
        </div>
```

as a general rule, you're not allowed to give two items on the same page the same id.
note that the button for submitting the passwords for sign-up does have a unique id.

**Comment by shane-tomlinson** [comment]
@kirmn - excellent catch, I can guarantee this was a copy/paste error on my part.  Those IDs aren't actually used for anything, removing.

**Comment by klrmn** [comment]
Hi @shane-tomlinson ,
while you might not be using those ids for anything, automation would very much like to have unique ids on those buttons. looking up something by id takes less oomph than looking them up by css selector.

**Comment by shane-tomlinson** [comment]
@kirmn - thanks for the quick feedback.  I have updated the PR to put the IDs back and give the next button the id of "next"

**Comment by klrmn** [comment]
@shane-tomlinson - i wish i could provide you quick verification, but the servers seem kinda fubar today

**Comment by klrmn** [comment]
LGTM
