### ISSUE TITLE
IE will not keep you logged in (observer API, current production)

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2218]
STR:
1. log into 123done.org on IE (8, 9, 10)
2. restart your IE browser
3. return to 123done.org

expected: you're still logged in
actual: you ain't

**Comment by lloyd** [comment]
fixed in dev and train-2012.07.30

**Comment by seanmonstar** [comment]
Was this what latchkey was running into? It was in prod?

**Comment by jrgm** [comment]
Verified. With [ ie8, ie9, ie10 ] X [ train0730.123done.org, dev.123done.org ] after signin, then quit IE, then return to 123done in IE, I recover my signed-in state correctly.
