### ISSUE TITLE
If user adds mistyped secondary email addr, the only path to correct it is to close the dialog and start over  

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2223]
User story:
1. A user has authed already. They go to an RP and want to add another email. 
2. User mistypes the email addr and clicks 'add'.
3. Screen transitions to show 'Confirm your email address' and shows the email addr they typed.
4. After waiting a bit for the email to arrive, the user looks at the dialog and notices the typo.

We used to show a link "If this is a mistake, just ignore the sent email and <a %s>use another email address</a>" that would let the user navigate back and re-enter the correct email address (it even prefilled the email with the off-by-one-char typo). In current UI, the only option for the user is to close the dialog and start again. 

This may have been intentional, and you can close this as as-designed, but I think this link was useful ;-)

**Comment by shane-tomlinson** [comment]
@jrgm - this was intentional in the redesign.  @skinny97214, can you weigh in here?

**Comment by lloyd** [comment]
@skinny97214 close if this is by design
