### ISSUE TITLE
dev.diresworb.org SSL cert is expired

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2224]
STR
1. Go the https://login.dev.anosrep.org and click for /signin page
2. Enter &lt;somename&gt;@eyedee.me and click next

Nothing much appears to happen but wait for ~30 seconds and the error screen is shown. More info says only 'Action: Checking Address Info'. A network trace with httpfox or firebug shows a failure on the client side in GET-ing https://dev.diresworb.org/provisioning_api.js

NOTE: this is not seen on train-2012.07.30 for an ephemeral deploy as https://train0730.personatest.org

**Comment by jrgm** [comment]
Ah, I see.

Loading https://dev.diresworb.org/provisioning_api.js directly gives:

```
dev.diresworb.org uses an invalid security certificate.
The certificate expired on 8/3/12 5:43 AM. The current time is 8/3/12 2:23 PM.
(Error code: sec_error_expired_certificate)
```

And so we fail to load it, javascript errors for navigator.id is not defined and bleh.

**Comment by jrgm** [comment]
Now https://bugzilla.mozilla.org/show_bug.cgi?id=780300. Thanks @6a68.

**Comment by jrgm** [comment]
Closing in favor of the ops ticket.

**Comment by lloyd** [comment]
this is, as of now, really addressed in our dev environment.  thanks @gene1wood !
