### ISSUE TITLE
In dialog, changing the email chosen then 'Forgot password' causes email to be sent to initial email not the corrected one.

### ISSUE THREAD

**Issue by gion-andri** [mozilla/persona#2231]
I found a bug on todays version of translate.personatest.org. 
1. Sign in (e.g. at http://translate.123done.org) with a wrong email adress (for example mistyped). 
2. Click cancel
3. Enter your correct email (from an existing account)
4. Click 'Forgot your password?'
5. Enter a new password and send the form

I get an email on the wrong (mistyped) adress with a link to activate a new account. The password for the existing account isn't changed.

**Comment by adamkalis** [comment]
I can also reproduce this bug. The mail was sent and received to the first wrong email address (the one at the first step).

**Comment by jrgm** [comment]
Yep, indeed.

**Comment by jrgm** [comment]
Update summary

**Comment by jrgm** [comment]
verified train-2012.07.30 for the original STR.
