### ISSUE TITLE
Wrong UI after cancelling "Forgot your password?" action.

### ISSUE THREAD

**Issue by adamkalis** [mozilla/persona#2234]
Steps to reproduce
1. Go to http://translate.123done.org/
2. Click on "Sign in with Persona"
3. At the pop-up complete an email address and press next
4. Press the "Forgot your password?" link, next to the "Sign in" button
5. Press the "Cancel" link, next to the "Reset password" button

What happens:
The UI returns on "Checking with your email provider." screen

What should happen:
The UI should return to login screen (the one at the 4th step) or to first screen (the one at the 3rd step)

Note: if you change the email on the "Checking with your email provider." screen, for example remove a letter, then the first screen shows up.

**Comment by jrgm** [comment]
This is/was GH-2132. It is fixed in the dev branch but  not in train-2012.07.30 which is essentially the code that translate.personatest.org / translate.123done.org are using.

**Comment by jrgm** [comment]
Thanks for the bug report. I am going to close this one as a duplicate.
