### ISSUE TITLE
Implement better support for iOS UIWebView

### ISSUE THREAD

**Issue by st3fan** [mozilla/persona#2240]
PROBLEM: when returning from IdP, no more JS context that lets Persona communicate back with iOS app. Possible approach: when Persona wishes to redirect to IdP, it communicates with iOS app, iOS app creates a new UIWebView to IdP, injects the IdP API instead of the RP API, and upon completion of authentication, kills the new UI Web View, and messages the now unhidden Persona UIWebView to proceed with reprovisioning.

As discussed with @benadida and @callahad at https://id.etherpad.mozilla.org/ios

**Comment by st3fan** [comment]
I created a new tiny minimal iOS project that can be used to work on the Persona flow on iOS:

https://github.com/st3fan/ios-minimal-persona

Unlike the other project, this one does not depend on anything server side. It is super basic and just starts the flow and then prints the assertion.

The app does say it is logging in to myfavoritebeer.org, but that is only because I had to specify an origin. It does not actually talk to that site.

As per Ben's recommendation, I removed the interceptor that prevented the user from escaping the Persona dialog. It will now just load any URL, including redirects to IDPs.

You can run this in the iPad simulator. Just download Xcode from the App Store and you have everything you need.

Let me know if you want me to walk you through this code or if I can help with anything.

**Comment by lloyd** [comment]
this is a Q3 goal!

**Comment by jaredhirsch** [comment]
Does https://github.com/mozilla/persona-ios count as fixing this bug? If not, reopen :-)
