### ISSUE TITLE
Dysfunctional sign-in dialog

### ISSUE THREAD

**Issue by wrr** [mozilla/persona#2246]
Today, I was repeatedly getting dysfunctional sign-in dialog (no email addresses listed, no space to enter an email). login.persona.org also listed no emails. Clicking [Sign Out] on login.persona.org fixed the problem. See a screen shot here:
![img](http://mixedbit.org/tmp/persona.png)

**Comment by shane-tomlinson** [comment]
@wrr - can you give any more info?  What was the RP being used, is the problem reproducible, what were the steps to produce in the first place?  Any info we can get can help us.

**Comment by wrr** [comment]
I'm sorry, but I'm unable to reproduce this. Once I clicked Sign Out button on the login.persona.org the problem disappeared. 
I was authenticating on a localhost, the site uses the new observer API. Perhaps it was some intricate condition, feel free to close the bug.

**Comment by lloyd** [comment]
2 stars until we have concrete steps to reproduce.

related to #2241 ?

**Comment by michelv** [comment]
I had the same problem yesterday.
A not so obvious way to get around it is clicking "This is not me".

I don't know if the steps will help reproduce it, but here's my situation :
- two Firefox instances, one at home and one at work (not using Firefox Sync)
- a self-hosted OpenPhoto install (3.0.1 at the time) on which I log in using Persona

…and how I got the problem:
- Persona on my work computer asked me to enter my password again, and I had forgotten the password I set
- I changed the password and validated the change using the link sent to my e-mail address
- when I got home and tried to log in using Persona, there was no e-mail displayed in the popup (like in the screenshot above)

I hope this helps.

**Comment by callahad** [comment]
Not to pile on, but I've also seen this happen. In my case, I was on a particularly flaky conference WiFi network at the time. Does the dialog need to do some kind of request to populate the list that might fail, despite the rest of the dialog rendering?

**Comment by wrr** [comment]
In my case, once the issue occurred, closing and reopening the dialog did not help (I tried it multiple times). So, at least in my case, it likely was not due to a temporary network problem.

**Comment by jrgm** [comment]
Oh, I see. This is GH-1472. Upping the starrage and nominating beta2-prereq on that one. Closing this as a duplicate. Thanks for the report and image and steps to reproduce.
