### ISSUE TITLE
Monitor and log email delivery times

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2247]
As per https://twitter.com/elijahmanor/status/232869682359697409 :

"Hmm, tried to sign-up for a BrowserID on MDN, but never received email conformation ;("

Did we have any known deliverability issues in the past day or two?

**Comment by callahad** [comment]
Followup from the user: "got an email response hours later" so he's good to go. Still, worth checking to see if this was on our end.

**Comment by jrgm** [comment]
I'd be interested in seeing the smtp headers, if those were made available. 

Otherwise, I have a monitor going through dev and it has not shown any delays of that order, but comparing that to prod is not entirely valid. I myself did have a case yesterday where delivery took ~10 minutes and I put in a ticket to our ops folks.

**Comment by callahad** [comment]
New purpose: We need to monitor and log email delivery times.

Title changed. @jedp to set up PersonaTestUser on a cron (5 minutes?) and log data.

**Comment by lloyd** [comment]
ping

**Comment by jedp** [comment]
Ok: to-do for me:
- create a new account at regular intervals using personatestuser
- capture the KPI stream for each identity created
- profit

**Comment by jedp** [comment]
@lloyd @callahad is this useful? http://50.16.47.187

Returns json structure of headers and data like so:

```
{ headings: 
   [ 'date',
     'session_context',
     'address_info',
     'stage_user',
     'email arrives',
     'complete_user_creation',
     'authenticate_user',
     'cert_key',
     'total_time' ],
  data: 
   [ [ '1348034925497', '832', '929', '1178', '2745', '1059', '959', '305', '12177' ],
     [ '1348035525055', '452', '701', '965', '2331', '683', '1118', '498', '7073' ],
     ...
   ]
}
```

Will have data up to the last 30 days.

**Comment by lloyd** [comment]
awesome.  closing
