### ISSUE TITLE
Calling navigator.id.watch() from the document <head> breaks onlogin/onlogout

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2252]
If you take the updated [Python cookbook example](https://github.com/mozilla/browserid-cookbook/blob/master/python/python.cgi) and apply the following patch (i.e. moving the `navigator.id.watch()` call from the `body` to the `head` of the page):

```
diff --git a/python/python.cgi b/python/python.cgi
index dba2f07..a559c32 100755
--- a/python/python.cgi
+++ b/python/python.cgi
@@ -10,8 +10,6 @@ def print_header(email = 'null'):

     print """<!DOCTYPE html><html><head><meta charset="utf-8">
 <script src="https://login.persona.org/include.js"></script>
-</head>
-<body>
 <script>
 navigator.id.watch({
     loggedInEmail: %s,
@@ -26,6 +24,8 @@ navigator.id.watch({
     },
 });
 </script>
+</head>
+<body>
 <form id="login-form" method="POST">
 <input id="assertion-field" type="hidden" name="assertion" value="">
 </form>""" % email
```

This problem occurs because:
1. `navigator.id.logout()` won't do anything if [`loggedInUser` isn't set properly](https://github.com/mozilla/browserid/blob/26a7264a31be3c210d7257bd0ab785ba5c040d3f/resources/static/communication_iframe/start.js#L96)
2. `loggedInUser` isn't set in the `navigator.id.watch()` call if [the communication channel isn't open](https://github.com/mozilla/browserid/blob/26a7264a31be3c210d7257bd0ab785ba5c040d3f/resources/static/include_js/include.js#L1071)
3. the communication channel is not open because while we're in the `head` of the document, [`dom.body` is null](https://github.com/mozilla/browserid/blob/26a7264a31be3c210d7257bd0ab785ba5c040d3f/resources/static/include_js/include.js#L998)

**Comment by jrgm** [comment]
verified in current dev (what will be train-2012-10-12)
