### ISSUE TITLE
MDN documentation issues

### ISSUE THREAD

**Issue by nmalkin** [mozilla/persona#2253]
On the [home page](https://developer.mozilla.org/en-US/docs/BrowserID):
- "To get BrowserID going, we're hosting three services at https://browserid.org"  
  should be Persona.org

Under "Information for Identity Providers":
- "IdP Overview" is a broken link
- "Development tips" is a broken link

[Guide to Implementing a Persona IdP](https://developer.mozilla.org/en-US/docs/BrowserID/Guide_to_Implementing_a_Persona_IdP)
- still references browserid.org instead of persona.org
- links to "Developer Tips and Tricks", which is a broken link

[Security considerations](https://developer.mozilla.org/en-US/docs/BrowserID/Security_Considerations)
- has old verifier URL (in two places)

[FAQ](https://developer.mozilla.org/en-US/docs/BrowserID/FAQ)
- still references browserid.org

[Remote Verification API](https://developer.mozilla.org/en-US/docs/BrowserID/Remote_Verification_API)
- has old verification URL in text and code samples

[Protocol overview](https://developer.mozilla.org/en-US/docs/BrowserID/Protocol_Overview)
- still references browserid.org

**Comment by lloyd** [comment]
@callahad what's eta on this?

**Comment by callahad** [comment]
@lloyd ETA for everything reviewed and cleaned up on MDN is no later than Monday morning.

**Comment by lloyd** [comment]
awesome, that's plenty fast.

**Comment by callahad** [comment]
Oops, forgot to close this. The docs are up to date. Thanks @nmalkin !
