### ISSUE TITLE
Changes to Selenium test importation.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2254]
This is a follow on tracker for @6a68's great work to import the Selenium tests (PR #2235).  I requested several changes in the PR but have since merged.
- Rename credentials.yaml to credentials.yaml.example and have people to copy it to credentials.yaml. Add credentials.yaml to the ".gitignore" file. This would prevent credentials.yaml from always showing up in a developer's modified file list.
- Add automation-tests/bid_selenium/ and automation-tests/results/ to the .gitignore list.
- Expand run.py so that it is possible to specify which driver to use and have it automatically set the correct command line parameters.
- The section in the README about writing automation tests is useful, but it leaves me scratching my head as to what I'd have to do to have a new test committed to both our mozilla/browserid repo and the upstream bidpom.

**Comment by jaredhirsch** [comment]
yay wut!

@shane-tomlinson thanks for your great detailed feedback on the test stuff. let me know if/when you start hacking tests, I'm happy to help :-)

**Comment by jaredhirsch** [comment]
seems out of date; closing. reopen if I've missed something.
