### ISSUE TITLE
implement cache busting

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#226]
implement a file naming scheme to support cache busting.  something like including a portion of the commit sha in referenced filenames with automatic substitution.

**Comment by lloyd** [comment]
can we use just ETags?  Unsure of browser support, but it's trivial to enable caching in connect's static middleware, and this already supports proper max-age and ETag headers.

**Comment by lloyd** [comment]
Shane and I spoke and we have an approach:
1. we'll use etags and non-zero max-age on include.js and all dom files
2. we'll include the first six chars of the current sha in session_context as 'code_version'
3. javascript bundles loaded (aka `production.js`) will have shas embedded in them (substitution needs to be figured out)
4. javascript bundles loaded will check that the current sha matches the sha in session context and will reload themselves with a specific url if required
5. server middleware will be installed that rewrites filenames : `s/(.*)_v[0-9a-fA-F]{6}(.*)/\1\2/`

lloyd will implement #2 and #5 and then pass the ball to @shane-tomlinson

_CONCERNS_: changing load order and reloading resources might mess up our somewhat fragile communication frame implementation.  We'll go slow and test along the way.

**Comment by shane-tomlinson** [comment]
@lloyd - I've done quite a bit of the work on the front end to be able to handle part #4.  Looking at part 3, in dialog_layout.ejs, we should be able to append the sha onto every "production.*" filename, this should work for css, js - background images are going to be tricky though.  Background images inside of the CSS are going to need some sort of search/replace mechanism, perhaps some sort of middleware that looks for {{sha}} (or similar) for local dev and sed at build time for the compressed CSS?

**Comment by lloyd** [comment]
as noted above, #2 and #5 are now done.  So  @shane-tomlinson tag!  you're it!  flip on 'enable_code_version' in configuration.js to see the backend support.

remaining work to be done  is substitution (as mentioned in #3 above) - seems like we need to bake code_version into production.js somehow (see this line https://github.com/mozilla/browserid/blob/dev/resources/static/dialog/start.js#L18 )

also, it seems like we might want to only enable code_version when minified resources is true.

The best approach I can think of at the moment would be to add a substitution thingy to postProcess to replace `__BROWSERID__CODE__VERSION__` with current sha (for develoment), and then for production, substitute that in compress.sh.

Key questions are:
- how does current code version get stamped into production.js?
- how does this work in development?

There's interesting interplay here with I18n efforts.  Specifically, if for I18n we'll be generating a cacheable production.js at runtime, then it might benefit us to performing resource generation at runtime rather than in a script....  dunno.

**Comment by shane-tomlinson** [comment]
@lloyd - To answer both of your questions, I have it implemented where there need to be two substitutions.

`__BROWSERID_ENVIRONMENT__` needs changed to "PRODUCTION" for code substitution to happen so we can debug without worry.

`__BROWSERID_CODE_VERSION__` needs changed to whatever the current code version is.

I am thinking to force an update of the scripts, using production_v`<VERSION>`.js is not the way to go, but instead we should be doing production.js?`<VERSION>`.  By adding the ?`<version>` we are forcing the browser to ignore the cache and fetch the updated resource with the added bonus that it forces an update of the browser's local cache.

**Comment by lloyd** [comment]
Ok, I'll grep around and try to figure out a sane way to do the substitution that works in all our environments.

Regarding adding GET data vs. changing the filename.  I remember some offhand suggestion from someone I respect (maybe it was @vmunix?) that certain poorly behaved middlemen on the intertubes might fail to update caches on appended get data where they wouldn't on an altered file name.

This is not well qualified information, but given it costs us little to do the filename update as opposed to appending get data, why not stay the course there?

Further I didn't understand your description of why get data is better.  it seems to me that in either case we'd force an update of browser cache?  Also that in either case we'd leave the old version in the cache till the browser decides it needs space...?

**Comment by shane-tomlinson** [comment]
@lloyd - OK, after last night's discussion, I am again comfortable with the _v`<VERSION>` scheme.  I have updated the front end to only do a version check if session_context returns a code_version variable.  The `__BROWSERID_ENVIRONMENT__` stuff has been removed.

**Comment by shane-tomlinson** [comment]
Linking to #620 - "Need cache headers on all static resources"

**Comment by shane-tomlinson** [comment]
@lloyd - Do we have proper etags set up and cache busting mechanisms in place?

**Comment by lloyd** [comment]
@shane-tomlinson All resources should have proper etags.  @ozten has taken the task of moving non-dom resources to perma urls with far future `maxAge`.

I think we can close this issue down and use/open two new ones.  one to track the task of dealing with out of date include.js, the other to track @ozten's task.

**Comment by ozten** [comment]
I wasn't aware of this bug, I'll definitely fold in our learnings here.

Closing and cache busting/http headers for static resources will happen in Issue#620.
Filed Issue#1089 to track dealing with out of date include.js.
