### ISSUE TITLE
IE8: After verifying second secondary email address, page is not redirected to RP.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2265]
This is intermittent and I am trying to figure out exact STRs

Initial STRs when I first saw the problem but have not since been able to.

1) In IE8, open the dialog using an already existing secondary address.
2) Add a new secondary address to the account
3) Open the verification page in a new IE8 tab
4) Page says "Your email has been verified" but never redirects.

Reported by @zacc

**Comment by zacc** [comment]
Saucelabs job video showing the failure.
http://saucelabs.com/jobs/3dd96e0838b24262acc962ab118190a1

**Comment by zacc** [comment]
Actually that video is IE9
the equivalent test running on XP/IE8 at Saucelabs passes.

**Comment by zacc** [comment]
The test that found this is test_add_another_email_address.py

When this is resolved revert this commit to restore coverage to IE9
https://github.com/mozilla/BrowserID-Tests/commit/0e3b7624b17e39a3669cf288d56b7f626b2d3a81

**Comment by jaredhirsch** [comment]
@zacc: Rather than pull that commit into browserid, I'm kind of inclined to just let the test keep on failing, so that @shane-tomlinson can easily verify he's fixed it (by running the affected test in his dev environment). Thoughts?

**Comment by zacc** [comment]
The test will show up with a small x while it is failing and a capital X in the test results when it is passing again. Or if you're looking in the HTML report it will say XPass. (meaning eXpected fail but got Pass).

Actually can you use a slightly different (preferred) code solution when you move this into the main repo? Just looks neater.

``` python
@pytest.mark.xfail("config.getvalue('browser_name') == 'internet explorer' and \
                   int(config.getvalue('browser_version')) == 9", 
                   reason='IE Local Storage https://github.com/mozilla/browserid/issues/2265')
def test_can_add_another_email(self, mozwebqa):
```

**Comment by jaredhirsch** [comment]
ok, since we're close to cutting the beta train and this might not get fixed, I'll pull over the fix.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
