### ISSUE TITLE
Make configuration tolerant of errors/omissions in production

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2268]
During the devops meeting, there was a request from @gene1wood and atoll  to make the configuration more tolerant of errors/omissions in production.

All config parameters should have a default value.

As appropriate, configs should be self-checking and report (possible) errors.

**Comment by lloyd** [comment]
I would not mind revisiting convict here.  I made a bad decision to include orderly in the initial creation of it.  Orderly prevents us from emitting better, clearer error messages.

I realize I suggest a heavy handed change to convict, but I just want it to be clear I've got no emotional attachment to it as it stands today and make sure all options are on the table.

If we can achieve our goals without reworking convict so extensively, then it will probably be less work.

**Comment by ozten** [comment]
I've spent some time with convict and [JVS](https://github.com/garycourt/JSV) and fixing this is non-trivial. I need help making these changes. I'm capturing devops requirements here, feel free to break this into more Issues and tackle them one at a time.

### Requirements:
- Config system should ignore unknown config, so that version 1 software can be deployed on version 2 config without the process existing
- Good error messages
  - For config properties with the wrong type or an invalid value, log an explanation "foo was set to 'bar', but server expected a number" or whatever
  - Bonus points: Check and log all of these error for the entire config before `process.exit`. This avoids an Ops person changing and restarting 4 times for a config file with 4 bad properties.
- Sanity check via heartbeat, startup, or another mechanism on core properties that can be misconfigured. Errors should not stop the server, but be logged as a warning.
  - Can we connect to the database
  - Can we GET /include.js from the static url
  - etc

### Nice to Haves:
- Config format should allow Ops to comment in configs
- A script which displays all possible config values, their docs, and default values
  - OR a maintained document with this info
  - Currently ops has to read lib/configuration.js to get this information

### Details

Config system should ignore unknown config. If the codebase doesn't know anything about redis, then 

```
{
    "redis": { "hostname": "localhost" }
}
```

should not cause the server to die. This will help ops in the case of rollbacks and mixed deployment with shared configs.

For a server that does support foo as an integer, then

```
{
    "foo": "bar"
}
```

would indicate that foo is known, but of the wrong type.

Sanity checks should be optimized for production deployment and not for the `run_locally` use case.

It's arguable that allowing comments in the config file should be a hard requirement.

**Comment by ozten** [comment]
Hmm, totally forgot a chunk of Gene's feedback. Updated previous comment and changed good error messages to "ignore unknown config".

**Comment by lloyd** [comment]
@zaach - Given that you're looking at re-vamping convict a bit and blogging about it, above are _suggested_ requirements from dev/ops.  Mind if I assign this to you?

**Comment by zaach** [comment]
@lloyd Thanks, this is a helpful list.

**Comment by zaach** [comment]
Bumping this, since the new convict has been released. We should see if it allows us to address these use cases. Importantly, it doesn't complain if there are extra settings not found in the schema.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
