### ISSUE TITLE
Localization docs don't tell users how to contribute new locales

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2279]
Hey @ozten or @mathjazz, could one of you please update https://github.com/mozilla/browserid/blob/dev/docs/I18N.md or http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/README to indicate how a user actually contributes a new translation back to the project?

The docs outline the mechanics, but stop short of saying "Okay, now that you've done that, here's how you submit this for inclusion."

Thanks!

**Comment by mathjazz** [comment]
Hey @callahad,

i18n.md are internationalization instructions for developers on how to make the project localizable, i.e. how to make the strings developers contributed available for localization.

README is mostly used by l10n drivers (and maybe deployment people) to help them learn how to extract new strings for every release and bring them to localizers.

The coordintation part with localizers is mostly done by l10n drivers via standard Mozilla localization communication channels (mailing lists, https://l10n.mozilla.org/ and https://localize.mozilla.org/), where we make announcements and where new locales can opt in.

However, I agree that there is no easy way from https://github.com/mozilla/browserid/ to localization. I think we should add something short and straightforward to https://github.com/mozilla/browserid/blob/dev/README.md which will connect localizers with l10n teams and l10n drivers.

Thoughts?
