### ISSUE TITLE
Some KPI data is missing fields

### ISSUE THREAD

**Issue by nmalkin** [mozilla/persona#2280]
Certain data points are missing fields, including:
- number_emails
- number_sites_signed_in
- number_sites_remembered
- orphaned

These fields are set [at window.unload time](http://irclog.gr/#show/irc.mozilla.org/identity/138345) so maybe the problem is somewhere around then.

The KPIs are otherwise normal, displaying non-empty event streams (some continue successfully through assertion generation), and appear on different operating systems (Mac, Windows, Linux) and browsers (Firefox, IE).

**Comment by shane-tomlinson** [comment]
@kparlante - have you seen this?

**Comment by kparlante** [comment]
@shane-tomlinson No, I have not seen this, but I will do a query on the production data tomorrow to confirm.

**Comment by kparlante** [comment]
@shane-tomlinson: I stand corrected, I do see this in production data when I go looking for it. About 4% of the blobs are missing the fields, if one is missing all are missing. I'll send you sample data.

**Comment by shane-tomlinson** [comment]
Thanks @kparlante for the extra info. Well, certainly the common factor is the four fields are set in the window.unbeforeunload DOM event. The browsers seem to be Opera/Webkit.

I wonder if we would be better off to _always_ include the communication_iframe, even for navigator.id.get. If communication_iframe were always included, we could be guaranteed of getting all results, for all users, regardless of the API, and we could set these KPIs to boot.

**Comment by shane-tomlinson** [comment]
@nmalkin - It took me 10 months to fix this problem - your diagnosis was spot on.

**Comment by nmalkin** [comment]
> @nmalkin - It took me 10 months to fix this problem - your diagnosis was spot on.

@shane-tomlinson: glad to see a happy ending! :smiley:
