### ISSUE TITLE
Distinct KPI for password reset screen

### ISSUE THREAD

**Issue by nmalkin** [mozilla/persona#2281]
Though the password reset screen is distinct from the regular set-password screen, the same event is emitted when it is displayed: _screen.set_password_. 

I propose having an event _screen.reset_password_ for this situation.

This is valuable, because, right now, there is no good way of identifying a user who is trying to reset his or her password through the KPI event stream. (The current best solution is to look for _screen.check_registration_ but **not** _user.email_staged_ or _user.user_staged_.)

(Similar to #1825).

**Comment by nmalkin** [comment]
> The current best solution is to look for _screen.check_registration_ but **not** _user.email_staged_ or _user.user_staged_.

Even that's not enough, as it turns out.

@shane-tomlinson, do you have any idea what subset of events could uniquely identify a user as being in the password reset flow? (Until we get this implemented.)

**Comment by shane-tomlinson** [comment]
@nmalkin - you wanna review the above to see if it gives you what you need?
