### ISSUE TITLE
new router process for verifier

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#2288]
We want to do traffic analysis on verifier to prevent attacks and what not, but we should do that separately from analysis on the dialog, since it's just not the same app and having user and server traffic flowing through the same router process doesn't seem right.

The solution is likely having a second router process in front of the verifier, meant only for routing verifier requests.

/cc @lloyd @zaach

**Comment by lloyd** [comment]
what are we trying to accomplish?  I think we should work toward having issues that discuss actual problems, not propose concrete implementation tactics.

In this case, we should move the verifier onto its own set of hardware off the boxes in use by the rest of our server deployment.  We may want to break out a separate router process, we may not - but preemptively re-architecting stuff doesn't seem useful.
