### ISSUE TITLE
ability to delete my account

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#23]
for testing purposes, so I can demo account creation

**Comment by lloyd** [comment]
I expect the ability to do this should be exposed on the "status" page, which should be styled the same as the rest of the site and maybe be renamed "manage"

**Comment by vthunder** [comment]
I agree, that would be a perfect place!

**Comment by benadida** [comment]
I'll work on this as a simple extension of the other work I did on manage.html

**Comment by lloyd** [comment]
gosh, it sure seems like I can close this.
