### ISSUE TITLE
use $.bind or create a wrapper for addEventListener on myfavoritebeer

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#230]
IE8 is blowing up on trying to use addEventListener on myfavoritebeer.

**Comment by lloyd** [comment]
done and live: https://github.com/lloyd/myfavoritebeer.org/commit/88f904a00cd11ddd9cea17a34badfac9c84a0fdf

make sure you flush browser cache for js/main.js

lloyd
