### ISSUE TITLE
BigTent: "Email is bad input" when using Yahoo Address on Android 4.0 default browser

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2300]
STR

1) Use Android 4.0 default browser - I am using an Asus EE Transformer
2) Browse to dev.123done.org
3) Open Persona dialog
4) Enter in a yahoo address.
5) Dialog redirects and shows "email is bad input"

![Android browser showing "email is bad input"](https://img.skitch.com/20120815-f5uqu7cdfyqxxa8j35r16fd6q9.png)

**Comment by shane-tomlinson** [comment]
Link to mozilla/browserid-bigtent#89

**Comment by jaredhirsch** [comment]
the linked bigtent issue has been closed for 4 months. please reopen if needed.
