### ISSUE TITLE
Set up dev "browserid" servers to use HTTPS to mirror prod environment

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#231]
This will help us test in an environment that more closely mirrors how BrowserID is being used in the wild.  Perhaps we just use self signed certs for the testing?

**Comment by lloyd** [comment]
maybe we should not do this and instead push to make our stuff heroku compatible?

**Comment by shane-tomlinson** [comment]
@lloyd - can we get an SSL cert on Heroku?  With the shared Joyent machines you cannot.  There were some strange bugs showing up with the IE security model that do not show up on local dev machines but only when serving up the JS using SSL.

**Comment by lloyd** [comment]
totally.  piggyback ssl is free on heroku:  https://myfavoritebeer.herokuapp.com/

here's doc: http://devcenter.heroku.com/articles/ssl

**Comment by lloyd** [comment]
this is done.
