### ISSUE TITLE
reset password flow can cause user to be locked out of account.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2314]
STR

1) Create account with two secondaries and a primary, email A, and email B.
2) Open dialog, sign out.
3) Enter email A, click "forgot password"
4) Enter in a new (make sure it is different!) password
5) Verify email address at email A's provider
6) Open dialog, sign out.
7) Enter email B.
8) Try both passwords, neither work, both show the "This email and password do not match"
9) Enter email A.
10) Try both passwords, neither work, both show the "This email and password do not match"
11) Log in with primary
12) visit main site's /primary page, both email A and email B are still in the list.

If I did not have the primary in my list of emails, I would not be able to access the account unless I did a reset password flow again.

**Comment by lloyd** [comment]
please clarify step 1?

**Comment by shane-tomlinson** [comment]
@lloyd - An account is needed that has two secondary emails and one primary email

**Comment by jrgm** [comment]
I'm probably missing something but this works fine for me (as in the new password (completed at in step 5) can be used with either email B or email A, and the old password is rejected as no longer correct).

**Comment by jrgm** [comment]
```
[13:37:05]  <stomlinson>    lloyd, jrgm: I am unable to reproduce 2314, I am wondering if I typed in a password with my caps lock on without realizing it.
```

So, I'm gonna close this issue...

**Comment by jrgm** [comment]
verified not-an-issue
