### ISSUE TITLE
Capture DB Schema and Schema changes in git

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2317]
We can improve how we manage the DB schema and how we hand off changes to Ops.

1) We should capture today's schema in git

2) We should capture changes to the schema in new files

3) If we ever adopt a schema management tool (like Django's South) it will be a develop tool, but may not actually be used by Ops .... they will still want a schema diff captured in git for the hand off.

This is because they are using MySQL Percona and other tools to manage downtime of master with alters, etc

Proposal:

```
config/db/schema_000.sql
```

File Contents:

```
CREATE TABLE IF NOT EXISTS user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    passwd CHAR(64),
    lastPasswordReset TIMESTAMP DEFAULT 0 NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS email (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user BIGINT NOT NULL,
    address VARCHAR(255) UNIQUE NOT NULL,
    type ENUM('secondary', 'primary') DEFAULT 'secondary' NOT NULL,
    verified BOOLEAN DEFAULT TRUE NOT NULL,
    FOREIGN KEY user_fkey (user) REFERENCES user(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS staged (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    secret CHAR(48) UNIQUE NOT NULL,
    new_acct BOOL NOT NULL,
    existing_user BIGINT,
    email VARCHAR(255) UNIQUE NOT NULL,
    passwd CHAR(64),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY existing_user_fkey (existing_user) REFERENCES user(id)
) ENGINE=InnoDB;
```

**Comment by jrgm** [comment]
Actually the schema are documented in lib/db/mysql.js. Calling that good enough.
