### ISSUE TITLE
[opera/winxp] "Sign Up" is clipped at the top on /signin page on transition 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2319]
STR
1) Load https://login.dev.anosrep.org/signin in Opera (I was on winxp)
2) Enter an unknown secondary email address to be prompted for password twice
3) page transitions to show this

![img](https://img.skitch.com/20120815-ub5h9ar66yxk86xbmd59sg2sf.png)

This is really more an Opera upstream issue. If you force a paint to happen, the dialog then shows without the clipping. I could even take a wontfix/upstream on this one ;-)

**Comment by jrgm** [comment]
I also see this clipping with Opera 12.01 on osx

**Comment by shane-tomlinson** [comment]
Page has been removed, closing as no longer applicable.
