### ISSUE TITLE
should /signin page always re-check address_info when deciding if known or unknown secondary email?

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2322]
Apologies up front. This is a bizarre corner case that may not ever affect a real user. (I just hit this by accident).

Anyways, seems like it could be fixed easily enough.

STR

1) In browser-1, go to https://login.dev.anosrep.org/signin
2) Enter an unknown secondary email address. Page prompts for two passwords.
   (Call to /wsapi/address_info?email=... returns {"type":"secondary","known":false})
3) Use browser-2 to actually signup the secondary email address in (2)
4) Back on the /signin page make a no-op edit to the secondary email address and click Next.
5) Page prompts for two passwords. No re-check on address-info is done.

**Comment by shane-tomlinson** [comment]
Page has been removed, closing as no longer applicable.
