### ISSUE TITLE
Text on browser id login is nearly unreadable on my machine

### ISSUE THREAD

**Issue by Mossop** [mozilla/persona#2324]
Originally filed at https://bugzilla.mozilla.org/show_bug.cgi?id=783128 where I put a screenshot for your viewing pleasure.

My machine is 64-bit Windows and I'm running Firefox nightly. It looks like the text is being over-anti-aliased or something. Most of it is readable though looks broken, some of the smaller text has so much missing that it can be a challenge to make out what the letters are.

**Comment by jrgm** [comment]
Hi, thanks for the report. We have some better fonts in the pipeline (GH-1856) that should resolve what you see. We don't have that on a staging environment at the moment but the will be available real soon now.

**Comment by jrgm** [comment]
Yeah, github doesn't have attachments for images, but you can refer to them in the text this way and get the image to appear inline with the comments, which is a pretty damn nice feature. 

```
![bug783128fonts](https://bug783128.bugzilla.mozilla.org/attachment.cgi?id=652275)
```

![bug783128fonts](https://bug783128.bugzilla.mozilla.org/attachment.cgi?id=652275)
