### ISSUE TITLE
"New to Mozilla Persona?" when signed in

### ISSUE THREAD

**Issue by peterbe** [mozilla/persona#2333]
I've I've managed to sign up it's very little I can learn from that "Learn more" link.
http://cl.ly/Inaw

Also, on my macbook the grey faint text on the yellow background is really hard to read. I like the yellow because it really caught my attention but not convinced on the contrast.

**Comment by shane-tomlinson** [comment]
Thanks for the report @peterbe - this is a dup of #2311.
