### ISSUE TITLE
P3P headers needed for IE8/some variants of IE9

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2340]
http://msdn.microsoft.com/en-us/library/ms537341%28v=vs.85%29.aspx

See #2183, #2192

**Comment by seanmonstar** [comment]
Quote from @benadida:

> In a brief conversation with Jishnu on Friday, he said he was supportive of the P3P approach that goes something like "this is not a P3P policy, but Mozilla deeply cares about your privacy, go <here> for more."

**Comment by jaredhirsch** [comment]
So we'd literally send down:

```
P3P: CP="This is not a P3P policy, but Mozilla deeply cares about your privacy. See 
http://www.mozilla.org/persona/privacy-policy for more."
```

An example of Google's workaround: http://blogs.msdn.com/b/ie/archive/2012/02/20/google-bypassing-user-privacy-settings.aspx

**Comment by shane-tomlinson** [comment]
Closing it, p3p headers are merged.
