### ISSUE TITLE
BrowserID sign-in form activates the keyboard on iOS

### ISSUE THREAD

**Issue by st3fan** [mozilla/persona#236]
When tapping on the Sign In button, or even just in the window outside of the text fields, iOS activates the iPad keyboard. Obscuring the sign in button.

This is not really cricitcal and I am not really sure what is going on here as it is difficult to debug. But somehow the WebView thinks that a input field is activated, so it pops up the keyboard. Maybe there is some javascript magic in there to deal with the form?

**Comment by shane-tomlinson** [comment]
@st3fan, I am putting the cursor programaticaly into the first form field every time the page "changes."  On a desktop browser, it felt like pretty poor usability without it.

**Comment by shane-tomlinson** [comment]
Closing as same cause of #1779, dup.
