### ISSUE TITLE
English localization not picked up unless using en-US

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2360]
When setting languages in Firefox to this:

![No en-US](https://gist.github.com/raw/3399722/ddf786054e8a5577424c8f430660907b36ae09fa/broken_headers.png)

the request to Persona includes this header:

```
Accept-Language: en-gb,en-ca;q=0.8,en-nz;q=0.7,en-au;q=0.5,en;q=0.3,fr;q=0.2
```

and the Persona screens are in French despite all of the other English locales coming before French.

On the other hand, if I do this:

![en-US](https://gist.github.com/raw/3399722/68d99f89774ba4e64048b5d470d4ead19e926d68/working_headers.png)

then the header becomes:

```
Accept-Language: en-gb,en-ca;q=0.9,en-nz;q=0.7,en-au;q=0.6,en;q=0.4,en-us;q=0.3,fr;q=0.1
```

and the dialog shows up in English.

**Comment by jrgm** [comment]
This is GH-1863. Closing as duplicate.
