### ISSUE TITLE
Not proper Forgot password window

### ISSUE THREAD

**Issue by teo951** [mozilla/persona#2371]
In the reset password window are displayed textboxes:
Password
Verify password

Why these elements are displayed? User forgot password and want reset yours password, so these elements are redundant.

**Comment by shane-tomlinson** [comment]
@teo951 - Thanks for the feedback, can you elaborate?

These two fields are for the user to reset their password.

We have changed how this works slightly. You can go to dev.123done.org and try the reset password flow there. Note, that is a development server and the user database is not connected to the one that drives the main persona.org site so you will have create a new account.

**Comment by teo951** [comment]
See attached image. This window is displayed when user click "forgot your
password?" link, not reset, so if user forgot password, how can insert
password?

Regards
Teo

2012/8/21 Shane Tomlinson notifications@github.com

**Comment by zaach** [comment]
The password fields are for creating a _new_ password, not for entering the old one (which the user forgot). This is unlike most sites which have you create a new password after you have followed a confirmation link. Issue #1232 is filed for flipping our order to be like most sites.

**Comment by lloyd** [comment]
is this a dup?

**Comment by zaach** [comment]
Yes, this is covered by other issues for changing copy and flipping order.
