### ISSUE TITLE
Some strings are not present in the last messages.po file

### ISSUE THREAD

**Issue by teo951** [mozilla/persona#2372]
I the last messages.po file strings:
# ~ msgid "New to Persona? Sign up today."
# ~ msgid "Create Account"
# ~ msgid "Existing account? Sign in."

are commented, so as translator I can remove them, but if I removed these strings, in the my language (Polish) are displayed in English.

**Comment by jrgm** [comment]
@teo951 can you try this again. translate.persontest.org has been updated. Those strings are now obsolete and have been removed from source.

**Comment by teo951** [comment]
Thanks. Now all is OK.

2012/8/24 John Morrison notifications@github.com

**Comment by jrgm** [comment]
Thanks for the original report and the followup @teo951. Closing.

**Comment by jrgm** [comment]
And thanks @zaach for digging into this.
