### ISSUE TITLE
MDN navigator.id.request privacyPolicy & termsofService docs

### ISSUE THREAD

**Issue by stenington** [mozilla/persona#2379]
https://developer.mozilla.org/en-US/docs/DOM/navigator.id.request

The parameters documentation for `privacyPolicy` and `termsOfService` say they want absolute URLs, but the example shows relative URLs and it seemed to me that relative URLs actually work better. Working locally, giving a url like `http://localhost:8000/privacy.html' resulted in an error whereas just giving it '/privacy.html' worked great.

**Comment by callahad** [comment]
Ah, right you are! I've updated the language to "Absolute path or URL" from "Absolute URL" -- thank you!
