### ISSUE TITLE
MDN "quick setup" uses less stable API

### ISSUE THREAD

**Issue by stenington** [mozilla/persona#2381]
https://developer.mozilla.org/en-US/docs/Persona/Quick_Setup

Don't know if this is a proper issue, but the _Quick Setup_ page describes the Observer API, which seems to be the less stable of the two available. I don't know if the Observer API is the preferred API, or if the Callback API will be going away... I took it to be a fairly strong endorsement that we should be using the Observer API which we then reversed later given the amount of warnings that it's still in flux. 

It would be helpful if the relationship between both styles of using the API were made clearer, along with expected lifespans, etc. If the Callback API is a viable option, it might be worth mentioning it early in the Quick Setup docs too.

**Comment by callahad** [comment]
Ah, yes. I should update the Observer API docs. The Observer API is now the recommended API for Persona.

**Comment by callahad** [comment]
Fixed! We don't anticipate any backwards incompatible changes to the Observer API in the near future, aside from renaming `loggedInEmail` to `loggedInUser`.
