### ISSUE TITLE
Re-enable siteName and siteLogo for .get()

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2382]
Last month we decided that we should support `siteName` and `siteLogo` with the `.get()` API after noticing that they were inadvertently available (#2086, #2109). This reverses a decision made in #2070.

We just need to update https://github.com/mozilla/browserid/blob/d6cf9538185623d53c87d2a0889868ec857823e8/resources/static/include_js/include.js#L1243-L1246 and add tests.

**Comment by shane-tomlinson** [comment]
Closing with the merge of #2421

**Comment by jrgm** [comment]
verified train-2012.10.12 (via beta.myfavoritebeer.org)
