### ISSUE TITLE
investigate using data: urls for images in HTML email

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2385]
I, like many people, don't show images in HTML by default. So the Persona email display in thunderbird or mobile gmail on adroid with ugly bits of extra UI to "Show images?". I'm used to that in all kinds of my email in my inboxes, and was just ignoring it as usual. 

But we could look at using `<img src="data:image/png;base64,iVBORw0K...` in the HTML email we send out. I mocked up an email, and works nicely in Thunderbird, but didn't work as nicely in mobile Gmail (didn't check others). But I probably botched something that gmail didn't like.

**Comment by seanmonstar** [comment]
Interesting. That gets around one concern: loading an image tells the
sender you opened the email. However, another concern would simply be that
you don't trust images from people you don't know. I wouldn't be surprised
if Gmail took this stance: do you want to chance seeing an image you'd
rather not if you don't trust the person?

**Comment by jaredhirsch** [comment]
I'd suggest somebody sign up for a litmus account, send an email with data URIs, and see which clients support it

**Comment by jrgm** [comment]
I'm closing this issue. While it might look nicer with data:... urls for images, @seanmonstar raises a very valid point (that you just don't want to load any (malformed, offensive) images from senders you have no prior relationship with).

If user testing/research shows a desire to do something like this, a new issue can be opened.
