### ISSUE TITLE
email associations stored in localStorage.loggedIn not removed when an email is removed from localStorage.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2389]
STR

1) Sign into an RP with account with two email addresses
2) Sign out.
3) Go to manage page "/"
4) Open up browser dev tools, look at localStorage.loggedIn[RP_origin]. The site's email is shown.

Link to #2387

**Comment by jrgm** [comment]
Hey @shane-tomlinson I see that PR-2390 is merged but this GH-2389 is still open. 

Anyways, I can't verify the STR above with FF16. Can you elaborate on the STR, or is this not actually fixed by PR-2390? (I really hate to ask this).

**Comment by shane-tomlinson** [comment]
@jrgm - this was fixed by #2390, closing.
