### ISSUE TITLE
dialog messaging ui nit when creating account with an existing address

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#239]
There is a slight visual problem when you try to create an account with an email address that already exists in the database.  Here's how you reproduce it:
1. go to myfavoritebeer.org
2. click sign in
3. click _this is not me_ if required
4. click _create a new account_
5. type in an email address that is in use and passwords
6. notice the bubble containing the message _XX@YY.com in use, If this email is yours you can sign in with it?_ overlaps a pixel or two with the bottom blue stripe.

**Comment by shane-tomlinson** [comment]
Closing as this flow no longer exists.
