### ISSUE TITLE
Confirmation screen asks "is this your computer," even when I'm on a phone

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2393]
Via krupa in IRC:

<krupa> when we show the confirm this is your device screen, shouldn't we try to be device-agnostic? It says "is this your computer?" even when i am on my phone.

@skinny97214 ?

**Comment by shane-tomlinson** [comment]
An RP that targets high school students has given me information that this screen confuses students as well. Many students think "yeah, this is my computer _right now_" and click yes.

+1 for wording changes.

**Comment by lloyd** [comment]
I think we should call it a phone, or a computer, or a tablet.  It feels so human.  Little tiny JavaScript library that encapsulates the sniffing?  whatisthis.js?

I know the simple solution is to just call it a device, but that's so cold.

-- lloyd (thumb-typing)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
