### ISSUE TITLE
gmail doesn't handle multipart/alternative email well 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2396]
I'd noticed this on mobile Gmail app (android/iphone) and assumed it was a mobile quirk. And I checked via Litmus that Gmail looked okay to them on multiple desktop OS. But my direct use of the web interface is awful. Grepping the internets says that multipart/alternative is a common problem with Gmail. We should probably disable HTML in this train, and then figure out if it's worth the rathole of HTML email issues.

Here is my plain vanilla test account when it first gets the email:

![img](https://img.skitch.com/20120825-xfuiyh7gushawi39pgrtp55f28.png)

After I click on the ellisis to show the hidden text:

![img](https://img.skitch.com/20120825-jp8dmqfbifuca6swmyxtc2myf2.png)

And now I allow images and it  still sucks. I highlight the subject line here, but it was already ugly in the first two:

![img](https://img.skitch.com/20120825-d7c5i56awjgmpgggtpa6eqnhex.png)

**Comment by seanmonstar** [comment]
Definitely agree. It only looks good if you click "Always display images", so that means that the first email will always look bad.

**Comment by klrmn** [comment]
my problem with it is not so much about showing images or not showing images, it's that if i end up with two confirmation emails (happens a lot with dev / beta sites, not so much with the 'prod' versions), the second one doesn't show the link because it is text repeated from the previous email and is therefore hidden behind the [...]

**Comment by seanmonstar** [comment]
You receive 2 when you should receive one? That sounds like a bug. Or do
you mean while testing, you need to receive a 2nd confirmation. That sounds
like just something Gmail does.

**Comment by shane-tomlinson** [comment]
@klrmn - is the problem stem from you using dev and beta both to send emails to your gmail account, with any subsequent emails being hidden?  Does the _first_ email show consistently if all other Persona confirmation emails are removed?

**Comment by lloyd** [comment]
Because this affects a small %age of users (must send self 2 emails from same site), and the HTML emails improve the world for everyone, I'm decrementing to 4 stars.

Let's get this problem understood and work around it, but go live with train-2012.08.17 regardless of this issue.

**Comment by skinny97214** [comment]
Investigate some ways to prevent gmail from collapsing. We may need to add a date/timestamp that's always unique. It'd be ideal if this was hidden since it's mostly just extra cruft the user shouldn't need to look at. 

"You requested this verification at 07:28GMT on Jan 01, 2012."

**Comment by jrgm** [comment]
I doctored up a couple of emails to make the text in the body slightly differ, and the collapsing did not occur with those messages.

**Comment by jrgm** [comment]
Oh, also, I went back to old text-only emails and they are not collapsed since the body _does_ differ with those emails due to the token. (Actually, the overall length of the token could probably be shorter).

**Comment by jrgm** [comment]
Assigning to @ryanfeeley for consideration, but pre-emptively closing this issue, if this is not of interest to improve the UX.
