### ISSUE TITLE
on a samsung galaxy tablet, I can't read the text due to userscalable=no

### ISSUE THREAD

**Issue by jmaher** [mozilla/persona#2398]
in testing marketplace apps for the testday on mobile, I was trying to login to mozilla persona and had a hard time reading.  doing my normal double tap or pinch to zoom didn't work to make the text more readable.

Please make the login process and related text more readable.

This was found on Firefox for Mobile on the Aurora channel.

**Comment by jmaher** [comment]
originally filed as https://bugzilla.mozilla.org/show_bug.cgi?id=785418

**Comment by jaredhirsch** [comment]
closing. please reopen if this is still a problem
