### ISSUE TITLE
Emails list should be scrollable

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2399]
OS: Win 7
Browser: FF 14.0.1
Client: http://train0817.123done.org/

Steps: 
1. Load http://train0817.123done.org/ in browser
2. Add >10 emails for same account
3. Observe the emails list dialog - Try to sign in an email without resizing the window

Expected:
Should be able to scroll the emails list to bring the 'Sign In'  button into view

Actual:
Emails list is not scrollable. The buttons are not visible until the window is resized.

**Comment by shane-tomlinson** [comment]
Since this particular bug requires >= 8 emails to be a problem on desktop, we have downgraded to 4*.

**Comment by shane-tomlinson** [comment]
Closing with merge of #2422
