### ISSUE TITLE
verify on myfavoritebeer uses CORS request, which IE8/9 cannot do.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#240]
@lloyd, the verify step on myfavoritebeer.org uses a CORS request to do the verification, which is causing IE to die as it doesn't support this yet.  Should we be model citizens and do the verify on myfavoritebeer's backend?

**Comment by shane-tomlinson** [comment]
This change has been checked in by @lloyd - the repo is located at https://github.com/lloyd/myfavoritebeer.org

**Comment by lloyd** [comment]
in dev and beta, works for IE8 and IE9 I'll take this into production myfavoritebeer on tuesday.

**Comment by shane-tomlinson** [comment]
@lloyd, is this now in production?

**Comment by lloyd** [comment]
no, I need to take this into production to fix IE.

**Comment by lloyd** [comment]
in production.  within 1hr DNS should be propogated and myfavoritebeer.org should be fixed for IE.
