### ISSUE TITLE
Make secondary to primary transition screen show one time only

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2404]
When we notice that a user's has a yahoo.com email address, we display a "Yahoo.com makes this easy" screen.

This is good because it informs the user that something is different and that they don't type in their Persona password anymore.

But we shouldn't this same screen every time.

Can we just display this screen once and skip this step for the second and subsequent flows?

This came up as a BigTent UX bug, but we should think about the general case.

**Comment by skinny97214** [comment]
+1

**Comment by jrgm** [comment]
So @skinny97214 says make it so... @ozten make it so!

**Comment by ozten** [comment]
I'm not currently working on mozilla/browserid, so I'm going to re-assign to @shane-tomlinson. Anyone who wants this, feel free to reassign to yourself.

**Comment by seanmonstar** [comment]
I'm on it.

**Comment by seanmonstar** [comment]
@ozten @lloyd i was making some mocks so that I wasn't fully blocked by 2686, and wondered what `state` should be if its primary, and all is well. undefined?

**Comment by seanmonstar** [comment]
With most of this working, I'm just wondering at what point should `/wsapi/complete_transition` be called? When the transition screen shown? Or once they acknowledge the transition by clicking the button?

**Comment by seanmonstar** [comment]
@lloyd @ozten when not authed, I can't call `/wsapi/complete_transition` to mark the transition completed, so it will likely need to piggyback on a call when the verification comes back positive. Is there a call that the state change should be join?

**Comment by seanmonstar** [comment]
all implentation issues are complete, so this is done
