### ISSUE TITLE
Collect JavaScript errors into a KPI

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2407]
Add a new `error` KPI, keeping track whenever a JavaScript error is thrown and not handled. We can try to take advantage of `window.onerror` to do so.

**Comment by seanmonstar** [comment]
Example http://jsfiddle.net/seanmonstar/9dTmm/

**Comment by ozten** [comment]
KPI Dashboard is not real time, nor does it have alert capabilities.

Another design to consider is to send these outside of KPI and have Node put them into statsd counters. Then we can use CEPmon or another tool to page/email based on rules.

If it's in statsd we can add to our monitoring dashboard and watch error counts after a release, etc.

**Comment by seanmonstar** [comment]
Does it make sense to add it to both? If it's a KPI, then we get the event stream, and can see most of the steps a user followed before hitting an error. And with statsd, we can get realtime alerts.

**Comment by seanmonstar** [comment]
@kparlante @shane-tomlinson how do we feel about this? should we record all errors?

The one I'm most interested in at the moment is the `errors.relaySetup` shown in #2034 when the `window.opener` can't be found. Seeing a percentage of how many users this affects would help me prioritize the bug. Would it be worth opening a single issue for that? Or do we want to collect them all? Pokemon?

**Comment by shane-tomlinson** [comment]
@seanmonstar - I would be interested in seeing the number of "unsupported dialog" messages we get as well as why, but like you said, that is probably best in a standalone bug. This bug is specific to JS errors.

**Comment by seanmonstar** [comment]
@shane-tomlinson I created #3302 for that specific error.

Still, is this worth pursuing? We claimed its only 3-star, but it seems pretty important to know when the dialog hits an error... Maybe just not in KPI?

**Comment by kparlante** [comment]
@seanmonstar I don't think KPI is the right place for collecting all errors generally. Perhaps specific cases where we know the event stream or other context will be important to track down a potentially significant problem (as you've identified above). As a more general mechanism, statsd/monitoring seems like a good approach, as @ozten proposed. Looking at the data, we're certainly losing people, so seems like a good idea to proactively get information about errors one way or another.

**Comment by shane-tomlinson** [comment]
@seanmonstar, @kparlante - agreed w.r.t. JS errors. The Popcorn Maker team came up with a hot JS error reporting library, I wonder if we can make use of any of it.

**Comment by ozten** [comment]
I don't think KPI should be used for error reporting. We should only collect anonymous usage data that we need to make product decisions and evaluate features.

@shane-tomlinson I like the idea of a separate error reporting system. That one or webdev has several others too.

**Comment by seanmonstar** [comment]
ok, so not to report all general errors. It **does** seem valid to report when a user hits an error screen (when we call renderError), as that can help us understand when our product directs a user to a screen we wish they hadn't seen.

**Comment by shane-tomlinson** [comment]
@seanmonstar - "screen.error" is reported in the event stream when an error screen is displayed to the user.

**Comment by kparlante** [comment]
@shane-tomlinson, @seanmonstar, @lloyd: while I had the map/reduce interface up, I checked out `screen.error`s on production. About 3% of the blobs had errors in them. A random sampling of those blobs here: https://id.etherpad.mozilla.org/kpi-issue-2407-data

**Comment by seanmonstar** [comment]
@shane-tomlinson yep, that was tracked in #3302 .

When it says "screen.error." with a trailing dot, it was trying to match the error screen to one in `BrowserID.Errors` and failed, probably because that error screen used a custom object instead of taking one from `BrowserID.Errors`.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
