### ISSUE TITLE
Make link to team blog more visible on login.persona.org

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2409]
The plain "By the Identity Team @ Mozilla" text in the https://login.persona.org/ footer actually contains two links! "Identity Team" goes to our blog, and "Mozilla" goes to Mozilla.

But they're completely indistinguishable from plain text. We should style those links differently, and/or have some nice, user-visible link to our blog from login.persona.org.

**Comment by skinny97214** [comment]
I'm not sure we can fix this issue without departing from the Sandstone style... @callahad

**Comment by callahad** [comment]
Two issues:
1. Can't tell links are links. Possibly a bug with sandstone? Where should I file that?
2. No prominent way to get to our blog. Probably fixable within sandstone?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
