### ISSUE TITLE
Add humans.txt (or CONTRIBUTORS)

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2411]
We could add a [humans.txt](http://humanstxt.org) or CONTRIBUTORS file to the repo, giving credit to the people that have worked on browserid.

**Comment by ozten** [comment]
+1

Also QA, Ops, UX, PM, etc.

**Comment by lloyd** [comment]
What some people do is use the built in github features, because they are zero maintenance.  i.e.
https://github.com/mozilla/browserid/graphs/contributors

**Comment by lloyd** [comment]
lets update the readme to call out the code contributors and if needed any other groups of people not represented in github's list

**Comment by seanmonstar** [comment]
An example for GitHub itself: https://github.com/humans.txt

**Comment by callahad** [comment]
@seanmonstar -- can I reassign this to you? You've got more of a grasp of what you want to see from this :)

**Comment by seanmonstar** [comment]
@callahad sure. do i make https://login.persona.org/humans.txt ?

**Comment by callahad** [comment]
Yep -- go for it. Also add a footer to the readme pointing to it the humans.txt?

**Comment by seanmonstar** [comment]
I grabbed all the emails from the `git log`, but that only includes people who have contributed commits. How should I collect who else to add?

https://github.com/seanmonstar/browserid/commit/c27b04e4f4b4c9e405f1abff66ac559e68a35726
