### ISSUE TITLE
KPI Dashboard - Enable opt-out via http cookie or similar mechanism

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2412]
Per the [Principle Real Choice](https://wiki.mozilla.org/Privacy/Reviews/KPI_Backend#Principle:_Real_Choice) the privacy team is requesting that we enable opt-out via http cookie or similar mechanism.

We'll want to add this feature to the account management screen of login.persona.org.

We must persist this (probably in a new db column) so that opt out is across devices.

We should use local storage or another mechanism to avoid sending KPI blobs for users which are in a logged out state, but which we know from pervious interactions that they have opt-ed out. For shared devices, it's probably okay if we block the whole device for the one account which opts out (per account would be preferred of course).

**Comment by lloyd** [comment]
we need to revisit this, the belief is that an option does not provide users Real Choice, and in facts distracts them from what matters.  Anonymous website analytics are different from tracking non-anonymous behavior across sites.  We're doing the former.

**Comment by ozten** [comment]
Via Email (from before I filed this bug) 

Sid Stamm says:

```
I updated the page accordingly.

One thing concerns me:

"(ozten) While working with the user data saftey group, we worked hard
with UX to try to find a way to provide an opt-out. We are unable to
find a solution. We're collecting less data than the web analytics
packages used on many Mozilla web properties; these packages also offer
no opt-out mechanism. "

So... can you create a link from the privacy policy page to a page that
sets an "opt out" cookie?  Then refrain from logging stuff when this
cookie is set.

Because other systems don't have opt outs absolutely does NOT mean it is
best practice.  Users who have to stop using the system if they don't
want to provide this data (data that is not directly required for the
functionality we give them) do not get a real choice.

Action items:
* File bug to explore adding an opt-out.
* Add links to wiki page where requested (should be self-explanatory,
ask me if you're not sure)


-Sid
```

**Comment by skinny97214** [comment]
I'm very interested in finding ways to keep 100% of our users safe by only collecting data that is anonymous, not just the 1% that opt out of our data collection entirely. 

Is there a matrix of the data that shows the scale of danger and sets appropriate protocols for each? I want to make sure our response is appropriate to the level of the threat. For example, what are our policies for analytics data for sites such as mozilla.com?

**Comment by sidstamm** [comment]
Users may have a different "scale of danger" matrix than we do, and no matter what we decide, some users will disagree with our classification of what's safe and what's not.  So I'd like an opt out.  It doesn't have to be front-and-center, but it should provide users the ability to say "no" to us collecting their data if they really want.  Otherwise they have to choose between using Persona and opting-out (which is not a real choice).

This project is different than most of our web sites (like mozilla.com) since people may be attempting to log into a third party site (not a Mozilla property) using Persona, and might not explicitly trust us.  We shouldn't require users of that third party site to stop using it just because we don't offer an opt-out.

**Comment by ozten** [comment]
In discussions outside of this bug:

1) We need this data to provide a quality fallback service
2) Users can "opt out" by using:
  a) a primary instead of our secondary
  b) a native implementation instead of our shim

We've all agreed we've explored this territory fully and feel comfortable closing this issue.
