### ISSUE TITLE
consolidate github and mozilla wiki post-beta 1

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2413]

**Comment by callahad** [comment]
Could you tell me more about what you're thinking?

GitHub Wiki seems like a good place for things for core devs, while WikiMo seems like a good place for product management.

**Comment by Brigit** [comment]
Currently, it seems difficult - at least to the newbie - to know where everything is and how it relates to bugs, etc.  It would nice to have some sort of centralized hub of sorts.  _6a68 is that what you were thinking?

**Comment by jaredhirsch** [comment]
Yeah, what @toxborrow said. I'm not too particular about where we put various things, but we absolutely need one canonical list of links to all the different artifacts the team has created and maintains. It's also important that every individual document carry a link back to that topmost registry, maybe in the footer of the page.

@callahad if this is something you're already working on, feel free to close out.

**Comment by callahad** [comment]
I think the documentation goal is:
- **RP & IdP Docs**: MDN
- **User Docs**: SuMo
- **Core Dev Docs**: GitHub and Mozpad
- **Product & Project Management**: WikiMo

And for communication:
- **RP and IdP**: persona-notices
- **Core Dev**: dev-identity and #identity
- **PR**: team blog

Does that organization sound good? Can you suggest improvements or do you see any areas where we're not putting the right things in the right places?

**Comment by jaredhirsch** [comment]
@callahad: that sounds great. I'd suggest we should be sure that there is exactly one place that says exactly what you said in your last comment, and I'd also suggest we make sure each individual site's top-level page links back to the main page.

**Comment by callahad** [comment]
I'll start by making a proper landing page for the Wiki with "trailheads" on it. I'm not sure linking everything to the hub makes sense -- well, really just the SuMo stuff. Something feels weird about having end-user support point off to developer APIs...

**Comment by jaredhirsch** [comment]
MDN wiki really does look great, but this never got closed. closing
