### ISSUE TITLE
Provide a way for users to connect using their own Persona server

### ISSUE THREAD

**Issue by AntoineTurmel** [mozilla/persona#2417]
Like OpenID and Firefox Sync, I would like a Persona login button to allow me connecting either on Mozilla persona.org or my own persona installation.

**Comment by callahad** [comment]
You can already set up your own domain to be a Persona "Identity Provider," as per the docs on https://developer.mozilla.org/en-US/docs/Persona

The UI for picking an address will still be hosted at login.persona.org, but that will change once browsers add native support for Persona's `navigator.id` API.

Does that cover what you're wanting to do?

**Comment by AntoineTurmel** [comment]
Yep, and will custom Identity Provider login will be provided in Mozilla websites before other browsers add native support ?

**Comment by callahad** [comment]
Yep! If you set up your own Identity Provider (IdP), it will work today, even in browsers without native support.

If you do build your own IdP, please let me know! I love to keep in contact with people implementing the various parts of Persona. You should also join the [persona-notices](https://mail.mozilla.org/listinfo/persona-notices) mailing list, in case we make any backwards incompatible changes to the IdP API.

**Comment by ozten** [comment]
Hello again @GeekShadow ! If you are okay hosting node code, try https://github.com/ozten/hostedpersona
