### ISSUE TITLE
Forwarding email address is slow....maybe doesn't send confirmation

### ISSUE THREAD

**Issue by MarkTraceur** [mozilla/persona#2425]
After asking about this project some time ago, I recently tried signing up to be represented on Persona.

I use a member.fsf.org email for most of my business, which is sent to the FSF servers first, and then to another email address that is "normal", i.e., it uses IMAP and accepts headers and whatever else have you.

When signing up with member.fsf.org, I did not receive an email for confirmation for many minutes. When using my riseup.net address, I got it within seconds.

I'm not familiar enough with the code base to say exactly what the trouble may be. Some possibilities:
- Weird email checking prevents subdomains (but that seems wrong, else mail._._ wouldn't work, and you would have heard about this already)
- Headers that you send are not understood by the forwarding server, slowing down the process
- You try to ping the mail server first for some unknown reason, but it gives you funny responses and that means a slower send-out time
- The FSF forwarding server is slow (I tested and got mail within 8 seconds or so, so this seems unlikely)

If any further testing is needed, I wound up not using my fsf.org address as my account, so I could try signing up again.

Thanks!

**Comment by MarkTraceur** [comment]
Oh, it should be said, though I signed up twice with the member.fsf.org address (thinking the first try failed), I may have received only one confirmation. This may be _cough_ clever _cough_ caching/mistake-preventing behavior that is intentional, but it seems the line may be a bit fuzzy there.

**Comment by jrgm** [comment]
Do you have the smtp headers for the email that was slow in delivery? Could you share them privately?

**Comment by jrgm** [comment]
Closing, a bit old now. @MarkTraceur if you still have this issue, could you share the SMTP headers with me? Thanks.

**Comment by MarkTraceur** [comment]
By what method?
