### ISSUE TITLE
rework popup identification in bidpom

### ISSUE THREAD

**Issue by klrmn** [mozilla/persona#2429]
from @davehunt via email:

BIDPOM currently cycles through the open windows until it finds out with the appropriate page title. This is a little more fragile than I'd like as the page title should be able to change without affecting the tests (and the page title is different in each locale). Since https://github.com/mozilla/browserid/issues/1023 has been fixed we can improve BIDPOM by referencing the popup window by name "__persona_dialog". Leah: this would certainly be a worthwhile enhancement if you'd like to take it.

**Comment by klrmn** [comment]
https://github.com/mozilla/browserid/pull/2434

**Comment by jaredhirsch** [comment]
@klrmn: thanks for filing the bug and the pull request to fix it!

Just a procedural note - to keep issues up to date, I'll close tickets right when I merge in pull requests.
