### ISSUE TITLE
provide a BIDPOM method that logs on whether you are returning or not

### ISSUE THREAD

**Issue by klrmn** [mozilla/persona#2430]
bidpom's methods currently expect the script to tell it whether you are a returning user or not, but some of the WebDriver implementations (IE, Android) do not provide clean profiles, so the first time you log in you're new, and the second time, you're returning.

**Comment by jaredhirsch** [comment]
we're moving from python selenium to node selenium; closing accordingly.

if this is still a desired feature, please reopen against mozilla/bidpom.
