### ISSUE TITLE
either fix www.123done.org to get include.js from browserid.org or fix run and run_sauce scripts to not point to www

### ISSUE THREAD

**Issue by klrmn** [mozilla/persona#2432]
klrmn
_6a68: whee! i can't test the merging of bidpom master into bidpom production because http://www.123done.org/ spins forever instead of giving the login button

_6a68
klrmn: give it a few, try again?

klrmn
it seems to be working better with 123done.org than www.123done.org

_6a68
huh

klrmn
interesting, doncahthink? dns entries whacky  maybe?
nope, ping resolves both of them to the same address
so maybe some other configuration thing on the server?

_6a68
klrmn: yeah, it looks like www.123done is trying to fetch the include.js snippet from www.personatest.org, while 123done fetches it from browserid.org.
klrmn: so it looks like the latter (no www) is what we should actually use to test against production

klrmn
_6a68: that means the run.py and run_sauce scripts need to be changed…they assume www

**Comment by jrgm** [comment]
The trick is here - https://github.com/mozilla/123done/blob/master/retarget.js#L17

But I'd prefer fixing the the run\* scripts to adding support for www.123done.org as an unneeded alias to 123done.org.

**Comment by jrgm** [comment]
-> @6a68 to pick a fix and fix it.

**Comment by jaredhirsch** [comment]
added to the list of todos in the test-automation-spec etherpad. closing.
