### ISSUE TITLE
We need a deprecation plan that we can announce with Beta 1

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2436]
Assigning to @fmarier to wrap up since he came up with a [great initial plan](https://etherpad.mozilla.org/VCEhszkXV6).

We need to commit to supporting our API, as it is documented, upon releasing Beta 1.

For RPs, this means committing to:
1. **id.watch()**: with loggedInUser, onlogin, and onlogout.
2. **id.logout()**: without any parameters.
3. **id.request()**: with oncancel, privacyPolicy, termsOfService, returnTo, siteName, and siteLogo.
4. **id.get()**: with privacyPolicy, termsOfService, siteName, and siteLogo.

The following are already undocumented or documented as deprecated. They may be deprecated more rapidly:
1. **id.getVerifiedEmail()**: in its entirety.
2. **id.watch()**: with loggedInEmail and onready.
3. **id.request()**: with privacyURL and tosURL.
4. **id.logout()**: with a callback as its first parameter.
5. **id.get()**: with requiredEmail, silent, privacyURL, and tosURL.

The following appear to have already been removed:
1. **id.get()**: with allowPersistent.
2. **id.sessions**: in its entirety.

Because many organizations are on annual upgrade cycles, such as schools using Mahara, we need to be able to provide at least one year of warning before making backwards incompatible change to items in the first group.

**Comment by callahad** [comment]
Also: Should we _only_ commit to API stability for RPs in Beta 1? We can add IdPs in Beta 2?

**Comment by callahad** [comment]
Posted to the mailing list: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/1957

**Comment by fmarier** [comment]
@callahad Do you think we have enough 3rd-party uptake on the IdP side to feel confident that the API is reasonable? I personally get the feeling that most Persona adopters are RPs at the moment (which is not a bad thing in itself).

Also, it might be good to explore DNS-based delegation (GH-1523) before we commit to keeping that API stable.

**Comment by callahad** [comment]
@fmarier I'm not completely confident in the IdP API -- especially given the issue #2339. Beta 2 will have a strong focus on IdPs, so I think it makes sense to stabilize that API then.

In my mind I see the following beta-worthy milestones:
1. RPs can ship with Persona.
2. IdPs can add support for Persona.
3. Data formats are stable, so RPs can do local verification.
4. Core API is stable, so RPs can self-host include.js and only upgrade when they want new features.

**Comment by benadida** [comment]
I like the RP plan.

Regarding IdP, agree to push back commitment to at least Beta 2, maybe later depending on feedback.

**Comment by callahad** [comment]
Closing this down -- the plan is a 6 month minimum notice for stable RP-facing APIs, with possible extension for another 6 months depending on feedback / metrics.
