### ISSUE TITLE
statsd module should log uncaught exceptions

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2440]
We register only 1 uncaughtexception handle, in lib/statsd.js.

This handler currently talks to statsd to record an exception. In some cases, nothing is logged so the server silently falls over.

We should also log an error right after talking to statsd.

**Comment by ozten** [comment]
[Pull Request](https://github.com/mozilla/browserid/pull/2449)

**Comment by lloyd** [comment]
marking this as closed
