### ISSUE TITLE
Client gets into a funky state where there are no email addresses listed

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#2441]
Luciana told me today that BrowserID wasn't working for her. When she showed me what happened when she clicked sign in on a BrowserID site, it was obviously wrong. I didn't take a screenshot, but it looked like the "signed in" popup state (showing the "add another email" and "this is not me" buttons). However, there were _no_ email addresses listed.

Luciana would click "sign in" on the popup, and then she would be prompted to enter an email address, then apparently tell her to check her email. But she says she never got the emails.

I had her click "this is not me" (=log out) and then try again, and she was correctly prompted for her password and could sign in. Signing out of the site and clicking sign in again correctly lists her email addresses to choose from.

So, I'm not sure how she got into that state, but we should a) try to track that down and prevent it, and b) maybe add some sanity check(s) and automatically trigger a logout if we detect something is broken.

**Comment by jrgm** [comment]
This sounds similar to GH-1472 and there are STR there and on previous duplicates. 

One part I don't understand here is that when in this state, clicking on sign in (for me) throws up an alert that says "The selected email is invalid or has been deleted". I'm also not sure what to say about the email delivery. Did Luciana _ever_ get the emails? Also does Luciana recall if she changed her password or made other modifications to her account on a second computer or browser? e.g., a home computer !== her office system.

Largely this is a duplicate and we should fix this soon, but I'm just curious about the above before calling this a dup.

**Comment by jrgm** [comment]
Okay, I spoke with Luciana about the questions I had. Marking dup on GH-1472
