### ISSUE TITLE
Bugzilla does not remember my Persona logon

### ISSUE THREAD

**Issue by renatosilva** [mozilla/persona#2446]
When I sign on to https://bugzilla.mozilla.org using Persona and then restart Firefox, it will ask me to log in again, even though it is configured to remember everything. I need to always go to the Persona pop-up then click to enter every time I restart Firefox. The only way to make it work is by setting "When Firefox starts" to "show my windows and tabs from last time'", however I use start page option instead.

**Comment by jrgm** [comment]
When authenticating to b.m.o with persona it issues session scoped login cookies from bugzilla.mozilla.org. If you authenticate using username + password, cookie expiry is set to year 2038. 

So on restart when authed with persona you have to pop the dialog again which is a nuisance, but a restart with username+password just let's you back in automatically. Is this a policy decision for the b.m.o RP integration, or unintended?  @gerv?

**Comment by gerv** [comment]
@jrgm: I did not consider cookie lifetime specifically when designing the integration, so I'd have to say it was unintended. That doesn't mean it's the wrong decision, of course :-) Please file a bug in BMO in the "bugzilla.mozilla.org" product to cover this issue, and assign it to me in the first instance.

Gerv

**Comment by lloyd** [comment]
thanks for chiming in @gerv - please let us know how we can help, people have been complaining about session duration on bugzilla and you have full access to any of the team to get this fixed!

@jrgm will make a bugzilla ticket

**Comment by jrgm** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=791035 - Cookie lifetime should extend beyond session when authenticated via Persona login
