### ISSUE TITLE
Opera account manager "Remove" button has wrong background

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2457]
The "Remove" button in the account manager is styled wrong:

![Account manager in Opera 12.50](http://new.tinygrab.com/31dd25712bfb59a4c75216068ef31abe741f2f80c2.png)

Specifically, none of the `button.delete` styles are getting a `background-image` set in Opera, while the normal `button` styles are. The obvious difference is that the `button` styles use `-webkit-linear-gradient`, which Opera understands and uses as per its inspector, while `.button.delete` uses `-webkit-gradient`.

**Comment by jrgm** [comment]
I get '-o-linear-gradient'. Huh?

![img](https://img.skitch.com/20120911-ndgsbafa1d4wwsrk2w89cdyssi.png)

**Comment by callahad** [comment]
This is apparently a change in the upcoming 12.50 release. As per [this blog post](http://my.opera.com/ODIN/blog/2012/08/10/css-vendor-prefixes-in-opera-12-50-snapshots) (emphasis mine):

> The latest CSS Gradients syntax is supported in Opera with no prefix. **Using an -o- will no longer work,** so if your CSS still has some -o-linear-gradient hanging around, you should start to include the unprefixed version as well.

So.. we need to add un-prefixed gradients to our stylesheets. This is only working at all in 12.50 by virtue of Opera implementing `-webkit-linear-gradient`.

MDN [suggests](https://developer.mozilla.org/en-US/docs/CSS/linear-gradient#Cross-browser_gradients) `-webkit-`, `-moz-`, `-ms-`, `-o-`, and unprefixed as the appropriate order.
