### ISSUE TITLE
clicking 'sign up' on anosrep.org goes to 'sign in' page, not 'create acct' page

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2458]
go to anosrep.org, click 'sign up'
in the existing site, you're taken to login.persona.org/signup. 
in the staging site, you're taken to login.anosrep.org/signin.

**Comment by jrgm** [comment]
"It's a feature!"

**Comment by seanmonstar** [comment]
Yea, that's working as intended. We merged the Sign In and Sign Up pages into one.
