### ISSUE TITLE
after sign up on anosrep.org, confirmation page header says 'sign in', not 'sign out'

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2459]
go through sign up flow with a secondary email on anosrep.org:
- click 'sign up'
- enter new secondary email
- enter password
- grab verification link from email
- enter verification link
- resulting success page says 'thank you for signing up', but the header has a 'sign in' link.

I'd expect the header to say 'sign out' at this point.

If I click 'sign in' there are a couple funky redirects, landing at the account manager page with 'sign out' correctly displayed in the header.

did this on IE8 and FF nightly, not a platform specific thing

**Comment by jrgm** [comment]
Actually, this is fixed in current login.dev.anosrep.org. See GH-2424
