### ISSUE TITLE
IE8: on acct mgr page, changing password, then back to old password causes ugly fail

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2460]
broken on IE8/XP
not broken on IE9/win 7, IE9/vista, or Chrome/Mac
- sign in to a secondary-based account on anosrep.org
- change to a new password in the account manager
- immediately change back to the old password
- the password does update, but the page freezes with a horrible error message

screenshot: http://imgur.com/Uj0n8

error message text: 

We are very sorry. There has been an error! 
Please close this window and try again. 

See more info 
Action: Updating password 
Network Info: POST: /wsapi/update_password 
Response Code - 12152

**Comment by jrgm** [comment]
I can't reproduce this with IE8/XP. What exactly do you mean by "immediately change back to the old password". Do you just mean to use the dialog twice changing password foo to bar, and then bar to foo?

**Comment by jaredhirsch** [comment]
hmm, what I mean is: you're on the account manager page. you change passwords. then, without reloading the page, you change them back. so the exact sequence would be:

sign in --> land on acct mgr page
click change password --> old/new password inputs appear
enter old & new passwords, hit submit --> form disappears
without reloading the page, click change password again --> inputs appear again
enter passwords, replacing new one with old one, hit submit --> form disappears, page freezes, after a few seconds displays error lightbox

helpful? if it's still unclear, I can screencast it maybe

**Comment by jrgm** [comment]
Hmm, I don't see this happening in my IE8. 8.0.6001.18702

**Comment by jaredhirsch** [comment]
I have the exact same version of IE8...and cannot currently repro this, either. Closing.
