### ISSUE TITLE
funky product asymmetry: can only add addresses in dialog, can only remove addresses in acct manager

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2461]
inside the dialog, it's possible to add email addresses, but not remove them.

at the account manager page, if you click 'edit', you can remove addresses, but not add them.

would be cool to provide the full range of behavior on the acct manager page.

adding 'remove this email' functionality within the dialog seems debatable.

**Comment by shane-tomlinson** [comment]
Closing as a dup of #421.
