### ISSUE TITLE
Site information

### ISSUE THREAD

**Issue by satdav** [mozilla/persona#2464]
Hello their possible site issue 

can you make the following text stand out better 

 New to Mozilla Persona? Learn more as hard to read with the dark background

**Comment by lloyd** [comment]
skinny to improve font color choices.

**Comment by skinny97214** [comment]
Make background white and the font the default blue.

**Comment by satdav** [comment]
that sounds good crystal

**Comment by jrgm** [comment]
We redirect to another page, the account management view now. So this issue is not applicable anymore. Closing.
