### ISSUE TITLE
after sucessful new user creation on persona server, confirm page should redirect to home page

### ISSUE THREAD

**Issue by klrmn** [mozilla/persona#2465]
open login.anosrep.org
click sign-up
provide (new) email and password
fetch link from email
open link in same browser

expected:
redirect to https://login.anosrep.org/ (after 5 seconds?)

actual:
no redirect. 
stuck on https://login.anosrep.org/verify_email_address?token=TOeFZCjarrJwRBBDwkzp82ZPST3SY2sEmol8ZqMNbY0pYPPs

**Comment by shane-tomlinson** [comment]
Link to #2388

**Comment by shane-tomlinson** [comment]
Check if taken care of with #2424

**Comment by shane-tomlinson** [comment]
Reading my own comments in #2424, this IS taken care of. Closing.

**Comment by jrgm** [comment]
verified for current dev (what will be train-2012.10.12).
