### ISSUE TITLE
Recapcha

### ISSUE THREAD

**Issue by satdav** [mozilla/persona#2466]
Hi can i suggest you enable recapcha on the system for people to login and register 

would be good and might stop spam in the long run

Recapcha is good it stops all kinds of spams

**Comment by callahad** [comment]
Hi @satdav, thanks for the enhancement suggestion! I don't think recaptcha makes sense for Persona, especially given its distributed nature: any domain can certify its own users. In the absence of evidence of actual spam issues related to Persona, I'm going to close this ticket for now.

Thanks again!
