### ISSUE TITLE
browserid/static/include.js: if message is not in JSON-string format

### ISSUE THREAD

**Issue by polymorphm** [mozilla/persona#247]
good day!

now: if message (window 'message' event) is not in JSON-string format -- then www-browser show error in console

but messages ( window.postMessage() ) may be not related with BrowserID-system , in this case -- this-alien-errors are unpleasantly interfere _(please, sorry my vary bad english :))_

i think will be nice -- do something like in this example: https://gist.github.com/1200224

thanks in advance!

**Comment by shane-tomlinson** [comment]
@polymorphm - ahhh, that is a very good catch, thanks for that.  I am going to have a chat with the original author of the Channel library and find out what we can do to address this.  Your proposed fix looks good, I just want to make sure that I do not introduce any side effects!

**Comment by shane-tomlinson** [comment]
@polymorphm - your suggestion was merged into WinChan, this is now taken care of.  Closing!
