### ISSUE TITLE
Persona password cannot be saved in Firefox password manager

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2470]
I searched for this and couldn't find an existing bug, so it must be in the too-obvious-to-file-a-bug category.

Nevertheless, it's a real pain point for many users (lots of users of bugzilla.mozilla.org prefer to sign-in w/o Persona so that their browser can save their credentials) and may lead to people picking a less secure password.

**Comment by jrgm** [comment]
Yeah, so github's problems today seem to have broken searches for issues before today. I'm sure it will be restored later. 

But I had been toying around with stuff and I have a mongo clone of the github issues and from that this is GH-314 and also https://github.com/mozilla/browserid/issues/1076#issuecomment-3879333. So, this is indeed a major pain point that we should fix (but IMHO it's an upstream issue). 

Closing as dup of GH-314. Ugh.
