### ISSUE TITLE
Stage is redirecting static.login.anosrep.org to login.anosrep.org 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2476]
Stage is redirecting static.login.anosrep.org to login.anosrep.org

On stage, at the moment, URLs like below are being returned a 301 response which is wrong:

https://static.login.anosrep.org/v/ad5ad4541d/pages/i/slit.png
https://static.login.anosrep.org/v/53e7265f01/production/en_US/browserid.js
https://static.login.anosrep.org/v/ad5ad4541d/pages/i/slit.png

/cc @gene1wood, @fmarier , @lloyd

**Comment by lloyd** [comment]
these 301s do not seem present on dev.  nor on production.  I agree that this seems like zeus.

**Comment by gene1wood** [comment]
I've rolled back staging to the current production zeus rules

**Comment by jrgm** [comment]
Confirmed that those requests are now 200 OK in stage.

**Comment by fmarier** [comment]
I have added a new test for this in [my fork](https://github.com/fmarier/checkurl) of the `check-url` script:

  https://github.com/fmarier/checkurl/commit/e1f46a3609f27222c14098d12447a909c5aad318
