### ISSUE TITLE
adjust selenium tests to use primary flow

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2477]
bigtent is now allowing gmail to be treated as a primary, not secondary, IdP, so that two of the 123done tests are busted.

@klrmn mentioned she has code to fix this, just opening this issue as a temporary placeholder

**Comment by klrmn** [comment]
I don't have the code yet, but I know what needs doing. We just need to
decide if it's happening within the current test organization, or as part
of the test re-org.

**Comment by klrmn** [comment]
the code now exists on my fork/branch at https://github.com/klrmn/browserid/blob/new_organization/automation-tests/tests/test_login_logout.py (and supporting files)

**Comment by lloyd** [comment]
placeholder issue no longer needed, @jrgm and @_6a68 have plans that cover this
