### ISSUE TITLE
add a .jshintrc file

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2478]
Our guidelines demand we run jshint before push code (on save is even better), but jshint allows us to declare different rules on each computer.

We have a few jshint settings hiding in the comments at the top of files, so why not just include a [root level `.jshintrc`](https://github.com/jshint/node-jshint/#within-your-projects-directory-tree).

**Comment by shane-tomlinson** [comment]
Here is what I am using, which I am sure can be cleaned up/added to:

```
{
    "passfail": false,
    "maxerr": 100,
    "browser": true,
    "node": true,
    "forin": false,
    "boss": true,
    "noarg": true,
    "undef": true,
    "browser": true,
    "laxbreak": true,
    "laxcomma": true,
    "expr": true,
    "predef": [
      "exports", 
      "require",
      "BrowserID",
      "_",
      "$",
      "jQuery",
      "ok",
      "equal",
      "strictEqual",
      "notEqual",
      "start",
      "stop",
      "asyncTest",
      "test",
      "raises"
    ],
    "es5": true,
    "shadow": false,
    "supernew": false
}


```

**Comment by seanmonstar** [comment]
I wonder if we should have maybe 2 or three, specifically for the `predef` field. I'd rather it only think that a global `ok` or `start` etc would only be true when modifying the test suite.

**Comment by shane-tomlinson** [comment]
Agreed, I also have es5 enabled for when I was doing extension development. Not cool for Persona.

**Comment by seanmonstar** [comment]
I looked into a little, and what I was hoping for doesn't work. JSHint does not recursively apply `.jshintrc` files. So, if we had 3 or 4 (node, browser, test suites), they would need to contain duplicate rules, and changes would potentially require changing all of them.

At the same time, I don't think we would change our linting rules very often, if ever. And we could always hope that reviewers would be a 2nd person to remember that we have multiple rcs. Do it anyways?

**Comment by zaach** [comment]
@seanmonstar I agree, I don't think the linting rules will change very often once we nail them down.

One other issue besides different predefined globals is mixed coding styles. Common linting rules will help us converge, though more generally it might be good to adopt a style guide.

**Comment by shane-tomlinson** [comment]
@zaach, @seanmonstar - there is a general Mozilla guideline - https://developer.mozilla.org/en-US/docs/Developer_Guide/Coding_Style.

We have adopted an unofficial policy of:
- no trailing whitespaces
- spaces instead of tabs, 2 spaces per "tab"/indent level
- space between if and (, for and ( - `if (` and `for (`
- { on same line as control statement
- single line `if(..) statement()` are allowed

Probably more that I'm not thinking of.

We have no variable naming convention yet.

**Comment by seanmonstar** [comment]
Don't forget the JavaScript style guide WebDev (cough I cough) put together: http://mozweb.readthedocs.org/en/latest/js-style.html
