### ISSUE TITLE
favicon.ico does not have an expires header set

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2482]
This is giving us a Grade B on Add Expires headers in YSlow

**Comment by jrgm** [comment]
There's a small problem with https://github.com/mozilla/browserid/pull/3578, in that /favicon.ico is now served with 
`Cache-Control: public, max-age=31536000` which is one year. 

Thoughts? @ryanfeeley, is this ok?

**Comment by shane-tomlinson** [comment]
@jrgm - we are now cachifying this, so the URL will be updated any time favicon is changed. Are you seeing something different?

**Comment by jrgm** [comment]
Brain cramp. Closing.

**Comment by jrgm** [comment]
Brain cramp. Closing.
