### ISSUE TITLE
Marketplace app does not remember my login

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#2491]
Migration of https://bugzilla.mozilla.org/show_bug.cgi?id=785572 to browser ID github repository.

Not sure if this is on purpose but I have to go through the Persona login every time I start the Mozilla Marketplace application. I did go through Persona both with and without the 'Is this your computer, yes remember me for 2 weeks' screen.

**Comment by seanmonstar** [comment]
@jds2501 When you click the login button, do you have to enter your email and password into Persona. or has the Persona screen remembered you?

**Comment by jrgm** [comment]
@seanmonstar : @jds2501 was just transferring the bug report from bugzilla. @st3fan (Stefan Arentz) is the original reporter.

**Comment by lloyd** [comment]
this issue should be taken to marketplace as they completely control the session, and we expose different tools to help them manage it.  

I don't believe this is our bug, but we're extremely willing to diagnose the issue in marketplace and support them.  @jrgm can you take lead.

**Comment by jds2501** [comment]
Okay, I'll close this and move the bugzilla bug over to marketplace and reopen it. Thanks for info.
