### ISSUE TITLE
persona.org claims it has already sent an e-mail

### ISSUE THREAD

**Issue by tessarakt** [mozilla/persona#2498]
On developer.mozilla.org, I click on "Sign in".

A persona.org window opens. It already knows my address ich@tessarakt.de.

I click on "Eine weitere E-Mail-Adresse hinzufügen" (add another e-mail address).

I enter blog@tessarakt.de and click "Hinzufügen" (Add).

A red box appears, saying " Wir haben gerade eine E-Mail an diese Adresse verschickt! Wenn Sie wirklich noch eine senden möchten, warten Sie ein oder zwei Minuten und versuchen Sie es dann erneut." ("We have just sent an e-mail to this address. If you really want to send another one, wait one or two minutes and try again.")

No e-mail was sent. Retrying after "one or two minutes" (why don't you have a more exact value?!) yields exactly the same message in a red box.

**Comment by lloyd** [comment]
we should audit email throttling code, and inspect the record in the stage table to figure out what's going on here.

**Comment by zaach** [comment]
This seems unrelated to #1677, which involves an account with a primary and secondary address. These addresses are from the same domain.

**Comment by jrgm** [comment]
This seems to old to take further action. Closing.
