### ISSUE TITLE
remove eval from l10n workflow

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2501]
currently compile-json.sh generates a javascript file with a .json suffix and consuming code eval it.  this is silly.  generation code should generate json and consuming code should json.parse.

**Comment by ozten** [comment]
Rough plan. Have `compile-json` create two files instead of one.

Before: messages.po -> messages.json

After: messages.po -> messages.json
                                    messages.js

The `.json` file will be valid JSON. The `.js` will be valid JavaScript.

Client side code will change the build step to include .js and server side will continue to use .json, using native JSON.parse.

**Comment by ozten** [comment]
Low level work done in i18n-abide@0.0.8beta6.

**Comment by ozten** [comment]
Persona work
- Move @mathjazz over to i18n toolchain or update compile-json.sh in the SVN repo
- Change lib/static_resources.js to use client.js instead of client.json

**Comment by mathjazz** [comment]
How can I help here?

Update compile-json in SVN repo with this?
https://github.com/mozilla/i18n-abide/blob/7a69be79c3e9938f750d9ede32b89e6a07db6e69/bin/compile-json

**Comment by ozten** [comment]
@mathazz - I haven't done the work in browserid's codebase, but ya. The tricky thing is picking a train and coordinating the work. I don't know if I'll have time next week.

I'll ping you when my parts are all done and coordinate a time that is good to you, so we can test the `.pot` files and makes sure everything is working well.

**Comment by mathjazz** [comment]
Thanks, I'm pretty busy this week, too.

**Comment by shane-tomlinson** [comment]
@ozten, @mathjazz - Did you guys ever get to this work? I could swear I saw something about it.

**Comment by ozten** [comment]
yes, I've re-written that part of i18n-abide. It no longer uses `eval`.

I think we just need to upgrade from

```
"i18n-abide": "0.0.8beta4"
```

to `0.0.8beta8`.

Part of this change is we generate both .json files and actual .js files. .js for client side and .json for server side.

I'm not sure how much work is left, sorry. I could use help crossing the finish line, or checking to see if we're "done" enough.

**Comment by shane-tomlinson** [comment]
@ozten, let's see where we are and make a list of what needs to get done. I can look at this a bit tomorrow if you don't mind helping me out.

**Comment by ozten** [comment]
I think this is the remaining work: https://github.com/mozilla/browserid/pull/3664

**Comment by shane-tomlinson** [comment]
@ozten - can this be closed now?

**Comment by ozten** [comment]
Sorry, Yes, I think so.
