### ISSUE TITLE
Allow cachify in dialog views

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2502]
`cachify` is needed to show some inline images, and it outputs a unique URL so we can cache bust later. However, it only exists on the server. So if a dialog view has inline images and needs cachify, the function doesn't exist.

**Comment by seanmonstar** [comment]
this blocks adding the Tour module in #1874

**Comment by seanmonstar** [comment]
Two ways I can think of to solve this:
1. Parse the functions with uglify during compression, and replace cachify() with an absolute URL.
2. Leave them in, and add a cachify() method to BrowserID.Renderer, that adds in the current unique prefix.

@ozten Is the prefix unique but consistent for each build, or can it be different for each resource? I imagine there's something in place so we don't change the prefix unless the file has changed?

/cc @shane-tomlinson

**Comment by seanmonstar** [comment]
So it looks like the hash is an md5 of the contents of the file, so it's likely best I just replace that during compression.

That'd require that we never pass a variable or string concatenation to `cachify`, since it's going to be string replacement.

**Comment by ozten** [comment]
Sorry, I missed this until now.

That sounds good. I think the original idea was to evaluate templates during the compress step, so that any embeded JS could run. This is where cachify would do the file hash.

You can also reproduce this behavior as you've said, instead.
