### ISSUE TITLE
post-mortem on overnight prod monitor email failures

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2506]
136 am - 145 am PST 9/20/12, prod alarm went off due to emails not arriving at restmail within the 90 sec timeout period.

Unclear at what point in the chain sending failed.

here's the failing jobs:
https://ci.mozilla.org/job/identity.browserid.prod-monitor/372/
https://ci.mozilla.org/job/identity.browserid.prod-monitor/373/
https://ci.mozilla.org/job/identity.browserid.prod-monitor/374/

**Comment by jaredhirsch** [comment]
failure on stage-monitor during same period (141 am)
https://ci.mozilla.org/job/identity.browserid.stage-monitor/957/

**Comment by jrgm** [comment]
I dug the restmail address out of 372,373,374,957 and here are the relevant headers from each:

```
bash-3.2$ curl -s http://restmail.net/mail/123donetest_1348130281.132334  | node /tmp/read.js
Date:  Thu, 20 Sep 2012 08:38:10 GMT
ReceivedAt  2012-09-20T08:53:35.003Z
Received  [ 'from r1.east.aws.in.socketlabs.com ([50.17.202.71]) by smtp104.email-od.com with ESMTP; Thu, 20 Sep 2012 04:39:13 -0400',
  'from sweb1.idsecweb.scl2.svc.mozilla.com ([63.245.208.224]) by r1.east.aws.in.socketlabs.com with ESMTP; Thu, 20 Sep 2012 04:38:12 - 0400',
  'from sweb1.idsecweb.scl2.svc.mozilla.com (localhost [127.0.0.1]) by sweb1.idsecweb.scl2.svc.mozilla.com (Postfix) with ESMTP id D765680822 for <123donetest_1348130281.132334@restmail.net>; Thu, 20 Sep 2012 01:38:10 -0700 (PDT)' ]

bash-3.2$ curl -s http://restmail.net/mail/123donetest_1348130556.20419   | node /tmp/read.js
Date:  Thu, 20 Sep 2012 08:42:45 GMT
ReceivedAt  2012-09-20T08:53:36.408Z
Received  [ 'from r1.rsc.in.socketlabs.com ([184.106.114.173]) by smtp104.email-od.com with ESMTP; Thu, 20 Sep 2012 04:43:47 -0400',
  'from sweb1.idsecweb.scl2.svc.mozilla.com ([63.245.208.224]) by r1.rsc.in.socketlabs.com with ESMTP; Thu, 20 Sep 2012 04:42:49 -0400',
  'from sweb1.idsecweb.scl2.svc.mozilla.com (localhost [127.0.0.1]) by sweb1.idsecweb.scl2.svc.mozilla.com (Postfix) with ESMTP id 9D9CE80822 for <123donetest_1348130556.20419@restmail.net>; Thu, 20 Sep 2012 01:42:45 -0700 (PDT)' ]

bash-3.2$ curl -s http://restmail.net/mail/123donetest_1348130858.7957261 | node /tmp/read.js
Date:  Thu, 20 Sep 2012 08:47:48 GMT
ReceivedAt  2012-09-20T08:53:36.905Z
Received  [ 'from r3.rsc.in.socketlabs.com ([184.106.77.196]) by mail30.email-od.com with ESMTP; Thu, 20 Sep 2012 04:48:50 -0400',
  'from sweb1.idsecweb.scl2.svc.mozilla.com ([63.245.208.224]) by r3.rsc.in.socketlabs.com with ESMTP; Thu, 20 Sep 2012 04:48:07 -0400',
  'from sweb1.idsecweb.scl2.svc.mozilla.com (localhost [127.0.0.1]) by sweb1.idsecweb.scl2.svc.mozilla.com (Postfix) with ESMTP id 3BE3780822 for <123donetest_1348130858.7957261@restmail.net>; Thu, 20 Sep 2012 01:47:48 -0700 (PDT)' ]

bash-3.2$ curl -s http://restmail.net/mail/123donetest_1348130554.5520749 | node /tmp/read.js
Date:  Thu, 20 Sep 2012 08:42:44 GMT
ReceivedAt  2012-09-20T08:53:35.995Z
Received  [ 'from r1.rsc.in.socketlabs.com ([184.106.114.173]) by smtp104.email-od.com with ESMTP; Thu, 20 Sep 2012 04:43:46 -0400',
  'from sweb1.idsecweb.scl2.stage.svc.mozilla.com ([63.245.208.224]) by r1.rsc.in.socketlabs.com with ESMTP; Thu, 20 Sep 2012 04:42:48 -0400',
  'from sweb1.idsecweb.scl2.stage.svc.mozilla.com (localhost [127.0.0.1]) by sweb1.idsecweb.scl2.stage.svc.mozilla.com (Postfix) with ESMTP id 15229160C3D for <123donetest_1348130554.5520749@restmail.net>; Thu, 20 Sep 2012 01:42:44 -0700 (PDT)' ]
bash-3.2$ 
```

The interesting thing is that while the emails started over a span of ~10 minutes, they all arrived within one second of each other. To me, that suggests the delay was in the egress attempt by socketlabs to restmail, and not a problem with restmail itself. 

Anyone have other interpretations of those numbers? (I can see some other possible ways to interpret this).

**Comment by lloyd** [comment]
@jrgm nice analysis.  It really does look like socketlabs delivery was backed up, and then caught up in one big jump.

Seems like next steps are to:
1. look at socketlabs web api to see if there is a logged slow down during that period
2. contact socketlabs to determine if this was a known problem and to understand if this is outside our SLA.

**Comment by jaredhirsch** [comment]
Awesome stuff. The socketlabs web dashboard isn't terribly informative, but
I can create user creds for @jrgm so he can poke around and/or open a
support ticket. Socketlabs has really great support.

**Comment by jrgm** [comment]
I've been looking at the dashboards and experimenting with the api to see what I can get from that. I also have some other random thoughts that I'll post about later.

**Comment by jaredhirsch** [comment]
I should add that, when I asked Brian in Socketlabs support about an SLA,
he told me to talk to their sales dept.

I totally avoided doing that at the time, but if we're going to pay for an
independent account, now's probably the perfect time to ask about SLAs.

**Comment by lloyd** [comment]
Ok, it sounds like we have performed the post-mortem.  It sounds like we need to reach out to socketlabs and figure out precisely whether they have an SLA and guarantee that works for us.  @toxborrow, can you help coordinate this?

**Comment by jaredhirsch** [comment]
I will contact socketlabs today and get some SLAs from the sales team.

**Comment by jaredhirsch** [comment]
doh! /me contacts socketlabs for reals this time...

**Comment by jaredhirsch** [comment]
lowered from ridonkulous 5-stars to 4-stars. talking with vendor tomorrow.

**Comment by jaredhirsch** [comment]
socketlabs account purchased, @gene1wood has new creds and will file bugzilla change window/release tickets to update in prod.

socketlabs does provide a 100% uptime SLA, as well as an API we can use to monitor and alert on the failure or stuck-in-queue ratios. I pinged the dev-identity list about this, see the archives for more info. closing.

**Comment by gene1wood** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=802744
