### ISSUE TITLE
need a clear procedure for communicating downtime/outages to mailing list

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2507]
Prod monitors (and stage monitor) went off last night due to email downtime.

There was approximately 20 minutes of prod write downtime sprinkled throughout the beta release period Tuesday, so signins worked, but new user creation flaked out.

In both cases, it would be great if we had a documented procedure for communicating these incidents. This implies figuring out language and either piggybacking on dev-identity or finding another avenue.

**Comment by lloyd** [comment]
this is probably a duplicate of SEVERAL issues.  I shall hunt them down.  @shane-tomlinson - let's _do_ this?

**Comment by shane-tomlinson** [comment]
@lloyd - on top of persona status, should there be a mailing list?

**Comment by jaredhirsch** [comment]
Hmm, so I've added some docs on how to report outages:

https://mana.mozilla.org/wiki/display/Identity/Public+communication+during+an+outage
linked from the main escalation page
https://intranet.mozilla.org/Services/Ops/Escalation

I'll add a mention that emails should also be sent, pointed at the personastatus site for up-to-the-minute news.
