### ISSUE TITLE
check iOS 6 POSTs

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#2514]
Apparently, iOS 6 Safari is doing some odd things:

  http://stackoverflow.com/questions/12506897/is-safari-on-ios-6-caching-ajax-results

We should check that we're doing the right thing and things work on iOS 6, I don't have it installed yet.

**Comment by shane-tomlinson** [comment]
I am upgrading my iPad now. The iOS 6 emulator had not given me any problems, but it has been nearly 2 months since checking properly.

**Comment by shane-tomlinson** [comment]
@benadida - I have not yet done an exhaustive test, but so far things look good.

From the stackoverflow article:

```
    No Cache-Control or Expires headers = iOS6 Safari will cache
    Cache-Control max-age=0 and an immediate Expires = iOS6 Safari will cache
    Cache-Control: no-cache = iOS6 Safari will NOT cache
```

Our POSTs:

```
Cache-Control   no-cache, max-age=0
Connection  keep-alive
Content-Length  73
Content-Type    application/json; charset=utf-8
Date    Mon, 24 Sep 2012 09:57:19 GMT
Strict-Transport-Security   max-age=2592000; includeSubdomains
x-frame-options DENY
```

Our max-age is 0 and the Date is immediate, but we also have Cache-Control set to no-cache.

I am continuing testing.

**Comment by shane-tomlinson** [comment]
Link to https://github.com/mozilla/browserid/issues/294.

With issue #294, we started setting `Cache-Control: no-cache` for similar caching behavior in IE9

**Comment by lloyd** [comment]
this sounds resolved to me, @shane-tomlinson research suggests we're fine, and I've confirmed product works great on iOS6 (no signs of cached WSAPI calls).
