### ISSUE TITLE
cannot run frontend tests on ephemeral instances

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2517]
The routes for `mocks/templates.js` and `mocks/site-templates.js` are set up to only serve up if the resources are not minified.

Front end unit tests are still allowed to be run on ephemeral instances. For the unit tests, ephemeral instances still serve up individual resources, so these two resources must still be included in the routes list.

While this is not user facing, this is important because @jrgm on occasion runs frontend tests on ephemeral instances.

**Comment by jrgm** [comment]
belated but yes front end tests run on ephemeral instances on train-2012.10.12
