### ISSUE TITLE
After creation / verification of an account on login.persona.org, redirect to the account management page.

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2519]
After I create or verify a new (secondary) account on login.persona.org, I'm shown a nice confirmation screen, but that's it.

The header still has a "Sign In" button, despite that fact that I really am signed in now.

It'd be great if I got redirected to the account management screen instead of getting stuck on the "you're verified!" page.

**Comment by jrgm** [comment]
I believe this is now addressed in current dev environment.

**Comment by callahad** [comment]
Indeed it is! Yay!
