### ISSUE TITLE
Removing last secondary verified email closes account - on accounts with primary verified email

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#252]

**Comment by shane-tomlinson** [comment]
@jbonacci - this at the moment only affects our development environment, it will not yet happen on prod.  I'll outline more once we do the demo.

**Comment by lloyd** [comment]
shall we move this to the primaries milestone?

**Comment by shane-tomlinson** [comment]
0187e21638c4e277c21246425338c9333cccd1e5 takes care of asking the user if they would like to close their account on the last email deletion, but it does not take into account primaries.

**Comment by lloyd** [comment]
this is fixed.
