### ISSUE TITLE
When Persona takes longer than it should, error message is incorrect

### ISSUE THREAD

**Issue by nth10sd** [mozilla/persona#2525]
The message "We are sorry, this is taking a longer than it should." has an excess "a".

**Comment by shane-tomlinson** [comment]
Thanks for filing this @nth10sd, I have issued a pull request for review.

**Comment by warner** [comment]
Originally in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=794306 , please close after the fix lands.
