### ISSUE TITLE
There's no image on login.persona.org for facebook / google+ to grab.

### ISSUE THREAD

**Issue by georgschoelly** [mozilla/persona#2533]
When sharing links on facebook and google+ there's usually a little icon with the link which gets grabbed from the site.

However, this does not work for login.persona.org. Probably because all the images are embedded as background images.

There are two fixes:

a) add an image with the `<img>` tag.

b) implement some [open graph](http://ogp.me) meta tags like this:

```
<meta property="og:image" content="https://login.persona.org/logo.png" />
<meta property="og:title" content="Mozilla Persona" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://login.persona.org/subpage" />
```

**Comment by jrgm** [comment]
Is there any intent to do this. Closing pending further information.
