### ISSUE TITLE
Spelling mistake in the German version of the Persona web site.

### ISSUE THREAD

**Issue by georgschoelly** [mozilla/persona#2534]
page: https://login.persona.org/about

offending sentence

> Persona wart Ihre Privatsphäre

ought to be

> Persona **wahrt** Ihre Privatsphäre

source: http://www.duden.de/rechtschreibung/wahren

**Comment by shane-tomlinson** [comment]
@mathjazz - Can you contact the German translator to have this looked at?

**Comment by mathjazz** [comment]
Done.

**Comment by mathjazz** [comment]
From Michael via email: "Thanks, fixed in r109441 [1]."

Fixed.

**Comment by mathjazz** [comment]
http://viewvc.svn.mozilla.org/vc/projects/l10n-misc/trunk/browserid/locale/de/LC_MESSAGES/messages.po?r1=109441&r2=109440&pathrev=109441

**Comment by shane-tomlinson** [comment]
@mathjazz - you are awesome, thanks!

**Comment by csuciu** [comment]
Verify fixed on https://login.persona.org/about
