### ISSUE TITLE
http://www.mozilla.org/en-US/persona/ - screenshot has the URL personaid.org 

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2535]
From the [bugzilla bug 773180](https://bugzilla.mozilla.org/show_bug.cgi?id=773180):

"I've seen a few people say that persona isn't working for them, turns out that this is because they've been copying the URL in the screenshot (http://www.mozilla.org/media/img/persona/signin.png) which is incorrect.

Fix:
Change the screenshot to show login.persona.org in the URL bar opposed to personaid.org"

I've closed the bugzilla bug with a pointer over here.

**Comment by jrgm** [comment]
issue is being handled in bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=773180 (reason for closing it here).
