### ISSUE TITLE
Setup delegated IdP

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2538]
We need to add authority delegation to our tests.

1) An IdP which delegates to the actual IdP

I've created https://github.com/mozilla/browserid-delegates and it's on an ephemeral instance.

2) The actual IdP - should use provisioning.js from stage and be okay with an @delegat.es email address.

@lloyd @callahad 
Does eyedee.me or mockmyid.com fit the bill here?

Or should we create a new IdP for this?

/CC @warner

**Comment by callahad** [comment]
MockMyID should gladly sign whatever email address you present to it -- point delegat.es at it and let's see what happens :)

**Comment by ozten** [comment]
Awesome! Blocked on a static IP and SSL cert, but will point to MockMyID ASAP.

**Comment by ozten** [comment]
We can now use **delegat.es** for testing:
- http://123done.org/
- http://beta.123done.org/
- http://dev.123done.org/

Procedure for the user sita...

Enter sita@delegat.es

Note: dev works, stage and production don't. I've verified through HTTP traffic that mockmyid.com is using the right environments for provisinging.js.

**Comment by ozten** [comment]
Per [Create delegator stage environment](https://bugzilla.mozilla.org/show_bug.cgi?id=752981) we'll transfer ownership of delegat.es to Ops within 6 months.
