### ISSUE TITLE
run_locally.js fails with ../var/root.cert file missing

### ISSUE THREAD

**Issue by pschlump** [mozilla/persona#2540]
I think that I have followed the instructions for running locally but I get an error.  I am running on Ubuntu 12.04 with node v0.8.4 and npm 1.1.45 - have installed python-software-properties and git-core, libgpm3-dev g++.  Node is my own build with no special flags.  npm is a default install.

root@pschlump-dev1:~/www/qr-today.com/browserid# npm start

browserid@1.0.0-b1 start /home/pschlump/www/qr-today.com/browserid
node ./scripts/run_locally.js

spawned verifier (/home/pschlump/www/qr-today.com/browserid/bin/verifier) with pid 4385
spawned keysigner (/home/pschlump/www/qr-today.com/browserid/bin/keysigner) with pid 4387
spawned dbwriter (/home/pschlump/www/qr-today.com/browserid/bin/dbwriter) with pid 4388
spawned example (/home/pschlump/www/qr-today.com/browserid/scripts/serve_example.js) with pid 4390
spawned example_primary (/home/pschlump/www/qr-today.com/browserid/scripts/serve_example_primary.js) with pid 4393
spawned proxy (/home/pschlump/www/qr-today.com/browserid/bin/proxy) with pid 4394
spawned browserid (/home/pschlump/www/qr-today.com/browserid/bin/browserid) with pid 4397
spawned static (/home/pschlump/www/qr-today.com/browserid/bin/static) with pid 4398
info: process type is run_locally
example (4390): using browserid server at http://127.0.0.1:10002
example (4390): running on http://127.0.0.1:10001
example_primary (4393): using browserid server at http://127.0.0.1:10002
example_primary (4393): running on http://127.0.0.1:10005
verifier (4385): info: verifier server starting up
verifier (4385): path.existsSync is now called `fs.existsSync`.
verifier (4385): info: process type is verifier
verifier (4385): info: running on http://127.0.0.1:10000
proxy (4394): info: process type is proxy
proxy (4394): running on http://127.0.0.1:10006
keysigner (4387): info: Certs will be issued from: 127.0.0.1
keysigner (4387): path.existsSync is now called `fs.existsSync`.
keysigner (4387): info: process type is keysigner
dbwriter (4388): path.existsSync is now called `fs.existsSync`.
keysigner (4387): info: running on http://127.0.0.1:10003
dbwriter (4388): info: session cookie name is: browserid_state_3e983a
dbwriter (4388): info: dbwriter starting up
browserid (4397): path.existsSync is now called `fs.existsSync`.
browserid (4397): info: session cookie name is: browserid_state_3e983a
static (4398): path.existsSync is now called `fs.existsSync`.
dbwriter (4388): error: can't read public key, exiting: Error: ENOENT, no such file or directory '/home/pschlump/www/qr-today.com/browserid/var/root.cert'
dbwriter (4388): info: inserted primary info for 'example.domain' into cache, TODO point at 'http://127.0.0.1:10005'
browserid (4397): info: browserid server starting up
static (4398): info: session cookie name is: browserid_state_3e983a
browserid (4397): error: can't read public key, exiting: Error: ENOENT, no such file or directory '/home/pschlump/www/qr-today.com/browserid/var/root.cert'
browserid (4397): info: inserted primary info for 'example.domain' into cache, TODO point at 'http://127.0.0.1:10005'
static (4398): info: static starting up
static (4398): error: can't read public key, exiting: Error: ENOENT, no such file or directory '/home/pschlump/www/qr-today.com/browserid/var/root.cert'
static (4398): info: process type is static
static exited(1)  
keysigner (4387): warn: SIGTERM received.  closing 0 connections and shutting down.
verifier (4385): warn: SIGTERM received.  closing 0 connections and shutting down.
example exited(1)  
example_primary exited(1)  
dbwriter exited(1)  
proxy exited(1)  
verifier exited(0)  
browserid exited(1)  
keysigner exited(0)  
all daemons torn down, exiting...

**Comment by seanmonstar** [comment]
The keys should get generated at `npm install`. Do you have that log dump?

**Comment by pschlump** [comment]
no I don't - but I can start over

**Comment by pschlump** [comment]
root@pschlump-dev1:~/www/qr-today.com/browserid# npm install
npm WARN cannot run in wd browserid@1.0.0-b1 ./scripts/lockdown (wd=/home/pschlump/www/qr-today.com/browserid)
npm WARN package.json connect@1.7.2 No README.md file found!
npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
npm http 200 https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
npm WARN cannot run in wd browserid@1.0.0-b1 node ./scripts/postinstall.js (wd=/home/pschlump/www/qr-today.com/browserid)
root@pschlump-dev1:~/www/qr-today.com/browserid# 
root@pschlump-dev1:~/www/qr-today.com/browserid# 
root@pschlump-dev1:~/www/qr-today.com/browserid# 
root@pschlump-dev1:~/www/qr-today.com/browserid# ls var
browserid_cookie.sekret  log
root@pschlump-dev1:~/www/qr-today.com/browserid# 
root@pschlump-dev1:~/www/qr-today.com/browserid# cd ..
root@pschlump-dev1:~/www/qr-today.com# mv browserid/ browserid.000
root@pschlump-dev1:~/www/qr-today.com# tar -xf ~/x.tar
root@pschlump-dev1:~/www/qr-today.com# cd browserid
root@pschlump-dev1:~/www/qr-today.com/browserid# ls
automation-tests  ChangeLog  CONTRIBUTORS  example  LICENSE        Makefile      README.md  scripts
bin               config     docs          lib      lockdown.json  package.json  resources  tests
root@pschlump-dev1:~/www/qr-today.com/browserid# npm install
npm WARN cannot run in wd browserid@1.0.0-b1 ./scripts/lockdown (wd=/home/pschlump/www/qr-today.com/browserid)
npm http GET https://registry.npmjs.org/JSONSelect/0.4.0
npm http GET https://registry.npmjs.org/bcrypt/0.7.1
npm http GET https://registry.npmjs.org/compute-cluster/0.0.6
npm http GET https://registry.npmjs.org/convict/0.0.6
npm http GET https://registry.npmjs.org/cjson/0.0.6
npm http GET https://registry.npmjs.org/connect/1.7.2
npm http GET https://registry.npmjs.org/connect-cachify/0.0.10
npm http GET https://registry.npmjs.org/client-sessions/0.0.9
npm http GET https://registry.npmjs.org/connect-cookie-session/0.0.2
npm http GET https://registry.npmjs.org/connect-logger-statsd/0.0.1
npm http GET https://registry.npmjs.org/ejs/0.8.3
npm http GET https://registry.npmjs.org/etagify/0.0.2
npm http GET https://registry.npmjs.org/express/2.5.0
npm http GET https://registry.npmjs.org/gobbledygook/0.0.3
npm http GET https://registry.npmjs.org/lockdown/0.0.1
npm http GET https://registry.npmjs.org/jwcrypto/0.4.2
npm http GET https://registry.npmjs.org/mkdirp/0.3.0
npm http GET https://registry.npmjs.org/mysql/0.9.5
npm http GET https://registry.npmjs.org/nodemailer/0.3.21
npm http GET https://registry.npmjs.org/postprocess/0.2.4
npm http GET https://registry.npmjs.org/semver/1.0.12
npm http GET https://registry.npmjs.org/optimist/0.2.8
npm http GET https://registry.npmjs.org/temp/0.4.0
npm http GET https://registry.npmjs.org/uglifycss/0.0.5
npm http GET https://registry.npmjs.org/uglify-js/1.0.6
npm http GET https://registry.npmjs.org/underscore/1.3.1
npm http GET https://registry.npmjs.org/urlparse/0.0.1
npm http GET https://registry.npmjs.org/winston/0.6.2
npm http GET https://registry.npmjs.org/validator/0.4.9
npm http GET https://registry.npmjs.org/awsbox/0.2.17
npm http GET https://registry.npmjs.org/irc/0.3.3
npm http GET https://registry.npmjs.org/jshint/0.7.1
npm http GET https://registry.npmjs.org/minimatch/0.2.6
npm http GET https://registry.npmjs.org/vows/0.5.13
npm http GET https://registry.npmjs.org/htmlparser/1.7.6
npm http GET https://registry.npmjs.org/which/1.0.5
npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
npm http 304 https://registry.npmjs.org/bcrypt/0.7.1
npm http 304 https://registry.npmjs.org/JSONSelect/0.4.0
npm http 304 https://registry.npmjs.org/convict/0.0.6
npm http 304 https://registry.npmjs.org/compute-cluster/0.0.6
npm http 304 https://registry.npmjs.org/cjson/0.0.6
npm http 304 https://registry.npmjs.org/connect/1.7.2
npm WARN package.json connect@1.7.2 No README.md file found!
npm http 304 https://registry.npmjs.org/client-sessions/0.0.9
npm http 304 https://registry.npmjs.org/connect-cachify/0.0.10
npm http 304 https://registry.npmjs.org/connect-cookie-session/0.0.2
npm http 200 https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
npm http 304 https://registry.npmjs.org/connect-logger-statsd/0.0.1
npm http 304 https://registry.npmjs.org/ejs/0.8.3
npm http 304 https://registry.npmjs.org/etagify/0.0.2
npm http 304 https://registry.npmjs.org/express/2.5.0
npm http 304 https://registry.npmjs.org/gobbledygook/0.0.3
npm http 304 https://registry.npmjs.org/lockdown/0.0.1
npm http 304 https://registry.npmjs.org/jwcrypto/0.4.2
npm http 304 https://registry.npmjs.org/mkdirp/0.3.0
npm http 304 https://registry.npmjs.org/mysql/0.9.5
npm http 304 https://registry.npmjs.org/nodemailer/0.3.21
npm http 304 https://registry.npmjs.org/postprocess/0.2.4
npm http 304 https://registry.npmjs.org/semver/1.0.12
npm http 304 https://registry.npmjs.org/temp/0.4.0
npm http 304 https://registry.npmjs.org/optimist/0.2.8
npm http 304 https://registry.npmjs.org/uglify-js/1.0.6
npm http 304 https://registry.npmjs.org/uglifycss/0.0.5
npm http 304 https://registry.npmjs.org/underscore/1.3.1
npm http 304 https://registry.npmjs.org/urlparse/0.0.1
npm http 304 https://registry.npmjs.org/winston/0.6.2
npm http 304 https://registry.npmjs.org/validator/0.4.9
npm http 304 https://registry.npmjs.org/awsbox/0.2.17
npm http 304 https://registry.npmjs.org/irc/0.3.3
npm http 304 https://registry.npmjs.org/jshint/0.7.1
npm http 304 https://registry.npmjs.org/minimatch/0.2.6
npm http 304 https://registry.npmjs.org/vows/0.5.13
npm http 304 https://registry.npmjs.org/htmlparser/1.7.6
npm http 304 https://registry.npmjs.org/which/1.0.5
npm WARN engine connect@1.7.2: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"node":"0.8.4","npm":"1.1.45"})
npm WARN engine express@2.5.0: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"node":"0.8.4","npm":"1.1.45"})
npm http GET https://github.com/benadida/cookies/tarball/d2f0f0b3
npm http GET https://registry.npmjs.org/mersenne
npm http GET https://registry.npmjs.org/read-installed/0.0.1
npm http GET https://registry.npmjs.org/node-proxy/0.6.0
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/vows/0.6.0
npm http GET https://registry.npmjs.org/aws-lib/0.0.5
npm http GET https://registry.npmjs.org/xml2js/0.1.13
npm http GET https://registry.npmjs.org/orderly/1.0.1
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http GET https://registry.npmjs.org/JSV/3.5.0
npm http GET https://registry.npmjs.org/mailcomposer
npm http GET https://registry.npmjs.org/cli/0.4.3
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/simplesmtp
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/hashish/0.0.4
npm http GET https://registry.npmjs.org/browserify/1.13.5
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/http-browserify/0.1.1
npm http GET https://registry.npmjs.org/optimist/0.3.1
npm http GET https://registry.npmjs.org/mkdirp/0.0.7
npm http GET https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/optimist/0.2.6
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/relative-date/1.1.1
npm http GET https://registry.npmjs.org/bigint/0.3.9
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/mersenne
npm http 304 https://registry.npmjs.org/read-installed/0.0.1
npm WARN package.json mersenne@0.0.3 No README.md file found!
npm http 304 https://registry.npmjs.org/node-proxy/0.6.0
npm http 304 https://registry.npmjs.org/vows/0.6.0
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/slide
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/read-package-json
npm http GET https://registry.npmjs.org/npmlog
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/aws-lib/0.0.5
npm http 304 https://registry.npmjs.org/xml2js/0.1.13
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/orderly/1.0.1
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> bcrypt@0.7.1 install /home/pschlump/www/qr-today.com/browserid/node_modules/bcrypt
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/JSV/3.5.0
npm http 304 https://registry.npmjs.org/mailcomposer
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/cli/0.4.3
npm http 304 https://registry.npmjs.org/simplesmtp
npm http 304 https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/nomnom
npm http GET https://registry.npmjs.org/rai
npm http GET https://registry.npmjs.org/xoauth2
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/hashish/0.0.4
make: Entering directory `/home/pschlump/www/qr-today.com/browserid/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/browserify/1.13.5
npm http GET https://registry.npmjs.org/mimelib
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/http-browserify/0.1.1
npm http 304 https://registry.npmjs.org/optimist/0.3.1
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
npm http 200 https://github.com/benadida/cookies/tarball/d2f0f0b3
npm http 304 https://registry.npmjs.org/mkdirp/0.0.7
npm http 304 https://registry.npmjs.org/cycle
npm WARN package.json cycle@1.0.0 No README.md file found!
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
npm http 304 https://registry.npmjs.org/relative-date/1.1.1
npm http 304 https://registry.npmjs.org/eyes
npm http 304 https://registry.npmjs.org/optimist/0.2.6
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/bigint/0.3.9
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/wordwrap

> bigint@0.3.9 install /home/pschlump/www/qr-today.com/browserid/node_modules/jwcrypto/node_modules/bigint
> node-waf configure build

npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/slide
npm http 304 https://registry.npmjs.org/graceful-fs

> node-proxy@0.6.0 install /home/pschlump/www/qr-today.com/browserid/node_modules/client-sessions/node_modules/node-proxy
> node-gyp configure build

npm http GET https://registry.npmjs.org/detective
npm http GET https://registry.npmjs.org/deputy
npm http GET https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/read-package-json
npm http GET https://registry.npmjs.org/nub
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
npm Checking for program g++ or c++          : /usr/bin/g++ 
http GET https://registry.npmjs.org/commondir
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/vm-browserify
npm http GET https://registry.npmjs.org/crypto-browserify
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/npmlog
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.026s)
Waf: Entering directory `/home/pschlump/www/qr-today.com/browserid/node_modules/jwcrypto/node_modules/bigint/build'
[1/2] cxx: bigint.cc -> build/Release/bigint_1.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
  COPY Release/bcrypt_lib.node
make: Leaving directory`/home/pschlump/www/qr-today.com/browserid/node_modules/bcrypt/build'
npm http GET https://registry.npmjs.org/ansi
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/nomnom
npm http 304 https://registry.npmjs.org/rai
npm http 304 https://registry.npmjs.org/mimelib
npm http 304 https://registry.npmjs.org/xoauth2
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/inherits
make: Entering directory `/home/pschlump/www/qr-today.com/browserid/node_modules/client-sessions/node_modules/node-proxy/build'
  CXX(target) Release/obj.target/nodeproxy/src/node-proxy.o
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/sax
../src/node-proxy.cc: In static member function ‘static v8::Handle<v8::Value> v8::NodeProxy::GetNamedProperty(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../src/node-proxy.cc:816:1: warning: control reaches end of non-void function [-Wreturn-type]
npm http 304 https://registry.npmjs.org/detective
npm http 304 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/encoding
npm http GET https://registry.npmjs.org/addressparser
npm http 304 https://registry.npmjs.org/deputy
npm http 304 https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/nub
npm http 304 https://registry.npmjs.org/commondir
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/vm-browserify
npm http 304 https://registry.npmjs.org/crypto-browserify
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/detective
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/ansi
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/wordwrap
  SOLINK_MODULE(target) Release/obj.target/nodeproxy.node
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/colors
  SOLINK_MODULE(target) Release/obj.target/nodeproxy.node: Finished
  COPY Release/nodeproxy.node
make: Leaving directory`/home/pschlump/www/qr-today.com/browserid/node_modules/client-sessions/node_modules/node-proxy/build'
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/encoding
npm http GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/addressparser
npm http 304 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/iconv
npm http 304 https://registry.npmjs.org/detective
[2/2] cxx_link: build/Release/bigint_1.o -> build/Release/bigint.node
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/wordwrap
npm Waf: Leaving directory `/home/pschlump/www/qr-today.com/browserid/node_modules/jwcrypto/node_modules/bigint/build'
http GET https://registry.npmjs.org/esprima
'build' finished successfully (0.919s)
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/iconv
npm WARN prefer global jshint@0.7.1 should be installed with -g
npm http 304 https://registry.npmjs.org/iconv-lite
npm http 304 https://registry.npmjs.org/esprima

> jwcrypto@0.4.2 postinstall /home/pschlump/www/qr-today.com/browserid/node_modules/jwcrypto
> node ./scripts/bundle.js

***_Bundling VEP for Browser**_*

**_Packaging External Dependencies**_*

path.existsSync is now called `fs.existsSync`.

> iconv@1.2.3 install /home/pschlump/www/qr-today.com/browserid/node_modules/nodemailer/node_modules/mailcomposer/node_modules/mimelib/node_modules/encoding/node_modules/iconv
> node-gyp rebuild

make: Entering directory `/home/pschlump/www/qr-today.com/browserid/node_modules/nodemailer/node_modules/mailcomposer/node_modules/mimelib/node_modules/encoding/node_modules/iconv/build'
  CC(target) Release/obj.target/iconv/deps/libiconv/libcharset/lib/localcharset.o
  CC(target) Release/obj.target/iconv/deps/libiconv/lib/iconv.o
  CXX(target) Release/obj.target/iconv/binding.o
  SOLINK_MODULE(target) Release/obj.target/iconv.node
  SOLINK_MODULE(target) Release/obj.target/iconv.node: Finished
  COPY Release/iconv.node
make: Leaving directory`/home/pschlump/www/qr-today.com/browserid/node_modules/nodemailer/node_modules/mailcomposer/node_modules/mimelib/node_modules/encoding/node_modules/iconv/build'
npm WARN cannot run in wd browserid@1.0.0-b1 node ./scripts/postinstall.js (wd=/home/pschlump/www/qr-today.com/browserid)
connect-logger-statsd@0.0.1 node_modules/connect-logger-statsd

gobbledygook@0.0.3 node_modules/gobbledygook

etagify@0.0.2 node_modules/etagify

urlparse@0.0.1 node_modules/urlparse

connect-cookie-session@0.0.2 node_modules/connect-cookie-session

temp@0.4.0 node_modules/temp

cjson@0.0.6 node_modules/cjson

mkdirp@0.3.0 node_modules/mkdirp

connect-cachify@0.0.10 node_modules/connect-cachify

irc@0.3.3 node_modules/irc

validator@0.4.9 node_modules/validator

ejs@0.8.3 node_modules/ejs

underscore@1.3.1 node_modules/underscore

JSONSelect@0.4.0 node_modules/JSONSelect

which@1.0.5 node_modules/which

uglifycss@0.0.5 node_modules/uglifycss

semver@1.0.12 node_modules/semver

uglify-js@1.0.6 node_modules/uglify-js

postprocess@0.2.4 node_modules/postprocess

htmlparser@1.7.6 node_modules/htmlparser

node-statsd@0.0.2 node_modules/node-statsd
└── mersenne@0.0.3

minimatch@0.2.6 node_modules/minimatch
└── lru-cache@2.0.4

optimist@0.2.8 node_modules/optimist
└── wordwrap@0.0.2

vows@0.5.13 node_modules/vows
└── eyes@0.1.8

compute-cluster@0.0.6 node_modules/compute-cluster
└── vows@0.6.0 (eyes@0.1.8)

connect@1.7.2 node_modules/connect
├── mime@1.2.7
└── qs@0.5.1

express@2.5.0 node_modules/express
├── mkdirp@0.0.7
├── mime@1.2.7
└── qs@0.5.1

winston@0.6.2 node_modules/winston
├── cycle@1.0.0
├── eyes@0.1.8
├── colors@0.6.0-1
├── stack-trace@0.0.6
├── pkginfo@0.2.3
├── async@0.1.22
└── request@2.9.203

bcrypt@0.7.1 node_modules/bcrypt
└── bindings@1.0.0

mysql@0.9.5 node_modules/mysql
└── hashish@0.0.4 (traverse@0.6.3)

awsbox@0.2.17 node_modules/awsbox
├── relative-date@1.1.1
├── aws-lib@0.0.5 (sax@0.1.5)
├── optimist@0.3.1 (wordwrap@0.0.2)
└── xml2js@0.1.13 (sax@0.4.2)

client-sessions@0.0.9 node_modules/client-sessions
├── cookies@0.1.7
└── node-proxy@0.6.0

convict@0.0.6 node_modules/convict
├── JSV@3.5.0
└── orderly@1.0.1 (nomnom@1.5.2)

lockdown@0.0.1 node_modules/lockdown
└── read-installed@0.0.1 (graceful-fs@1.1.14, semver@1.0.14, slide@1.1.3, npmlog@0.0.2, read-package-json@0.1.5)

jshint@0.7.1 node_modules/jshint
├── minimatch@0.0.5 (lru-cache@1.0.6)
└── cli@0.4.3 (glob@3.1.13)

jwcrypto@0.4.2 node_modules/jwcrypto
├── http-browserify@0.1.1
├── optimist@0.2.6 (wordwrap@0.0.2)
├── bigint@0.3.9
└── browserify@1.13.5 (nub@0.0.0, commondir@0.0.1, vm-browserify@0.0.1, crypto-browserify@0.1.1, resolve@0.2.3, coffee-script@1.3.3, optimist@0.3.4, detective@0.1.1, deputy@0.0.4)

nodemailer@0.3.21 node_modules/nodemailer
├── simplesmtp@0.1.24 (rai@0.1.6, xoauth2@0.1.2)
└── mailcomposer@0.1.21 (mime@1.2.7, mimelib@0.2.7)

Same problem 2nd time.

**Comment by pschlump** [comment]
about 5 lines in - this seems to be the important line

npm WARN cannot run in wd browserid@1.0.0-b1 node ./scripts/postinstall.js (wd=/home/pschlump/www/qr-today.com/browserid)

**Comment by seanmonstar** [comment]
Yep, the postinstall script, among other things, sets the certificates in
the proper locations. I'm not sure what "wd" is, though.

**Comment by seanmonstar** [comment]
@pschlump I notice that you're running this as root. Can you try just as your usual user?

We've seen this before in #1795.

**Comment by jrgm** [comment]
Closing this, as it was probably due to running as root (which one should not do, in general).
