### ISSUE TITLE
[Chrome] navigator.id.logout does not trigger onlogout callback passed to navigator.id.watch

### ISSUE THREAD

**Issue by jimmycuadra** [mozilla/persona#2545]
### Steps to reproduce:
1. Call `navigator.id.watch`, providing callbacks for both `onlogin` and `onlogout`.
2. Call `navigator.id.logout`.
### Expected behavior

The `onlogout` callback passed to `navigator.id.watch` should be invoked in both Firefox and Chrome.
### Actual behavior

Only invoked in Firefox, not Chrome (v22.0.1229.79 on OS X Mountain Lion).

**Comment by shane-tomlinson** [comment]
@jimmycuadra - onlogout will only be called if Persona believes a user is logged in. Was onlogin ever called? If not, are you passing a user to loggedInUser? If not, was the Persona dialog opened and a user signed in?

If none of the above happen, calling logout will have no effect.

**Comment by jimmycuadra** [comment]
@shane-tomlinson There are two cases I've encountered, and `onlogout` does not fire in either case in Chrome:
1. I'm logged out on the initial page load. `navigator.id.watch` is called with `undefined` for `loggedInUser`, and callbacks for both `onlogin` and `onlogout`. I click the sign in button, get the Persona dialog, sign in, successfully verify the assertion, and store the session information in localStorage (not using cookies). If I then click on sign out  (which calls `navigator.id.logout`, the `onlogout` callback originally passed to `navigator.id.watch` does not fire.
2. The second flow is similar, but involves a page refresh after successfully signing in. In this case, the user session is looked up from localStorage and the email address is passed to `navigator.id.watch` as `loggedInUser`. Again, clicking on sign out (which calls `navigator.id.logout`) does not fire the `onlogout` callback.

Both of these flows fire the callback in Firefox.

**Comment by jimmycuadra** [comment]
I discovered that the callback fires as expected if I enable third-party cookies or create an inclusion filter specifically for login.persona.org, as mentioned in #2546. Both issues seem to be related to cookies.

**Comment by jimmycuadra** [comment]
Closing this, as it is covered by #982, #989, and #1352.
