### ISSUE TITLE
[Chrome] Calling navigator.id.watch throws "QUOTA_EXCEEDED_ERR: DOM Exception 22" in communication_iframe.js

### ISSUE THREAD

**Issue by jimmycuadra** [mozilla/persona#2546]
### Steps to reproduce
1. Load a page with `include.js`.
2. Call `navigator.id.watch`.
### Expected behavior

No exceptions should be thrown.
### Actual behavior

Chrome (v22.0.1229.79 on OS X Mountain Lion) throws `QUOTA_EXCEEDED_ERR: DOM Exception 22`.

**Comment by shane-tomlinson** [comment]
@jimmycuadra - this happens when you have Cookies or access to localStorage disabled. Can you check to make sure that both are enabled?

**Comment by jimmycuadra** [comment]
@shane-tomlinson Cookies are set to "Allow local data to be set (recommended)" with "Block third-party cookies and site data" checked. I don't see a setting for disabling localStorage, but it must be on because the app I'm working on uses it.

**Comment by jimmycuadra** [comment]
@shane-tomlinson Unchecking "Block third-party cookies and site data" prevents the exception. It seems the script should handle this case gracefully, though. Many users will have this option set.

**Comment by shane-tomlinson** [comment]
@jimmycuadra - I agree with you 100%, we have 3 separate issues open about this - #982, #989, #1352.

Closing this one as a dup, feel free to re-open or append to one of those with any new info.

Thanks for the report!
