### ISSUE TITLE
The "How it Works" page isn't

### ISSUE THREAD

**Issue by pmclanahan** [mozilla/persona#2547]
A friend was evaluating Persona and sent me the following complaints:
1. The "How it Works" page does not explain how it works.
2. Its URL is /about which is confusing
3. When on the page there's no indication that you are. The "How it Works" button should be highlighted at least.

They're little things, but they're part of the first impression, and have not impressed at least this one guy.

**Comment by skinny97214** [comment]
Agree 100%! @callahad and I are already on it and will have a pull request coming this week. The [How it Works] page will be going away entirely in favor of a redesigned home page that explains the dev and user values.
