### ISSUE TITLE
Relay frame could not be found error in Chrome Extension 

### ISSUE THREAD

**Issue by andornaut** [mozilla/persona#2548]
I'm working on integrating Persona into a Chrome Extension

After calling navigator.id.request() from the extension's "options.html" page, the popup window shows the following error message: 

Action: Establishing Relay
Relay frame could not be found

Extension details:
- Backbone.js
- Manifest v2

Please note that I've enabled 'unsafe-eval' as well as "persona.org" locations for frame-src and script-src via the default-src directive of the extension's manifest.json:

"content_security_policy": "default-src 'self' 'unsafe-eval' https://login.persona.org https://static.login.persona.org;",

http://developer.chrome.com/extensions/contentSecurityPolicy.html

I've also set the following in the manifest.json:
- web_accessible_resources: [ "options.html" ]

Environment:
- Chrome 21.0.1180.89, Debian Linux (wheezy)
- Chrome 22.0.1229.79, Mac OSX Lion
- Chrome 23.0.1271.10, Debian Linux (wheezy)

**Comment by shane-tomlinson** [comment]
Hi @andornaut - We would like to see your extension once it if finished! The relay frame error is by design, you are going to want to check our "Internal API" which is made especially for purposes like this.

Please see: https://github.com/mozilla/browserid/wiki/Front-End-Development under "Internal API".

If you need any more info, feel free to re-open this issue.

**Comment by ozten** [comment]
Remember, the **internal API** is not a final, publicly supported API!

Follow the SDK work which will probably help to cement the real API that would be useful from Add-ons.

**Comment by andornaut** [comment]
Shane:

It's not clear what js files are required to work with the Internal API. Neither the include.js nor the internal_api.js define a BrowserID object, which the docs refer to.

I'd appreciate a little more of a nudge in the right direction. Thanks.

Also, if you don't mind, it'd be great if you could explain why the regular way of doing things doesn't work here. I understand that for iOS or Android apps there are problems with popups, etc; but a chrome extension should work much the same as any regular website, no?
