### ISSUE TITLE
login.persona.org responds to ICMP Echo Request with ICMP Port Unreachable

### ISSUE THREAD

**Issue by kevinoid** [mozilla/persona#2550]
Performing a ping of login.persona.org results in the following output:

```
$ ping login.persona.org
PING persona.org (63.245.217.134) 56(84) bytes of data.
From phx1-persona.services.mozilla.com (63.245.217.134) icmp_seq=1 Destination Port Unreachable
From phx1-persona.services.mozilla.com (63.245.217.134) icmp_seq=2 Destination Port Unreachable
From phx1-persona.services.mozilla.com (63.245.217.134) icmp_seq=3 Destination Port Unreachable
From phx1-persona.services.mozilla.com (63.245.217.134) icmp_seq=4 Destination Port Unreachable
--- persona.org ping statistics ---
4 packets transmitted, 0 received, +4 errors, 100% packet loss, time 3005ms
```

This is because rather than sending an ICMP Echo Response, login.persona.org sends an ICMP Port Unreachable in response to the ICMP Echo Request.  The practical problem that this causes is that the ping tool will not display the RTT/latency information if an Echo Response is not received.

Ping can be a useful tool for network testing, and I would appreciate it if you would consider supporting it.

Thanks,
Kevin

**Comment by fmarier** [comment]
I will follow up with netops to see whether that can be done.

**Comment by fmarier** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=803391
