### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by aackerman** [mozilla/persona#2555]
I'm working on Persona integration and looking for a few answers. I have a site that allows a user to login at http://www.example.com, but they can also login at https://www.example.com. Currently Persona considers these two domains to be completely different when determining if the user is logged in, I understand that they are considered cross-domain due to differing protocols.

However in practice we consider both of these to be our same site. The same would also be true if the user attempts to login at http://www.example.com and attempts to access http://othersubdomain.example.com. In practice we would consider the user to be logged into both, with all other forms of login currently used with our site.

Is it possible to allow a user to login with Persona for an entire hostname?
Such as considering the user logged in for *.example.com.

I understand there are possible security issues if this behavior was the default. However it would be nice to specify an option to handle an entire hostname.

If my understanding of how a user is logged in is completely off base, can you please explain how I can have a user logged into multiple domains technically considered cross-domain with one login action and to have the ability to log them out with one action.

**Comment by shane-tomlinson** [comment]
@theron17 - Thanks for the suggestion!  

We recently started discussing how we could use Persona to enable SSO. We have not yet come up with any concrete proposals, but will present them once we are further along!

**Comment by lloyd** [comment]
thanks a ton for the idea!  typically what we do with ideas this big is discuss them first on our mailing list, please bring it over to dev-identity@mozilla.org

**Comment by seanmonstar** [comment]
That's dev-identity@lists.mozilla.org :)

https://lists.mozilla.org/listinfo/dev-identity

**Comment by seanmonstar** [comment]
Re-opening, since we're doing this feature NAOW!

**Comment by seanmonstar** [comment]
Relevant discussions that happened on the list:

https://groups.google.com/d/topic/mozilla.dev.identity/oMuTGsxLKQk/discussion
https://groups.google.com/d/topic/mozilla.dev.identity/z3d_wj6Jjq0/discussion

**Comment by gene1wood** [comment]
Proxy server support added here https://github.com/mozilla/identity-ops/commit/e6e293149747a18278d79fe4d3b5fa24bbbd0e69

When this feature goes to stage we'll need to build new proxy amis with the new proxy support.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
