### ISSUE TITLE
raise the idproxy byte size limit for .well-known/browserid

### ISSUE THREAD

**Issue by lmorchard** [mozilla/persona#2559]
So, [I'm hacking together an IdP](https://developer.mozilla.org/en-US/docs/Persona/Implementing_a_Persona_IdP), and having no luck getting production or staging to recognize it. A laptop instance and dev.anosrep.org does, though. I had a self-signed SSL cert, but upgraded to a free cert from startssl.com - still no luck.

Then, @floatingatoll caught me on IRC and said 'ERR_TOO_BIG' from the idproxy logs. I don't know what that means, but FWIW my `.well-known/browserid` was 1756 characters:

```
-> % curl -s 'https://whuru.com/.well-known/browserid' | wc -c
    1756
```

And, here's what it looked like:

```
{
    "public-key": {"algorithm":"DS","y":"319eaa88576d0cb3cfd7d62142eaeaf0880ca6842ec3938e451d7d91ed70f589e785daba8ff86cc52801a1c26c945f9730b84fc3d263410137e29499b00bf8e620d9bcef4e89ceddf217161fd8aff04768532dd75ef7807edcbf7b70c46ddd8807926d9bd3ac7a30daa0e19eb8617ee9e9a85b8f444eb07e9c457f6e3a2a22acbe03f2bd9a456dbb78850f239b7e57ab792aa84f9e2528fb2d9c1164a6ee1a758ee70dd79c5fee4585c2c7fe0a011cb0539edc588fc46ec0f92fe2309bf160586a9afb3b164d149e7923c5313ba68c7a0f311bca46eb86acef1433dc5ce42bf9fe51783f8aeb77d842c4791b67d0bf563c3ba483c084b6ef103fecbbe8b7ab5f","p":"d6c4e5045697756c7a312d02c2289c25d40f9954261f7b5876214b6df109c738b76226b199bb7e33f8fc7ac1dcc316e1e7c78973951bfc6ff2e00cc987cd76fcfb0b8c0096b0b460fffac960ca4136c28f4bfb580de47cf7e7934c3985e3b3d943b77f06ef2af3ac3494fc3c6fc49810a63853862a02bb1c824a01b7fc688e4028527a58ad58c9d512922660db5d505bc263af293bc93bcd6d885a157579d7f52952236dd9d06a4fc3bc2247d21f1a70f5848eb0176513537c983f5a36737f01f82b44546e8e7f0fabc457e3de1d9c5dba96965b10a2a0580b0ad0f88179e10066107fb74314a07e6745863bc797b7002ebec0b000a98eb697414709ac17b401","q":"b1e370f6472c8754ccd75e99666ec8ef1fd748b748bbbc08503d82ce8055ab3b","g":"9a8269ab2e3b733a5242179d8f8ddb17ff93297d9eab00376db211a22b19c854dfa80166df2132cbc51fb224b0904abb22da2c7b7850f782124cb575b116f41ea7c4fc75b1d77525204cd7c23a15999004c23cdeb72359ee74e886a1dde7855ae05fe847447d0a68059002c3819a75dc7dcbb30e39efac36e07e2c404b7ca98b263b25fa314ba93c0625718bd489cea6d04ba4b0b7f156eeb4c56c44b50e4fb5bce9d7ae0d55b379225feb0214a04bed72f33e0664d290e7c840df3e2abb5e48189fa4e90646f1867db289c6560476799f7be8420a6dc01d078de437f280fff2d7ddf1248d56e1a54b933a41629d6c252983c58795105802d30d7bcd819cf6ef"},
    "authentication": "/browserid/sign_in",
    "provisioning": "/browserid/provision"
}
```

My keys were generated by this process:
- Clone [browserid-certifier](https://github.com/mozilla/browserid-certifier)
- `npm install`
- `./node_modules/.bin/generate-keypair`

Further IRC discussion notes that my keys use the DSA algorithm (to which `generate-keypair` defaults), while everything else assumes the RSA algorithm.

Regenerated my keys with `./node_modules/.bin/generate-keypair -a rsa`, which resulted in a 764 character `.well-known/browserid`, though that has not yet resolved my issue either. (But, _that_ might just be an artifact of caching, so I'll go do something else for awhile and try again later)

**Comment by floatingatoll** [comment]
The spec maybe used to say RSA, but it doesn't specify RSA or DSA anymore
-- however, RSA keys fit within the idproxy byte size limits, but DSA keys
do not. So if we intend to support DSA keys, we should bump that limit up
to support them.

**Comment by ozten** [comment]
This is an Ops bug. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=800439
