### ISSUE TITLE
internal api needs logout and logoutEverywhere functions.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2561]
B2G and other internal/native implementations that make use of the API need a way of logging the user out of a specific site as well as a general logout function.

**Comment by shane-tomlinson** [comment]
link to #1416

**Comment by lloyd** [comment]
Lets include the motivating use case in issues, it helps people understand and prioritize.

-- lloyd (thumb-typing)

**Comment by seanmonstar** [comment]
Motivating case is that it seems the B2G dialog will use the internal API, and there's currently no internal logout. So, priority is like 9000.

**Comment by lloyd** [comment]
Cool, Ty @seanmonstar!

So this is for the dialog to sign in at time of first app purchase? Or for dialog when signing in to websites? Or both?

What are desired semantics of logout?  Logs you out locally?  Form the current site?  

How about logoutEverywhere?  Does that log you out on other devices?  All sites on current device?  Destroy your session with persona services?

Meta question is how do functions designed for internal use or use by sites on the web map into b2g...

-- lloyd (thumb-typing)

**Comment by shane-tomlinson** [comment]
@lloyd - you are not supposed to be working today.

**Comment by lloyd** [comment]
Yeah man.  But my baby is sleeping on me.  Also, I think it is critically important we focus on describing high level product requirements in bug reports, rather than implementation details.  So I guess I'm on a crusade here :)

-- lloyd (thumb-typing)

**Comment by shane-tomlinson** [comment]
@lloyd - 

These are both thin wrappers around their user.js equivalents. For now, these will act exactly like they do in the normal web flow.

Calling BrowserID.internal.logout will log the user out of the specified origin on the current device. When you log out of a site on one device, it has no effect on another device. This has never been synced across devices.

Calling BrowserID.internal.logoutEverywhere clears your session and marks all sites as logged out on the current device - this too has never been synced across devices. A better name for this may be logoutAllSites.

The meta question will be hammered out further tomorrow with @benadida. The internal API is going to be updated, driven by high level requirements (some of which are outlined in the etherpad that you and @anantn wrote 6 months ago) In theory, I would like the internal API to provide an interface similar to navigator.id so there is minimal friction for developers embedding the dialog in web views.

**Comment by seanmonstar** [comment]
This was fixed!
