### ISSUE TITLE
Implement Secondary <-> Primary UX Tweaks

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2569]
Per BigTent UX Improvements discussion... skinny wants a set of prototypes to test against users.

I'm guessing we need:

**high priority**

1) First time Persona User with Primary supported email address
2) Returning user from #1, second sign in flow
3) Existing Persona User with a Secondary account, First time signing in since Primary started supporting that email address

**lower priority**
1) Returning user with existing Primary account, first time signing in since Primary stopped supporting email address (without warning)
2) Returning user with existing Primary account, first time signing in since Primary started advertising removal of support
3) Returning user with existing Primary account, first time signing in since Primary stopped supporting email address (after advertising removal of support)

**Comment by shane-tomlinson** [comment]
link to #1039

**Comment by skinny97214** [comment]
tasks to test migration

#1 log in (show secondary flow)
#2 log in to another site (show secondary to primary migration)
#3 log in to another site (show primary flow)

**Comment by ozten** [comment]
Discussing with Crystal
- If a user has never used a primary, they should not see a transition screen
- it is okay, but not ideal, if this is per-device (no db support needed)

Putting these requirements together, we should be able to store in local storage the fact that the user is using a secondary address or a primary address and then trigger transitions from there.

**Comment by ozten** [comment]
Working in a new branch based on f9880c620339292f429fac57445f5a5572c97066 per stomlinson

/CC @lloyd

**Comment by ozten** [comment]
Working off a new branch based on dev, actually.

per discussion with skinny, we'll go ahead and implement these improvements, then do UX review. This is because doing a full A/B user testing of these features isn't really possible for a couple of reasons

a) No A/B testing framework
b) Too much "roll playing" or the need for a set of primaries that could be flipped on and off during user testing to cause the different cases

**Comment by ozten** [comment]
Chatted with @shane-tomlinson 
- we should use id instead of email
- this feature should eventually work across sessions, which is related to Issue #1500 but we don't want to block on 1500

**Comment by ozten** [comment]
So `storage.clear` currently clears everything that storage tracks.

It is called from user, when the user isn't authenticated.

This makes sense, as it has an email to user id mapping, sites visited, and other sensitive data.

I'm wondering if we can't add a hashed email to last known state map, which is not managed by `clear`.

```
{ 'a878234ab': { 'type': 'secondary', 'updated': 1350577448476}}
```

**Comment by lloyd** [comment]
if we use localstorage for this we cannot guarantee once per user, it's once per user per device, per browser reset.

**Comment by ozten** [comment]
lloyd has reworked this bug into
- Issue #2606
- Issue #2607
- Issue #2608

Closing, as this bug is too high level, we'll further split it into smaller chunks we can swarm on.
