### ISSUE TITLE
A cert can be dropped to the browser without being authenticated with BrowserID.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#257]

**Comment by benadida** [comment]
I'm not sure this is a bug. What if you aren't logged into BrowserID, but then you do log in. I think you want the certs that were dropped to appear in your list.

**Comment by shane-tomlinson** [comment]
@benadida - For public machines, I would disagree with this.  Doing so would be allow a BrowserID user to gain identities for users that used the machine before them where they may not have an account.

**Comment by benadida** [comment]
that's a great point. Dan and I were discussing something similar recently, which might apply here. We thought that, in the case of a public machine (as declared by user), we could make it so certs are issued for only a few minutes' validity (say 5 minutes). This could apply here for not-logged-in users.

**Comment by lloyd** [comment]
should we move this to the primaries milestone?

**Comment by benadida** [comment]
yep, looks like you did it :)

**Comment by lloyd** [comment]
no longer true with the primary support implementation in dev now.  closing.
