### ISSUE TITLE
"Forbidden: no cookie" response in Chrome 22 from "auth_with_assertion"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2575]
This prevents the user from logging in when using BigTent.

STR

1) in Chrome 22, ensure that cookies are set to "Allow local data to be set (recommended)
2) open dev.123done.org
3) Click "Sign In"
4) Open Chrome Dev Tools, select "Network"
5) In the dialog, enter a Yahoo! address.
6) Log in to Yahoo! if needed.
7) When the user is returned to the dialog, they see:

```
"Persona requires cookies to remember you.
Please close this window, enable cookies and try again"
```

8) Look at the Chrome Dev Tools network console for /wsapi/auth_with_assertion, the BrowserID Request cookie is sent.

**Comment by ozten** [comment]
The first time this morning, I saw "Persona requires cookies to remember you."

Now 6 times in a row I see "We are very sorry. There has been an error!"

```
{"success":false,"reason":"issuer 'login.dev.anosrep.org' may not speak for emails from 'yahoo.com'"}
```

which is a known bug warner is working on.

Are you reproducing this 100%? Are you doing other steps like clearing cookies, caches, or ?

**Comment by ozten** [comment]
via IRC "Chrome->Clear Browsing Data" "I cleared everything forever and ever"

I've done this 4 times and am unable to hit the 3rd party cookie thing.

**Comment by ozten** [comment]
Does this reproduce with non-bigtent IdPs too?

**Comment by shane-tomlinson** [comment]
I can no longer reproduce this. Closing.
