### ISSUE TITLE
Add deployment_rate setting to proxy_idps to support gradual deployment

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2577]
We don't have a great load testing tool for BigTent.

We can support gradual deployment of users on a per-proxy IdP basis.

Add `deployment_rate` setting to each idp in [proxy_idps](https://github.com/mozilla/browserid/blob/dev/lib/configuration.js#L235) config.

It's value is a float between 0 and 1. Default value is 1. Email addresses will be mapped into an md5 hash and the deployment rate will be used to calculate if an email address should have BigTent available or if it should continue to use the secondary.

Old config:

```
proxy_idps = {
    "yahoo.com": "yahoo.login.persona.org",
    "gmail.com": "google.login.persona.org"
}
```

New config:

```
proxy_idps = {
    "yahoo.com": {
        "host": "yahoo.login.persona.org",
        "deployment_rate": 0.3
    },
    "gmail.com": {
        "host": "google.login.persona.org",
        "deployment_rate": 0
    }
}
```

**Note;** `deployment_rate` is like Freedom Rock, once turned up, it must never be turned down. Making this number lower than it had previously been will cause uses to flop back to the Secondary.

The mapping is deterministic. As overall traffic increases, a consistent fraction of that traffic will hit BigTent.

**Comment by lloyd** [comment]
I love this idea!  I want to lick it!

@bwarner can you suggest a simple hash function to map email addresses into 0..1 ? It obviously needn't be perfect, but simple and functional.  I have found plenty of interesting options on the intertubes, but you're more qualified than them.

**Comment by callahad** [comment]
What if we _have_ to turn it down? (Rollback / revert of the train, for instance.)

Maybe we should only roll this out to users with Persona passwords, so flopping back isn't terrible?

**Comment by lloyd** [comment]
I think solving this (have to turn it down) is a pre-requisite to shipping bigtent and pertinent to IdP support in general.

+1 to thinking through user flows and making sure we can do this in a user understandable way for both bigtent and other email providers.

**Comment by callahad** [comment]
I think we also need to figure out how verification of users works when we're partitioning like this. How do you get the right public key / issuer as a verifier?

**Comment by ozten** [comment]
callahad via Email:

I believe we have a related issue with the proposal for rolling out BigTent to fractions of a domain, instead of everyone at once:
1. With Yahoo's exposure rate at 50%, half of users will have certs backed by login.persona.org, half will have certs backed by BigTent.
2. If dynamic well known is based solely on the domain of the email, it would get it wrong 50% of the time.

**Comment by ozten** [comment]
> With Yahoo's exposure rate at 50%, half of users will have certs backed by login.persona.org, half will have certs backed by BigTent.

Depending on how we refine the discover process (an active discussion between Ben and Brian), this is probably not an issue with _correct_ verifiers.

> If dynamic well known is based solely on the domain of the email, it would get it wrong 50% of the time.

ah, without the local part of an email address, Dynamic well known lookups against the secondary will not be deterministic. Good call.

**Comment by callahad** [comment]
Right, and revealing the local part when trying to look up a public key feels like a no-go from a privacy standpoint...

**Comment by ozten** [comment]
I'm cool with closing this.
