### ISSUE TITLE
Need the ability to sync emails backed by certs across browsers.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#258]
Means if a cert is dropped into one browser, we should have the ability to request a cert from another browser.  Requires backend support I believe.

**Comment by lloyd** [comment]
I'm confused.  Why do this instead of just having the issuer of the cert issue a new cert?  Given cert lifetime is 2-6 hours, is there any value here?

**Comment by shane-tomlinson** [comment]
@lloyd - at the moment if you have a cert added on machine 1, on machine 2 you do even know that a cert has been added.  This means your potential list of emails is out of sync.  The certs themselves should not be synced, instead the list of emails should be, including those that are backed by certs.

**Comment by lloyd** [comment]
ok, so really we're saying "Server needs to know about primary email addresses"

**Comment by shane-tomlinson** [comment]
That is indeed the case.

**Comment by benadida** [comment]
yes, and we waited on this for you @lloyd :) because this requires a data model change that I didn't want to do.

I don't think this is required for launching primary support. We could start with only-local-machine primary support, and then eventually sync'ed primary support.

**Comment by lloyd** [comment]
should we move this to the primaries milestone?

**Comment by lloyd** [comment]
this is solved.
