### ISSUE TITLE
Persona emails getting caught up by Zimbra / Postini?

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2581]
According to some of the UR folks who were in town yesterday, Persona registration and password reset emails to mozilla.com addresses are getting caught by Zimbra and Postini's built-in spam filter. Eek!

Also reported internally: https://www.yammer.com/mozilla.com/#/threads/show?threadId=218145946&messageId=218145946

**Comment by jrgm** [comment]
Hey @callahad do you have more info from UR folks about details of the messages quarantined. I'll ask around with IT folks about tracking this down.

**Comment by jrgm** [comment]
In particular if they have the SMTP headers for the emails that got quarantined that would be useful to the mozilla admins for figuring out why they were blocked.

**Comment by jrgm** [comment]
I got headers from Ludovic and am working with admins to figure out why it was quarantined.

**Comment by jrgm** [comment]
Our instance for Postini did flag this as spam. IT is asking for more info on what triggered that (although apparently mozilla has very aggressive settings). The sender address we use has been whitelisted for mozilla.com, but I'm considering asking to have that reversed. I really want to know what is not kosher about our content and/or headers, and would rather feel the pain @ mozilla until we know that. Thoughts?

**Comment by callahad** [comment]
+1. We can trust people with Mozilla email addresses to be sufficiently aware of / persistent with Persona to survive this friction, and it will ensure that we get this fixed for folks at other organizations. (Because, seriously, if it happened to us...)

**Comment by jrgm** [comment]
Okay, the exemption has been removed.

**Comment by lloyd** [comment]
is this still a 5 star?

**Comment by jrgm** [comment]
We can mark this four star. IT is working to get an answer from Postini about what in particular triggered this being marked as spam.

**Comment by jrgm** [comment]
Hmm, I thought I had closed this. At any rate, there is no specific answer from Postini about why it was flagged. Mozilla has very high sensitivity settings which contribute to false positives. I had asked that IT not whitelist us. This will just have to a canary. Not a terrific answer, but closing this issue.
