### ISSUE TITLE
ephemeral deployments not serving static resources

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2587]
With change 1173c2d7c173e9deabe9209b4136006935f1bfaa we broke serving of static resources on ephemeral instances.  Because ephemeral aws deployments use `production.json` then overlay `aws.json`, the addition of `public_static_url` to the former caused ephemeral instances to serve static resources from `https://static.login.persona.org`.

**Comment by shane-tomlinson** [comment]
Closing as fixed with #2588
