### ISSUE TITLE
Reduce the size of images by removing unnecessary bytes images

### ISSUE THREAD

**Issue by Lennie** [mozilla/persona#2596]
As a test I ran the following files through:

http://www.smushit.com/ysmush.it/ (the site does not support downloading from HTTPS directly so you'll have to upload them by hand)

image - result size - savings - % savings

https://login.persona.org/v/7ec8bdec1f/common/i/button-arrow-active.png  331 bytes  846 bytes  71.88%
https://login.persona.org/v/8b6dbe4ebd/common/i/button-arrow-hover.png   452 bytes  1002 bytes  68.91%

As you can see that does help, although if issue #2595 is applied the effect is probably gone.

**Comment by shane-tomlinson** [comment]
@fmarier - we had done this once before, but this was many moons ago and several images have been added since then.
