### ISSUE TITLE
Inline the communication_iframe scripts

### ISSUE THREAD

**Issue by Lennie** [mozilla/persona#2597]
It probably needs some testing, but it might be a good idea to just combine the following files in one response:

https://login.persona.org/communication_iframe
https://static.login.persona.org/v/d01d1d543a/production/communication_iframe.js

Looking at the HTML-output it looks like it might be cachable like the javascript code in that case the files could be combined in one file.

(might not be very compatible with CSP)

**Comment by fmarier** [comment]
Yeah, I think we are hoping to enable CSP for security reasons, so this may not work.

**Comment by shane-tomlinson** [comment]
@Lennie - Thanks for the suggestion! @fmarier is correct, inlining scripts in the communication iframe is not compatible with CSP, which we want to enable shortly. Closing for now, but we will keep this in mind when weighing the tradeoffs between performance and security.
