### ISSUE TITLE
turn up crypto parameters for certs

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#260]

**Comment by benadida** [comment]
so it turns out that the current crypto params are equivalent to what we have in production: 512-bit RSA keypairs. This is, of course, not sufficient for the long run, but before we turn it up, I want to run some performance tests and see what we can improve. We may switch to DSA before we up the keypair length.

@lloyd the big issue is the generation of the browserid root key. That key needs to be bigger. I've tweaked generate-keypair to at least use 1024-bit keys, but we eventually want 2048 keys.

**Comment by lloyd** [comment]
I don't understand why we don't just jump to 2048 keys?  Are we worried that the poor performance will make testing laborious?  

One thing that it would force is for us to properly handle delays in computationally expensive code.  We do some dumb things like generating all certs for all emails at once, rather than when they're needed.  upping now would force us to address issues like this..  dunno.

**Comment by benadida** [comment]
2048 bit keygen performs extremely poorly even in modern browsers. We shouldn't upgrade until we have a better path.

And no, the solution really isn't to call yield in computationally expensive code, we have to find a better solution, which is why I'm investigating DSA as a replacement for the sig algorithm. Alternatively, use Web Workers.

**Comment by lloyd** [comment]
I suggest we move this conversation over to issue #278

**Comment by lloyd** [comment]
darnit, I meant issue #244

**Comment by benadida** [comment]
oh and I agreed with #278 :)

**Comment by lloyd** [comment]
removing the in-dev label, because nothing is actually in dev.  decreasing the priority down to four stars because we're willing to ship 512 bit keys in production (given that turning them up without other some of the other optimizations we're planning would make the system unusable)

**Comment by benadida** [comment]
dsa support now merged, keys upgraded to DSA with 2048 bit keys.
