### ISSUE TITLE
[stage] Unable to add '@yahoo.com' email addresses

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2602]
Browser: FF 16.0.1
OS: Ubuntu 12.04

Steps: 
1. Go to www.beta.123done.org or www.beta.myfavoritebeer.org and press on Sign in with Persona
2. In the sign in dialog enter any 'yahoo.com' email address and press on next

Expected:
User should be able to sign in 

Actual:
"We are very sorry. There has been an error!" message is displayed. User is not able to set up a persona account or add a new email to an existing account using a 'yahoo.com' address.

**Comment by jrgm** [comment]
Thanks @csuciu 

@gene1wood, @ozten - we need to disable bigtent in stage while train-2012.10.12 is on the tracks in stage

The request for `https://login.anosrep.org/wsapi/address_info?email=abcabdab1%40yahoo.com` returns 200 OK in about 1 seconds with body `{"auth":"https://yahoo.login.anosrep.org/authentication","prov":"https://yahoo.login.anosrep.org/provision","type":"primary"}`.

---

Subsequent to the address_info request the browser loads `https://yahoo.login.anosrep.org/provision`, `https://login.dev.anosrep.org/provisioning_api.js`, and `https://yahoo.login.anosrep.org/provision.js` as 200 OK, but I get these two JS errors on FF16:

```
Error: uncaught exception: target window is same as present window -- not allowed

Error: TypeError: navigator.id.beginProvisioning is not a function
Source File: https://yahoo.login.anosrep.org/provision.js
Line: 17
```

**Comment by jrgm** [comment]
Actually, sorry. Those JS errors are shown if I load `https://yahoo.login.anosrep.org/provision` directly in the browser. My mistake.

**Comment by ozten** [comment]
> @gene1wood, @ozten - we need to disable bigtent in stage while train-2012.10.12 is on the tracks in stage

Filed https://bugzilla.mozilla.org/show_bug.cgi?id=802645

**Comment by jrgm** [comment]
This has been fixed. @yahoo.com addresses are now treated as secondaries on stage.
