### ISSUE TITLE
"We are sorry, this request is taking to long" is displayed every time for '@yahoo.co.uk' email addresses 

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2603]
Browser: FF 16.0.1, Chromium 20.0.1132.47
OS: Ubuntu 12.04
1. Go to www.beta.123done.org or www.beta.myfavoritebeer.org and press on Sign in with Persona
2. In the sign in dialog enter any '@yahoo.co.uk' email address and press on next. 

Expected: 
"Confirm your email address" message  pops up

Actual:
"We are sorry, this request is taking to long" message is displayed every time for a few seconds before you are ask to "Confirm your email address"

I only saw this for 'yahoo.co.uk' email addresses

**Comment by jrgm** [comment]
@ozten, @gene1wood - This is true in production too. The request for https://login.persona.org/wsapi/address_info?email=5a433f9e76784632d%40yahoo.co.uk takes ~15 seconds and returns 200 OK with body 
`{"type":"secondary","known":false}`

@gene1wood - what is the cause of the delay in production? When I do `time curl -D - http://yahoo.co.uk/.well-known/browserid` from my laptop that only takes ~400ms.

**Comment by gene1wood** [comment]
My first guess would be the cause is the id proxy servers and may be the same issue reported here : https://bugzilla.mozilla.org/show_bug.cgi?id=775177

**Comment by jaredhirsch** [comment]
@jrgm: haha, you used http, not https. try time curl -D - https://yahoo.co.uk/.well-known/browserid and it will take well over a minute. My guess is that squid is timing out at 15 seconds.

```
jareds-partybus:~ jhirsch$ time curl -D - https://yahoo.co.uk/.well-known/browserid
curl: (7) couldn't connect to host

real    1m15.443s
user    0m0.006s
sys 0m0.006s
```

@gene1wood is wondering if we need to use https to fetch a well-known?

the relevant snippet of code is here:  https://github.com/mozilla/browserid/blob/dev/lib/primary.js#L185

**Comment by gene1wood** [comment]
Here's yahoo.com exhibiting something similar

```
user@host ~$ time curl -D - https://yahoo.com/.well-known/browserid
curl: (35) Unknown SSL protocol error in connection to yahoo.com:443 

real    0m12.555s
user    0m0.000s
sys 0m0.008s
```
