### ISSUE TITLE
Improve user messaging when email provider (dis|en)ables persona support

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2606]
When an email provider enables persona support (adds a `.well-known` document, etc), a user that _was_ using the persona service previously with an address from this provider should see clear one-time messaging.

Basically, the user's experience will change significantly, we should tell them how it's changing and why this is good for them.

The same reasoning exists for opposite case: an email provider drops persona support.

@skinny97214 - This requires two new screens.

**Implementation Ideas:**

Implementing this will probably require two bits of information:
1. the last state the provider of the email address was in when the user used it (primary or secondary)
2. the current state the provider of the email addess is in (primary or secondary)

if #1 and #2 don't match we should send down a `transition` bit to front-end code.

**Comment by seanmonstar** [comment]
assigning to @skinny97214, since the description mentions depending on new screens.
