### ISSUE TITLE
When email providers transition, certificates should be invalidated

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2607]
In order to smoothly handle the moment when an email provider brings persona support online, we should have a way to instantly disable outstanding certificates for the domain in question.

Specifically, this scenario details the issue:
1. User logs into a site with persona using `foo@example.com` - `example.com` is not a primary
2. User now has a certificate issued by `login.persona.org` in their local storage
3. `example.com` comes online as a persona provider
4. User goes to log into a different site
5. User issues an assertion using the cert issued by `login.persona.org`
6. Site attempts to verify assertion, discovers that `example.com` _should_ be the issuer
7. User is unable to log in until certificate expires.

The solution may be to, during step 4, invalidate certificates.  This could be achieved in a variety of different ways, and will require re-checking the domain (and/or cache) and sending down information to the client so that we can invalidate certificates.

**Comment by shane-tomlinson** [comment]
link to the closed #1039

**Comment by shane-tomlinson** [comment]
Initial implementation was done in f9880c620339292f429fac57445f5a5572c97066.
