### ISSUE TITLE
[bigtent] https://yahoo.login.anosrep.org/ needs an Access-Control-Allow-Origin header to load fonts correctly in FF

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2610]
STR
1. Load `https://yahoo.login.anosrep.org/authentication` directly in the browser.

When I load that, I get this JS error message in FF16:

```
Error: downloadable font: download failed (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:3): status=2152398850
source: https://yahoo.login.anosrep.org/fonts/OpenSans-Regular.woff
Source File: https://yahoo.login.anosrep.org/css/style.css
Line: 0
Source Code: @font-face {   font-family: "Open Sans";   font-style: normal;   font-weight: 400;   src: local("Open Sans"), local("OpenSans"), url("/fonts/OpenSans-Regular.eot") format("embedded-opentype"), url("/fonts/OpenSans-Regular.woff") format("woff"), url("/fonts/OpenSans-Regular.ttf") format("truetype"); }
```

The headers for `https://yahoo.login.anosrep.org/authentication` need to include something like
`Access-Control-Allow-Origin: https://yahoo.login.anosrep.org` to eliminate the error (review that carefully from a security pov; I'm just suggesting that off the top of my head).

**Comment by jrgm** [comment]
Oops, I meant that the headers for the font files served from yahoo.login.anosrep.org need to include the `Access-Control-Allow-Origin` header.

**Comment by ozten** [comment]
This is a bigtent server change, right?

**Comment by ozten** [comment]
Weird, we don't need Access-Control-Allow-Origin if the fonts are served by the same server as the CSS and HTML... right?

**Comment by jrgm** [comment]
Hmm, yeah the css and font have the same origin. Well, I'm unclear why the error then. But it is there.

**Comment by ozten** [comment]
Confirmed... weird.

Fixed in [697943c8ffb68](https://github.com/mozilla/browserid-bigtent/commit/223e390de903f4cf612b2caff9450d3d9a944baf)

**Comment by jrgm** [comment]
Okay, with browserid-bigtent train-2013.01.17 160f4c0, visiting https://yahoo.login.anosrep.org/authentication, the content is served with `Access-Control-Allow-Origin: https://yahoo.login.anosrep.org`.

However, with an empty cache shows this javascript error. I think the issue is that in transitioning among pages in the authentication, we're aborting the load of this woff file, which then causes firefox to show an error. Bleh.

Anyways, while it's ugly to have errors being reported, I don't think this impacts any functionality.

This is related to  mozilla/browserid-bigtent#120

**Comment by ozten** [comment]
Loading /errors was how I reproduced the issue as well as checked for a fix after adding the headers.

This page is stable and won't redirect.

Good point about pages with redirects.
