### ISSUE TITLE
Persona doesnt appear to work in IE9(32bit) and Windows 7 pro 32 bit

### ISSUE THREAD

**Issue by ajazam** [mozilla/persona#2614]
Hello,

I've spent too much time getting persona to work with IE9 and windows 7 Pro 32 bit.
My IE 9 (32 bit) is 9.0.8112.16421 update 9.0.10
And windows 7 pro (32bit ) SP1 and fully patched to today (17/10/2012)

I keep getting told that the browser is not supported. I do not have any special addons installed. The problem also occurs on two other PC's ive tested it on so it's not isolated.

However it works (the login box appears and can login) with the following combination

IE9 (32 bit) 9.0.8112.16421 update 9.0.9 with windows 7 pro SP1 64 bit 
IE9 (64 bit) 9.0.8112.16421 update 9.0.9 windows 7 pro SP1 64 bit
Firefox 15.0.1 windows 7 pro SP1 64 bit.

Anybody got an pointers to what I should do next?

Jabbar Azam

**Comment by shane-tomlinson** [comment]
Hi Jabber,
I am sorry to hear about your problems with IE9 on Win7. I regularly test in IE8 and 9 but in Win7 64 bit. The site that you are trying to sign in to, does it have a doctype set which forces the browser into standards mode? Is the doctype declaration on the very first line of the document? Finally, can you log in if you browse to 123done.org?

Sent from my HTC

----- Reply message -----

**Comment by callahad** [comment]
@shane-tomlinson Will a site running in compatibility mode force IE9 to render a Persona popup in compatibility mode?

**Comment by shane-tomlinson** [comment]
@callahad - no, but it will stop the site from having window.JSON and there were other problems - see #803

**Comment by seanmonstar** [comment]
It shouldn't affect the actual dialog, but since it's needed from the include.js (which runs on a page in compat mode), then the "unsupported" dialog will get shown.

**Comment by callahad** [comment]
Aaah! That makes sense. Thanks. I don't think we emphasize in the docs that RPs need to be using standards mode for IE. I'll file a new docs issue to make sure that gets added to our best practices page.

**Comment by jrgm** [comment]
I have the exact same OS+IE versions as 32-bit
IE: Version: 9.0.8112.16421, Update version: 9.0.10
Windows 7 Pro, Service Pack 1, System Type: 32-bit operating system
All updates applied

and I'm not having an problem with using persona. (Sorry, not that it helps you that my system works ;-( ).

**Comment by ajazam** [comment]
Sorry for the late reply, I went home after I created the initial issue. The doc type I use is

<!DOCTYPE html>

I'll see if there is another more appropriate doctype I can use.

I can also login to 123done.org.

I'll check the source for 123done.org

**Comment by shane-tomlinson** [comment]
@ajazam - this is the appropriate HTML5 doctype, is it on the very first line of the document?

**Comment by ajazam** [comment]
I had a look at the html and found I didn't have the following

```
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
```

The website works now. Thank you all for a fast response.

**Comment by shane-tomlinson** [comment]
@ajazam - thanks for following up with the solution! As reported in #796, users of Google Chrome Frame cannot log in using Persona. You will have to remove the `,chrome=1` portion of the above declaration for GCF users to correctly sign in.

Also related - #2566
