### ISSUE TITLE
Emphasize that RPs need to be using standards mode on their pages

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2616]
If IE renders a site in compatibility mode, it won't have window.JSON or other things that Persona needs. A small note somewhere in the docs should highlight that sites must be rendered in standards mode.

**Comment by callahad** [comment]
See: #2614

**Comment by seanmonstar** [comment]
Specifically, IE8 or higher mode.

**Comment by wbamberg** [comment]
I've added a section on this in "Browser compatibility": https://developer.mozilla.org/en-US/docs/persona/Browser_compatibility.

I also noticed that this page says:

> When forced to emulate IE8, Internet Explorer 9 may fail to log in to sites.

Is this correct? I thought it was IE7 emulation that was a problem? Or is this a different problem?

**Comment by jrgm** [comment]
I don't think that is correct. @callahad can you comment. I don't recall the specifics.

**Comment by callahad** [comment]
I don't recall that being the case. Let's nuke that sentence. Otherwise, the page looks good to me!
