### ISSUE TITLE
improve diagnostic value of monitoring

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2617]
We are going to improve our monitoring focusing on outbound traffic from per-colo load balancers.  We believe we can get extremely timely alerts at extremely low cost using this approach (i.e. detect spikes in 50x responses, detect slow queries that should not be, etc.)

To improve the speed of diagnosis of these failures, we should include a new header in all responses that tells us all of the processes that touched the request, and what machines they are running on.

**Implementation Ideas**:

Header may look like:

```
X-Debug-Path: p-r-1, p-w-1, p-sw-3
```

this fictional header includes the colo ("p" could mean PHX1), the and the process ("r-1" could mean router on the "1" node).  We need to figure out how to represent these three pieces of information:
- colo
- machine within colo
- process running on machine within colo

Further, the comma separated list allows you to understand each of the nodes involved.

Suggest we introduce a configuration parameter like `process_id` that is an opaque string with these three bits of information, then figure out a simple way to integrate it into our stack.

**Comment by lloyd** [comment]
an additional idea that may be a second phase would to be to have timestamps embedded in said header to help isolate sources of latency.

**Comment by jaredhirsch** [comment]
this looks good to me.

It would be cool to use a naming scheme that doesn't require manual intervention to scale out. For instance, if we use hostname & pid in the header, we could make the hostname reflect the role, or map hostnames to roles when we process logs.

**Comment by lloyd** [comment]
This sounds reasonable.  I was thinking we can leave the string completely opaque to our software and let gene solve it with configuration.  Appending PID would handle the case where we run multiple process instances on a single box though, which we may do.  <hostname>:<process type>:<pid> ?

they get longer, but if we strip we don't really care, right?

**Comment by gene1wood** [comment]
Ya, I'd second @6a68's comment and collapse the "datacenter-role-servernumber" into "hostname" since we (ops) already deal with the question of turning hostnames into datacenter, role etc.

**Comment by jaredhirsch** [comment]
grabbing this, looks like it'll be fun

**Comment by lloyd** [comment]
yay!  have fun!

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
