### ISSUE TITLE
[IE9] ugly flash in /sign_in dialog when signing an already authed user

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2618]
STR
1. Go to 123done.org (or beta.123done.org)
2. Click signin and finish being authenticated
3. Back in 123done, click logout and bring up the dialog again
4. Click signin in the dialog

There's a flash of 'Finishing signing in..' in the dialog for less than a second, which is a bit ugly.

ISTR that I filed this issue before for IE. There's also GH-2320 which is for Opera.

IE8 shows the 'Finishing signing in...' as well, but  for a long enough period of time that it "feels" OK. But on IE9 it has a feel of "WTF was that?".

This is on stage and in prod. Not sure why I didn't notice this before. I guess if you don't watch closely you don't notice?

**Comment by jrgm** [comment]
So, I guess I was just forgetting that I had already filed this 4 months ago in GH-1705 o_O. 

Anyways, it seems much more jarring on IE9 now.

**Comment by jrgm** [comment]
Hey @shane-tomlinson or @seanmonstar : give this a try on IE9, and see what you think. (No this bug doesn't affect actual usage of the dialog, but is a fairly significant visual flaw).

**Comment by seanmonstar** [comment]
That flash is oogly.

**Comment by jrgm** [comment]
Thanks @seanmonstar, bump to 4-star. (Yes, the world won't fall apart if this remains, but oogly is oogly).
