### ISSUE TITLE
[dev] signin with primary email address not working in dev

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2624]
STR
1. Load http://dev.123done.org and click signin.
2. In the dialog, enter an @eyedee.me email address.
3. When prompted, click 'sign in with eyedee.me'.
4. On eyedee.me, enter a password and click 'Sign in'.

The dialog returns to /sign_in#AUTH_RETURN, but doesn't complete signin.
Eventually, the error screen is shown with 'Action: Checking Email Address'.

This is working fine in stage and prod.

**Comment by ozten** [comment]
I can reproduce, following the STR.

https://eyedee.me/api/whoami

```
{"user":"ozten"}
```

I don't see the next expected call, a POST to eyedee.me/api/cert_key

Interestingly, **no repro** if I log into eyedee.me directly first.

Unable to troubleshoot with Chrome/Safari Dev Tools, getting "Uncaught TypeError: Cannot read property 'd' of undefined " dialog.js line 3.

**Comment by ozten** [comment]
Eyedee.me always uses the SHIM from https://browserid.org. Is this a valid test case? Maybe this isn't failing as soon as it did before?

**Comment by lloyd** [comment]
taking

**Comment by lloyd** [comment]
NOTE: @ozten 's comment about "cannot read property 'd' of undefined" was a separate five star, issue #2629, now fixed in dev.

Thinking the easiest way to move forward on this one is to bisect and isolate the commit where the breakage was introduced.

**Comment by lloyd** [comment]
from deep in the bowels... 

```
error: "runtime_error"
id: 264228
message: "{"message":"generator isn't seeded"}"
```

This may mean that the codepath used in #AUTH_RETURN is not seeding the random number generator.  This may be related to load time optimizations, as I believe that the session_context call seeds said generator...
