### ISSUE TITLE
navigator.id.rerequest ??

### ISSUE THREAD

**Issue by davesann** [mozilla/persona#2625]
https://groups.google.com/d/topic/mozilla.dev.identity/49I-npdQvUM/discussion

If you are writing a single page app and, for whatever reason, the session times out on the server, the only way I know to auto login the user is by refreshing the page. 

Is it possible to enhance the api to allow a login re-request that will act like a page refresh to the extent that:
1. Like a page refresh - if a user is logged in through persona and a valid assertion is available, this will be used  to request validation from the server and establish a new session.
2. If there is no valid assertion, only then will the user be asked to login.

I don't think that you should be forced to refresh the page if persona already has the ability to do auto login. It is, in some cases, bad user experience.

**Comment by callahad** [comment]
Next steps: I'm going to see if I can come up with a good workaround, then I'll have a broader discussion with @vthunder and @lloyd to see if there's a way we can kill a bunch of birds, including this one, with one stone :)

**Comment by jrgm** [comment]
@callahad do you want to close this and propose a discussion on the email list? There's no specific action to be done for this ticket. Closing.
