### ISSUE TITLE
[dev] dialog stuck at "Connecting to Persona..." in chrome

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2629]
STR:
1. visit dev.123done.org
2. click the button
3. notice the dialog is stuck

cannot reproduce on firefox, but occurs on recent chrome both in OSX and linux

**Comment by lloyd** [comment]
I bisected this issue and found a the offending commit: 

```
3e49e6f06060e7ff03db1316f49644808cde88e7 is the first bad commit
commit 3e49e6f06060e7ff03db1316f49644808cde88e7
Author: Shane Tomlinson <stomlinson@mozilla.com>
Date:   Tue Oct 16 13:30:06 2012 +0100

    Remove withContext from the cookie check to speed up dialog startup.

    withContext will be still called when an XHR request needs the context.

    Updated the unit tests to make use of network.init({ cookiesEnabledOverride: xxx }); instead of     transport.setContextInfo("cookies_enabled", xxx); The context info's cookies_enabled field was never actually checked anywhere.

:040000 040000 9294495a9c46977250bd848d82a7717f28c96ebf 0fe60b9e41f3437058baa485ef00c1a5d77c106e M  resources
```

**Comment by lloyd** [comment]
in chrome, there is a console error: "Uncaught TypeError: Cannot read property 'd' of undefined"

**Comment by lloyd** [comment]
I've dug down into this issue.  It seems that the change @shane-tomlinson made change our load timing (of course).  It further seems like winchan.js, subsequent to invocation of 'onOpen' expects a single message to be posted to it.  Further, it seems like browserify uses postMessage to implement a browser happy version of `.nextTick()` so nodejsy code can run in your browser.

So this change causes a browserify message to be posted, that gets caught by winchan after invocation of onOpen, that causes winchan to puke, because the message is not what it is expecting.  And this only manifests on chrome with minified resources.

**Comment by lloyd** [comment]
fixed in dev.

**Comment by benadida** [comment]
oh man, I can see why @lloyd vomited.

@lloyd is there a way to look at the postMessage event source to make this judgment call rather than the slightly less robust check you're doing? Not a blocker, just a suggestion.

**Comment by lloyd** [comment]
On Oct 24, 2012, at 4:59 PM, Ben Adida notifications@github.com wrote:

> oh man, I can see why @lloyd vomited.
> 
> @lloyd is there a way to look at the postMessage event source to make this judgment call rather than the slightly less robust check you're doing? Not a blocker, just a suggestion.
> 
> yeah, great idea.

@seanmonster suggested this as well.  There are at least two more checks you can add to make the re-emergence of this bug less likely:
1.  `event.source` should be the same as `window.opener`
2.  make the string "request" much more unique, less likely to collide

Both of these are good ideas, but I'd want to test the `event.source == window.opener` check in all browsers we support, cause it's the web!

**Comment by ghost** [comment]
Might this also explain why I'm seeing the same thing on iOS?

Regards,
Dan Walkowski

**Comment by lloyd** [comment]
yes!  please point over to dev (login.dev.anosrep.org) and tell us if things seem fixed there!

lloyd

**Comment by jrgm** [comment]
The fix for this has been merged and deployed on stage. In my testing with the Chrome/JellyBean device where I formerly could see this error occasionally, I cannot see it now. 

Does anyone have any other results on stage?
