### ISSUE TITLE
no client validation error when creating address without .suffix

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#263]
There is no client side error if a user enters an email address without the .suffix.    Client side errors should check @ and . symbols.

Repro:
1) visit current.openphoto.me
2) click browserID signin
3) click add a new email address
4) type in an email address without the suffix (eg.  Tony@badass)  
5) click continue, and verify user is taken to next screen

Expected:
- error halts client cause i'm missing the suffix in my email address

Actual:
- no suffix still can proceed through sign in path.

**Comment by shane-tomlinson** [comment]
@tonychung - The reason is because the name@domain passes the HTML5 email field RegExp.  You are correct in that this should be made more strict, with the UX redo, we are going to have to come up with a consistent way to do validations and error messages.

**Comment by shane-tomlinson** [comment]
8968fef93c082c4db987240feb8d2c149cf0b200 fixes this.
