### ISSUE TITLE
[dev] siteName not being used in '%s uses Persona instead of usernames....' in dialog.js

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2632]
Oops.

![img](http://i.imgur.com/b8b4U.png)

**Comment by jrgm** [comment]
Note: this is fine in stage train-2012.10.12. This got lost in GH-2556.

**Comment by jrgm** [comment]
Marking 5-star to have this not be like this in the upcoming train.

**Comment by lloyd** [comment]
+1 to 5 stars.

**Comment by shane-tomlinson** [comment]
This only manifests if the RP supplies siteName. Nice catch @jrgm.
