### ISSUE TITLE
undefined variable used to call toString on error path from GH-2621

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2636]
At line 208 here https://github.com/mozilla/browserid/blob/380f33a6fabc239971b97ba51cd0b0c9f73e7a15/lib/primary.js#L205 the code calls e.toString(), but there is no `e` defined.

/me bows to jshint@0.9.1 (not the version jshint-tests uses). I'll file a bug to update that version.

Marking five-star to simply remove the `+ e.toString()` on that line for the next train.

**Comment by seanmonstar** [comment]
Guh! How did I miss that in review?

Also, `String(e)` down below in the error handler seems better, since it won't error if e is null.
