### ISSUE TITLE
update jshint to current version on npm (currently it is 0.9.1)

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2637]
We should update the jshint module to the currently available version on npmjs which is 0.9.1

In GH-2636, I was playing around locally, and accidentally found that with that version, but not in version 0.7.1 which we currently use.

**Comment by seanmonstar** [comment]
Even better: now that we have defined jshintrc files, we should add the full things to your jshint-tests.js suite. It's really ugly at first, and shows we have several hundred errors, but after the initial cleanup, it will keep our code clean!
