### ISSUE TITLE
[dev] Dialog fails to show authenticate screen on Android (perhaps iOS also?)

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2638]
Logging into http://dev.123done.org from and Android device (using stock Browser, Fennec, and Chrome). LIkely also happens on iOS, since Dan tells me that the dev dialog won't load for him in his native app.

**Comment by lloyd** [comment]
this sounds like 5 star material to me.  @jrgm, can you reproduce?

**Comment by seanmonstar** [comment]
It was 5-star, and @shane-tomlinson merged my fixed this morning. All is well again.
