### ISSUE TITLE
small bug in lib/i18n.js assuming two character language codes

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2644]
I was looking at the bug for changing the way we handle 'en' and noticed this small issue.

https://github.com/mozilla/browserid/blob/dev/lib/i18n.js#L187

There it assumes the language tag is 2 bytes, but >2 is possible, e.g., 'lij' Ligurian, which we have in config/l10n-prod.json.

**Comment by jrgm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=806649 was filed for this. The user had their highest preferred language to 'fil-PH' which if Filipino Phillipines, and next preference for 'en-US', but got the dialog in Finish (fi) o_O

Raising to 4-star - "A highly visible defect which is confusing for users".

**Comment by ozten** [comment]
Fixed in mozilla/i18n-abide/issues/17, will pick up fix when we move to depending on i18n-abide.
