### ISSUE TITLE
/sign_in dialog broken if browser sends no Accept-Language header

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2645]
Follow-on from GH-2384, GH-1863

STR
1. In Firefox open `about:config`
2. Change the value of  `intl.accept_languages` to the empty string
3. Load http://beta.123done.org/ and click 'Sign in with Persona'

Expected: dialog opens with server default language.

Actual: /sign_in loads content that has the HTML lang attribute set to 'en-US' and tries to load https://login.anosrep.org/production/en_US/dialog.js which is 404. The dialog is broken.

https://login.anosrep.org/ is broken for the same reason.

Admittedly, not sending any Accept-Language header is unusual but not impossible.

**Comment by jrgm** [comment]
Note: sending no Accept-Language header in production train-2012.08.17 works fine with either /sign_in or the main site.

**Comment by jrgm** [comment]
Hmm, although this does work with no Accept-Language header in either `dev` or with an ephemeral deploy of train-2012.10.12 on https://train1012.personatest.org. 

Are we missing a config change for `default_lang: "en"` on stage?

**Comment by shane-tomlinson** [comment]
My amount of knowledge is very low.

We changed all references of "en-US" to "en" in #1863. It _seems_ like the config on stage is different than what we expect it. Can the configuration on stage be checked?

**Comment by ghost** [comment]
Or maybe this one explains the brokenness on iOS :/

Regards,
Dan Walkowski

**Comment by ozten** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=805482, will work with @gene1wood to see what current configs are in stage.

**Comment by jrgm** [comment]
@dwalkowski was this on stage? What brokenness on iOS on stage? Is this Safari Mobile or something else on iOS?
Safari on iOS 6 works for me on stage (which sends Accept-Language: en-us in the default config).

**Comment by ozten** [comment]
Fixed in stage via config.

**Comment by lloyd** [comment]
no, you were using production iirc dan, this was a stage specific issue.
