### ISSUE TITLE
ephemeral deployments need updated to node >= 0.8.11

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2646]
Otherwise we can't push

**Comment by lloyd** [comment]
you can't push to a server originally deployed with 0.6.17 with code that now requires 0.8.11.  Pain that happens when we update node.  Is it possible to redeploy the servers in question?

**Comment by shane-tomlinson** [comment]
On 25/10/2012 17:27, Lloyd Hilaiel wrote:

> you can't push to a server originally deployed with 0.6.17 with code 
> that now requires 0.8.11. Pain that happens when we update node. Is it 
> possible to redeploy the servers in question?

as it is, I can't even create a new instance.

**Comment by lloyd** [comment]
oh really!?  re-opening, I'll try to reproduce from tip of dev.

**Comment by lloyd** [comment]
try npm install locally and see if that addresses the issue.
