### ISSUE TITLE
.watch() should throw an exception if loggedInUser is not a valid type

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2647]
Valid types are: `undefined`, `null`, `false`, String

Anything else should result in an exception

See mozilla/id-specs@4558cb25a1f5d4d542b7b46cd18fe16cf890b926

**Comment by mohit-agarwal** [comment]
We need to throw an exception if loggedInUser is not a valid type. So If I throw an error with a message, would that work?

 `throw new Error("loggedInUser is not a valid type");`

This would be thrown when `loggedInUser` is not a valid type.

**Comment by jaredhirsch** [comment]
@mohit-agarwal that sounds good to me! feel free to submit a PR with the changes. would also be good to add a unit test to ensure the exception is thrown if the type is wrong.

**Comment by seanmonstar** [comment]
@6a68 trololol. would be great to have _any_ unit tests for include.js

**Comment by shane-tomlinson** [comment]
@seanmonstar, @6a68 - ooooohihihahaha..  testing of include.js.. I can't find the open issue about this.

A shell: https://github.com/mozilla/browserid/blob/dev/resources/static/test/cases/include.js

**Comment by seanmonstar** [comment]
this is in train-2013.10.23
