### ISSUE TITLE
Add new optional callback, onmatch, to watch()

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2648]
See mozilla/id-specs@0ad12419034273e888992305f37effbd2b4e4044

`id.watch` should have a third callback, `onmatch` that is optional and is invoked whenever the browser's state matches the value of `loggedInUser`.

This would change our possible callback sequences from:
1. `onlogin` then `onready`
2. `onlogout` then `onready`
3. `onready`

To
1. `onlogin` then `onready`
2. `onlogout` then `onready`
3. `onmatch` then `onready`

**Comment by jrgm** [comment]
no problems noted in stage train-2013.03.01
