### ISSUE TITLE
dismiss tooltips when dialog is actively moved to a different state

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2651]
STR
1. With FF, load http://beta.123done.org and click sign in.
2. Enter a secondary email address not previously known.
3. Enter and confirm password.
4. Dismiss the /sign_in dialog.
5. Click sign in again.
6. Enter the same secondary email address again.
7. Dialog shows red tooltip 'We just sent an email...'
8. Click 'cancel'.

Expected: dialog moves back to the email prompt, and tooltip dismisses when you click cancel.

Actual: dialog moves back to the email prompt, but tooltip remains on screen.

Note: I intend this as a more general issue about dismissing tooltips whenever an appropriate user action changes the state of the dialog.

**Comment by jrgm** [comment]
http://inline-tooltips.123done.org/ by @shane-tomlinson resolves the issue above. This can be closed when that lands (the inline tooltip is nicely collapsed on clicking `cancel` in the dialog). :musical_note: ...This is fucking awesome ... :musical_note:

**Comment by shane-tomlinson** [comment]
relate to #3154

**Comment by shane-tomlinson** [comment]
inline-tooltips has been merged for 3 months, closing.
