### ISSUE TITLE
Add high level monitoring of persona

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2659]
We have lots of low level monitoring of the persona service, we should complement that with high level monitoring on requests at the load balancer level to detect production issues faster, even when we don't have great coverage on low-level monitoring.  

In order to make this happen, this bug lists a subset of requests that are expected, along with expected response codes and maximum request time.  This list specifies conditions that should always be true if the service is healthy.
## Static Requests

`GET /include.js` - < 200ms - 200 response code
**What:** Included by websites using persona, upon failure sites will have non-operational sign-in buttons
**Who:** Served by `static` on web tier.

`GET /communication_iframe` - < 200ms - 200 response code
**What:** Included by websites using persona, upon failure sites will lack some features (automatic sign-in upon redirect and logout)
**Who:** Served by `static` on web tier.

`GET /sign_in` - < 200ms - 200 response code
**What:** Loaded in dialog window after user clicks website's sign-in button, upon failure user will see a popup without content.
**Who:** Served by `static` on web tier via `router`.
## API Requests

`GET /wsapi/session_context` - < 200ms - 200 response code
**What:** First thing hit during API interaction by dialog (or communication_iframe).  If broken, almost all other API calls will fail (returns CSRF token, entropy for crypto, serverTime for assertion signing, and more).  Probably we would stall at "Connecting To Persona...".
**Who:** Served by `browserid` on web tier via `router` - requires database read connection.

`GET /wsapi/list_emails` - < 500ms - non-5xx response code (2xx and 4xx possible)
**What:** Invoked during API interaction at dialog load time.  If broken, dialog will probably be rendered non-operational, but visible.
**Who:** Served by `browserid` on web tier via `router` - requires database read connection.

`GET /wsapi/address_info` - < 10s - non-5xx response code (2xx and 4xx possible)
**What:** Invoked at the time a user enters an email address (either to add an email address to an existing account, or create a new account).  If broken, the user will not be able to sign into websites.
**Who:** Involves `browserid` on web tier, forward proxy (squid) accessed from web tier, via `router` - requires database read connection

`POST /wsapi/authenticate_user` - < 2s - non-5xx response code (2xx and 4xx possible)
**What:** Invoked at the time a user tries to authenticate with a password - on a device where they have not used persona within 30 days or have recently logged out.
**Who:** Served by `browserid` on web tier via `router` - requires database read connection.

`POST /wsapi/cert_key` - < 2s - non-5xx response code (2xx and 4xx possible)
**What:** Called when a user wishes to sign in with a email address from a non-persona-IdP domain.  Invoked when that email address has not been used for 6 hours to attain a new certificate
**Who:** Involves `keysigner` on sign tier, invoked over HTTP by `browserid` on web tier, via `router`

`POST /wsapi/auth_with_assertion` - < 10s - non-5xx response code (2xx and 4xx possible)
**What:** Invoked when a user signs in with a "primary" email address.  May create a persona account if neccesary
**Who:** Sometimes involves `dbwriter` on the sweb, always involves proxy invoked via `browserid` on the web tier. routed via router.   Database read connection required always, sometimes write access from dbwriter is required.  Outbound HTTP from dbwriter to forward proxy required sometimes.

`POST /wsapi/complete_user_creation` - < 2s - non-5xx response code (2xx and 4xx possible)
**What:** Invoked when a user clicks on a verification link in email to create a persona account
**Who:** involves `dbwriter` on the sweb tier, via `router` on the web tier.  Requires write database access from `db_writer`

**Comment by gene1wood** [comment]
This looks good.
- For the "non-500 response code" items, does that mean that 400's are ok? By 500 I'm assuming you mean 5xx.
- For each of these monitors can you add an indication of what this interface does (e.g. what user impact it would have) as well as what tiers (web sweb sign db etc) are involved in the flow and any common causes for both non conforming http response codes and response times outside of the windows you've defined?

**Comment by lloyd** [comment]
updating the issue with this information ...  done.

Is the **What** and **Who** useful, or just information overload? :)

**Comment by gene1wood** [comment]
Totally not information overload.
1. For GET /wsapi/address_info
   - What type of request is being sent through squid (what does it do)?
   - Of the various elements needed for this API call, would is respond differently when differing elements fail or are absent? (e.g. db vs proxy)
2. For POST /wsapi/auth_with_assertion is it possible to go into more about the "sometimes" items? How frequently or under what conditions do these paths in the flow get exercised? (this'll help us identify problems that affect some percentage of users other than 100%)

**Comment by jrgm** [comment]
For address_info, given an incoming request of `/wsapi/address_info?email=foobar@example.com`, the outgoing request, via squid, would be GET of `https://example.com/.well-known/browserid`.

If example.com has the appropriate info at that URL and is a primary IdP, there is no database query. If not a primary IdP, the database is checked to see if `foobar@example.com` is a known email address, or one that is new to Persona.

**Comment by jrgm** [comment]
Hey @lloyd, this is great. Is it worth also mentioning these also?

`GET /v/<hash>/production/communication_iframe.js` - < 200ms - 200 response code
**What:** Entrained by the request for `/communication_iframe`.
**Who:** Served by `static` on web tier. 

`GET /v/<hash>/production/en_US/dialog.js` - < 200ms - 200 response code
**What:** Entrained by the request for `/sign_in`.
**Who:** Served by `static` on web tier. 

The value of `<hash>` can be parsed out of the referer document (i.e., /communication_iframe or /sign_in).

**Comment by lloyd** [comment]
@jrgm - I ignored cachified static resources on purpose for the first pass, I wanted to give gene an easy small set of urls to monitor (the parsing requirement was what worried me, but I suppose we could just give him a regex?  My worry is that this is prone to false positives if someone manually formulates a broken GET request.  OTOH, it would be good to have a monitor that caught broken cache headers which would result in people getting an old DOM during deployment that has embedded in it references to cachified resources from the previous train.  dunno.  leaning towards punting on cachified stuff for the first pass)  

That said, would you mind auditing the list I propose?  Ideally we'll have phase one be the smallest possible set of APIs that are hit most frequently and would fail if any process on any tier of the application goes south.  How did I do?

**Comment by callahad** [comment]
According to @jrgm this is detailed and ready to go to @gene1wood.

@gene1wood how do you want to do this? Is this fine, or would you like a bugzilla ticket.

**Comment by jaredhirsch** [comment]
@jrgm, @gene1wood pointed out that the expected response code is specified here, but the actual POST bodies aren't specified above.

If it's possible to POST with empty bodies or static bodies, can you specify the static bodies for each of these?

If dynamic contents are needed for each of these, we need to figure out how to generate those onboard the nagios machine.

**Comment by jrgm** [comment]
Some additional notes on two of them (the straightforward ones), adding how to call (arguments if any) and what a valid response looks like):

GET /wsapi/session_context 
- this is a straight GET, no arguments or authentication required
- response code 200 - returns application/json that should be parseable and contain these keys:
    '{ csrf_token, server_time, authenticated, auth_level, domain_key_creation_time, random_seed, data_sample_rate }'

GET /wsapi/address_info
- GET with query string '?email=username@mailserver.com'
- response code 200 - returns application/json; the keys depend on whether "mailserver.com" is a primary identity provider:
  - not a primary? - keys: '{ type, known }'
  - primary? (e.g., eyedee.me, or when bigtent is enabled for yahoo, yahoo.com (in dev now))
      keys '{ type, auth, prov }'

The rest of them are a little more of a dance.

**Comment by jrgm** [comment]
Um, sorry, by little more of a dance, I mean it has to first get session_context so it has a CSRF token for the POST, and then depending on the api, might authenticate so it has a session cookie, and then call the api to test (i.e., list_emails is a simple get with no arguments, but without a valid session cookie, it will return 400 Bad Request).

**Comment by jrgm** [comment]
I should note that the argument for address_info is url encoded. So `/wsapi/address_info?email=someuser%40domain.com`

**Comment by jaredhirsch** [comment]
reassigning to lloyd to make sure all the necessary info gets attached to this ticket

**Comment by jaredhirsch** [comment]
@gene1wood I think what we want is to passively monitor stuff that requires an active session.

@lloyd or @jrgm plz fill in details on how we want to partition active ping checks vs passive log listening

**Comment by gene1wood** [comment]
I've created the logstash configs for these new monitors. I've not yet tested or committed them.

I want to monitor the non-200 metrics in a new form using cepmon (a form we don't current use). cepmon doesn't currently support this but I can see how to extend it by writing new EPL ( https://github.com/fetep/cepmon/blob/v0.4/lib/cepmon/config.rb#L100 and http://esper.codehaus.org/tutorials/solution_patterns/solution_patterns.html#aggregate-1). Instead of watching the # of 500's or 400's and setting a threshold above which we get alerted as we do currently, I want to watch the percentage of requests that return 500's or 400's. I think this will better reveal problems within our control and not misconfigured RPs out in the world.

For the response time alerting, I will just use the current cepmon functionality but haven't written the config for that yet.

The cepmon config work will go here : svn.mozilla.org/sysadmins/puppet/weave/modules/cepmon/templates/cepmon.cfg
The logstash config changes are here : svn.mozilla.org/sysadmins/puppet/weave/modules/logstash/templates/zlb.conf

**Comment by gene1wood** [comment]
I discovered that all of our current response time monitoring has never worked due to a mistake when setting them up (data point is in "seconds", we monitor it as if it's in "milliseconds").

I've corrected the existing monitoring and added in all new response time monitors.

I've disabled all alerting on all response time monitors since many of the values that we do not match the real world response times. So far I've made these changes :

webhead.node_time.upper_90 upped from 15ms to 100ms
verifier.req_time.upper_90 upped from 1.5s to 2.5s
dbwriter.req_time.upper_90 upped from 1s to 1.5s
keysigner.req_time.upper_90 upped from 100ms to 150ms
webhead.req_time.upper_90 upped from 2s to 2.25s

All response time monitors mentioned in this ticket description have looked good so far.

# What remains to be done?
- Let another few days pass to validate the current req_time thresholds
- Create response code thresholds in cepmon and nagios
- Bring over details in this ticket into monitoring docs on the wiki ( possible template : https://mana.mozilla.org/wiki/display/NAGIOS/HTTP or https://intranet.mozilla.org/Services/Ops/BID/Alerts )

**Comment by shane-tomlinson** [comment]
@6a68 - are you all over this? Can this be closed?

**Comment by jaredhirsch** [comment]
yeah, this is stale, closing. Nice find, @shane-tomlinson :surfer:
