### ISSUE TITLE
Support OCSP stapling

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2660]
Cloudflare have made [SSL 30% faster](http://blog.cloudflare.com/ocsp-stapling-how-cloudflare-just-made-ssl-30) by turning on [OCSP stapling](https://en.wikipedia.org/wiki/OCSP_stapling).

Not sure how (or if) it can be done in node, but both [Apache](https://httpd.apache.org/docs/trunk/fr/mod/mod_ssl.html#sslusestapling) and [Nginx](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling) support it now.

**Comment by lloyd** [comment]
/cc @gene1wood is this something that is possible with zeus?

@fmarier what percentage of our supported browsers also support OCSP stapling?

**Comment by fmarier** [comment]
As far as I can tell, it's been [enabled in chrome for a while](http://www.chromium.org/developers/design-documents/network-stack/network-stack-objectives) (third section of 2011Q1 goals) but it's [not available](https://bugzilla.mozilla.org/show_bug.cgi?id=700693) nor [enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=700698) in Firefox yet.

No idea about Safari or IE.

**Comment by gene1wood** [comment]
@lloyd If we were to implement it, we should do so in nginx, not zeus. We shouldn't be adding anything new to zeus.

**Comment by fmarier** [comment]
Dropping to 1-star because it seems like it's very limited at the moment.

**Comment by fmarier** [comment]
This is [now in Firefox Nightly](http://blog.mozilla.org/security/2013/07/29/ocsp-stapling-in-firefox/). It's [available in nginx](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling) as of 1.3.7.

Upgrading to 2 stars due to increased browser support. It will be especially interesting once Firefox OS and Fennec get it.

**Comment by fmarier** [comment]
This is not currently possible with ELB.

**Comment by fmarier** [comment]
Closing as "wontfix" since we can't do it on ELB.
