### ISSUE TITLE
Support SPDY

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2661]
The multiplexing of resources may help us out.

**Comment by lloyd** [comment]
What percentage of our supported browsers support SPDY?  What level of speedup might we expect practically?

/cc @gene1wood Is this something that we would do at the zeus tier?

**Comment by shane-tomlinson** [comment]
Both Firefox and Chrome support SPDY today [1]. Reports vary on speedup, some claim 0[2], Google claims on mobile networks a 1.3x improvement. 

Once this is supported in mobile browsers where connection latency is costly, SPDY will be a bigger win than for desktop browsers.

There already exists a node implementation for SPDY that integrates with express [4].  This would probably have to be enabled in our router process. I could not find any info on a Zeus implementation.

If the integration is straight forward, I think it would be valuable to experiment and capture concrete timings on simulated mobile networks - @fmarier 

# 

[1] - http://en.wikipedia.org/wiki/SPDY
[2] - http://www.guypo.com/technical/not-as-spdy-as-you-thought/
[3] - https://developers.google.com/speed/articles/spdy-for-mobile
[4] - https://github.com/indutny/node-spdy

**Comment by Lennie** [comment]
Opera also support SPDY, here is the complete list:
http://caniuse.com/spdy

**Comment by gene1wood** [comment]
@lloyd We shouldn't do this with zeus but instead with nginx. We should seek to remove all app logic from zeus since we will likely change load balancers and so that dev has control over app logic (if it lives in nginx).

**Comment by joelcox** [comment]
Experimental SPDY support [landed in nginx](http://nginx.org/en/docs/http/ngx_http_spdy_module.html). I wasn't too pleased with the stability of the SPDY module for Node, to be honest.

**Comment by Lennie** [comment]
Looks to me like SPDY isn't gonna happen anytime soon with login.persona.org:

https://github.com/mozilla/browserid/issues/3252

**Comment by shane-tomlinson** [comment]
Unfortunately, our migration to EC2 is going to block any ability to add SPDY, at least for the time being. SPDY is not yet supported by Amazon ELB.  http://serverfault.com/questions/453741/how-can-i-setup-spdy-with-jetty-behind-amazons-elb and https://forums.aws.amazon.com/message.jspa?messageID=364788 for reference.

**Comment by fmarier** [comment]
Closing as "wontfix" since we can't do it on ELB.
