### ISSUE TITLE
API semantics broken: onlogout fired even if loggedInUser: null

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2662]
the API is not supposed to invoke the onlogout callback if a website supplies `loggedInUser: null`.  This behavior was broken in commit f94a3b40364f3db78568de7630944d4262eb8699

Sites that rely on this API contract and redirect upon onlogout events can get into an infinite reload loop

**Comment by lloyd** [comment]
NOTE: this bug rolled out into production in 0.2012.10.12.5 (7b851924d8afe794c66283a25ed4ad5164542217) and caused us to rollback to 2012.08.12.

**Comment by vivor** [comment]
Is this really fixed, now? Because I'm using the latest version and I'm still getting a reload loop. Usually loggedInUser is not defined in my code but setting it manually will still result in reloading the page over and over again.

Code looks like this (maybe I'm just using it wrong):

``` javascript
navigator.id.watch({
    onlogin: function (assertion) {
        $.ajax({ 
            type: 'POST',
            url: '/ajax.php', 
            data: {assertion: assertion},
            success: function(res, status, xhr) { window.location.reload(); },
            error: function(res, status, xhr) { alert("login failure" + res); }
        });
    },
    onlogout: function () {
        window.location = '?logout';
    }
});
```

**Comment by callahad** [comment]
If `loggedInUser` isn't set when you call `watch()`, then you will _always_ get an `onlogin` or `onlogout` callback. It's Persona's way of saying "you didn't say what was up, so here's what I know about the user."

**Comment by vivor** [comment]
Thanks for the explanation. I can see the problem with my code, now. I'll try to think of some other way to do this.
