### ISSUE TITLE
Security Errors on IE9

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#267]
Occurs when clicking "sign-in" on dev.myfavoritebeer.org:

SEC7111: HTTPS security is compromised by https://dev.diresworb.org/relay

**Comment by shane-tomlinson** [comment]
7c7c9ae8b3ec4666084e70aa7095a9b8a522d446 addresses this problem.

For the relay, removing the StealJS dependency.  compress.sh concatenates the two necessary files manually.

**Comment by shane-tomlinson** [comment]
No more security exception in IE9.

The license info of production.js shows directions on how to use Channel.  This is not the desired outcome.
