### ISSUE TITLE
In IE9 must re-auth to browserid ever time

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#268]
STR:
1. http://dev.myfavoritebeer.org/
2. click sign in
3. select an email address and login
4. logout and reload the page
5. click sign in
6. notice that you have to re-authenticate

**Comment by shane-tomlinson** [comment]
@lloyd - unable to reproduce.

**Comment by lloyd** [comment]
woah.  this issue is specific to one of my VMs, investigating.  thanks @stomlinson

**Comment by lloyd** [comment]
scratch that, can't repro anywhere anymore.  Assuming this issue was fixed with the flurry of other fixes.
