### ISSUE TITLE
Shim accepts certificates with arbitrary email addresses

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2680]
When provisioning a user, an IdP invokes `navigator.id.registerCertificate(signedCert)`, where `signedCert` is a signed JSON object containing a field with the user's email address.

This field is supposed to be set by the user's request: "please provision me as foo@example.com"

However, the IdP can change this to an arbitrary email address, and the shim still accepts it and lists it in the picker. This seems strange, and may potentially be able to be used maliciously.
### STEPS TO REPRODUCE
1. Try to authenticate as `bug2680@mockmyid.com`
2. Notice that your picker now actually lists `whoops@mockmyid.com`

**Comment by callahad** [comment]
You can see this here:

https://github.com/callahad/mockmyid/blob/500c7d173b9c4a50adf0f99262a47ea0d4b13079/public_html/browserid/provision.html#L42-45

Note: The shim _will_ reject the cert if I try to provide something from another domain (e.g., if MockMyID tries to hand back a signed cert for `whatever@eyedee.me`)

**Comment by jaredhirsch** [comment]
@callahad this bug is closed, thug! current output if I try to login to 123done.org as bug2680@mockmyid.com:

![Screen Shot 2013-03-08 at 8 26 48 AM](https://f.cloud.github.com/assets/96396/237193/fdec207c-880c-11e2-8bc3-049fd8ab3947.png)

**Comment by callahad** [comment]
Hawt! :tada:

**Comment by jaredhirsch** [comment]
wait a minute. mockmyid cannot login _at all_ on dev. so this might not actually be fixed

**Comment by callahad** [comment]
Hooooray clock skew! If you can suggest a good, reliable time source that MockMyID can pull from, I'd be all over it. This is callahad/mockmyid#9

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
