### ISSUE TITLE
Infinite Sessions for B2G

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2681]
The B2G team doesn't want users to ever\* have to re-authenticate once they've logged into their phones.

*Unless forced to via logoutEverywhere, or having reset your password from another device (useful if your device is stolen or lost.)

**Comment by seanmonstar** [comment]
@lloyd @ozten it looks like this is controlled by a config option. Is it best to change the default in `lib/configuration.js`, or in `config/production.json`? Would I need to also edit `aws.json` and `local.json`?

**Comment by seanmonstar** [comment]
@zaach maybe you can provide insight? i don't know how it all works together yet.

**Comment by zaach** [comment]
`.awsbox.json` provides a clue. It appears you can specify how config files are layered in there. You should be able to layer a new b2g.json on top of the others.

**Comment by seanmonstar** [comment]
Oh great. So then I can add a b2g.json, add to that line, and then we need
to use that also when we finally deploy to prod.

**Comment by jrgm** [comment]
I noted a (maybe) issue in GH-2816. This was from working with notoriousb2g. @jedp, @seanmonstar we should chat about whether that is the right endpoint for me to ponder for now.
