### ISSUE TITLE
change address_info to include transition state

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2686]
taken from https://id.etherpad.mozilla.org/primary-transition-ux-swarm

(CHANGE) address_info
- currently returns an object with keys:
  - `type`: {primary, secondary} // type of email when it was added
  - `known`: {true, false} // (secondary only) whether the email is known to persona 
  - `auth`: <string> // (primary only) authentication URL
  - `prov`: <string> // (primary only) certificate provisioning URL
- semantic changes as well as a "state" will be added indicating what user screens should be displayed.
  - `type`: {primary, secondary} // indicates email type right now
  - `state`: {string}
    - "known": the secondary email address is known and requires a password, or the primary address is known and requires an assertion
    - "unknown": the secondary email is not known and can be used to create a new account, or the primary address is unknown and the user should be shown "<domain> makes this easy" before re-directing them.
    - "transition_to_primary": the primary email address was last used as a secondary,  the user will be authenticating via idp for the first time
    - "transition_to_secondary": the secondary email address was last used as a primary, the user has a password and can authenticate with it.
    - "transition_no_password": the secondary email address was last used as a primary address, the user has no password and must select one.
    - "offline": the primary authority is offline and the user cannot authenticate with this email right now.
  - `auth`: <string> // (primary only) authentication URL
  - `prov`: <string> // (primary only) certificate provisioning URL

**Comment by seanmonstar** [comment]
this blocks #2404

**Comment by lloyd** [comment]
done, baby.

**Comment by lloyd** [comment]
landed in 781184b5f2b6372c0ce44fff046f1719a78553f9
