### ISSUE TITLE
investigate preventing RPs from using forceAuthenticate on B2G devices

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2693]
Since this API is private, but needed for B2G (specifically the marketplace), we may want to look into side effects. Perhaps RPs will want to try to use this, and it's not ready for public use yet.

**Comment by seanmonstar** [comment]
related PR where this landed: #2692

**Comment by benadida** [comment]
I would like to mark this invalid, because I'm okay with other apps calling this API, and we're starting to get requests for it in mainline browserID, too. So, closing, but reopen if you feel strongly!

**Comment by seanmonstar** [comment]
This was just to investigate if there was a need, not that it actually had to be done.
