### ISSUE TITLE
remove-email, returning-users: clickIfVisible sometimes hangs

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2702]
Depending on annoyingly unresolved timing issues, we sometimes see the 'is this your computer' pane in the dialog, so we have an extension function for wd that clicks a button only if it's visible, with a very short timeout in case it isn't.

On FF, in the remove-email test, there's a step where you log into myfavoritebeer using a secondary email that's verified. If the 60 second "this is my computer" timer has not run out, the dialog will close itself, but the click-if-displayed function seems to ask for a non-existent window handle, and FF freezes.

I think checking the number of windows, or looking for the __persona_dialog window.name, should do it, but we'll see.

Opened an issue against wd: https://github.com/admc/wd/issues/55

Update: this same bug seems to be occurring against Chrome and IE9, admc is looking into it.

**Comment by shane-tomlinson** [comment]
@6a68 - so my bastardization of clickIfExists is doing what you suggest here.

Every time a new window is opened, I get a handle to the window and save it.
When clickIfExists is called, I then:
1) wait for 15 seconds for the dialog to potentially close.
2) get the current list of window handles.
3) check that the window handle we think is current is still in the list. If so, try to click the button. If not, exit happily.

It's a massive hack, but it has worked around the timing issues for now.

**Comment by jaredhirsch** [comment]
Ha, that's awesome. If you look at the open issue against admc's wd, sebv
suggested we check for a specific error code in out utils.waitFor method.
Also, it looks like they've added their own extension method to poll for
elements, we can try that as well.

For now, though, I'm satisfied if the bug fixes tests on our platform of
the week, FF16/vista :-)

**Comment by jaredhirsch** [comment]
this looks fixed to me. @shane-tomlinson, reopen if I'm wrong.
