### ISSUE TITLE
IE9, add-primary-to-primary: eyedee.me 'create account' button sticks

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2706]
Broken in [job 1944](https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.ie.9/1944/) ([sauce link](https://saucelabs.com/tests/4f4ba1a067e04d1099596596ab6726cc)) and [job 1943](https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.ie.9/1944/) ([sauce link](https://saucelabs.com/tests/586ba68355cc4e98afbb539560be6304)).

I'm inclined to throw a click-if-visible in here, but I know that it'll cause every other friggin platform to freeze and die at this point, since those other platforms don't have trouble with the button sticking.

Maybe we add a delay before clicking, at least until admc/wd fixes the hanging bug.

**Comment by jaredhirsch** [comment]
four stars but, try to stabilize chrome and FF first.

**Comment by jrgm** [comment]
Um, something is really weird here. If you watch the video a dialog (modal? don't know) pops up saying `"Java(TM) Platform SE Binary has stopped working"` and nothing happens in the browser after that. This totally does not match the screenshots that sauce shows for this run. Huh?

**Comment by shane-tomlinson** [comment]
@jrgm - I have a screen shot of this - ![Screen shot of Java Crash](https://www.evernote.com/shard/s1/sh/2914ed38-5394-43df-bb83-fd0bcebac2c0/f67fdf0e2384bffd86139d546d31e07f)

**Comment by shane-tomlinson** [comment]
@6a68, @jrgm - I have completely bastardized clickIfExists, you don't want to look at the code. But, as@6a68 suggests, adding these to the eyedee.me submit button has "fixed" the problem. Yuck.

**Comment by jaredhirsch** [comment]
@AutomatedTester - we're seeing super funky java crashing in this test (see the screenshot shane posted). Know anybody at Sauce who would be interested in this?

**Comment by shane-tomlinson** [comment]
Closing as fixed, both the sticky button behavior and IE9 exploding due to Selenium versions.
