### ISSUE TITLE
IE9, change-password-test: need to watch for 'is this your computer' screen

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2707]
Broken in job [1943](https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.ie.9/1943) ([sauce](https://saucelabs.com/tests/89015caab65c4eacbe7b918d6545d5d1#) [jobs](https://saucelabs.com/tests/fb7037000a5043378b08d9e056c8e2a7)) and [1944](https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.ie.9/1944) ([sauce](https://saucelabs.com/tests/3b0c8a68bb7e42578786ac2d98776212) [jobs](https://saucelabs.com/tests/5b9ed4228a7d4f5d86c1aedb145b61b5)).

Another test failing because it's not checking for the 'is this your computer' screen. Adding a wclickIfVisible is probably the fix.

**Comment by shane-tomlinson** [comment]
I'm calling this done, with some changes to wd-extensions and a change to the change-password test, I think an entire class of timing issues should be resolved in Firefox and IE.
