### ISSUE TITLE
Add a version lock api to detect client/server mismatches

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2710]
Background: Everytime we deploy, we currently can have a state where the client (dialog) and the server can have different versions of the code. An incremental improvement would be to detect this and display an error message or 'maintenance' message.

Eventually, we want to be able to deploy with zero user facing impact.

We should add a version lock to our wsapi requests. The version of the git sha will be included with all network requests. Middleware will compare this value with the git sha of the current process.

If they don't match, the API call will fail. The FE dialog will have a new `code_version_mismatch` state.

The UI for code_version_mismatch will happen out side of this bug in Issue ???

Updated wsapi calls will be in the from of

```
/wspi/{SHA}/{CALL}
```

**Comment by ozten** [comment]
If anyone wants to take a run at this before I get back to it... please do!

Use a custom HTTP header, instead of versioned urls.

**Comment by callahad** [comment]
Do we want to do this? The majority of changes will alter the SHA without impacting the `wsapi` -- it feels weird to proactively fail on requests that would otherwise work.

**Comment by shane-tomlinson** [comment]
This has been merged.
