### ISSUE TITLE
personatestuser: document all the things

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2715]
Document how to connect to the machine, how to investigate probable sources of errors/downtime, how to respawn services.

**Comment by jaredhirsch** [comment]
@jedp - just a placeholder for a conversation, an etherpad with some cryptic shell scripts pasted in, or a series of increasingly difficult physical challenges culminating in a battle with those giant Q-Tips they used to use on American Gladiators. Whatever works for you.

**Comment by jaredhirsch** [comment]
I'm stealing. Will try to shell into le box and extract wisdom by perusing the source.

**Comment by jedp** [comment]
Q-Tips sounds like a good start.

**Comment by jaredhirsch** [comment]
closing as "medium-value idea, unlikely to actually get done, likely to be thought of again in the future"
