### ISSUE TITLE
"emails from browserid.org come from hostname that doesn't match reverse DNS"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#272]
This comes from https://bugzilla.mozilla.org/show_bug.cgi?id=688068

**Comment by lloyd** [comment]
this will be fixed when we move to a 3rd party email vendor.  I have no ETA on this.

**Comment by benadida** [comment]
this appears to be entirely subsumed by #214, I'm going to aggressively close

**Comment by lloyd** [comment]
fixed in dev and beta.
