### ISSUE TITLE
test runner: don't start tests unless sauce has resources available

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2721]
I'm not totally sure, but I think [this Jenkins job](https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.firefox.16/1957/console) failed because it kicked off 6 tests, but some of those used multiple browsers, so that the change-password-test was started, but never got access to a sauce VM at all. I think that's why the run failed.

One way to address this is to have individual runners manage their own work queues:
- Individual tests could publish the total number of browsers they need to complete successfully, inside the hash that currently contains suiteName and cleanup.
- The runner can poll [sauce labs' API](https://saucelabs.com/docs/rest#usage) to trivially obtain the number of jobs running and the number of queued jobs
- When the necessary number of browsers is available, the runner can submit the jobs to the queue.

The downside is that having a bunch of queues that are separately polling could easily lead to headaches, but this would still be one step better than what we have now.

We could also just let all jobs be queued up by sauce, and ensure that the runner waits until jobs make it all the way through the queue. I'm not totally sure what caused the timeouts on the Jenkins side at this point.

**Comment by jaredhirsch** [comment]
bumped down to 3 stars because we can put this off for a little while

**Comment by jrgm** [comment]
I wrote this https://github.com/jrgm/browserid/commit/f0cbb53ebb72b1ba2d04dd3bcace3457816a4e34 but then 
kinda forgot about it. Look useful for this?

**Comment by jaredhirsch** [comment]
Bumped back up to 4 stars because it happened again:

https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.chrome/1971

**Comment by jaredhirsch** [comment]
Bumped back down to 3 stars because the next run passed:

https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.chrome/1972/

**Comment by jaredhirsch** [comment]
related to #2737: let's get more data, make a more precise diagnosis, and then see what actions to take.
