### ISSUE TITLE
request: hide URL when site name is redundant

### ISSUE THREAD

**Issue by wolftune** [mozilla/persona#2724]
Our site's name is the URL. We can choose to just have no specified name and then Persona uses the URL as the name. Overall, that's fine. But we'd like to be able to have control over capitalization. Also, we'd like the main domain name to be used as the site name when we have a login to a subdomain.

Our request: when a specified site name matches the URL (perhaps differing in capitalization though), then hide the url in the login popup so we don't see redundant entries.

This way, the name (such as where it mentions the name for accepting ToS) will have the capitalization we want, we won't get the redundancy, and yet the name and the URL will both show up if logging into a different subdomain.

Ok? No big deal, but would be nice.

**Comment by lloyd** [comment]
skinny, lets' see if can strike a compromise and improve the font used for domain  when site is not present

**Comment by skinny97214** [comment]
@wolftune Can you post a screenshot of what it looks like now for you domain?

**Comment by wolftune** [comment]
right now we just left the site name blank since the name is the URL. So everything looks fine except that it is all lower-case and we wanted to have a capitalized name. But we didn't want to see both the capitalized name and the URL at the same time since they are the same basically.

And so Llyod, your compromise doesn't help with capitalization. It also doesn't help with subdomain issues. We want the main site name to still be showen even if someone is logging into a subdomain, although in that case the URL should be shown. Currently (although we don't have any subdomains at this time), if we leave the site name blank then the URL only will be shown and so no primary site name will be present when logging into a subdomain.

So the current screenshot won't look like anything interesting because it just looks like any Persona login where no site name is listed so the URL is used instead. I can go share it anyway if you really want.

Thanks for your work, btw!

To try to clarify:
We don't really care about font. We just want to be able to specify a site name but have the URL hidden if it matches the site name, because it looks bad to be redundant.

**Comment by skinny97214** [comment]
Here's a mock that better balances the site name and url so that even if there is duplication it looks fine. The idea is for you to have the url for security purposes and the site name that's more human readable. @wolftune would this address your issue?

http://cl.ly/image/0D0m1f432H31

**Comment by wolftune** [comment]
Well, we thought of that but the problem is that we want the top-level domain bit to be included as part of the name.

What about showing the URL with longer stuff like including "http://" ? That would allow us to specify the site name and it would still make human-readable sense why there are two lines shown.

I'm not sure what else is the best way to do this. We want it to look good and be clear and secure…

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
