### ISSUE TITLE
Missing error check; lib/primary.js crashes if no content-type in response

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2728]
Just happened to notice this, but this should check that there is a content-type before using it.

```
res.headers['content-type'].indexOf('application/json') !== 0
```

https://github.com/mozilla/browserid/blob/dev/lib/primary.js#L167

**Comment by shane-tomlinson** [comment]
@jrgm - this is also an issue in http_forward.js

**Comment by jrgm** [comment]
@shane-tomlinson you mean here? https://github.com/mozilla/browserid/blob/dev/lib/http_forward.js#L101

(update to previous line in primary.js: https://github.com/mozilla/browserid/blob/dev/lib/primary.js#L113).

**Comment by shane-tomlinson** [comment]
@jrgm - exactly.
