### ISSUE TITLE
unverified email for b2g

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2744]
We need an undocumented way of using unverified emails, only for FirefoxOS for now.

details available at https://bugzilla.mozilla.org/show_bug.cgi?id=794634#c9

**Comment by seanmonstar** [comment]
After digging into our API and seeing how things work, i think I know how to support un-verified users being authenticated. After that, comes the additions to the verifier.

The database table for users will need a new row, `unverified`, or `verified` perhaps. Or maybe it can be a 3rd "auth_level": `password`, `assertion`, and now `unverified`?

`/wsapi/stage_user` should accept a new argument, `allowUnverified`, which will mean that the call automatically completes the registration of the user. An email is still sent out with a token, so that the user can upgrade to verified status.

/cc @benadida @ozten sanity check?

**Comment by ozten** [comment]
I'll defer to @benadida.

**Comment by benadida** [comment]
@seanmonstar I'd recommend a new column. Worth exploring how this works with the field we set when a password is reset.

Worth laying out all the necessary changes:
- cert_key should use a different root key
- verifier needs to take a parameter that allows unverified and returns the right data structure
- anything else?

**Comment by benadida** [comment]
@seanmonstar to be clear, I think this direction feels right. Go for it, and let's check in regularly in case it ends up being a bad decision.

**Comment by seanmonstar** [comment]
@benadida good point, I didn't think of cert_key.

While most of this extra functionality can live at the FxOS domain, since we hope to use the same database as the rest of Persona, the database changes will need to be merged back into production, right? @lloyd see any issues with that?

**Comment by benadida** [comment]
@seanmonstar @lloyd what I've proposed and what I suggest we keep doing for now is to make the changes we need for fxos, then delay discussions of merging (even the DB) until early next year, once we've ironed out all the last-minute needs / changes.

**Comment by seanmonstar** [comment]
@benadida or @lloyd:

Since this is my first foray into the backend, I'll just talk much more about my problem than I normally would, to make sure I don't miss something.

In /wsapi/stage_user, I see that db.stageUser is called, which creates a new row in `staged`. I'm wondering if from there I can call db.completeCreateUser, perhaps with a modification to not need the token? And then after that, I'd need to call wsapi.authenticateSession().

I don't fully know the difference between a staged user and a staged email. Maybe it's better to just say this user is created, and call `/wsapi/stage_email`? Or can you not create assertions with a staged email?

**Comment by ozten** [comment]
Very cool, nice work so far. I'd like to see a concrete example of what the updated db would look like.

I'll throw out a variation:

Would it be possible to implement this without any new db changes?

The `staged` table would be used to store `email` and `passwd` (as it currently is). Additional logic would be added to use it from an unverified email perspective.

I think this table already has a unique constraint on the email column.

Primary Addresses - Not eligible✝, user's sent through provisioning and authentication flows.

Secondary Addresses:
1) First unverified user enters alice@example.com, sets a password and is issued a unverified assertion
2) If she forgets this password and tries to do the unverified flow again, she must use the reset password link
3) If a second, completely different user tried to also use alice@example.com, they would be forced to use the reset password link

✝ For b2g this feature will be used with forceIssuer, so this won't be an issue. ForceIssuer causes primaries to be staged like secondary types and include a password. For normal primary usage, perhaps this is acceptable as most users can easily auth with their IdPs.
