### ISSUE TITLE
personatestuser only allows env from prod, stage, dev or local

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2746]
This is after fixing change-password-test.js to report errors that occur in setup.

➜  automation-tests git:(cancel-account-failure) ✗ PERSONA_ENV=testy-temp vows tests/change-password-test.js
request test user response env must be one of prod, stage, dev, local
✗teardown called
·· 

  1: setup tests
    ✗ succeeds
      »   env must be one of prod, stage, dev, local
✗ Broken » 1 honored ∙ 1 broken (0.333s)

**Comment by jedp** [comment]
I've submitted lloyd/personatestuser.org#21 as a proposed solution
