### ISSUE TITLE
Make Testy work with Pull Requests

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2755]
This is somewhat difficult at the moment because GitHub does not call the Web Notifier Service on a Pull Request. Travis-CI gets a notification with a SHA that is not usable to do a git checkout, instead the PRs HEAD must be checked out.

**Comment by jaredhirsch** [comment]
Bumped down to 2 stars because I kinda think we need a better solution that encompasses what jenkins, deployer, travis, and random-ops-builder-box do. In short, we need to engineer releases LIKE A BOSS

**Comment by shane-tomlinson** [comment]
Testy is not being used for its original purpose right now. Closing.
