### ISSUE TITLE
merge forceAuthentication into mainline Persona service

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#2757]

**Comment by dgreisen** [comment]
modified from my post to dev-identity:

This feature is badly needed, but the implementation is very insecure. You don't have to be a sophisticated attacker to bypass this security feature. You just need firebug to delete the flag in the javascript and you can make unlimited purchases, delete accounts - do anything that the developer trusted could only be done by an individual in possession of the password. 

This implementation is good if you're trying to keep your not-very-determined kid from buying every version of angry birds without permission, but it is wholly inadequate for protecting web ecommerce. My use cases would be ecommerce, deleting accounts and other transactions that are high-cost to reverse, or are irreversible. This implementation with this significant security hole does not address those use cases.

I would strongly recommend against pulling this implementation. It is better that developers know that persona currently can make no assertions about the identity of the person currently sitting in front of the computer - only about the identity of some individual who at some point sat at that computer - than that they be given a  false sense of security that they can perform sensitive operations protected by persona.

Wait to implement this feature until it can be done securely and correctly without giving a false sense of security.

**Comment by callahad** [comment]
More discussion on the dev-identity mailing list: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/2677

And a reminder: **Please submit pull requests and/or open GitHub Issues against [mozilla/id-specs](https://github.com/mozilla/id-specs) before anything like this enters the mainline!**

**Comment by lloyd** [comment]
@benadida please give us some context and rationale so we can prioritize and understand the what and the why, yo!

**Comment by robhudson** [comment]
Similar to @dgreisen, the Marketplace team is hoping to use something like this for irreversible actions (deleting accounts or submitted apps, etc). There are also administrative actions that we want to re-verify the user prior to allowing.

**Comment by benadida** [comment]
@lloyd this feature, that a web site should be able to force reauthentication, has been requested by a number of folks, within Mozilla and outside of Mozilla. Since we are building it for FXOS, it seems like a good thing to merge this into mainline. That is all :) Opportunistic merging of features that we know the community wants.

Note that I don't think our solution is fully secure against a serious adversary at this point. But that's okay, it's bathroom-lock security for now, and we will advertise it as such.

**Comment by lloyd** [comment]
thanks for the clarification.  My only qualm was with the lack of a bug description, so it's hard to make a priority call in a fast paced triage meeting :).

**Comment by shane-tomlinson** [comment]
This has been in production for several months as a new option passed to navigator.id.request called `experimental_forceAuthentication`, closing.
