### ISSUE TITLE
"#~" and quotes appended to the strings in the login screen

### ISSUE THREAD

**Issue by pandark** [mozilla/persona#2763]
When I've not logged in or I've clicked the "It's not me" button,

What I should see:

<blockquote>bugzilla.mozilla.org utilise Persona au lieu d'un nom d'utilisateur pour vous identifier.</blockquote>

 <blockquote>Pour vous identifier avec Persona, veuillez saisir votre adresse de courrier électronique.</blockquote>

What I see instead:

<blockquote>#~ "bugzilla.mozilla.org utilise Persona au lieu d'un nom d'utilisateur pour vous identifier."</blockquote>

 <blockquote>#~ "Pour vous identifier avec Persona, veuillez saisir votre adresse de "#~ "courrier électronique."</blockquote>

**Comment by lloyd** [comment]
/cc @mathjazz 

assigned to @jrgm to dedup

are french strings borked?

**Comment by shane-tomlinson** [comment]
Reported on our mailing list:

```
Hi everyone,

I'm getting what I think is buggy text on the first screen of the Persona iframe 
connection process (screenshot : http://cl.ly/image/0B2Z0z3g3v0W). I don't 
see what those #~ characters are doing here, but maybe I'm lacking imagination ? 
It seems like some not interpreted markup...

It happens both on MDN and my site. Language is French. I tried to change 
language with Quick locale switcher on Firefox (and cookie reset) but it did 
not work. Happens both on Firefox 16 and Safari (Mac OS).

Thanks for your help !
--
Alexandre Bulté
```

**Comment by mathjazz** [comment]
This is the duplicate of:
https://bugzilla.mozilla.org/show_bug.cgi?id=809901

**Comment by jrgm** [comment]
Thanks @mathjazz for the dup. This seems to be fixed in train-2012.11.23, which will go live real soon now.

**Comment by jrgm** [comment]
train-2012.11.23 went live in production this morning (12/17 PDT). I don't see this problem there. Closing, but please reopen if you don't have the same result.

**Comment by jrgm** [comment]
Hmm, didn't actually close this. Closing now.
