### ISSUE TITLE
password rejected for anaaktgeboren@mozilla.com | ally@mozilla.com

### ISSUE THREAD

**Issue by anaaktge** [mozilla/persona#2767]
When attempting to sign into bugzilla or http://ponyplace.ajf.me/ with either mozilla email address, the correct password is rejected with "This email address & password do not match". 

The password does not contain any unusual characters and is neither short  nor excessively long.

**Comment by anaaktge** [comment]
and etherpad. which is a serious bummer for work-related things.

**Comment by callahad** [comment]
Has this same password worked previously for you? Can you try resetting your password?

**Comment by anaaktge** [comment]
My password had not changed recently, so I think but cannot prove that the password worked previously.

I reset the password. Same issue.

**Comment by lloyd** [comment]
@anaaktge Hi!  I wonder if you would mind very quickly creating a screencast of you reproducing the problem on http://123done.org ?  This would help me theorize on what exactly is going wrong.

**Comment by callahad** [comment]
@anaaktge Also, have you _ever_ been able to successfully log into a site with Persona using one of those addresses? Using any address at all?

Can you try a different browser or another computer with those same addresses?

**Comment by anaaktge** [comment]
@callahad Yes, I have signed into sites with persona with those addresses(the services teams <3 etherpad). I tried 123done, bugzilla, & etherpad on IE with the same results. I also tried chrome on gene's ubuntu box and 123done produced the same error.

@lloyd Im afraid win8 will not make that terribly easy at present. If you are about the sf office, I can bring the machine to you(or another identity person)?

**Comment by ozten** [comment]
@anaaktge can you try recording a screencast with Jing and paste the url here?
http://www.techsmith.com/jing.html

lloyd and others are not in sf.

**Comment by gene1wood** [comment]
Aha, turns out Vinz Clortho is not live ( https://wiki.mozilla.org/Identity/BrowserID/VinzClortho ) and ( https://mozilla.com/.well-known/browserid ) meaning that for email addresses @mozilla.com one's password has nothing to do with one's LDAP password.

**Comment by anaaktge** [comment]
hat tip to mconnor.

I apparently have a local password (my ldap password 4 iterations ago) which does work. Mike Connor points out that his persona account has a local password (different from his ldap) because his persona account was created before mozilla became an Idp. I created mine around the same time, and apparently also have a local password. 

I understand from gene that the bridge between ldap & persona is not in production and that may or may not be relevant.

**Comment by callahad** [comment]
Marking resolved -- this was a misunderstanding related to the fallback. Mozilla.com is _not yet_ a native Identity Provider, so a user's Persona password is not in any way connected to the internal LDAP password.
