### ISSUE TITLE
FF16: clicking "add another email address" button causing trouble

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2769]
4/5 recent failures were due to not successfully clicking the "add another email" button in the dialog.

More details: https://gist.github.com/4152343

Need to click this a bit differently--might be auto-fixed by @shane-tomlinson's merging of wsubmit code into wclick?

**Comment by shane-tomlinson** [comment]
@6a68 - this should be taken care of with the update to wclick in #2771

**Comment by shane-tomlinson** [comment]
Closing as same cause as #2740
