### ISSUE TITLE
Use pushState so users can use browser history to navigate dialog

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#277]
For IE8/9 probably have to use hashbangs.

**Comment by lloyd** [comment]
Is there an accessibility motivation here?  I'm a bit unclear on why we need to enable browser based navigation for the dialog which is rendered in a window without controls.

**Comment by benadida** [comment]
I agree with @lloyd: what happens in the browser-provided doorhanger? We probably want to treat this like a dialog, no going back or forward, click cancel any time.

**Comment by shane-tomlinson** [comment]
@lloyd, @benadida - this is a navigation concern.  We have neither back nor cancel buttons in any of the designs, though these are standard features in many dialogs that I think we should have.  Users are accustomed to being able to go back and forth, whether this is through a button in the page or using their browser's back/forward buttons.  pushState would allow users of mobile devices like phones and tablets to be able to use swipe gestures to go back whenever they realize they really didn't want to change their password.

**Comment by lloyd** [comment]
Good point re mobile.  I've always expected that for mobile we'll generate custom UI for different devices for the best possible experience.

I know you suggest there should be back and forward buttons in the window we spawn, but I don't agree.  There's precedent for the type of dialog we render.

I guess I wonder if we should consider the use of pushState one possible implementation tactic when we go and go deep on mobile devices?

**Comment by shane-tomlinson** [comment]
opening a mobile specific issue - #341
