### ISSUE TITLE
Not authed / secondary / transition_to_secondary

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2770]
If the user isn't logged in, and types an email that is known to us that used to be a primary, but is now a secondary, they need to be shown a transition explaining they need to use the password they created previously on Persona.

Not having a password previously is a different issue.

**Comment by ozten** [comment]
Great work! r+ once [travis is green](https://travis-ci.org/seanmonstar/browserid/jobs/3395109) which you already fixed. I'll check back later to merge.

**Comment by ozten** [comment]
I'm watching https://travis-ci.org/seanmonstar/browserid/builds/3404595 which is still running after 1 hour.

**Comment by lloyd** [comment]
resolved in 781184b5f2b6372c0ce44fff046f1719a78553f9
