### ISSUE TITLE
testuser2@testuser.com needs mock in xhr.js

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2776]
In both the b2g and bigtent sprints, I ran into a missing mock in xhr.js

```
"get /wsapi/address_info?email=testuser2%40testuser.com valid": { type: "secondary", state: "known" },
```

Fixed it.

See https://github.com/mozilla/browserid/pull/2775/files#r2239154 for reference.

**Comment by lloyd** [comment]
fixed
