### ISSUE TITLE
Not authed / secondary / transition_no_password

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2779]
If the user isn't logged in, and types an email that is known to us that used to be a primary, but is now a secondary, and have never used a password with this email, they need to be shown a transition explaining they need to create a password for use with Persona.

**Comment by shane-tomlinson** [comment]
Can this be closed with all of the recent work?

**Comment by jaredhirsch** [comment]
I see the code from PR 2789 in the git log for dev, so I'm closing this.
