### ISSUE TITLE
on-demand cert generation

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#278]
/cc @benadida @stomlinson

Today in several places in the front end code we "sync" email addresses by calling "list emails", and then we go an update all certs all at once.  This occurs _before_ the user may select an identity in the dialog.

This could be a lot better.  Instead what we should do is adapt all of our code to accept that a certificate may or may not be available for any given identity.  Certificate generation should be performed at the time an assertion is requested for a specific identity.  This will reduce upfront latency in rendering the dialog, and will reduce total latency for accounts with more than one email address.

This is not an edge case, given that certs are short lived, the user will hit generation delay frequently, and it will only get worse as we continue to up keylength (however awesome we are, we'll still have double digits on IE8/winxp/1.5ghz machines for a while)

**Comment by benadida** [comment]
I agree with this direction.

**Comment by shane-tomlinson** [comment]
Merge 9af57dafde3c2e6f74da423f7fd44864ac256865 puts this into dev.

**Comment by lloyd** [comment]
woohoo!!
