### ISSUE TITLE
sauce performance enhancement: disable videos for passing tests, disable screenshots always

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2786]
The actual work here is figuring out how to tell sauce that a given test run was a failure.

Ref: https://saucelabs.com/docs/additional-config#performance

**Comment by lloyd** [comment]
How much faster will tests run?

-- lloyd (thumb-typing)

**Comment by jaredhirsch** [comment]
Good question. Needs a little experimentation. Would be useful to mark
tests as passed/failed regardless of whether we ultimately want to
disable/enable videos.

**Comment by jaredhirsch** [comment]
closing as "low-value idea unlikely to ever actually get done"
