### ISSUE TITLE
Set a default for proxy_idps in lib/configuration.js

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2790]
We're working around with a config change in stage and prod, but defaulting here would be best.

Maybe something like:

```
   proxy_idps: {
     doc: "A mapping of domain names to urls, which maps popular email services to shimmed IDP deployments.",
-    format: 'object { } *?',
+    format: 'object {}* = {}',
     env: 'PROXY_IDPS' // JSON text, i.e. {"yahoo.com":"yahoo.login.persona.org"}
   },
```

**Comment by lloyd** [comment]
r+, make a PR

**Comment by jrgm** [comment]
I realized that setting a default would change control flow in lib/primary.js (.has() would now be true not false). So, I'm just gonna change views.js to check `has` before calling `get`.

**Comment by jrgm** [comment]
PR-2809 was merged for this issue and is in production for a while. Closing.
