### ISSUE TITLE
browserid.spec designates wrong version of nodejs

### ISSUE THREAD

**Issue by gene1wood** [mozilla/persona#2791]
At this commit e69ee9965dccd17b9df7a82e767d49d0ad2c6c56 the browserid.spec was set to require "nodejs >= 0.6.17" which worked with our version of nodejs, 0.8.12-3. At this commit 412e0551517f7c9d1d345ba1ed0bc82b29eb55a3 however that requirement was changed to "nodejs == 0.8.12" which is not a version we have.

In order to maintain our desired behaviour of not upgrading to new nodejs versions and get things working this needs to be changed to "nodejs == 0.8.12-3"

**Comment by jrgm** [comment]
Can we designate 'nodejs >= 0.8.12'. @lloyd?

**Comment by gene1wood** [comment]
@jrgm we hadn't wanted that behaviour to prevent having a heterogeneous set of nodejs versions in prod. For example, if some other product at mozilla uses nodejs version 0.8.13, we don't want new browserid servers to get this such that we have untested versions of nodejs in prod and a mixed set of 0.8.12 and 0.8.13 nodejs's within a cluster.

**Comment by jaredhirsch** [comment]
@gene1wood is the specfile the right place to encode that requirement, though? strictly speaking, what you're talking about is a higher-level requirement ("servers should always have the same version of node") that might be better enforced via a config management tool like puppet?

**Comment by gene1wood** [comment]
@6a68 Ya, I'd like to hear @lloyd 's thoughts.

**Comment by jrgm** [comment]
This is done. Closing.
