### ISSUE TITLE
Mostly blank login popup, no next step

### ISSUE THREAD

**Issue by dethe** [mozilla/persona#2792]
[Moving this from a GameOn issue: https://github.com/mozilla/gameon/issues/35 as it seems to be a problem across Persona sites (tried both GameOn and Thimble).]

When I tried to log in, I got what appears to be an incomplete Persona popup[1], not clear how to proceed.

I'm using Firefox 17.0 on OS X 10.8.2. Third-party cookies turned are enabled.

I tried logging in a few times, but it happened consistently. I thought it might only happen from certain pages, but I tried from the GameOn Apply page, from the GameOn Apply page with a submit error, from the GameOn home page, and from the Thimble home page. I tried again the next morning, got the same thing, so it wasn't imagination or a transient issue (I've restarted my browser since then).

Add-ons installed and enabled: Add-on Builder Helper 1.4, Blank Tab Multivariate Test Addon 1.3, BugzillaJS 3.0.4, Firebug 1.10.6, Live HTTP Headers 0.17, Test Pilot 1.2.2. I tried disabling all of these and restarting the browser, same issue.

I hadn't used this computer for some time, thought maybe I had an old browser_id cookie that was conflicting or something. I had one cookie that matched "persona":

site: login.persona.org
cookie name: browserid_state
content: [gibberish I can provide if its helpful]
path: /wsapi
Expires on: Xmas

I deleted that and tried again, still no way to log in via Persona in Firefox.

Firefox is not configured to use a proxy and the OS X firewall is not active. I don't see any network or other errors in the log.

 I get the normal Persona dialog in Chrome, with a field prompting me for my email address, so this appears to be Firefox-specific.

[1] https://www.evernote.com/shard/s5/sh/340a4c55-3f5d-498a-8edc-a71eeed1f280/8938e81cb8d06d83acb708a958c2aea8

**Comment by jrgm** [comment]
Hey, @dethe, was this on a retina display? /cc @shane-tomlinson

**Comment by jrgm** [comment]
@shane-tomlinson any thoughts about what's going on here?

**Comment by dethe** [comment]
Hi John,

Sorry for the delay. No, not on retina, on an older (2008) Macbook. On Macbook Air (one from 3 months ago, now stolen, and new replacement one) I haven't seen the same problem.

**Comment by csuciu** [comment]
I can't repro this issue using Firefox 17.0 on OS X 10.8. The Persona sign in dialogue is displayed correctly when signing in from the GameOn web site. 

@dethe, are you still able to reproduce the bug?

**Comment by jaredhirsch** [comment]
I can't repro either, closing. @dethe please reopen if you can still reproduce this and we'll dig in. :beers:
