### ISSUE TITLE
Login hangs when using iPad 3

### ISSUE THREAD

**Issue by jamesshore** [mozilla/persona#2793]
I have a user, @dfjones1981, who is having trouble logging in to my site with Persona using Safari on his iPad 3 (version 6.0.1 10A523). He's reproduced this on the Mozilla site as well.

**Steps to Reproduce:**
1. Visit https://developer.mozilla.org/en-US/ and click "Sign In" button, then click the "Sign In" button in the "What's This?" pop-up.
2. Enter username in Persona dialog and click "next" button.
3. Enter password in Persona dialog and click "sign in" button.

**Resulting (Incorrect) Behavior:**
1. dfjones reports: "A spinner image appears on the "sign in" button for half a second, then nothing."
2. Refreshing https://developer.mozilla.org/en-US/ and trying again works.
3. After logging out and following the "Steps to Reproduce" again, the problem reappears.

**Expected Behavior:**
1. Successful login.

I haven't been able to reproduce this issue on my iPad 2 or in the iOS simulator. However, dfjones is able to reproduce it consistently on his iPad 3. I'm opening this issue because login to my site is my responsibility. However, @dfjones1981 has agreed to track this issue and provide more information as needed.

**Comment by dfjones1981** [comment]
Just to expand on the Incorrect Behaviour:

When I click the sign in button after entering an incorrect password, I correctly get the "Incorrect Password" message pop up. When I enter my correct password and click the sign in button, the sign in button displays a "please wait" spinning circle icon for a brief moment, then the icon disappears and nothing else happens. I would expect the login to complete and display the original page, but logged in.
If i refresh the page, and go to the persona page again as if to attempt another log in, the persona page has remembered my username and gives me the option to log in without having to enter my password again, or to log out and log in as someone else ("Not You?")

**Comment by jamesshore** [comment]
This turned out to be caused by a case sensitivity issue. Duplicate of #2866.
