### ISSUE TITLE
Use MERGE instead of ON KEY DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2801]
From a suggestion in the mailing list from raul.san@sent.com:

stageUser[1](https://github.com/mozilla/browserid/blob/dev/lib/db/mysql.js#L262) is using the "on duplicate key update" non-standard clause, but it could be used the MERGE statement instead. So somebody could want to use it for another RDBMS.

The MERGE statement would be like (untested):

"MERGE staged ON (email=?)" +
" WHEN NOT MATCHED THEN INSERT (id, newAcct, email, secret, passwd, ts)" +
" VALUES(?,TRUE,?,?,?,?)" +
" WHEN MATCHED THEN UPDATE staged SET" +
" secret=?, existingUser=NULL, newAcct=TRUE, ts=?",

**Comment by lloyd** [comment]
Our code is very mysql specific.  If one wanted to support a different RDBMS, it would be a larger process.  maybe it would be creating a postgresql.js file next to the mysql.js file and factoring out commonality.  given the other 417 open issues, I say let's not pro-actively do this.  I see little value.
