### ISSUE TITLE
IE9 sucks at switching windows

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2805]
We are seeing a lot [1] of test failures where
- it looks like we've logged into 123done/myfavoritebeer successfully
- IE9 cannot find the logged-in node
- the raw selenium log indicates that the element wasn't found as part of a NoSuchWindowException

My guess, based on this, is that IE9 has some bizarro way of sorting handles when it stores them internally. Either that, or it puts the newest window at the 0th, not the nth, spot in the window_handles array, and we only sometimes see this error because it's a race between browser.wwin() switching windows, and the dialog closing, reducing the length of window_handles to 1.

Here's an example of an error log snippet (full log is here [2]) that shows the element lookup failure as the message inside a NoSuchWindowException:

```
15:48:36.094 ERROR - Unexpected exception during findElement
org.openqa.selenium.NoSuchWindowException: Unable to find element with css selector == #emailList .email (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 20.01 seconds
```

Either we manually store the base window handle in every test (since every test uses the dialog and switches back to parent window at some point), or we find a clever but robust way to do this behind the scenes. One trick that could work: assign the topmost window handle when you setup the browser, then, when someone calls wwin() without arguments, pass in the parent window handle by default, instead of assuming the 0th window in the window_handles array is the right one. This is just a guess.

[1] https://gist.github.com/4173166
[2] https://saucelabs.com/jobs/7e772c3b8ebb479186a6bc3fcae657e6/selenium-server.log

**Comment by shane-tomlinson** [comment]
Ah BOOO! I just took the code out that saves the current window handle every time there is a change to wwin. Should we put this back in?
