### ISSUE TITLE
Error while authenticating with assertion

### ISSUE THREAD

**Issue by djc** [mozilla/persona#2814]
Today I tried to login again on a site where I implemented RP flow in August. This site is still using navigator.id.get(), since I haven't had time to upgrade it yet. After clicking the "sign in" button, I first get the "Identity verified" thingy, then there's an error:

"We are very sorry. There has been an error!

Please close this window and try again.

Action: Authenticating with Assertion"

I'm not seeing anything untoward in the Firefox (19.0a2) Web Console, either in the main browser window or in the dialog. Chrome seems to be failing with a differnet failure mode altogether. I have no clue how to debug this, which is really the worst part. Any hints?

**Comment by ozten** [comment]
If you can provide a sample assertion and the following details:

1) Test website you were on
2) Time you signed in

Then I'll crack it open and look at the principal, the issuer, etc to see if there is anything obviously wrong.

You can get the assertion by looking at a network traffic analyzer like HttpFox, Firebug, etc and looking in the POST arguments.

**Comment by djc** [comment]
I've determined this is a problem with my IdP, not with the RP flow. Still, better error messages would help here.

**Comment by djc** [comment]
I've found an actually useful error message in the response from wsapi/auth_with_assertion:

{"success":false,"reason":"assertion issued later than verification date"}

The content of the assertion posted was:

{"iss": "ochtman.nl", "iat": 1354648068000, "public-key": {"y": "7e9b74b55b85ac879aaa4b63db6421b4f21fb967f02b51778159c05dc81c6a7e45044514438565c61b9f8dd2a8097cf460ad06457b44af5c06d985f8699f229f1fbcab7da30ea6eb9792cdfbe85d2b786216605af305321e7edbdf52cb4e8362424df798ec16569eb1fdf4c6cf9cb0e3a443b082de59c835dce99f651240bebc", "p": "ff600483db6abfc5b45eab78594b3533d550d9f1bf2a992a7a8daa6dc34f8045ad4e6e0c429d334eeeaaefd7e23d4810be00e4cc1492cba325ba81ff2d5a5b305a8d17eb3bf4a06a349d392e00d329744a5179380344e82a18c47933438f891e22aeef812d69c8f75e326cb70ea000c3f776dfdbd604638c2ef717fc26d02e17", "g": "c52a4a0ff3b7e61fdf1867ce84138369a6154f4afa92966e3c827e25cfa6cf508b90e5de419e1337e07a2e9e2a3cd5dea704d175f8ebf6af397d69e110b96afb17c7a03259329e4829b0d03bbc7896b15b4ade53e130858cc34d96269aa89041f409136c7242a38895c9d5bccad4f389af1d7a4bd1398bd072dffa896233397a", "q": "e21e04f911d1ed7991008ecaab3bf775984309c3", "algorithm": "DS"}, "exp": 1354669668000, "principal": {"email": "dirkjan@ochtman.nl"}}

> > > time.gmtime(1354648068000 / 1000) # from the iat key
> > > time.struct_time(tm_year=2012, tm_mon=12, tm_mday=4, tm_hour=19, tm_min=7, tm_sec=48, tm_wday=1, tm_yday=339, tm_isdst=0)
> > > time.gmtime()
> > > time.struct_time(tm_year=2012, tm_mon=12, tm_mday=4, tm_hour=19, tm_min=12, tm_sec=14, tm_wday=1, tm_yday=339, tm_isdst=0)

So I'm really not sure what's wrong here?

**Comment by ozten** [comment]
@djc good point.

When we [verify the assertion](https://github.com/mozilla/browserid/blob/dev/lib/verifier/certassertion.js#L95) we pass in `new Date()`. We should probably push this in to the past by some tolerance, to avoid clock skew. Not sure if @warner and @lloyd have discussed this before.

**Comment by djc** [comment]
Right, it turned out the server running my IdP was running about 40s fast.

So I actually have three issues here:
- There's a great error message in the auth_with_assertion response, it should be available from the dialog (after clicking "Show me more"). I got pretty frustrated because I felt stupid for letting my login mechanism be held hostage to a big ball of JS I didn't write; making Persona debuggable would be good for the developer story.
- It would probably be good to offer the IdP a little tolerance in their clock skew.
- It would be wonderful if the UI offered me a way out if my IdP fails (for a while). That's probably a little complicated.

**Comment by djc** [comment]
And what I actually meant to ask: are these issues listed elsewhere, or should I file them separately to make sure they won't get lost?

**Comment by lloyd** [comment]
can we take this to the list?  there are some great ideas in here, but we should discuss them first and based on that open actionable issues for each thing we agree upon.

**Comment by djc** [comment]
For future reference: https://groups.google.com/d/topic/mozilla.dev.identity/fyL8_uc7OLQ/discussion.
