### ISSUE TITLE
b2g and in general: should HSTS max-age value always exceed browserid cookie embedded duration

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2816]
Currently, HSTS max-age is hard coded to be 30 days in our code base. Which is greater than the valid duration of the browserid session-cookie. 

In GH-2681, we're setting authentication_duration_ms to a much longer duration. I haven't thought much about this, but wanted to note this for other folks (ohai, @warner, @fmarier, @lloyd) to ponder.

At minimum, the HSTS max-age should be in configuration and not hard-coded, imho.

**Comment by jrgm** [comment]
Hmm, interesting related note on firefox preload list and max-age to qualify: 

```
http://blog.mozilla.org/security/2012/11/01/preloading-hsts/
Only if a host responds with a valid HSTS header with an appropriately large max-age value 
(currently greater than or equal to 10886400, which is eighteen weeks) do we include it in our list.
```

**Comment by lloyd** [comment]
@fmarier would you look into this and come back with a proposal for what duration we should be usign with HSTS?

**Comment by fmarier** [comment]
@lloyd I can't think of a reason why we'd ever want to provide a non-HTTPS service under the `login.persona.org` domain, so that "18 weeks" (10886400 seconds) looks good.

Given that we are in the preloaded lists for both Chrome and Firefox, right now the value doesn't matter much (as long as it's >= 18 weeks).

**Comment by jrgm** [comment]
Closing in favour of GH-2903 which is a specific action (not my vague question here) and assigning 2903 to @fmarier
