### ISSUE TITLE
[b2g] KPI is enabled on notoriousb2g.personatest.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2821]
Do we really want to do that there?

(This probably also means that enable_development_menu config is true, which perhaps we want at this time).

**Comment by jrgm** [comment]
Please configure notoriousb2g.personatest.org:/home/app/config.json to add:

```
"enable_development_menu": false,
"kpi_backend_sample_rate": 0.0,
```

**Comment by seanmonstar** [comment]
I made the changes and re-deployed.

**Comment by jrgm** [comment]
Thanks @seanmonstar
