### ISSUE TITLE
Password Reset emails not being sent

### ISSUE THREAD

**Issue by erikrose** [mozilla/persona#2829]
I've tried it in Safari and FF now, on two different accounts (one served by me, so I know it's not going into some spam filter), and it seems that password reset emails aren't being sent.
1. Try to log into mozillians.org.
2. Click Forgot Password.
3. Enter a new password, as prompted.
4. Click "reset password".

It says "Check your email at erik att mozilla.com", but nothing ever comes. [Breaking news: I finally got one of the reset mails at my own server, but I'm owed one more. I've still never got any at my mozilla addresses, even after about 16 hours.] Halp. :-)

**Comment by erikrose** [comment]
And now I've got the second one on my personal server. A sure way to fix a problem is to file a bug about it! This has got to be something with the incoming mail server or filters, so never mind.

**Comment by jrgm** [comment]
I know this is closed but do you the email headers for those emails? What do the various time stamps indicate about where it spent its time?

**Comment by erikrose** [comment]
Actually, my Received headers look great. It would seem to indicate it blew 4 minutes on socketlabs' servers, except that it then time-traveled back 4 minutes to land on mine. I confirmed my server does have its clock set correctly, so I suspect email-od.com has its set wrong. Any lag was due to me not hitting Refresh in my phone's mail client.

```
Received: from mail24.smtprelayserver.com (mail24.smtprelayserver.com [64.151.119.54])
        by grinchcentral.com (Postfix) with ESMTP id D27BF400E9
        for <******@grinchcentral.com>; Thu,  6 Dec 2012 14:06:57 -0500 (EST)
Received: from r2.rsc.in.socketlabs.com ([184.106.77.179]) by mail30.email-od.com
        with ESMTP; Thu, 6 Dec 2012 14:11:18 -0500
Received: from sweb2.idsecweb.scl2.svc.mozilla.com ([63.245.208.224]) by r2.rsc.in.socketlabs.com
        with ESMTP; Thu, 6 Dec 2012 14:07:15 -0500
Received: from sweb2.idsecweb.scl2.svc.mozilla.com (localhost [127.0.0.1])
        by sweb2.idsecweb.scl2.svc.mozilla.com (Postfix) with ESMTP id 08A8F7A4114
        for <******@grinchcentral.com>; Thu,  6 Dec 2012 11:06:56 -0800 (PST)
```

So the only mystery that remains is what's going on on Mozilla's incoming mail servers.

**Comment by jrgm** [comment]
Yeah, the clocks in socketlabs are always off. Don't know why that is.
