### ISSUE TITLE
Make browserid send kpi data to kpiggybank awsbox instance

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#2831]
In order to send KPI data confidentially to a kpiggybank server on AWS, there are probably three parts to this issue:
1. Update `lib/wsapi/interaction_data.js` to create https connections (not http as now).  
2. Any webhead configurations, such as updating the proxy config to allow the communication.  (The urls for kpiggybank's api all begin with `wsapi/interaction_data`, if that helps at all; or perhaps it's better to go by IP address.)
3. Any changes to `lib/configuration.js` to use the http_proxy. 

There are other issues that will have to be addressed for kpiggybank, in particular setting up instances, getting ssl certs, and ensuring that read queries are restricted only to privileged apps (like kpi-dashboard).  We can track these elsewhere.

@6a68 , @gene1wood , and I talked this over on IRC.  Crucially, there is this note to bear in mind:

http://irclog.gr/#show/irc.mozilla.org/identity/186352

**Comment by gene1wood** [comment]
jedp, will _all_ calls from the webheads to kpiggybank be POSTs against the specific url path "/wsapi/interaction_data"? Or will the webheads initiate "Stream Changes" calls to kpiggybank?

When we'd talked we had called out the specific target of https://kpiggybank.hacksign.in/ . I'll use that IP in my proxy rules

**Comment by gene1wood** [comment]
Here's the change I'd like to make to enable this. :

```
Index: idproxy-stage.conf
===================================================================
--- idproxy-stage.conf  (revision 54058)
+++ idproxy-stage.conf  (working copy)
@@ -37,6 +37,11 @@
 acl bigtent_microsoft1 url_regex ^https://oauth.live.com/token$
 acl bigtent_microsoft2 url_regex ^https://apis.live.net/v5.0/me?access_token=.*$

+# KPIggyBank connections
+acl kpipath url_regex ^/wsapi/interaction_data$
+# to_dev_kpiggybank is the IP address of kpiggybank.hacksign.in
+acl to_dev_kpiggybank 23.20.153.45/32
+
 # Allow verifier requests over SSL.
 http_access allow bidcert ssl get

@@ -51,6 +56,9 @@
 http_access allow bigtent_microsoft1 post
 http_access allow bigtent_microsoft2 get

+# Allow KPIggyBank calls
+http_access allow to_dev_kpiggybank kpipath post
+
 # Reject any requests to internal networks.
 http_access deny to_localnet
 http_access deny to_localhost
```

**Comment by jaredhirsch** [comment]
@gene1wood I think you're right about the path, based on a little greppin.

It looks like we'll also need to update a couple configuration items in prod, I'm assuming this is done via environment variables:
- KPI sample rate https://github.com/mozilla/browserid/blob/dev/lib/configuration.js#L152
- KPI target URL https://github.com/mozilla/browserid/blob/dev/lib/configuration.js#L157

**Comment by gene1wood** [comment]
@6a68 these config settings would need to be added to our puppet driven config files

**Comment by jedp** [comment]
@gene1wood in response to your question above, currently all calls are single POSTs to that url, yes.

**Comment by kparlante** [comment]
Update: We're going to use personatest.org instead of hacksign.in, so the hosts will be
- https://kpiggybank.personatest.org
- https://kpiggybank-stage.personatest.org
- https://dashboard.personatest.org
- https://dashboard-stage.personatest.org

**Comment by kparlante** [comment]
#3008 Blocks kpi deployment

**Comment by kparlante** [comment]
Update: using the http_proxy is a code change in interaction_data.js, not a config change. I should have a PR tomorrow.

**Comment by jaredhirsch** [comment]
@kparlante reassigning to you, I haven't been too involved with this

**Comment by kparlante** [comment]
@gene1wood, we're ready to configure stage to send kpi data to https://kpiggybank-stage.personatest.org

Also, if you send me ip's, I'll configure the security group.

As per above, to turn this on we need to set kpi_backend_sample_rate, kpi_backend_db_url, and configure the proxy to handle the outgoing connection.

cc: @jrgm, @karlht

**Comment by kparlante** [comment]
The browserid repo changes have been made in #3025, moving config tasks into separate issues. For staging, #3092 and #3093. Closing this one.
