### ISSUE TITLE
[train-2012.12.07/dev] after 'this is not me', must enter same password for both secondaries on same account.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2834]
STR

1) set up so that you have two secondary emails on the same account.
2) Go to an RP and pop the dialog.
3) Click 'this is not me', enter one of the secondary addresses, enter the password, complete signin to the RP.
4) Sign out of the RP, and pop the dialog again.
5) Pick the other secondary address.

Expected: on prod/stage, you are not challenged to enter the password.

Actual: on dev, you are challenged to enter the password again for the account.

Or, is my expected wrong?

**Comment by lloyd** [comment]
your expectation is right, this looks like a bug to me.  trying to reproduce...

**Comment by jrgm** [comment]
Works for me on http://transition.myfavoritebeer.org/

**Comment by jrgm** [comment]
verified stage train-2012.12.07. Fixed with PR-2843.
