### ISSUE TITLE
Cancel button non-functional when primary IDP is broken

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2839]
reproduced by the `broken-primary.js` automated test, currently in the `primary-automation-tests` branch.

**Comment by ozten** [comment]
Thanks for fixing my broken code!

This also affects non-auth users. See pull request for details.

**Comment by shane-tomlinson** [comment]
Adding @ozten's STRs for posterity:

STR

1) Create a new IdP https://testidp.org/
2) Log in with the primary
3) Log out
4) Update IdP's well known to {}
5) Attempt to log in
6) Note offline copy and click 'Cancel'

Actual: Nothing happens

Expected: Return to Auth screen
