### ISSUE TITLE
Some template code appears in the login popup.

### ISSUE THREAD

**Issue by yanndinendal** [mozilla/persona#2845]
#~ "bugzilla.mozilla.org utilise Persona au lieu d'un nom d'utilisateur pour vous identifier."
# ~ "Pour vous identifier avec Persona, veuillez saisir votre adresse de "#~ "courrier électronique."

**Comment by shane-tomlinson** [comment]
Thanks for the report @yanndinendal - Closing as a dup of #2763. You can follow our progress with this bug there!

**Comment by jrgm** [comment]
verified duplicate. Thanks for the bug report. Please reopen if this is not fixed for you.
