### ISSUE TITLE
400 response to /wsapi/cert_key when using mockmyid.com

### ISSUE THREAD

**Issue by yourcelf** [mozilla/persona#2847]
I'm running browserid locally, and signing in with mockmyid.com. After a period of time of being signed in (30 minutes or more) with no problem, firebug reported a 400 error from `/wsapi/cert_key`.  This error persists across refreshes.

![cert_key_error.png](https://f.cloud.github.com/assets/21318/2490/d494d5f0-4227-11e2-8c89-ca40858945ae.png)

Digging into the code, it looks like the failure is emanating from [here](https://github.com/mozilla/browserid/blob/dev/lib/wsapi.js#L397); the operation is `cert_key`, the required level is "password", but the `req.session.auth_level` is only "assertion".

Running Firefox 17.0.1, Ubuntu.

**Comment by seanmonstar** [comment]
What commit do you have checked out locally? Are you updating from the dev
branch?

## 

Sean McArthur
http://seanmonstar.com

**Comment by yourcelf** [comment]
On branch `dev`, commit 8bcfc616632af3a5713a4c2c78c11df1d18f0eb5.

More details on steps to reproduce: 
1. starting afresh with cleared cookies I log in with mockmyid.com.  
2. One hour after my first signin, signout is forced -- it seems there's some baked-in timeout.
3. I sign in a second time, and this time I am presented with the option to stay signed in for 1 month, or to sign in for the session only. I select "one month".
4. One hour later, this error occurs.

**Comment by seanmonstar** [comment]
This sounds like at some point, the dialog wrongly thinks that mockmyid
became a secondary, and so you need to be issued a cert from us. We're
currently landing on dev a bunch of work to deal with secondaries vs
primaries, and so this is likely a bug in the work somewhere.

Cc @lloyd

**Comment by yourcelf** [comment]
I went local in pursuit of [this issue](https://groups.google.com/forum/?fromgroups=#!searchin/mozilla.dev.identity/unminified/mozilla.dev.identity/kDuUnKYr68c/rQ5_0Tpo3n0J) which I brought up on the dev-identity mailing list, and which I was encountering on persona's servers.  I don't know for sure if this error is the same one -- it has similar steps to reproduce, but a different error response (that one complains of a missing function rather than a 400 error).

Is there a branch I can pull that would be closer to the current production code in order to suss that out?

**Comment by jrgm** [comment]
I'll note that mockmyid.com is vulnerable to small amounts of client-side clock skew. Do you perhaps have the network traces from firebug/httpfox/other when you get the 400? (Yes, tedious test case with the one hour default lifetimes).

**Comment by jrgm** [comment]
Oh, stupid comment above. You have the firebug image above. Hrm.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
