### ISSUE TITLE
xhr to session_context fails in the onlogin callback and triggers onlogout (Chrome only)

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2849]
This Chrome-only problem was first discovered by @SyntaxC4 in the PHP cookbook example: https://github.com/mozilla/browserid-cookbook/issues/20

The xhr call to `/wsapi/session_context` in the initial `onlogin` callback returns the following:

```
{
  readyState: 4,
  status: 0,
  responseText: ""
}
```

which fires the `onlogout` callback.

In `start.js`, the `checkAndEmit()` function takes the [error path](https://github.com/mozilla/browserid/blob/train-2012.10.12/resources/static/communication_iframe/start.js#L68) which triggers the following chain of failures:
1. `user.getSilentAssertion()`
2. `user.checkAuthenticationAndSync()`
3. `user.checkAuthentication()`
4. `user.cookiesEnabled()`
5. `network.withContext()`
6. `xhr.withContext()`
7. `xhr.request()`

**Comment by fmarier** [comment]
Test RP demonstrating this problem: http://issue2849.personatest.org/

Code here: https://github.com/fmarier/browserid-issue2849

**Comment by fmarier** [comment]
According to my searches, an HTTP status of 0 in Chrome XHRs is usually reserved for same-origin violations or XHRs from within Chrome extensions. Neither of these should be relevant in this case.

**Comment by ozten** [comment]
This affects production, right?

**Comment by fmarier** [comment]
Yes, that test RP is using https://login.persona.org/include.js

**Comment by shane-tomlinson** [comment]
@fmarier - what is the actual user impact here, does it always log the user out?

**Comment by callahad** [comment]
@fmarier Can you get the demo site back up? I'll then ping someone on the Chrome team to ask about status 0 in XHRs

**Comment by fmarier** [comment]
The RP impact is that they receive an unnecessary `onlogout` callback.

The end-user impact depends on the RP implementation. It could be:
- two extra AJAX calls down,
- one or two extra redirects / page loads,
- or (possibly if the RP is doing something weird) a broken site.

@callahad It's still up, but it looks like DNS is not configured properly. I just noticed I have this in my hosts file:

```
54.242.208.136 issue2849.personatest.org
```

**Comment by fmarier** [comment]
I have redeployed that site and DNS is working now.

**Comment by fmarier** [comment]
Ideas from @lloyd and @warner: maybe the `session_context` XHR is done too early (before the browser is ready or before the origin is set properly). We could try adding sleeps or waiting longer before doing the XHR.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
