### ISSUE TITLE
replace implicit with explicit waits

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2857]
I think we should be able to replace implicit with explicit waits under the covers of our extension methods wclick, wfind, etc.

Interesting, related: https://blog.mozilla.org/webqa/2012/07/12/how-to-webdriverwait/

**Comment by callahad** [comment]
+1. In trying to write BigTent tests, everything was awesome with implicit waits... until it wasn't. And then you have to go all the way back and refactor everything (boo!).
