### ISSUE TITLE
Persona popup shows both e-mail selection and "sign up" elements

### ISSUE THREAD

**Issue by malthe** [mozilla/persona#2863]
![Mozilla Persona: A Better Way to Sign In Bug Report](https://f.cloud.github.com/assets/26405/10551/fcc6a9f0-4523-11e2-89f5-54a4b542760c.png)

**Comment by shane-tomlinson** [comment]
@malthe - thanks for the report! This is completely not cool. What browser/OS are you seeing this on?

**Comment by malthe** [comment]
This was on Chrome – a very recent one.

**Comment by shane-tomlinson** [comment]
Thanks @malthe - I am able to reproduce this about 1 in 10 tries in both the production and beta versions of Chrome for OSX.

**Comment by malthe** [comment]
If you full-screen the popup, then you get the same result. This actually happens rather frequently in Chrome, because popups open in a new tab, typically.

**Comment by jedp** [comment]
I got the same thing yesterday in full-screen firefox on OSX 10.8.  I can try to come up with STR if you need.

![Screen Shot 2012-12-12 at 5 45 54 PM](https://f.cloud.github.com/assets/532953/11269/8c0cb2ba-4549-11e2-96fd-9fcefee38dd8.png)

**Comment by shane-tomlinson** [comment]
this ain't cool. Assigning to me.

**Comment by jrgm** [comment]
So, we understand why this was happening and fixed in production. Thanks for finding this @malthe

**Comment by lloyd** [comment]
we rolled a fix for this into production a couple hours ago

**Comment by jrgm** [comment]
@malthe let us know if you have any further problems. Thanks for the help!
