### ISSUE TITLE
sync calls on requests in lib/template.js

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2868]
https://github.com/mozilla/browserid/blob/dev/lib/templates.js#L60

I think it should be possible to not have to reload these on requests.

**Comment by seanmonstar** [comment]
I'm not sure what you mean. The templates only re-generate if one of the template source files has changed since the last time, otherwise it uses the already generated file.

**Comment by callahad** [comment]
According to @shane-tomlinson this only happens during the build step. Closing.

**Comment by shane-tomlinson** [comment]
@jrgm - I had a good look at this and the sync code in template.js and this was only happening in the build step. As such, I do not think this is a problem.
