### ISSUE TITLE
.watch() redirect page should be white

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#2871]
desired
1. user clicks on email
2. user hits a blank white page on the persona server
3. user is logged in

currently step 2 looks like this http://cl.ly/image/42443t213R37

**Comment by shane-tomlinson** [comment]
The idea is that the user visits the verification page for "only as long as it takes to verify the user" and then it should redirect.

**Comment by skinny97214** [comment]
Upgrading this to four stars

**Comment by lloyd** [comment]
woohoo!  didn't realize this landed.  great improvment to verification flow @skinny97214 & @shane-tomlinson ! :heart:
