### ISSUE TITLE
IE9: tests failing due to missed clicks

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2874]
Now that we've adjusted the implicit wait down to zero, a new class of bugs has appeared.

See https://gist.github.com/4281705 for a list of failures with this problem.

This isn't happening to any specific button, so adding delays would entail adding it at the wclick level, which would make tests so much slower.

Better idea perhaps: wclick checks that the node is gone from the DOM after clicking, if not clicks it again. would fail in cases where the button is reused across steps in a form, or is reused with different classes on it.

**Comment by shane-tomlinson** [comment]
@6a68 - do you think we should revert the implicit wait & related removal of the .delay's until we get this resolved? I didn't see it while testing locally, so I thought things were A-OK.

**Comment by jaredhirsch** [comment]
@shane-tomlinson Tell you what, I'll revert the changes in my fork, run Jenkins 50x, and compare failure rates. We can run through it Monday in triage.

**Comment by jaredhirsch** [comment]
@shane-tomlinson Well, the failure rate is about the same, nearly 50%. Looking more closely now to see if the type of error occurring is any different.

The regular job is here: https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.ie.9/
The temporary job (with the implicit wait re-added) is here: https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.ie.9.with-implicit-waits/
Failure analysis for temporary job: https://gist.github.com/4319268

**Comment by shane-tomlinson** [comment]
@6a68 -

```
➜  automation-tests git:(issue_2945_verify_with_wrong_password) ✗ ./scripts/run-all.js -p 5 -e add-email --platform=win7_ie_9
adding add-primary-to-primary.js
adding add-primary-to-secondary.js
adding cancel-account.js
adding change-password-test.js
adding frontend-qunit-test.js
adding health-check-tests.js
adding broken-primary.js
adding primary-shuts-down-single-email.js
adding primary-starts-up-single-email.js
adding new-user-primary-test.js
adding new-user-secondary-test.js
ignoring public-terminals.js
adding remove-email.js
adding reset-password-test.js
adding returning-user.js
adding sign-in-test.js
Running 15 suite(s) on 1 platform(s), 5 at a time against https://add-email.personatest.org
>>>>>.............................<>...<>..................<>....<>.....................<>.......<>...........<>....................................<>...<>.....................<>....................<..........<...............<.<...<

217/217 tests passed
```

I have run this several times with 217/217 passes. Closing as "appears to be working." If this shows up again, re-open.

**Comment by jaredhirsch** [comment]
\o/
