### ISSUE TITLE
Terms, Privacy Policy and Learn more links don't work on B2G

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#2879]
Migration of https://bugzilla.mozilla.org/show_bug.cgi?id=796185 to github, given that this is a hosted JS code, not client-side code.

The Terms, Privacy Policy and Learn more links on the login screen of the Marketplace app don't work for me, do they try to open a new window or something?

**Comment by seanmonstar** [comment]
They're actually just `<a target="_new"></a>` links. That doesn't sound like anything special.

**However**, UX has asked that we open the ToS and PP links inline, which is implemented in the native dialog. Need to pref that on to see it.

**Comment by shane-tomlinson** [comment]
There is code to take care of this now. It could use cleaned up, but that is another issue. Closing.
