### ISSUE TITLE
Implement a workaround on b2g for persona sign in to get around bug 820057

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#2882]
https://bugzilla.mozilla.org/show_bug.cgi?id=820057 basically will produce a bad experience right now for users to sign into persona, as the keyboard will remain up post sign in. Triage determined that the identity team should see if there's a work-around that could be implemented to get around this bug, so that we don't have to block on bug 820057. This bug tracks that work to implement a workaround.

@benadida and @jedp

**Comment by benadida** [comment]
no way to do this that I can tell, this is a client-side repaint issue. Closing
