### ISSUE TITLE
[b2g] cannot add user to account

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2884]
STR
1. authenticate on b2g with the trusted ui for an account with 1 secondary email address
2. bring up the dialog again and click 'add another email address'
3. enter a second secondary address and submit it
4. dialog transitions to say 'check your mail' (/wsapi/stage_email is submitted)
5. polling of email_addition_status begins
6. after a while, the dialog switches back to show the screen at 3. And at some point shows the 'taking a long time screen. Polling of email_addition_status continues in the background.

Expected: dialog should stay on the screen with 'check your email' until email is confirmed (or the dialog is cancelled)

Actual: #6 above

**Comment by seanmonstar** [comment]
fixed with https://github.com/mozilla/browserid/commit/98f9e06930531b6199f7edd42870c5eba4eec994
