### ISSUE TITLE
etag hash generator uses on-disk content instead of what's being served by browserid

### ISSUE THREAD

**Issue by gene1wood** [mozilla/persona#2885]
In talking to @lloyd it sounds like the code that generates etags to be served with resources uses the on-disk content to create the etag instead of the in-memory content which is actually being served allowing for cache poisoning when an etag is served based on on-disk content and the page that's served with that etag differs. This will happen during every software update between code deploy and service restart.

**Comment by gene1wood** [comment]
Looks like this design is held here : https://github.com/lloyd/connect-etagify/blob/master/etagify.js#L44

**Comment by lloyd** [comment]
Issue restated: etagify assumes that production resources won't be changed on disk while running.

> This will happen during every software update between code deploy and service restart.

So are our processes are handling traffic in the period between code deploy and service restart?  Is it difficult to ensure that this never happens?

**Comment by ozten** [comment]
Thanks for highlighting this.

[connect-cachify](https://github.com/mozilla/connect-cachify) is where we'd fix this.

Let's take this discussion to IRC or the mailing list.

Closing bug until we have a concrete design.
