### ISSUE TITLE
Invalid URLs trigger 500 errors indicating Server Error instead of 400 errors indicating Client Error

### ISSUE THREAD

**Issue by gene1wood** [mozilla/persona#2887]
When an invalid URL is requested such as : `https://login.persona.org/%e3h`

browserid responds with a 500 Internal Server Error

```
$ curl -i https://login.persona.org/%e3h
HTTP/1.1 500 Internal Server Error
Vary: Accept-Encoding,Accept-Language
Content-Type: text/plain
Strict-Transport-Security: max-age=2592000; includeSubdomains
Date: Thu, 20 Dec 2012 00:28:02 GMT
Transfer-Encoding: chunked
Access-Control-Allow-Origin: https://login.persona.org
Connection: close
X-Frame-Options: DENY
```

This type of request should result in a Client Error since the reason the page isn't being served back is because the client is requesting an invalid page :

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

The downsides to returning this Server Error page is that from a monitoring perspective, requests like these can't be distinguished from actual problems that cause unhandled exceptions in the server.

Here are some other URLs that are triggering 500s and shouldn't

```
/%e3h
/..%c0%af
/..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%afetc/passwd
/%bf%27%bf%22
/%f0%27%27%f0%22%22
/%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%afwindows%c0%afwin.ini
//..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%afwindows/win.ini
//%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd
//%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/windows/win.ini
//%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af%c0%ae%c0%ae%c0%af/windows/win.ini
//..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c/etc/passwd
//..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c/windows/win.ini
//%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%aeetc/passwd
//%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%ae%c0%aewindows/win.ini
//%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c/etc/passwd
//%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c/windows/win.ini
```

Please return the appropriate category 400 errors for requests like these.

**Comment by jaredhirsch** [comment]
Not to split hairs here, but I'd expect to return a 404 in that case.

Nothing about the syntax of the request is malformed, it's just that the
specified URI is unknown to us.

**Comment by jrgm** [comment]
Not to split the split hairs, but...
1. Those URI are malformed per decodeURIComponent(), which throws URIError
2. Yes, absolutely 500 must only appear for cases we can't handle ("Help me! I'm broken.").
3. The exception originates in `connect` code, and may be already done more safely in an uplevel version
4. We could either teach the uncaught exception handler to recognize URIError and return some other code, or, at an appropriate place in our middleware check the URI with decodeURIComponent() and bail on malformed with some other code. I prefer the latter as it is more specific. (Side note: but be aware that v8 will not optimize any function that contains a try (true in node 0.8.12, but the v8 team is working to improve that. So isolate the use of try to a util function).
5. I was going to say yeah make it a 404, but for a malformed URI, perhaps 418 from https://tools.ietf.org/html/rfc2324.

**Comment by jrgm** [comment]
By "appropriate place" that could be here: https://github.com/mozilla/browserid/blob/dev/bin/static#L105 for this specific case, but probably better to handle it generically earlier.

**Comment by jrgm** [comment]
Also see https://github.com/visionmedia/express/issues/678

**Comment by callahad** [comment]
Bumping to 4+1-star (not _quite_ 5-star), since this actually did cause a fire drill within the ops team.

**Comment by gene1wood** [comment]
@6a68 : Ya, when I say 400 I mean the Client Error category of errors (4XX). 404 sounds right to me but I wanted to leave it open as to what 4XX error we serve.

@callahad : True, until I got into the actual raw logs I wasn't sure that this wasn't a problem. I also hope to improve our monitoring to not trigger when a single user experiences a bunch of 500's but if a malformed URL were posted to a blog or tweet or something and a bunch of different users went to it, I wouldn't be able to distinguish that from a real problem.

**Comment by gene1wood** [comment]
If there's an interest I could fetch all the URLs that have triggered 500's in the last month. Let me know if that would be useful.

**Comment by jrgm** [comment]
@gene1wood yes I'd like this list. I hate 500's.

**Comment by jrgm** [comment]
Verified. The example URL are all now 404. I have a list of others to research for why they bomb.
