### ISSUE TITLE
add system nonce to password hashing, as per Mozilla Security Guidelines

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#289]
The recommendation is to HMAC in a system secret in addition to bcrypt:

https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines#Password_Storage

This will also require an upgrade capability for passwords that are not mixed in with system nonce.

**Comment by lloyd** [comment]
the migration to this is crappy if we do not do the work factor update and system secret at the same time.  We would need to include a new field in the user database to indicate whether the secret is hashed into the password.  

would we consider doing this in lockstep with work factor update which would not require additional database state?  Or is there a way to stash additional bits of application level information in the bcrypt hash?

**Comment by benadida** [comment]
agreed from bug triage meeting that we will not lock-step with work factor update. When we do this, we will add to the password-hash field content a delimiter and indication of the system nonce.

**Comment by lloyd** [comment]
the maintainer of node.js bcrypt has already demonstrated an awesome willingness to accept our patches, we could consider using an 'application specific' data field of the bcrypt nonce to store password versions to migrate in the system nonce.  this is not a change to @benadida's suggestion, just a proposed implementation tactic.

**Comment by benadida** [comment]
so @lloyd do you mean this just to store the password _version_, not the actual system-wide nonce right?

**Comment by lloyd** [comment]
Correct.

--lloyd

**Comment by shane-tomlinson** [comment]
@lloyd, @benadida - has this been taken care of?

**Comment by benadida** [comment]
no, it hasn't, let's review with @warner

**Comment by warner** [comment]
Yeah, if we add this, I'd prefer to put it into the bcrypt module, and add a field to the hashed password to indicate the use of a systemwide nonce. It'd probably be a good idea to include a nonce-version field, so we can gradually rotate to new system-nonces, but we'd also need to be able to efficiently identify which rows still need upgrading, which a simple magic string might not provide (imagine doing LIKE queries against the hashedPasswd field). To really handle that would require a new column.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
