### ISSUE TITLE
Please confirm that no change to this URL is ok.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2896]
For the update GH-2889, I was comparing stage on the new build vs. production.

In starting to compare the '.js$|.css$' files for urls that hadn't changed, I noticed one oddity. 

'https://static.login.anosrep.org/v/4da163f37c/production/en/dialog.js' has a reference to 'https://login.anosrep.org/v/1e78e62723/dialog/css/style.css'. That appears to come from here (?): 
resources/static/dialog/views/test_template_cachify.ejs from looking at unminified en/dialog.js. 

Now the resources/static/dialog/css/style.css shows a change on Oct 5th, and then on Nov 27th and Nov 30th, so appears to be outside the window (and appears to be for testing?).

@lloyd, @shane-tomlinson please confirm that this is expected and safe.

(Also, 1. f this is test code should this be in the build (or is this part of the disabled--in-production development menu, and 2. note that this is not on static.login.anosrep.org).

**Comment by lloyd** [comment]
yep, test template.  non issue.
