### ISSUE TITLE
css fix to reduce need for JS to display about page

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#2900]
nemo suggests:

footer { position: fixed; } #wrapper { margin-bottom: 30px; }

**Comment by shane-tomlinson** [comment]
This will upset our IE8 users I believe. Need to recheck.

**Comment by shane-tomlinson** [comment]
The other thing is we use the js to centre the content vertically, to do so using display: table-cell,  an explicit height must be set on a container element, percent values do not work.

**Comment by lloyd** [comment]
what's the actual issue here?  none of us in the scrub have context to understand what issue we're solving.

**Comment by callahad** [comment]
Here's context from IRC on Dec 21st:

> [17:18:05] &lt;nemo&gt; https://login.persona.org/about
> [17:18:05] &lt;nemo&gt; footer is absolute instead of fixed, so it doesn't scroll
> [17:18:05] &lt;nemo&gt; and if it is set to fixed, the wrapper div needs a margin-bottom to make room for the footer
> [17:18:08] &lt;nemo&gt; as it is, the footer gets in the way of the description of Persona
> [17:22:30] &lt;nemo&gt; someone is "fixing" the footer w/ javascript :D
> [17:22:38] &lt;nemo&gt; requires NoScript to notice it

Also, regarding upsetting IE8, Nemo added "that's only IE6, not IE7 or IE8"

Lastly, the vertical centering seems like an unrelated issue:

> [20:06:58] &lt;nemo&gt; unless he's talking about getting rid of the JS entirely
> [20:07:04] &lt;nemo&gt; I'm sure a small amount of effort could do that
> [20:07:11] &lt;nemo&gt; but in terms of readability, the footer is the main problem

**Comment by shane-tomlinson** [comment]
I was wrong - a quick experiment shows that `position: fixed` does work in IE8.

The reason we used Javascript to place the footer is the desired behavior as explained to me:

1) If the content height is > viewport height, place the footer below the contents. The footer does not scroll with content. It remains pegged below the content.
2) If the content height is < viewport height, place the footer at the bottom of the screen and vertically center the contents.

Adding a position: fixed will break #1.

I am open to revisit this decision, but I would like input from @skinny97214 before doing so.

**Comment by benadida** [comment]
@shane-tomlinson @skinny97214 we shouldn't let JS/no-JS drive the UX.

The only question here is: can we, relatively easily, make the front and documentation pages of Persona.org render properly without JS? @shane-tomlinson will a media query solve the dichotomy your'e looking for? If so, let's do it. If you can't figure it out in 30 minutes, let's close this issue and move on.

**Comment by skinny97214** [comment]
LMK where the CSS wizards land on this question.

**Comment by jaredhirsch** [comment]
meh. unassigning myself & labeling as good first bug.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
