### ISSUE TITLE
Send  a longer STS max-age so that we get STS pinning

### ISSUE THREAD

**Issue by evilpie** [mozilla/persona#2903]
persona.org was originally included in the STS pinnig list included with Firefox 17. Due to some issues all sites having a max-age small than 18 weeks however were removed from that list. This means persona.org at the moment is not on the preloaded STS list. (https://bugzilla.mozilla.org/show_bug.cgi?id=786417)

Please change the max-age of the Strict-Transport-Security head on login.persona.org and persona.org. We also probably need to coordinate with Firefox so that we update the list.

**Comment by jrgm** [comment]
Also noted in GH-2816.

**Comment by jrgm** [comment]
Gifted to @fmarier to make this change (and closed GH-2816)

**Comment by jrgm** [comment]
Also, the request above is for persona.org and *.persona.org. But should also cover legacy browserid.org, I suppose.

**Comment by evilpie** [comment]
Any update on this?

**Comment by lloyd** [comment]
merged. should be in production on feb 13th.  http://personatra.in/#2013.02.01

**Comment by evilpie** [comment]
Great, thank you.

**Comment by evilpie** [comment]
The max-age of login.persona.org is still 2592000. And we are close to shipping!

**Comment by jrgm** [comment]
Ugh. So, this also needs an update in bin/static and bin/router. (bin/browserid is serving 18 weeks when queried directly, but it's moot, since router stands in front of it).

**Comment by jrgm** [comment]
request in stage for any GET path returns 'Strict-Transport-Security: max-age=10886400; includeSubdomains'. Should go out to prod tomorrow.
