### ISSUE TITLE
[b2g] error message bringing up trusted UI (sometimes) - "uncaught exception: target window is same as present window -- not allowed"

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2904]
When looking at logcat output for b2g with native identity enabled, I occasionally see this error reported which comes from jschannel (I think). I don't have specific STR other than to bring up the trusted UI, and don't know for sure if this has adverse effects. But seems like something that should be investigated.

E/GeckoConsole( 1082): [JavaScript Error: "uncaught exception: target window is same as present window -- not allowed"]

**Comment by jedp** [comment]
I see this happening in the desktop browser as well.  It does appear to be harmless, but it is disconcerting.

https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/lib/jschannel.js#L244

I'm going to take the b2g milestone marker off so that it appeals to a broader audience.

**Comment by shane-tomlinson** [comment]
@jedp or @jrgm  - are you still seeing this?

**Comment by jrgm** [comment]
Yes, this still happens.

**Comment by stephendonner** [comment]
We just saw this in a run of a Marketplace Payment automation test: http://qa-selenium.mv.mozilla.com:8080/job/b2g.unagi.mozril.gaia.v1-train.ui.marketplace_payment/885/

Logcat: http://qa-selenium.mv.mozilla.com:8080/job/b2g.unagi.mozril.gaia.v1-train.ui.marketplace_payment/885/artifact/logcat.txt

https://www.dropbox.com/s/3spttd7ua6tn2qy/identity-failure-logcat.txt, for posterity.

**Comment by stephendonner** [comment]
@kumar303 @vaidik @zacc @bebef1987 ^^^

**Comment by stephendonner** [comment]
Saw this again (still) on our v1-train Marketplace Payments automation:

http://qa-selenium.mv.mozilla.com:8080/job/b2g.unagi.mozril.gaia.v1-train.ui.marketplace_payment/1715/

Here's a logcat w/it: http://pastebin.mozilla.org/2990561

Can we bump this up a bit in priority?  Thx :-)

**Comment by stephendonner** [comment]
For more info, I just noticed that this occurs even when our Payments test passes, so it doesn't appear to be fatal:

http://qa-selenium.mv.mozilla.com:8080/job/b2g.unagi.mozril.gaia.v1-train.ui.marketplace_payment/1716/

For the full logcat: http://pastebin.mozilla.org/2990572

**Comment by jrgm** [comment]
```
$ curl -s 'http://qa-selenium.mv.mozilla.com:8080/job/b2g.unagi.mozril.gaia.v1-train.ui.marketplace_payment/1716/' | grep -c uncaught
0

$ curl -s 'http://pastebin.mozilla.org/2990572' | grep -c uncaught
0
```

@stephendonner is this about this issue as originally described, or did you update the wrong issue?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
