### ISSUE TITLE
[b2g] fix (or remove) footer for /privacy and /tos when in iframe of trusted UI

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2905]
Sorry if this is a duplicate of some other bug somewhere else. 

Anyways, the footer is at a fixed position when /privacy and /tos are viewed in an iframe from the trusted UI on b2g and doesn't scroll properly

![2013-01-03-20-31-51](https://f.cloud.github.com/assets/758162/41660/249e4f50-55e6-11e2-96f9-987dace8f555.png)

But the links in that footer seem pointless in this constrained UI, so probably better to just hide the footer entirely.

**Comment by shane-tomlinson** [comment]
Is this related to #2900?

**Comment by jrgm** [comment]
How #2900 is addressed would affect this (but just hiding the footer in this case seems best for this case).
