### ISSUE TITLE
[b2g] webfont cross-origin errors when loading iframe for https://notoriousb2g.personatest.org/tos (or /privacy).

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2906]
I see these errors in `adb logcat` when bringing up the notoriousb2g tos or pp iframe. Although I don't really understand why since the webfont file is being served with `Access-Control-Allow-Origin https://notoriousb2g.personatest.org`. 

Anyways, presumably this means we're falling back to some other font, but visually I don't notice anything really bad as a result.

```
E/GeckoConsole( 6353): [JavaScript Error: "downloadable font: download failed (font-family: "Open Sans" style:normal weight:300 stretch:normal src index:4): bad URI or cross-site access not allowed
E/GeckoConsole( 6353): source: https://notoriousb2g.personatest.org/v/1bf71be111/common/fonts/OpenSans-Light.ttf" {file: "https://notoriousb2g.personatest.org/v/b421fea41c/production/browserid.css" line: 0 column: 0 source: "@font-face {
E/GeckoConsole( 6353):   font-family: "Open Sans";
E/GeckoConsole( 6353):   font-style: normal;
E/GeckoConsole( 6353):   font-weight: 300;
E/GeckoConsole( 6353):   src: local("Open Sans Light"), local("OpenSans-Light"), url("https://notoriousb2g.personatest.org/v/1112689d33/common/fonts/OpenSans-Light.eot") format("embedded-opentype"), url("https://notoriousb2g.personatest.org/v/c335fd209b/common/fonts/OpenSans-Light.woff") format("woff"), url("https://notoriousb2g.personatest.org/v/1bf71be111/common/fonts/OpenSans-Light.ttf") format("truetype");
E/GeckoConsole( 6353): }"}]
E/GeckoConsole( 6353): [JavaScript Warning: "downloadable font: no supported format found (font-family: "Open Sans" style:normal weight:300 stretch:normal src index:5)
E/GeckoConsole( 6353): source: (end of source list)" {file: "https://notoriousb2g.personatest.org/v/b421fea41c/production/browserid.css" line: 0 column: 0 source: "@font-face {
E/GeckoConsole( 6353):   font-family: "Open Sans";
E/GeckoConsole( 6353):   font-style: normal;
E/GeckoConsole( 6353):   font-weight: 300;
E/GeckoConsole( 6353):   src: local("Open Sans Light"), local("OpenSans-Light"), url("https://notoriousb2g.personatest.org/v/1112689d33/common/fonts/OpenSans-Light.eot") format("embedded-opentype"), url("https://notoriousb2g.personatest.org/v/c335fd209b/common/fonts/OpenSans-Light.woff") format("woff"), url("https://notoriousb2g.personatest.org/v/1bf71be111/common/fonts/OpenSans-Light.ttf") format("truetype");
E/GeckoConsole( 6353): }"}]
```

**Comment by jrgm** [comment]
Actually, it may be the case that this error is defeating caching on b2g for the trusted dialog.

Every time the /sign_in dialog comes up on b2g, requests are made for /v/&lt;hash&gt;>/common/fonts/{OpenSans-Light.ttf,OpenSans-Regular.ttf,OpenSans-Bold.ttf}.

These three requests return 200 OK with appropriate headers for caching, but each subsequent request makes an unconditional GET, and the above error is shown again in `adb logcat`. 

(Note: I do not see the same problem (either the error message, or the non-cached behaviour) with desktop FF 18.0.1 on Ubuntu when using native-persona.123done.org to bring up the dialog from native-persona.org).

So, these requests return a total 650KB, which is a _big_ hit on network time on the phone.

Platform: 18.0
Build Identifier: 20130131111648
Update Channel: Nightly

@jedp, @seanmonstar, @shane-tomlinson, @fmarier: let me know if I can help in setting up nspr logging for HTTP on b2g so you can see the request/response messages for yourselves.

**Comment by shane-tomlinson** [comment]
@jedp - is this still an issue?

**Comment by jedp** [comment]
I think once we're using the on-device gaia sans-serif font, this is going to be a non-issue.

**Comment by shane-tomlinson** [comment]
@jedp - can you write STRs, I have not seen this on device.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
