### ISSUE TITLE
[b2g] failure(s) in opening email link to /verify_email_address

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2909]
STR
1. Load http://notoriousb2g.123done.org and click the 'Sign in with Persona' button.
2. In the trusted dialog, enter a secondary email address not used before with notoriousb2g.
3. Enter a password twice and submit.
4. Leave the trusted dialog up, but switch to the email client.
5. Find the verify message in email and click the link to /verify_email_address. (Click OK when prompted for 'Browse to URL'.
6. The UI switches to show the trusted UI, but nothing apparently happens.
7. In logcat where I have enable verbose HTTP logging (see https://etherpad.mozilla.org/http-logging-for-b2g), I can see requests are made for 

```
GET /verify_email_address?token=Af0hoaf71WGlbCAt7SA4Za6JlXqkohhoAUhC5QsJVpHxLzHA
GET /wsapi/session_context
GET /wsapi/email_for_token?token=Af0hoaf71WGlbCAt7SA4Za6JlXqkohhoAUhC5QsJVpHxLzHA
```

which all return 200 OK, but I can't see the actual content body returned. Also, I can see `GET /wsapi/user_creation_status?email=abcabdab%2Bs21%40gmail.com` polling continue, but the trusted UI just stays in the same state.
8. I cancelled out of the trusted UI, and the browser is showing /verify_email_address loaded. The username appears blank, but if I enter the password (which isn't displayed as '****...'), I can complete the signup as the email I started with.
9. Looking at the HTTP request headers, I see that no cookie is sent on the /verify_email_address request, which implies that this request is not made in the same context as the /wsapi/stage_user request was made.

So this is really two issues at core:
1. Following a link from email is not made with the right cookie jar(s) available.
2. Display issues in the /verify_email_address page.

**Comment by jrgm** [comment]
So, in 2013-01-07-10-58-06 build, the display problem is not there anymore. 

But the request for /verify_email_address, etc., are made without the browserid_state cookie.

**Comment by seanmonstar** [comment]
I imagine this and #2918 are the same thing.

**Comment by seanmonstar** [comment]
Emails sent to people when allowUnverified is true should get a confirmation email, instead of the newUser email, so they won't be sent to `/verify_email_address` anymore.
