### ISSUE TITLE
BrowserID.internal.get() should allow application-defined claims

### ISSUE THREAD

**Issue by lhoward** [mozilla/persona#2910]
We have a profile for using BrowserID in the GSS-API/SASL, so that non-web applications may authenticate using BrowserID. It is described at http://www.padl.com/~lukeh/gss-browserid.html.

The mechanism supports channel binding (so the authentication can, for example, be bound to a TLS channel) and can perform a Diffie-Hellman key exchange in order to establish a shared session key, used for message protection services and fast re-authentication. Both of these parameters need to be included in the assertion, so they are signed with the user's private key.

In an earlier implementation of the mechanism, these were encoded in the audience URL. Our current implementation overrides jwcrypto.assertion.sign() so that it can insert the addition claims immediately prior to signing. As this is obviously implementation dependent and unsupported, I would like to ask that when an assertion is requested from a native app - that is, the usage is #NATIVE and BrowserID.internal.get() is called - that it be possible to submit application-specific claims for inclusion in the assertion. This could be an additional parameter or a new key on the options object.

**Comment by ozten** [comment]
@lhoward - Had a chance to discuss this and Issue #2913 in the bug triage meeting.

The core team is excited about your work on a BrowserID GSS mechanism. Working through these ideas and sharing updates on the mozilla.dev.identity mailing list is awesome.

We're going to close these two bugs for the following reasons:
- Issues against mozilla/browserid should be very specific reports of a bug against the core system. They should include steps to reproduce, actual results, and expected results
- GSS-API/SASL design should take place on the mailing list, not this issue tracking system
- GSS-API/SASL implementation issues would be best tracked in that project

We are really excited about the potential for GSS-API and another SASL mechanism! Keep up the great work in your project and in our mailing list.

**Comment by shane-tomlinson** [comment]
Re-opening since @lhoward has issued #3952 to address this.
