### ISSUE TITLE
[b2g] js error loading notoriousb2g.myfavoritebeer.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2912]
On a b2g phone with dom.identity.enabled, go to notoriousb2g.myfavoritebeer.org. WIth a build from 2012-01-07, I get this error and the page does not layout.

```
E/GeckoConsole(  694): [JavaScript Error: "Error: Permission denied to access property 'sessions'"
 {file: "http://notoriousb2g.myfavoritebeer.org/js/main.js" line: 10}]
```

where line 10 is:

```
function setSessions(val) {
  if (navigator.id) {
    navigator.id.sessions = val ? val : [ ];
  }
}
```

**Comment by seanmonstar** [comment]
Hm, that'd be because with native identity, navigator.id is probably a `WrappedJSObect` or something similar, which means other contexts don't have permission to change it's properties.

We need to decide if this is a bug in the native implementation (people should be able to modify navigator.id) or in myfavoritebeer (it should store sessions somewhere else).

/cc @jedp

**Comment by jedp** [comment]
Yes, I expect that's what's happening.  The object is not initially defined in user space; it's privileged.  When it's exposed to user space, you can't change it.

Similar example that will work in any firefox browser, try: `navigator.mozCameras.glurk = 42` then note that `navigator.mozCameras.glurk === undefined`.

This is a tricky problem, as an RP would get away with this on the shim, but then find itself in trouble on native implementations and be confused.

I think though that I would decide that the RP should not be allowed to modify properties on navigator.id.  Even if we fix this somehow in firefox, who's to say that the same would be done by google or other potential native implementers?

**Comment by lloyd** [comment]
@shane-tomlinson to clean up obsolete session stuff in myfavoritebeer.

**Comment by shane-tomlinson** [comment]
Removed the obsolete session code on mfb. Closing.
