### ISSUE TITLE
Origin check fails when using custom URLs

### ISSUE THREAD

**Issue by lhoward** [mozilla/persona#2913]
My application uses a non-HTTP/HTTPS URL in the assertion audience. This works fine with BrowserID.internal.get(), however origin validation (in lib/validate.js) fails with "not a valid origin" if the user does not have an existing Persona identity and attempts to create a new one. It would be good to relax this check to accept any valid URN if called from the internal path.

(Example URL: urn:x-gss:ldap/browserid.persona.org)

**Comment by ozten** [comment]
Closing this bug do to reasons noted in Issue #2910.

I'll follow up on the mailing list with my advice on this two bugs.
