### ISSUE TITLE
[b2g] wrong cookie jar used on restart for this scenario

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2915]
This is related to GH-2914.

STR
1. Go to http://notoriousb2g.123done.org and auth with an existing secondary user (only one email on the account).
2. Create a new tab in the phone browser, and load https://notoriousb2g.personatest.org
3. Restart the phone and go to http://notoriousb2g.123done.org again.

Expected: You should be auth'd with notoriousb2g.personatest.org and presented with a sign in button in the trusted UI.
Actual: You are prompted for an email address.

I can see in adb logcat with http logging that the 'browserid_state...' cookie that is offered in (3) is the cookie that was set in step (2). So, not the authenticated client-session cookie that was generated in step (1).

**Comment by shane-tomlinson** [comment]
@jedp, @jrgm - is this still the case?

**Comment by jedp** [comment]
I was having trouble reliably reproducing this.  And there is a serious bug underneath it all.

Apparently, on FirefoxOS, tabs are their own windows on _desktop_ builds; and on mobile, tabs are _iframes_ within a single window.  All along the native identity solution has been completely unaware of this.  It has taken its cue from its desktop origins, where window id is used as a unique id in messages.  But these IDs are not unique enough on FirefoxOS mobile!

I have a patch submitted that fixes this problem on platform.  It is a DOM component issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=868530

Received initial f+; waiting for r=jst

**Comment by jedp** [comment]
The fix was uplifted into the v1.0.1 release (which goes to market) and has been performing correctly in tests.  So closing this.
