### ISSUE TITLE
[b2g] 503 error when creating unverified email account

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#2918]
Initially reported by Krupa; I can reproduce:

Using the marketplace-dev app downloaded from http://people.mozilla.org/~kmcmillan/mktdev.html, I tried to login with a new unverified email address.  I already have a `jparsons@mozilla` address with notoriousb2g; I chose `jparsons+foo@mozilla`.

Marketplace received an unverified assertion from notoriousb2g and signed me in

In my desktop browser, I went to my mozilla inbox and clicked on the  waiting "verify email" link, which took me to notoriousb2g

I entered my password and received an error that the server was under extreme load.

The actual `dbwriter.log` reads:

```
{"level":"warn","message":"couldn't complete email verification: this verification link is not for a new account","timestamp":"2013-01-08T21:04:30.443Z"}
{"level":"warn","message":"database is down, cannot process request: this verification link is not for a new account","timestamp":"2013-01-08T21:04:30.443Z"}
{"level":"info","message":"127.0.0.1 - - \"POST /wsapi/complete_user_creation HTTP/1.1\" 503 453 41 \"-\" \"-\"","timestamp":"2013-01-08T21:04:30.446Z"}
```

Unfortunately, this is preventing QA from testing marketplace+identity.

**Comment by seanmonstar** [comment]
I see, I was sending the wrong email. I switched it to `email.sendConfirmationEmail`, which is the same one sent when adding a new unverified email to an existing account.

I'd test on that link you put in the description, but the linked page scares me.

**Comment by seanmonstar** [comment]
kumar says i've fixed 'er.

**Comment by jedp** [comment]
Thank you sir!

**Comment by jrgm** [comment]
Works for me with 2012-01-08 b2g. Email link is for /confirm; user is signed in.
