### ISSUE TITLE
[b2g] account_cancel of unverified user has 503 error on foreign key constraint

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2919]
STR
1. With marketplace sign up as a new unverified user
2. Open a new tab and load notoriousb2g.personatest.org
3. Sign in with that user's email address and password.
4. In the admin UI, click on 'cancel your account'.

Expected: all relevant rows are removed in database and UI shows the account is gone.
Actual: UI shows 'We are very sorry...' with details of POST /wsapi/account_cancel and 503 code.

In the server logs: 

```
{"level":"warn","message":"database is down, cannot process request: Error: Cannot delete or update a parent row:
 a foreign key constraint fails (`browserid`.`staged`, CONSTRAINT `staged_ibfk_1` FOREIGN KEY (`existing_user`) 
 REFERENCES `user` (`id`))","timestamp":"2013-01-09T00:36:35.355Z"}
```

The email row is gone, but it chokes on removing the user row due to the fkey on staged.

![2013-01-09-00-44-00](https://f.cloud.github.com/assets/758162/52313/ecda8eb8-59f9-11e2-89c8-a8994f8e882e.png)

**Comment by seanmonstar** [comment]
At this point, an "unverified" user in b2g is just a normal user in Persona, who has had an email staged. Would the same thing happen in Persona if I staged a new email, and then tried to delete my account?

**Comment by jrgm** [comment]
It probably would error out, if you could actually do that. But in the absence of unverified email, you couldn't ever be logged in while the row is in the staged table and cancel the account ;-)

**Comment by seanmonstar** [comment]
Oh? I imagine I can make this happen :)

**Comment by seanmonstar** [comment]
STR:
1. Create an account with an email and verify on dev.123done.org
2. Logout, login, and Add another email. Don't verify.
3. Go to login.dev.anosrep.org and login.
4. Cancel your account.

kaboom!

**Comment by seanmonstar** [comment]
@lloyd or @gene1wood The delete query is failing because of relying foreign keys. Any reason why I shouldn't modify the schema to use `ON DELETE CASCADE`?

**Comment by lloyd** [comment]
I'm scared by this idea, but I cannot say why.  inspect `cancelAccount` in mysql.js.  Currently it explicitly deletes all emails before deleting users.

CASCADE seems like a viable approach to me, but this makes me wonder about how our software behaves with dangling pointers in the staged table?

suggestion: for the purposes of this patch just add another DELETE query, then let's look at cascade separately and perhaps get sheeri's thoughts about depending our dependence on Foreign key constraints in mysql.
