### ISSUE TITLE
Privacy Policy has outdated, scary bullet point

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2922]
At the very top of https://login.persona.org/privacy is this bullet:

> As part of the normal operation of the Persona service, Mozilla will retain a log of which sites you have disclosed your email to.

AFAIK, we are not logging this. Can we please get legal review and remove this bullet?

@benadida, what's the next step? Should I file a Bugzilla bug targeted at Jishnu or the Legal team in general?

**Comment by benadida** [comment]
@callahad no, no need to file, the new privacy policy is almost done, I'm still working with Jishnu on it.

**Comment by lloyd** [comment]
@benadida please link to the tracking bug/document/website/whatever.

**Comment by benadida** [comment]
@lloyd privacy policies have a separate process within legal at Mozilla, with a post to dev-governance coming from Jishnu soon. I think we can use this issue as a tracker for us.

**Comment by lloyd** [comment]
sounds great.  exactly what we concluded in triage today.

**Comment by jaredhirsch** [comment]
bump. any open legal bugs we can tie to this one?

**Comment by benadida** [comment]
@6a68 discussion underway on dev-governance, I'll check in with Jishnu.

**Comment by benadida** [comment]
Jishnu is out this coming week, I'll check back with him when he returns.

**Comment by jaredhirsch** [comment]
@benadida ping - any news?

**Comment by callahad** [comment]
@benadida I'm excited for the new privacy policy, but as a stopgap can we get Jishnu's approval to just delete that one damned bullet point and keep the rest of the document intact? This has been an issue for months.

**Comment by benadida** [comment]
In general, no we shouldn't tweak privacy policies very often. But the good news is, this is moot, cause Jishnu has completed the privacy policy and its review:

https://bugzilla.mozilla.org/show_bug.cgi?id=848506

Woohoo! Let's make it happen.

**Comment by callahad** [comment]
Yay!
