### ISSUE TITLE
Ensure all b2g locales are supported

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2939]
@mathjazz Do you know which locale codes will be baked into the b2g device for the Brazil market?

Potential problem: Our production system displays English for `pt`. We do have a locale for `pt-BR` however.

Questions:
1) What is the final list of locales on the b2g device?
2) Should we alias pt-BR to pt? If so, what is the best way to do that? Rename the pt-BR directory?

**Comment by Pike** [comment]
FxOS should report pt-BR or es right now.

**Comment by ozten** [comment]
Perfect. Thanks Pike!

We have pt-BR and es. Closing.
