### ISSUE TITLE
all /wsapi/ returns should be Cache-Control: no-cache

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#294]
Inspecting network behavior of IE9 shows that it's caching CSRF responses.  Frequently this just works, however several conditions exist where it does not (any time the server regenerates the csrf).

Generally the node server should return a `Cache-Control: no-cache` on all WSAPI requests.

**Comment by benadida** [comment]
we may need to forcefully cache-bust with a timestamp parameter, just to be extra sure.

**Comment by lloyd** [comment]
Totally.  We could do something like that later if we find some browser that doesn't respect the cache headers we're now sending (no-cache + max-age: 0).
