### ISSUE TITLE
Dialog form not immediately visible

### ISSUE THREAD

**Issue by zaach** [mozilla/persona#2940]
On Firefox 18, OS X 10.8.2 (retina)

STR
- go to dev.123done.org
- click on Persona sign in button
- observe dialog with missing form

![Screen Shot 2013-01-15 at 1 40 53 PM](https://f.cloud.github.com/assets/3903/69390/95e8b9a0-5f5c-11e2-823e-2f31f44ef4ee.png)

Once you resize the dialog it returns to normal and the form appears.

**Comment by zaach** [comment]
This only happens when Firefox is in "retina mode". On my external monitor it looks fine.

**Comment by jaredhirsch** [comment]
Closing; I can't repro. @zaach, please reopen if you're still seeing this.
