### ISSUE TITLE
Unhelpful error message displayed if user enters in the wrong password on email verification

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2945]
STR

1) In browser 1, stage a new user
2) In browser 2, open verification link
3) Enter an incorrect password
4) Check out the very unhelpful error message.

![error-message-post-verification-wrong-password](https://f.cloud.github.com/assets/848085/71419/f62f4fbe-5fe7-11e2-8b83-6c3aea8d20be.png)

More desirable:

Give the user another chance to enter their password.

**Comment by jaredhirsch** [comment]
Oh no! There _were_ other similar edge cases

**Comment by jaredhirsch** [comment]
feel free to assign me on the pull request when it's ready

**Comment by shane-tomlinson** [comment]
@6a68 - I cannot reproduce this. Can you give it a try, and if it is unreproducible, close?

**Comment by jaredhirsch** [comment]
Yay! The dialog is unaffected by bad attempts and I get a helpful tooltip in the persona window:

![Screen Shot 2013-04-03 at 10 19 05 AM](https://f.cloud.github.com/assets/96396/335011/ae22befe-9c82-11e2-93e1-4c024ded117c.png)

Closing with gusto and an artful flourish :art:
