### ISSUE TITLE
Put communication_iframe.js on a diet.

### ISSUE THREAD

**Issue by potch** [mozilla/persona#2946]
Taking a look at the resources loaded by marketplace.firefox.com and observed that the JS used by the communication <iframe> clocks in at well over 100K, making it the second largest resource loaded by a visitor to our site. As a resource loaded by every site using BrowserID, that file should be as small as tolerable.

**Comment by jedp** [comment]
Hi, @potch.  We're actively working on this, particularly with marketplace and b2g in mind.  @shane-tomlinson and @fmarier have already done a lot of research and work towards huge improvements.  We're kicking off a little task force next week that includes Krupa from marketplace QA.  Our goals are smaller code, and fewer https requests.  We're going to do everything we can to make it good on a 2G edge network.

**Comment by shane-tomlinson** [comment]
Hi @potch - as @jedp says, we are working on this. We know we can do better.

The 122KB you are seeing is the uncompressed size. Fortunately, communication_iframe.js is served to the user gzipped, its compressed footprint is ~46KB. On a slow 2G connection with a download speed of 30KB/sec, this represents somewhere between 1.5 and 2 seconds, depending on connection latency.

**Comment by lloyd** [comment]
francois, please close this issue when the work you're doing lands

**Comment by shane-tomlinson** [comment]
Dup of #3060. Closing because that bug has much more discussion.
