### ISSUE TITLE
auto-generate API docs

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2950]
Apparently lloyd's been hiding docstract from us this whole time. Could be cool. 

Example: http://mozilla.github.com/chromeless/

REST API docs (wsapis) are the first priority for our friendly RPs, but documenting internals would be sweet as well.

**Comment by djc** [comment]
I'll try to take a look at this.

**Comment by lloyd** [comment]
I'm unconvinced of the value of wholesale api documentation for the whole source tree.  As far as wsapi documentation, a custom extractor _might_ be a better fit?  Given that this is the unit of thing that we want to document:

https://github.com/mozilla/browserid/tree/dev/lib/wsapi

even though I toiled on docstract, I'm not sure it's a great fit here?

**Comment by djc** [comment]
So maybe just do REST API Sphinx docs?

**Comment by jaredhirsch** [comment]
I'm not familiar with Sphinx.

But the wsapis follow a predictable structure: they export an interface, and the top-level wsapi.js file uses the exported info to filter out requests to undefined endpoints or requests containing undefined parameters.

For example, take a look at the interface exported by wsapi/address_info.js: https://github.com/mozilla/browserid/blob/dev/lib/wsapi/address_info.js#L54-L60

**Comment by jaredhirsch** [comment]
Hmm, maybe that comment wasn't totally clear. We could write a bit of JS to require individual wsapi files, then transform their exported API properties into compact and concise API docs.

Going further, it might be interesting to actually insert the code comments (like [these](https://github.com/mozilla/browserid/blob/dev/lib/wsapi/address_info.js#L15-L25)) into the exported interface. This would let us do 2 cool things: we could automatically add that info to the auto-generated API docs, and we could also potentially add a discovery feature to the wsapis, exporting the API doc info as JSON, so other folks can discover useful API facts by hitting some info-providing endpoint.

But maybe I'm getting a little far afield here.

**Comment by lloyd** [comment]
agreement in bug scrub is that spending time on documenting an internal api that is only useful for a small group of developers, that is already is a pretty scrutable form, is not the best use of our time.

fwiw, hapi has automatic documentation facilities and assessing what it would take to move to hapi may be a better way to get there.
