### ISSUE TITLE
permit resource: and chrome-extension: schemes as audience=

### ISSUE THREAD

**Issue by warner** [mozilla/persona#2956]
For browser addons, which serve control-panel UI content from inside the addon (rather than fetching it from an external website), it would be nice to allow "resource:" and "chrome-extension:" as valid audiences. (currently the code conservatively rejects any audience that isn't "http:" or "https:"). This would allow addon code to use navigator.id from their own content.

The usual security goal is that no web content should be able to get you to accidentally agree to create an assertion for the wrong audience. A page fetched from evil.com should not be able to obtain an assertion for good.com (at least not without postMessaging a cooperative frame sourced from good.com, so the user knows for sure that they're agreeing to a good.com assertion, and good.com can decide for itself who to give it out to).

Assertions created for resource: and chrome-extension: audiences cannot be created by web content, because the browser doesn't look to the outside world when serving these pages. (the pages must avoid incorporating content from the outside world, of course: XSS is just as much a danger for addon pages). An external RP who wishes to accept assertions with addon-based audience= values has no assurance that the actual addon in question provoked its creation, just like they have no assurance that the user didn't manually construct an assertion for their own email address for the audience of their choice without actually talking to that server. But they can be assured that no web content caused the normal browser login flow to create such an assertion.

We might also want to add some native UI for addon modules (instead of popping a normal panel, we could present a UI somewhere that normal web content cannot, to teach users the difference between trusted chrome UI and untrusted content UI). But that's for later.

@psawaya on Gombot is looking at the same issue.

**Comment by lloyd** [comment]
let's bring this general issue of what _our_ verifier should support to dev-identity first before we open a bug?

note: this is important and relevant to FirefoxOS as well, which needs app:// urls

**Comment by warner** [comment]
Based on the dev-identity discussion in https://groups.google.com/forum/?fromgroups=#!topic/mozilla.dev.identity/6OW0BIzWjOs , it looks like we've got consensus to implement this. Reopening. I'll try to come up with a patch.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
