### ISSUE TITLE
Confirm "remove email" and "cancel account" messages are not displayed correctly on Opera

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2958]
Opera 12.12
Ubuntu 12.04
1. have one account with one email
2. open https://login.anosrep.org/ and sign in
3. click on remove email or cancel your account

Actual: The confirmation messages are not displayed correctly (see the screenshot)

![screenshot](https://f.cloud.github.com/assets/1866605/85695/a96e6f94-6473-11e2-8305-e61137adf6b9.jpeg)

**Comment by lloyd** [comment]
this is as designed, at some point in the future we may improve the UI.
