### ISSUE TITLE
IE9 cookie behavior breaks dev.diresworb.org

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#296]
that's right.  because dev.diresworb.org is under diresworb.org, and IE's behavior for cookies is different for other browsers, IE ends up sending TWO cookies of the same name, which causes everything to go to hell (namely, csrf fails first).

Here's the reference: http://blogs.msdn.com/b/ieinternals/archive/2009/08/20/wininet-ie-cookie-internals-faq.aspx

Here's the excerpt:

```
Q3: If I don’t specify a DOMAIN attribute when a cookie, IE sends it to all nested subdomains anyway?

A: Yes, a cookie set on example.com will be sent to sub2.sub1.example.com.

Internet Explorer differs from other browsers in this regard.
```

This is **only** an issue with IE and dev, so it's not ultra high priority.  But boy is it annoying when it hits you.

**Comment by benadida** [comment]
nice catch. So we have to specify a domain in the cookie?

**Comment by lloyd** [comment]
That won't do it: "a cookie set on example.com will be sent to sub2.sub1.example.com"

One thing that would solve the problem would be to vary the name of the cookie for the different servers.  Whether that's the _best_ solution I dunno yet.

**Comment by benadida** [comment]
Sorry I was too terse in my comment. If I'm correctly reading the comment above from blogs.msdn.com, it looks like, if we add a domain parameter to the Set-Cookie header, this behavior will stop. More on domain parameter:

https://tools.ietf.org/html/rfc6265#section-5.2.3
