### ISSUE TITLE
 [marketplace] Persona login is in English when it should be in a different language

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#2964]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=834051, as this is server side.
## Environment :

Gecko  http://hg.mozilla.org/releases/mozilla-b2g18/rev/32f66481e161
Gaia   None
BuildID 20130123070202
Version 18.0
Unagi
## Repro :
1. set device to Pt-Br
2. go to marketplace
3. scroll down to the bottom
4. press the identificar-me button
## Expected :
1. Persona login should be in Portuguese
## Actual :
1. the Persona login is in English

**Comment by ozten** [comment]
Don't mid-air me bro....

I've enabled en and pt-BR on native-persona.org

Steps I took:

1) svn co http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/
2) mv browserid/locale /home/app/code/
3) cd /home/app/code
4) edit /home/app/config.json and add supported languages block
5) mkdir resources/static/i18n
6) ./locale/compile-json.sh locale resources/static/i18n/
7) CONFIG_FILES=/home/app/config.json ./scripts/compress
8) forever restartall

Please let me know if your seeing any issues. You should see pt-BR localization now.

**Comment by nhirata** [comment]
hey ozten, is es enabled as well?  It would be most appreciated if you do that.  :)

**Comment by jrgm** [comment]
@nhirata - no, 'es' is not enabled, but will be simple to add it.

**Comment by jrgm** [comment]
@nhirata actually, can you open a new issue to request 'es' (and any other language that we support, which are listed here https://localize.mozilla.org/projects/browserid/ with the current state of the translation).
