### ISSUE TITLE
support app:// prototocol in validator for FirefoxOS

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#2965]
Apparently gaia apps give their origin as app://foo instead of http://foo.  This does not pass the persona origin validator.

As a result, users will receive a red "There has been an error" message when trying to log in with unverified email and/or forced issuer.  The error message will say something about an invalid origin.

I had never noticed this, because building gaia with DEBUG=1 transforms all the app:// origins to http://, and I always build with DEBUG=1 so I can do testing.  Such is life.

**Comment by jds2501** [comment]
I should note that fixing this is required to use persona in a packaged app. So this is definitely a bad bug.
