### ISSUE TITLE
Why 3 shims? Why not everything in include.js?

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2980]
This came up from prepping for the IdP talk:

Why do we have 3 shims (include.js for RPs, provisioning_api.js and authentication_api.js for IdPs) -- couldn't we just roll all of them into include.js?

And symlink the three together for backwards compatibility?

**Comment by lloyd** [comment]
yeah, why don't we?

**Comment by jaredhirsch** [comment]
Would doing so make the include.js download larger?

We're asking people to block their page on our code downloading and being parsed on the client; from a performance standpoint, I'm -1 on this proposal.

...unless I'm misunderstanding the use case?

**Comment by lloyd** [comment]
I had the same objection, but shane explained to me that the super-set is not significantly larger than any one subset, and the browser caching wins might actually outweigh it, especially when bigtent goes live.

Shane's arguments added a | to my -.

**Comment by jaredhirsch** [comment]
Interesting! Thanks for the explanation.

**Comment by lloyd** [comment]
but that's not to say that we shouldn't get before and after numbers of the gzipped super set as compared to the current 3 individual files.

This is easy to do and rigorously answers the download size concern.

**Comment by callahad** [comment]
This is in the neighborhood of a 460 or 627 byte increase.

> Current: 5386 bytes, from `uglifyjs include.js -c -m | gzip - > current.js.gz`
> 
> Naive Concatenation: 6013 bytes, from `uglifyjs include.js authentication_api.js provisioning_api.js -c -m | gzip - > naive.js.gz`
> 
> However, both `include.js` and `provisioning_api.js` include a copy of jschannel. By removing the copy in `provisioning_api`, the gzipped bundle drops to 5846 bytes, an increase of 460 bytes.

**Comment by jedp** [comment]
There would also be advantages for native if we rolled them all into one.  Specifically, when we expose `navigator.mozId` from chrome, it is an immutable object.  Therefore an IdP must _not_ source `include.js` before sourcing the provisioning or authentication APIs.  If it does, an error will result, because the APIs try to add properties to the `navigator.id` object.  Having everything in one single place would be cleaner and less error-prone.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
