### ISSUE TITLE
translation_directory default in lib/i18n.js

### ISSUE THREAD

**Issue by josendf** [mozilla/persona#2983]
In file lib/i18n.js

Line:
if (! options.translation_directory)  options.i18n_json_dir = 'l10n/';

Should be:
if (! options.translation_directory)  options.translation_directory = 'l10n/';

**Comment by callahad** [comment]
@ozten will be making a pull request this week which will remove / replace this file altogether. Thanks for the report!

**Comment by ozten** [comment]
@josendf Good catch! I also noticed this last week while porting us to [i18n-abide](https://github.com/mozilla/i18n-abide)

**Comment by ozten** [comment]
Proposed fix in https://github.com/mozilla/browserid/pull/3003

**Comment by ozten** [comment]
Thanks again for the report. This is fixed wtih 3003.
