### ISSUE TITLE
The "enable cookies" howto text at persona.org displays raw HTML <a> tag instead of displaying a link

### ISSUE THREAD

**Issue by dholbert** [mozilla/persona#2988]
STR: 
1. Install an addon that rejects cookies by default, e.g. Cookie Whitelist With Buttons:
     https://addons.mozilla.org/en-us/firefox/addon/cookie-whitelist-with-buttons/
(Or, if you rather, you can turn off cookies w/out using any addons by going to Firefox Preferences | Privacy and change "Remember History" to "Use custom settings" and then uncheck "Accept cookies from sites")
1. Visit https://www.persona.org/signin

ACTUAL RESULTS: Link to help page about enabling cookies is displayed as raw HTML, instead of as a link.  The text is:
`Please close this window, <a target='_blank' href='http://support.mozilla.org/kb/Websites%20say%20cookies%20are%20blocked'>enable cookies</a> and try again.`
Screenshot:
http://i.imgur.com/Tj23Xrc.png

EXPECTED RESULTS: Site should show an actual link instead of raw HTML.

**Comment by shane-tomlinson** [comment]
Thanks for the report @dholbert - this is a dup of #2979, closing.
