### ISSUE TITLE
navigator.id.logout() can trigger onlogout multiple times

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2998]
As noticed in #2997, if the user is logged in, calling `navigator.id.logout()` multiple times will trigger the `onlogout` callback every time.

It should only trigger it the first time.

**Comment by arlolra** [comment]
Is this reproducible?

**Comment by tangstad** [comment]
Could not reproduce on current code.

Tried reproducing with example/rp/index.html:
1. start local webserver (python -m SimpleHTTPServer 8000
2. open page in browser: http://localhost:8000/example/rp/index.html
3. click "get an assertion"
4. enter username/password and login
5. click logout
6. click logout again

After 4, verified that login had been logged to the page, and after 5 verified that logout event had been logged to the page. After 6 no new logout event appeared, even though the button non-conditionally calls navigator.id.logout().

Would be nice if someone could confirm if these steps make sense at all.

**Comment by seanmonstar** [comment]
Code that fixed another issue also inadvertently fixed this issue: https://github.com/mozilla/browserid/commit/5d24e404d5676a89463e53aae6ddf9a9622be754

It didn't used to check if `loggedInUser` was null before triggering the logout event. Now it does.
