### ISSUE TITLE
[ios/chrome] dialog fails: action: establishing relay, relay from could not be found. 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3004]
We don't officially support Chrome on iOS, but it's broken (at least on recently updated iOS and Chrome).

STR
1) On iOS, start chrome and go to https://123done.org. Bring up the dialog.

Expected: usable dialog
Actual: action: establishing relay, relay from could not be found.

This is Chrome 23.0.1271.100, on iOS 6.1.1 (iPhone 4s).

**Comment by shane-tomlinson** [comment]
Dup of #1870, #2034 - since Chrome on iOS is a UIWebView, it fits under this category. Closing.
