### ISSUE TITLE
[android4.2.1/stock] Main site, change password doesn't show password input boxes

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3005]
Sorry, I've been burnt out of clicking on mobile.

STR:
1) login to https://login.{persona,anosrep}.org
2) On the accounts page, click on 'edit' for the password.

Expected: two password fields are visible for password entry
Actual: no editable fields are shown; nothing in `adb log` of interest, probably some style/dom thing.

Fails on Android 4.2.1; stock browser 4.2.1-533553

Works on 4.2.1 for current Chrome, FF, FFBeta, FFAurora, FFNightly. 
And on android 2.3.20 (droid2/verizon) for **stock version 2.2***, and  
FF, FFBeta, FFAurora, FFNightly.

**Comment by shane-tomlinson** [comment]
@jrgm - on my Nexus 4 with 4.2.1, I _only_ have Chrome by default, I have no stock browser. How can I go about installing that?

**Comment by jrgm** [comment]
@shane-tomlinson - hmm, my 4.2.1 phone is also a Nexus, but one that I've had for >1 year with several OTA kernel updates. I may just have a legacy stock browser here. I'll ask some folks here in MV about this in (PST) morning if there's a way to get the stock browser installed on your phone.

**Comment by callahad** [comment]
I'll try to reproduce

**Comment by callahad** [comment]
Aaand I am able to reproduce this.

**Comment by callahad** [comment]
For anyone without a device, this is also reproducible in the Android emulator.
