### ISSUE TITLE
siteName is double escaped

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3007]
STR:

1) In the repo, edit example/rp/index.html:186 to be "Persona Test / Relying Party"
2) Load up the dialog

![Screen Shot 2013-02-13 at 16 52 14](https://f.cloud.github.com/assets/848085/153604/eaa7453a-75fd-11e2-8ac2-ddec8306c378.png)

**Comment by jrgm** [comment]
works from me in a local test for train-2013.03.01
