### ISSUE TITLE
kpi stuff is reporting emails - blocker of KPI shipping

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#3008]
example: 

```
  "xhr./wsapi/user_creation_status?email=lloyd%40hilaiel.com",
```

this is no good.  perhaps we should wash away query data.  Any ideas on how we can fix this at a more fundamental level and reduce chances of future data leak?

**Comment by seanmonstar** [comment]
In Playdoh projects, they use a middleware that essentially blacklists certain properties: https://github.com/jsocol/commonware/blob/master/commonware/exceptions/middleware.py

**Comment by ozten** [comment]
Before KPI event stream had complete urls. We have sensative data in the query string parameters.

PR #3012 removes the query string.
