### ISSUE TITLE
"Never used BrowserID?" should be changed into a more appropriate message

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#301]
The "Never used BrowserID?" text leads the user to thinking that the link will open a help page not a Sign up page. Besides this, a user might have used BrowserID for a long time, then canceled his account. In this case, the "Never used BrowserID?" text is not really correct.

Possible replacements could be "Sign up to BrowserID" or "Start using BrowserID".

**Comment by shane-tomlinson** [comment]
This is no longer relevant in the new UI.  Closing.
