### ISSUE TITLE
Longer implementation guide for RPs

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3014]
Our [Quick Setup guide](https://developer.mozilla.org/en-US/docs/Persona/Quick_Setup) is great at getting RPs started and showing that it's not that scary.

We should write the guide that comes next: the detailed implementation guide. Tips and tricks for the problems RPs are likely to run into on real-life sites.

I've collected notes from conversations I had with RPs here: https://id.etherpad.mozilla.org/rp-guidelines

**Comment by callahad** [comment]
@wbamberg can you take a look at this and suggest a way to integrate this into our current docs?

**Comment by wbamberg** [comment]
Sure, I'll take a look at this.

**Comment by wbamberg** [comment]
I've made some updates to the documentation for this.
- I've added a note on IE Compatibility Mode to the [Quick Setup](https://developer.mozilla.org/en-US/docs/Persona/Quick_Setup). This is against my better judgement: keeping the Quick Setup, well, quick, is a good idea, and we do link to the page that explains this problem. But the [feedback on the mailing list](https://groups.google.com/forum/?fromgroups#!topic/mozilla.dev.identity/yDoSCA2JZYo) suggests that people would like this in Quick Setup.
- added stuff about calling logout() to Quick Setup, and updated the samples there to call it.
- added a new page called ["Implementor's Guide"](https://developer.mozilla.org/en-US/docs/Persona/The_implementor_s_guide) - I'm not particularly in love with this title, but I like the idea that it captures real-life issues people have run into, while the Quick Setup describes an idealised and simplified version (for the same reason, I'm also happy to make these notes very concrete, and not worry too much about generalising them). This page just lists links to individual notes on the topics identified by @fmarier above. Some of these are really short and look odd as complete pages, but trust me, my first effort had all of these notes in a single page and it looked horrible. At least with this structure it's easy to grow the guide, to add more stuff and extend the existing entries.

**Comment by fmarier** [comment]
@wbamberg I really like the changes you've made. Thanks!

A few suggestions:
- How about removing the stuff about testing in Step 5 of the Quick Setup and moving it to be a topic in the Implementor's Guide? (It's not as important as security considerations and joining the persona-notices list IMHO.)
- Step 5 of the Quick Setup should link to the Implementor's Guide
- The "supporting users without javascript" topic could link to https://developer.mozilla.org/en-US/docs/Persona/FAQ#Why_does_Persona_require_JavaScript.3F

**Comment by lloyd** [comment]
link to #3083 w.r.t "keeping the quick setup, well, quick"

**Comment by wbamberg** [comment]
@fmarier: thanks, those are good suggestions, and they should be done now. Shall we close this bug?

I might also try to make the FAQ more readable.

@lloyd: thanks for the link.

**Comment by fmarier** [comment]
Since I was the one who opened this bug and I think the new page is great, I'm resolving this bug.
