### ISSUE TITLE
New Persona user

### ISSUE THREAD

**Issue by matbeedotcom** [mozilla/persona#3016]
New Persona account creations don't redirect back to the originating page. It leaves them on the Persona Account Manager page.

My new users are getting extremely confused and are waiting to go back to my page.

**Comment by lloyd** [comment]
diagnosing with matbee in irc:  http://irclog.gr/#show/irc.mozilla.org/identity/209855

it looks like this was due to usage of .get() api rather than .watch() - the former doesn't support post-sign-in redirect.

**Comment by lloyd** [comment]
resolved!  http://irclog.gr/#show/irc.mozilla.org/identity/209901
