### ISSUE TITLE
post-verification redirect not always working

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#3017]
`matbee` in irc reports that post-verification redirect is not working for him all the time, specifically when he closes the popup window before clicking on verification link in email.  I'm opening this as a tracking bug, as I cannot readily reproduce yet.

Anyone know of user behaviors that break redirect?  /cc @shane-tomlinson @seanmonstar

**Comment by matbeedotcom** [comment]
matbee here..

If we nuke the cookies in our browser. Then we create our user on our page. A brand new Persona user who has never accessed it before. Never gets redirected back to US, only to login.persona.org
BUT, if we create a new user without nuking the cookies, and HAVE accessed Persona before, it works fine!

A) Clear _all_ cookies.
B) Create new Persona user.
C) Accept email.
D) Redirects to login.persona.org :)

**Comment by lloyd** [comment]
Aha!  we tracked this down to one remaining `.get()` call.  No bug in persona here.
