### ISSUE TITLE
If logged in with another BrowserID email on a different browser, the user is logged out

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#302]
STR:
1. Open http://beta.myfavoritebeer.org/ in IE and log in.
2. Open http://beta.myfavoritebeer.org/ on Fx and log in to another email from the same BrowserID account or to another account.

Actual Results:
 The user is automatically logged out from http://beta.myfavoritebeer.org/ on IE without any notice. This issue reproduces when switching browsers  or using other browsers (e.g. Chrome). It also reproduces on all OSs.

Expected Results:
 The user should either be announced that he will be logged out from his previous log in, or be allowed to log in this way.

**Comment by lloyd** [comment]
I cannot reproduce with chrome and firefox on osx.  please try to reproduce on current beta and reopen if the situation persists.

**Comment by ghost** [comment]
Verified this issue on the 9/29/2011 Beta using Chrome and Opera too. It doesn't reproduce on them either.
