### ISSUE TITLE
The IdP shim (authentication_api.js and provisioning_api) is not minified

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3020]
The IdP shim is available un-minified here:
- https://login.persona.org/authentication_api.js
- https://login.persona.org/provisioning_api.js

Ideally, it should be minified there and available in source form here:
- https://login.persona.org/authentication_api.orig.js
- https://login.persona.org/provisioning_api.orig.js

**Comment by callahad** [comment]
4-star since this is a high effort-to-reward ratio
