### ISSUE TITLE
Detect against mis-use of navigator.id.request before the watch API

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3023]
As reported in https://bugzilla.mozilla.org/show_bug.cgi?id=842784 is likely that misuse of `request` and `watch` end up changing the behavior of the dialog.

This shouldn't be possible.

If we can, we should just make things work.

If we detect that watch's state isn't setup when we get a call to request, we should log an error to let a developer know.

Basically, we need to validate if this hypothesis for 842784 is accurate and what is the best behavior for users and developer feedback.

**Comment by jrgm** [comment]
no problems noted in stage train-2013.03.01
