### ISSUE TITLE
Russian 'ru' is not loading the 'cyrillic' fonts to which they appear to be mapped

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3029]
I may be reading this wrong, but shouldn't `Accept-Language: ru` be loading fonts from node_modules/connect-fonts-opensans/fonts/cyrillic. This is in the stage environment with train-2013.02.15.

STR
1. Empty the browser cache.
2. Configure the browser to want only Russian (so `Accept-Language: ru` is sent).
3. Use httpfox (or other tool) to log the network requests.
4. Go to beta.123done.org and bring up the dialog (https://login.anosrep.org/sign_in)

Actual:

```
Timestamp    Secs. Sent Recv. Method Res. Content-Type   
00:00:08.209 0.174 339  270     GET  200  text/html               https://login.anosrep.org/sign_in
00:00:08.410 0.133 340  310     GET  200  text/css                https://static.login.anosrep.org/v/a93b0364f0/production/ru/dialog.css
00:00:08.415 0.185 324  310     GET  200  application/javascript  https://static.login.anosrep.org/v/2b3f2940da/production/ru/dialog.js
00:00:08.582 0.962 426  62754   GET  200  application/x-font-woff https://login.anosrep.org/v/ac327c4db6/fonts/default/opensans-regular.woff
00:00:08.587 1.255 424  61279   GET  200  application/x-font-woff https://login.anosrep.org/v/963eb32907/fonts/default/opensans-light.woff
00:00:08.592 1.436 423  61279   GET  200  application/x-font-woff https://login.anosrep.org/v/892667349c/fonts/default/opensans-bold.woff
00:00:09.455 0.280 666  463     GET  200  application/json        https://login.anosrep.org/wsapi/session_context
00:00:10.041 0.065 308  1428    GET  200  image/x-icon            https://login.anosrep.org/favicon.ico
```

Expected:
The `.woff` files are loaded from `cyrillic` not `default` (about 75K more bytes with default).

Either set of woff files, of course, works, but just at a larger network cost.

**Comment by shane-tomlinson** [comment]
This was a problem with connect-fonts that got fixed in shane-tomlinson/connect-fonts@db7501dbbbd0da63867214151913bc2559d37bb5. I am going to issue a PR to update connect-fonts and connect-fonts-opensans to the newest versions.
