### ISSUE TITLE
jenkins builds for health test have fallen down and can't get back up

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3030]
See https://ci.mozilla.org/job/identity.browserid.prod-monitor/

So, seems something in https://github.com/mozilla/browserid/compare/95cbd2c0bc99...b51bbf014efd this morning has now fully coupled the automation-tests to having a full browserid install. (I tried cherry picking modules for a while until it was clear to me that this was unlikely to work).

I changed the build config on Jenkins to `npm install` the full browserid, but that failed because `node` on the Jenkins box is 0.6.15, and we now no longer can build with that version of node (somewhat expected).

I apparently don't have rights to disable the job, but I can change the schedule, so I'll change this to every four hours.

We can look into getting a newer node.js (which we really should have had anyways, in principle), or at whether there's a simple way to de-couple from the need to have the full browserid installed.

**Comment by jrgm** [comment]
Actually, here's a gist to get these de-coupled again (but not sure this is the right thing to do. Comments?)

https://gist.github.com/jrgm/5002316

**Comment by callahad** [comment]
@6a68 you're the testing master, can you look at this?

**Comment by jaredhirsch** [comment]
yeah, I'll have a look. For now, I'll disable the currently-worthless health check until test week next week.

**Comment by jrgm** [comment]
From a chat in IRC with @shane-tomlinson, he pointed out that we will need real version.js someday, but maybe I could stub out lib/logging.js there. I tried that, but then had to stub out lib/secrets.js for weakGenerate, and subsequently lib/configuration.js for config.get('env'). Which would be quite a mess.

So, decoupling automation-tests from having a full browserid/node_modules is not an option, imho.

**Comment by jaredhirsch** [comment]
argh, turns out there's [already](https://bugzilla.mozilla.org/show_bug.cgi?id=845020) an open bug to upgrade Jenkins nodejs to 0.8 with ETA of a couple of weeks.

**Comment by jrgm** [comment]
I updated  [that bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=845020) to note how to get the internal rpm we use in production. /cc @gene1wood

**Comment by gene1wood** [comment]
I've added a link to the nodejs rpm they need

**Comment by jaredhirsch** [comment]
the linked bugzilla bug is closed. @jrgm, this should be resolved. reopen if not.
