### ISSUE TITLE
ReferenceError listed in stdout of frontend tests

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3032]
`WHAT_TESTS=front npm test` passes, but there is this message in stdout.

```
>>> Now Running: Front end unit tests under PhantomJS
· · · · ReferenceError: Can't find variable: BrowserID
```

See https://travis-ci.org/mozilla/browserid/jobs/4935079, or run locally with npm, or loading https://login.dev.anosrep.org/test/ in the browser.

In browser, it's pointing at code_version.js.

**Comment by shane-tomlinson** [comment]
This does not affect the front end tests, but it is an exception so must be fixed.  The root problem is ordering of dependencies.

**Comment by jrgm** [comment]
closed by GH-3039
