### ISSUE TITLE
 "<email> in use, If this email is yours you can sign in with it?" should be changed by a more appropriate message

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#304]
"<email> in use, If this email is yours you can sign in with it?" should look more like this "<email> is already associated to a BrowserID account. If this email is yours, you can sign in with it."

**Comment by shane-tomlinson** [comment]
@ioanab: this is taken care of in the UX redesign.

**Comment by shane-tomlinson** [comment]
6e56e38526ad1740e8094cadee18a4a2446196e5 addresses this in the main page, it was already done in the dialog.
