### ISSUE TITLE
Aw snap! - vista_chrome / remove-email passes but with the sad page showing...

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3048]
See this job https://saucelabs.com/tests/edff8111f2ce4faabd88dc8fd7e55a6d
and video https://saucelabs.com/jobs/edff8111f2ce4faabd88dc8fd7e55a6d/video_edff8111f2ce4faabd88dc8fd7e55a6d.flv

"Aw snap!" appears at 01:37.

**Comment by callahad** [comment]
This can be reproduced, @jrgm to dig more

**Comment by jaredhirsch** [comment]
@AutomatedTester have you seen this, it recurs frequently for us. Maybe a ChromiumDriver issue?

**Comment by jrgm** [comment]
I think this still lurks, but closing this issue, and a new issue can be opened with a more recent STR to be looked into.
