### ISSUE TITLE
Add a Delete button on the "What email address would you like to use ...?" page

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#305]
Adding a Delete button on the "What email address would you like to use ...?" page would improve the user experience. The user can select an email address by clicking on the radio button in its left then press the button to delete it. 

When deleting the last address associated to an account, the user should be announced that he is canceling the whole account.

Currently the user has to load the server page just to press a button and delete an email address associated to a BrowserID account.

**Comment by shane-tomlinson** [comment]
I personally feel this may clutter up the interface, but defer to the UX/UI team to see if they can make it work.

**Comment by lloyd** [comment]
I agree with @shane-tomlinson that this could clutter.  I also agree with @ioanab that users will not discover nor frequently use the browserid server pages. Creating a new label for this issue 'needs UX input'

**Comment by skinny97214** [comment]
as designed
