### ISSUE TITLE
Wrongly escaped string in the "you must enable cookies" screen

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3050]
The link to SUMO is escaped and raw HTML is displayed when cookies are disabled:

![doubly_escaped_cookie_error](https://f.cloud.github.com/assets/167821/195035/351abe30-7fd1-11e2-90e2-62e701c9bd07.png)

**Comment by jrgm** [comment]
Duplicate of GH-2979. Closing as dup.
