### ISSUE TITLE
Yahoo! email address is not pre-filled in when redirecting from BigTent and not authenticated at Yahoo!

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3057]
Using BitTent, I have to type my Yahoo! email address twice if I am not logged in at Yahoo! - first in Persona, next on Yahoo!

STR
1) Visit Yahoo! Sign out.
2) Visit beta.123done.org
3) Open Persona dialog
4) Enter Yahoo! address.
5) Click "Next" on redirection screen.
6) I'm asked for my email address again.

![Screen Shot 2013-02-27 at 10 46 14](https://f.cloud.github.com/assets/848085/200515/0aa6d1ca-80cb-11e2-98f5-35d4bd4b0a30.png)

**Comment by callahad** [comment]
Closing in favor of the duplicate in the browserid-bigtent repo.

**Comment by jaredhirsch** [comment]
what callahad said
