### ISSUE TITLE
Logging in using Yahoo! BigTent is difficult, especially with 2 factor auth.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3058]
Duplicate of mozilla/browserid-bigtent#126

Is there a mobile version of their authentication page for OpenID? There is a mobile login page: https://mlogin.yahoo.com/

**Comment by callahad** [comment]
Closing in favor of the dupe in the bigtent repo.

**Comment by jaredhirsch** [comment]
what callahad said
