### ISSUE TITLE
The Confirm Your Email dialog is opened when trying to add an invalid email address to BrowserID

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#306]
STR:
1. Open http://beta.myfavoritebeer.org/.
2. Click on the Sign in button.
3. Click on the "Never used BrowserID?" link.
4. Enter an invalid email address that contains one '@' and a password.
5. Click on the Continue button.

Actual Results:
The Confirm Your Email "Waiting for email confirmation... " dialog is opened and it keeps waiting until the user manually closes it.

This issue also reproduces when trying to add a secondary email address to your BrowserID account.

Expected Results:
An error message letting the user know that he needs to enter a valid email address is displayed.

Reproducible on all OSs and browsers.

**Comment by shane-tomlinson** [comment]
This is a duplicate #263, closing.
