### ISSUE TITLE
internal_api should not require callbacks to have curry() method on prototype

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3067]
Some `internal_api` methods expect callers to have a `curry()` method on the `Function` prototype.  This is problematic when integrating with native platform code like FirefoxOS or a desktop browser.  Since curry is (unfortunately) not part of the JavaScript standard function prototype, we should not make this assumption.

Other methods in `internal_api` define an internal `complete()` function; we can follow that pattern in `logout` and `logoutEverywhere`.

**Comment by shane-tomlinson** [comment]
@jedp - Function.prototype.bind is defined here: https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/javascript-extensions.js#L32, which should be included in the internal API, no?

**Comment by jedp** [comment]
@shane-tomlinson curry() is in the internal_api by dint of the Function prototype extension; the problem arises when you try to call the internal_api from, say, native code on firefox.  If your callback in firefox doesn't have a curry method on the function, then persona doesn't like it.

But I think the solution is clear - elsewhere in internal_api, we have a complete method; we can just do the same thing for logout and logoutEverywhere.  I'm testing it now to see if it works.

**Comment by jedp** [comment]
submitted PR #3069

**Comment by shane-tomlinson** [comment]
@jedp - thanks for the explanation, I understand after looking at the code. Since the callback comes from native code, it won't have curry. Your solution makes sense, though you could use helpers.complete instead of redefining complete in two places.

**Comment by shane-tomlinson** [comment]
The PR for this was merged, closing.
