### ISSUE TITLE
Incomplete transition for reset password when a stale staged row for the user exists

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3068]
1. Set up an awsbox on train-2013.02.15.
2. Create a secondary user on the awsbox, then signout and stage a password reset (where in this train, you will be prompted to enter the password first, twice). Close the /sign_in dialog. (This is the case where the user staged the reset but e.g., then remembered their password and left a record in the staged table with a pending password).
3. Force push the version of the awsbox to train-2013.03.01.
4. Bring up the dialog and stage another password reset for that user. (In 03.01, the email is sent without prompting for password). [In the staged table, I see that the secret and ts columns have new values and the passwd column is NULL).
5. Collect the latter reset email and load in a new window/tab of the browser, leaving the dialog up and polling.
6. In the reset_password page, you are now prompted to enter a new password twice. Do that and click Finish.

Expected: The reset_password transitions to show the return_to url and the dialog completes auth and closes.

Actual: the reset_password page does transition, but the dialog stays up with a disabled username field containing your email address, and a 'verify email' button. Clicking the verify email button does nothing, although looks like the very bottom of a tooltip flashes at the very top of the dialog. I don't see any errors in the JS console.

If I close the dialog and then launch it again from the RP, the dialog now shows as authenticated and can be used to sign in with the RP.

**Comment by lloyd** [comment]
resulting in crappy ux for a small %age of users, and the problem is specific to 03.01 deployment, we're choosing to suffer this marginal pain.
