### ISSUE TITLE
When confirming an email from a second browser, the server page is opened with no account information

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#307]
STR:
1. Open http://beta.myfavoritebeer.org/ in a browser.
2. Create a new BrowserID account.
3. Confirm the used email address from another browser.

Actual Results:
 https://www.diresworb.org/ is opened in the second browser but it contains no account information.

Expected Results:
 Either the account information should be displayed on  https://www.diresworb.org/, or just display a "email address confirmed" message.

**Comment by lloyd** [comment]
this situation is improved in dev, and no further work will be done on the current UI (new UI to land in < 2 weeks).

issue #290 and issue #336 discuss variations of this issue that are still pertinent.
