### ISSUE TITLE
[password reset] When using two different browsers, the flow winds up with the dialog prompting for password

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3070]
Not a bug per se. See below for comments.

STR
1. Use two different browsers, browser1 and browser2, and have already created a secondary email address to use below.
2. In browser1, go to beta.123done.org or beta.myfavoritebeer.org and bring up the dialog. If auth'd click 'this is not me'. Enter the secondary email address and when prompted for the password, click 'forgot password'. In this train, an email is immediately sent out with a link to `reset_password`.
3. Load the `reset_password` link in browser2. You will asked to choose a password (twice). Fill it in and submit. browser2 then completes the process and redirects to load the main site page.
4. However, back in browser1, the dialog remains up and transitions to show the email address and a prompt for a password. Enter the same password as in browser2, and the dialog completes auth and closes. You are now logged into beta.123done.org.

The previous behaviour seemed a bit smoother (the challenge to prove you know the password was in a full window of browser2, and then the dialog would automagically auth and close).

This is not be a bug per se, but filing to note the behaviour and ask if it meets expectations, or can be finessed in some way. (And of course, I'm not asking to revisit the whole topic again and go back to the previous way ;-)).

**Comment by lloyd** [comment]
@shane-tomlinson any ideas on whether we could improve this?

**Comment by shane-tomlinson** [comment]
I'm not aware of a way to get around this without introducing a major security hole.

A bad person could initiate a password reset, leave the dialog open, and wait for the target user to open the verification link in browser2. Unless the bad person in browser1 is forced to enter the same password as the target in browser2, bad person gains access to the account just by having a bit of patience.

**Comment by jrgm** [comment]
So given @shane-tomlinson's comment, closing this issue.
