### ISSUE TITLE
End-user troubleshooting tool

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3073]
I'm currently trying to reproduce [a problem affecting an end-user](https://groups.google.com/d/topic/mozilla.dev.identity/yDoSCA2JZYo/discussion) and having no luck. The user is getting the "cannot establish relay frame" error but it works fine for me on the exact same version of IE with the same security/privacy settings.

So here's a tool that would be handy to have. A webpage hosted by us that would test the user's browser and provide a bunch of green ticks for meeting the requirements and display a red X next to the requirements that aren't satisfied if any.

The tests would include:
1. is Javascript enabled?
2. is your browser supported? (display the user agent we see)
3. are third-party cookies enabled?
4. can the test page load `include.js`?
5. can the test page load resources from `static.login.persona.org`?
6. can we create open an iframe to the `login.persona.org` domain?
7. ...

(A browser needs to get a perfect score to pass.)

This page would be the first place we send end-users to when they have a problem with Persona and want support from us. It could also be useful to SUMO.

**Comment by jrgm** [comment]
Nice idea. (One other thought in the interim, and the user may not be willing to do this, and login.dev.anosrep.org may not always be available, but you could ask them to load https://login.dev.anosrep.org/test/ and see what that says).

**Comment by fmarier** [comment]
@jrgm Good idea. I've emailed the user with instructions on how to run this.

**Comment by fmarier** [comment]
@jrgm all tests pass in the cursed IE9 browser:

![ie9_qunit](https://f.cloud.github.com/assets/167821/224932/75f6952e-85e3-11e2-8827-16d2a657ff7e.png)

**Comment by jaredhirsch** [comment]
@fmarier seriously, this is a brilliant idea--a self-serve page for debugging problems with a third-party snippet.

We should do this as a separate, no-dependencies github project, because every third-party provider would want to fork that hotness.

**Comment by jaredhirsch** [comment]
@fmarier honestly, we could just use modernizr checks for the "is your browser modern enough" questions (localstorage, postmessage). if JS is disabled, just tell them via text inside noscript tags. we'd still need a page on our site for the third-party cookie check and to ensure that iframes can communicate ok.

**Comment by fmarier** [comment]
@6a68 I agree that many of these checks could be done directly inside the dialog, but I'm thinking of a page that would run lots of (potentially slow) tests to detect weird environmental problems. Random example: maybe there's a corporate proxy or plugin that finds a porny substring in one of our URLs and blocks it.

**Comment by lloyd** [comment]
yeah, this is an awesome idea.

One thing we did that was pretty successful in browserplus - we had a landing page that end users could go to and type in a problem report.  We combined these problem reports with anonymous diagnostic information, and had a system to track number of reports.

When we normalized for usage and did content analysis, we had another KPI.

@fmarier's idea could be the "automatically" determined components of such a system.

First baby step is to stand up such a site and allow it to export the results to JSON.  We can then immediately begin using it for live debugging with end users.  "run this, export to text or json, and append the results to this github issue"  Perhaps we enumerate the top five tests we'd like to run and go?

Next step would be to integrate this into our main site and have it be linked from the dialog - "Persona not working for you?"

This link could appear in various places where we know the user is having problems - like in the error screen in the dialog.

the KPI system could be reused in the short term and I think we could get there rather quickly.

@fmarier :beers:

**Comment by lloyd** [comment]
fantastic freaky friday project.  who wants it?

**Comment by jaredhirsch** [comment]
@fmarier I meant just stand up a testing page with modernizr doing some browser checks, etc.

we could have a rainbow that goes across the screen as a progress meter while you're doing the checks. goes full double rainbow if everything works?

**Comment by fmarier** [comment]
@6a68 ah I see now. Sounds like a good plan. Huge +1 on the double rainbow ;)

**Comment by lloyd** [comment]
:rainbow: :rainbow:

**Comment by fmarier** [comment]
I started working on this in https://github.com/fmarier/persona-troubleshoot

**Comment by fmarier** [comment]
Well the tool exists. It's not finished (and probably never will), but patches welcome ;)
