### ISSUE TITLE
Easy-to-make user error results in dead page

### ISSUE THREAD

**Issue by karlht** [mozilla/persona#3075]
Flow looks like this:
1. I (Karl) make an attempt to sign in as Ed, giving his email address, clicking 'forget password' and assigning him a password '123456.'  
2. Ed gets a confirmation email and clicks it absent-mindedly.  
3. He is asked to confirm the new password, but whatever he types (unless it happens to match what I previously set) will get him out of the dialogue, and there are no error messages like 'This does not match the new password you gave when you generated this email.'   In fact, there are no error messages at all, giving the appearance of a dead page.

This does not impact Ed's ability to log in; his actual password has not changed.  But it is certainly potentially confusing.

**Comment by jrgm** [comment]
@karlht is this fixed on stage where the password reset flow has changed? I think it is fixed in this train.

**Comment by karlht** [comment]
@jrgm Yes, this is fixed on stage.  Closing #3075.
