### ISSUE TITLE
"Please choose an email address" UX is odd when I only have one address

### ISSUE THREAD

**Issue by keturn** [mozilla/persona#3076]
I've done this thing repeatedly now, when I go to log in to a site with Persona, the login window pops up, everything looks fine, I hit the "sign in" button, and I get this unhappy red message saying "Please choose an email address."

![persona-choose-one](https://f.cloud.github.com/assets/83819/223934/8d994734-85c6-11e2-9476-1d652912c76f.png)

Choose what? There's only one address presented.  There is not any indication to me that it is _not_ selected already, no checkbox to check or radio button to punch.  The only thing that is obviously an enabled control on the page is the bold blue "sign in" button, directly below my email address, which the button I already hit.

Now it turns out if I click on my email address, even though that doesn't seem to make _any **visible**_ change, and _then_ click the bold blue button, then it works.

Chrome 26 on Linux, and as you can see on the screenshot, I have lastpass, which might be relevant somehow.  (I admit I have not tried this on a clean browser profile.)

**Comment by callahad** [comment]
:(

Does this happen if you temporarily disable your add-ons?

**Comment by callahad** [comment]
I can't reproduce this on Firefox or Chrome with LastPass.

**Comment by lloyd** [comment]
@jrgm or @jbonacci - mind giving this a look and one more attempt to reproduce?

**Comment by jrgm** [comment]
I tried with Google Chrome Version 26.0.1410.28 beta on Ubuntu 12.10 with Lastpass installed in Chrome, and cannot reproduce.

**Comment by keturn** [comment]
okay, turns out I can't reproduce this anymore either.

**Comment by jrgm** [comment]
Thanks @keturn. I'm not sure what to think as that looks like a real bug to me. But if we don't have a way to reproduce at the moment, then sure close. If you see this again, please reopen.
