### ISSUE TITLE
navigator.id.watch() does not trigger onlogin() for forced issuers

### ISSUE THREAD

**Issue by kumar303** [mozilla/persona#3089]
This is what I am expecting to work:

Let a user log in with:

```
navigator.id.request({
  allowUnverified: true,
  forceIssuer: "b2g2pac.personatest.org"
});
```

On the next visit to the site, automatically log them back in with:

```
navigator.id.watch({
  onlogin: function(assertion) {
    // if assertion is valid on the server, auto-login here.
  },
  onlogout: function() {...}
});
```

But in this scenario, onlogin() is never called. The user is not automatically logged in when I force an issuer.

If I stop forcing an issuer, onlogin() does an auto-login every time as I expect. That is, starting the login flow like this works as expected:

```
navigator.id.request({
  allowUnverified: true,
  forceIssuer: ""
});
```

Is this something that can be easily fixed for the Firefox OS launch? Otherwise, let us know and we can check our session cookie (which will tell us if they are logged in). We do need to force issuers for Firefox OS because we are dealing with unverified emails.

FYI this is only on B2G using this shim: `<script src="https://native-persona.org/include.js"></script>`

**Comment by lloyd** [comment]
@jedp - do you have this under control?  do you need help?

**Comment by kumar303** [comment]
We currently disabled forcing issuers (I think that is bad) and we're tracking it here https://bugzilla.mozilla.org/show_bug.cgi?id=850084 as a reminder to re-enable it

**Comment by jedp** [comment]
@lloyd, @kumar303 I should be able to fix this, but I'm a little backed up on other b2g things.  If anyone wants to jump in, that would be awesome.  Otherwise I ought to be able to work on it in the next few days.

**Comment by jedp** [comment]
Met with @benadida, @shane-tomlinson, @kumar303, and @skinny97214 this morning to talk through this.  We're planning to change nothing about the observer API (e.g., not require any new parameters in `watch`).  We've jotted some notes about forced-issuer in [this etherpad](https://etherpad.mozilla.org/forced-issuer)

**Comment by shane-tomlinson** [comment]
The fix for this pushed to the "b2g-picl-merge" branch, though @kumar303, .watch may be acting differently than you expect. I added some tests that should (hopefully) give some insight into how the .watch API acts: https://github.com/mozilla/browserid/blob/b2g-picl-merge/resources/static/test/cases/dialog/js/misc/internal_api.js#L242-L321

**Comment by jedp** [comment]
@shane-tomlinson awesome.  @kumar303 i think we'll be in a good position to re-deploy b2g next week (it's been a busy week).  So this should be live soon.

**Comment by kumar303** [comment]
Interesting, thanks. We aren't using loggedInUser yet (it's in our session after the first login so we could use it). I'll wait for the merge and try it out!

**Comment by jedp** [comment]
Since https://bugzilla.mozilla.org/show_bug.cgi?id=850084 is resolved=fixed, I'm going to close this.

@kumar303 will you re-open if there are further problems?
thanks
