### ISSUE TITLE
Unable to login via bigtent when there is an existing session/cookie from a different yahoo properties

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3090]
description: Unable to login with user@yahoo.com acct when a user@ymail.com cookie exists

steps:
1. clear all previous users in persona
2. goto http://beta.123done.org/ and click sign in
3. login using a user@ymail.com acct - follow the dialog till logged in
4. on http://beta.123done.org/ click logout
5. on http://beta.123done.org/  click sign in
6.  enter a user@yahoo.com acct

result:
Authentication Error
Sorry, it looks like you were trying to log in as user@yahoo.com, but were logged in to Yahoo as a different address.
Please visit Yahoo and ensure that you are logged in as user@yahoo.com.

expected:
You should be able to login. I should be able to have ymail and yahoo emails that should not collide in authenticating.

**Comment by callahad** [comment]
How does Yahoo handle `@yahoo.com` vs. `@ymail.com`, are they handled separately, or are they aliases for each other? (That is to say, can `foo@yahoo.com` be a different person from `foo@ymail.com`?)

**Comment by edwindotcom** [comment]
moving to mozilla/browserid-bigtent
