### ISSUE TITLE
Configure stage to point at kpiggybank-stage for kpi metrics

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3092]
This issue captures setting up stage to be able to POST to kpiggybank-stage, without setting the sample rate. This enables load testing without acutally turning on the kpi metrics.
- Configure the proxy to allow POSTS to https://kpiggybank-stage.personatest.org
- Set KPI target URL: https://github.com/mozilla/browserid/blob/dev/lib/configuration.js#L157

@gene1wood's earlier comment about the proxy (though we're using the personatest.org domain instead of the hacksign.in domain):
https://github.com/mozilla/browserid/issues/2831#issuecomment-11139764

cc: @jrgm, @karlht 

Moved out of #2831

**Comment by gene1wood** [comment]
Here's the updated patch based on the new domain name :

```
Index: templates/idproxy-stage.conf
===================================================================
--- templates/idproxy-stage.conf    (revision 57704)
+++ templates/idproxy-stage.conf    (working copy)
@@ -37,6 +37,11 @@
 acl bigtent_microsoft1 url_regex ^https://oauth.live.com/token$
 acl bigtent_microsoft2 url_regex ^https://apis.live.net/v5.0/me?access_token=.*$

+# KPIggyBank connections
+acl kpipath url_regex ^/wsapi/interaction_data$
+# to_dev_kpiggybank is the IP address of kpiggybank-stage.personatest.org
+acl to_dev_kpiggybank 50.19.201.169/32
+
 # Allow verifier requests over SSL.
 http_access allow bidcert ssl get

@@ -51,6 +56,9 @@
 http_access allow bigtent_microsoft1 post
 http_access allow bigtent_microsoft2 get

+# Allow KPIggyBank calls
+http_access allow to_dev_kpiggybank kpipath post
+
 # Reject any requests to internal networks.
 http_access deny to_localnet
 http_access deny to_localhost
```

**Comment by gene1wood** [comment]
I'm assuming for stage the KPI target URL is :

https://kpiggybank-stage.personatest.org/wsapi/interaction_data

**Comment by gene1wood** [comment]
Squid config in staging was updated at sysadmins r60893 and r60894 and deployed

**Comment by gene1wood** [comment]
And here's my patch for enabling kpi on browserid in stage :

```
Index: webhead.json.stage
===================================================================
--- webhead.json.stage  (revision 59756)
+++ webhead.json.stage  (working copy)
@@ -10,5 +10,6 @@
   "http_proxy": {
     "host": "idproxy.idweb.scl2.stage.svc.mozilla.com",
     "port": 8888
-  }
+  },
+  "kpi_backend_db_url": "https://kpiggybank-stage.personatest.org/wsapi/interaction_data"
 }
```

**Comment by gene1wood** [comment]
Deployed to stage and services restarted

**Comment by jrgm** [comment]
Closing, but we still have an issue with the squid proxy.

**Comment by gene1wood** [comment]
Fixing a bug in the regex

```
Index: templates/idproxy-stage.conf
===================================================================
--- templates/idproxy-stage.conf    (revision 60894)
+++ templates/idproxy-stage.conf    (working copy)
@@ -38,7 +38,8 @@
 acl bigtent_microsoft2 url_regex ^https://apis.live.net/v5.0/me?access_token=.*$

 # KPIggyBank connections
-acl kpipath url_regex ^/wsapi/interaction_data$
+acl kpipath url_regex ^https://kpiggybank-stage.personatest.org/wsapi/interaction_data$
+
 # to_dev_kpiggybank is the IP address of kpiggybank-stage.personatest.org
 acl to_dev_kpiggybank dst 50.19.201.169/32
```

**Comment by jrgm** [comment]
So in the midst of a massive day in IRC, I noted that I had run load_gen against stage for a bit, and was no longer seeing squid errors in pencil, and @kparlante confirmed that " yup, the count's going up, excellent". So this is good. `next()`.
