### ISSUE TITLE
Turn on sample rate for kpi metrics

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3093]
Depends on #3092 (configure proxy and set kpi_backend_db_url)

When @jrgm is ready, set kpi_backend_sample_rate on stage to be non-zero:
https://github.com/mozilla/browserid/blob/dev/lib/configuration.js#L152

We were planning on a rate of 0.1 in production.

Moved out of #2831

**Comment by lloyd** [comment]
waiting for goahead from @jrgm

**Comment by jrgm** [comment]
@gene1wood you can set it 0.2 for the stage environment (upped a little bit to get a little more activity in stage).

That's ' kpi_backend_sample_rate: 0.2' in production.json

**Comment by gene1wood** [comment]
Talked to @jrgm in irc and found this config change goes only on the webheads

**Comment by jrgm** [comment]
Yes, correct. (Should have updated here too).

**Comment by gene1wood** [comment]
Here's the change

```
Index: webhead.json.stage
===================================================================
--- webhead.json.stage  (revision 61083)
+++ webhead.json.stage  (working copy)
@@ -1,5 +1,5 @@
 {
-  "kpi_backend_sample_rate": 0.0,
+  "kpi_backend_sample_rate": 0.2,

   "database": {
     "host": "slaves.iddb.scl2.stage.svc.mozilla.com",
```

This has been deployed to stage

**Comment by jrgm** [comment]
gene: thank you. I can see that in session_content, and a ~proportional number of posts to interaction_data.
