### ISSUE TITLE
Cancelling out of dialog when on login.yahoo.com leaves signin button disabled

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3098]
Originally filed by @jrgm at mozilla/browserid-bigtent/issues/139

STR
1. Be signed out of Yahoo.
2. Go to either beta.123done.org or beta.myfavoritebeer.org and click the signin button.
3. Enter an @yahoo.com email address
4. The dialog transitions to now show the page from https://login.yahoo.com/config/login?...etc... with a prompt for Yahoo name and password.
5. Close the dialog.

Expected: the signin button is re-enabled when the dialog is closed.
Actual: the signin button stays disabled and the RP page must be reloaded.

This STR works with either FF19 or Chrome 25, for either the get or watch API.

**Comment by ozten** [comment]
I can reproduce this on Aurora as well as Firefox 20 both on Mac 10.7.5.

I think this would be an issue with how the RP is written. This problem doesn't happen with the browserid example RP page.

Hmm, beta.123done does use `oncancel`, but this isn't called for primaries when the dialog is closed.

**Comment by shane-tomlinson** [comment]
This is a dup of another bug which I cannot find right now. Searching.

**Comment by shane-tomlinson** [comment]
Dup of #1773, @ozten, do you want to close one of these two?

**Comment by ozten** [comment]
Thanks @shane-tomlinson!
