### ISSUE TITLE
(bigtent relevant) [ie8] signin with foo@yahoo.com; main site shows error if you don't complete the popup window in ~10 seconds.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3120]
STR

Use an absolutely clean profile (with IE, Safety->Delete Browsing History', check all the boxes; when that is done, quit the browser and start it again).
1. Go to login.anosrep.org and click 'Sign in'
2. Enter somerandomusername@yahoo.com, click Next, then click Verify. 
3. The dialog comes up and switches to Yahoo signin form.
4. Touch nothing else and just wait for 10 to 20 seconds.

Expected: nothing happens in either window
Actual: with IE8, the main window transitions to show an error screen, with details 'Action: Checking Address Info'

Notes:
1. I cannot reproduce this with IE9/win7 or FF19/osx.
2. This isn't specific to Bigtent, since I can do this with eyedee.me. [1]

Seems like some sort of uncancelled timer. I do not see anything in the devtools console on ie8 though.

[1] eyedee.me has other issues on IE8 which I've been remiss on not raising the priority.
See: https://github.com/mozilla/browserid/issues/2239#issuecomment-7626513

**Comment by ozten** [comment]
> FYI - I get an error if I try to open https://login.anosrep.org/sign_in directly.
> I assume this is expected.

Yes, this is expected. Users shouldn't go there manually.

**Comment by shane-tomlinson** [comment]
We took the /signin page out, I just tested on login.dev.anosrep.org and see an error in the dialog, not the main site. Opened #3293 with the STRs.

Closing this one because we took the /signin page out, it has been replaced with the dialog everywhere.
