### ISSUE TITLE
Footer text wraps on to two lines in certain languages.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3129]
As reported by a list member:

FF - German: http://f.666kb.com/i/cck4ck1idf6b6kp3q.jpg (broken design)
FF - Russian: http://f.666kb.com/i/cck4dbtk85yd77tw6.jpg (broken design)
FF - Spanish: http://f.666kb.com/i/cck4dpjhxmjkl9sly.jpg (broken design)
IE - German: http://f.666kb.com/i/cck4e5p4ftzqz27me.jpg (broken design)
Chrome - German: http://f.666kb.com/i/cck4elrl9chkxbb4m.jpg (broken design)

**Comment by jaredhirsch** [comment]
One fix for this is to dynamically calculate the width of the footer text, then resize it down until it is less than the width of the popup. I might spend a couple minutes and try to just squash this.

I went ahead and copied the images to github so we won't lose them:

FF - German:

![image](https://f.cloud.github.com/assets/96396/306502/ebb9fc3c-9683-11e2-8a15-ac97165bb55e.png)

FF - Russian:

![image](https://f.cloud.github.com/assets/96396/306505/f2b3237e-9683-11e2-8779-422137d4b156.png)

FF - Spanish:

![image](https://f.cloud.github.com/assets/96396/306506/fba2b030-9683-11e2-96bf-03e672d0eee6.png)

IE - German:

![image](https://f.cloud.github.com/assets/96396/306507/06747f34-9684-11e2-9e80-48618b316b2b.png)

Chrome - German:

![image](https://f.cloud.github.com/assets/96396/306508/0d50486a-9684-11e2-81d4-86226f21ab98.png)
