### ISSUE TITLE
transitive identity from site to site / pre-auth

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#313]
added here for tracking purposes:

https://groups.google.com/group/mozilla.dev.identity/browse_thread/thread/127bb0f86a2321e/f1192a4ac7180f1c

**Comment by shane-tomlinson** [comment]
@benadida, @lloyd - Is this still under consideration or can it be closed until we actually get to this?

**Comment by ozten** [comment]
Not sure what the best way to get community involvement is, but this is ripe for some experiments.

Since we don't have a good "Get Involved" integration with github issues, I'd say close it.

**Comment by lloyd** [comment]
this feature was motivated by an internal mozilla initiative, not by the community, and there was significant discomfort around it.  It seems like we've solve the problem a different way, so the internal impetus to look at this is gone.

+1 to closing (and I am!)

**Comment by ozten** [comment]
Ah, Sorry my comments are for "SSO experiments", which I thought might solve this. I probably misread.
