### ISSUE TITLE
sign in button isn't very responsive on android browsers

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3133]
Initially i was going to log this on 123done 's repo, but i noticed it with Voo.st also.  The facebook button doesn't exhibit the same issue on Voo.st
1. on android FF (stable and beta) or stock browser
2. goto: 123done.org or voo.st 
3. click on the persona sign in button

result: i often have to press on the screen 2-3 times to get it to pop the new window.

not sure if how we recommend embedding, interaction with pop up blockers coming from abosolute URLs?

**Comment by jaredhirsch** [comment]
if this is a race condition, where users are clicking before click handlers are listening, this is another argument for an async queue that's registered in the header, in the style of the google analytics async snippet's `gaq`.

**Comment by callahad** [comment]
123done only displays the button after `onmatch` fires, so this isn't a race condition.

**Comment by edwindotcom** [comment]
I can't repro this anymore. closing
