### ISSUE TITLE
[B2G][l10n][Spanish] The Persona login page on a Spanish phone is shown in English

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#3139]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=855022.

Description:
A user with their device language set to Spanish will see the Persona login page for the marketplace rendered in English.

Repro Steps:
1) Updated to Unagi Build ID: 20130326070208
2) Select Settings, then Language, then change the language to Spanish.
3) Restart the device and select the Marketplace app once the restart finishes.
4) Tap the gear icon in the upper-right corner, then tap the Iniciar sesion / Registrarte button.
5) Observe the appearance of the Persona page.

Actual:
The Persona page is rendered in English.

Expected:
The Persona page is rendered in Spanish.

Environmental  Variables:
Kernel Date: Dec 5
Gecko: http://hg.mozilla.org/releases/mozilla-b2g18_v1_0_1/rev/4931ec89ebbe
Gaia: 5c3583a7a58f0c47da0e48b90273fa36cc508b0b

Notes:
Repro frequency: 100%
Q Analysts Test Team Priority: Pri 3
See attached screenshot for more info.

**Comment by jaredhirsch** [comment]
@jds2501 do you happen to have the request headers? I'm curious what the Accept-Language header looks like.

the screenshot didn't get copied over from the original bug. here it is:

![image](https://f.cloud.github.com/assets/96396/306487/19601596-9683-11e2-984c-c1e917bf6be2.png)

**Comment by jrgm** [comment]
I think it's just that the server (native-persona.org?) is not configured to support 'es'.

**Comment by jds2501** [comment]
@jrgm FWIW, I think we had a similar bug like this with a different locale in the past. Can't remember which locale.

I can work with jrgm to dig up the headers tomorrow if need be though.

**Comment by jrgm** [comment]
The other language was probably pt-BR. But rather than doing these one by one, is there a document on what languages are required? Only two are configured at the moment (if I was on the right (temporary) server).

**Comment by jds2501** [comment]
@autonome or @akeybl probably would know the formal language list we need 1.01 and 1.1 respectively (it was mentioned in 1.1 triage). I agree that we might as well get the list here and add support for the missing languages.

**Comment by jrgm** [comment]
I should note that while 2 are configured on that server, we have 30+ locales available that are currently live on login.persona.org. All credit for that to the verbatim community.

**Comment by shane-tomlinson** [comment]
@mathjazz - Hey, for B2G, we are going to have a few new languages that are being asked for. What do we need to do to start the process to find community members that can help us out with this?

**Comment by shane-tomlinson** [comment]
@jedp - Are you the one handling the B2G server? Can we start to get some of the requested languages that we already have translated turned on so that we can begin testing.

**Comment by mathjazz** [comment]
@shane-tomlinson You need to talk to me. :-) What new locales do we need? The ones that also need to translate Gaia?

**Comment by jedp** [comment]
@shane-tomlinson @mathjazz it looks like the b2g server has `supported_languages` = en, pt-BR, it-CH.  So yes, we ought to add spanish :)  I can try to follow @ozten's docs about l10n.  I need to learn how to do this for browserid, especially these ephemeral awsbox deployments.

**Comment by shane-tomlinson** [comment]
@mathjazz - Those are the ones, @jrgm has a list of locales that need to be done, he has more context.

@jedp - it should be pretty straight forward to enable locales, the docs are pretty good and the install scripts on ephemeral boxes do the hard work of downloading the svn repo and generating the appropriate JSON files. I can help out if you need some pointers.

**Comment by mathjazz** [comment]
@jedp Spanish is already translated, so I guess we only need to add it to the list of supported languages on the b2g server. We have 50 localization teams working on Persona, and usually we have ~30 locales at 100%: https://localize.mozilla.org/projects/browserid/

@shane-tomlinson "The v1.0.1 branch targets Czech, German, Croatian, Hungarian, Polish, Portuguese (Brazil), Romanian and Spanish." See: https://groups.google.com/forum/?fromgroups=#!topic/mozilla.dev.l10n/zwpP8Wa_KvA. We have these locales in Verbatim, but Hungarian and especially Romanian are not complete ATM. Should I get in touch with localizers?

**Comment by shane-tomlinson** [comment]
@jedp - are there new strings in the b2g branch that are not in the main branch? 

@mathjazz - Thanks for looking into this, let me find out the priority of Hungarian and Romanian. If there are new strings in the B2G branch, is it alright to have these localized as we start merging features back into the main branch, or is it preferable to get a list of new strings ahead of time?

**Comment by jedp** [comment]
@shane-tomlinson, @mathjazz there is a handful of new strings.  They are in this gist: https://gist.github.com/jedp/5506266

/cc @ozten

**Comment by ozten** [comment]
This is fixed.
