### ISSUE TITLE
Saved passwords are not automatically filled in when logging in with BrowserID on Firefox 6

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#314]
OS: Windows 7 32-bit
Browser: Firefox 6.0 (Mozilla/5.0 (Windows NT 6.1; rv:6.0) Gecko/20100101 Firefox/6.0)

STR:
1. Open http://beta.myfavoritebeer.org/ in Fx6.
2. Click on the Sign in button.
3. Enter your credentials and click on the Sign In button.
4. Click on the "Remember password" button (displayed in a pop-up).
5. Select an email address and finish the login process.
6. Log out.
7. Click on the Sign in button from MyFavoriteBeer again, then click on the "This is not me" link.
8. Type the same email address in the corresponding textbox, then click on the Tab key (or click inside the password textbox).
   1. Click on the Cancel button.
   2. Click on the Sign in button from MyFavoriteBeer again.
   3. Type the same email address in the corresponding textbox, then press the Tab key (or click inside the password textbox).

Expected Results:
 The password is automatically filled in the corresponding field both at step 8 and steps 11.

Actual Results:
 The password is not automatically filled in no matter if I manually type in the email, select it from a drop-down, click inside the password field or press Tab.

**Comment by ghost** [comment]
I should also mention I verified the Fx Password Manager and the password was actually saved.

**Comment by ghost** [comment]
This issue reproduces on Firefox (6.0, 7.0.1) on multiple OSs (Win XP, Win 7, Mac 10.6, Android). It works fine on IE9.

**Comment by shane-tomlinson** [comment]
@jbonacci -

https://bugzilla.mozilla.org/show_bug.cgi?id=355063 outlines a Firefox bug that shows that authentication content added to the DOM after DOMContentLoaded does not receive any love from the password manager.

This leads me to think I should pre-fill the form with the authentication content so that we do not have this problem.

**Comment by shane-tomlinson** [comment]
There are several bugs in Bugzilla related to this:

https://bugzilla.mozilla.org/show_bug.cgi?id=583578 - Prevents the password field from being updated with required email.

https://bugzilla.mozilla.org/show_bug.cgi?id=670137 - Closes the "remember password" dialog when a window is opened (or closed as is our case)

https://bugzilla.mozilla.org/show_bug.cgi?id=631800 - Prevents passwords from being saved if originally entered in a popup window.

**Comment by shane-tomlinson** [comment]
Following the instructions on https://wiki.mozilla.org/Firefox:Password_Manager_Debugging, I get the following in my error console.

https://skitch.com/set117/8b2u3/firefox-error-console-dialog-saving-password

STR
1) Load up Firefox
2) Do the about:config changes outlined in the above URL.
3) Restart browser
4) Go to myfavoritebeer.org
5) Open the Firefox error console.
6) Click Sign In
7) If Signed in, sign out
8) Enter email and password
9) Check error console.

**Comment by KaiRo-at** [comment]
For me, this is the most annoying issue with BrowserID so far, and the reason I have not chosen to use a very strong password for it, as remembering and re-entering a strong password time and again on multiple devices is a pain for me. If password manager can fill in the password, I'm much more willing to chose a stronger password that I might not remember as well personally - if it can't fill in the password, I need to chose one I can remember and type more easily, which usually ends up being way weaker.

**Comment by aleksejrs** [comment]
If you go to browserid.org itself, Firefox can enter the password, but that takes something like entering your e-mail address and clicking Sign In, possibly because the password field does not appear without an e-mail address.

And of course, it doesn’t work in the popup.

**Comment by Pike** [comment]
FWIW, this keeps me from editing MDN or finding people on mozillians. Also don't want to adapt persona on elmo until this is fixed.

**Comment by skinny97214** [comment]
Who is working with the upstream to get this fixed? This is a huge UX problem.

**Comment by shane-tomlinson** [comment]
Filed an upstream bug at: https://bugzilla.mozilla.org/show_bug.cgi?id=784028

**Comment by jrgm** [comment]
See also 
https://bugzilla.mozilla.org/show_bug.cgi?id=653775
https://bugzilla.mozilla.org/show_bug.cgi?id=631802
https://github.com/mozilla/browserid/issues/1076#issuecomment-3879333

**Comment by benediktp** [comment]
I'm seeing this in Firefox 20. It kept me from updating MDN a few times already.

**Comment by shane-tomlinson** [comment]
@aleth and @benediktp - Is this a Firefox bug for all sites or is this Persona specific?

**Comment by benediktp** [comment]
@shane-tomlinson: the password manager works for other sites but fails with the Persona login page [1].

The password manager contains an item for the domain with the correct password but its associated user name is empty. @aleth, do you see this too?

[1] https://login.persona.org/sign_in

**Comment by flying-sheep** [comment]
[this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=906300#c8) on bugzilla explains exactly what’s wrong, so how is this gaping omission still not closed?

i simply won’t even consider using persona on my own pages, and having to use it on MDN annoys me greatly.

**Comment by shane-tomlinson** [comment]
@flying-sheep - We are extremely resource constrained at the moment. PRs always gladly accepted and will be reviewed with utmost speed.

**Comment by shane-tomlinson** [comment]
Opened a new issue for the re-emergence of this issue: #4009
