### ISSUE TITLE
[bigtent] Showing an incomplete translation for website name on yahoo login dialog.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3146]
Refiled from @jbonacci's original filing of mozilla/browserid-bigtent#173

> I changed my Android device to Italian and started through the process of logging in with a Yahoo ID. In this case, I am trying a .com address in a localized log in, expecting to go to yahoo.com to log in (vs. going to yahoo.it).
> 
> When I get to the localized equivalent of the preverification step, I see the following:
> yahoo.com rende tutto cio davvero semplice
> Persona ti permette di utilizzare l'indirizzo yahoo.com account per accedere a siti come 123done.
> 
> Una volta verificato il tuo account presso il provider potrai accedere a %(aWebsite).s.
> 
> I am going to assume that list bit should be an actual web site name.
> 
> (This may have already been logged, but I could not find the issue listed)
> (And this may exist across more/all languages)

**Comment by shane-tomlinson** [comment]
@mathjazz - the problem here is in the Italian translation.

The translation of `"Once you verify your account there, you will be signed in to %(aWebsite)s."`

is listed as

```
"Una volta verificato il tuo account presso il provider potrai accedere a %"
"(aWebsite).s."
```

There is an extra `.` between the `)` and the `s` in `(aWebSite)s`

**Comment by mathjazz** [comment]
Fixed: http://viewvc.svn.mozilla.org/vc/projects/l10n-misc/trunk/browserid/locale/it/LC_MESSAGES/client.po?r1=114486&r2=114485&pathrev=114486

**Comment by shane-tomlinson** [comment]
@mathjazz - thanks!
