### ISSUE TITLE
[kpi] we are recording all xhr polling in interaction_data (regressed from issue 1619)

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3148]
In GH-1619, we stopped recording repetitive xhr polling. For example, if the /sign_in dialog is left up for several minutes, it will poll every 3 seconds waiting for e.g., `https://login.dev.anosrep.org/wsapi/email_addition_status?email=...`. 

A blob with all this data will exceed our 10K cap on POSTs, and the data will be discarded, with 413 returned.

However, trying this with dev.123done.org tonight, and leaving the dialog up for a long time, shows that we have started accumulating the polling xhr again.

It looks like this now:

```
    ...
    [
      "xhr_complete.GET/wsapi/email_addition_status",
      560839,
      223
    ],
    [
      "xhr_complete.GET/wsapi/email_addition_status",
      564064,
      219
    ],
    [
      "xhr_complete.GET/wsapi/email_addition_status",
      567285,
      240
    ],
    ...
```

I've checked that this is still rejected as 413 for POST /wsapi/interaction_data and that the localStorage.interaction_data is reset (but need to check this more with other browsers). (Side note: I need to check #1620 for the working offline case, but that's not this bug).

Anyways, @shane-tomlinson, we need a way to coalesce the xhr polling.

**Comment by shane-tomlinson** [comment]
@jrgm - we never actually fixed this problem. We filtered which data got sent so only the allowed top level KPIs were sent, then in another PR filtered email addresses, but never actually consolidated requests. 

We can make this happen easily enough though.

**Comment by shane-tomlinson** [comment]
@jrgm, @kparlante - What would the ideal here be? Should we keep track of the number of times the *_status functions were called? Do we care about the time the response takes?

**Comment by jrgm** [comment]
Probably what you had suggested, the first xhr plus a final count and duration of the series of xhrs. But I don't know how that would work with backend analysis purposes.

**Comment by kparlante** [comment]
@shane-tomlinson, @jrgm - Right now "backend analysis" of this would be a human looking at the data. High level questions we might ask with future visualizations/analysis: how many users wait for excessive amounts of time, what the average wait is, etc. Should be easy enough to get at those questions with the final count and duration of series of _status calls, so that seems like a reasonable strategy.
