### ISSUE TITLE
The "Password too long" message should mention the maximum number of allowed characters

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#315]
The "Password too long" message is displayed when the user tries to create an account and enters a password (+verification password) longer the the accepted amount of character. This message should mention the maximum number of allowed characters so the user could know how to modify his password without further investigation on his part. 

There are two other issues I found but I am not very sure they are bugs (if confirmed as bugs, they will be logged separately):
1. Currently the maximum number of characters the user can enter for his password 80. Isn't this a bit too long?
2. The user can enter any characters in his password. Is this ok? In case some characters will be restricted, an error message with those characters will have to be created too (in case the user tries to use them).

**Comment by shane-tomlinson** [comment]
maxlength="80" added to all password fields in 43ddfb02f4ef0aaed2b198471b3c58fd02280f37.

**Comment by shane-tomlinson** [comment]
@benadida - are there any restrictions on the characters that can be entered?

**Comment by benadida** [comment]
no restrictions on special characters.

**Comment by shane-tomlinson** [comment]
@benadida - We should put in a minimum password length message - the min is 8 characters?

**Comment by shane-tomlinson** [comment]
a new issue for minimum password length - #338
