### ISSUE TITLE
convert the tooltips to inline indicators and highlights

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#3154]
Kill them. Die. Die. Die.

We need to move to inline errors anyway for B2G. Let's make one visual style that works everywhere.

**Comment by jaredhirsch** [comment]
Is there a wireframe or mock someplace that documents inline notification
styles? Are they already in the product and I'm just forgetting them?

**Comment by skinny97214** [comment]
@6a68 They are coming from the b2g work to align our visual design more with Gaia.

![Screen Shot 2013-03-29 at 2 32 03 PM](https://f.cloud.github.com/assets/41135/319261/235ae242-98b8-11e2-8abd-8964c1399d3b.png)

**Comment by callahad** [comment]
Assigning to @skinny97214 to clarify. Other comments and concerns coming up.

**Comment by shane-tomlinson** [comment]
@skinny97214 - Can you elaborate more? My initial fears are that this is going to require a substantial amount of both work and testing to ensure our layout still functions correctly in letterific locales like German and Swedish. I want to find out more about the requirements before I go running for the hills.

**Comment by skinny97214** [comment]
@shane-tomlinson What's your feeling on how soon we might be able to get to this?

**Comment by jedp** [comment]
Update: @shane-tomlinson, @skinny97214, and @jedp meeting 6/10 to plan and schedule the work.

**Comment by shane-tomlinson** [comment]
Link this to the corresponding bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=879626

**Comment by csuciu** [comment]
"Sorry, PIN doesn't match" is still displayed as tooltip
