### ISSUE TITLE
Enabling KPI in browserid production

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3156]
This if for Monday, Apr 1st. Is noon a good time for Gene, and other folks (after the identity meeting)?

This will require changing the puppet production.json config to include:

```
"kpi_backend_sample_rate": 0.1,
"kpi_backend_db_url": "https://kpiggybank.personatest.org/wsapi/interaction_data",
```

and webheads will need to be restarted to pick up that change. The webheads will be individually drained. 

I have sent traffic at multiples of the expected rate that will result in, and I'm ok with that value for kpi_backend_sample_rate.

The squid proxy will also need changes similar to those for stage in https://github.com/mozilla/browserid/issues/3092. And gene already has those rules in place in production as of Friday afternoon.

I will have a tool to quickly check that posting into  the interaction_data is delivered all the way to the collector. @kparlante is getting the prod collector in place.

/cc @karlht, @kparlante, @gene1wood

**Comment by kparlante** [comment]
To ping the kpiggybank server, you can GET https://kpiggybank.personatest.org/wsapi/ping

**Comment by kparlante** [comment]
To look at the couchdb while on the box, you can get a count of blobs: curl -X GET http://127.0.0.1:5984/bid_kpi/_design/data/_view/count

**Comment by jrgm** [comment]
Okay, kpi is live in production as of 11:00 PDT and data is being received. Closing.
