### ISSUE TITLE
[chrome] IdP provisioning fails if 3rd party cookies are disabled.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3169]
STR)

1) Use Chrome with 3rd party cookies disabled.
2) visit dev.123done.org
3) Enter an eyedee.me address
4) Authenticate with eyedee.me
5) When you are redirected back to Persona, the dialog just sits there with no feedback. You can click the "submit" button twice to end up back at eyedee.me.

**Comment by callahad** [comment]
> 1) **Don't** Use Chrome with 3rd party cookies disabled.

FTFY.

**Comment by callahad** [comment]
With #2999, we'll know whether or not the user has 3rd party cookies disabled, so we have a path to figure this out and give a good error message.

**Comment by shane-tomlinson** [comment]
Link to #3116

**Comment by shane-tomlinson** [comment]
Closing since we merged #3116.
