### ISSUE TITLE
 After restarting an Android phone, the BrowserID Signing in tab is opened with the saved password prefilled in the corresponding textbox but with no email address

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#317]
Device: Google Nexus S phone 
OS: Android version: 2.3.4
Browser: Firefox 6

STR:
1. Open http://beta.myfavoritebeer.org/ in Firefox.
2. Log in to an account and allow the browser to save your password.
3. Log out from http://beta.myfavoritebeer.org/, then click on the "This is not me" link to log out from the BrowserID.
4. Restart the device.
5. Open http://beta.myfavoritebeer.org/ in Firefox again.
6. Click on the Sign in button.

Actual Results:
 The Signing in tab is opened with the saved password prefilled in the corresponding textbox but with no email address.

Expected Results:
 The Signing in tab is opened with wither both the saved password and the email address prefilled in the corresponding textboxes, or with none of them prefilled.

**Comment by csuciu** [comment]
This issue is no longer reproducible

Device: Samsung Galaxy R
OS: Android version: 2.3.4
Browser: Firefox 15
http://myfavoritebeer.org
