### ISSUE TITLE
[signin] - dialog does not close after verifying second secondary address when logged in with primary

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3178]
STR

1) Have an account with a primary and secondary
2) If signed in to Persona, sign out
3) Sign in to Persona with primary address
4) Re-open dialog
5) Click "Add new email address"
6) Enter a new secondary email address
7) In a different browser, open verification link
8) Enter password
9) return to original dialog, it just sits there.

This affects the current beta.

![Screen Shot 2013-04-03 at 12 47 01](https://f.cloud.github.com/assets/848085/333417/45fae230-9c54-11e2-84dc-09b0979712c1.png)

**Comment by jrgm** [comment]
Should be fixed by PR-3179. Closing.
