### ISSUE TITLE
Sign Up flow is confusing; conflates Sign Up with Sign In

### ISSUE THREAD

**Issue by aral** [mozilla/persona#3189]
Starts with Sign Up:

https://twitter.com/aral/status/319550653099802625

Becomes Sign In (at this point I think I must have done something wrong/I don’t know what to do)

https://twitter.com/aral/status/319550872315113472

If I do enter my email as if I was going to sign in (this is wrong; the two flows have intersected confusingly), I go back to the Sign Up flow:

https://twitter.com/aral/status/319551388730392577

The Sign Up process should remain landmarked as Sign Up throughout.

**Comment by edwindotcom** [comment]
I'd vote for just removing the term 'Sign Up' altogether in favor of just 'Sign In' throughout .

**Comment by jaredhirsch** [comment]
@skinny97214 care to comment?

**Comment by callahad** [comment]
The vast majority of users will get bootstrapped through the popup workflow as they're trying to sign into a site using Persona for the first time. That experience is a lot cleaner.

But we wanted _something_ that let people sign up or sign in by hitting the service's homepage...

What if we killed the in-content flow on login.persona.org and actually started using the normal popup?

Paging @skinny97214

**Comment by shane-tomlinson** [comment]
relate to #3151

**Comment by shane-tomlinson** [comment]
@callahad - ahha, you suggest issue #900.

**Comment by callahad** [comment]
@skinny97214 Concrete proposal: We're going to use the popup unless you tell us no. Assigned to you to tell us what's up.

**Comment by skinny97214** [comment]
Kill sign up for a new account CTA inside login.persona.org. There's just no reason to make an account with no RP context. I'll open a new bug for the necessary home page change.

**Comment by skinny97214** [comment]
For further context, our copy guideline are that it's always "sign in". We're following the pattern already established by other similar single sign on providers. There is no "sign up" or "sign on" only "sign in"

**Comment by callahad** [comment]
@skinny97214 Just to make sure: No popup _or_ sign in button on login.persona.org?

**Comment by skinny97214** [comment]
@callahad The sign in button can and should use the popup.

We have to allow _existing_ users to sign in, but we do not need to go out of our way to have a giant CTA on the home page for them to create an account. 
![BG9FoD5CAAAxmsp png_large](https://f.cloud.github.com/assets/41135/341042/3154aa26-9d64-11e2-9b9f-76c8d4f57907.png)

**Comment by callahad** [comment]
Gotcha. Thanks, @skinny97214 !

**Comment by shane-tomlinson** [comment]
@skinny97214 - what is a CTA?

**Comment by ozten** [comment]
CTA - Call to Action - Like a button that says "Create Account"

**Comment by shane-tomlinson** [comment]
Thanks @ozten, my UX vocabulary isn't very deep yet.

**Comment by callahad** [comment]
I'm hoping to hack on this soon.

**Comment by jaredhirsch** [comment]
#3253 has been merged in & removes the sign up/sign in flow completely from the site. Closing.
