### ISSUE TITLE
Possible b2g-blocker: Marketplace app sometimes dies due to OOM during identity login

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3191]
QA asked to escalate this issue, logged here for tracking purposes:
https://bugzilla.mozilla.org/show_bug.cgi?id=856240

Not sure if this is a b2g issue or browserid.

**Comment by jedp** [comment]
Short answer: I would consider this a b2g issue.

Longer answer:

As I understand it, when marketplace opens the identity flow, marketplace goes into the background, and this is the beginning of the problem.  From the operating system's point of view, this makes marketplace look like a good candidate for killing if there's an OOM situation.  When the Persona process starts (remember, it's its own process, and not in the main thread), the new process requires a large amount of memory - 10MB to be precise.  Persona doesn't have a choice in this; this is simply the base footprint of a new process.  So even though it only wants to open an iframe, the cost of opening an iframe in a separate process is 10MB.  

If this causes an OOM situation, the OS will look for apps to kill.  It will find the most killable apps and pick one at random.  The OS currently (as far as I know) has no hint that marketplace should be the last thing it tries to kill. It could therefore happen that marketplace gets killed at random.

As Justin commented on the bugzilla bug, there are two things that can be done to mitigate this problem.  First, the marketplace frame could remain in the foreground; this would render it a bad candidate for killing by the OS.  Second, the OOM procedure could include LRU logic, which I think Justin is working on.  This would be much better.

A third solution, which we would need platform's help on, would be to have a more nuanced way for a service like identity to request resources, e.g., web activity style.  I would expect that kind of thing is more of a 1.2 feature.  In the near term, finding a way to keep the marketplace app in the foreground sounds like a good fix.  Getting LRU behavior in there sounds like it would probably solve our problem completely, but I don't know what the time-frame is on that.

**Comment by edwindotcom** [comment]
Thanks for the update, I'll close this issue.
