### ISSUE TITLE
running selenium automation_tests go fullscreen on opera

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3192]
1. run java -jar selenium-server-standalone-2.X.jar
2. get on mac opera (didn't check windows) 
3. run automation_tests/scripts/run_all.js --local --platform=opera

actual: when tests run, opera goes fullscreen.  Something in the test framework or webdriver is causing browser to go 'mac' fullscreen (no menu bar)

expected: it shouldn't go fullscreen

**Comment by edwindotcom** [comment]
download and install? http://www.opera.com/computer/mac

automation-tests/config/local-platforms.js now supports 'opera'

**Comment by edwindotcom** [comment]
i believe opera works with this webdriver without anything opera specific: selenium-server-standalone-2.31.0.jar

#!/bin/sh
cd ~/Library/Selenium
exec java -Dwebdriver.chrome.driver=/Users/<YOU>/Library/Selenium/chromedriver -jar /Users/<YOU>/Library/Selenium/selenium-server-standalone-2.31.0.jar

**Comment by jaredhirsch** [comment]
@AutomatedTester have you heard about this bug? Any hints?

**Comment by lloyd** [comment]
does this actually cause tests to fail?

**Comment by callahad** [comment]
@karlht to try to repro outside of our testsuite

**Comment by callahad** [comment]
Tests still work, but it steals focus _every_ test.

We need to buy QA more machines and/or fix this.

**Comment by edwindotcom** [comment]
Karl and I tested with just a dumb py script and were able to repro the going fullscreen issue.  So this isn't specific to what we're doing. I'm happy to close this as upstream.  There are a number of specific local selenium issues for different browser and OS configs.  Saucelabs value add is that they solve a lot of these specific config quirks.

**Comment by jaredhirsch** [comment]
There's no reason we can't up our Saucelabs pipeline. Having a bunch more
people developing Selenium tests seems like a great justification to me.

**Comment by karlht** [comment]
As Edwin says, I was able to repro this issue outside of the Javascript webdrivers.  I'm inclined to tag it as upstream and emphasize Saucelabs testing over local.  In my opinion, local automated testing is best for very tightly focused testing of a single known issue.

**Comment by edwindotcom** [comment]
I'm closing since there no action here for us.
