### ISSUE TITLE
If the user saves the password used on the  "Never used BrowserID?" page, he is no longer given the possibility to save it for the "Signing in to..." page

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#320]
OSs: Windows XP, Windows 7, Android 2.3.4 (Samsung Nexus S phone), Android 3.1 (Acer A500 tablet)
Browser: Firefox 6

STR:
1. Open http://beta.myfavoritebeer.org/ in Firefox.
2. Click on the Sign in button.
3. Click on the "Never used BrowserID?" link.
4. Enter the required credentials and click on the Sign In button.

Actual Results:
 The user is offered the possibility to save his password. If the user agrees to save it from the "Never used BrowserID?" page, he is no longer offered the possibility to save it when logging in again from the "Signing in to ..." page. The password will not be automatically filled on the "Signing in to..." page either.

 Since usually a user configures an account much more rarely than he uses it to log in, it is preferable that he is either only given the chance to save his password from the "Signing in to..." page or from both pages.

**Comment by shane-tomlinson** [comment]
closing this issue as it is no longer valid in the new UX flow.
