### ISSUE TITLE
The whole BrowserID UI needs to be refitted when displayed on mobile devices

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#321]
Acer tablet
Model number: A500
Android version: 3.1
Kernel version: 2.6.36.3

Samsung Nexus S phone
Android version: 2.3.4

The whole BrowserID UI needs to be refitted when displayed on mobile devices. 

On both phones and tablets, the user needs to do too much scrolling through white space to reach different elements on a page.

The pages also need to be centered: e.g. the signing in area of the page (including the title above it) should be centered on the page, not displayed too small in a corner of the page (tablet) or somewhere close to the center but still so small half of the screen is white (phone).

Pop-up dialogs should be shorter while the devices are in portrait mode.

The text, links and buttons on BrowserID pages (pop-ups(native browser) or tabs(Fx6)) are much too small. The text from the pages footers is so small on phones it is barely readable. The links are also difficultly selected because of their size.  Considering the amount of empty space on the pages, these elements could be increased to appropriate sizes.

**Comment by lloyd** [comment]
I agree.  I think once this new UX in dev settles, we need to go and write custom UI for important mobile devices.

**Comment by shane-tomlinson** [comment]
This and #341 are duplicate.  Closing.
