### ISSUE TITLE
add IDL cat signal snippet to persona properties

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3210]
feel kinda bad to open as a ticket instead of PR, should be straightforward. anybody object to third-party code on persona.org (not in the dialog) and maybe the persona tumblr?

See internetdefenseleague.org for details.

**Comment by callahad** [comment]
I'd be -1. A breach on persona.org could expose certs / private keys, right? We've moved to hosting fonts and other assets ourselves for that reason.

**Comment by jaredhirsch** [comment]
Yeah, I was thinking about that. I suppose I'd have to sandbox their snippet inside an iframe.

**Comment by callahad** [comment]
Closing as wontfix :(
