### ISSUE TITLE
persona dialog hogs focus FF/linux

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3211]
@callahad has seen this on Gnome 3, reported by nemo in IRC this afternoon.

While the persona dialog is open, it stays on top of other open windows--a bit of a pain when you're waiting for the email to arrive.

Bug found on FF on linux, I can't repro on other platforms.

Not clear if this is an upstream bug (bug in OS window mgmt) or something we can improve by tweaking the window.open params.

**Comment by callahad** [comment]
I need to verify this, will update later.

**Comment by callahad** [comment]
Can reproduce on Linux. Other popups work fine. It's clearly something we're doing.
