### ISSUE TITLE
/include.orig.js is 404 on train-2013.03.29 on stage

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3212]
1. Go to https://login.anosrep.org/include.orig.js => 404

lib/static/views.js is looking for it in /build/include.js, but there is nothing there. Nor do I see a file `include.orig.js` anywhere in the unpacked rpm.

**Comment by shane-tomlinson** [comment]
This is the revenge of #3056 I believe. @callahad - wanna look at this?

**Comment by shane-tomlinson** [comment]
@jrgm - how is the server process started on staging/prod, is run_locally.js called at all?

**Comment by callahad** [comment]
sure thing

**Comment by jrgm** [comment]
So npm install is run on a build box and then an rpm is packaged with scripts/rpmbuild.sh and scripts/browserid.spec. That rpm is installed on stage/prod and is started with a shell script that sets CONFIG_FILES and does `bin/browserid`.

So, no, no run_locally.js.

**Comment by shane-tomlinson** [comment]
@jrgm - are any resources that we place into the "production" subdirectory included in the rpm package? I am thinking if we still do the initial build step to create the uncompressed include.js into build, then copy that as include.orig.js into production, it should be copied into the rpm and available to people that request it.

**Comment by jrgm** [comment]
Sorry, I got behind on all the email. So, see https://github.com/mozilla/browserid/blob/dev/scripts/browserid.spec#L35

So, resources/static/production is packaged into the rpm, so you're idea would work.

**Comment by swh** [comment]
Someone should get on this - it should be a simple fix, and it looks really scruffy!

Worst case just remove the comment from the top of the compressed .js file.

**Comment by edwindotcom** [comment]
+1 - still 404'ing

**Comment by lbredeso** [comment]
I just ran into this while trying to find the JavaScript that handles "returnTo" in the Observer API:  https://developer.mozilla.org/en-US/docs/Web/API/navigator.id.request

https://login.persona.org/include.js still references https://login.persona.org/include.orig.js, which still returns a 404.

**Comment by callahad** [comment]
<-- Jerk who didn't fix include.orig.js

**Comment by chilts** [comment]
I'll take a look at this. Assigning myself.

**Comment by seanmonstar** [comment]
Here's the reasons why: The uncompressed file is cleaned up by the rpmbuild process.

https://github.com/mozilla/browserid/blob/dev/lib/static/views.js#L145
https://github.com/mozilla/browserid/blob/dev/scripts/browserid.spec#L30

**Comment by jrgm** [comment]
Actually, the uncompressed file is not generated at build time anymore, so it doesn't exist anywhere for the packaging script to package.

**Comment by jrgm** [comment]
Ah, I'm sorry @seanmonstar. It is in ./rpmbuild/BUILD/browserid/resources/static/build. (I was looking in the wrong tree).

**Comment by gilbert** [comment]
I just ran into this problem too. I think there may be an issue with persona.js and rails 4's turbo links. I'd like to look into it; where can I view the uncompressed file?

**Comment by seanmonstar** [comment]
@mindeavor the uncompressed file is getting deleted in our build step. If you just want to browse the source, its in this folder: https://github.com/mozilla/browserid/tree/dev/resources/static/include_js

**Comment by djc** [comment]
@chilts sorry for stealing this, figured it'd be okay since you didn't touch it for two weeks or so.

So my patch is fairly straightforward. I tried to find a less literal way of describing the target path, but didn't really succeed. So I hope this simple approach is okay.

**Comment by mathiasbynens** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=901464 was merged into this issue.

**Comment by jrgm** [comment]
Hey @djc, sorry to steal your steal, so I stole your browserid.spec change, and adjusted some view logic and will have a PR in a moment to get this back available again as advertised.
