### ISSUE TITLE
Have an avatar/picture associated with a Persona.

### ISSUE THREAD

**Issue by sergiotapia** [mozilla/persona#3216]
When a user registers with OpenID they usually use an icon either saved from Gravatar or something else.

I would like it if Persona handled this natively and had some sort of Avatar/Picture associated with a user.

I'm not that familiar with the internals, but based on my limited knowledge on Persona, I imagine this would need to be handled by the persona ID provider.

**Comment by shane-tomlinson** [comment]
This is a dup of #1589, closing. @sergiotapia - I personally would love to see this too. Can you pile on in that issue?

**Comment by sergiotapia** [comment]
@shane-tomlinson  When you say pile on, do you mean just write a comment on the issue mentioning my interest in such a feature? I'm kind of new to this 'large' open source contribution thing.

**Comment by callahad** [comment]
@sergiotapia Yep, that's the idea. Everything is pretty chaotic, so more noise and history in a bug is generally a good proxy for "this is really important to a lot of people" :)

**Comment by callahad** [comment]
At least for our specific workflow. It's DEFINITELY not a universal thing :)
