### ISSUE TITLE
set password api call needed.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#322]
@lloyd (and others) - does it make sense to have a plain 'ole set password api call so that users can change their password after they have verified their account?

**Comment by benadida** [comment]
as long as it only works for accounts that don't already have a password. If the account already has a password, it should be a change password that includes the old password and new password.

**Comment by shane-tomlinson** [comment]
@benadida - I am thinking of the case where the user wants to change their password after their account is created/verified - so adding the old password field does make sense.

**Comment by shane-tomlinson** [comment]
relating this to issue #323.  We need the ability to allow the user to reset their password when the user has forgotten their password.  This would be triggered by a click to a link inside of an email - would this be taken care of by "complete_user_creation"?  If so, can we change the name of that function to better reflect its purpose?

**Comment by shane-tomlinson** [comment]
Closing.

We now have both change password and set password on accounts that need passwords..
