### ISSUE TITLE
check_primary_support fails silently unless ephemeral keypair present

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3221]
This is the second report I've seen of check_primary_support stalling and never returning info: https://twitter.com/Lukasaoz/status/320967071934603264

**Comment by Lukasa** [comment]
I got this failure on Mac OS X 10.8.2 (Mountain Lion), using Node version v0.10.3 (which is the version you get if you install from Homebrew).

**Comment by jrgm** [comment]
Works for me on either hand-rolled 0.10.3 or 0.8.17 on Mac OS X 10.7.5 (which isn't a "no you're wrong", but just "need a better way to narrow this down").

**Comment by Lukasa** [comment]
To be totally clear, I'm not very familiar with Node at all, so it's quite possible that I've done something stupid. I don't think I did though :smile:.

When I stepped through this in the debugger, execution went basically as I expected to [here](https://github.com/mozilla/browserid/blob/dev/lib/primary.js#L149), and then it never hit the callback [here](https://github.com/mozilla/browserid/blob/dev/lib/primary.js#L107).

**Comment by seanmonstar** [comment]
Could it be like we've seen just recently on the list, an SSL error? Maybe
one of you guys have the cert cached on your Mac, and the others don't?

**Comment by Lukasa** [comment]
Do you have a link to the issue on the list? I'm not subscribed to it so I can't really say.

**Comment by callahad** [comment]
@Lukasa A quick way to rule out sean's suggestion would be to try to run check_primary_support against a known-good primary, like eyedee.me. Does that fail in the same way for you?

**Comment by Lukasa** [comment]
It does, yes.

**Comment by callahad** [comment]
Cool. I suspect a node 0.10 issue, since most of us are still on 0.8... but haven't had a chance to actually try upgrading myself

**Comment by Lukasa** [comment]
When I get some spare time, I'll see if installing 0.8 fixes my issue. =)

**Comment by jrgm** [comment]
Yeah, I missed that the "fail" was that it never returns. Missed that. With 0.10.3 I see that. The answer comes back okay, but it never exits. Or actually, if you wait long enough, it will exit. Anyways, looking at the code, I'm not sure how this ever worked ;-). It's registering listeners on the request not the response.

**Comment by Lukasa** [comment]
Hmm. Installing v0.8 hasn't fixed the issue, and neither has updating to the latest HEAD (which presumably includes #3185. Any further thoughts about areas I might look into?

**Comment by callahad** [comment]
@Lukasa Really? Hrmph. 

Here's what I see when I run it. How does your output differ?

```
$ git checkout -q 229e8e4b288d33e5b97b7536163e95f03ced52ae

$ node -v
v0.10.4

$ node ./scripts/check_primary_support yahoo.login.persona.org
info: process type is check_primary_support
info: yahoo.login.persona.org is a valid browserid primary
Primary domain:      yahoo.login.persona.org
Authoritative Domain:    yahoo.login.persona.org
Authentication URL:  https://yahoo.login.persona.org/authentication
Provisioning URL:    https://yahoo.login.persona.org/provision
Public Key:      {
  "rsa": {
    "n": {
      "arr": [
        135885251,
        154196924,
        93658565,
        181499840,
        5243574,
        8571970,
        199417801,
        77222063,
        170291818,
        220839529,
        7355243,
        120255474,
        93622368,
        85121521,
        166334144,
        131898341,
        131923101,
        100152342,
        70592962,
        33508776,
        236884196,
        151631986,
        258026027,
        99205318,
        50608852,
        235889835,
        48195313,
        160243045,
        57257592,
        178351812,
        222874454,
        3648664,
        60820657,
        13787982,
        99420085,
        163182499,
        46417881,
        182276352,
        47258295,
        44791630,
        175968538,
        191511325,
        112606096,
        23267672,
        170091947,
        102037681,
        196628438,
        246172665,
        125110736,
        108728567,
        262678722,
        18252088,
        48400338,
        88886900,
        176603890,
        147777209,
        55921559,
        252227316,
        80891212,
        24574039,
        198476395,
        215717482,
        107716095,
        147564124,
        227968129,
        1509405,
        44307316,
        100172140,
        112420531,
        162041611,
        53062097,
        145143762,
        19006004,
        12,
        0
      ],
      "t": 74,
      "s": 0
    },
    "e": {
      "arr": [
        65537
      ],
      "t": 1,
      "s": 0
    },
    "d": null,
    "p": null,
    "q": null,
    "dmp1": null,
    "dmq1": null,
    "coeff": null
  },
  "keysize": "256",
  "algorithm": "RS"
}
https://yahoo.login.persona.org/authentication contains proper script tag
https://yahoo.login.persona.org/provision contains proper script tag

$
```

**Comment by Lukasa** [comment]
```
$ git checkout -q 229e8e4b288d33e5b97b7536163e95f03ced52ae

$ node -v
v0.10.4

$ node ./scripts/check_primary_support yahoo.login.persona.org
info: process type is check_primary_support

$
```

**Comment by callahad** [comment]
Alright, I'm actually on OS X 10.7, as is @jrgm. Let me go find a box with 10.8 on it...

**Comment by callahad** [comment]
Oh, great. I can reproduce this on OS X 10.8.2.

**Comment by Lukasa** [comment]
Phew. I was afraid I might be going crazy or missing something really obvious. =)

**Comment by callahad** [comment]
I just... why would this break between 10.7 and 10.8 on the same version of node? :cold_sweat:

**Comment by callahad** [comment]
I'll try to come up with a minimal test case by Monday.

**Comment by Lukasa** [comment]
Yeah, right now I have infinite sympathy for this you with this bug. :cake:

**Comment by callahad** [comment]
Woo! I've got it!

@Lukasa Run `node ./scripts/generate_ephemeral_keys.js`, then try to use `check_primary_support` again.

**Comment by callahad** [comment]
Basically, `primary.js` tries to load a local keypair, which fails on fresh checkouts of the repo because, well, you haven't generated it yet.

However, it fails before logging is set up, so you never see the error message.

By commenting out the `logging.enableConsoleLogging()` line in `check_primary_support` and then running `LOG_TO_CONSOLE=1 ./scripts/check_primary_support yahoo.login.persona.org` logging will be configured early enough to see that error message.

**Comment by Lukasa** [comment]
Victory! Works like a charm!

Awesome, thanks so much guys. =)

**Comment by callahad** [comment]
/me re-titles issue to "check_primary_support fails silently unless ephemeral keypair present"
