### ISSUE TITLE
General update any old browser, OS, and selenium versions

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3231]
- win7_firefox_16
- linux_firefox_16
- osx_firefox_14
- win7_chrome
- winxp_ie_8
- win7_ie_9
- win8_ie_10
- linux_opera_12
- osx_safari_5

Firefox -> 20
Mac 10.6 is also old.

If we bump the version, we also need to increase our version of selenium, according to saucelabs. Currently 2.26 to the latest 3.31.

To do this we would:
0. run all tests on all platforms with current set locally. Save results.
1. make changes firefox and other browsers. Also change our selenium version
2. run all tests on all platforms with current set locally. Save results
3. diff results

**Comment by jaredhirsch** [comment]
Let's update it for sure. PRs welcome, I'm happy to review.

**Comment by jrgm** [comment]
Closing. I did this in https://github.com/mozilla/browserid/pull/3510
