### ISSUE TITLE
The user is signed out from his account on http://myfavoritebeer.org/ when reloading the page

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#324]
OS: Windows 7 32-bit
Browser: Firefox 6.0

STR:
1. Open http://myfavoritebeer.org/.
2. Sign in using BrowserID.
3. Reload  http://myfavoritebeer.org/.

Actual Results:
 The user is signed out from his account.

Expected Results:
 The user is still logged into his account.

**Comment by shane-tomlinson** [comment]
@ioanab - can you log bugs for myfavoritebeer.org at https://github.com/lloyd/myfavoritebeer.org/issues

**Comment by ghost** [comment]
@shane-tomlinson
I logged a copy of this bug at https://github.com/lloyd/myfavoritebeer.org/issues.

**Comment by ghost** [comment]
The copy of this bug on https://github.com/lloyd/myfavoritebeer.org/issues is issue #24.
