### ISSUE TITLE
For android support, server responses may not be 'false' or 'null'

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#325]
There are issues with current android browsers.  Anant writes:

> JSON.parse behaves badly on Android, where if it gets a null or false value it raises an 'Illegal access' exception which is exactly what I was seeing: http://samritchie.net/2011/04/01/uncaught-illegal-access-exception-in-android-browser-on-json-parse/
> 
> /wsapi/am_authed returns 'false' if you're not logged in and this causes JSON.parse to blow up. Perhaps we can return [false] or {'authed':false} instead?

We should review all api output and change it to return objects in all cases, imo.  This would also address issue #217 and issue #216

**Comment by lloyd** [comment]
Anant found the problem on version 2.3.4 of the android browser.  @stomlinson or @benadida - is this in the range that we know we don't support?  /me forgets.

**Comment by benadida** [comment]
I'm not sure, but since I'm comfortable moving to all JSON object return values after discussing with QA, why don't we just solve this regardless?

**Comment by shane-tomlinson** [comment]
@benadida, @lloyd - we have discussed moving to all JSON object return values before, I'm all for doing it.

**Comment by shane-tomlinson** [comment]
https://github.com/mozilla/browserid/issues/217 is the issue talking about JSON objects.

**Comment by lloyd** [comment]
it's unanimous re json objects.  all we needs is some agreement on naming.
