### ISSUE TITLE
"Add another address" / "this is not me" buttons reflow poorly in non-English locales

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3250]
[Reported on the mailing list](http://thread.gmane.org/gmane.comp.mozilla.identity.devel/4159)

In some locales, like French and German, the "Add another email address" and "This is not me" buttons overflow their container and look bad:

![Screenshot of issue](https://f.cloud.github.com/assets/24193/383185/d492d430-a60e-11e2-889d-849b924ac64e.png)

**Comment by jaredhirsch** [comment]
yeah, that doesn't look great. I'm not sure how we could improve this with just a tweak.

Right-aligning or left-aligning those grey buttons is just going to look awkward, and so will keeping the grey buttons on one line, so that they stretch past the blue button.

**Comment by callahad** [comment]
To start, it might help to give the buttons some measure of `margin-top` so they at least have some space when that happens...

**Comment by shane-tomlinson** [comment]
@skinny97214 and I fixed this exact problem yesterday, but I have not yet submitted a PR for it. Will do today.
