### ISSUE TITLE
Looks like https://login.persona.org/ isn't using TLS session tickets

### ISSUE THREAD

**Issue by Lennie** [mozilla/persona#3252]
Looks to me like https://login.persona.org/ isn't using TLS session tickets this adds a lot of connection overhead when a second TLS connection is created.

It looks like Nodejs already has code to handle it in 0.8: https://github.com/joyent/node/issues/2846

I thought 0.8 was already in use in production.

**Comment by seanmonstar** [comment]
0.8.x is in production. That ticket suggests the speed up was from using 64bit nodejs. Worth investigating...

**Comment by callahad** [comment]
Wouldn't this be nginx's job? Or are we letting node handle TLS itself in production?

**Comment by jrgm** [comment]
We use 64bit node 0.8 in production, but ssl is handled by Zeus currently and will be handled by ELB on aws.

**Comment by callahad** [comment]
Marking as 1-star since we're moving to AWS.

@gene1wood: Will we need to do this once we're on AWS? If so, please bump to 3 stars.

**Comment by jedp** [comment]
This might not be perceptible on desktop over a good network, but for a user on 2G edge network, the extra requests would surely cause a noticeable slow-down. Anything we can do to improve performance for mobile users, I think we should do.

**Comment by gene1wood** [comment]
@Lennie what's a good way to detect if TLS session tickets are in use? Can you test if the same problem exists at https://yahoo.login.persona.org/ ? This is because this load balancers is in AWS and will be what all of our load balancers will look like shortly. If https://yahoo.login.persona.org/ isn't using TLS session tickets then we're good and this problem will be solved with our move to AWS.

**Comment by Lennie** [comment]
Gene I found it by just looking at things with Wireshark.

But just looked around and there is an easier method:

$ openssl s_client -connect yahoo.login.persona.org:443 -reconnect -no_ticket | grep Session-ID
depth=3 /C=US/O=Equifax/OU=Equifax Secure Certificate Authority
verify return:1
depth=2 /C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
verify return:1
depth=1 /C=US/O=GeoTrust, Inc./CN=GeoTrust SSL CA
verify return:1
depth=0 /serialNumber=tN9IL7t4sarCaTQYjFETqnfDK/LIS-2J/C=US/ST=California/L=Mountain View/O=Mozilla Corporation/CN=yahoo.login.persona.org
verify return:1
    Session-ID: 4845ACBBB0ED3E33DF56F627CF26C3FFB8B6E6084119097A3F34DFE3ADD0104E
    Session-ID-ctx:
    Session-ID: 4845ACBBB0ED3E33DF56F627CF26C3FFB8B6E6084119097A3F34DFE3ADD0104E
    Session-ID-ctx:
    Session-ID: 4845ACBBB0ED3E33DF56F627CF26C3FFB8B6E6084119097A3F34DFE3ADD0104E
    Session-ID-ctx:
    Session-ID: 4845ACBBB0ED3E33DF56F627CF26C3FFB8B6E6084119097A3F34DFE3ADD0104E
    Session-ID-ctx:
    Session-ID: 4845ACBBB0ED3E33DF56F627CF26C3FFB8B6E6084119097A3F34DFE3ADD0104E
    Session-ID-ctx:
    Session-ID: 4845ACBBB0ED3E33DF56F627CF26C3FFB8B6E6084119097A3F34DFE3ADD0104E
    Session-ID-ctx:
^C
$ openssl s_client -connect login.persona.org:443 -reconnect -no_ticket | grep Session-ID
depth=3 /C=US/O=Equifax/OU=Equifax Secure Certificate Authority
verify return:1
depth=2 /C=US/O=GeoTrust Inc./CN=GeoTrust Primary Certification Authority
verify return:1
depth=1 /C=US/O=GeoTrust Inc/OU=See www.geotrust.com/resources/cps (c)06/CN=GeoTrust Extended Validation SSL CA
verify return:1
depth=0 /businessCategory=Private Organization/1.3.6.1.4.1.311.60.2.1.3=US/1.3.6.1.4.1.311.60.2.1.2=California/serialNumber=C2543436/C=US/ST=California/L=Mountain View/O=Mozilla Foundation/OU=IT/CN=www.persona.org
verify return:1
    Session-ID: D18C81D01A3A28DC9C61FA7B7FDF5BA2CA53967CFB32D0E5AB0C8EDA473EA43C
    Session-ID-ctx:
depth=3 /C=US/O=Equifax/OU=Equifax Secure Certificate Authority
verify return:1
depth=2 /C=US/O=GeoTrust Inc./CN=GeoTrust Primary Certification Authority
verify return:1
depth=1 /C=US/O=GeoTrust Inc/OU=See www.geotrust.com/resources/cps (c)06/CN=GeoTrust Extended Validation SSL CA
verify return:1
depth=0 /businessCategory=Private Organization/1.3.6.1.4.1.311.60.2.1.3=US/1.3.6.1.4.1.311.60.2.1.2=California/serialNumber=C2543436/C=US/ST=California/L=Mountain View/O=Mozilla Foundation/OU=IT/CN=www.persona.org
verify return:1
    Session-ID: 87C715C7F4FA0923764471358F1D21B5891B5267833351C460B3B2A8A9AC8707
    Session-ID-ctx:
    Session-ID: 87C715C7F4FA0923764471358F1D21B5891B5267833351C460B3B2A8A9AC8707
    Session-ID-ctx:
depth=3 /C=US/O=Equifax/OU=Equifax Secure Certificate Authority
verify return:1
depth=2 /C=US/O=GeoTrust Inc./CN=GeoTrust Primary Certification Authority
verify return:1
depth=1 /C=US/O=GeoTrust Inc/OU=See www.geotrust.com/resources/cps (c)06/CN=GeoTrust Extended Validation SSL CA
verify return:1
depth=0 /businessCategory=Private Organization/1.3.6.1.4.1.311.60.2.1.3=US/1.3.6.1.4.1.311.60.2.1.2=California/serialNumber=C2543436/C=US/ST=California/L=Mountain View/O=Mozilla Foundation/OU=IT/CN=www.persona.org
verify return:1
    Session-ID: 5A2C4B870D6903F1E328965099745593918A5410A19BBFABE46DD5C1C81138C7
    Session-ID-ctx:
depth=3 /C=US/O=Equifax/OU=Equifax Secure Certificate Authority
verify return:1
depth=2 /C=US/O=GeoTrust Inc./CN=GeoTrust Primary Certification Authority
verify return:1
depth=1 /C=US/O=GeoTrust Inc/OU=See www.geotrust.com/resources/cps (c)06/CN=GeoTrust Extended Validation SSL CA
verify return:1
depth=0 /businessCategory=Private Organization/1.3.6.1.4.1.311.60.2.1.3=US/1.3.6.1.4.1.311.60.2.1.2=California/serialNumber=C2543436/C=US/ST=California/L=Mountain View/O=Mozilla Foundation/OU=IT/CN=www.persona.org
verify return:1
    Session-ID: 20C529204BFE62B3A9320E3B124F7FB181AF4618A8BD7926B6EACF25F3B02016
    Session-ID-ctx:
depth=3 /C=US/O=Equifax/OU=Equifax Secure Certificate Authority
verify return:1
depth=2 /C=US/O=GeoTrust Inc./CN=GeoTrust Primary Certification Authority
verify return:1
depth=1 /C=US/O=GeoTrust Inc/OU=See www.geotrust.com/resources/cps (c)06/CN=GeoTrust Extended Validation SSL CA
verify return:1
depth=0 /businessCategory=Private Organization/1.3.6.1.4.1.311.60.2.1.3=US/1.3.6.1.4.1.311.60.2.1.2=California/serialNumber=C2543436/C=US/ST=California/L=Mountain View/O=Mozilla Foundation/OU=IT/CN=www.persona.org
verify return:1
    Session-ID: 6ED6DE9A4E1D36C4C4B6ECF7A41315323D127D596FCE4B785EC29DA4311732E1
    Session-ID-ctx:
^C

As you can now easily see login.persona.org does not support TLS session reuse and yahoo.login.persona.org on Amazon does support it.

**Comment by gene1wood** [comment]
Great, so with our move this problem gets solved for free. If waiting for the move to finish to get this functionality is acceptable I'll close this.

**Comment by Lennie** [comment]
I don't see much of disadvantage.

Obviously your data is not encrypted on the network between ELB and your machines, but I doubt that matters much.

The biggest disadvantage, I can see, if you choose to terminate HTTPS on ELB/AWS you also choose not to use SPDY. You can also terminate TCP at ELB, I believe, but I've never really looked into it.

**Comment by callahad** [comment]
@Lennie Thanks for the investigation!

@gene1wood During triage we felt like this was great, but not worth the time if we got it for free with AWS. Given that AWS is pretty imminent. Closing.

**Comment by fmarier** [comment]
@gene1wood Another easy way to check whether TLS session tickets are in use is to use the [SSL Labs test tool](https://www.ssllabs.com/ssltest/analyze.html?d=https%3A%2F%2Flogin.persona.org) (second to last section).

**Comment by fmarier** [comment]
Just to confirm, we now have _Session resumption_ and _Session tickets_ enabled in production.
