### ISSUE TITLE
Sign in button hidden if too many email addresses -- add affordances for this use case.

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3266]
I have to scroll to find the sign in button if I have too many email addresses:

![Screen Shot 2013-04-17 at 4 23 20 PM](https://f.cloud.github.com/assets/24193/393850/794056dc-a7a5-11e2-836a-ceddb94fa3e0.png)

This fails _hard_ in Safari and Chrome on OS X, thanks to the new scrollbar style introduced in 10.7. Firefox will have the new style soon: http://bugzilla.mozilla.org/636564

![Screen Shot 2013-04-17 at 4 27 18 PM](https://f.cloud.github.com/assets/24193/393860/cd0ebc4a-a7a5-11e2-9bd8-23c36bf6b2ae.png)

![Screen Shot 2013-04-17 at 4 29 29 PM](https://f.cloud.github.com/assets/24193/393868/eb0a67a8-a7a5-11e2-95b1-3d79dfe97876.png)

**Comment by callahad** [comment]
This is related to #2399, which made the list scrollable in the first place.

**Comment by jrgm** [comment]
There is an open issue on firefox in bugzilla, where the zoom on the opener page affects the size of the opened window - https://bugzilla.mozilla.org/show_bug.cgi?id=779335

**Comment by callahad** [comment]
@jrgm I think you meant to comment on #3267...

**Comment by shane-tomlinson** [comment]
We did it this way because on mobile in landscape mode, you could only see 1 email address if the buttons were always shown, especially once you consider TOS/PP agreements.

**Comment by callahad** [comment]
@shane-tomlinson Can we add some sort of inner shadow when that content overflows? I don't know how easy CSS makes it these days...

**Comment by callahad** [comment]
Re-purposing bug: Add some sort of indication that there are things that are hidden.

**Comment by shane-tomlinson** [comment]
What would be super handy here is knowing both the maximum and median number of emails users have. @kparlante - can we get that info from the KPIs?

**Comment by edwindotcom** [comment]
what if  you scrolled the list so the buttons show at the very least?

**Comment by shane-tomlinson** [comment]
Dup of #2622, closing.
