### ISSUE TITLE
Popup is a different size in all browsers. Looks bad in Safari.

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3267]
Check out the screenshots in #3266. The content area of the popups are different sizes in each:

Safari is 700x391
Firefox is 700x375
Chrome is 700x347

Anything over 375 starts showing the flat edges of the arrow, making Safari looks particularly bad.

**Comment by callahad** [comment]
In all cases, zoom level was set to 100%.

**Comment by shane-tomlinson** [comment]
@callahad - something is fishy here.

Here is what it looks like on my computer

Safari->Firefox->Chrome (L->R)

![screen shot 2013-05-03 at 15 24 34](https://f.cloud.github.com/assets/848085/459280/6481436e-b3fd-11e2-89ed-4465e85c0d6d.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
