### ISSUE TITLE
performance: what's ApplicationCache got to offer?

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3269]
suggested by @benadida: could appcache improve performance significantly?

refs:
- basics
  - https://developer.mozilla.org/en-US/docs/HTML/Using_the_application_cache
  - www.html5rocks.com/en/tutorials/appcache/beginner/
- gotchas
  - http://appcachefacts.info/
  - http://alistapart.com/article/application-cache-is-a-douchebag

**Comment by lloyd** [comment]
Does this really deserve a github issue?

-- lloyd (thumb-typing)

**Comment by jaredhirsch** [comment]
@lloyd it's an optimization we might try; not sure how to slot this into existing performance stuff. is there an etherpad? should I just ping the dev-identity list?

**Comment by shane-tomlinson** [comment]
After talking with several well respected developers (Google and Financial Times engineers) about this, I believe App Cache is not the solution. App cache is a difficult to manage cache on top of the HTTP cache and is meant for offline applications. Using it for performance generally only causes headaches and as long as the app is online, the HTTP cache is significantly more flexible and faster in most cases. Their recommendation was unless we are going for offline capabilities, use only the HTTP cache.
