### ISSUE TITLE
The xhr_delay error message doesn't specify which WSAPI call is timing out

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3270]
When an XHR to a WSAPI call is taking longer than 10 sec to return, we show the "We are sorry, this is taking longer than it should." error message.

It would be great to have a "show more details" link like on other error pages and to include the name of the WSAPI call it was trying to make.

In the `xhrDelay()` function of `resources/static/common/js/xhr.js`, it looks like we are passing the request information (`reqInfo`) along with that event. However, `delayStart()` (in `resources/static/common/js/modules/xhr_delay.js`) isn't passing it on when rendering the error page.

**Comment by khuevu** [comment]
Hi fmarier, can I work on this issue?

**Comment by seanmonstar** [comment]
@khuevu it's yours!
