### ISSUE TITLE
Add CSP headers to login.persona.org

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3271]
While we've writing about [CSP](https://developer.mozilla.org/en-US/docs/Security/CSP) in a number of other bugs, it doesn't look like we have a bug open for actually adding CSP headers to `login.persona.org`.

Even if we still have eval's in our code, we could serve a `Content-Security-Policy` header with `script-src: unsafe-eval` and a `X-Content-Security-Policy` header with `options eval-script`.

The big win for us would be that we could disable all inline scripts.

**Comment by fmarier** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=672001

**Comment by seanmonstar** [comment]
taking this, it's easy and big win
