### ISSUE TITLE
Filing a security related bug not possible

### ISSUE THREAD

**Issue by gtrs** [mozilla/persona#3272]
As the github bugtracker doesn't support marking bugs as private, a security related issue would become public before a fix can be released.

On https://github.com/mozilla/browserid/wiki/So,-you-wanna-hotfix,-eh%3F it is suggested to use bugzilla instead. On https://bugzilla.mozilla.org BrowserID is not listed as a Mozilla product, so the bug cannot be categorized correctly and can only be submitted to a different project team.

**Comment by callahad** [comment]
If you're aware of a security issue, you can always email any of us directly. (I'm callahad, mozilla.com)

Otherwise, the Mozilla Labs :: Identity component is a fine place to file.

**Comment by callahad** [comment]
(Let's update the wiki!)

**Comment by ozten** [comment]
[Boom!](https://github.com/mozilla/browserid/wiki/So,-you-wanna-hotfix,-eh%3F)
