### ISSUE TITLE
b2g: unable to sign in with a mockmyid.com (primary) account

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3278]
On Inari:
1. goto native.123done.org
2. goto step 1, add a user@mockmyid.com
3. click 'Add'

result: page refresh in native UI and 'Add' button returns to enabled (not greyed out)
if you leave it there, it eventually goes to a time out error page

expected: you should be able to add a primary

**Comment by edwindotcom** [comment]
my settings are: 
b2g 1.1.0.0
roamer2

**Comment by edwindotcom** [comment]
This also includes user@eyedee.me

**Comment by shane-tomlinson** [comment]
Is this using Persona from the marketplace? If so, primary support should be completely disabled and there may be another issue here.

**Comment by callahad** [comment]
Closing as wontfix
