### ISSUE TITLE
b2g: after javascript closes native UI dialog, browser becomes fullscreen with no address bar

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3281]
on roamer2 with build 4/18 build
0. sign in with an account 
2. goto native.123done.org
3. sign in with an account (secondary),
4. goto native.123done.org
5. click 'this is not me'
6. enter the same user as step 3
actual: native UI closes and browser is now in fullscreen and has no address bar.

expected: javascript closing the native UI should not cause browser to go full screen

**Comment by jedp** [comment]
@edmoz, apart from the browser going full-screen, which is certainly weird, does it sign you in correctly as the user from step 3?

**Comment by jds2501** [comment]
FWIW, if this was an issue potentially, I'd expect it to be a Gaia Browser bug, not a persona bug.

**Comment by jds2501** [comment]
Another thing you should check is that after complete the STR, if you scroll up, can you get the address bar back?

The address bar becomes non-present in cases where you are not at the top of the page. But if it's permanently gone, that's bad.

**Comment by edwindotcom** [comment]
I could never get the address bar back, I had to kill the process with Xing the card view.

**Comment by edwindotcom** [comment]
I haven't been able to repro this a 2nd time.  I'm thinking i may have gotten into a low memory situation which cause the screen artifacts.  I'll leave it open for a few days to see if I run into it again.

**Comment by edwindotcom** [comment]
I'm going to close this as the fullscreen issue is a red herring.  I'll log a new one that's related but different in many ways.
