### ISSUE TITLE
b2g: native.123done.org sign in button takes 2x longer to load than regular site

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3283]
1. goto native.123done.org
2. noticed the blue 'sign in' button

actual: takes 1-2 sec to load, about 2x longer compared to when you go to 123done.org

expected: should be same time as 123done.org.

**Comment by callahad** [comment]
On the same device, good connection, etc.

The difference is native-persona.org vs persona.org.

**Comment by callahad** [comment]
@jedp Probably slow because it's spinning up an entirely new process to handle the native-persona iframe.

**Comment by callahad** [comment]
@jedp to investigate and update.

**Comment by lloyd** [comment]
I'd love to see timing numbers:
1. iframe embedded
2. iframe resources loaded
3. RP receives onready

These three points will allow us to understand whether process startup or network latency is the major culprit.

I suggest we do this minimal amount of assessment, reason about the results, and then either make a fix if it's apparent there's something we can do, or close this down.

Optionally, we can consider changing our recommendation to RPs that they don't wait for the iframe to display a user actionable button.  see voo.st's implementation

**Comment by jedp** [comment]
So far other b2g stuff has kept me from investigating this further this week.

**Comment by callahad** [comment]
native.personatest.org seems to be dead. Is this bug still valid since #3576 has been closed?

**Comment by jedp** [comment]
You should just be able to hit 123done.org now - no `native` prefix anymore.

**Comment by edwindotcom** [comment]
agreed - this is obsolete and does not occur with www.123done.org
