### ISSUE TITLE
b2g: logging out of 1 tab does not cause other tabs to logout till refreshed

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3284]
I'm on Inari with sha: a5a95f7f
1. goto native.123done.org in 1 tab and sign in
2. do the same for another tab
3. log out of one of the tabs
4. look at the other tab

result: you are not automatically logged out.
expected: you should get logged out.
work around: if you hit refresh, you will be logged out.

**Comment by jedp** [comment]
Good catch.  I think this broke when we made the persona iframe non-permanent on b2g.

This is going to require a fix on device.  Here's a bug for it:
https://bugzilla.mozilla.org/show_bug.cgi?id=864886

**Comment by jedp** [comment]
I've uploaded a patch to the bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=864886#c3

**Comment by jedp** [comment]
Oh great.  The patch works on b2g desktop, but seems to have no effect on b2g device.  It appears that each tab in the browser on b2g desktop has a different window id; but each tab on the device browser has the _same_ window id.  Can this really be?

**Comment by jedp** [comment]
There's a fix on b2g platform for the window id issue I mentioned in the previous comment.

**Comment by jedp** [comment]
I've requested uplift for v1.1 (leo+)

**Comment by jedp** [comment]
So this has landed in b2g18 and has been uplifted to b2g18 v1.1.  It should be testable on any b2g18 nightly build

https://pvtbuilds.mozilla.org/pub/mozilla.org/b2g/nightly/mozilla-b2g18-unagi-eng/latest/

Closing.  Please re-open if there are problems.
