### ISSUE TITLE
b2g: general UX issues of fields and buttons

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3285]
linking issue to https://bugzilla.mozilla.org/show_bug.cgi?id=851190
I don't want to lose this bug

In general, a lot of scrolling and return key must be used to navigate the native UI when using persona.  It would be fairly frustrating for new users.

**Comment by edwindotcom** [comment]
the bugzilla bug is the main bug to use

**Comment by shane-tomlinson** [comment]
@edmoz - is this a dup of #2970?

**Comment by edwindotcom** [comment]
yes - happy to dupe to #2970
