### ISSUE TITLE
need to sync time with server before signing assertion

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#329]
otherwise problem logging in.

**Comment by lloyd** [comment]
@benadida suggests we get server time.  I suggest we combine this with the /wsapi/csrf call, meaning that call moves to return an object which returns server time and csrf token, then at the time assertion signing is performed we calculate offset from the time csrf response was received, and that is the assertion generation time.

we might want to rename csrf call to `session_context` or some such.

**Comment by benadida** [comment]
agreed.
