### ISSUE TITLE
[bigtent] ie8 - provisioning fails with "provisioning timeout" if user does not click "Sign in with Yahoo" within 10 seconds.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3293]
@ozten, @callahad - I could use some help debugging this.

STR

1) Load up IE8.
2) Clear browser cache
3) Visit dev.123done.org
4) Open dialog
5) Enter a yahoo address
6) On the "Yahoo makes this easy" screen, wait for 20 seconds.

![Screen Shot 2013-04-22 at 13 50 13](https://f.cloud.github.com/assets/848085/409213/5bac7efc-ab4c-11e2-9e1a-c5ba05834ca9.png)

Is BigTent relying on the referrer header?

Relate to #3120

**Comment by shane-tomlinson** [comment]
@edmoz - is this a dup of #2970?

**Comment by shane-tomlinson** [comment]
@edmoz - That last comment was for issue #3285, not this.

**Comment by callahad** [comment]
This is not bigtent-specific. I addeded an ugly hack to MockMyID that waits 20 seconds before finishing provisioning if you append `+slow` to your username there:

``` javascript
if (email.indexOf('+slow@') !== -1) {$
  window.setTimeout(function () { navigator.id.registerCertificate(signedObject); }, 20000);$
} else {$
  navigator.id.registerCertificate(signedObject);$
}
```

20 seconds seems to reliably trigger this error. 19 works fine.

When failing, no additional POSTs are made to any wsapis -- the shim just locally rejects the cert and calls it a day.

**Comment by lloyd** [comment]
We have a timer to deal with runaway provisioning pages.  See provisioning.js.  It sounds like that timer is not ending properly for the first provisioning attempt.

I don't think the mockmyid repro is relevant...

-- lloyd (thumb-typing)

**Comment by callahad** [comment]
@lloyd Can I challenge the status quo? Removing the timer solves both the bigtent and the mockmyid issue, and gives the user the possibility of succeeding with provisioning.

Leaving it in just fails without recourse...

**Comment by lloyd** [comment]
@callahad the bigtent issue is just a bug.  we start the timer too early.  is there really a mockmyid issue?

**Comment by ozten** [comment]
> Is BigTent relying on the referrer header?

Just to answer this question....

BigTent uses referrer in development mode to dynamically pick the Persona environment. Our dev server isn't in development mode.

**Comment by callahad** [comment]
@lloyd There's not "really" a mockmyid issue, but the hack there demonstrates that: If an IdP takes more than 20 seconds to provision, the user sees an error message and does not get provisioned.

If the timer didn't exist, it would work fine. And so would BigTent.

**Comment by ozten** [comment]
This occurs in production per lloyd in IRC.

**Comment by shane-tomlinson** [comment]
@ozten - it does. Does that mean it is a regression that slipped past us or has it always been there?

**Comment by ozten** [comment]
@shane-tomlinson It's a brand new service, so it's not a regression.

Any idea of % of Persona users on IE 8 to help with priority/severity of this bug?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
