### ISSUE TITLE
Inputs not disabled when adding another address or signing in for the first time

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3294]
While the dialog is "Checking with your email provider," the text input is disabled, but the "next" button is still active. There's no spinner indicating progress / work.

![Screen Shot 2013-04-22 at 10 31 35 AM](https://f.cloud.github.com/assets/24193/409968/f3d70c3c-ab61-11e2-8f53-3cfe694c6196.png)

When adding an email address to an existing account, the dialog remains fully enabled and is interactive during provisioning.

![Screen Shot 2013-04-22 at 10 34 12 AM](https://f.cloud.github.com/assets/24193/409978/1d1be7d4-ab62-11e2-8b08-6e6aadca2f9a.png)

The text input and button should be disabled during these phases.

**Comment by shane-tomlinson** [comment]
@callahad - does this affect all browsers?

**Comment by callahad** [comment]
@shane-tomlinson Definitely Chrome and Firefox. Haven't checked others.

**Comment by shane-tomlinson** [comment]
Manually merged @arlolra's PR, closing.
