### ISSUE TITLE
path.js throw error 'Arguments to path.join must be strings'

### ISSUE THREAD

**Issue by jzkunlun** [mozilla/persona#3297]
When run npm install, it failed on multiple locations with path.js error.

**Comment by callahad** [comment]
What version of Node are you using? Can you paste some of the console output? Thanks!

**Comment by jzkunlun** [comment]
npm ERR! toobusy@0.2.2 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 8
npm ERR!
npm ERR! Failed at the toobusy@0.2.2 install script.
npm ERR! This is most likely a problem with the toobusy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls toobusy
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/home/jing/node/bin/node" "/home/jing/node/bin/npm"
"install"
npm ERR! cwd /home/jing/node/browserid
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE

> node-proxy@0.6.0 install
> /home/jing/node/browserid/node_modules/client-sessions/node_modules/node-proxy
> node-gyp configure build

path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at new Gyp
(/home/jing/node/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:49:22)
    at gyp
(/home/jing/node/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:39:10)
    at Object.<anonymous>
(/home/jing/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jing/node/browserid/npm-debug.log
npm ERR! not ok code 0
npm ERR! browserid@1.0.0-b1 preinstall: `node ./scripts/lockdown`
npm ERR! `sh "-c" "node ./scripts/lockdown"` failed with 1
npm ERR!
npm ERR! Failed at the browserid@1.0.0-b1 preinstall script.
npm ERR! This is most likely a problem with the browserid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/lockdown
npm ERR! You can get their info via:
npm ERR!     npm owner ls browserid
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/home/jing/node/bin/node" "/home/jing/node/bin/npm"
"install"
npm ERR! cwd /home/jing/node/browserid
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jing/node/browserid/npm-debug.log
npm ERR! not ok code 0

**Comment by callahad** [comment]
Reformatted:

```
npm ERR! toobusy@0.2.2 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 8
npm ERR!
npm ERR! Failed at the toobusy@0.2.2 install script.
npm ERR! This is most likely a problem with the toobusy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls toobusy
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/home/jing/node/bin/node" "/home/jing/node/bin/npm"
"install"
npm ERR! cwd /home/jing/node/browserid
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE

> node-proxy@0.6.0 install
/home/jing/node/browserid/node_modules/client-sessions/node_modules/node-proxy
> node-gyp configure build



path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at new Gyp
(/home/jing/node/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:49:22)
    at gyp
(/home/jing/node/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:39:10)
    at Object.<anonymous>
(/home/jing/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jing/node/browserid/npm-debug.log
npm ERR! not ok code 0
npm ERR! browserid@1.0.0-b1 preinstall: `node ./scripts/lockdown`
npm ERR! `sh "-c" "node ./scripts/lockdown"` failed with 1
npm ERR!
npm ERR! Failed at the browserid@1.0.0-b1 preinstall script.
npm ERR! This is most likely a problem with the browserid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/lockdown
npm ERR! You can get their info via:
npm ERR!     npm owner ls browserid
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/home/jing/node/bin/node" "/home/jing/node/bin/npm"
"install"
npm ERR! cwd /home/jing/node/browserid
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jing/node/browserid/npm-debug.log
npm ERR! not ok code 0
```

**Comment by callahad** [comment]
It looks like you're using Node 0.10.4 -- Persona is currently being developed against 0.8.x. Could you try downgrading and see if you can reproduce the error? Or check out the `nodejs-0.10.0` branch of this repository?

**Comment by jzkunlun** [comment]
Thanks
