### ISSUE TITLE
b2g: confirming email causes native UI freeze

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3299]
I'm on inari/ikura - sha: a5a95f7f8 - I've repro'd this 2 times.
1. sign in with a new email on native.123done.org
2. let phone sit with native UI up for about 5 min
3. on another device, confirm email
4. look at phone

actual: settings UI returns to 'add another email address' and clicking on the 'Add' button is not responsive. No error pages is ever loaded.

expected: native UI should close and you should return to browser.

**Comment by edwindotcom** [comment]
native UI gets into a bad state. See screenshot:
![2013-04-23-11-02-39](https://f.cloud.github.com/assets/3698618/415939/7d0c423a-ac41-11e2-93cc-b0a829fd39ae.png)

**Comment by edwindotcom** [comment]
oh wow - i killed the process, and it's still messed up. I have to restart phone.

**Comment by jedp** [comment]
@edmoz did you get any logs?  if you can repeat it, can you stash the logs?  thanks!

**Comment by edwindotcom** [comment]
refined title and steps. There's a second bug here that i'll log seperately.  Here are what i get when i run logcat http://people.mozilla.com/~ewong2/reg_fail.txt

**Comment by jedp** [comment]
Hm.  Can you push this pref: `pref("toolkit.identity.debug", true);` to your user prefs?

That will enable all the persona logging.  Thanks!

**Comment by jedp** [comment]
@jedp will try as well

**Comment by edwindotcom** [comment]
I updated my channel to nightly and pushed the pref. Now i'm not able to repro.  I'm thinking I was on an old build.  I'm on SHA: 

Gecko  http://hg.mozilla.org/releases/mozilla-b2g18/rev/efe8da9c584a
Gaia   a5a95f7f8ae6f1ba297bd5d5dd117b4197e1047c
BuildID 20130418070205

closing till I can repro again.
