### ISSUE TITLE
b2g: sign in with new email and waiting 3 min leads to registration failed

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3301]
repro'd 2 times on ikura - sha: a5a95f7f8
1. sign in with new email on native.123done.org, redirected to waiting for confirm page
2. wait about 3 min
3. on another device/computer confirm email with native UI page is up.

actual: 503 error or registration failed error.
see screen shot
![2013-04-23-12-20-51](https://f.cloud.github.com/assets/3698618/416465/3af6b670-ac4e-11e2-8bd8-682eaddc4b17.png)

logs:
503 error:
http://people.mozilla.com/~ewong2/503_on_wait.txt
registration failed error:
http://people.mozilla.com/~ewong2/reg_fail.txt

**Comment by edwindotcom** [comment]
I'm no longer able to repro this after i updated to nightly channel

**Comment by edwindotcom** [comment]
dupe of #3309

**Comment by jrgm** [comment]
Not a dup on #3309. GH-3309 is specifically about auth_with_assertion, and your image above  shows user_creation_status.
