### ISSUE TITLE
Publish error screens to KPI

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#3302]
It'd greatly help to know what percentage of users are "unsupported", and which browsers those are.

**Comment by seanmonstar** [comment]
I'm trying to decide if this should be an addition the `kpi_data`, or just an additional event.

There's two places I could do this: 
- at the catch block in dialog.js, so that we only publish this error
- inside PageModule#renderError, we could publish an error event (which gets added to the KPI stream) that includes the error message and extra info. This seems like a decent KPI to know: when did the user hit an error screen, and why?

@shane-tomlinson @kparlante did I just overload this issue too much? The work for either fix is similar, just one shares with us more data that seem like valid KPIs.

**Comment by kparlante** [comment]
@seanmonstar @shane-tomlinson So I was skeptical that collecting all JS errors in KPI was a good idea, but it does make sense to me that we would capture an error screen in the event stream.

**Comment by seanmonstar** [comment]
@shane-tomlinson what do you think of an implementation like this? https://github.com/seanmonstar/browserid/commit/a7a2477e0895ab7f652b62f713ebf0734461838e

I can create a PR once it seems like a good idea to do it that way.

**Comment by seanmonstar** [comment]
Fixed with #3304
