### ISSUE TITLE
Send interaction_data from communication_iframe on dialog_complete

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#3305]
We currently only get KPI data if the user comes back a second time. What about all the people who try once, and never come back? We'd love to see what screen they got to before deciding this wasn't for them.

If a site is using the watch() API, then the calling site will have an iframe available, and can send the data to our piggyback right when the dialog is closed. It should clean up when it's sent, so that when the dialog opens again, it doesn't get sent twice.

The check in the dialog should stay put, so that sites using the get() API will still send us KPI data.

**Comment by shane-tomlinson** [comment]
Closing as a dup of #3306

**Comment by jaredhirsch** [comment]
/me wins the bug filing race ;-)
