### ISSUE TITLE
KPI data is not sent for users who only open the Persona dialog once

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3306]
Currently, we don't fire KPI data at the time it's collected, we fire it on the subsequent trip through the dialog.

Since the dialog's localstorage is accessible to the communication_iframe, we could just have the iframe fire kpi data when it receives the dialog_complete event.

In particular, we could figure out how many users are bailing out of the dialog flow by saving some state in localstorage each time a dialog screen is displayed.

We could either just record the last screen viewed, or we could record the sequence of screens they viewed.

In either case, even if a user never uses persona again, we can figure out where in the flow they are bailing out.

**Comment by seanmonstar** [comment]
It seems easiest and data-full to just allow the event stream to fill up as normal, and send the full interaction_data. That will show what screen they got to.

Also, we filed the same issue at the same time. #3305

**Comment by lloyd** [comment]
Generally, i think we should try in multiple places.  Dialog and now also iframe.  Was that the intention?

-- lloyd (thumb-typing)

**Comment by seanmonstar** [comment]
@lloyd I said as much in #3305, which I filed at the same time as Jared filed this one.

**Comment by r0bl0rd** [comment]
Hey all - this is Rob Lord, incoming Mozillian. (More on that later.)

+1 for metrics at each stage of the funnel so we know our visible -> qualified -> best bet -> closed user counts and conversions. 

Rob
via iPhone

**Comment by shane-tomlinson** [comment]
@6a68, @seanmonstar - We talked about doing it this way once and decided against it. Sending data from the iframe will not work for RPs that are using the .get API. So that we did not have to have some sort of lock mechanism to check who should send the data, we decided to do it only in the dialog. If we are to convert to sending data from the iframe, we have to make sure all of the flows are properly covered.

Changing the name of this issue from a proposed solution to a description of the problem - "KPI data is not sent for users who only open the Persona dialog once."

**Comment by lloyd** [comment]
@seanmonstar word.

**Comment by lloyd** [comment]
@shane-tomlinson good point about the locking mechanism.  I'm curious though if we can solve this with a creative algorithm that simply and elegantly addresses the race condition.
1. take the blob out of local storage
2. try the XHR
3. if it fails return the blob to local storage.

**Comment by seanmonstar** [comment]
@lloyd :+1:

You'd have to very fast to open the dialog again before the communication frame finishes sending the small JSON blob back home.

**Comment by lloyd** [comment]
sorry for the noise.  apparently I'm wondering what if 9 was 6.  Ignore the previous two commits.

**Comment by jaredhirsch** [comment]
do we assign a UUID to the blobs? if so, we could leave the de-duping to the server and simplify the client

**Comment by ozten** [comment]
+1 UUID

**Comment by shane-tomlinson** [comment]
I stole this. A PR is outstanding, but needs to be updated - #3495
