### ISSUE TITLE
sign-in-test fails on stage

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3308]
Only happens on staging. 
in local tree:
1. git checkout train-2013.03.29
2. scripts/run-all.js --local -e stage --platform osx_firefox_14 --tests sign*
-in the test, it signs in with all caps user@personatestuser.org to beta.myfavbeer.org
-when it's confirmed, the top right of the site just says 'Yo, ' , it should say 'Yo, user@personatestuser.org'

result:
    sign-in-test - osx_firefox_14 (1 failure(s), 0 warnings):
      13: verify signed in to myfavoritebeer, errors:
        \*   timeout hit

expected:
if you run it on prod, it passes. `scripts/run-all.js --local -e prod --platform osx_firefox_14 --tests sign*`

No repro on prod or dev which leads me to believe there's an AWS issue.

**Comment by edwindotcom** [comment]
gene and jrgm are discussing - looks like there's a bad redirect in stage.

**Comment by edwindotcom** [comment]
I'm assigning and starring.  This is blocking automated testing for the AWS release.

**Comment by gene1wood** [comment]
Our physical staging environment and AWS staging environment had different keys. diresworb.org and anosrep.org still point to physical stage ( due to https://id.etherpad.mozilla.org/root-zones-and-aws-elbs ). I've updated physical staging's keys and cookie secrets to match and deployed. Test it now

**Comment by karlht** [comment]
Passes for me now on stage.

**Comment by edwindotcom** [comment]
passes for me now, closing
