### ISSUE TITLE
blocker: can't sign in: Permission denied to access property 'browserid_relay_https://browserid.org/sign_in'

### ISSUE THREAD

**Issue by mimecuvalo** [mozilla/persona#331]
Getting this JS error:
Error: Permission denied to access property 'browserid_relay_https://browserid.org/sign_in'
Source File: https://browserid.org/dialog/production.js
Line: 38

Both in Firefox 7 and Chrome.

**Comment by benadida** [comment]
this might be a caching issue, can you try clearing your cache so we can see if this is the issue?

**Comment by mimecuvalo** [comment]
Cleared cache now on Chrome and Firefox - still no go.

2011/9/30 Ben Adida <
reply@reply.github.com>

**Comment by mimecuvalo** [comment]
Ok, this is my fault actually.  Instead of directly linking to https://browserid.org/include.js I had copied that source code to my server to avoid the cost of the extra HTTP call to your browserid server.  I see though that the interface is not yet completely settled.

Might be good to add a note on https://browserid.org/developers that it might not be wise to copy the file (at least for now).
