### ISSUE TITLE
B2G: For testability, make removal of `waiting` class from body the very last javascript action

### ISSUE THREAD

**Issue by zacc** [mozilla/persona#3318]
For testability it would be hugely beneficial to make the removal of the `waiting` class in the body the very last step performed by javascript after opening the Trusty UI dialog.

This would create a clear event from which the test is free to proceed.

Currently our UI tests wait for this to be cleared but then immediately run into problems with more javascript still processing after that point.

We can't wait for an element because of device (B2G) limitations on clearing cookies, localStorage, etc we cannot be 100% sure which state the Persona dialog will be in when we open it.

**Comment by jaredhirsch** [comment]
Updated title to make it clear it's B2G-specific

**Comment by callahad** [comment]
@shane-tomlinson recently fixed this. Still needs to get merged into dev and deployed.

**Comment by shane-tomlinson** [comment]
By coincidence, I did this in PR #3331. As soon as it is merged, this will be all good. @zacc - FWIW, I changed the name of the class from "wait" to "loading"

**Comment by shane-tomlinson** [comment]
This should be fixed with the merge of #3331. The "waiting" class name has been renamed to "load". @zacc - take it away, this is now merged into dev. Can you let me know if this suits your needs better?
