### ISSUE TITLE
train-2013.04.26 - javascript error bringing up the dialog.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3319]
Right now train-2013.04.26 is on the old physical stage. I was just going to get it a quick look before I asked to push this out to AWS. And I hit an error on the main site:

STR

1) Change /etc/hosts to point to physical stage:

63.245.209.245 diresworb.org www.diresworb.org
63.245.209.240 anosrep.org login.anosrep.org www.anosrep.org
63.245.209.239 static.login.anosrep.org verifier.login.anosrep.org

2) Go to login.anosrep.org, and click signin to bring up the dialog.

Actual:

Chrome says "improper usage of API: TypeError: Cannot read property &#x27;length&#x27; of undefined"

If I'm right, I think the exception is here: https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/modules/interaction_data.js#L348 and `eventStream` is undefined.

Which fits. This error is "most of the time", and stage is configured to sample kpi at 20%.

**Comment by seanmonstar** [comment]
Interesting. I'd expect it to be only part of the 20%, not most of them time, because that function is not supposed to be executed [if sampling is not enabled](https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/modules/interaction_data.js#L322).

**Comment by jrgm** [comment]
Yeah. Okay, I may be wrong about the location; that was just from trying to recognize fragments from the minified code.

**Comment by jedp** [comment]
It looks like the default value here should be `[]`, not `null`: https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/modules/interaction_data.js#L249 (`null !== undefined`, but still)

**Comment by jrgm** [comment]
Running locally unminified firefox says "TypeError: eventStream is undefined ".

**Comment by jrgm** [comment]
Oh, there we go: https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/modules/interaction_data.js#L322

**Comment by jrgm** [comment]
Oops, wrong line. Here: https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/modules/interaction_data.js#L388

**Comment by jrgm** [comment]
oh, and @seanmonstar, the 'sampling is not enabled' check sometimes has  samplingEnabled === undefined, so that check doesn't bail.

**Comment by lloyd** [comment]
@shane-tomlinson hey dude, given you're going to be waking up in an hour or two, do you mind reviewing jrgm's minimal patch and merging or changing it so we can close down the 5 star and proceed with train testing?

**Comment by jrgm** [comment]
By the way, this PR is running at https://issue3319j.personatest.org/

**Comment by jrgm** [comment]
@lloyd also noted this in irc: "are these two lines transposed? https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/modules/interaction_data.js#L321-L322"

**Comment by lloyd** [comment]
fix is merged into the train, what do we have to do to land a fix on dev and shut down this 5 star eyesore?

**Comment by jrgm** [comment]
I'm making a PR for dev as we speak.

**Comment by jrgm** [comment]
Patches landed in both `dev` and `train-2013.04.26`. Closing.
