### ISSUE TITLE
Google Talk interaction?

### ISSUE THREAD

**Issue by davidascher** [mozilla/persona#332]
Not sure how I got in this state, but after trying to auth to http://dev.myfavoritebeer.org/, I ended up with 

a) a google talk widget on my G+ tab which shows a 404 error page
b) an Error Console with:

Error: An exception occurred.
Traceback (most recent call last):
  File "resource://browserid_addon-at-mozillalabs-dot-com-api-utils-lib/tabs/tab.js", line 254, in null
    .getInterface(Ci.nsIWebNavigation)
Error: Permission denied for https://talkgadget.google.com to create wrapper for object of class UnnamedClass

which seems very odd.

**Comment by davidascher** [comment]
btw, using: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:9.0a1) Gecko/20110924 Firefox/9.0a1

**Comment by lloyd** [comment]
Disabling browserid addon, restarting browser, makes problem disappear?  /cc @stomlinson

**Comment by shane-tomlinson** [comment]
This is not a browserid bug but a browserid_addon bug which is filed under https://github.com/mozilla/browserid_addon/issues/83

**Comment by lloyd** [comment]
@shane-tomlinson woah dude.  wait a second.  who is @stomlinson, and who is @shane-tomlinson?

**Comment by shane-tomlinson** [comment]
@stomlinson is my personal GitHub., When I started with Mozilla, I was asked to create a new account (or so it seemed to me at the time) so @shane-tomlinson is the account I use for Mozilla related projects.  I want to merge the two accounts because having both is a serious pain.

**Comment by lloyd** [comment]
I conclude it was a misperception.  that's not how mozilla rolls.

**Comment by shane-tomlinson** [comment]
@lloyd - I agree with you, and now I have two accounts.  Merging the two means I lose the history of one.
