### ISSUE TITLE
New registration redirects to login.persona.org instead of relying party after timeout

### ISSUE THREAD

**Issue by yourcelf** [mozilla/persona#3333]
**Expected**: When a user is confirming an email address with persona for the first time, and clicks the link in the "Confirm address" email that reads "Click to confirm this email address and sign in to &lt;relying party domain&gt;", they are redirected to the relying party.

**Actual**: If the user waits some period of time before clicking the link in the email (I don't know what the lower limit is -- 15 minutes seems to be enough to trigger the problem), they are redirected to "login.persona.org" instead.

**Steps to reproduce**:
1. Sign up for persona by clicking a "sign in" link on a relying party's website, and enter a new email address.
2. Wait a while before clicking the email link.
3. Click the email link, and get redirected to login.persona.org instead of the relying party's site.

I encountered this because the email provider I was signing in with uses graylisting, which means I didn't get persona's email till around 15 minutes after it was sent.  When I sign up with the same site with a non-graylisting email provider, it works fine.  When I sign up with the non-graylisting email provider and wait 15 minutes before clicking the link, the problem happens.

The relying party I tested with (https://intertwinkles.org) issues navigator.id.request with the following parameters:

```
{
    siteName: "InterTwinkles"
    termOfService: "/about/terms/"
    privacyPolicy: "/about/privacy/"
    returnTo: "/"
    siteLogo: "/static/img/star-icon.png"
}
```

**Comment by shane-tomlinson** [comment]
@yourcelf - this is very strange indeed. Are you opening the verification link in the same browser that you started the process in?

**Comment by yourcelf** [comment]
@shane-tomlinson Hadn't expected that to be necessary, but I checked again, and yes: same browser exhibits this problem.

**Comment by p0ffsrule** [comment]
Is it OK if I try to fix this bug?  Also, could I get any relevant information I would need ?

**Comment by seanmonstar** [comment]
This is apparently by design. If the returnTo field is older than 5 minutes, we dump it: https://github.com/mozilla/persona/blob/dev/resources/static/common/js/storage.js#L181

As to whether we actually want that design, I have no idea. If we didn't it'd be a simple as changing that line.

**Comment by yourcelf** [comment]
I'd argue for not expiring returnTo's.  When the confirmation email reads "Click to confirm this email address and sign in to &lt;relying party domain&gt;", it's a lie if Mozilla doesn't sign you in to &lt;relying party domain&gt;.  At the very least, grow the timeout.  Standard email graylisting services run around a 15 minute delay, which causes all users behind such systems to not get in.

If there is a good reason to expire returnTo (privacy?) maybe make the timeout a few hours.

**Comment by callahad** [comment]
@p0ffsrule go for it! :)

**Comment by p0ffsrule** [comment]
So, should I remove the timeout altogether or extend it to a few hours like yourcelf said?

**Comment by callahad** [comment]
I think a few hours is a more conservative change. Let's do that.

**Comment by p0ffsrule** [comment]
On it.

**Comment by p0ffsrule** [comment]
I sent the pull request.  I changed the timeout to 2 hours.
