### ISSUE TITLE
b2g: need myfavoritebeer.org to work with native UI

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3335]
1. on b2g - goto  myfavoritebeer.org
2. click sign in
   actual: new browser dialog pops up
   expected: native UI should launch

**Comment by jedp** [comment]
Fantastic.  It's broken on b2g.  https://bugzilla.mozilla.org/show_bug.cgi?id=867847

A fix on client is necessary.  Patch submitted.

**Comment by jedp** [comment]
In triage for tef+

**Comment by jedp** [comment]
Approved for tef+.  Should be landing in the coming week.

**Comment by jedp** [comment]
Landed and uplifted to 1.0.1.  Yay.

**Comment by shane-tomlinson** [comment]
merged and pushed lloyd/myfavoritebeer.org#66
