### ISSUE TITLE
Uncompressed JavaScript isn't available

### ISSUE THREAD

**Issue by swh** [mozilla/persona#3347]
https://login.persona.org/include.js

says:

```
/**
 * Uncompressed source can be found at https://login.persona.org/include.orig.js
 *
```

But https://login.persona.org/include.orig.js just returns an error:

```
Cannot GET /build/include.js
```

**Comment by shane-tomlinson** [comment]
Dup of #3212, closing.  We should really fix this.

**Comment by shane-tomlinson** [comment]
Sorry for the terse response @swh - thanks for reporting this to us. Can you pile on in the first bug and chastise us into action?

**Comment by swh** [comment]
No problem, and will do.
