### ISSUE TITLE
iOS dialog has spinner while loading

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3353]
Not really sure if this is a bug.

Steps to Reproduce
1) On iPhone in Safari go to http://dev.myfavoritebeer.org
2) Click button

Actual
For 1-3 seconds, I see the spinner. It is now huge and white, instead of being grey like the rest of the dialog
![](http://dl.dropbox.com/u/10060532/Screenshots/prWw.png)

Expected
Dialog loads. Maybe a subtle indeterminate progress bar if this will take a while.

**Comment by jedp** [comment]
This functionality was requested by the designer.  @shane-tomlinson has made it look a lot better since this was filed, but this is the desired behavior

Ergo closing.
