### ISSUE TITLE
[safari] Persona login fails in Safari Private Browsing

### ISSUE THREAD

**Issue by zandr** [mozilla/persona#3356]
If I'm using Safari in Private Browsing mode, I'm unable to log in to air.mozilla.org.

Clicking the Sign In button takes me to the login popup, but I get "Persona requires cookies to remember you." 

Same behavior in desktop and mobile (iPad) Safari. Functions as expected in Aurora.

**Comment by shane-tomlinson** [comment]
Thanks for reporting this @zandr - this is a dup of #3094 I believe.

**Comment by shane-tomlinson** [comment]
And #3220

**Comment by zandr** [comment]
I'll take your word for it. Those are pretty different behaviors from the user perspective, which is why I filed a new issue. :)

**Comment by jedp** [comment]
Closing as duplicate
