### ISSUE TITLE
KPI: cancel after mistyped email shouldn't count as new_account

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3359]
- open a browser with empty local storage
- sign in to 123done.org (or wherever)
- enter an email address (non-bigtent) that doesn't exist on the fallback yet (mistyped or wrong email, from the user's perspective)
- hit cancel when it prompts you to create a password
- choose an email address that has been entered before properly
- enter the correct password and sign in

The blob that is generated has new_account = true, which it probably shouldn't.

The kpi-dashboard was confused by this case, as it hit the set_password screen and assertion_generated but not the email verification middle steps. The kpi-dashboard is not currently using new_account, fwiw, so this change isn't blocking anything. (I modified the data to treat any event stream with enter_password as not new).

**Comment by seanmonstar** [comment]
Mmm, so then `new_account` should be set after we get a successful return from `set_password` screen?

**Comment by kparlante** [comment]
Or, re-set `new_account` to be false if the user later goes down a path known to be not-new, e.g. if they hit `authenticate.enter_password`. I think we want `new_account` to be true even if the user wanders away at that point and fails to set a password.
