### ISSUE TITLE
Verification of email in different browser is broken

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#336]
When you verify an email using a browser other than the one you use to create the browserid account, the dialog displays the "yucky" error message:

> Registration Failed
> An error was encountered and the signup cannot be completed. Yucky!

Steps to reproduce:
1. go to dev.myfavoritebeer.org and sign in
2. click `this is not me` if you're already logged in
3. add a new email address you haven't used before
4. get the email
5. open the verification link in a different browser than the first
6. complete account setup by setting a password
7. notice the dialog transitions to _yucky_

The wsapi in this case will return 'needsAuth', which means that it's detected that the verification link was used to verify the email, however it also sees that no authenticated session was created.  The only way this can occur is if the email is verified elsewhere.

We _are_ talking about disallowing this in another issue, but for the purposes of the design branch we should probably just detect the `needsAuth` error condition and transition back to the authentication screen with the email that the user has verified pre-filled in.  It's not awesome UX, but at least it's functional.

**Comment by ghost** [comment]
Verified this issue by:
logging in to beta.myfavoritebeer.org from Fx 7.0.1 and confirming email from Opera;
logging in to beta.myfavoritebeer.org from Chrome and confirming email from Fx 7.0.1.

The "Thank you for signing up with BrowserID ..." message is displayed in the browser you confirm the email from and the user can continue his log in in the other browser without any issues. 

OS: Windows 7 x86
