### ISSUE TITLE
Dialog disappears and won't come back up after following "Learn more" link to main page

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3360]
1. Go to dev.123done.org
2. Sign in with Persona
3. In the dialog, hit the "learn more" link
4. In the browser, hit the "sign in" button

The dialog closes, and repeatedly hitting the sign in button doesn't bring it back up.

On production of course, you can sign in on the main site. This is new with the change to use the dialog from the main site: @shane-tomlinson

**Comment by kparlante** [comment]
I should add that you can go back to dev.123done.org and bring up the dialog from the "Sign in with Persona" link normally -- you just can't do it from the main page.

I tried this on both Chrome and Safari.

**Comment by jaredhirsch** [comment]
maybe just dismiss the dialog after learn more is clicked? /me shrugs

**Comment by callahad** [comment]
Closing. This basically works for me in Firefox, Chrome, Safari, and Opera. It's a little weird -- takes two clicks instead of one -- but it otherwise works and represents a super weird corner case.
