### ISSUE TITLE
Sign-in link on TOS page doesn't work

### ISSUE THREAD

**Issue by karlht** [mozilla/persona#3361]
STR:
1. Pop a dialog from beta.123done.org
2. Click on the Terms of Service link.
3. Try to click on the 'Sign in' link on the resulting TOS page.

Expected:
1. Sign-In page.

Actual:
1. Link doesn't work.

**Comment by karlht** [comment]
This is probably due to the sandboxing done as part of the b2g work.  /cc @shane-tomlinson, @jedp  

Thoughts?

**Comment by shane-tomlinson** [comment]
@karlht - Are you trying this from a b2g phone or a normal browser? If a normal browser, I think this is related to #3253.

**Comment by shane-tomlinson** [comment]
@karlht - this is a really odd scenario, this is occurring because the dialog is already open when you try to do another sign in. In effect, you are trying two do two concurrent sign ins in two dialogs, I do not believe we have ever supported this.

**Comment by shane-tomlinson** [comment]
@karlht - finally, with the merge of #3236, this exact scenario should no longer be possible because TOS/PP agreements are opened inline in the dialog. Nice corner case finding. It will still be possible to have the dialog open, and in another tab, open the tos link and try to open another dialog.

**Comment by jedp** [comment]
Compare Issue #3360

**Comment by callahad** [comment]
Closing. This specific case has been resolved since the ToS and PP pages do not have sign in links anymore.
