### ISSUE TITLE
confirm email link page is all white with no error on screen

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3362]
1. goto beta.123done.org
2. enter a non-yahoo email to sign in
3. check email and click on link to confirm acct, 
4. refresh that link again to show the error

result:
https://login.anosrep.org/confirm?token=MOtSNLkrerOFiEopGGLIafEiJPrTL9T4vRxhCDzJh5Ut0pad
I think this might be the issue:
<body class="loading" style="display: none;">

expected:
https://login.persona.org/confirm?token=MOtSNLkrerOFiEopGGLIafEiJPrTL9T4vRxhCDzJh5Ut0pad

**Comment by edwindotcom** [comment]
related to #3363 , could be duped - but will leave it for now.

**Comment by shane-tomlinson** [comment]
I theorize this is a result of #3262.

**Comment by shane-tomlinson** [comment]
@edmoz - the `confirm` link leads me to believe this is not a user creation, but an email addition, a reverification or the staging of an unverified user. Did you open the verification link in the same browser or a different browser?

**Comment by shane-tomlinson** [comment]
@edmoz - so far, I have been unable to reproduce this.

**Comment by shane-tomlinson** [comment]
ahha - I have reproduced. This is the case if you re-open a link that has already been verified. An edge case, but should be handled. Bumping to 5\* since this is a regression (even if it is a long standing one).
