### ISSUE TITLE
Confirmation page with unknown/incorrect token leads to a blank, dead page.

### ISSUE THREAD

**Issue by karlht** [mozilla/persona#3363]
STR:
1. Pop a dialog from beta.123done.org.
2. Enter an email address and then click 'forgot password'
3. Copy and paste the URL from the email, but omit the last character in the token.

Expected:
1. Error message: 'Invalid token.'

Actual:
1. An all-white page (body element is styled 'display: none')

**Comment by karlht** [comment]
I suspect this is what is causing #3362, as well, because the token is known to persona.org but not to anosrep.org.

**Comment by shane-tomlinson** [comment]
Closing as dup of #3362.
