### ISSUE TITLE
eyedee.me not working as a primary idP right now

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3364]
looks like something is wrong with eyedee.me.  This blocks automation.
1. sign into {www,beta}.123done.org
2. enter an user@eyedee.me acct

result: you're asked for email, then to confirm via email

expected: you should be redirected to eyedee.me if new acct, other wise verified inline

**Comment by jrgm** [comment]
The SSL certificate issued by Godaddy expired earlier today.

**Comment by lloyd** [comment]
Shit.  I can fix this.

-- lloyd (thumb-typing)

**Comment by lloyd** [comment]
resolved.
