### ISSUE TITLE
sign in button never loads on dev.123done.org

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3365]
1. goto: http://dev.123done.org/

actual: the sign in button displays loading spinner, and never loads

-- after a long time, you see this in console:
[13:57:52.637] TypeError: navigator.id is undefined @ http://dev.123done.org/js/123done.js:14

expected: it should load

**Comment by lloyd** [comment]
login.dev.anosrep.org is down right now.

my DNS provider was under DDoS attack earlier and now I'm unable to update DNS.

this bug is invalid I think, underlying problem is dev is down.

**Comment by lloyd** [comment]
just sent a message to zerigo support, should be resolved shortly
