### ISSUE TITLE
stage_user with allowUnverified throws a 400

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3366]
Seems like this got bruised up a bit in the big merge

Blocks b2g and marketplace

**Comment by shane-tomlinson** [comment]
I cannot get this to occur locally. You mentioned this might have something to do with app:// domains?

**Comment by shane-tomlinson** [comment]
@jedp - could this be related to #3368, which is another issue that I cannot reproduce locally because it only happens with a mySQL database?

**Comment by jedp** [comment]
This was me being a moron.  I had a bad parameter name.  closing as invalid.
