### ISSUE TITLE
Ensure that Mozilla properties are not using the old browserid.org URLs

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3367]
Chris More reports that the following sites still contain the string `browserid.org`:
- [ ] affiliates.mozilla.org
- [ ] air.mozilla.org
- [ ] builder.addons.mozilla.org
- [ ] gameon.mozilla.org
- [ ] identity.mozilla.com
- [ ] metrics.mozilla.com
- [ ] mozillalabs.com
- [x] moztrap.mozilla.org
- [ ] quality.mozilla.org
- [ ] reps.mozilla.org
- [ ] status.mozilla.com

(from https://wiki.mozilla.org/Websites/Domain_List/Mozilla_Prod_Owned)

**Comment by callahad** [comment]
(I added checkboxes)

**Comment by chrismore** [comment]
Can we file bugs for each of the websites in the appropriate components in Bugzilla?

Affiliates: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20Affiliates&component=affiliates.mozilla.org

Air: https://bugzilla.mozilla.org/enter_bug.cgi?product=Air%20Mozilla&component=Other

Mozilla labs: https://bugzilla.mozilla.org/enter_bug.cgi?product=Websites&component=mozillalabs.com

Reps: https://bugzilla.mozilla.org/enter_bug.cgi?product=Mozilla%20Reps&component=reps.mozilla.org

status: https://bugzilla.mozilla.org/enter_bug.cgi?product=mozilla.org&format=itrequest and have them change it to persona.org.

Quality: https://bugzilla.mozilla.org/enter_bug.cgi?product=quality.mozilla.org&component=Website

@rossbruniges -- Where do you file bugs for gameon?

@benadida -- Do you want to edit some of the older blogs with links to browserid.org on identity.mozilla.com blog?

@DEinspanjer -- Where should we file the metrics.mozilla.com bug?

@camd -- Where should bugs be filed for moztrap.mozilla.org?

**Comment by chrismore** [comment]
Just as a note to some of the people mentioned above, @fmarier is asking for these changes:

We will remove support for the following deprecated URLs by November
1st, 2013:

https://browserid.org/include.js
https://browserid.org/verify

Now would be a good time to update your applications, libraries and
sites to the correct URLs:

https://login.persona.org/include.js
https://verifier.login.persona.org/verify

(Note that https://login.persona.org/verify is NOT valid.)

**Comment by camd** [comment]
I fixed MozTrap and pushed it out today.  So hopefully you can take me off your list.  :)

Though if you DID want to enter a bug on MozTrap:
https://bugzilla.mozilla.org/enter_bug.cgi?component=MozTrap&form_name=enter_bug&product=Mozilla%20QA

**Comment by seanmonstar** [comment]
Also https://builder.addons.mozilla.org! (which also uses the getVerifiedEmail() API, eep!)

**Comment by rossbruniges** [comment]
mozilla.org/gameon is where to file the gameon bugs

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
