### ISSUE TITLE
B2G Metrics

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3373]
It would be great if we could be tracking B2G persona accesses when it goes to market.

As long as B2G isn't on its own isolated server, I believe it will show up in router-metrics, identifiable by the browser. I don't think we can currently identifiy verifier hits that are from B2G. With auto-login, we don't see a hit in router-metrics for every login.
- Do we want/need additional B2G metrics to count hits beyond calls to signin?
- Will B2G be on the main persona service before it goes to market?

If the answers are No and Yes, we can just close this bug.

**Comment by jedp** [comment]
@jedp ought to do something

**Comment by kparlante** [comment]
The coarse_user_agent_parser needs to be modified for KPI blobs to be able to segment B2G blobs by browser/OS: https://github.com/mozilla/browserid/blob/dev/lib/coarse_user_agent_parser.js

#kparlante will handle the changes needed on the dashboard side: https://github.com/mozilla/kpi-dashboard/issues/45

The pentaho dashboards will get the user-agent header as is, no changes required: https://github.com/mozilla/browserid/blob/dev/lib/metrics.js (@kparlante will double check that the pentaho/metrics dashboards will indeed show the new browser/os and not process it out).

@jedp may have something else up his sleeve as well...

**Comment by kparlante** [comment]
FWIW, the Firefox OS user agent string: http://lawrencemandel.com/2012/07/27/decision-made-firefox-os-user-agent-string/ TL;DR: `Mozilla/5.0 (Mobile; rv:18.0) Gecko/18.0 Firefox/18.0`

**Comment by kparlante** [comment]
@shane-tomlinson : make sure the Firefox OS shows up in KPIs
