### ISSUE TITLE
pt-BR translation needed for tos/pp

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3375]
It seems we never got the persona tos and pp translated into Brazilian Portugese.

This will be a blocker for Marketplace going to market in June, so if we can get this landed in dev in the next two weeks, I think we should make it.

**Comment by shane-tomlinson** [comment]
@mathjazz, @jedp - I was once told that we have to have special legal translators for TOS/PP text.

**Comment by Pike** [comment]
We're generally not translating any of our privacy policies and the like.

**Comment by ozten** [comment]
@pike thanks for you help. From a B2G partner perspective... we are okay? This isn't a shipping blocker?

**Comment by jedp** [comment]
Update - Axel says that traditionally we don't do this.  Ozten has a question in with Jishnu as to what legal wants. Waiting to hear back.

**Comment by ozten** [comment]
Via phone, Jishnu says these will need to be localized.

Per [bug#873241](https://bugzilla.mozilla.org/show_bug.cgi?id=873241)...

Persona TOS/PP are only in English and hosted on the Persona public website which has no localization. The dialog is localized, of course, but not the stand-alone pages.

We need to support localized TOS and PP for some locales. If a localized version doesn't exist, en-US should be used.

Proposed Changes:
1) TOS / PP will be localized as HTML files (not via `gettext`)
2) URLs to TOS / PP will include a locale code
3) TOS / PP tempalates should be moved into a locale based directory structure

```
resources/views/tos.ejs
```

might become

```
resources/views/en_US/tos.ejs
```

We'll verify these details in 873241.

CC @mathjazz

**Comment by ozten** [comment]
Ideally this would be done by 5/22 with 6/5 being the latest to make the next train (via lloyd on IRC)

**Comment by mathjazz** [comment]
@ozten, this sounds good. Could you give me access to bug 873241 (m@owca.info)?

**Comment by ozten** [comment]
You betcha.

**Comment by mathjazz** [comment]
Thanks.

**Comment by ozten** [comment]
I think we can get away with not localizing the header and footer of the public website.

Background:
On the device, when you click TOS or PP, it loads just that partial document into the trusted window.

On a web browser, when you click TOS or PP, it opens a new tab/window and loads the entire persona page which includes non-localized header and footer.

**Comment by ozten** [comment]
Started a [branch off of b2g](https://github.com/mozilla/browserid/compare/b2g...issue-3375-localize-tospp).

Design:
Terms of Service (TOS) moved to `resources/views/en/tos.ejs`.
Privacy Policy (PP) moved to `resources/views/en/privacy.ejs`.

On server startup we record which locales are supported for each document. Fallback is `en`.

For a given locale, say Spanish (es) we'd do this...

```
cp resources/views/en/tos.ejs resources/views/es/tos.ejs
cp resources/views/en/privacy.ejs resources/views/es/privacy.ejs
```

We'd get those two new `.ejs` files localized and commited to git.

**Comment by mathjazz** [comment]
@ozten, when I open https://www.persona.org/tos in Firefox in Slovenian (sl), I see header and footer localized:
http://cl.ly/image/0X260a0Q3Y1D

**Comment by shane-tomlinson** [comment]
@ozten, @mathjazz - Headers and footers are indeed translated, I imagine no extra work needs to be done for those.

**Comment by ozten** [comment]
@mathjazz - Oh, awesome! Thanks @shane-tomlinson

**Comment by ozten** [comment]
Tauni is going to follow up with Jishnu, as there hasn't been a concrete plan updated in the bug#873241.

**Comment by shane-tomlinson** [comment]
@ozten, @mathjazz - Do we need these translated into the newly divulged languages as well?

**Comment by jaredhirsch** [comment]
@ozten @mathjazz So, we just recently merged in Spanish TOS/PP (#3604) and that bug referred to bugzilla#873241, has there been any movement on pt-BR? (I don't have access to the bugzilla bug)

**Comment by ozten** [comment]
Nope. I've CC'd you.

**Comment by jaredhirsch** [comment]
closing in favor of bugzilla bugs, all the action's happening over there.
