### ISSUE TITLE
b2g: closing nativeUI does not cause sign in button to be enabled on mfb.com

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3377]
1. goto dev.myfavoritebeer.org
2. click on sign in button
3. click 'X' to cancel out of native UI

result: sign in button is disabled and greyed out
expected: it should be enabled and not greyed out

**Comment by jedp** [comment]
The dialog subscribes to `window.close` events, and sends a close command when it receives one.  But there are no `window.close` events on b2g.  So it would appear the solution will require some work both on the platform side and in the dialog.

Note that an RP using the observer API will receive the `cancel` event and have its `oncancel` callback invoked if someone closes the trusted UI.  So this issue affects specifically non-observer RPs.

**Comment by jedp** [comment]
Actually, the way we implemented `get` in the native api looks like this actually should work.  @ozten and I are investigating now.

**Comment by jedp** [comment]
I think I see what i did wrong with the native `get` cancel.

**Comment by jedp** [comment]
Sorry I didn't close sooner.  This has been fixed.
