### ISSUE TITLE
b2g: sign in via bigtent results in json parse error

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3378]
1. on b2g goto dev.123done.org
2. sign in with user@yahoo.com

result: upon signing in to yahoo page, i get the error parse json error

After i close the window - i'm logged in

**Comment by edwindotcom** [comment]
![2013-05-08-15-28-58](https://f.cloud.github.com/assets/3698618/480477/ac258cde-b830-11e2-8129-74694f74d93c.png)

**Comment by edwindotcom** [comment]
this is the same on www.123done.org with browser based persona (not native UI)

**Comment by jedp** [comment]
Current plan is to disable federation on b2g v1

**Comment by edwindotcom** [comment]
primary sign in is not supported on b2g - closing
