### ISSUE TITLE
Always call onlogout when navigator.id.logout is called

### ISSUE THREAD

**Issue by Osmose** [mozilla/persona#3379]
Currently, when `navigator.id.logout` is called while the user doesn't have an active Persona session, the `onlogout` callback isn't run. Because of this, there's no way to write code that is guaranteed to run _after_ `navigator.id.logout` finishes (unless logout is synchronous and I'm missing that fact).

My suggestion is to always run `onlogout` when `navigator.id.logout` is called, perhaps with a parameter that signals if the logout was successful or not. There's still some discussion on the list about whether this is the right way to go, but @benadida wanted to have an issue to track it, so here you go. :)

**Comment by mattbasta** [comment]
don't want to say that I already filed this bug...[but I already filed this bug](https://github.com/mozilla/browserid/issues/3229).

;)

**Comment by shane-tomlinson** [comment]
Thanks @mattbasta, I was looking for that. Closing as dup. @Osmose, can you pile on in the other?
