### ISSUE TITLE
Typo in micrajax breaks support for IE8 without native XMLHTTP support

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3383]
There is a typo in [micrajax](https://github.com/mozilla/browserid/blob/2a638af0190162fc3480ed07458e66013d7ec775/resources/static/common/js/lib/micrajax.js#L27):

```
new ActiveXObject('Microsoft.XM/LHTTP');
```

should be:

```
new ActiveXObject('Microsoft.XMLHTTP');
```

It looks like the spurious slash was introduced in e00740316ccf61f60f6efc29905da6d039178fc8.

**Comment by jaredhirsch** [comment]
persona doesn't work on IE older than 8 because we assume window.postMessage is defined, I think we don't need to worry about this.

**Comment by fmarier** [comment]
There is an option called "Enable native XMLHTTP support" which disables `window.XMLHttpRequest` but still allows old-style XHRs.

So we should re-enable that ActiveX fallback to support these IE8 users that have that setting.

**Comment by fmarier** [comment]
This is how I found out about this problem. A user opened my [Persona troubleshooting page](https://github.com/fmarier/persona-troubleshoot) and got this:
![ie8_broken_xhrs](https://f.cloud.github.com/assets/167821/499160/99367a86-bc2f-11e2-9145-e2f2322b179b.png)

This shows that while `window.XMLHttpRequest` is not defined, XHRs work fine through jQuery 1.x.
