### ISSUE TITLE
Users cannot log out

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3386]
We're seeing that calling `navigator.id.logout()` no longer logs the user out. You can see it for yourself:
1. Visit marketplace-dev.allizom.org
2. Sign in with Persona
3. Sign out (hover over the gear in the upper right)
4. Refresh the page

We're calling `navigator.id.watch()` with a blank string for the email and on sign out we're calling `navigator.id.logout()`, and yet Persona still magically fires `onlogin` with an assertion when the page loads.

**Comment by seanmonstar** [comment]
Is there another step or detail? Following the steps listed doesn't show me the issue. I log in fine, and then click Sign out, and upon refresh, I'm still logged out.

**Comment by mattbasta** [comment]
Try a second time? Perhaps @cvan or @krupa can give some additional information. If you're in MV, I can walk you through the code and show you on my machine.

**Comment by mattbasta** [comment]
I'm able to reproduce this on Chrome Beta as well as Firefox Nightly, so it's not just me being a silly sally. cvan and Krupa were purportedly able to repro it on their machines as well.

**Comment by seanmonstar** [comment]
I don't assume any silly sallys. I've just tried it a couple times, and haven't seen it, so I wondered if there's a step I'm missing... I've been trying on Nightly, I'll give it a go in Chrome.

**Comment by callahad** [comment]
I can't reproduce this -- what page am I supposed to be on? I'm trying logging in and out a bunch on https://marketplace-dev.allizom.org/developers/

**Comment by jedp** [comment]
I also can't reproduce this.  Since you're using marketplace-dev, you're currently hitting native-persona.org.  To test that, you can use this: http://people.mozilla.org/~jparsons/test_b2g.html

To test:
1. Sign in
2. Reload the page; I am automatically signed in
3. Logout
4. Reload the page; I am not signed in; I get a ready message.

Matt, do you have more context? Logs?

**Comment by mattbasta** [comment]
This won't affect /developers since that code uses a different set of login scripts.

marketplace-dev only loads native-persona.org if it detects Firefox OS, so if you're testing on desktop, you'll be hitting the normal Persona URLs.

I just committed some extra logging code (and refactoring, for ease of code reading) to marketplace-dev. You can see the following things in the logs:

On log out:

```
[user] Clearing user token
[user] Saving settings to localStorage
[mkt] Reloading chrome
[previews] Populating trays
[login] Triggering Persona logout 
```

On refresh:

```
Mozilla(R) FP-MKT (R) 1.0
   (C)Copyright Mozilla Corp 1998-2013

64K High Memory Area is available.
Templates loaded
[model] Stored all as category
[req] GETing https://marketplace-dev.allizom.org/api/v1/apps/category/?dev=desktop&format=json&lang=en-US&pro=3040fe.32.1&region=us

... snip ...

[mkt] Initialization complete
[login] No previous user detected
[login] Calling navigator.id.watch

... snip ...

[login] Got assertion from Persona
[req] POSTing https://marketplace-dev.allizom.org/api/v1/account/login/?dev=desktop&format=json&lang=en-US&pro=3040fe.32.1&region=us
[req] POSTed https://marketplace-dev.allizom.org/api/v1/account/login/?dev=desktop&format=json&lang=en-US&pro=3040fe.32.1&region=us
[user] Setting new user token
[user] Updating user settings Object {display_name: "mattbasta2", email: "mattbasta@gmail.com"}
[user] Saving settings to localStorage
[login] Login succeeded, preparing the app
[mkt] Reloading chrome
[previews] Populating trays
[login] Resolving outstanding login requests 
```

**Comment by mattbasta** [comment]
You can trace the code here:

https://github.com/mozilla/fireplace/blob/master/hearth/media/js/login.js#L34
https://github.com/mozilla/fireplace/blob/master/hearth/media/js/login.js#L61
https://github.com/mozilla/fireplace/blob/master/hearth/media/js/login.js#L128

**Comment by jedp** [comment]
64k High Memory Area is available.  Awesome :)

I've tried the STR again and still it isn't broken for me.  I've ended up here from desktop firefox: https://marketplace-altdev.allizom.org/category/all/featured?src=category-featured (that's correct, isn't it?)

 (I've also double checked the latest v1.0.1 unagi build on b2g, just to make super double sure that logout is logging out on device as well as desktop.)

I'm wondering whether we're testing the same thing.  I see in your code you console.log "Got assertion from persona" in `gotVerifiedEmail`, but my console never shows that message after logging in successfully.  Should I be seeing "Got assertion from persona" after any login in my firefox console?

**Comment by cvan** [comment]
You should be trying on https://marketplace-dev.allizom.org/ (not -altdev).

As a shortcut to installing Marketplace Dev, you can use [this page here](http://people.mozilla.org/~cwiemeersch/mktdev.html).

**Comment by cvan** [comment]
Heh, this is what I see right now:

![](http://f.cl.ly/items/46111T0u1M3r1j0l2t11/Screen%20Shot%202013-05-13%20at%208.24.33%20PM.png)

**Comment by jedp** [comment]
Hi, @cvan,

altdev is what krupa originally reported in https://bugzilla.mozilla.org/show_bug.cgi?id=869258 where she provided STR.  I don't know the difference between altdev and dev.  Which persona services do they use?

I just instlalled mktdev from the link you provided (is that different from ~kmcmillan/mktdev.html?) on a v1.0.1 unagi build from today, and I can't reproduce the problem initially reported, or the blank screen in your comment.

In your desktop build, can you pref on `toolkit.identity.debug`?  That will provide verbose logging for Persona.  Hopefully that will help us get to the bottom of this.

Cheers
j

**Comment by ozten** [comment]
Can we jump in a Vidyo and step through via screenshare?

**Comment by cvan** [comment]
> Hi, @cvan,
> 
> altdev is what krupa originally reported in https://bugzilla.mozilla.org/show_bug.cgi?id=869258 where she provided STR. I don't know the difference between altdev and dev. Which persona services do they use?

We don't update -altdev anymore. -altdev is updated via manual pushes. -dev is updated automatically whenever new code lands on mozilla/fireplace.

Same Persona services.

> I just instlalled mktdev from the link you provided (is that different from ~kmcmillan/mktdev.html?) on a v1.0.1 unagi build from today, and I can't reproduce the problem initially reported, or the blank screen in your comment.

Mine's better than Kumar's.

> In your desktop build, can you pref on toolkit.identity.debug?

Well so the thing is I can reproduce this on desktop (not using native Persona) in both Chrome and Firefox (stable and Nightly).

> That will provide verbose logging for Persona. Hopefully that will help us get to the bottom of this.

I can do that. @mattbasta: you can repro on desktop, yeah?

**Comment by mattbasta** [comment]
I've reproduced (and am presently reproducing here at home) the issue on
-dev. Functionally, -dev and -altdev are identical, except -altdev is
currently about a week behind. I wouldn't trust it for anything right now;
-dev reflects our current master branch.

Both -dev and -altdev will use native-persona when navigator.mozApps is
present, "Mobile" is in the UA, and "Android" is not in the UA. Otherwise,
they use standard Persona. This means that any B2G build (on-device or on
the desktop) will get Marketplace with native-persona, and any desktop
browser will see standard Persona.

**Comment by mattbasta** [comment]
Some debugging that I've done:
- I can't reproduce in Chrome's incognito mode
- In incognito, I notice that the localStorage for persona has an extra value "`loggedIn`"
- Upon manually triggering `navigator.id.logout()` via the console, `loggedIn` does not drop its `marketplace.firefox.com` field.
- Deleting the `loggedIn` field outside of incognito solves the problem and the Marketplace and Persona behave as they should.

**Comment by jedp** [comment]
Thanks @cvan and @mattbasta for the clarification about -dev.  I'll stick to that.  If one of you can pastebin up some logs with `toolkit.identity.debug` preffed on, that would be a huge help.  There should be a line in the logs that declares `persona uri = x.y.z`; please paste that line and everything after it.  Thanks!

**Comment by cvan** [comment]
I can't reproduce this in desktop b2g. Just on desktop.

If you're curious here are screenshots from my desktop b2g build, which works fine logging in/logging out:

http://cl.ly/image/0f3G2X0A2G0D
http://cl.ly/image/2Q2l0o1a3M1g
http://cl.ly/image/1X0k092n3n0O

Hmm, @mattbasta, might this be from the issue when our JS was being duplicated and initialized 11 times? I thought this to be the problem. Cleared my cookies and cache - still occurring.

Interestingly, in Safari (which I haven't used until this very moment lol) I cannot reproduce this issue.

I'm inclined to think this is some weird issues we caused when over the weekend -dev was initializing Persona 11 times per page load.

**Comment by seanmonstar** [comment]
I was wondering if it might be something cached. Since it seems new
browser's aren't hitting it?

**Comment by callahad** [comment]
Could this be related to what Pwnna was seeing in IRC [last night](http://irclog.gr/#show/irc.mozilla.org/identity/259627)? Persona worked fine on other sites for him, but on his own site `.logout()` wasn't clearing the logged in value. Clearing localStorage solved it for him, but now I'm a bit uncomfortable if this has happened to two people...

**Comment by mattbasta** [comment]
When I get into the office, I'll inspect that mystery key on the
login.persona.org origin for you guys. I'll also dive a bit deeper into
include.js and the session_context stuff to see where it comes from.

Perhaps the loggedIn key is a relic from a previous push that's only read
and not written now?

**Comment by seanmonstar** [comment]
I feel I remember @stomlinson saying there was a recent change the
localStorage structure, specifically where loggedIn is stored. I'm going to
assume it's related. Will look at commits when I get to the computer.

**Comment by cvan** [comment]
I just cleared `localStorage` and that enabled me to log out. Hmmm, do we know which keys/values were causing issues here?

**Comment by shane-tomlinson** [comment]
@seanmonstar - AGH! I see the problem. When I upgraded from loggedIn to use the site namespace, I automatically upgrade the logged in info without clearing the original cache. The next time the user returns, it re-upgrades the site info from loggedIn, effectively re-signing in the user.

**Comment by kumar303** [comment]
Thanks for the fix! When could we expect this to land in firefoxos.persona.org?
