### ISSUE TITLE
Native persona sign in fails with a 400 to POST /wsapi/cert_key

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#3399]
## Preconditions
1. Tester is on the latest 1.0.1 build on their unagi device.
2. Tester has marketplace-stage installed
## Steps to reproduce
1. Launch marketplace-stage app on your Firefox OS phone
2. Navigate to the details page of a paid app like Private Yacht
3. Click the Purchase button
4. Persona sign in screen loads within the trusted UI
5. Sign in using valid credentials
## Expected behavior

Sign in is successful
## Actual behavior

Sign in fails with "We are very sorry. There has been an error!"
Action: Getting Assertion
Network info: POST: /wsapi/cert_key

POST /wsapi/cert_key returns HTTP/1.1 400 Bad Request

http logs: http://www.pastebin.mozilla.org/2403854

**Comment by edwindotcom** [comment]
I'm not able to repro with native.123done.org on, though things were really slow the first time.
Gecko  http://hg.mozilla.org/releases/mozilla-b2g18_v1_0_1/rev/b0b2b5cfdc5b
Gaia   30ad443fbe5363a7381c19c6bf9d6ca49228fb8b
BuildID 20130509070209
trying a newer build

**Comment by jedp** [comment]
This should be fixed now.  @krupa, is it still failing on you?

**Comment by krupa** [comment]
works now, thanks!

**Comment by jrgm** [comment]
taking @krupa's coment as a reason to close this bug.
