### ISSUE TITLE
persona sign-in dialog from marketplace uses off-center spinner

### ISSUE THREAD

**Issue by wfwalker** [mozilla/persona#3404]
when I try to log into marketplace on my unagi, the spinner i see is off-center, looks like a mistake. To quote Jed Parsons, "it looks like someone twirling a frisbee around their finger.

I attach a screenshot, but it doesn't really give a flavor of the experience.

![2013-05-14-14-39-20](https://f.cloud.github.com/assets/812428/504197/d734df70-bcdf-11e2-926d-bd473fc56aba.png)
"

**Comment by kumar303** [comment]
In case it helps, I'm seeing this on today's 1.0.1 unagi build. Maybe some assets aren't loading? Also, note that this is loading from firefoxos.persona.org which is why people are seeing the new UI now

**Comment by edwindotcom** [comment]
no assets are missing - this is the new UI I believe.  But it is a bit distracting.

**Comment by jedp** [comment]
Yes, this is the new UI.  I agree with Bill; it's just a little bit wobbly; the center of rotation doesn't seem to be the center of the image

**Comment by lloyd** [comment]
We could patch in a new asset if one was provided.

-- lloyd (thumb-typing)

**Comment by shane-tomlinson** [comment]
@wfwalker - do you have an image I can use? I got this one directly out of the mocks I was sent.

**Comment by kumar303** [comment]
@muffinresearch may be able to help. He implemented very similar UX mocks in [webpay](https://github.com/mozilla/webpay/blob/master/media/css/pay/throbber.less)

**Comment by muffinresearch** [comment]
Here's the css from the webpay throbber which was lifted from what we use on fireplace.

https://github.com/mozilla/webpay/blob/master/media/css/pay/throbber.less

**Comment by shane-tomlinson** [comment]
@muffinresearch, @kumar303, @mattbasta - have I mentioned that you guys have been awesome with all the help?

**Comment by edwindotcom** [comment]
just a note - using a b2g phone a fair amount, there's a spinner that looks similar but it's about 24x24 px, I'm not sure if we want to match that size to be more consistent with the b2g OS.  I may log a new bug for that since we're looking at UX right now

**Comment by kumar303** [comment]
Yeah, I was thinking the same thing. The UI should be consistent across Persona, Webpay, and Bango.

**Comment by shane-tomlinson** [comment]
@edmoz, @kumar303 - I updated the spinner from the CSS that @potch sent me. This has not made its way to beta yet but can be seen on all-together-now.personatest.org
