### ISSUE TITLE
UX input for marketplace Terms & Policy section

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#3413]
The new persona sign in screen has the Marketplace Terms & Policy section at the top. We should consider moving to a different screen like the mostly-empty Sign in screen or at least make it less space consuming.

Maureen can probably pitch in here.

**Comment by mhanratty** [comment]
Let's add the Terms and Privacy Policy for Marketplace directly underneath the Persona terms.

![screen shot 2013-05-15 at 3 28 08 pm](https://f.cloud.github.com/assets/4432402/509769/e541868e-bdae-11e2-9c99-0d004e92f921.png)

**Comment by jedp** [comment]
/cc @skinny97214 

I think the new string will require localization, too.

**Comment by shane-tomlinson** [comment]
@mhanratty - this has a side effect on the "email picker" screen. If the user has not previously visited the site they are trying to sign in to, the site's TOS/PP agreement must be shown. I will try to use the pattern shown here for that purpose too.

**Comment by jedp** [comment]
@jedp to drop some screenshots from the ephemeral instance into this bug so @skinny97214 and @mhanratty can take a look at it.
