### ISSUE TITLE
Persona loading screen persists after the user is already logged into Marketplace

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#3414]
## Steps to reproduce
1. Tester is not logged in
2. Launch marketplace-dev app on your 1.0.1 unagi phone
3. Navigate to the details page for any app
4. Click on the "Write a review" button
5. Persona sign in screen loads.
6. Log in using valid credentials
## Expected behavior

Focus returns to Marketplace after the user is signed in
## Actual behavior

Persona loading screen persists after the user is already logged into Marketplace

http://www.pastebin.mozilla.org/2408026

screenshot:
![2013-05-15-15-48-45](https://f.cloud.github.com/assets/301317/510048/c7c25baa-bdb9-11e2-89dd-cc5a5d500dc8.png)

**Comment by jedp** [comment]
Thanks for the screenshot and the logs.  Investigating.

**Comment by jedp** [comment]
Assigning five stars

**Comment by jedp** [comment]
@krupa notes in addition that the login is successful, but the UI persists nonetheless

**Comment by edwindotcom** [comment]
I repro'd this on my inari

**Comment by jedp** [comment]
And i'm seeing it on unagi with today's v1.0.1 build

**Comment by jedp** [comment]
Here are the logs from the end of the sign-in process (with `toolkit.identity.debug` preffed on)

```
I/Gecko   (  410): Identity DOMIdentity: doLogin: {b601f365-846d-4104-94a7-3a2b29972f12}
E/GeckoConsole(  410): Identity DOMIdentity: doLogin: {b601f365-846d-4104-94a7-3a2b29972f12}
I/Gecko   (  410): Identity SignInToWebsiteController: telling gaia to close the dialog
E/GeckoConsole(  410): Identity SignInToWebsiteController: telling gaia to close the dialog
D/memalloc(  410): /dev/pmem: Allocated buffer base:0x4aa00000 size:36864 offset:1708032 fd:147
D/memalloc(  621): /dev/pmem: Mapped buffer base:0x45200000 size:1744896 offset:1708032 fd:53
D/memalloc(  410): /dev/pmem: Allocated buffer base:0x4aa00000 size:36864 offset:8351744 fd:224
D/memalloc(  621): /dev/pmem: Unmapping buffer base:0x46589000 size:8052736 offset:8015872
I/GeckoDump(  410): XXX FIXME : Got a mozContentEvent: undefined
D/memalloc(  410): /dev/pmem: Freeing buffer base:0x4b1a5000 size:36864 offset:8015872 fd:238
D/memalloc(  410): ashmem: Freeing buffer base:0x42763000 size:36864 fd:244
D/memalloc(  410): ashmem: Unmapping buffer base: 0x42763000 size: 36864
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [login] Got assertion from Persona
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [req] POSTing https://marketplace-dev.allizom.org/api/v1/account/login/?dev=firefoxos&lang=en-US&pro=fbff7fdc.32.1&region=us
D/memalloc(  622): ashmem: Unmapping buffer base: 0x42405000 size: 405504
D/memalloc(  410): ashmem: Freeing buffer base:0x442e8000 size:405504 fd:225
D/memalloc(  410): ashmem: Unmapping buffer base: 0x442e8000 size: 405504
D/memalloc(  410): /dev/pmem: Freeing buffer base:0x4b0df000 size:405504 offset:7204864 fd:151
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [req] POSTed https://marketplace-dev.allizom.org/api/v1/account/login/?dev=firefoxos&lang=en-US&pro=fbff7fdc.32.1&region=us
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [user] Setting new user token
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [user] Updating user settings [object Object]
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [user] Saving settings to localStorage
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [login] Login succeeded, preparing the app
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [mkt] Reloading chrome
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [login] Page requested reload on login
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [views] Reloading current view
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [req] Opening pool
E/GeckoConsole(  539): Content JS LOG at https://marketplace-dev-cdn.allizom.org/media/fireplace/js/include.js?b=7e8af9d:1507 in anonymous: [req] Closing pool
```

The `FIXME : Got a mozContentEvent: undefined` is ignorable.  It's gaia complaining that there's no `type` attribute on our event, which is technically ok, but stylistically needs to be fixed.

`telling gaia to close the dialog` is the crucial line; that means that the native identity code is sending a message to the trusted ui to close.  I'm investigating now to make sure that this message is correct.

**Comment by kumar303** [comment]
The logs indicate that this might be a Fireplace issue not a Persona issue.

**Comment by kumar303** [comment]
Another clue that suggests this is Fireplace related is that this is only broken when clicking the Write Review button to log in. I can log in without error via the settings screen and when clicking purchase on an app.

**Comment by jedp** [comment]
I added logging to the gaia apps `apps/system/js/identity.js` (which governs the identity bit that shows up in the trusted ui, and which receives the close message), and `apps/system/js/trusted-ui.js`, which controls the trusted ui itself.

It looks like the message is getting through.  Digging deeper into the trusted ui and ensuring our IDs line up.

**Comment by krupa** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=872849 against Fireplace. Thanks for the help and sorry about the scare.

**Comment by jedp** [comment]
Perhaps noteworthy: when i install mktdev, the icon does not show up on the screen until i reboot the phone or restart the desktop.

**Comment by jedp** [comment]
krupa thanks for filing that bug, but i'm still scared :)  I don't see how we can send a close dialog message to the trusted ui and not have it close.  Still digging.

**Comment by jedp** [comment]
Moving my comments over to the bug krupa opened,  https://bugzilla.mozilla.org/show_bug.cgi?id=872849. I want to make damn sure this isn't a platform bug we're looking at.

**Comment by jedp** [comment]
this has been resolved as an issue with fireplace firing two request() calls nearly simultaneously.  Logs and documentation are attached to  https://bugzilla.mozilla.org/show_bug.cgi?id=872849

fireplace sha: https://github.com/mozilla/fireplace/commit/ab1e8e29d7abbc333e9312c32ca8089b85064b12

Bugzilla calls the issue resolved=fixed, so closing this

**Comment by kumar303** [comment]
It seems like maybe Persona should create a lock and disallow multiple calls to request() or something. It shouldn't be this easy to put Persona into an unusable state.

**Comment by ozten** [comment]
Good point, we should bulletproof the API where possible.
