### ISSUE TITLE
frontend tests failing on login.dev.anosrep.org with a real browser

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3424]
There's at least a typo here - https://github.com/mozilla/browserid/blob/dev/resources/static/test/cases/dialog/js/misc/state.js#L578

But with that url quoted correctly locally, there is still a test failure - 

http://127.0.0.1:10002/test/?filter=dialog%2Fjs%2Fmodules%2Fauthenticate%3A%20authentication%20form%20initialized%20on%20startup%2C%20hidden%20on%20stop

It passes in the phantomjs tests though, perhaps because it is skipped (?).

**Comment by jrgm** [comment]
So the PR above is merged to fix the typo. 

But the test failure remains - https://login.dev.anosrep.org/test/?filter=dialog%2Fjs%2Fmodules%2Fauthenticate%3A%20authentication%20form%20initialized%20on%20startup%2C%20hidden%20on%20stop

Actually, if you load that URL and quickly bring another window to the foreground, the tests will pass because the focus check is skipped (similar to what makes this test pass with headless phantomjs).

**Comment by shane-tomlinson** [comment]
Nice find @jrgm, this test failure brings up a real issue - the email field was not being focused on dialog startup.
