### ISSUE TITLE
Footer text is microscopic

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3426]
http://cl.ly/image/0R3H3O360k1a

**Comment by jaredhirsch** [comment]
@mattbasta I can't repro this. What browser/OS?

**Comment by mattbasta** [comment]
Chrome Beta on 10.6.8

**Comment by edwindotcom** [comment]
resize the dialog a few times as it re-flows.  I'm on chrome release and dan repro'd with FF

**Comment by jaredhirsch** [comment]
This is totally my fault. I added a clever routine to shrink the footer when we're in German and overflowing boundaries, but I didn't set a legible lower bound. Lemme fix real quick.
