### ISSUE TITLE
[b2g] B2G apps use Feura Sans font set, not Open Sans

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3430]

**Comment by shane-tomlinson** [comment]
Using the natively installed fonts should give us performance wins too.

**Comment by shane-tomlinson** [comment]
@skinny97214, @mhanratty - Once all the various styling changes are merged, including the change to Feura Sans, the dialog looks like this:

![screen shot 2013-05-17 at 13 39 05](https://f.cloud.github.com/assets/848085/517941/5341c054-beef-11e2-8561-4a6bf02f5aa5.png)

The title seems squashed, is there a style guide saying what the letter spacing should be for Feura Sans and the verious headers?

**Comment by seanmonstar** [comment]
Seems odd to not have the Persona branding. When I see this, I just wonder what Persona possibly refers to.

**Comment by skinny97214** [comment]
@shane-tomlinson Hold off on this until we get confirmation from that team that the whole flow is using Feura.

**Comment by mhanratty** [comment]
We want to use the default font that Gaia uses which is Feura Sans.
