### ISSUE TITLE
[b2g] We have pt_BR translations, all pt translations are empty.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3435]
I am worried a subset of B2G users may choose pt instead of pt_BR.

@mathjazz, should we alias these?

**Comment by mathjazz** [comment]
If both (pt and pt_BR) are available in B2G, I agree - we should alias them.

**Comment by mathjazz** [comment]
Well, as @ozten and @shane-tomlinson pointed out, pt-PT users might be offended if what they get is pt-BR for pt-PT not being available. I'm getting in touch with pt-PT community about that.

**Comment by mathjazz** [comment]
And pt is now at 100%:
https://localize.mozilla.org/pt/browserid/

**Comment by shane-tomlinson** [comment]
@mathjazz - Dude, you are a machine. How'd you do that so quickly?

**Comment by mathjazz** [comment]
Carlos is the real hero:
https://wiki.mozilla.org/L10n:Teams:pt-PT

**Comment by ozten** [comment]
So awesome, thanks everybody!

**Comment by jedp** [comment]
Sweet! Yes, thank you!
