### ISSUE TITLE
b2g: persona loading spinner should be smaller to match other b2g apps

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3436]
I've been using b2g phone for a bit and noticed the spinner on other apps like marketplace are much smaller.  This would improve persona as first class on b2g.
1. on b2g launch marketplace

actual: see mkt screen shot which is a lot smaller than persona's spinner

![2013-05-17-10-06-23](https://f.cloud.github.com/assets/3698618/519387/b60fe0fa-bf15-11e2-94eb-4a307537e1a1.png)

**Comment by edwindotcom** [comment]
adding @skinny97214 since she's doing a UX review

**Comment by shane-tomlinson** [comment]
@edmoz - check "all-together-now.personatest.org" - the spinner that I am using there is the CSS that was passed to me by @potch, which they use.

**Comment by edwindotcom** [comment]
@shane-tomlinson I thought you went to sleep!

**Comment by jedp** [comment]
He never sleeps

**Comment by shane-tomlinson** [comment]
@edmoz - are we good here?

**Comment by edwindotcom** [comment]
The spinner is still 2x bigger than marketplace.  Ideally it's the same size.  I'll let UX do final approval.
![2013-06-10-13-40-39](https://f.cloud.github.com/assets/3698618/633981/5ca5eb3e-d20e-11e2-90a3-fd6d94f2e7d3.png)

**Comment by mhanratty** [comment]
Spinner for overlay is correct size as implemented--no need to change. We are using a smaller spinner for the Marketplace loading screen.

**Comment by ozten** [comment]
Thanks!
