### ISSUE TITLE
unable to sign into beta.myfavoritebeer.org 

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3437]
I've repro'd on mac ff beta and iOS safari.
1. goto http://beta.myfavoritebeer.org/
2. sign in with any address
3. pop up dialog completes sign in, 

actual: but the parent page, fails to refersh to a signed in state.  If i refresh the page, i get an alert dialog said - sign in failed.  I don't repro this on beta.123done.org.

**Comment by jrgm** [comment]
Okay the broken proxy was restarted by mostlygeek and myfavoritebeer should be all happy now.  The problem appears to be that the apache proxy was not re-resolving DNS for ELB and using stale IP addresses that pointed to no actual hosts. Which means about a 3 minute timeout. And then I think if enough was blocked that way, we would get gateway errors.

@gene1wood or @mostlygeek - is `HostnameLookups` set to off in the Apache config?

I'm going to close this bug as fixed and file another one to address specifically apache not re-resolving DNS names.

**Comment by jrgm** [comment]
1000 consecutive requests to diresworb.org/verify returned a correct response.
