### ISSUE TITLE
sign into beta with dirty state results in assets not loading

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3438]
I noticed this on iOS first but repro'd similar behavior on mac FF beta. I have previous history with the sites (not a clean history/cache state).
1. don't clear cache from previous signins
2. goto beta.myfavoritebeer.org
3. click sign in

result: see screen shot.  

workaround: clear cache/cookies, refresh fixes this issue.

![screen shot 2013-05-17 at 12 56 13 pm](https://f.cloud.github.com/assets/3698618/520099/0976537a-bf2d-11e2-9acd-35e9d606af00.png)

**Comment by edwindotcom** [comment]
I've also repro'd this on beta.123done.org, steps are hard to nail down except, i'm signing in, then out, refresh, then repeat.

**Comment by jrgm** [comment]
This is really the same as #3439.
