### ISSUE TITLE
sign in to beta and refresh results in 404 error when loading communication_iframe.js

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3439]
1. goto beta.123done.org
2. sign in with any username
3. after dialog closes, hit refresh on RP site.

result: button spins a loading icon and 
(from httpfox)
404 error
Cannot GET /v/519d69406f/production/communication_iframe.js

![screen shot 2013-05-17 at 1 13 47 pm](https://f.cloud.github.com/assets/3698618/520143/61103e60-bf2e-11e2-9d82-2a2192d4ca55.png)

**Comment by jrgm** [comment]
From the date in the image above (in the response header), this was while I mistakenly had on server live with an updated build, and a request for communication_iframe was served by that host, but the request for communication_iframe.js was served by a different server (which correctly said 404 to not allow the cached content to be incorrect).
