### ISSUE TITLE
[mobile][firefox][safari] cannot scroll Persona TOS/PP in dialog

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3442]
https://discussions.apple.com/thread/4023861?start=0&tstart=0
https://bugzilla.mozilla.org/show_bug.cgi?id=703573

**Comment by callahad** [comment]
It's probably pretty important that the ToS and PP are actually readable in their entirety.

**Comment by callahad** [comment]
The fix for Firefox for Android and Mobile Safari breaks old Android.
