### ISSUE TITLE
communication_iframe.js should be given `defer` attribute

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3454]
This makes a very slight improvement in perf on mobile. I believe that adding the attribute should be a safe change.

**Comment by shane-tomlinson** [comment]
@mattbasta - I will experiment with this.

My theory is that this will make the RP's JS load & parse faster, but the time to Persona's onready/onlogin/onlogout will be slower. Is that an acceptable tradeoff?

**Comment by mattbasta** [comment]
I think it will really depend on how the browser imppements defer. It's
possible to go either way in most cases.

**Comment by shane-tomlinson** [comment]
@mattbasta - tentatively, when testing using Firefox Desktop, I see almost no difference. This is at full speed, I have not artificially restricted the bandwidth to simulate 2/3G speeds.

The `I:` number is the iframe, the `D:` is the dialog.

```
sync-comm-iframe (cache empty), I:956, D:974
sync-comm-iframe (cache empty), I:946, D:1027
sync-comm-iframe (cache empty), I:949, D:906
sync-comm-iframe (cache empty), I:934, D:946
sync-comm-iframe (cache empty), I:943, D:953
sync-comm-iframe (cache empty), I:933, D:918
sync-comm-iframe (cache empty), I:967, D:960
sync-comm-iframe (cache empty), I:926, D:1053
sync-comm-iframe (cache empty), I:949, D:925

defer-comm-iframe (cache empty), I:952, D:922
defer-comm-iframe (cache empty), I:1054, D:947
defer-comm-iframe (cache empty), I:938, D:1071
defer-comm-iframe (cache empty), I:947, D:1051
defer-comm-iframe (cache empty), I:949, D:864
defer-comm-iframe (cache empty), I:935, D:1064
defer-comm-iframe (cache empty), I:925, D:1029
defer-comm-iframe (cache empty), I:945, D:1102
defer-comm-iframe (cache empty), I:930, D:975
defer-comm-iframe (cache empty), I:932, D:947

sync-comm-iframe (cache full), I:439, D:784
sync-comm-iframe (cache full), I:395, D:596
sync-comm-iframe (cache full), I:326, D:734
sync-comm-iframe (cache full), I:366, D:598
sync-comm-iframe (cache full), I:351, D:570
sync-comm-iframe (cache full), I:372, D:583
sync-comm-iframe (cache full), I:349, D:606
sync-comm-iframe (cache full), I:327, D:680
sync-comm-iframe (cache full), I:337, D:713

defer-comm-iframe (cache full), I:435, D:678
defer-comm-iframe (cache full), I:327, D:666
defer-comm-iframe (cache full), I:328, D:636
defer-comm-iframe (cache full), I:325, D:620
defer-comm-iframe (cache full), I:420, D:622
defer-comm-iframe (cache full), I:334, D:534
defer-comm-iframe (cache full), I:338, D:572
defer-comm-iframe (cache full), I:338, D:547
defer-comm-iframe (cache full), I:333, D:738
defer-comm-iframe (cache full), I:334, D:535
```

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
