### ISSUE TITLE
b2g: oncancel isn't called when clicking cancel button in trustedui

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/persona#3456]
STR:

Using marketplace-dev app on unagi 
- Go to settings
- Click Sign In / Sign up
- If you have previously logged in you're shown your email address + cancel and sign-in buttons
- Click cancel 

What should happen:
- oncancel callback should be fired and you should see "Persona login cancelled" in the logcat output.

What happens:
- oncancel isn't fired.

Same thing happens if you click on the "This is not me" link and then press cancel.

If you close the trusted-ui dialogue with "X" the oncancel fires as expected.

**Comment by jedp** [comment]
@jedp and @shane-tomlinson will take a look

**Comment by edwindotcom** [comment]
I'm not able to repro this with UI Test app (6/1 build) but I have been getting some strange behavior with trying to write an automated test.

**Comment by jedp** [comment]
Yes, the 'cancel' buttons were added to the b2g UI flows after our on-platform code-freeze.  (There are no corresponding cancel buttons in the desktop persona fow.)  As such, the best we could do was to have the cancel buttons send gotAssertion(null) (which is what persona used to do on cancel).

I would like to see us get a fix for this into v1.1

**Comment by jedp** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=881014

**Comment by jedp** [comment]
Thank you, @ozten, for the patch! https://bug881014.bugzilla.mozilla.org/attachment.cgi?id=760144

**Comment by shane-tomlinson** [comment]
Related to #3377?

**Comment by jaredhirsch** [comment]
@mattbasta found these too:

https://bugzilla.mozilla.org/show_bug.cgi?id=881167
https://bugzilla.mozilla.org/show_bug.cgi?id=881962

**Comment by jaredhirsch** [comment]
@jedp so the related bugzilla bug (https://bugzilla.mozilla.org/show_bug.cgi?id=881014) is closed, what more can we do on our end? Can we close this bug and point to the bugzilla bug?

**Comment by jedp** [comment]
@_6a68, @mattbasta, There's nothing to be done on the server side.  It's a client patch that was necessary when the new cancel buttons were added.  We're just waiting for [bug 881014](https://bugzilla.mozilla.org/show_bug.cgi?id=881014) to get uplift to b2g v1.1; then it will be fixed on device.

So the progress for this fix is all in [bug 881014](https://bugzilla.mozilla.org/show_bug.cgi?id=881014)

Since, as you say, there's nothing for us to do server-side, I'll close this.

**Comment by jedp** [comment]
@shane-tomlinson not actually directly related to #3377, but certainly thematically related :)

**Comment by vaidik** [comment]
We are experiencing https://bugzilla.mozilla.org/show_bug.cgi?id=881962 again. And it marketplace dev team says its a persona related bug and not something in fireplace that is causing the issue.

@jedp @shane-tomlinson can you please look into this again?

**Comment by shane-tomlinson** [comment]
This looks like a dup of #3568

**Comment by shane-tomlinson** [comment]
@vaidik - The problem you are seeing using same STRs as outlined in the description above?

**Comment by shane-tomlinson** [comment]
@vaidik - In https://github.com/mozilla/browserid/issues/3456#issuecomment-19358349, @jedp says the fix to this problem requires a change on the phone that is being uplifted to v1.1. @jedp - just to confirm, is there any way around this using Persona-served code, or does this require a change on the phone?

**Comment by vaidik** [comment]
STRs are similar - see https://bugzilla.mozilla.org/show_bug.cgi?id=881962. `marketplace` perhaps makes use of `oncancel` event to remove a throbber that is shown to the user, which does not disappear on cancelling Persona login.

Noticed that `logcat` should point out that Persona login was cancelled. I am not getting that in my logcat. This is the logcat I get: http://pastebin.mozilla.org/2586137.

**Comment by ozten** [comment]
This requires a change to the phone.

**Comment by jedp** [comment]
@shane-tomlinson to confirm: yes, this requires a client fix to the phone.  So it is unfixable on v1.0.1.  v1.1 phones and beyond will work correctly.
