### ISSUE TITLE
L10n preview env is down

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3462]
From @mathjazz in IRC...
https://translate.personatest.org/ is down.

**Comment by ozten** [comment]
I don't know if this blocks [bug#876409](https://bugzilla.mozilla.org/show_bug.cgi?id=876409), but that is a high priority b2g bug. Localizers need this environment to check their work.

**Comment by mathjazz** [comment]
It doesn't block the bug.

http://translate.123done.org/ also doesn't work (button never loads).

**Comment by lloyd** [comment]
123done 使用 Persona 作為登入機制，讓您不需要多記憶帳號密碼就能登入。

Translate environment is back!
