### ISSUE TITLE
onmatch fires when closing popup

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3463]
onmatch appears to accidentally fire if I prematurely close the dialog.

Steps to reproduce on the Test RP:
1. Load Test RP, notice correct automatic callback sequence: onlogout, onready
2. Click "Get an assertion"
3. Close the popup

Notice that onmatch was called. Weird!

**Comment by shane-tomlinson** [comment]
@callahad - is this related to #3170 and #3194?

**Comment by callahad** [comment]
Probably. It's a more minimal steps to reproduce. Hopefully #3194 will fix it. I need to review that :(

**Comment by jaredhirsch** [comment]
fixed by #3699.
