### ISSUE TITLE
SHIMMED_PRIMARIES requires on-disk well-known file

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3464]
The `SHIMMED_PRIMARIES` feature makes developing an IdP a breeze, but instead of fetching the `.well-known/browserid` document from the shimmed primary, it requires a copy of it on-disk.

This seems strange. Fixing it would let us kill a few dozen lines in the gmail identity bridge, and would make local testing even easier.

**Comment by shane-tomlinson** [comment]
AHA! I was running into this yesterday as well. It is a pain. I want a simple way of marking a shimmed primary as "disabled" and then an equally simple way to re-enable it.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
