### ISSUE TITLE
errors shown when running backend tests (shutdown race?)

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3465]
Thought I filed this a while ago, but I guess not.

I was running `WHAT_TESTS=back_mysql npm test` with the `dev` branch, locally on osx and noticed there were occasional chirps in stdout/stderr about `failed to clear authentication attempts`. The tests passed though.

Examples:

```
tests/primary-secondary-transition-test.js
  -> browserid (83630): error: failed to clear authentication attempts for 1: Error: socket hang up
tests/verify-in-different-browser-test.js
  -> browserid (84447): error: failed to clear authentication attempts for 1: Error: socket hang up
tests/registration-status-wsapi-test.js
  -> browserid (92998): error: failed to clear authentication attempts for 2: Error: connect ECONNREFUSED
```

I think this a race with shutdown in the tests, due to changes for PR-3337.

In https://github.com/mozilla/browserid/blob/dev/lib/wsapi/authenticate_user.js#L81, 
we try to do further work after telling the client that 'everything is
done'. 

If that test has nothing further to do (haven't traced all the way through each test), the test will begin shutdown of the test servers, and the race is on.

Anyways, this probably isn't a production issue (except maybe in a corner case of flapping servers). 

But perhaps for the local test, a little delay trick on mutual shutdown of local servers. (Might also help with other things).

**Comment by shane-tomlinson** [comment]
The fix has been merged, closing.
