### ISSUE TITLE
error seen once when signup new user at main site

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3466]
I hit this once, but on retrying this ~10 more times, I haven't hit it again. This was with FF21 using an ephemeral instance with train-2013.05.22 - https://jrgmtrain0522.personatest.org.

STR
1. Load the main site and click signin.
2. In the dialog, enter a new email address and the password twice. Dialog transitions to polling for user_completion_status.
3. Load that email in a new window/tab of the same browser.

Expected: user completes creation in the new window, the dialog dismisses and the first window transitions to signed in state.
Actual: user completes creation in the new window, but I got this error below, and the dialog stops.

Timestamp: 5/29/13 4:29:51 PM
Error: Error: module not started for check_registration
Source File: https://jrgmtrain0522.personatest.org/v/6f499d473e/production/en/dialog.js
Line: 4

**Comment by jrgm** [comment]
I was running selenium with IE8 (after repairing the tests for IE8) and had some failures. Saw the error icon, so ran the tests again and got lucky is seeing it in a live test with this message. The occassionally failing test was new-user-secondary-test and the error happens after the username and passwords have been submitted and the dialog transitions to the polling state.

**Comment by jrgm** [comment]
The tests were running against stage which is now the train-2013.06.05

**Comment by jrgm** [comment]
To clarify, by "this message" I mean "module not started for check_registration".

**Comment by jrgm** [comment]
I saw this again in GH-3560. It's seems this may have become easier to hit. I'm raising this to 5-star for investigation.

**Comment by jaredhirsch** [comment]
looking now

**Comment by jaredhirsch** [comment]
Well, been at it for 90 minutes or so, here's what I've traced thus far.

The failure screen is triggered when the function call [in check_registration#startCheck](https://github.com/mozilla/browserid/blob/dev/resources/static/dialog/js/modules/check_registration.js#L47-L52) fires its errback:

```
# inside check_registration#startCheck
user[self.verifier](self.email, function(status) { ... }, self.getErrorDialog(...))
```

That's a dynamic function call, it's a bit much to unpack. But note that the basic deal is, we're calling a dynamically-selected function on the user object, `user[self.verifier]`, and the last argument is the errback, which displays the error screen observed when the bug attacks, `self.getErrorDialog(errors.registration, oncomplete)`.

When we are initially creating a user and polling for completion of the email roundtrip, [doConfirmUser](https://github.com/mozilla/browserid/blob/dev/resources/static/dialog/js/modules/actions.js#L72) calls `startCheck` and passes it the function `User#waitForUserValidation`, which in turn asks `Network` to poll the `wsapi/user_creation_status` endpoint.

If the wsapi returns ok, the `user_confirmed` signal is fired. If not, the errorDialog is shown.

Now, the observed error message, "module not started for check_registration", is thrown when we tell a module to `stop()` when it hasn't been `start()`ed, see [here](https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/lib/module.js#L80-L86). This seems like our race condition, but I don't yet understand how these calls could be failing to fire in order. Still digging.

**Comment by jaredhirsch** [comment]
Funny how writing things up makes sense of stuff. We [only let one service run at a time](https://github.com/mozilla/browserid/blob/dev/resources/static/dialog/js/modules/actions.js#L22-L25), so if another service starts asynchronously, then check_registration tries to `stop` and is already stopped, there's our error.

**Comment by jaredhirsch** [comment]
@jrgm I'm stumped. @seanmonstar took a look as well, but this one needs a stack trace for further digging.

I'm not sure how to proceed, it's a weird one:

![](http://media1.giphy.com/media/3VmNQvngIrTRC/original.gif)

reassigning to you, do as you will with't.

**Comment by jrgm** [comment]
Yeah, not sure what to do here (I don't have reliable STR, and don't know how much it happens in the wild, but I've bumped into enough that there is likely real user impact).

**Comment by shane-tomlinson** [comment]
@6a68 - There is a bug in startService that could be contributing to this.

If startService is invoked, it shuts down the previous service and attempts to start the next service. If the next service cannot be found, the reference to runningService is still set to the just shut down service. 

This implies that check_registration is shut down, then the next service cannot be found. check_registration is still registered as running. The "next" service, whatever that is, is trying to re-shut down check_registration and failing.

Or, this implies that check_registration was shut down outside of modules/action.js and then it attempted to re-shut it down. 

So, it seems there are at least two bugs.

**Comment by kparlante** [comment]
@6a68, @shane-tomlinson : yes, I'll look for this error in the kpi data

**Comment by kparlante** [comment]
@6a68, @shane-tomlinson, @jrgm : near as I can tell, this is what the error profile looks like in the kpi blobs: https://id.etherpad.mozilla.org/kpi-issue-3466-data

Sampled over a short period in June, this is the most common of the error screens
- 1.8% of all blobs
- 47% of blobs with screen.error

We can validate that assumption once the fix goes in.

**Comment by shane-tomlinson** [comment]
There are a couple of interesting things going on.
- All but one data point from the sample data set is Chrome.
- screen.error.registration is on the event stream after window.unload even though it occurs before window.unload in time.
- Screen.error.registration should only occur if /wsapi/user_creation_status returns a non-200 error code.
- In the set that completes, /wsapi/authenticate_user is called immedaitely after /wsapi/user_creation_status.

I wonder if for a small subset of these XHR requests, the user closes the dialog to verify their email address while /wsapi/user_creation_status is in flight. If so, the XHR request would be aborted, causing Chrome to complete the with a status of 0 [see #2423  and http://stackoverflow.com/questions/11666421/jquery-ajax-request-abort-in-chrome]

This could be caused by:
1) /wsapi/user_creation_status is in flight when user triggers dialog close
2) /wsapi/user_creation_status is started after the user triggers dialog close

#1 could happen because XHR requests are not aborted on dialog close.
#2 could happen because the email verification poll is on a repeating setTimeout that does not take dialog close into consideration.

But these seem like distinct problems to the one reported here by @jrgm.

log with error screen:

```
[["xhr_complete.GET/wsapi/session_context", 4095, 525], ["window.channel_established", 4849], 
["screen.rp_info", 4853], ["screen.authenticate", 4858], ["user.can_interact", 4922], 
["xhr_complete.GET/wsapi/address_info", 20146, 2774], ["screen.set_password", 23639], 
["xhr_complete.POST/wsapi/stage_user", 42254, 1210], ["user.user_staged", 43467], 
["screen.check_registration", 43468], 
["xhr_complete.GET/wsapi/user_creation_status", 43503, 238, 3], 
["window.unload", 50001], ["screen.error.registration", 49986, 13]]
```

log of new user flow with successful completion:

```
"event_stream": [["window.dom_loading", 382], 
["xhr_complete.GET/wsapi/session_context", 1931, 63, 2], 
["window.channel_established", 2006], ["screen.rp_info", 2007], 
["screen.authenticate", 2008],
["user.can_interact", 2028], ["xhr_complete.GET/wsapi/address_info", 4112, 1768], 
["screen.set_password", 5953],
["xhr_complete.POST/wsapi/stage_user", 9480, 411], ["user.user_staged", 9893], 
["screen.check_registration", 9894], 
["xhr_complete.GET/wsapi/user_creation_status", 9911, 15, 5], 
["xhr_complete.POST/wsapi/authenticate_user", 22004, 404], 
["xhr_complete.GET/wsapi/list_emails", 22410, 13, 2], 
["user.user_confirmed", 22437], ["generate_assertion", 22437], 
["screen.generate_assertion", 22437], 
["xhr_complete.POST/wsapi/cert_key", 22462, 785], ["assertion_generated", 23258], 
["window.unload", 25044]],
```

**Comment by kparlante** [comment]
@shane-tomlinson : interesting... should I log this as a separate issue? Should I look for jrgm's case, or do we think we have a handle on it without more investigation? If I did go look, what should I be looking for?

**Comment by jrgm** [comment]
Just noting that I hit this by random timing (again) last night with osx chrome 27.

**Comment by shane-tomlinson** [comment]
@jrgm - I haven't forgotten about this. ;) It has taken up most of the week so far and led me down a rabbit hole of finding several subtle timing bugs.

**Comment by shane-tomlinson** [comment]
@kparlante - I agree, the posted data looks to be another issue - I have opened #3618 for that. Thanks for spotting it!

**Comment by jaredhirsch** [comment]
@jrgm @shane-tomlinson I'll take another swing at this today.

**Comment by jaredhirsch** [comment]
@jrgm @shane-tomlinson demoting to four stars. This bug doesn't fit [the definition of five-star](https://github.com/mozilla/browserid/wiki/The-BrowserID-Bug-Process): it doesn't block trains, force a hotfix, or affect enough users to merit _all_ engineering resources focusing on this.

Bump back up if you disagree.

**Comment by jrgm** [comment]
I really haven't seen this in a while now. No real proof that it is gone, but given recent FE changes, possibly this is not reproducible anymore. Closing. WIll reopen if seen again.
