### ISSUE TITLE
add far-future caching headers to favicon.ico

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3468]
Minor improvement to be sure, but might help b2g depending on how it deals with favicon. 

Anyways, just happened to notice that we serve https://login.persona.org/favicon.ico with:

```
Cache-Control: public, max-age=0
```

Should probably give that, say, a 90 day or longer expiry to remove an unnecessary network request when bringing up the dialog.

**Comment by shane-tomlinson** [comment]
Closing as dup of #2482
