### ISSUE TITLE
[b2g] Turn on kpi logging for ephemeral instance

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3470]
Dev instances can send blobs here: https://kpiggybank-dev.personatest.org/

**Comment by jedp** [comment]
I'm all upons

**Comment by ozten** [comment]
I'm confused. [aws.json](https://github.com/mozilla/browserid/blob/dev/config/aws.json#L24) already has sample rate set to 1.0 and is using https://kpiggybank-dev.personatest.org/.

For example on firefoxos.personatest.org I see this in the startup logs

```
"kpi_backend_sample_rate":1,"kpi_backend_db_url":"https://kpiggybank-stage.personatest.org/wsapi/interaction_data"
```

What do we want to do here, exactly?

**Comment by kparlante** [comment]
@ozten : The log above shows kpiggybank-stage, not kpiggybank-dev (stage has specific security group settings and won't accept posts from ephemeral instances).

aws.json may have been updated with the correct settings since this issue was logged (#3471). On firefoxos.persona.org, kpi_backend_sample_rate is set to 0.0 in /home/app/config.json, which takes precedence over config/aws.json.

**Comment by jedp** [comment]
Note that `firefoxos.persona.org` proxies to `firefoxos.personatest.org`.  On `firefoxos.personatest.org`, I've updated the `aws.json` to use `kpiggybank-dev`.  The startup config now says:

```
\"kpi_backend_sample_rate\":1,
\"kpi_backend_db_url\":\"https://kpiggybank-dev.personatest.org/wsapi/interaction_data\",
\"kpi_backend_sample_rate_per_agent\":{}
```

Is this correct?

**Comment by ozten** [comment]
Attention to detail, isn't my strong suit.

Deploying an ephemeral from dev, to ensure it uses kpiggybank-dev.

**Comment by ozten** [comment]
Launched kpitester42.personatest.org

Looking at the logs, I think it is doing the right thing:
    "kpi_backend_sample_rate":1,"kpi_backend_db_url":"https://kpiggybank-dev.personatest.org/wsapi/interaction_data"
    {"level":"debug","message":"sending request to KPI backend: https://kpiggybank-dev.personatest.org/wsapi/interaction_data","timestamp":"2013-06-10T17:52:46.609Z"}

Closing bug. Please re-open if I've missed anything.

**Comment by kparlante** [comment]
@ozten: Yes, looks like we're seeing b2g blobs on kpiggybank-dev. Thanks! FWIW, the blobs currently show up as "Unknown Firefox 18" with `"rp_api": "internal"`
