### ISSUE TITLE
[ie8][bigtent] after Authentication Error using "wrong user, screen resized smaller twice

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3476]
This is reproducible in current production or on current stage. I cannot reproduce in FF21, so this may be IE8 specific.

STR
1. Be signed into yahoo as foo@yahoo.com, but not signed into to login.persona.org.
2. Go to 123done.org, and try to signin as bar@yahoo.com.
3. Screen resizes and then "Authentication Error: Sorry, it looks like you were trying to log in as bar@yahoo.com, but were logged in to Yahoo as a different address. (foo@yahoo.com)"
4. Click 'Try Again'.
5. Enter foo@yahoo.com instead.
6. Screen resizes a second time, and will log you in, but this is what it looks like:

![double-shrink-dialog](https://f.cloud.github.com/assets/758162/587914/7d4f356e-c973-11e2-967a-98498a3db2e0.png)

**Comment by jrgm** [comment]
And if it's time for the "Is this your computer" question, it looks like this:

![doube-shrink-an-is-this-your-computer](https://f.cloud.github.com/assets/758162/587938/42d347b2-c974-11e2-8618-9a4a0e9c18c1.png)

**Comment by callahad** [comment]
Wow, that looks ridiculous. The Gmail bridge doesn't have any resizing code in it, itself. The Google OpenID permissions screen (only seen once per email address) does resize, but only vertically and only if the window is smaller than a certain minimum height.

@jrgm What happens on subsequent login attempts, after you've told Google to "Allow" in a previous transaction?

**Comment by jaredhirsch** [comment]
@jrgm I just logged in successfully using a yahoo account on IE8, and the window shrunk as seen in your screenshot--except it gave the primary success message. Looking at this now.

**Comment by shane-tomlinson** [comment]
Is this related to mozilla/browserid-bigtent#58

**Comment by jaredhirsch** [comment]
@shane-tomlinson GO TO SLEEP ;-) yeah, looks related. I was just looking at screen_size_hacks to determine when/how we're resizing the dialog, so that when we return from the primary, we could resize it accurately. Open to suggestions on a better approach.

**Comment by jaredhirsch** [comment]
@shane-tomlinson this is also probably related to @callahad's "the dialog is different sizes different places" bug

**Comment by jaredhirsch** [comment]
@shane-tomlinson you were right, this was related to the IE 8-incompatible fix for #58. Working on a PR now, and the fix lives entirely within the bigtent repo.

**Comment by jaredhirsch** [comment]
ok, I think I found a simpler way to fix this. @shane-tomlinson thoughts on the latest latest attempt, https://github.com/6a68/browserid-bigtent/commit/f85d3aa39dc0537656a61337d3998e1f9f7746b9?

**Comment by jrgm** [comment]
@6a68 - you should be aware of this bug in gecko with the actual opened width not being what was requested - https://bugzilla.mozilla.org/show_bug.cgi?id=779335

Although, I haven't checked that recently.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
