### ISSUE TITLE
manage page showing up by default is uncomfortable

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#348]
The new site design shows the "manage" page on browserid.org whenever a user visits the site and has an existing session.  This is uncomfortable as in our case most users will start by using browserid via sites they visit.  Only when they wish to learn more will they land on browserid.org.  Because our usage patterns are a little odd, the expectation is that a significant number of users will arrive on browserid wanting information, not to manage their addresses.

**Comment by skinny97214** [comment]
Bryan - What would you think of switching the "how it works" page to be the home page. Then you'd have an "My account" link in the top nav.

**Comment by benadida** [comment]
@skinny97214 I'm going to guess that Bryan is super busy: want to make the call on what it should be?

**Comment by clarkbw** [comment]
Yeah, this is a deficiency that wasn't fixed from the original design.  The plan was to convert the (logged out) main page into a single line that sat above the account manager, something a little more friendly than standard tag line.  "You're using BrowserID, want to <a>learn more</a>?".  Bonus points to be awarded if you recognized that someone was arriving at the BrowserID for the first time and made that single line call out to the user more than usual.

**Comment by skinny97214** [comment]
Here's a mockup that adds the feedback from @clarkbw.
http://cl.ly/0n1l3o3C081V2I1R433a

Do we have a welcome email on the roadmap?

**Comment by benadida** [comment]
assigned @shane-tomlinson to make this beautiful thing happen.

No welcome email beyond the confirmation email yet. You thinking of something fun?

**Comment by skinny97214** [comment]
Clarification: this should only show to new users, as bryan said "Bonus points to be awarded if you recognized that someone was arriving at the BrowserID for the first time."

It's too bold to be there always.

**Comment by benadida** [comment]
so... new users as in someone who has set up BrowserID in the popup, but never gone to the manage page?

**Comment by skinny97214** [comment]
Yes, exactly. Since the manage page = home page, we want to make sure we get new users up to speed on how it works.

**Comment by benadida** [comment]
so we'd have to keep track of that in the DB (or in a cookie and then get inconsistent behavior.) OK, let's make it happen first with a cookie (no DB change.) Better than what we have now.

**Comment by shane-tomlinson** [comment]
@benadida, @skinny97214 - implemented using localStorage to keep track of whether the user has visited the manage page before.

**Comment by shane-tomlinson** [comment]
1b3d5e434fbe811cc4f30c76d6c30e84420fa275 fixes this.
