### ISSUE TITLE
With new support for custom origins, Persona should allow verification against app: scheme

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3481]
Support for custom origins has landed:

https://bugzilla.mozilla.org/show_bug.cgi?id=852720

If this seems sane, we should start talking about getting app://-scheme audiences verifiable. The docs for Persona and for packaged apps should also be updated to reflect how to specify an origin for a packaged app in order to take advantage of Persona.

It might be a good idea to reject audiences in the form app://{guid} (as packaged apps are/have been) to prevent developers from abusing the audience.

cc @cvan, @markgif (for docs)

**Comment by shane-tomlinson** [comment]
@mattbasta - I believe this has been taken care of already - #3334

**Comment by mattbasta** [comment]
Oh, very cool. Keeping this open for documentation.

**Comment by markgif** [comment]
mattbasta, is this going to be for 1.1 or later? I am hotly focused on 1.0 docs right now.

**Comment by mattbasta** [comment]
I don't think custom origins are available in 1.0, so it can wait until
then.

**Comment by lloyd** [comment]
this should be fixed in code that landed in #3334, please review the change and re-open if it doesn't solve the `app://` problem!

**Comment by mattbasta** [comment]
Does documentation exist for using custom origins with persona?

**Comment by markgif** [comment]
I'm not familiar with the Persona docs, which are here: https://developer.mozilla.org/en-US/docs/Mozilla/Persona
I think Will Bamberg handles them. Since custom origins were just implemented, I doubt the Persona docs talk about them. Do you have any info on how to do it, I can help.
