### ISSUE TITLE
personatest.org SSL certificate has expired

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#3484]
> The certificate expired on 6/1/13 4:20 AM. The current time is 6/1/13 10:21 AM.

**Comment by lloyd** [comment]
this affects all ephemeral testing instances.

**Comment by callahad** [comment]
mozilla/identity-ops#38 also warns of an about-to-expire SSL certificate. Can we knock both of these out at the same time? Also, do we have someone actively watching the persona.org cert for expiration?

**Comment by lloyd** [comment]
resolved, new SSL cert delivered to the team via identity staff and [the usual mechanism](https://github.com/mozilla/browserid/blob/dev/docs/AWS_DEPLOYMENT.md#prerequisites)
