### ISSUE TITLE
[sideshow] 'gmail makes this easy' page is missing from workflow

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3489]
1. goto: https://login.dev.anosrep.org/
2. click sign in 
3. enter user@gmail.com

actual: you end up on gmail login page

expected: you should see - yahoo makes this easy page.  I saw this last weekend but I don't see it anymore.  I cleared my local cache/history as well.

**Comment by edwindotcom** [comment]
that page isn't displayed when the account exists.  If you cancel account, you'll see it.  I'll close this bug for now, I'll compare against yahoo

**Comment by lloyd** [comment]
Design intent was the page would show the first time a user uses an email address unknown persona. It sounds like the bug might go the other way and could somehow be a bug with Yahoo?

Edwin Wong notifications@github.com wrote:

that page isn't displayed when the account exists.  If you cancel account, you'll see it.  I'll close this bug for now, I'll compare against yahoo

---

**Comment by edwindotcom** [comment]
@lloyd i just confirmed the same behavior on yahoo bigtent. No issues here.
