### ISSUE TITLE
email confirmation page is unstyled

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#349]
currently when you add an email to an existing account, the verification landing page that you get to by clicking on the link in your email is completely unstyled.  We should style this and hopefully help the user along.  By the time the user sees that page they are probably already logged into the RP which is open in another tab.  so what, we say "You did it!  Your new address is set up and you should now be signed in.  You may now close this window and go back to zzzz.com"?

**Comment by shane-tomlinson** [comment]
I did a bit of styling work, but I agree with @lloyd - I think instead of going to the manage screen immediately, we should say which site they are now logged in as.  Maybe we should do that with the verify initial user page as well?
