### ISSUE TITLE
[b2g] tooltips can run off the screen.

### ISSUE THREAD

**Issue by zacc** [mozilla/persona#3496]
When using trusty ui in the modal dialog mode this error message is obscured.

I also need ot know what it says - something about logging in more than once?

![2013-06-06-06-22-50](https://f.cloud.github.com/assets/966053/618139/a7c0115e-ceac-11e2-9bbf-2bc3c7349bee.png)

**Comment by jedp** [comment]
@zacc thanks for the report, and yes, this is horrible.  

We're already on this issue.  Please follow this bug: https://github.com/mozilla/browserid/issues/3154

Closing as duplicate.

**Comment by zacc** [comment]
What does the message actually say though?

I was told to use an unverified user for this test but I am hitting this error message and I need to set up the device to handle the unverified user. Using a verified user in the meantime.

**Comment by shane-tomlinson** [comment]
@zacc - an email is still sent to unverified users so that they can verify their ownership of the email address. This message is saying "hey, we just sent a message to that address!"

**Comment by shane-tomlinson** [comment]
Re-opening to fix this before fully addressing #3154

**Comment by shane-tomlinson** [comment]
This affects the current beta. @jrgm - is this worthy of a hotfix?

**Comment by shane-tomlinson** [comment]
@jedp - the same comment goes to you - is this worthy of a hotfix?

**Comment by shane-tomlinson** [comment]
@jedp and @jrgm - this bug should be limited to the "We just sent an email to that address! If you really want to send another, please wait a minute or two and try again." tooltip when Persona is accessed from Marketplace. When Persona is accessed from Marketplace, the RP info at the top of the screen is not displayed, which pushes the rest of the screen up. The code to anchor the tooltips did not check to ensure the tooltip boundaries were still on the screen.

The fix to this is an additional 10 lines added to tooltip.js to check the top and right boundaries of the tooltip. With tests, the changes come to 30 lines.
