### ISSUE TITLE
Cannot login through Persona on Yahoo due to email alias

### ISSUE THREAD

**Issue by nuschke** [mozilla/persona#3498]
I was trying to login in through Persona to access mozilla's addon builder tool. I had previously used my yahoo email address for the account.

Recently I tried to login through persona, and it found my original Yahoo email address that is no longer in use, and was not used for the addon builder. I had created an alias in Yahoo for this old email so that I didn't have to start a new account.

Unfortunately, there is no way to get around this that I can determine and I cannot login through Persona to access my account.  Any ideas?

**Comment by callahad** [comment]
@nuschke I'm sorry you got bit by this bug. Persona doesn't currently support Yahoo aliases (this is a regression), but we're working on fixing it. We'll hopefully have you unblocked in the next few weeks. You can follow mozilla/browserid-bigtent#216 for more info and for updates.
