### ISSUE TITLE
never store passwords in plaintext

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#35]
there's no need to store plaintext passwords on the server.  we should hash them right when they come in.

**Comment by benadida** [comment]
bcrypt preferred with a randomly selected salt every time please :)

**Comment by lloyd** [comment]
17:29 < lloyd|afk> benadida: when you say "every time" you mean generated at first run?
17:29 < benadida> every time the password is set/changed.
17:29 < lloyd|afk> benadida: or you mean randomly generate salt for each user?
17:29 < lloyd|afk> and store salt in the user record?
17:29 < benadida> for each new password for each new user.
17:29 < benadida> yes
17:29 < lloyd|afk> what's a good salt bitwidth?
17:30 < benadida> 64+ bits I would say.
