### ISSUE TITLE
new /about page needs graphics!

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#350]
the new "about" page has four graphics that are missing.  The largest topmost graphic is to be a screencast, that's not what this bug is about.

This bug is for the three smaller images that appear underneath.

reference: https://dev.diresworb.org/about

**Comment by lloyd** [comment]
I added placeholder graphics:  https://dev.diresworb.org/about - downgrading this issue to 4 stars.

**Comment by clarkbw** [comment]
This looks pretty good for now, I'll move on to other stuff.  I only have a couple of nits with the text.
- remove the ":" at the end of "BrowserID is an easier way to sign in"
- remove the "." at the bullet point 1 and 2

**Comment by ghost** [comment]
Verified that these changes are also made on https://diresworb.org/about.
