### ISSUE TITLE
New account creation: Hitting 'enter' on first password field should focus the next

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3502]
Currently, if you create a new account on b2g, when you are prompted to create a password, hitting 'enter' tries to submit the form, which fails because you haven't yet entered the password as second time for confirmation.

What should happen is that hitting 'enter' in the first field should focus on the second field, and then hitting 'enter' in the second field should try to submit.

**Comment by shane-tomlinson** [comment]
I fixed this already, did the change not get applied in the merge frenzy?

**Comment by shane-tomlinson** [comment]
@jedp - this was added in 54a51195a4d16f59b11f38b91c800e75d84574e0, but for an as of yet unexplainable reason, is not working in FirefoxOS.
