### ISSUE TITLE
'onmatch' firing incorrectly

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3503]
Split from #3417 

'onmatch' seems to be firing if the user has _any_ active persona session, and loggedInUser is set to `undefined` on a different RP site.

**Comment by shane-tomlinson** [comment]
This is not great.

**Comment by callahad** [comment]
And it's totally my fault. Sorry :(

**Comment by jaredhirsch** [comment]
@callahad don't feel bad, bro. everybody writes bugs :beers:

**Comment by callahad** [comment]
I was all like: :pencil2: :soon: :bug:

**Comment by jaredhirsch** [comment]
The [code docs](https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/user.js#L1486-L1489) for `User.getSilentAssertion` suggest that an assertion should only be passed to the callback if Persona believes the user is signed in to the current site.

It appears that the fix would be to check `loggedInUser === email && assertion` inside [the communication_iframe](https://github.com/mozilla/browserid/blob/dev/resources/static/communication_iframe/start.js#L67).

I'll give this approach a try today and see how it goes.

**Comment by jaredhirsch** [comment]
No wait! Reading `getSilentAssertion` more carefully, it looks like the signal that things match is that `loggedInUser == email && !assertion`. Hmmm.

**Comment by jaredhirsch** [comment]
No wait, I don't think that's it. I now suspect it's the same root cause (race condition between 'loggedInUser' and 'dialog_complete' signals) as #3170, see specifically [shane's comment in that bug](https://github.com/mozilla/browserid/issues/3170#issuecomment-15776273).

**Comment by shane-tomlinson** [comment]
Did I fix this with 6943324fa160b5a81fcd9abd1fbbbfae1bb33054? See the note here:

https://github.com/mozilla/browserid/blob/dev/resources/static/include_js/_include.js#L393-L399

If not, what are the concrete STRs?

**Comment by jaredhirsch** [comment]
Just saw this--I'll take a look in the morning :)

**Comment by jaredhirsch** [comment]
@shane-tomlinson I can't repro this using IE9 or FF22 on login.persona.org or login.dev.anosrep.org, implying that the fix shipped with some previous train. So, I guess I'll close and reopen if I can reproduce.

I've been testing this by going through the following flow:
1. load up a fiddle that logs when callbacks fire: http://jsfiddle.net/XgVD5/9/
2. play around with the value of loggedInUser in the fiddle
3. log into persona.org/anosrep.org in another tab
4. reload the fiddle, again play with loggedInUser
5. possibly reset browser, then start again
