### ISSUE TITLE
experimental features from .request have not been added to .get in the shim

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3506]
The experimental features added for FirefoxOS were only added to .request and have not been added to .get.
- experimental_forceAuthentication
- experimental_forceIssuer
- experimental_allowUnverified

**Comment by jedp** [comment]
Good observation

**Comment by jedp** [comment]
The same needs to happen on b2g platform.  I've opened [bug 881345](https://bugzilla.mozilla.org/show_bug.cgi?id=881354).

**Comment by jedp** [comment]
I presume this is overall of low priority, though.  We're not encouraging people to use `get()`, and we're not at all encouraging people to get in the habit of using these experimental parameters.

**Comment by shane-tomlinson** [comment]
@jedp - should both of these be updated together so there is minimal API disparity?

**Comment by lloyd** [comment]
The goal hasn't been minimal api disparity.  The goal was to move from get to watch.  Now, on list, were wondering about a new attempt at a better api.

I don't think three APIs do the same thing is long term tenable, and really hurts our ability to roll out features.

I think we should _not_ upgrade get() but instead accelerate efforts to figure out if a compromise api will be easier to implement for people and will help adoption.

Shane Tomlinson notifications@github.com wrote:

@jedp - should both of these be updated together so there is minimal API disparity?

---

**Comment by jaredhirsch** [comment]
+1 for closing and driving the "simpler .watch alternative" discussion harder instead
