### ISSUE TITLE
Some users cannot log in - assertions failing validation - "expired"

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#3514]
Jeff reports on our mailing list "Once every few days I get an assertion that fails validation"

We are pro-actively auditing servers for clock skew, and awaiting more information from Jeff - we need when the assertion was received from the user, and the time the assertion was issued, and the time the certificate embedded was issued.

Jeff, you can inspect the details of an assertion using `bin/check-assertion` from mozilla/jwcrypto - and you can remove the specific email address and post the rest here?

**Comment by lloyd** [comment]
time skew audit being tracked in mozilla/identity-ops#67

**Comment by gene1wood** [comment]
I've established clock skew monitoring on the webheads in both regions. The greatest clock skew is one webhead is off by 0.02 seconds.

**Comment by jaredhirsch** [comment]
zomg intermittent five-star bug! need moar info! cannot get! anxiety attack!

![](http://25.media.tumblr.com/ecbd7946e9f71b5008328f57303d49af/tumblr_mepyoedTR81qebfwho1_250.gif)

@stickfigure we're dying to see that funky assertion, minus the specific email address

**Comment by yourcelf** [comment]
I'm getting "assertion has expired" errors routinely (a couple per day).  In the mailing list, @lloyd suggested logging assertions and timestamps to help debug this -- I've begun doing so.
1. Is it safe (privacy-wise) to attach assertions+timestamps the bugtracker here?
2. Would it be helpful to do so?

**Comment by callahad** [comment]
@yourcelf The assertions contain the user's email address, so I'd recommend not posting them directly.

You can either email one of us directly {lloyd,callahad,6a68}@mozilla.com, or parse out the cert body and remove the email address. :)

Backed Identity Assertions are just formatted like `header.payload.signature~header.payload.signature`, where so if you split on `~` you'll separate the certificate and the assertion, then you can split each of those on `.` to get the individual parts.

The payloads are url-safe base64 encoded, and you may have to add 1, 2, or 3 `=` characters to the end to get the base64 padding right :)

**Comment by lookfirst** [comment]
For what it is worth, we (myself and @stickfigure) have no control over our server time since we are hosted on Google AppEngine. Those servers have been known to not always carry the best time.

**Comment by jaredhirsch** [comment]
@lookfirst o rly, that's a super interesting datapoint. I wonder if this applies to peeps using Nodejitsu, Heroku, etc. 

cc @warner, who is thinking about server clock skew and jwcrypto

**Comment by stickfigure** [comment]
Sorry about the delay - it's been a busy week. Here's the check-assertion for the most recent failure, which was approximately Mon, Jun 10, 2013 at 6:04 PM (pacific):

==== cert ====
issuer: login.persona.org
principal: {"email":"xxxx.xxxxxxxx@gmail.com"}
iat: Fri May 31 2013 17:16:01 GMT-0700 (PDT) (1370045761418)
exp: Sat Jun 01 2013 17:16:01 GMT-0700 (PDT) (1370132161418)
(seeking public key! trying to fetch .well-known from login.persona.org)
(using a median timestamp to ensure no timestamp failure)
cert is properly signed

==== assertion ====
{ header: { alg: 'DS128' },
  payload: { exp: 1370912803284, aud: 'https://www.voo.st' },
  signature: 'b96b3af618aba6d86308dbcf0155837da6b76be2d60004b52a7bb582276bd2d8f216b0e2cb62d1fe',
  headerSegment: 'eyJhbGciOiJEUzEyOCJ9',
  payloadSegment: 'eyJleHAiOjEzNzA5MTI4MDMyODQsImF1ZCI6Imh0dHBzOi8vd3d3LnZvby5zdCJ9',
  cryptoSegment: 'uWs69hirpthjCNvPAVWDfaa3a-LWAAS1Knu1gidr0tjyFrDiy2LR_g' }
audience: https://www.voo.st
expires: Mon Jun 10 2013 18:06:43 GMT-0700 (PDT)
FATAL: assertion was likely issued after cert expired
(verifying with an expiration date that should be valid for this assertion.)
assertion is properly signed

==== bundle ====
assuming public key is the key for login.persona.org
FATAL: assertion is invalid: assertion has expired

**Comment by stickfigure** [comment]
And this one just happened seconds ago:

==== cert ====
issuer: yahoo.login.persona.org
principal: {"email":"xxxxxxxxx@yahoo.com"}
iat: Tue Jun 11 2013 03:03:07 GMT-0700 (PDT) (1370944987306)
exp: Tue Jun 11 2013 03:08:17 GMT-0700 (PDT) (1370945297306)
(seeking public key! trying to fetch .well-known from yahoo.login.persona.org)
(using a median timestamp to ensure no timestamp failure)
cert is properly signed

==== assertion ====
{ header: { alg: 'DS128' },
  payload: { exp: 1371325257603, aud: 'https://www.voo.st' },
  signature: '2ecf75d24a012857aa80cdbfaa2ba56c6347354fbf8edb7e9361d1490107ab176cace35051edf300',
  headerSegment: 'eyJhbGciOiJEUzEyOCJ9',
  payloadSegment: 'eyJleHAiOjEzNzEzMjUyNTc2MDMsImF1ZCI6Imh0dHBzOi8vd3d3LnZvby5zdCJ9',
  cryptoSegment: 'Ls910koBKFeqgM2_qiulbGNHNU-_jtt-k2HRSQEHqxdsrONQUe3zAA' }
audience: https://www.voo.st
expires: Sat Jun 15 2013 12:40:57 GMT-0700 (PDT)
FATAL: assertion was likely issued after cert expired
(verifying with an expiration date that should be valid for this assertion.)
assertion is properly signed

==== bundle ====
assuming public key is the key for yahoo.login.persona.org
FATAL: assertion is invalid: assertion has expired

**Comment by stickfigure** [comment]
More information that might be relevant: We validate the assertion using https://verifier.login.persona.org.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
