### ISSUE TITLE
silent assertions are generated from .onlogin of .watch API with incorrect issuer after issuer changes

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3515]
If the issuer changes for a particular address but the user has a cert in localStorage, the .watch API will invoke .onlogin with the cert from the old issuer.

STR

1) Start the dev RP with the example IdP enabled
2) create a Persona account using the example IdP
3) Stop the server
4) Disable the example IdP (change it's .well-known/browserid to have "disabled": true)
5) restart server
6) refresh example RP

**Comment by lloyd** [comment]
potentially a blocker for gmail. /cc @seanmonstar @callahad 

5 to investigate.  is this a regression?

**Comment by seanmonstar** [comment]
so, this means that the communication_iframe is noticing the cert in localstorage, and proceeding to use it, without a check to make sure it's allowed to?

**Comment by jaredhirsch** [comment]
I've repro'd this locally but haven't found the offending code yet. Will finish git bisecting tomorrow.

**Comment by shane-tomlinson** [comment]
@lloyd - I believe we have always been broken here. We never stored the issuer for a cert along with the cert, and we don't have any explicit tests for this.

The root of the problem is, when we fetch a silent assertion, we do not call addressInfo to check whether the issuer contained in a stored cert is up to date.

**Comment by shane-tomlinson** [comment]
@lloyd - We do check for invalid certs with out of date issuers, but only when calling addressInfo.
