### ISSUE TITLE
Account has been reset on persona login

### ISSUE THREAD

**Issue by rjian** [mozilla/persona#3518]
Having issue on login as my account has been reset on persona or re-created. Issue happens two weeks before as i try to login persona using keon devices on marketplace then persona recognized it as a new email on database, when i login to http://reps.mozilla.org, i cannot edit my profile or see my dashboard. I need to revert my account as i need to login at reps portal to file my report. Already file a bug on reps portal and found out the issue is on persona not on the portal.  To trace the bug i file previously on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=881573

**Comment by jaredhirsch** [comment]
I also don't have access.

**Comment by rjian** [comment]
@jbonacci already update it, but the problem now is not already the device. The persona itself as the account has been reset.. by the way do you have bugzilla account? can you advice me your email address? ill add you to CC on the bug so that you can access it..

**Comment by rjian** [comment]
oh ok. done adding you to the bug.

**Comment by jedp** [comment]
We have not yet switched firefoxos over to point at the production `persona.org` servers.  We plan to do that next week.  But until then, firefoxos is hitting a sandboxed development integration server and will have a separate persona account.

Best thing is to stick with logging in via desktop to manage your marketplace account for now.
