### ISSUE TITLE
Setting password on verification page silently fails

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#352]
This is using dev.myfavoritebeer.org, on Firefox (not Nightly/Aurora).

After setting a password on the verification page (that opens up via the link from the verification email), nothing seems to happen. Pressing enter or clicking the Finish button causes the password manager dialog to come up and ask if you want to save this password, but nothing else. The dialog is still up on the "check your email" page, dev.myfavoritebeer.org is still on the splash (signed out) page.

**Comment by lloyd** [comment]
Tried this on my machine (OSX 10.7.1, firefox 8).  From your description it sounds like I should not be able to successfully create a "new account", and I am.

Try clearing cache?  look for javascript errors?  quick screencast?

**Comment by lloyd** [comment]
(closing for now, please reopen with more details?)
