### ISSUE TITLE
Get firefoxos.persona.org on HSTS pre-load lists

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3521]
@jrgm has observed that we should get `firefoxos.persona.org` on the [Firefox](https://hg.mozilla.org/mozilla-central/file/default/security/manager/boot/src/nsSTSPreloadList.inc) and [Chromium](https://src.chromium.org/viewvc/chrome/trunk/src/net/http/transport_security_state_static.json) HSTS pre-load lists.

@fmarier has already done this with `login.persona.org` in https://github.com/mozilla/browserid/issues/2157

**Comment by fmarier** [comment]
I can take care of this.

@jedp What's that domain used for? Is it just the FxOS equivalent of `login.persona.org`?

**Comment by jedp** [comment]
@fmarier Awesome!  

Yes, that is correct.   This is the fxos equiv of `login`.  It will in fact be a CNAME for `login.persona.org`.

**Comment by fmarier** [comment]
Does it make sense to get that added to Chromium too or just Firefox? i.e. when would a Chromium user want to connect to `firefoxos.persona.org`? CC @jrgm

**Comment by jrgm** [comment]
I don't know the policy considerations or the process for adding to the Chromium STS preload list vs. having this added for only Gecko builds. I'll defer to @jedp on the use case questions.

**Comment by jedp** [comment]
Good point. Chromium probably couldn't care less about this.  Or do we need to be on their list to be on the master list?

**Comment by fmarier** [comment]
Currently the Firefox list is generated from the Chromium one, but there is a patch under review to change this and let us add extra entries if we want to: https://bugzilla.mozilla.org/show_bug.cgi?id=861960

**Comment by jrgm** [comment]
Random comment, but it seems that if the Chromium STS preload list doesn't wish to be the canonical list for browser vendors who opt in to using it, then there should be some other canonical list (not fragmented per-browser-vendor lists). I mean, it's about https origins (websites) wanting to inform browser vendors that they want HSTS-always treatment.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
