### ISSUE TITLE
dev and beta sites not loading dialog on android 2.2

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3522]
1. goto {dev,beta}.123done.org on a Android 2.2 stock browser, or Firefox
2. click the sign in button

actual: dialog opens and spins with loading icon

expected: it should load.  It works on Android 4.0 and desktop as expected.

**Comment by edwindotcom** [comment]
no repro on production sites.

**Comment by jrgm** [comment]
This works on beta (but not dev) for android 2.2 DROID2.

**Comment by jaredhirsch** [comment]
I can repro this problem on dev for another 2.2 handset, the Galaxy S.

**Comment by shane-tomlinson** [comment]
@edmoz - is this due to the cert not being trusted?

**Comment by lloyd** [comment]
we did move from a godaddy SSL cert to a gandi SSL cert...

**Comment by lloyd** [comment]
5 stars to try to figure out what this is.  the downgrade as appropriate

**Comment by jaredhirsch** [comment]
this loads fine for me on beta.123done.org, but dev is busted

**Comment by jaredhirsch** [comment]
@edmoz /me goes off to search for The Creature causing all this 

![image](http://media2.giphy.com/media/LUJOKw7BK9AIg/original.gif)

**Comment by jaredhirsch** [comment]
JS console in my 2.2 handset says "https://static.dev.anosrep.org/w/23c7058d9b/production/en/dialog.js:7 Uncaught SyntaxError: Unexpected token native"

**Comment by jrgm** [comment]
Yeah, me too, although that comes up after a while of just spinning, so don't know if that is the root cause. (Gee, I did not know github had acquired tumbler...).

**Comment by jaredhirsch** [comment]
heh. spinning up an ephemeral instance with unminified resources, hopefully I can get to something more specific.

**Comment by jaredhirsch** [comment]
train-2013.05.22 works fine on an awsbox, train-2013.06.05 does not. git bisecting to find the bad commit.

**Comment by edwindotcom** [comment]
@shane-tomlinson yeah - no idea about the SSL cert stuff. I haven't dug in too deep.  Thanks for spelunking @6a68

**Comment by jaredhirsch** [comment]
`git bisect` claims the bad commit is 15d4c9ab, "Fix primaries on FirefoxOS!".

Digging further.

**Comment by jaredhirsch** [comment]
Turns out "native" is a non-standard reserved word in JavaScript on Android 2.2.

If I replace `info.native` with `info["native"]` right here https://github.com/mozilla/browserid/commit/15d4c9ab#L2R53, it works.

Opening a PR momentarily.

**Comment by lloyd** [comment]
Wow, Jared. Well done.  

Jared Hirsch notifications@github.com wrote:

Turns out "native" is a non-standard reserved word in JavaScript on Android 2.2.

If I replace `info.native` with `info["native"]` right here https://github.com/mozilla/browserid/commit/15d4c9ab#L2R53, it works.

Opening a PR momentarily.

---

**Comment by jaredhirsch** [comment]
let's end this insanity on a **positive** random/WTF note

![](http://media3.giphy.com/media/li9Ph3PqJl2Ew/original.gif)

**Comment by jrgm** [comment]
```
$ git branch --contains 15d4c9a
* dev
  train-2013.06.05
```

So we need a PR from train-2013.06.05 ;-)

**Comment by jaredhirsch** [comment]
This has been deployed to dev.123done.org, and I can load the dialog without problems on my 2.2 handset. @edmoz holler if it's still busted for you.

**Comment by jrgm** [comment]
@edwong when you first filed this issue, you said it was both dev and beta. Neither @6a68 nor I could reproduce this issue on beta (stage). Do you see this on beta.123done.org?

**Comment by edwindotcom** [comment]
I've confirmed dev and beta 123done.org now work as expected on android 2.2 stock browser. Thanks!
