### ISSUE TITLE
button overflow on "Provider makes this easy" screen

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#3525]
The login with button includes domain name.  When domain names are long (or the translated text that accompanies them is long), this button rolls off the left side of the dialog.

![screen shot 2013-06-13 at 12 04 30](https://f.cloud.github.com/assets/39411/649239/d65493ac-d440-11e2-9957-90e7e2f277d3.png)

**Comment by lloyd** [comment]
Here's the same issue from a user with a wierd window manager that forces the dialog fullscreen.  This is a non-standard environment, but still the point about overflowing text is valid:
![d41d8c-1](https://f.cloud.github.com/assets/39411/649259/53b5eca6-d441-11e2-9fd2-871c44b9f054.png)

**Comment by lloyd** [comment]
Same thing, in spanish on chrome / osx
![screen shot 2013-06-13 at 9 55 44 am](https://f.cloud.github.com/assets/39411/649292/de75f89a-d441-11e2-941b-074460487ad5.png)

**Comment by lloyd** [comment]
we should get a recommendation from Ryan Feeley?

can we just have this break and the button expand vertically?

**Comment by jaredhirsch** [comment]
@ryanfeeley thoughts on this'n?

**Comment by ryanfeeley** [comment]
Gah!!! We need a dialog about dialogs. What's the best way for me to get an inventory of these things? Would like to make text more concise, and also consider introducing some truncation rules...

**Comment by jaredhirsch** [comment]
@skinny97214 is a good resource to get you oriented with whatever random wires we have in whatever random places :-)

**Comment by shane-tomlinson** [comment]
@lloyd, @ryanfeeley a mult-line button will require new button graphic resources. As @ryanfeeley said, I'd like to see what we can do by making the text more concise first. That text is fugly.

**Comment by ryanfeeley** [comment]
Doing some basic Firebuggery, it looks like the button will support one line break, no? I should confirm with Horlander about visual issues, but the arrow graphic can support it.

**Comment by ryanfeeley** [comment]
I turned off no-wrap on the button, wrapped a small tag around the string before the domain, and then un-bolded it. Actual text is for position only.
![button](https://f.cloud.github.com/assets/68213/662522/4fa12d9c-d757-11e2-8e57-a5fe8f7a796a.png)

**Comment by ryanfeeley** [comment]
I guess we're ditching this screen, so issue averted? @lloyd @shane-tomlinson @6a68

**Comment by shane-tomlinson** [comment]
@ryanfeeley - we are ditching the initial "makes this easy" screen, but not the "Your <IdP> account has been upgraded to work even better with Persona. We will redirect you to <IdP>." (I forget the new text on this). The upgrade screen still shows this button, though we could remove the IdP text.

**Comment by shane-tomlinson** [comment]
Link to #3671

**Comment by shane-tomlinson** [comment]
Fixed with copy updates in #3684  - closing
