### ISSUE TITLE
[l10n] In french on the "provider makes this easy" screen, no domain name

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#3526]
the `%` character in french is displayed instead of the domain name...

![d65493ac-d440-11e2-9957-90e7e2f277d3](https://f.cloud.github.com/assets/39411/649271/8793d7ae-d441-11e2-8667-240235f5a4db.png)

**Comment by lloyd** [comment]
Confirmed, this appears to be specific to the french translation.  Did we drop a substitution marker?  This should be a really simply 1 char fix in SVN.  Here's spanish, it looks fine:

![screen shot 2013-06-13 at 9 55 44 am](https://f.cloud.github.com/assets/39411/649302/fc871404-d441-11e2-8880-60801eb19a93.png)

**Comment by mathjazz** [comment]
http://viewvc.svn.mozilla.org/vc/projects/l10n-misc/trunk/browserid/locale/fr/LC_MESSAGES/client.po?r1=116913&r2=116912&pathrev=116913

Fixed.

**Comment by lloyd** [comment]
@mathjazz you are wonderful.

**Comment by jedp** [comment]
Merci!
