### ISSUE TITLE
[kpi] Make metrics data available to kpi dashboard

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3529]
It would be great if we could send router-metrics and verifier-metrics data to a kpiggybank collector. It would need to be processed to strip out information for user privacy, just as we do before making the data available to metrics.

cc @lloyd, @shane-tomlinson

**Comment by shane-tomlinson** [comment]
@kparlante - @6a68 says that there may already be a JSONP API for that.

**Comment by jaredhirsch** [comment]
@kparlante @shane-tomlinson Indeed, https://bugzilla.mozilla.org/show_bug.cgi?id=822126 has some backstory.

**Comment by jedp** [comment]
This has been tagged with four stars: How can we close this bug with a PR to browserid?  Does this bug belong in pentaho or kpiggybank?

**Comment by kparlante** [comment]
@jedp: The code to process those files should belong to the identity team, not the pentaho/metrics team, going forward. As the kettle scripts are replaced (python? node?), they could live in browserid, identity-ops, or a new repo.

**Comment by kparlante** [comment]
@6a68: I don't think jsonp from the pentaho sites is the right way to do this -- we really don't need it to route through pentaho at all.

**Comment by kparlante** [comment]
Moving out of browserid repo

**Comment by shane-tomlinson** [comment]
Re-opening as a tracker until we get this merged.

**Comment by jaredhirsch** [comment]
closed by merging #3939 :beers:
