### ISSUE TITLE
[b2g] need to disable primary support on b2g/native UI for now

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3531]
There are a lot bad UX (UI, unable to sign out of primaries) that we encounter with native UI's security model which is very different from all other browsers. We need to disable primaries till we sort out the rollout plan.

**Comment by shane-tomlinson** [comment]
@edmoz - It's not as simple as just disabling primaries, this has _HUGE_ repercussions w.r.t. verifiers. @jedp or @lloyd, wanna fill @edmoz in on all the stuff we talked about?

**Comment by edwindotcom** [comment]
Hi @shane-tomlinson
I logged this mainly as a placeholder so we know the state of primary support on b2g.  It's currently enabled in source code - but waiting for us to point firefoxos.persona.org as a cname to login.persona.org.  I totally understand this issue is big and disabling primaries is hard.  My goal is to force the conversation a bit as we are approaching going live with a merged persona for b2g/desktop.

I'd propose we:
1. get primaries working on firefoxos.persona.org so we can log bugs
2. look through the bugs and triage the impact and blockers (starrage)
3. come up with overall high level strategy/plan (disable, enable, other)
4. agree that we will ship with bugs based on overall strategy balanced with user impact.
5. get the team (dev, qa, product, director) to agree on what we will ship and what bugs might exist.

**Comment by edwindotcom** [comment]
There seems to be momentum to stay the course with primaries on b2g even though there are a number of outstanding issues to discuss.  B2G doesn't have users currently and the team hopes to fix by then.

**Comment by edwindotcom** [comment]
@jedp and I are going to communicate the issues to Product and Pgm to inform B2G about the impact of the plan.

**Comment by edwindotcom** [comment]
dupe of #3566 , closing this one
