### ISSUE TITLE
Oddities with trying to use an AWS stack with train-2013.05.22 & marketplace.firefox.com

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3536]
Five star. Why is desktop using firefoxos.persona.org for forceIssuer? 

STR

Apologies this is a little involved to get set up. This will be using a pre-release production stack, and you'll have to point your local DNS at that stack. To do that do:
- git clone git://github.com/jrgm/dnshook.git
- cd dnshook && npm install
- curl https://gist.github.com/jrgm/0acd36a7846a8886428c > config.json
- On osx, do `sudo networksetup -setdnsservers Wi-Fi 127.0.0.1; sleep 1; sudo node dnshook.js`.
  On other platforms see: https://github.com/jrgm/dnshook/blob/master/README.md
- restart your browser

Anyways, I'm starting with a completely clean browserid profile for these STR, just so there are assumptions of any prior state.
1. Go to https://marketplace.firefox.com/ and click 'Sign in'.
2. So, your browser will have loaded login.persona.org/sign_in, but the content is from train-2013.05.22.
3. Enter someaddress@gmail.com (or any secondary domain), where someaddress is already known to login.persona.org.
4. I see in HttpFox network trace that a call is made to `https://login.persona.org/wsapi/address_info?email=abcabdab%2Bs1%40gmail.com&issuer=firefoxos.persona.org` which returns:
   
   {"type":"secondary","issuer":"firefoxos.persona.org","disabled":false,"normalizedEmail":"someaddress@gmail.com","state":"known"}
5. Enter the password for the account. A post to login.persona.org/wsapi/cert_key is made with `"forceIssuer":"firefoxos.persona.org"`, and a certificate is issued with `"iss": "firefoxos.persona.org"`.
6. An assertion is POSTed to `https://marketplace.firefox.com/api/v1/account/login/?lang=en-US&pro=8afd544c.32.1&region=us` which returns HTTP 401 response with no message. The marketplace UI shows 'Persona login failed. A server error occurred.'. (This error I think occurs because the certificate for `"iss": "firefoxos.persona.org"` was issued with the official keys, but when the assertion is passed along to public DNS's idea of where the /verify service is located, that server (train-2013.04.26) will contact the current home of firefoxos.persona.org which has a different set of keys. Um, I think. Maybe).

**Comment by edwindotcom** [comment]
from conversation with lloyd and jrgm: firefoxos.personatest.org is not acting as a verifier here.  Force issuer inserts that value in localStorage.  jrgm has confirmed that the server has no updates from marketplace.  Lloyd is going to contact marketplace that we're pushing this train soon and to be aware of the situation.

**Comment by edwindotcom** [comment]
we pushed the train live and marketplace fixed the issue.  Issue is no longer repro.
