### ISSUE TITLE
When closing the Signing in dialog from [X] in Opera, the Sign In button from http://beta.myfavoritebeer.org remains grayed out and unresponsive

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#355]
OS: Windows 7
Browser: Opera 11.51 

STR:
1. Launch Opera.
2. Load http://beta.myfavoritebeer.org in an Opera tab.
3. Click on the Sign In button.
4. Close the opened dialog from the [X] button.

When closing the Signing in dialog from [X] in Opera, the Sign In button from http://beta.myfavoritebeer.org remains grayed out and unresponsive. A simple reloading of the page solves the issue. 

This issue doesn't reproduce on Firefox and Chrome (same OS).

**Comment by shane-tomlinson** [comment]
@ioanab - Please file this at the myfavoritebeer repo.

**Comment by ghost** [comment]
Filed at the MyFavoriteBeer repo https://github.com/lloyd/myfavoritebeer.org/issues/26.
