### ISSUE TITLE
User with many accounts, easy to miss the "Sign in" button

### ISSUE THREAD

**Issue by robhudson** [mozilla/persona#3557]
The following is my Persona account window. On Mac, with hidden scrollbars, it's very easy to miss the fact that there's a "Sign in" button below. It's also not obvious where to scroll to find it. It took me by surprise the first time this happened and I was looking where to click to make the sign in "go" before I realized I needed to scroll down.

![persona-many-accounts](https://f.cloud.github.com/assets/1106/675706/cb00e2ce-d8f7-11e2-8d68-19db6961c37c.png)

**Comment by shane-tomlinson** [comment]
Thanks for the submission @robhudson - Closing as a dup of #3266, can you pile on over there?
