### ISSUE TITLE
signing in with gmail.com acct on stage results in 'gmail is not responding dialog'

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3560]
1. sign into beta.123done.org using a user@gmail.com acct

result:
gmail.com is not responding. Please wait a few minutes and try again. 

expected - normal secondary fallback email verification

![screen shot 2013-06-19 at 10 17 19 am](https://f.cloud.github.com/assets/3698618/676365/432136d0-d904-11e2-897d-afea5b526c75.png)

**Comment by edwindotcom** [comment]
this is where we're at with the gmail-bigtent deploy.  You should only get gmail-bigtent if you use dnshook to point to a specific the AWS stack, it looks like we're stuck somewhere in between
https://bugzilla.mozilla.org/show_bug.cgi?id=884483

**Comment by edwindotcom** [comment]
I've confirmed this does not happen on production.

**Comment by jrgm** [comment]
oh, heh. In stage, because the gmail ministack is sharing the same stage database with the regular stage stack, gmail.com is listed in browserid.idp table. So a request from address_info returns 

```
{"type":"secondary","issuer":"login.anosrep.org","disabled":false,"normalizedEmail":"foo@gmail.com","state":"offline"}
```

**Comment by jrgm** [comment]
Although, if I use an gmail.com address that has not been used before, I get 

```
{"type":"secondary","issuer":"login.anosrep.org","disabled":false,"state":"unknown"}
```

So I get the fallback Idp treatment (prompt for a fallback password twice).

**Comment by jrgm** [comment]
And then if I follow through with entering passwords, then loading the email in the same browser I get this error, which is GH-3466

```
Timestamp: 6/19/13 12:31:42 PM
Error: Error: module not started for check_registration
Source File: https://static.login.anosrep.org/v/1759436d12/production/en/dialog.js
Line: 4
```

**Comment by seanmonstar** [comment]
So, a new user who shows up while an idp is `offline` can sidestep the idp and use the fallback. That seems like a bug.

**Comment by jrgm** [comment]
It's a bit of an odd situation, since gmail.com isn't really an idp, and the stage stack is not configured to short circuit that domain as a proxy_idp, so...

**Comment by jrgm** [comment]
@seanmonstar so, I'll leave you to ponder whether this is a real bug or a configuration paradox. For purposes of getting stage in working order, I could manually hack configuration on stage to set proxy_idps: to list the gmail domains. Thoughts?

**Comment by edwindotcom** [comment]
Triage: Gene please rescue us...

**Comment by edwindotcom** [comment]
this is fixed, not sure how, but closing.
