### ISSUE TITLE
User is being rejected using FF 21

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/persona#3562]
A user signing up for backpack.openbadges.org is getting this message,

![screen shot 2013-04-08 at 2 33 51 pm](https://f.cloud.github.com/assets/64711/678574/07a341a6-d93c-11e2-92a2-a7ced8d97690.png)

Anything I should ask him to troubleshoot?

**Comment by callahad** [comment]
@cmcavoy Please let us know what the result of this page is: http://lloyd.github.io/persona-troubleshoot/troubleshoot.html

**Comment by edwindotcom** [comment]
We haven't been able to reproduce this on multiple machines with FF 21, 22, or Aurora.  You might try again with a clean Firefox profile?  Closing for now, please reopen if you can still reproduce with clean profile.
