### ISSUE TITLE
[b2g][request] A URL which clears localStorage/cookies for the Persona origin

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3563]
Currently the way QA and devs are clearing cookies and `localStorage` for FXOS devices is to flash the phone. It would be simple enough to have a URL on the Persona domain which simply blew out `localStorage` and `document.cookie`.

**Comment by mattbasta** [comment]
This would also unblock a lot of geeksphone users who have bunk data in localStorage.

**Comment by seanmonstar** [comment]
Unfortunately, on FxOS devices, the dialog lives in the system app, which has it's own cookie jar and storage. Going to a URL in the browser, even though it could wipe cookie and localstorage, wouldn't affect the dialog in the TrustedUI...

**Comment by mattbasta** [comment]
What is the solution here, then, short of flashing the phones?

**Comment by jedp** [comment]
I've wanted this forever.  I had a bug open here for identity/marketplace tracking: https://bugzilla.mozilla.org/show_bug.cgi?id=823566 ... but i see the bug that blocked has been resolved invalid.

Shall we re-file that bug for gaia core?

**Comment by mattbasta** [comment]
Yes, definitely. I'd really like to see a version which can be triggered by the user, as well. Right now for instance, Geeksphone owners can't purchase apps on the marketplace due to an invalid issuer error, but it's because we can't clear their localStorage because the data is not on our origin :(

Perhaps we can add some sort of code to the Trusted UI which can be triggered externally? Maybe an API method?

**Comment by jedp** [comment]
I think i heard that clearing bookmarks (is it bookmarks?) in the preferences actually has the effect of removing this data?  At least local storage.  We'd still have http-only cookies.  If this is true, then we could reasonably request a more obvious gaia interface for this.

**Comment by shane-tomlinson** [comment]
Relate to #3532

**Comment by jaredhirsch** [comment]
![](http://media0.giphy.com/media/2xgzOPvrWW7hm/original.gif)

**Comment by jedp** [comment]
@6a68 you are UNACCEPTABLLLLLLLLLLLE!!!!!!  UNACCCEPTABBBLLLLLLLLLLLLLE!!!!!!!!

**Comment by jedp** [comment]
Assigning this to me for figuring out what we can do

**Comment by mattbasta** [comment]
Gaia team gets one million years dungeon, no trial.

**Comment by jedp** [comment]
As I mentioned above, there is a workaround for persona, at least, and that is to go to Settings -> App Permissions -> Clear Bookmarks Data.  That seems to blow away localStorage.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
