### ISSUE TITLE
[b2g] "OK" button on Error page does not send cancel event

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3568]
On this provisioning timeout, I click the OK button.  The trusted ui closes, but the RP has not received a cancel event.

We may already have fixed this and our fix hasn't been pushed to the 1.1 builds yet.  Opening this bug to track while I find out.

![2013-06-20-09-04-33](https://f.cloud.github.com/assets/532953/682223/4f3bbeda-d9c3-11e2-9199-4be809a99b41.png)

**Comment by jedp** [comment]
Assigning to me to investigate

**Comment by shane-tomlinson** [comment]
@jedp - is this the same as #3456?

**Comment by jedp** [comment]
Yes, looks like a dupe.  Closing this.
