### ISSUE TITLE
[b2g] intermittent 'improper usage of API: json parse' when signing in with primaries

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3572]
I saw this 2 times on different sign in email but it doesn't repro the 2nd time I execute it.  Here are the vague steps:
1. set pref on phone to use login.anosrep.org
2. sign into beta.123done.org with a user@yahoo.com, logout
3. sign into beta.123done.org with a user@test-moz-idp.org, logout
4. sign into beta.123done.org with a user@gmail.com
   start these steps again over an over a few times.

actual: intermittently you'll see this:
![2013-06-21-16-25-26](https://f.cloud.github.com/assets/3698618/690136/70f4a2a0-dacf-11e2-80c8-198a2345f635.png)

**Comment by jedp** [comment]
@shane-tomlinson and I think this may be due to [Bug 781452 - when window.open is called mozbrowserloadstart and mozbrowserloadend are fired two times](https://bugzilla.mozilla.org/show_bug.cgi?id=781452)

**Comment by shane-tomlinson** [comment]
@jedp - I did a lot of testing yesterday, and I no longer believe window.open is being called twice. Instead, it looks like sessionStorage is being wiped after the system runs out of PMEM.

**Comment by callahad** [comment]
Fix available -- waiting for merge.
