### ISSUE TITLE
Next button on authentication page is not lined up with the right hand side of the input box.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3573]
![screen shot 2013-06-24 at 12 51 58](https://f.cloud.github.com/assets/848085/695121/2029dc58-dcc5-11e2-8e72-51d8bb243dae.png)

**Comment by ozten** [comment]
This is reporting an issue with the native desktop integration?
or will we only use bugzilla for those issues?

or Perhaps [web-desktop] instead?

**Comment by shane-tomlinson** [comment]
@ozten, nope just the normal dialog in any browser, not native integration. I need a better tag, eh?

**Comment by chilts** [comment]
Ok, I've pushed a new version of the branch, which just removes that class.

It was interesting that I was initially looking in `resources/static/dialog/views/` but actually found this one in `resources/views/`. I _think_ it's the correct one. :)

**Comment by chilts** [comment]
@shane-tomlinson ah, sorry, didn't notice you'd closed the PR. Am not sure what you're thinking in terms of a better solution ... ?
