### ISSUE TITLE
Kill native-persona.org

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3576]
1. goto:
   https://native-persona.org

acutal: there's no CSS there

expected: there should be... which makes me thing this isn't a cname to login.persona.org  We need this to unblock any old versions of gaia/gecko.  

here's a related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=886404

**Comment by jedp** [comment]
I propose we switch off native-persona.org.  It was obsolete when we started firefoxos.persona.org (pointing to the ephemeral instance firefoxos.personatest.org).  

We kept it alive as an emergency backup that we could swing the DNS back to if necessary.  But that was never necessary.  When the firefoxos ephemeral instance was stable (this was the Big Merge), we switched native-persona to a proxy to the new firefoxos instance so we could bring people over without any disruption in service.  Finally, months later, when the b2g code all landed in prod, firefoxos was turned into a cname for login.  At this point in time, there should be no longer be any devices pointing at native-persona.

All of the builds that went to vendors are v1.0.1 or later, so they are all using firefoxos.persona.org.  I personally think if there are any old versions of gecko out there that are hitting native-persona, they don't need unblocking - they need upgrading!

/cc @lloyd, @ozten, @shane-tomlinson

**Comment by ozten** [comment]
+1

`kill -9`

**Comment by shane-tomlinson** [comment]
@edmoz, I agree with @jedp - we are still dealing with the repercussions of the firefoxos CNAME, which requires special handling for IdPs to re-write URLs. Adding code to support a very limited number of test devices is not worth the extra long-term maintenance effort.

**Comment by callahad** [comment]
Retitling to "Kill native-persona.org" from "native-persona.org is not mirroring firefoxos.persona.org which can break old b2g installs"

**Comment by jedp** [comment]
fwiw, `var/log` last recorded any action on that machine on May 14.

**Comment by jedp** [comment]
I want to remove this instance, but don't have sign-in to the AWS console to remove the termination protection.

@lloyd or someone, can you kill it?  There may also be a static IP to reclaim.  Instance is:
- `native-persona` {i-211a4c50}:  54.234.233.99 (last log Apr 19)

I have destroyed these:
- `native-persona-123done` {i-470a5c36}: 23.20.36.223
- `notoriousb2g` {i-a74484d5}: 23.22.160.203

**Comment by jaredhirsch** [comment]
@gene1wood @mostlygeek ping. can one of you guys shut down native-persona.org?

**Comment by gene1wood** [comment]
I've stopped this instance. @jedp do you want me to terminate (destroy) it? Shall I release the elastic IP? What about the domain name, what should be done with that?

**Comment by jaredhirsch** [comment]
@gene1wood My read of the bug history is: kill, reap, pillage, plunder. It's over for native-persona.

**Comment by gene1wood** [comment]
I've terminated the instance

**Comment by jedp** [comment]
Thank you, @gene1wood
