### ISSUE TITLE
[b2g] Stuck on Persona loading screen

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#3577]
While trying to buy an app on a hamachi device, I am stuck at the Persona loading screen and I see this error in logcat-

06-25 01:17:37.031 E/GeckoConsole(  795): [JavaScript Error: "downloadable font: download failed (font-family: "Feura Sans" style:normal weight:normal stretch:normal src index:3): bad URI or cross-site access not allowed
06-25 01:17:37.031 E/GeckoConsole(  795): source: https://login.persona.org/v/1a3c73d674/fonts/en/feurasans-regular.woff" {file: "https://static.login.persona.org/v/9dda1efb9f/production/en/dialog.css" line: 0 column: 0 source: "@font-face {...

**Comment by krupa** [comment]
this is on 1.01

**Comment by jrgm** [comment]
See also https://github.com/mozilla/browserid/issues/2906. However a CORS error on loading a webfont does not prevent page load (or should not). The user agent would fall back to some other font.

**Comment by jedp** [comment]
@krupa, was there anything else in the logcat about js files getting blocked?

**Comment by jedp** [comment]
We're wrestling with fonts now.  See also issue #3579

**Comment by shane-tomlinson** [comment]
@jedp - the cname is causing a lot of headaches. 

@krupa - like @jrgm said, this should not _STOP_ the dialog from loading, instead the dialog should fall back to another font. Are there any further log messages, the Javascript Error related to fonts may be a red herring/misnamed since no javascript is involved.

**Comment by jedp** [comment]
@shane-tomlinson yes I agree.

**Comment by krupa** [comment]
I didn't see any error message other than those. Persona is generally very slow on wifi. We can probably attribute the behavior to that and close this issue.

**Comment by shane-tomlinson** [comment]
@krupa - I'd like to keep this open until we can investigate further, at least if this is reproducible.

**Comment by callahad** [comment]
Hi @krupa, @jrgm would like further feedback:
1. Can you get a full `adb logcat` when this happens?
2. Does it happen every time?
3. Does it happen on other sites that use Persona?
4. Have you seen this happen on other handsets?
5. Have you seen this happen on other hamachi devices?

**Comment by jaredhirsch** [comment]
editing title to contain [b2g]

**Comment by jedp** [comment]
Following @krupa 's advice from 14 days ago and closing the issue.
