### ISSUE TITLE
[b2g] Feura Sans not served - cross origin errors when downloading fonts when origin is firefoxos.perona.org

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3579]
@jedp and I are simulating prod in a dev environment with one server with two URLs: primaries.personatest.org is the A record and fx-primaries.personatest.org is a CNAME to primaries.personatest.org. The FirefoxOS device is pointed at fx-primaries.personatest.org. You can see the CORS errors below:

```
E/GeckoConsole( 1296): [JavaScript Error: "downloadable font: download failed (font-family: "Feura Sans" style:normal weight:bold stretch:normal src index:4): bad URI or cross-site access not allowed
....

E/GeckoConsole( 1296): [JavaScript Warning: "downloadable font: no supported format found (font-family: "Feura Sans" style:normal weight:bold stretch:normal src index:6)
E/GeckoConsole( 1296): source: (end of source list)" {file: "https://primaries.personatest.org/v/bed6e74109/production/en/dialog.css" line: 0 column: 0 source: "@font-face {
E/GeckoConsole( 1296):   font-family: "Feura Sans";
E/GeckoConsole( 1296):   font-style: normal;
E/GeckoConsole( 1296):   font-weight: 700;
E/GeckoConsole( 1296):   src: local("Feura Sans Bold"), local("FeuraSans-Bold"), url("https://primaries.personatest.org/v/9ee1ab1f19/fonts/en/feurasans-bold.eot#") format("embedded-opentype"), url("https://primaries.personatest.org/v/ab710ed2da/fonts/en/feurasans-bold.woff") format("woff"), url("https://primaries.personatest.org/v/22fb5eea7e/fonts/en/feurasans-bold.ttf") format("truetype"), url("https://primaries.personatest.org/v/9e85ff5af7/fonts/en/feurasans-bold.svg#Feura Sans") format("svg");
E/GeckoConsole( 1296): }"}]
```

The CORS headers on fonts are by default set to the A record name.

**Comment by jedp** [comment]
Stupid question ... why is this even happening when FeuraSans is on device?  Why doesn't it pick it up locally and just be happy?

**Comment by callahad** [comment]
Are the font family names maybe different?

**Comment by shane-tomlinson** [comment]
@callahad - that is my guess, but Feura Sans is the one I was told to use by the Marketplace dudes. I will re-check.

**Comment by callahad** [comment]
Stomlinson: Looks like you can [separate things with a semi-colon](http://tools.ietf.org/html/rfc6454#section-7.1):

```
7.1. Syntax

   The Origin header field has the following syntax:

   origin              = "Origin:" OWS origin-list-or-null OWS
   origin-list-or-null = %x6E %x75 %x6C %x6C / origin-list
   origin-list         = serialized-origin *( SP serialized-origin )
   serialized-origin   = scheme "://" host [ ":" port ]
                       ; <scheme>, <host>, <port> from RFC 3986
```

**Edit:** [Maybe not, actually](http://www.w3.org/TR/access-control/#access-control-allow-origin-response-header)?

> In practice the origin-list-or-null production is more constrained. Rather than allowing a space-separated list of origins, it is either a single origin or the string "null".

We should:
- [ ] Make sure CORS headers work for static, login, and firefoxos subdomains?
- [ ] See if we can use the font on the phones

**Comment by jaredhirsch** [comment]
as requested by @jrgm:

![](http://24.media.tumblr.com/tumblr_mb95ci00X31qk04bto1_500.gif)

ONE MILLION YEARS DUNGEON for reusing CORS headers

**Comment by jrgm** [comment]
To be specific, that webfonts is piggybacking on the cors headers, and to load a webfont means you have to change the security model of your page.

**Comment by jedp** [comment]
So Marketplace has this: https://github.com/mozilla/zamboni/commit/1e8eff64b4fe179eb551a79e8914a308405a3b4e

We don't have that FeuraSansWeb in our code.  Maybe this is the culprit.

**Comment by jedp** [comment]
Oh awesome:

```
"08:50 david`bgk: [14:29:24] mmh, it looks like FeuraSans has been renamed to FiraSans, too bad I integrated it 2 days ago :("
```

**Comment by shane-tomlinson** [comment]
@jedp - is this fixed by the change to `Fira Sans`?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
