### ISSUE TITLE
Destroy firefoxos ephemeral instances

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3591]
Now that `firefoxos.persona.org` is a cname to `login.persona.org`, it's time to clean up some awsboxen.

Any objections to terminating these from the identity console:
- `firefoxos` {i-d39c59be}: 184.73.36.182 (Still being accessed! how???)
- `fxrp` {i-2a32e64b}: 54.242.214.74 (I can't actually ssh to this)
- `fxrp` {i-a269edc7}: 50.17.109.61 (another by the same name)
- `b2g_2013-04-16-738ece2e` {i-61536d0c}: 54.235.220.29 (last log May 13)

and from the moz svc dev console:
- `firefoxos-test` {i-830f19ec}: 54.235.98.239 (Last log June 9)

I'm puzzled by the log activity in the `firefoxos` instance.  Is someone hitting the IP address directly somewhere?  Really long-lived dns cacheing?

I count between 20 and 40 accesses per day in the last few days.  Not a lot.  But still quite surprising.

**Comment by jedp** [comment]
Perhaps the hits on `firefoxos` are due to issue #3547?

**Comment by ozten** [comment]
That makes sense.

Proposal - Kill DNS and wait a few days for complaints or bugs? Then kill instances afterwards.

**Comment by jedp** [comment]
@ozten that seems like a good pattern in general for terminating our awsboxen.  I like that.  I think you should suggest that to our ops folks for the next time they do a sweep to clean up our ephemeral instances.  It could save a lot of pain.

**Comment by jrgm** [comment]
Note though that (at least) Firefox ignores TTL until it fails to connect to a running server. (Or that's what I'm seeing).

**Comment by jedp** [comment]
@jrgm yes for the `firefoxos` instance, we'll have to just take it down to make people stop connecting.  The DNS has already been changed for almost two weeks.

**Comment by jaredhirsch** [comment]
@jedp bump. are we ready to reap this box?

**Comment by callahad** [comment]
@mostlygeek Can you reap these, please?

**Comment by mostlygeek** [comment]
Done.
