### ISSUE TITLE
IE8: Cachified resources are still re-requested and checked for ETags.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3596]
STR

1) Load up Windows XP with Fiddler and IE8
2) Open Fiddler
3) Visit login.persona.org
4) Place the cursor into the URL bar, press enter without changing the URL
5) Watch the requested resource list in Fiddler. All the JS/CSS is re-requested and ETags checked.

**Comment by jaredhirsch** [comment]
hopefully closed by #3582, I need to verify on dev

**Comment by jrgm** [comment]
This was also https://github.com/mozilla/browserid/issues/1268.

**Comment by shane-tomlinson** [comment]
Thanks for the link @jrgm - closing as dup of an already closed bug.
