### ISSUE TITLE
include.js sets variables = undefined. undefined can be redefined to no longer be undefined.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3598]
See https://github.com/mozilla/browserid/pull/3589#discussion_r4931463. Nice catch @6a68.

**Comment by seanmonstar** [comment]
Including `var undefined;` at the top of the wrapping function will clear out any redefining an RP has done.

``` js
(function() {
  var undefined;
  // WinChan, JSChannel, _include, etc
})();
```

**Comment by callahad** [comment]
We can also use `void 0` to get a real, unadulterated `undefined`

**Comment by shane-tomlinson** [comment]
I dig @seanmonstar's solution, only one line of code changed.

**Comment by shane-tomlinson** [comment]
This is also a problem in provisioning_api.js
