### ISSUE TITLE
beta /wsapi/add_email_with_assertion is returning 503 error

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3611]
1. sign in to beta.123done.org with a yahoo email alias

result:
Error
We are very sorry. The server is under extreme load!

Please close this window and try again.

```
Action: Adding Primary Email Address to User
Network Info: POST: /wsapi/add_email_with_assertion

Response Code - 503
```

**Comment by edwindotcom** [comment]
feels like the root cause is db replication on stage: 
https://github.com/mozilla/identity-ops/issues/87

**Comment by jrgm** [comment]
Closing. The databases were broken in stage.
