### ISSUE TITLE
Persona Popup does not load properly in the Firefox OS Simulator 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/persona#3614]
To reproduce: 
1. Install the simulator add-on, I've used version 3.0.1
2. Open the simulator, open the Marketplace App, navigate to the gear icon and hit Sign-In
3. Here's the result:

![](http://v14d.com/i/51d2f326023e7.jpg)

**Comment by jedp** [comment]
That's grody.  I wonder if you have a dns cache of `firefoxos.persona.org` pointing to the old ephemeral server?  Are there any console logs you can share?

**Comment by edwindotcom** [comment]
I'm kinda back to the cname native-persona so that basic usage works, rather than just breaking them completely.

**Comment by vladikoff** [comment]
@jedp @edmoz can you reproduce this? or is this local to my environment?

**Comment by callahad** [comment]
@vladikoff Everything works for me, using the 4.0pre5 version of the simulator.

**Comment by vladikoff** [comment]
@callahad thank you for checking!

**Also if someone finds this issue, just update your simulator from: [http://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/](http://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/?C=M;O=D)**

I guess the issue is that [https://addons.mozilla.org/en-us/firefox/addon/firefox-os-simulator/](https://addons.mozilla.org/en-us/firefox/addon/firefox-os-simulator/) still has the old Firefox OS Simulator 3.0.1 for download. Just something to be aware off

Here's the 4.0pre5 screenshot:
![image](https://f.cloud.github.com/assets/128755/737874/13bc2d84-e339-11e2-89a0-cf59e2cc672b.png)

Closing because it's not a **browserid** issue.
