### ISSUE TITLE
tooltip error message lacks padding

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3615]
Krupa reports that the error tooltip (fixed in Issue #3496, from [Bug 879626](https://bugzilla.mozilla.org/show_bug.cgi?id=879626)) lacks padding.

I'll try to reproduce and post a screenshot.

**Comment by callahad** [comment]
Possibly obsoleted by the inlining of tooltips?

**Comment by callahad** [comment]
Let's just WONTFIX this in favor of the tooltip changes that Shane has put together?

**Comment by shane-tomlinson** [comment]
Closing as WONTFIX, the fix #3154 will make this moot.
