### ISSUE TITLE
primary upgrade screen shows RP name as "undefined"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3621]
This is going to kick in whenever we turn on GMail Sideshow and MoCo IdP

![12 primary upgrade](https://f.cloud.github.com/assets/848085/744325/62ee0410-e3fa-11e2-8040-95dd0bdb3c3f.png)

STR
1) Using the local dev idp, edit /example/primaries/.well-known/browserid to contain `"disabled": true`
2) Go to example RP, open dialog
3) Edit new email address with @example.domain as the domain
4) Verify email, let dialog close
5) edit /example/primaries/well-known/browserid to remove `"disabled": true`
6) re-open dialog
7) Select email address
8) What's up with that `undefined` for the RP name?

Expected:
RP's name or IP address is displayed in the text

Actual:
RP's name shows up as `undefined`

**Comment by edwindotcom** [comment]
nice catch and fix...  it would be great if we could mock out this workflow as we don't have an easy way to test this as of now. @jrgm any ideas?
