### ISSUE TITLE
ie 10 onmatch erratic behavior

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3631]
I've integrated Persona [here](http://wiki.aok.io) using the watch API and `onmatch`. It works, except in IE 10 on Windows 7 (and other OSes, so I've heard).

Most of the time, onmatch doesn't fire, so I never show my sign in button. Sometimes it does fire, but there is not reduced test case. It's kind of voodoo.

I'm going to switch to using onready instead of onmatch, but we should make an RP that uses onmatch or maybe port 123done to onmatch.

**Comment by callahad** [comment]
onmatch is super broken at the moment, sorry! :( It's been low priority since we haven't documented onmatch externally.

**Comment by ozten** [comment]
Ah, thanks.

I've switched to onready and everything is dandy.

**Comment by callahad** [comment]
Closing this in favor of the meta bug that "Onmatch don't work"

**Comment by jaredhirsch** [comment]
reopening--the meta bug tracks but doesn't close the other three related bugs

**Comment by shane-tomlinson** [comment]
@ozten, @6a68 - testing IE10 on Win7 right now, all looks good against the current dev w.r.t. onmatch. Can you confirm?

**Comment by jaredhirsch** [comment]
@shane-tomlinson I don't have an IE10 VM yet, I'll get one together, try to repro, and update this ticket tomorrow. We didn't do anything related to this in the 2013.07.03 train, judging by the ChangeLog, but that's the only release since the bug was filed. Mysterious indeed.

**Comment by jaredhirsch** [comment]
@ozten I don't think it's documented, but if third-party cookies are disabled, or if the user has "from visited" third-party cookie settings and hasn't visited persona.org before, then only `onready` will fire.

Do you think this might be the source of the bug you observed?

Anyway, the 3p cookie restrictions mean that displaying a button to first-time visitors would have to use `onready`, not `onmatch`. Another way to go might be, "always show the login button unless loggedInUser is truthy and onmatch has fired".

**Comment by ozten** [comment]
I got ride of my test case and VM. Will take me a while to get that back.

**Comment by shane-tomlinson** [comment]
@6a68, @ozten - I downloaded a pre-made VM from MS directly - http://www.modern.ie/en-US/virtualization-tools#downloads

Super easy, legit, and no new licenses are needed.

**Comment by jaredhirsch** [comment]
@ozten I've been unable to repro problems with onmatch in an IE10 VM. I'm going to close this--we'll reopen if it recurs.
