### ISSUE TITLE
[b2g] "Privacy Policy" and "Terms" type size should match the legal copy (FFOS Payments)

### ISSUE THREAD

**Issue by mhanratty** [mozilla/persona#3634]
See Payments Style guide for more info:https://wiki.mozilla.org/Apps/ID_and_Payments#UX
![2013-06-11-11-14-51](https://f.cloud.github.com/assets/4432402/770849/c8383cb6-e8d5-11e2-9da0-7f3fdbf456c4.png)

**Comment by shane-tomlinson** [comment]
@mhanratty - can you specify what the type size should be? The provided link contains a lot of information, but nothing regarding legal.

**Comment by mhanratty** [comment]
I'm not sure what the type size is for "By proceeding..." but the inline links should also have the same type size.

**Comment by shane-tomlinson** [comment]
Fixed with @ozten's PR. Closing.
