### ISSUE TITLE
[b2g] Buttons backgrounds are incorrect, remove the highlight rule (FFOS Payments)

### ISSUE THREAD

**Issue by mhanratty** [mozilla/persona#3635]
Gaia documentation: https://wiki.mozilla.org/File:OWD_01_Lists.jpg
![2013-06-11-11-14-51](https://f.cloud.github.com/assets/4432402/770857/2430b5de-e8d6-11e2-9c77-513059cf4df8.png)

**Comment by shane-tomlinson** [comment]
The hightlight was shown in https://www.dropbox.com/s/6x1ylgn2v06simk/Marketplace_Payments_Flows_Persona_042313.pdf. If there is an alternate styleguide, please specify; the linked doc is what I was using as the source of truth.

**Comment by mhanratty** [comment]
That was my bad on the Persona flows :) Our visual designer Michael Maslaney created a Payments Style Guide that shows them without the highlight. You can find the doc on the payments wiki:

https://wiki.mozilla.org/Apps/ID_and_Payments#UX

**Comment by shane-tomlinson** [comment]
Thanks @mhanratty! I'll do a review next week and get some updated styles out of that doc.

**Comment by shane-tomlinson** [comment]
@mhanratty - whenever I do the updates, could you help me do a review one morning to make sure things are as they should be?
