### ISSUE TITLE
[b2g] Type on the overlay screen should be 14pt with 22px of line height (FFOS Payments)

### ISSUE THREAD

**Issue by mhanratty** [mozilla/persona#3636]
![2013-06-11-11-15-54](https://f.cloud.github.com/assets/4432402/770863/37a940ea-e8d6-11e2-954e-81077d550bb6.png)

**Comment by shane-tomlinson** [comment]
@mhanratty - easy enough, is that spinner the correct size? #3436 says the spinner is too big.

**Comment by mhanratty** [comment]
Spinner for overlay is correct size as implemented--no need to change.
