### ISSUE TITLE
Can't build browserid: i18n-abide@0.0.8-beta4 not in lockdown.json

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3642]
Looks to be an upstream problem.  @ozten  has opened [an npm issue](https://github.com/isaacs/npm/issues/3645) for this

The simple workaround to get browserid to build is:
1. `npm install git://github.com/mozilla/i18n-abide.git`
2. remove `i18n-abide` from `package.json`
3. `npm install`

But I expect all our travis builds and persona-deployer builds will fail until this is fixed :(

**Comment by shane-tomlinson** [comment]
This is a dup of #3639, which was "fixed" in #3640.

**Comment by jedp** [comment]
Also fixed upstream in npm.  

Useful tip from [the npm issue](https://github.com/isaacs/npm/issues/3645): it may be necessary to run `npm cache clean` first.
