### ISSUE TITLE
[b2g] forceIssuer has no effect with primary IdPs

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3644]
STR

First, point your phone at stage by flashing it with a `/data/local/user.js` containing: `pref("toolkit.identity.uri", "https://firefoxos.anosrep.org");`

Then
- Open the UI Tests app
- Scroll down and choose `navigator.mozId tests`
- Enter `login.anosrep.org` in the forceIssuer input box
- Click **Request** (Force Issuer)
- Enter an eyedee.me address

Expected: use of forceIssuer should disable federation

Actual: Persona delegates to eyedee.me for provisioning

**Comment by jedp** [comment]
@ozten and I have tested on desktop and things appear to work as expected, both on dev and in production.  (For production, you can use https://people.mozilla.com/~jparsons/test_firefoxos.html to test the firefoxos.persona.org CNAME.)

So it would appear that we have broken something in our code path on device only.

**Comment by edwindotcom** [comment]
I repro'd this on my b2g inari with v1.1

**Comment by jedp** [comment]
I am a fool.  The UI Tests app was never updated to use the `experimental_` prefix on `forceIssuer` and other friends.  D'oh!

**Comment by jedp** [comment]
Yep, it looks ok with a local patch to the UI Tests app.  Closing this as complete bogus crap.

**Comment by jedp** [comment]
(And I will submit a patch to gaia, yes.)

**Comment by seanmonstar** [comment]
And here I was all excited that `disableFederation` wasn't working.

**Comment by jedp** [comment]
lol

**Comment by jedp** [comment]
Bugzilla bug and PR: https://bugzilla.mozilla.org/show_bug.cgi?id=892299

**Comment by ozten** [comment]
Thanks for the speedy debug and patch!
