### ISSUE TITLE
Meta: onmatch is FUBAR

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3649]
The `onmatch` callback is totally broken. See the following bugs for test cases:
- [x] #3631 
- [x] #3503
- [x] #3463
- [x] #3170

**Comment by jaredhirsch** [comment]
yay checkboxes.

**Comment by jaredhirsch** [comment]
child bugs closed, closing this one out also. :surfer:

**Comment by shane-tomlinson** [comment]
wooohooo!!!
