### ISSUE TITLE
Responsive design for 123done

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3650]
It would be nice to see 123done looking good on FirefoxOS.

This is actually [issue 1](https://github.com/mozilla/123done/issues/1) on 123done :)

Referencing it here so we can track it as part of the Persona + FirefoxOS story

**Comment by ozten** [comment]
I actually already have a patch going. Let me find it.

**Comment by jedp** [comment]
Awesome!  I'll try to review today.

**Comment by jedp** [comment]
That looks great.  Merged!
