### ISSUE TITLE
cannot build browserid rpm due to npm semver changes

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3658]
In GH-3639 and GH-3640, it turned out that npm semver is now stricter on versions like 0.0.8beta4 (it wants the hyphen). 

However, applying the fix in GH-3640 to train-2013.07.03 does not solve a problem with actually building the rpm. 

To allow train-2013.07.03 to be built, @ozten provided this temporary workaround - https://github.com/mozilla/browserid/commit/2a8cb61a8a070ca12f764b70eef4f328a3c67c13 (use a git url and accept any checksum in lockdown). [And I've checked that the bits for i18n-abide were identical to what was built in the rpm for train-2013.06.19].

Anyways, we may need to upgrade to 0.0.8 which @ozten has published. That however had a test failure (and to avoid going further down that path while just trying to get train-2013.07.03 I asked for a workaround).

**Comment by jrgm** [comment]
Since the rpm for train-2013.07.17 cannot be built without a fix for this, this is a blocker.

**Comment by jrgm** [comment]
To be clear, the workaround works and an rpm for train-2013.07.03 has been built. This issue is about the next train.

**Comment by ozten** [comment]
I've started working on this.

**Comment by jaredhirsch** [comment]
@ozten @jrgm can we close this?

**Comment by ozten** [comment]
Fixed!
