### ISSUE TITLE
Improve https://login.persona.org TLS settings

### ISSUE THREAD

**Issue by Skalman** [mozilla/persona#3659]
According to [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=login.persona.org&s=107.23.76.176) there are several things to improve regarding the HTTPS support for https://login.person.org/.

The server should:
1. Mitigate the BEAST attack
2. Not support client-initiated renegotiation (otherwise it's easier to attack via DoS)
3. Support TLS 1.1 and 1.2
4. Investigate and possibly fix PFS (perfect forward secrecy) - SSL Labs is ambiguous: it says that PFS is not active, but goes on to say that it is indeed used for Chrome 27 and Firefox 21

**Comment by callahad** [comment]
@jrgm believes we've got a similar open bug in Bugzilla.

We should find those and close this as a dupe once we've ensured they're all in there.

**Comment by callahad** [comment]
@edmoz to handle the searching.

**Comment by fmarier** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=845316 is the closest one I know of but it's now closed as the main issue (insecure renegotiation) is now resolved.

**Comment by hsivonen** [comment]
> SSL Labs is ambiguous: it says that PFS is not active, but goes on to say that it is indeed used for Chrome 27 and Firefox 21

Firefox Nightly now has UI that shows the cipher suite in use. Click the lock to show Larry, click More Information and look under Technical Details. I get TLS_RSA_WITH_CAMELLIA_256_CBC_SHA in Nightly. In Chrome, I get AES instead of Camellia.

So no forward secrecy. :-(

**Comment by fmarier** [comment]
Here's the ticket for improving the cipher suite: https://bugzilla.mozilla.org/show_bug.cgi?id=904077

It's marked as resolved because we can't do any better with Amazon ELB.

**Comment by hsivonen** [comment]
Considering the nature of Persona, it seems to me that forward secrecy should be regarded as an important feature. If it's not possible to do better with Amazon ELB, maybe it's not appropriate to use Amazon ELB for Persona.

**Comment by fmarier** [comment]
As mentioned on bugzilla, opsec is talking to Amazon to see whether they could upgrade their ancient version of OpenSSL given that Persona is not the only affected website. Failing that, you're right, we shouldn't terminate TLS on ELB.

**Comment by jvehent** [comment]
PFS is regarded as a very important feature, and OpSec is working with the differents teams to upgrade our SSL terminations. Hopefully, ELBs and the various TLS vendors will pick up the pace and accelerate their integration of ECC, GCM, TLS1.2 and OCSP Stapling. Failing that, there is always the possibility to terminate TLS ourselves, but that requires some engineering time.

As a side note, github issues are hard to track. Bugzilla is really preferred for everything security related.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
