### ISSUE TITLE
lock icon animation overlaps site name

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/persona#366]
beta.myfavoritebeer.org, on Mac, is 220px wide.  On login, when the lock icon is animated rightwards, the lock finishes under the sitename and it looks kinda messy.

Perhaps we should a) wrap the sitename, b) treat the overflow somehow (dangerous, nevermind, don't do that), c) put the lock icon into a div that will overlap the text more attractively (perhaps a floating textured div with a dropshadow).

**Comment by lloyd** [comment]
this relates to an issue we were discussing earlier.  Because keygen occurs during that animation (not technically _during_, but whatever), we need a larger change here that displays a non-functional progress indicator to the user.  We should rethink the anim to address both issues in one breath.

**Comment by shane-tomlinson** [comment]
#399 is to improve the user experience during key generation.
