### ISSUE TITLE
Cancelled GET requests from communication_iframe in Chrome

### ISSUE THREAD

**Issue by lrowe** [mozilla/persona#3663]
My site and myfavoritebeer.org is showing multiple canceled GET requests initiated by the communication_iframe in the network panel on Chrome. The requests are for frame resources, including: dialog.js, dialog.css, grain.png, persona-logo-transparent.png, arrow_grey.png, ...

Firefox doesn't seem to be affected. Clearing my cache does not help.

To reproduce using Chrome:
1. Open the network panel.
2. Navigate to myfavoritebeer.org
3. Click the "Sign in with Persona" button"
4. Observe the canceled get requests in red.

**Comment by vladikoff** [comment]
Reported in https://github.com/mozilla/browserid/issues/3561 Thanks!
