### ISSUE TITLE
[B2G] [Leo] [Marketplace] Javascript error when attempting to access Persona's Terms or Privacy Policy

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#3674]
Description:
When selecting the Terms or Privacy Policy links in the Persona login page, the user is given a JavaScript warning instead of the appropriate page.

Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=895017.

Repro Steps:
1) Updated Leo to Build ID: 20130717070237
2) Launch the Marketplace app.
3) Select the gear icon in the upper right corner, then "Sign In / Sign Up".
4) When the sign in page appears, tap any of the Terms or Privacy Policy links.
5) Observe the page that appears.

Actual:
An error message appears stating "Sorry, you need JavaScript to access the Marketplace".

Expected:
The Terms of Use or Privacy Policy pages appear depending on the link you selected.

Environmental Variables
Build ID: 20130717070237
Gecko: http://hg.mozilla.org/releases/mozilla-b2g18/rev/582e3a7018b0
Gaia: c506c50adaaebcf729ac3c27887ba2931ab79040
Platform Version: 18.1
RIL Version: 01.01.00.019.164 

Notes:
Repro frequency: 75%
Q Analysts Team Priority: Pri 2
See attached screenshot and logcat logs

**Comment by shane-tomlinson** [comment]
@jds2501 - There are two issues going on here, first, we are showing the TOS/PP agreements in a sandboxed iframe that does not have Javascript support. We use a sandboxed iframe to prevent RPs from attempting to frame break from the TOS/PP pages and take over the dialog. 

Second, the string "Sorry, you need JavaScript to access the Marketplace" is not in our repo. I would guess that marketplace has a `<noscript>` tag in its TOS/PP page with that message. 

Enabling Javascript in the iframe would have negative security consequences, can we see if the marketplace team can remove this message from their TOS/PP agreements? @mattbasta, @kumar303, @potch

**Comment by mattbasta** [comment]
The message is inside a noscript tag. We use JS to download the appropriate
localized document since we're not yet a true packaged app.

**Comment by shane-tomlinson** [comment]
@mattbasta - thanks Matt. 

Our Javascript concern is with frame busting and with devious iframes trying to do something nefarious with JS. If an RP can frame bust, they can redirect the phone's system dialog wherever they want. 

Can l10n be done a different way, perhaps front loading the locale in the URL that is passed to termsOfService and privacyPolicy and rendering those documents directly? 

We had to modify how our own TOS/PP was displayed to remove JS, we feel your pain here too.

**Comment by mattbasta** [comment]
If we give off-origin URLs for the ToS/PP, will Persona still load them?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
