### ISSUE TITLE
Yahoo OpenID sends wrong SSL cert

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3676]
Yahoo bridge is broken because Yahoo is serving the wrong SSL cert for their OpenID endpoint:

![Yahoops!](https://f.cloud.github.com/assets/24193/815777/f74cb2dc-ef30-11e2-8046-aee3b6a83278.png)

**Comment by callahad** [comment]
This is an upstream issue -- Yahoo OpenID auth is broken web-wide, including on [StackOverflow](http://stackoverflow.com/users/login) and [Janrain](https://dashboard.janrain.com/signin).

**Comment by callahad** [comment]
I suggest we kill the Yahoo bridge and let things fall back to the fallback.

**Comment by callahad** [comment]
@gene1wood ?

**Comment by callahad** [comment]
Gene is getting in touch with operations at Yahoo to try to resolve before we pull the plug on our bridge.

**Comment by gene1wood** [comment]
I've had a friend contact their ops team, hopefully we'll hear back soon

**Comment by callahad** [comment]
If we don't hear anything in the next 20-ish minutes, we'll manually flip the switch on our bridge and route people back through the email-based fallback.

**Comment by callahad** [comment]
Ticket has been escalated at Yahoo, they're aware of the problem.

**Comment by callahad** [comment]
We've disabled the Yahoo bridge. Users should be flowing through the fallback flow.

We'll leave it like this overnight and turn it back on once Yahoo has fixed their certificate.

**Comment by callahad** [comment]
(Leaving this as a 5-Star issue so we don't forget to turn it back on)

**Comment by gene1wood** [comment]
Internal note : I've disabled the yahoo bridge by manually modifying the config and restarting services. To re-enable the bridge all that need be done is have chef re-converge the system and revert this changed config setting. This can be done by running `chef-solo -c /etc/chef/solo.rb -j /etc/chef/node.json` on each of the 6 bigtent servers

**Comment by callahad** [comment]
@gene1wood Yahoo is back online -- Please resolve at your leisure.

**Comment by gene1wood** [comment]
I've reverted the config change which disabled yahoo bigtent. I've tested and confirmed I can again login with a yahoo account.

**Comment by callahad** [comment]
I've also verified (along with the alias / PIN hotfix). All systems normal. Closing this bug.
