### ISSUE TITLE
Make the default RP backgroundColor ligher

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3677]
Per Jon of Voost:

> right now, the background involves color and an image. I'd hate to lose the grey grainy image as I think it is pretty nice right now.

If the site doesn't specify any backgroundColor preference, maybe we could bring back the grain and a slight tint to keep the defaults more aesthetically pleasing / interesting?

**Comment by shane-tomlinson** [comment]
meh. I'd rather aim for consistency. The background adds bytes to the download and slows down rendering. Can we get shorelander's input?

**Comment by seanmonstar** [comment]
I like the solid color. It's very holo/metro/ios7.

**Comment by callahad** [comment]
I like the solid color, too. When used. But to be fair, our default styling feels uncomfortably plain, to me. Maybe even a bit of a regression?

![screen shot 2013-07-18 at 7 42 56 am](https://f.cloud.github.com/assets/24193/819011/990f6666-efa7-11e2-9350-1196df7ff35c.png)

![screen shot 2013-07-17 at 10 48 29 pm](https://f.cloud.github.com/assets/24193/819015/a5538eca-efa7-11e2-9ebd-65d551b2238c.png)

**Comment by callahad** [comment]
Of course, for sites that take advantage of it, backgroundColor can be a HUGE win:

![backgroundcolor-ting](https://f.cloud.github.com/assets/24193/819022/ea2a9b38-efa7-11e2-8e91-24f60d0987f3.jpg)

**Comment by shane-tomlinson** [comment]
This is going to come down to a matter of taste (I'm in favor of the spartan look), which is why I'd like to get a designer involved.

**Comment by jaredhirsch** [comment]
-1 on making changes to appease a single RP, that's not how good coherent design happens

**Comment by shane-tomlinson** [comment]
Word from Shorelander:

> Hi Shane,
> 
> I don't think we should add the noise back. As far as default colors, if the darker grey is default then I would 
> suggest lightening it up. Still darker than the left, but lighter than it is now.
> 
> Thanks
> - Stephen

Changing the title of this bug "Make the default RP backgroundColor ligher"
