### ISSUE TITLE
[train-2013.07.17] translate not displaying localized versions of files

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3681]
@mathjazz Heads up, the translate server is doing something funny this morning. I'm looking into it now.

**Comment by jaredhirsch** [comment]
I'm not sure what was wrong, but spinning up a new server fixed it. @mathjazz please reopen if you see that it's broken again.

**Comment by mathjazz** [comment]
Hey @6a68,

As reported by localizers: https://translate.personatest.org is displayed in English, not localized, and http://translate.123done.org only partially localized.

**Comment by jaredhirsch** [comment]
Hey @mathjazz - Thanks for the ping.

**Comment by jaredhirsch** [comment]
@mathjazz - Whoops, hit the green button too soon. @ozten helped me figure out the translate environment problems this morning, and I'm working on a permanent fix. We have a lot of new strings and the weekend is coming up, so I'm going to be sure to get it fixed by end of day today for our awesome localizers.

**Comment by jaredhirsch** [comment]
@mathjazz I've pushed some updates to the translate environment, and it should be fixed. Please reopen this bug if problems recur and I'll look.
