### ISSUE TITLE
Copy when returning from IdP is confusing and verbose.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3691]
@ryanfeeley agrees. He suggests changing it to look like:

![screen shot 2013-07-22 at 19 41 01](https://f.cloud.github.com/assets/848085/837039/5741da66-f2fe-11e2-8d95-cb5607e36f0c.png)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I know we don't have the lock yet:

![screen shot 2013-07-22 at 20 01 44](https://f.cloud.github.com/assets/848085/837174/6456c2b8-f301-11e2-8cf7-cacacca49f9f.png)

**Comment by ryanfeeley** [comment]
Lower budget option is to animate the ellipsis like:

Signing you in...
Signing you in
Signing you in.
Signing you in..
Signing you in...
Signing you in
Signing you in.
Signing you in..
Signing you in...
etc.

**Comment by callahad** [comment]
Closed #3708 as a dupe.
