### ISSUE TITLE
I'm unable to login to etherpad with LDAP

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/persona#3693]
Trying to open a particular [protected mopad](https://apps.etherpad.mozilla.org/ep/account/sign-in?&cont=https%3a%2f%2fapps.etherpad.mozilla.org%2fsupporting-developers-meetup), I enter my email, then enter my ldap credentials, then loop back to being prompted to enter my email, then my ldap AGAIN, then loop back endlessly and can never get in.  I'm seeing a HTTP 403 in the console when an HTTP POST is made "[23:29:18.912] POST https://login.mozilla.org/api/provision [HTTP/1.1 403 Forbidden 37ms]".  Also, if I start firefox with a different profile I can log in, just not with my usual one.

**Comment by seanmonstar** [comment]
A 3rd party cookie needed. You probably don't allow them, but a new default
profile does allow from visited. If you add an exception for
login.mozilla.org, it should work.

We have better messaging in development.

**Comment by nickdesaulniers** [comment]
Thanks @seanmonstar , adding login.mozilla.org to the exceptions of third party cookies did indeed fix the problem.  I'll leave it up to you to close this, maybe once a better error message reaches production.

**Comment by callahad** [comment]
The better error message has been merged, will go live in ~2 weeks. Closing this for now.

Thanks for the report, Nick.
Thanks for the quick response, Sean.

**Comment by shane-tomlinson** [comment]
FWIW, linking to #3520

**Comment by erikvold** [comment]
I never want to allow third party cookies, and Persona worked without them before recent changes, so I consider this bug unresolved, and the product is useless to me if I have to add 3rd party cookie exceptions.

**Comment by nickdesaulniers** [comment]
Can we ship FF with this exception built in, or is that taking choice away from the user?

**Comment by erikvold** [comment]
> Can we ship FF with this exception built in, or is that taking choice away from the user?

That is taking the choice away from the user, and browserid is supposed to work on the other browsers too so this question is moot.

**Comment by nickdesaulniers** [comment]
As a heads up, the error message says to add an exception for "mozilla.com" not "login.mozilla.org"

**Comment by nickdesaulniers** [comment]
For the love of god, this is driving me nuts!

**Comment by seanmonstar** [comment]
@nickdesaulniers i opened a new issue describing this newer problem in #4022
