### ISSUE TITLE
Suggested "forgotten username" implementation?

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3698]
Hi all

We've encountered a user that's forgotten the email that they use to sign in to the Marketplace with. Is there a suggested implementation for this? Or is this something that we should leave up to Persona to eventually implement?

**Comment by shane-tomlinson** [comment]
Link to #1500

**Comment by callahad** [comment]
Issue #1500 should address some of the corner cases where this could happen, but generally, no, we don't have plans to help users rediscover completely forgotten identities.

We'd be very interested in what you come up with, though!
