### ISSUE TITLE
Need to present and have user agree to TOS & privacy policy

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#37]
Sad, but true.

**Comment by lloyd** [comment]
need specifics.  are links at the bottom of the dialog and a default unchecked box sufficient?  are links the same as on all other moz sites?

**Comment by benadida** [comment]
Yes, this is required. We should add this at least at the time that users set a password.

@skinny97214 ? I know this is going to make you sad, but we don't have a choice.

**Comment by skinny97214** [comment]
Proposal: sites can choose between three options.
1. no checkbox
2. checkbox prechecked
3. checkbox unchecked

**Comment by benadida** [comment]
@skinny97214 sorry I'm talking about something else. This is _our_ TOS & privacy policy, not the site's. So when we prompt for a user password to set up their BrowserID account, we need them to affirmatively opt into our ToS and Privacy Policy. Sadly, we don't have the choice of (1) or (2). It has to be (3).

**Comment by lloyd** [comment]
dup of issue #841
