### ISSUE TITLE
Gmail bridge failing on Bugzilla

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3704]
When I try to log into Bugzilla with my Gmail address, I get the following error:

> An error occurred during communication with the Persona servers:
> issuer 'gmail.login.persona.org' may not speak for emails from 'gmail.com'

I am not able to proceed.

Other sites (123done, Ting, MDN, Voost, Marketplace, Addon Builder, Discourse, DrupalPersona.me) all work fine.

**Comment by callahad** [comment]
deimidis in IRC is experiencing the same issue.

**Comment by callahad** [comment]
Is Bugzilla somehow hitting an old stack whose verifier doesn't include the gmail bridge?

**Comment by callahad** [comment]
cc @gene1wood @jrgm

**Comment by jaredhirsch** [comment]
@callahad bugzilla.moz.org has the verifier IP hard-coded in /etc/hosts. See https://bugzilla.mozilla.org/show_bug.cgi?id=875873 for background, and https://bugzilla.mozilla.org/show_bug.cgi?id=897499 for the bug tracking this specific issue.

**Comment by gene1wood** [comment]
Specifically, hardcoded to the deprecated PHX1 installation
