### ISSUE TITLE
no message provided during arrow animation when a user successfully authenticates.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3708]

**Comment by shane-tomlinson** [comment]
Link to #3691

**Comment by shane-tomlinson** [comment]
It would be awesome to unify this and the updates for #3691.

**Comment by callahad** [comment]
Closing as dupe

**Comment by shane-tomlinson** [comment]
Re-opening since the resolution to #3691 (#3692) got merged.

@ryanfeeley and I spoke yesterday, he says that displaying the same message as displayed for primaries is a good first step into making this stage of the signin flow more awesome.
