### ISSUE TITLE
[chrome] box-shadow does not show above and below the arrow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3712]
Primarily a problem on Android tablets, but also affects desktop if the user resizes the window.

![screen shot 2013-07-25 at 15 24 51](https://f.cloud.github.com/assets/848085/856121/1be88af2-f536-11e2-9b32-dc0c118a49ea.png)

**Comment by callahad** [comment]
Only happens in Chrome. All other browsers are happy with it.
