### ISSUE TITLE
Some files are missing copyright headers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3715]
The following files seem to be missing copyright headers (or at least didn't match the default copyright header exactly (and case sensitive)):

No copyright found in: ../browserid/lib/boolean-query.js
No copyright found in: ../browserid/lib/cef_logger.js
No copyright found in: ../browserid/lib/db/dbutils.js
No copyright found in: ../browserid/lib/email.js
No copyright found in: ../browserid/lib/static_resources.js
No copyright found in: ../browserid/lib/well-known-parser.js
No copyright found in: ../browserid/resources/static/build/code_version.js
[snip]
No copyright found in: ../browserid/resources/static/dialog/js/misc/screen_size_hacks.js
No copyright found in: ../browserid/resources/static/include_js/_include.js
No copyright found in: ../browserid/resources/static/include_js/_jschannel.js
No copyright found in: ../browserid/resources/static/include_js/_winchan.js
No copyright found in: ../browserid/scripts/check_l10n_config.js
No copyright found in: ../browserid/scripts/compress-worker.js
No copyright found in: ../browserid/scripts/deploy.js
No copyright found in: ../browserid/scripts/every_locale.js
No copyright found in: ../browserid/scripts/generate_ephemeral_keys.js
No copyright found in: ../browserid/scripts/postinstall.js
No copyright found in: ../browserid/scripts/show_config.js

And my cheap and dirty Node.js-based copyright checker code:

``` javascript
#!/usr/bin/env node

var fs = require("fs")

var shell = require("shelljs");

var COPYRIGHT_HEADER = "* This Source Code Form is subject to the terms of the Mozilla Public\n"+
" * License, v. 2.0. If a copy of the MPL was not distributed with this\n"+
" * file, You can obtain one at http://mozilla.org/MPL/2.0/.";

shell.find("../browserid").filter(function (file) {
    // We only care about .JS files, presumably.
    return file.match(/\.js$/i);
}).filter(function (file) {
    // Ignore if it's a node module, a test file, or an example file.
    return  !file.match(/\/(node_modules|tests?|automation-tests|example)\//i);
}).forEach(function (file) {
    var data = fs.readFileSync(file, "utf8");
    if (data.indexOf(COPYRIGHT_HEADER) === -1) {
        console.log("No copyright found in: %s", file);
    }
});
```

**Comment by shane-tomlinson** [comment]
Thanks @pdehaan - the files in browserid/resources/static/common/js/lib are all external libraries and should _not_ receive the MPL.

**Comment by pdehaan** [comment]
Thanks @shane-tomlinson. I removed them from the bug report above and will paste them here for history/giggles:

No copyright found in: ../browserid/resources/static/common/js/lib/base64.js
No copyright found in: ../browserid/resources/static/common/js/lib/dom-jquery.js
No copyright found in: ../browserid/resources/static/common/js/lib/gobbledygook.js
No copyright found in: ../browserid/resources/static/common/js/lib/highlight.js
No copyright found in: ../browserid/resources/static/common/js/lib/html5shim.js
No copyright found in: ../browserid/resources/static/common/js/lib/hub.js
No copyright found in: ../browserid/resources/static/common/js/lib/jquery-1.7.1.min.js
No copyright found in: ../browserid/resources/static/common/js/lib/jschannel.js
No copyright found in: ../browserid/resources/static/common/js/lib/json2.js
No copyright found in: ../browserid/resources/static/common/js/lib/module.js
No copyright found in: ../browserid/resources/static/common/js/lib/urlparse.js
No copyright found in: ../browserid/resources/static/common/js/lib/winchan.js

**Comment by jaredhirsch** [comment]
@pdehaan: thanks for calling this out. pull requests welcome :-)

**Comment by pdehaan** [comment]
Pull request submitted.

**Comment by pdehaan** [comment]
Confirmed.
Reran my script and now only getting one warning:
browserid/scripts/aws_enable_locales.js

I'll file a new bug and pull request. #copyrightallthethings
