### ISSUE TITLE
login/logout/match doesn't fire on first visit with "from visited" cookie settings

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3717]
If you clear your FF 22 session, then load something like [this fiddle](http://jsfiddle.net/XgVD5/9/), only onready will fire--regardless of what loggedInUser is set to.

This is a third-party cookie edge (case that runs counter to the spec.

Not sure how we should handle this. It seems like RPs might reasonably assume that some callback would be fired on page load.

**Comment by jaredhirsch** [comment]
Should we provide an `onerror` callback, so RPs can display error states if, say, localstorage is disabled? :-\

**Comment by callahad** [comment]
I think this is a known issue. The docs could possibly be improved around it.

I believe we're only committing to firing onready automatically. The others are "maybes."

I'd also be open to reevaluating that stance, but I do kind of wonder how many other cases / callbacks we might want/need?

**Comment by jaredhirsch** [comment]
Hmm. I was thinking of this in terms of the specs with `onmatch` added, which claim that one of three things will happen (`onmatch`, `onlogin`, or `onlogout`), followed by `onready`.

Maybe we close this and mention something in the spec?

**Comment by jaredhirsch** [comment]
@callahad - Oh, shane made the same point you just made in the discussion of #3417. Closing.
