### ISSUE TITLE
"Account upgraded!" message showing too often?

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3724]
I've seen the account upgraded message several times with my gmail address. I should only see it once, right?

**Comment by jaredhirsch** [comment]
@callahad should we move this to the sideshow repo?

**Comment by seanmonstar** [comment]
Sideshow doesn't handle this at all. It's just an IdP. This message is
shown by browserid, when comparing states in the DB.

**Comment by callahad** [comment]
Closing as not reproducible
