### ISSUE TITLE
backgroundColor clashes with ToS/PP links

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3725]
Screenshot: 
![Screenshot of backgroundColor and link color with too little contrast](https://f.cloud.github.com/assets/24193/865791/787e8c2a-f645-11e2-8348-b110a62c7e95.png)

Suggested resolution: set the link color to the [complement](https://en.wikipedia.org/wiki/Complementary_color) of backgroundColor.

**Comment by zaach** [comment]
We could also use black/white for light/dark backgrounds if complementary colors end up being too intense or hard to read.

**Comment by martin308** [comment]
either would be fine with me
