### ISSUE TITLE
siteLogo has an appended slash

### ISSUE THREAD

**Issue by martin308** [mozilla/persona#3726]
When you specify a siteLogo then a trailing slash is appended to the img src which is incorrect. I could fix this on my end but it seems that if I provide a path then that is what should be used.

I have traced this down to the urlparse.js, the regex in there does not accommodate a URI without a username:password specified before the domain.

Happy to provide more information if required. My regex skills are not good enough to handle this one! :cry: 

```
/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/
```

**Comment by callahad** [comment]
Paging @SamPenrose :) Also, debuggex.com might be good for understanding and tweaking our regexes.

**Comment by SamPenrose** [comment]
The current unit tests seem to idicate that this is no longer happening. See e.g. https://github.com/SamPenrose/browserid/blob/dev/resources/static/test/cases/dialog/js/modules/validate_rp_params.js#L263 and following "allowed" tests. Close out?

**Comment by martin308** [comment]
Cool, that looks good to me :smile: I see there is support for CDN served logos in those test cases as well! :+1: Any idea when those changes will be merged in/deployed?

**Comment by SamPenrose** [comment]
Not sure. The branch I was working in got pretty mangled, and I'm redoing it. Also one of the lead developers is out ATM. Hoping to have a PR ready tomorrow.

**Comment by callahad** [comment]
@martin308 Expect 2-3 weeks from merge until we get into production.

**Comment by martin308** [comment]
cool, thanks. This can be closed then
