### ISSUE TITLE
[login.mozilla.org IDP] Content Security Policy: Directive inline script base restriction violated @ https://login.mozilla.org/sign_in

### ISSUE THREAD

**Issue by dholbert** [mozilla/persona#3730]
STR:
1. Visit https://login.mozilla.org/sign_in in Firefox Nightly
2. Inspect your Browser Console. (Ctrl+Shift+J). Make sure the "Security" button is pressed (so you'll see Security errors)

ACTUAL RESULTS: This error appears:
Content Security Policy: Directive inline script base restriction violated @ https://login.mozilla.org/sign_in

Looks like we're serving content that violates the CSP headers we're sending, or something...?  I suspect it might be that we have:
`<script src="https://login.persona.org/authentication_api.js"></script>`
which pulls in a cross-domain script, and depending on the CSP headers that login.mozilla.org provides, that might not be kosher.

**Comment by dholbert** [comment]
Hmm.  curl -vvv says we're setting this CSP header:
`Content-Security-Policy: default-src 'self' https://login.persona.org`
which looks like it should let us load cross-domain scripts from Persona, but I'm not sure. So maybe I'm incorrect about what the error is pointing to.

**Comment by dholbert** [comment]
Actually, per https://bugzilla.mozilla.org/show_bug.cgi?id=630882#c5 , it looks like it's possible this is is caused by a load _performed by_ any of the scripts we're pulling in.  (Possibly jquery, though that bug comment indicates that jquery fixed an issue like this a few years ago.)

**Comment by birtles** [comment]
I'm seeing this too.

Furthermore, when logged into a Persona site using my mozilla.com address I see an identical set of errors but this this originating from the 'provision' script (https://login.mozilla.org/provision, which I happen to notice pulls in jQuery).

**Comment by shane-tomlinson** [comment]
Moved to the vinz-clortho repo, closing. Thanks for the report, please pile on over there!
