### ISSUE TITLE
[login.mozilla.org IDP] Security Error: Content at https://login.mozilla.org/ may not load data from https://login.persona.org/sign_in

### ISSUE THREAD

**Issue by dholbert** [mozilla/persona#3731]
STR:
1. Ctrl+Shift+J to open Browser Console
2. (optional) Click buttons to turn off all logging except for "JS"
3. In a browser window, visit http://123done.org/
4. Click "Sign in with Persona"
5. Type an @mozilla.com address into the persona popup.
6. inspect your Browser Console window.

ACTUAL RESULTS:
This error message (among others):
Security Error: Content at https://login.mozilla.org/ may not load data from https://login.persona.org/sign_in.

Mozilla/5.0 (X11; Linux x86_64; rv:25.0) Gecko/20130726 Firefox/25.0

**Comment by shane-tomlinson** [comment]
Dup of the closed #1078

**Comment by jrgm** [comment]
Closing as dup.

**Comment by dholbert** [comment]
The dupe target was closed as "I can no longer reproduce" a year ago, FWIW, whereas this one here was opened 2 months ago (and is still reproducible).

I guess I'll reopen the dupe target.
