### ISSUE TITLE
Persona dialog opens in new tab as opposed to new window on UX Nightly for OSX

### ISSUE THREAD

**Issue by mikeconley** [mozilla/persona#3737]
Not sure if this applies to Nightly as well as UX Nightly, but I've been experiencing this for some time now (I've also seen chatter about the bug in IRC, which makes me think this might be a dupe).

STR - on an OSX machine, using UX Nightly, open a Persona dialog.

ER: Dialog should open in a new window

AR: Dialog opens in a new tab

The new tab works as you'd expect - but I think the new window is what's desired here.

**Comment by vladikoff** [comment]
Fixed this for @mikeconley  :) 
Issues with `browser.link.open_newwindow.override.external`
