### ISSUE TITLE
bumping jschannel version broke dev against IE8

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3740]
see https://github.com/mozilla/jschannel/issues/16 :sadface:

**Comment by jrgm** [comment]
Driveby comment. We should set up a jenkins job that runs:

```
./scripts/run-all.js -e dev --parallel 12 --platform all -i 1 -t frontend-qunit-test
```

Yes, the deployer/jenkins asynchronous issues are a problem, but perhaps a little preflight check and retry script would dampen out false noise; the frontend-qunit-test itself is not noisy to my knowledge (aside from occasional timer-based test failures on the slow IE8 JS engine).

**Comment by jaredhirsch** [comment]
@jrgm sounds like a separate bug, I've opened #3745 to cover that feature request :)
