### ISSUE TITLE
Feature: BrowserID  datastore

### ISSUE THREAD

**Issue by ir-g** [mozilla/persona#3746]
BrowserID/Mozilla Persona is an impressive and helpful web application, which caters to the great need for an Open, Secure SSO system. I would like the addition of a feature to provide data storage, to enable data to be stored online, across computers, via Persona.

The aim would be for the data to be stored as plain text, accessible in JavaScript as a variable, easily managed as JSON data, capable of databasing uses.

This would be especially useful for Static web applications, where databases are non-existent, except for Web SQL(neither cross-device or widely supported).

_This data would only be accessible to the app when they[the user] are logged in, and the user should be able to see this data at [persona.org](http://persona.org), under an app manager section._

_One thought for integration of this idea would be adding an App registration system, which could provide beneficial features, like this data system._

**Comment by shane-tomlinson** [comment]
@isaacrg - We are already on it. Please see https://github.com/mozilla/picl-server and the other mozilla/picl-\* related projects.
