### ISSUE TITLE
Use custom-built jQuery to minimize file size

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3749]
Persona loads `https://login.mozilla.org/js/lib/jquery.min.js`, which includes all jQuery features.

Instead, Persona should load a version of jQuery built using [the jQuery grunt script](https://github.com/jquery/jquery#how-to-build-your-own-jquery). This allows you to eliminate unneeded or unused features, especially legacy or deprecated functions. For Marketplace, this cut the size of the minified and gzipped jQuery by over half.

**Comment by shane-tomlinson** [comment]
Dup of #2306, closing. Thanks @mattbasta!
