### ISSUE TITLE
verification looks bad at low widths

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#3752]
When viewed in gmail especially or with a width less than 600 pixels, verification emails look bad.  I hit this accidentally on a 15" macbook, so I expect it will be common.  It would be nice to have a guaranteed minimum border around the white box containing the confirmation link.

![screen_shot_2013-08-06_at_1 59 45_pm](https://f.cloud.github.com/assets/39411/916278/edf8b74c-fe87-11e2-8241-d562e56ec348.png)

**Comment by shane-tomlinson** [comment]
Fixed by c32acb2fde4db937ae24afcb8b56ab863253753d, closing.
