### ISSUE TITLE
metrics output should really be JSON

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3755]
the metrics files, like `router-metrics.json`, aren't valid JSON. They are a bunch of stringified JSON objects, but they aren't collected inside a top-level object, and they aren't separated by commas.

it would be way easier to process those files if they were valid JSON, so, do that.

**Comment by jaredhirsch** [comment]
link to mozilla/identity-ops#102 ("Update the cron job processing the metrics file to send metrics data to a kpiggybank collector")

**Comment by callahad** [comment]
If this is a streaming logfile, I'm not sure how we could sanely ensure that it's valid JSON at all times.

Every time we wanted to append, wouldn't we need to truncate the file to kill the final `}`, then write the next line with with a leading `,` and a trailing `}`?

Seems complex :(

**Comment by jaredhirsch** [comment]
@callahad ah, that's true. i'm no longer attempting to parse metrics files, so, closing as "meh."
