### ISSUE TITLE
3 CSS errors in /resources/static/dialog/css/m.css

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3765]
I saw some warnings through `adb logcat` and looking through the mobile source for https://static.login.anosrep.org/v/2bf9f39515/production/en/dialog.css it looks like the -webkit-gradient lines have an extra closing right brace (confirmed on csslint).

https://github.com/mozilla/browserid/blob/eaa8760bc42fa98e79493bd04fdbbd483057a69a/resources/static/dialog/css/m.css#L134

Line 134: background-image: -webkit-gradient(linear, left top, left bottom, from(#fcfcfb), to(#d8d9d8)));
Line 146: background-image: -webkit-gradient(linear, left top, left bottom, from(#fcfcfb), to(#ccc)));
Line 155: background-image: -webkit-gradient(linear, left top, left bottom, from(#d8d9d8), to(#fcfcfb)));

If you copy the content from the m.css file mentioned above and paste it into CSSLint.net, you should see 3 errors and ~32 warnings.

**Comment by shane-tomlinson** [comment]
@pdehaan - it looks as if there is an extra `)` on each of the lines. Thanks for pointing that out.

**Comment by jrgm** [comment]
Closing, since PR-3791 was merged.
