### ISSUE TITLE
Long email addresses cause the sign in window to scroll horizontally on B2G devices (truncates on desktop)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3767]
If I have an absurdly long email address it truncates nicely on the desktop site (with a tooltip displaying the full address).

![desktop](https://f.cloud.github.com/assets/557895/935666/f3b5f22a-008b-11e3-9e2d-8bf2de71342e.png)

On the B2G device, the email addresses scroll horizontally, making it a bit tricky to read the domain and then scroll back to find the Sign In button.

![mobile1](https://f.cloud.github.com/assets/557895/935674/446a2b8c-008c-11e3-80c2-6662cc4a1e0f.png)

![mobile2](https://f.cloud.github.com/assets/557895/935675/4801fdce-008c-11e3-9ed0-fedc80746e33.png)

**Comment by callahad** [comment]
@mhanratty can you weigh on on expected design / behavior here? Is horizontal scrolling OK?

**Comment by mhanratty** [comment]
I can live with horizontal scrolling for this. Thanks for bringing it to my attention!

**Comment by callahad** [comment]
Great, thanks!
