### ISSUE TITLE
Sign in and Cancel buttons aren't consistent on Desktop and B2G

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3768]
When signing in using LDAP on desktop, the buttons seem to be [Confirm] [Cancel]
![sign_in](https://f.cloud.github.com/assets/557895/935753/c183b528-008e-11e3-8ef5-a44773cacd3d.png)

On B2G the buttons always seem to be [Cancel] [Confirm] style.
![2013-08-08-17-43-42](https://f.cloud.github.com/assets/557895/935775/6058571c-008f-11e3-8787-8adfb413031c.png)

I think we should consider swapping the desktop LDAP button order.

**Comment by seanmonstar** [comment]
See mozilla/vinz-clortho#87
