### ISSUE TITLE
Too easy to lose the Persona popup window after the window gets obscured

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3772]
**Steps to reproduce:**
1. Go to http://123done.org/ and click the Sign in with Persona button to launch the dialog.
2. Open a few other windows/apps so that the Persona login gets pushed to the background.
3. Forget that you were mid-login and go back to the 123done.org site and try and sign in again.

**Actual results:**
The "Sign in with Persona" button is disabled and cannot be clicked. In order to actually sign in, you have to hunt around for the previously opened (but now obscured) dialog window and close it, or complete the sign-in process.

**Expected results:**
Instead of disabling the Sign in button, it may be nicer if we change the behavior so that clicking the Sign in button a second time just brings the previous dialog back into focus (or just relaunch the Sign In button with the same window/target name so the previous window gets recreated and the user has to start over).

**Comment by jaredhirsch** [comment]
@pdehaan This is really a 123done bug, so I've moved the issue over there. (Persona, as a third-party snippet, doesn't control how RPs manage the UX around the login button on their sites.)

:beers:
