### ISSUE TITLE
Lots of "401 Unauthorized" POSTs to login.mozilla.org

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3773]
We're seeing more than a few console logs about 401'd POSTs to `https://login.mozilla.org/api/provision`. This is causing some noise in our logs. We're seeing it in multiple projects in the Marketplace using `https://login.persona.org/include.js` as the `include.js` file.

http://cl.ly/image/261A0b1l1B2i

**Comment by jrgm** [comment]
See also https://github.com/mozilla/vinz-clortho/issues/93 which is essentially the same issue, but this one has a prettier picture ;-)

**Comment by jaredhirsch** [comment]
can we close this in favor of the vinz-clortho bug? we aren't tracking mozilla idp bugs here as far as I know

**Comment by callahad** [comment]
Closing in favor of the vinz-clortho bug.
