### ISSUE TITLE
Persona broken in packaged apps

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3778]
`navigator.id.watch` gets called successfully. There are no errors on the page.

After `navigator.id.request` gets called, though, this is the screen that loads:

http://cl.ly/image/2o2b0r2T1O1M

**Comment by vladikoff** [comment]
@mattbasta Sorry, cannot reproduce, I've just tried several websites (i.e. http://123done.org/ ) and all of them worked fine. Is this inside of an app or something else? Are you using the latest version of the simulator (4.0)?

**Comment by mattbasta** [comment]
This happened inside a packaged app loaded via "Add Directory". I'll check
what version of the simulator I'm using, but I believe it is the latest.

**Comment by shane-tomlinson** [comment]
Is this a dup of #3614?

**Comment by mattbasta** [comment]
Doesn't look like it. The dialog loads "correctly", but throws the error
shown.

Interestingly, it's also impossible to close the login dialog. You have to
shut down the simulator to get rid of it.

**Comment by shane-tomlinson** [comment]
@mattbasta - That's not so awesome. Thanks for the extra info.

**Comment by mattbasta** [comment]
Updated the title: I can reproduce the issue in on a Keon device as well (fully updated). You can download the package yourself here:

http://inferno.paas.allizom.org/

**Comment by callahad** [comment]
Likely related to the hotfix we deployed to strictly check origins in winchan.

**Comment by shane-tomlinson** [comment]
@callahad - packaged apps should be using native Persona, bypassing WinChan completely. @mattbasta - can you provide a set of STRs? I am unfamiliar with installing packaged apps on a device manually.

**Comment by ozten** [comment]
Simulator STR
1) Install the FxOS simulator via Add-On https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/

2) In Fx Tools > Web Developer > Firefox OS Simulator

3) Start simulator

4) Download http://inferno.paas.allizom.org/package.zip

5) mkdir inferno ; cd inferno; unzip package.zip

5) Click Add Directory and locate `manifest.webapp`

6) Note: ![](http://dl.dropbox.com/u/10060532/Screenshots/T9VM.png) launches

7) Click gear icon

8) Click Sign In

Expected

Usual Persona flow

Actual

![](http://dl.dropbox.com/u/10060532/Screenshots/ynH0.png)

**Comment by ozten** [comment]
Is this the first packaged app where we have passed `termsOfService` and `privacyPolicy` in the `request` options?

If I remove those arguments, Persona doesn't have this error.

What do we do today, for TOS/PP on Marketplace?

**Comment by ozten** [comment]
You can use [absolute URLs](https://developer.mozilla.org/en-US/docs/Web/API/navigator.id.request) in request and a quick test shows that this works with packaged apps.

```
    var opt = {
        termsOfService: '/terms-of-use',
        privacyPolicy: '/privacy-policy',
```

could be

```
    var opt = {
        termsOfService: 'https:://marketplace.mozilla.org/en/terms-of-use',
        privacyPolicy: 'https:://marketplace.mozilla.org/en//privacy-policy',
```

I made up https:://marketplace.mozilla.org/en/ but you get the idea.

**Comment by mattbasta** [comment]
ToS/PP are kind of broken at the moment due to the documents being loaded
with JS.

Would it be a mortal sin for us to simply remove those params?

**Comment by shane-tomlinson** [comment]
@ozten - this is a great catch. What are the current agreement URLs?

**Comment by ozten** [comment]
I think we are going to drop them for now, per basta.

**Comment by shane-tomlinson** [comment]
Demoting this from 5\* to 4\* since the problem lies with privacyPolicy and termsOfService on packaged apps and has a work around.

**Comment by ozten** [comment]
@jedp can you look at the SIgn in error? Steps to reproduce and screenshot of the error in [Comment 22726190](https://github.com/mozilla/browserid/issues/3778#issuecomment-22726190).

**Comment by jedp** [comment]
@ozten thanks - just looking into this now

**Comment by jedp** [comment]
I figured I'd try first on device, since the emulator can behave differently than multi-proc b2g, especially for marketplace and identity.  I downloaded the marketplace app from http://inferno.paas.allizom.org/

When I try to sign in with the gear in Marketplace using my mozilla.com address, I am prompted to enter a password.  I did not get sent over to the Mozilla IDP.  I entered a password.

Returning to Marketplace from the dialog, Marketplace reports a server error trying to log in.  The lolcat says:

> E/GeckoConsole( 1978): Content JS LOG at app://{f7f8dc30-1d3f-4e67-a275-2faba386eda6}/media/js/log.js:46 in anonymous: [req] Response data:  {"reason": "No profile."}
> E/GeckoConsole( 1978): Content JS WARN at app://{f7f8dc30-1d3f-4e67-a275-2faba386eda6}/media/js/log.js:46 in anonymous: [login] Assertion verification failed! UNAUTHORIZED 401

(What url is being sent to the verifier?  It should be an https:// url corresponding to the Marketplace server, yes?)

I went over to sign in to a Persona site that doesn't use unverified emails (the UI Tests app).  I tried to sign in with my mozilla.com address.  It said, "good news! your account no longer requires an additional password."  So my account had switched over to being staged by the Marketplace sign-in attempt.  This time, I did get the Mozilla IDP, and signed in with LDAP.

I wondered whether I could return to marketplace and get an automatic assertion now. Going back to Marketplace and clicking the sign-in button, I selected my mozilla.com address in the Persona dialog, and clicked sign in.  Dialog closes and again the server error is reported.

Lolcat shows same error as before: Assertion verification failed!

So there are at least three things going on here:
- The emulator behaves differently from FirefoxOS on device
- forceIssuer + allowUnverified is ugly when you already have a primary address (we all knew this)
- The verifier is upset about something.

Do we know what url is actually going to the verifier?  Is it the app:// url?  Or is it getting the https:// url to the marketplace server itself?  (It should be the latter, as per Issue #3205)

**Comment by mattbasta** [comment]
The `{"reason": "No profile."}` you're seeing is coming from the
Marketplace API. Not sure why that's happening, though. I've never
experienced the failed assertion.

What device did you test on? I've had the dialog-never-closing issues on
the Keon/Peak.

**Comment by jedp** [comment]
Could "No profile" be what Marketplace says when the verifier says no to the assertion?

This is a local build of b2g18 + v1-train for Unagi.  I have a Keon - I'll try it.

What is Marketplace using as the audience for the assertion?  Is it the https:// marketplace url?

**Comment by mattbasta** [comment]
That's a great question for @kumar303 or @washort.

**Comment by washort** [comment]
yes, it's using `https://marketplace.firefox.com/`.

**Comment by jedp** [comment]
@washort so that sounds right.

@mattbasta are you able to log what comes back from the verifier?  or is it just sending you a 500?

I'll test against a local persona instance

**Comment by mattbasta** [comment]
I don't think the verifier is sending a 500. This is where the error comes from:

https://github.com/mozilla/zamboni/blob/master/mkt/account/api.py#L137

I just added a bit of logging to help debug:

https://github.com/mozilla/zamboni/commit/000a08f73c33ca23a548d97f258af4715b0e7f1c

From my understanding, this error is only returned when the verification step fails in `django_browserid`, but we'll see what the logs have to say.

**Comment by jedp** [comment]
@mattbasta did you get any fuller logs out of django?  Do we know what `msg` is coming back from that authenticate function?

**Comment by mattbasta** [comment]
Instead of trying to fiddle with production, I'm going to take a few minutes today to fiddle with our mock API. That has the same configuration as prod (I think) and returns the exact error rather than a sanitized version. I'll report back with my findings.

**Comment by mattbasta** [comment]
```
Attempting verification: app://{4d5cb5c1-f5b6-442c-ae69-4d69e1948f0b} 1
{"status":"failure","reason":"audience mismatch: domain missing"}
```

The first line shows the origin passed as the audience (the `1` means that it was using native persona). The second line is the output from the verifier.

In production, we'll have a "real" origin, but in our test apps that won't happen because you need to be signed for that to work. Any ideas?

**Comment by jedp** [comment]
Good to know that this is confined to the test apps.  Can we confirm that things are actually working properly in production?

In the test apps, if you're not signed in, what are you sending to the verifier as an assertion?

**Comment by mattbasta** [comment]
We can't confirm in production since we can't make a production version of the Marketplace. We'd effectively have to ship an update to prod, and if it doesn't work, the Marketplace is dead in the water.

That's the biggest issue: we can't really generate a test app that works. You can't specify an origin unless you're privileged, and to be privileged you need to be signed. And to be signed, you have to be submitted to the production Marketplace (you can conceivably do it with dev certs, but I haven't found a single person in MV that knows how to install dev certs on a phone).

> In the test apps, if you're not signed in, what are you sending to the verifier as an assertion?

The assertion is whatever `navigator.id.watch` gives back to us. The audience is something like `app://{4d5cb5c1-f5b6-442c-ae69-4d69e1948f0b}`. The UUID is unique to the app and device, not just the app.

Would it be possible to pass some kind of flag to the verifier to say, "please trust app:// scheme URLs with UUIDs, this is a dev server"?

**Comment by shane-tomlinson** [comment]
> Would it be possible to pass some kind of flag to the verifier to say, "please trust app:// scheme URLs with UUIDs, this is a dev server"?

@mattbasta - I think at that point, you guys might want to consider running your own verifier with those modifications, my feeling is enabling that behavior globally could lead to security problems.

@fmarier - Whatcha think?

**Comment by jedp** [comment]
Sorry, @mattbasta - I misread "signed" in [your comment above](https://github.com/mozilla/browserid/issues/3778#issuecomment-23756570) for "signed in".  That's why I was scratching my head about how you got an assertion of any kind to send to the verifier.

**Comment by mattbasta** [comment]
Ah yeah, signed like with certificates and magic and stuff.

**Comment by jedp** [comment]
@mattbasta so what's the best way we can help?  We can help set up a dev verifier to just verify whatever it gets, though having a verifier with different behavior seems like it could mask bugs.  If you could install dev certs on the phone, would you have everything you need to unblock this?

**Comment by mattbasta** [comment]
Requiring dev certs would make the packaged builds largely inaccessible to
the folks that would need to test it,  including the better part of QA. It
would also add a manual dev deploy step, which is less than ideal. I'd
rather avoid it at all cost, if possible.

**Comment by jedp** [comment]
I agree that having manual steps is not good.  What if there was another automated nightly build that included the dev certs?  Wouldn't that be easy for everyone to flash to their devices and make it accessible to all?

**Comment by mattbasta** [comment]
The issue with the dev certs is that they need to be installed on the phone
using a special tool. The signing process is the additional step that would
need to be performed on the zipball.

It's also worth noting that dev certs can't be installed in the simulator,
meaning we wouldn't be able to do any Marketplace testing in the simulator.

I really don't consider signing the package and requiring dev certs to be a
viable option.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
