### ISSUE TITLE
IE8: siteLogo - data uri > 32KB causes causes browser to run slowly, show blank image

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3781]
![screen shot 2013-08-13 at 12 09 45](https://f.cloud.github.com/assets/848085/954045/0954e8fe-0409-11e3-8809-16a71b80516e.png)

Dialog is still usable after about a 10 second wait.

@jrgm - would this cause a train blockage? If so, we can get it fixed.

**Comment by callahad** [comment]
I feel like we can resolve this by documenting it, leaving the decision up to the RP.

**Comment by shane-tomlinson** [comment]
@callahad - seems good to me. Does it warrant a console warning?

**Comment by callahad** [comment]
Nah, but good idea.

**Comment by shane-tomlinson** [comment]
Closing as wontfix.
