### ISSUE TITLE
Mozilla IdP  - beta.123done.org does not ask for password after changing it

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#3787]
Env
beta.123done.org
Win 7 & IE FF 22 release
Win 7 & IE 10

Steps:
1. Sign in with username@test-moz-idp.com
2. Provide the password when asked
3. Logout 
4. Login again with username@test-moz-idp.com - password is not requested
5. Go to https://ldap.mozilla.org/passwordreset/ and change the password for username@test-moz-idp.com
6. Wait for a while (I waited up to 30 minutes) 
7. Sign in again with username@test-moz-idp.com

Expected:
User should be asked to enter the new password

Actual:
The account is logged in without asking for password

**Comment by shane-tomlinson** [comment]
Thanks for the submission @csuciu - I am going to refile this verbatim in the [mozilla/vinz-clortho](https://github.com/mozilla/vinz-clortho) repo.

**Comment by karlht** [comment]
Thanks for moving the bug, Shane.  Sorry about that.
