### ISSUE TITLE
Display of all available persona ids in the popup is confusing when trying to log into a site

### ISSUE THREAD

**Issue by whimboo** [mozilla/persona#3793]
I have a couple of email addresses for my persona account which I share between various sites. But whenever I want to log into a site which I haven't used for a long time, I'm always confused which email address to use.

It would be great if the popup would not show all available email addresses but only the one which I have used to login, and an input field where I can specify another one if necessary. But most of the times an user will only have a single address assigned.

**Comment by ozten** [comment]
I believe the current tradeoff is due to localStorage and security/privacy.

We're planning to make this much better for FxOS and FxDesktop. A proposal is coming. We'd be storing email addresses in a more secure location with better integration into existing Fx preferences.

**Comment by shane-tomlinson** [comment]
@whimboo - I agree 100%.

This is a dup of #2953 and I have added it to mozilla/browserid-roadmap#51 which is where we are now tracking feature requests.
