### ISSUE TITLE
KPI data conains many one event blobs (window.unload)

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3794]
Looking at all of the blobs, an unexpectedly large number have short, hard to classify event_streams. The majority of these have only one event, and in most cases that event is "window.unload". (~17% of the kpi blobs since 2013-07-11 are blobs with only one event).

I haven't really been able to reproduce this, but I have been able to generate blobs without "window.unload" at the end, and seen only "window.unload" in my local storage, fwiw. I've seen this using Chrome, when closing the window instead of the dialog. I don't remember seeing an extra blob showing up in the kpi data, however, but I'll try again.

The % of these blobs has been growing, in particular right around the gmail announcement (where we had a spike in traffic overall).

It would be good to understand if this is a measurement error (sending an extra blob sometimes that doesn't represent a distinct session) or aborted dialog sessions, or something else entirely. (I suspect measurement error, but perhaps that is wishful thinking).

**Comment by kparlante** [comment]
@shane-tomlinson sample data for this issue: https://id.etherpad.mozilla.org/kpi-bounce-rate-data, https://id.etherpad.mozilla.org/kpi-issue-3794-data

**Comment by shane-tomlinson** [comment]
This is only a theory. 

It could be possible for the assertion to be sent to the RP, which notifies the communication iframe, which flushes and sends the KPI blob, and THEN the window closes, creating a new, empty KPI blob.

Seems plausible, but have to dig in to find out.

**Comment by jaredhirsch** [comment]
Regardless of the funky edge case that might be causing this, it seems like we can safely discard any blobs that contain the final `window.unload` event, but not the initial `window.dom_loading` event? Could this clean up the data while we investigate the root cause?

**Comment by kparlante** [comment]
We're already ignoring it in most graphs (I didn't include it in "bounce rate", assuming it was an edge case, and they don't show up in the "new user" graphs that track new fallback users). It only affects the general progress graph and the graph that shows the total # of blobs. Right now we have several metrics related "fires" which take precedence, but logged here: https://github.com/mozilla/kpi-dashboard/issues/78
