### ISSUE TITLE
compile failures in ./resources/static/test are not detected by QUnit

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3797]
This came up when I ran the redirect-flow branch on an ephemeral with IE8.

Stderr does spit out a SyntaxError message, but... 

... Despite a syntax error in resources/static/test/cases/common/js/storage.js, the Qunit (phantomjs or IE8) test reported "all passed".

The problem in this case was that the syntax error meant none of those tests for the storage case were executed. 

So, is there a setting of QUnit to fix this? Otherwise, the other defence would be jshint, but there's a lot of tuned-to-many-browsers changes that would need to happen. (I suppose another approach is to keep better track of how many tests should exist, but that's also failure prone).

**Comment by jaredhirsch** [comment]
qunit's config options seem [pretty minimal](http://api.qunitjs.com/QUnit.config/).

It's a bit meta for my taste, but we could write a test that runs last, and which checks the qunit UI to ensure that the expected number of tests was registered/executed, and barfs if not.
