### ISSUE TITLE
"persona is slow"

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#3799]
there have been some reports about persona being slow.  Here's one:

https://twitter.com/dolske/status/367361102356566016

It sounds like dolske is talking about time from click on website, to initial render of dialog.

**Comment by lloyd** [comment]
We need STR and to understand what device and website were in use.  I'm unable to reproduce the symptoms described.  I see the dialog visible in about 2 seconds at cache empty and much less in a subsequent attempt (cache full).

**Comment by callahad** [comment]
Suspected STR:
1. Open [Network Link Conditioner](http://stackoverflow.com/questions/9659382/installing-apples-network-link-conditioner-tool)
2. Set it to high packet loss and latency
3. Try to open a Persona popup

**Comment by shane-tomlinson** [comment]
Link to #2400

**Comment by jaredhirsch** [comment]
this bug isn't actionable, closing in favor of https://github.com/mozilla/browserid/issues/3825 (CDN implementation ticket)
