### ISSUE TITLE
rendering issue when the login dialog animates in Chrome 28

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3803]
https://dl.dropboxusercontent.com/u/4509565/moz-videos/signin-chrome28.mov

After successfully logging in, there is a stray vertical line while the login dialog closes, as seen in the video link above.

I wasn't able to reproduce this in FF24.

**Comment by jrgm** [comment]
This was https://github.com/mozilla/browserid/issues/3668 and the fix for this is visible on stage for me. Closing as dup.
