### ISSUE TITLE
Login doesn't work in WebApp installed in Firefox for Android

### ISSUE THREAD

**Issue by alex-pl** [mozilla/persona#3807]
I put a simple Persona login into one of my sites. The login works on Firefox and Firefox OS - no matter if opened in a browser tab or as a installed WebApp. It works also on Firefox for Android (23 stable up to 26 nightly), but _not as a WebApp, that is installed in Firefox for Android_.

_Expected result:_
The navigator.id.request() call should open a login screen.

_Actual result:_
The navigator.id.request() call does nothing.

That's the website: http://www.birdgames.de/
WebApp Manifest: http://www.birdgames.de/birdgames.webapp

_Steps to reproduce:_
- mobile view: Click "Login" in the main menu. The main menu can be opened at the top left corner.
- desktop and tablet view: Click "Login" in the footer menu (scroll to the bottom of the page).

I haven't found and issue that tracks that problem. Also I've tried to use remote debugging to figure out the problem, but remote debugging doesn't work with WebApps on FF for Android.

**Comment by shane-tomlinson** [comment]
Relate to #3778

**Comment by shane-tomlinson** [comment]
@alex-pl - thanks for the bug report! I have opened a bug in Bugzilla for this as well so that it can be tracked by the Open Web Apps team: https://bugzilla.mozilla.org/show_bug.cgi?id=908718

**Comment by alex-pl** [comment]
The issue has been fixed in the current stable release \o/

**Comment by callahad** [comment]
Closing :) Thanks!
