### ISSUE TITLE
allowUnverified accounts can't login to non-allowUnverified RPs

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3811]
@stephendonner found this bug in production, and @shane-tomlinson figured out STR locally.

STR:
1. create a new secondary with an RP that allows unverified accounts, like an FXOS phone
2. then, without clicking the link in your email, try to use that unverified account to log into an RP that does not allow unverified, like persona.org
3. when you enter the email into the dialog and hit 'next', the button will spin, but nothing will happen--you cannot log in.

We observed this today with the webqa test account not being able to log into production persona.org.

STR locally (thanks to shane):
1. load up the dev RP
2. click 'allow unverified'
3. create a new secondary acct
4. visit the dev login.persona.org and sign out
5. re-load up the dev RP
6. un-select 'allow unverified' if it is selected
7. load the dialog
8. enter the email address from step 3

The underlying bug is rather subtle and funky:
- [the authenticate module](https://github.com/mozilla/browserid/blob/6a8b8e/resources/static/dialog/js/modules/authenticate.js#L129-L137) fires 'email_chosen'
- the state machine's ['email_chosen' handler](https://github.com/mozilla/browserid/blob/6a8b8e/resources/static/dialog/js/misc/state.js#L460-L464) fires 'stage_reverify_email' if the address is unverified and the RP doesn't allowUnverified
- the state machine's ['stage_reverify_email' handler](https://github.com/mozilla/browserid/blob/6a8b8e/resources/static/dialog/js/misc/state.js#L493) fires a corresponding [action](https://github.com/mozilla/browserid/blob/6a8b8e/resources/static/dialog/js/modules/actions.js#L110) which calls into a [dialogHelper](https://github.com/mozilla/browserid/blob/6a8b8e/resources/static/dialog/js/misc/helpers.js#L76-L87) which, finally,
- calls [user.js.requestEmailReverify](https://github.com/mozilla/browserid/blob/6a8b8e/resources/static/common/js/user.js#L850-L861), which doesn't find anything in storage (since this is a different browser, I think?) and gives up.

This is an obscure but ugly edge case. :beers: to webqa for flushing it out

**Comment by shane-tomlinson** [comment]
New, easier to reproduce (and more likely) STRs:

1) Create an account with 2 secondary addresses
2) Visit 123done.org, open dialog, sign out.
3) Enter 1st address from step 1
4) Click on "Forgot your password?"
5) Open password reset email & enter new password
6) In a second browser (one with no Persona session - private mode works well), open dialog from 123done.org
7) Enter the 2nd address from step 1
8) User should be forced to enter their password and re-verify their ownership of the address.

**Comment by jrgm** [comment]
marking 5-star to get a fix on the dev branch.
