### ISSUE TITLE
3 errors and 3 warnings when trying to validate login.persona.org markup on w3 validator

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3827]
http://validator.w3.org/check?uri=https%3A%2F%2Flogin.persona.org&charset=%28detect+automatically%29&doctype=Inline&group=0

The reported errors are as follows:

> The encoding utf8 is not the preferred name of the character encoding in use. The preferred name is utf-8. (Charmod C024)

&nbsp;

> Error Line 12, Column 56: Bad value X-UA-Compatible for attribute http-equiv on element meta.
> 
>  <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>

&nbsp;

> Error Line 58, Column 103: An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.
> 
> …img src="https://static.login.persona.org/v/bc1d781d44/pages/i/slit.png"></div>

Not sure if any warrant investigation, although the utf8 vs utf-8 one seems odd. It looks like the <meta> header is explicitly specifying utf-8 already.

Re: IE=Edge, it looks like we may want to check that flag as Microsoft says it is intended for testing only: http://msdn.microsoft.com/en-us/library/jj676915%28v=vs.85%29.aspx

> For testing purposes, you can also use the following value to display the webpage in the highest standards mode supported by Internet Explorer.
> 
>   `<meta http-equiv="x-ua-compatible" content="IE=edge" >`
> 
> **Note  Edge mode is intended for testing purposes only; do not use it in a production environment.**
> 
> Because it forces all pages to be opened in standards mode, regardless of the version of Internet Explorer, you might be tempted to use this for all pages viewed with Internet Explorer. Don't do this, as the X-UA-Compatible header is only supported starting with Windows Internet Explorer 8.

The 3 reported warnings seem to be that HTML5 validation is an experimental feature, and then 2 warnings about utf8 goodness, most notably:

**Warning Character Encoding mismatch!**

The character encoding specified in the HTTP header (utf8) is different from the value in the <meta> element (utf-8). I will use the value from the HTTP header (utf8) for this validation.

**Warning Rare or unregistered character encoding detected**

The character encoding declared for this document (utf8) is supported by the validator, but may not be widely supported across platforms. For the sake of interoperability, it is best to use a unicode character encoding such as UTF-8, or one of the registered character encodings.

**Comment by pdehaan** [comment]
Filed the x-ua-compatible IE=edge issue separately as #3852

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
