### ISSUE TITLE
When signing into a site using Persona, you dont see TOS or PP links if you see a list of emails

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3834]
If you log out of the site and then log back in again, you're presented with your list of emails, but you don't see the any Terms of Service of Privacy Policy links.

![mozilla_persona__a_better_way_to_sign_in](https://f.cloud.github.com/assets/557895/1018875/9d313550-0c33-11e3-8191-309819f658c2.png)

**Comment by shane-tomlinson** [comment]
@pdehaan - This is by by design. The user should only see the RP's TOS/PP links if they have never visited the site before. If they HAVE visited the site before (and it looks like you have, I see one email address is highlighted in the background), the TOS/PP agreements are not shown.

**Comment by pdehaan** [comment]
I don't quite get it. What happens if the Persona/site TOC or PP changes since I first logged in? I wouldn't be able to see the changed docs unless I try and log in, then click "This is not me" and then log in all over again.
Wouldn't it make sense to always show links to the TOS/PP for Persona and the site regardless of login workflow?

**Comment by callahad** [comment]
This feels super strange to me as well, <del>and is a change from what's currently in production</del>. Once I've logged into a site once, I can no longer view its terms of service or privacy policy?

**Comment by jrgm** [comment]
It's not a change from what's currently in production.

**Comment by callahad** [comment]
@jrgm is right, I misunderstood the condition. Not a change from prod.

**Comment by pdehaan** [comment]
Mr @ryanfeeley , do you have any thoughts on this?

**Comment by ryanfeeley** [comment]
@pdehaan I reviewed the current behavior with @shane-tomlinson and it behaves as designed. The TOS for both Persona and the RP are only shown the first time a user signs into a given RP. For subsequent sign-ins, Persona's TOS link is one click further away under "learn more", as is the RPs after sign in (though may be available unauthenticated). This decision was made to remove as much friction as possible from subsequent sign-ins.

**Comment by callahad** [comment]
So we're OK with the RP's ToS and PP being invisible until after you've signed in, for subsequent sign-ins?
