### ISSUE TITLE
[headsup] Sometimes, persona login using gmail fails with an error message about third-party cookies

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#3846]
## Steps to reproduce
1. Launch marketplace-dev.allizom.org on nightly or Chrome
2. Sign in using your gmail account
## observed behavior:

During verification step, login fails with a user message about third-party cookies not allowed by the browser. However, trying to sign in immediately afterwards results in a successful login. 

Sorry for the vague bug report. i will add more details if i hit the issue again. I have hit this issue twice so far.

**Comment by karlht** [comment]
@krupa, Nightly had a change where third-party cookies are disabled by default now, which would cause this issue.  If this recurs, please include what the third-party settings and/or exceptions are.

Thanks.

**Comment by jaredhirsch** [comment]
@krupa - closing, please reopen if you can repro
