### ISSUE TITLE
x-ua-compatible ie=edge is intended for testing purposes only and not for use in a production environment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3852]
Per http://msdn.microsoft.com/en-us/library/jj676915%28v=vs.85%29.aspx
### Understanding legacy document modes

When using the X-UA-Compatible header to restrict a webpage to a legacy document mode, use one of the following values:

For testing purposes, you can also use the following value to display the webpage in the highest standards mode supported by Internet Explorer.

```
<meta http-equiv="x-ua-compatible" content="IE=edge" >
```

**Note: Edge mode is intended for testing purposes only; do not use it in a production environment.**

Because it forces all pages to be opened in standards mode, regardless of the version of Internet Explorer, you might be tempted to use this for all pages viewed with Internet Explorer. Don't do this, as the X-UA-Compatible header is only supported starting with Windows Internet Explorer 8.

Tip  If you want all supported versions of Internet Explorer to open your pages in standards mode, use the HTML5 document type declaration, as shown in the earlier example.

**Comment by shane-tomlinson** [comment]
@pdehaan - we only support IE8 and above and we use the HTML5 doctype.

**Comment by callahad** [comment]
@shane-tomlinson I think @pdehaan is suggesting that the `IE=edge` setting is unnecessary if we have the proper doctype, and that setting it to `edge` is a bad practice according to Microsoft.

IIRC, the tag is still necessary in order to override IE's heuristics for switching to IE7 mode on intranet sites, but I could be wrong.

**Comment by shane-tomlinson** [comment]
@callahad - you are indeed correct.

**Comment by callahad** [comment]
Closing as wontfix; I think the MS docs are a bit crazy in that regard.

**Comment by shane-tomlinson** [comment]
Link to #2566
