### ISSUE TITLE
Validate email addresses when signing up?

### ISSUE THREAD

**Issue by sole** [mozilla/persona#3858]
I saw a couple of "average users" try out webmaker/thimble today and try to register with the site using Persona. The first attempt failed because the person didn't notice that she had incorrectly entered her email address--instead of `something.org` she had entered `something.og` (note the missing R in org).

She kept checking her email account and even going to the spam folder to no avail, until we decided to go back and try again, then we noticed that she had entered a wrong address.

Maybe some sort of "simple" regexp could be implemented so that we say something like: you entered .OG, are you sure you didn't mean .ORG?

**Comment by seanmonstar** [comment]
This was suggested [on the list](https://groups.google.com/d/topic/mozilla.dev.identity/hm_J8agRb6w/discussion) a while ago, and we agreed it would be a great idea. I searched to see if we had an existing issue, and couldn't find one.

I'm :+1: on this.

**Comment by jaredhirsch** [comment]
zomg verifying valid TLDs is really hairy. maybe we could do a service roundtrip.

**Comment by sole** [comment]
Yeah, I know! that's why I suggested a simple regexp, "non blocking" (i.e. it wouldn't be "modal"). And maybe it could be ran only in some cases, say if it ends on .og where the usual thing is ORG. Not sure how would the heuristic work o_O

**Comment by pdehaan** [comment]
I think Mailgun has a service for email validations, but not sure about rate limits and details: http://blog.mailgun.com/post/free-email-validation-api-for-web-forms/

They also have a simple jQuery demo: http://mailgun.github.io/validator-demo/

**Comment by seanmonstar** [comment]
As linked in the discussion on the list, try out http://kicksend.com/join, and type a foo@gmail.ocm address or something. It's just a gentle reminder to check your spelling.

**Comment by shane-tomlinson** [comment]
This should be captured in a user story.

**Comment by callahad** [comment]
Closing since we have a user story.
