### ISSUE TITLE
siteName not showing in some Portuguese strings

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#3859]
Reported by Lucas Junqueira on the list.

Looking into the our [translations](https://localize.mozilla.org/pt_BR/browserid/LC_MESSAGES/translate.html#search=Confirm&sfields=source,target), it could be that we have some strings that use `%(site)s`, but the translations remove the name, leaving only `%s`, which fails to be formatted.

![1](https://f.cloud.github.com/assets/51479/1085037/6f0f707a-15bf-11e3-94c0-ade03437c96b.jpg)
![2](https://f.cloud.github.com/assets/51479/1085039/76574484-15bf-11e3-9f8d-a5f78c67126d.jpg)

**Comment by shane-tomlinson** [comment]
@mathjazz - looking at the `pt` translations, it looks like @seanmonstar was right. The translation for "Check your email" contains a `%s`. The translation for "Confirm your account now" is missing (as well as "Learn more at https://login.persona.org/about")

**Comment by mathjazz** [comment]
@seanmonstar @shane-tomlinson PT translation is not at 100%, so it could be that we changed the original string but they didn't follow up with translaiton. I'll ping them to fix it.

**Comment by shane-tomlinson** [comment]
Thanks @mathjazz - have these been updated?

**Comment by mathjazz** [comment]
Yes, pt and pt_BR are both updated and fixes.

**Comment by shane-tomlinson** [comment]
Thanks @mathjazz - closing this issue. If this is still seen, please re-open.

**Comment by seanmonstar** [comment]
This should be seen in production with the next train, right?
