### ISSUE TITLE
Persona official website and where to report bugs

### ISSUE THREAD

**Issue by sole** [mozilla/persona#3860]
Hello guys

Sorry this is a bit of fuzzy metabug. Basically, it's a question and a request for confirmation that I did the right thing:

The question: what is Persona's official website? If such a thing exists, that it.
Is it https://developer.mozilla.org/en-US/docs/Mozilla/Persona ?

The reason I ask is, whatever that place is needs to have an obvious link that links to the issue tracker. I got to report a bug yesterday only because @shane-tomlinson told me where to do it (github). I wonder if there are more bugs that get unreported because people don't know where to do it.

I edited the page to add links to the issue tracker in github. Here's the diff:
https://developer.mozilla.org/en-US/docs/Mozilla/Persona$compare?to=463993&from=454395

Hope that's fine, but please feel free to revert or edit again if that's not the proper place :-)

**Comment by jaredhirsch** [comment]
@callahad / @wbamberg thoughts here? want to keep or revert?

**Comment by wbamberg** [comment]
I'm not sure I can say which is Persona's official website, but thanks for the edit, I agree that this page needs to link to "report a bug".

**Comment by callahad** [comment]
Thanks, edits look good to me. MDN is currently the developer-facing landing page.

There's an ongoing effort to create a centralized landing page at www.persona.org in the next few weeks, which should help matters even more :)

Thanks again for the contribution!
