### ISSUE TITLE
Intermittent "Cannot verify user@example.com" for @mozilla.com (primary) email account

### ISSUE THREAD

**Issue by gene1wood** [mozilla/persona#3870]
Over the weekend I saw this sequence. I've not seen it before and my browser doesn't block third-party cookies (to my knowledge).
1. Go to https://login.persona.org/ and click Sign Out
2. Go to a URL authenticated by mod_authn_persona (I'm unsure if this is part of the issue or not, but this was what I was attempting)
3. Click Sign in with your email
4. Type in a @mozilla.com email address
5. Your taken to a screen that says "user@mozilla.com no longer requires an extra password. Verify your account and you will immediately be signed in to example.com" ![user@mozilla.com no longer requires an extra password. Verify your account and you will immediately be signed in to example.com](http://img703.imageshack.us/img703/2984/wv6l.png)
6. Click "Verify" 
7. Your taken to MozIDP : https://login.mozilla.org/sign_in?email=user%40mozilla.com
8. Login to MozIDP ![Login to MozIDP](http://img835.imageshack.us/img835/1269/ji7n.png)
9. Error message : Cannot verify jdoe@mozilla.com This may be due to your browser blocking third-party cookies. Please ensure your browser's privacy preferences are set to accept third-party cookies for mozilla.com and try again ![Cannot verify jdoe@mozilla.com This may be due to your browser blocking third-party cookies. Please ensure your browser's privacy preferences are set to accept third-party cookies for mozilla.com and try again](http://img10.imageshack.us/img10/9531/2h8f.png)

**Comment by edwindotcom** [comment]
moved to https://github.com/mozilla/vinz-clortho/issues/121
