### ISSUE TITLE
Allow the user to switch languages on login.persona.org

### ISSUE THREAD

**Issue by benoit-l** [mozilla/persona#3871]
When loading login.persona.org, everything is displayed according to the accept-language setting of the browser.

But it happens sometimes when travelling that people have to use a browser with different language settings, be it in airports, internet cafés or at friend's house. 

There should be a language switcher somewhere on the login screen like on other Mozilla properties.

(and on a personal note, it would also make it easier for me to test my own locale if I can compare it quickly to other languages)

**Comment by shane-tomlinson** [comment]
Link to #1798

**Comment by callahad** [comment]
Closing as a dupe of 1798
