### ISSUE TITLE
loggedInUser's value is case sensitive

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3878]
As reported in mozilla/django-browserid/issues/192, loggedInUser is case sensitive, which leads to false-negatives and logout loops when a user should otherwise be considered as logged in.

STR:
1. Start a local browserid instance.
2. Navigate to the local example RP.
3. Click "get an assertion" and sign in as `FOO@mockmyid.com`
4. Refresh the page, notice the correct onlogin -> onready callback sequence.
5. Set the session to `FOO@mockmyid.com` and refresh the page, note the correct onmatch -> onready callback sequence.
6. Set the session to `foo@mockmyid.com` and refresh the page, note the incorrect onlogin -> onready callback sequence.

**Comment by edwindotcom** [comment]
this sucks!

**Comment by glogiotatidis** [comment]
Any progress on this one? We keep getting complaints from people who for some reason end up with the same email with different casing in different websites and they get locked out from the websites.

**Comment by glogiotatidis** [comment]
Here is a related bug that tracks occurrences of this problem in mozillians.org 

https://bugzilla.mozilla.org/show_bug.cgi?id=908342

Thanks!

**Comment by seanmonstar** [comment]
We're deprecating `loggedInUser` and all session management. Initial work to support no session management is in stage.

**Comment by glogiotatidis** [comment]
OK! :)

**Comment by callahad** [comment]
Suggest closing as wontfix -- we'll deprecate the Observer API soon and suggest that people move to Goldilocks...

**Comment by callahad** [comment]
(Added a small note to the docs that loggedInUser is case-sensitive... which makes me realize how much this kinda sucks. Grr... Full steam ahead on Goldilocks, but I'd totally :heart: a patch to fix this.)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
