### ISSUE TITLE
 Persona window never opens on Android from web app

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3882]
@kumar303 reports in [Bug 914415](https://bugzilla.mozilla.org/show_bug.cgi?id=914415):

**To reproduce**
- Install Firefox Nightly on an Android device
- Install this add-on to activate payments prefs: http://mzl.la/19BZQCx, from https://addons.mozilla.org/en-US/firefox/addon/dev-marketplace/ (source: https://github.com/wesj/devMarketplace)
- Install the in-app payment tester from http://apploa.de/3b25a (manifest: http://inapp-pay-test.paas.allizom.org/manifest.webapp)
- Open the tester app from the Android home screen
- Tap Pay
- When prompted to sign-in, tap the sign-in button

**Expected**

A Persona window should open and let you sign in.

**Actual**

No Persona window opens. You only see the spinner from the webpay server and there isn't anything useful in the logcat that I can see. Note that the add-on above activates Persona debug settings.

![device-2013-09-09-184555](https://f.cloud.github.com/assets/532953/1141288/2c7b0618-1cb1-11e3-9ec0-cc4f483f9f52.png)

**Comment by jedp** [comment]
Not being able to sign into marketplace on android sounds like a five-star to me.  Assigning it as such.

**Comment by jedp** [comment]
@kumar303, you mention that the add-on activates persona debug settings.  There is an experimental Persona implementation in Firefox, but it's not even included in the Android build, as far as I know.  So the debug setting should do nothing.

Do the logs say anything useful at all?  Is there a log of network requests?

**Comment by jedp** [comment]
Ah - I missed the logcat in the bugzilla bug somehow.  This line looks a little worrisome:

```
E/GeckoConsole( 2304): [JavaScript Warning: "Content Security Policy: 
The page's settings blocked the loading of a resource at 
https://login.persona.org/communication_iframe 
("frame-src https://ssl.google-analytics.com:443 https://firefoxos.persona.org:443")."]
```

`firefoxos.persona.org` is a CNAME for `login.persona.org` which we only use on FirefoxOS.  There turned out to be many hoops through which there was need to jump in order to get this CNAME working on FirefoxOS.  We only jump through these hoops for FirefoxOS user agents - not other mobile devices.  So I'd recommend you try using `login.persona.org` and see how that goes.

[Here is kumar's full logcat](https://bug914415.bugzilla.mozilla.org/attachment.cgi?id=801905)

**Comment by kumar303** [comment]
I disabled CSP on our WebPay server and all those messages went away but the Persona window still wouldn't open. We can rule out CSP. Also, I switched to using login.persona.org for everything but that still didn't fix the issue.

**Comment by shane-tomlinson** [comment]
@jedp - I'm having a hard time understanding the problem, it sounds like this is one of two things - Either a native Android app trying to open Persona, or a desktop Firefox app trying to open Persona. As I understand it, we have never officially supported either of these.

If this a native Android app is trying to open Persona, @seanmonstar has a library - https://github.com/seanmonstar/android-browserid.

**Comment by eholk** [comment]
This sounds like an issue I've been seeing. I have an app where Persona login works fine when I open the page from the Firefox for Android browser, but if I install the page as a Firefox web app then I never see the Persona login window. Incidentally, Persona login does work in app mode in the Firefox OS simulator and an actual Firefox OS device.

**Comment by seanmonstar** [comment]
@shane-tomlinson on Firefox for Android, you can install "webapps" from the Firefox Marketplace, just like FxOS.

I wonder if the implementation has altered popups at all. It'd be great to get any console logs that could be happening. I don't remember how to remote debug Firefox on Android.

**Comment by eholk** [comment]
I was asking some people on the devtools team the other day, and it sounds like remote debugging is sadly not possible yet for Firefox android apps.

**Comment by jedp** [comment]
Based on Shane's [comment](https://github.com/mozilla/browserid/issues/3882#issuecomment-24498733) that this is not officially-supported behavior, I'm venturing to demote this to four stars, since, while it doesn't work, it's not strictly-speaking broken.

@eholk so there's no way to even get any kind of logs?  argh.

**Comment by eholk** [comment]
@jedp - not as far as I know, although I'm far from an expert. I've tried sprinkling some alerts around, but that's not super useful.

I've had a little better luck by hacking include.js to always use the redirect flow. It does all the Persona stuff, but when it returns to my app it doesn't log in. This may be in my code though.

**Comment by seanmonstar** [comment]
A simple test case is to see if `var window = window.open('somepage')` returns the window on one side, and then the opened window has `window.opener` pointing at the original window on the other.

If not, that would explain the error. Is there a way to feature detect or UA sniff a Firefox for Android webapp? Then we could add it in to use the redirect flow. Though, that also sounds like a valid bug to file against Firefox.

**Comment by kumar303** [comment]
@jedp payments are a feature required for Firefox OS on Android -- @andymckay or @clouserw probably know more about roadmap timing for getting payments working on Android.

@seanmonstar I don't know how to attach log files to github but you can grep GeckoConsole in the logcat attached to the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=914415

**Comment by seanmonstar** [comment]
Looking at the code again, I see that the redirect flow would not try to work in the dialog if it successfully found `window.opener` (doesn't try redirect flow till after trying WinChan https://github.com/mozilla/browserid/blob/dev/resources/static/dialog/js/modules/dialog.js#L48-L52). So, that would mean `window.opener` is not set.
1. That sounds like a bug for Firefox.
2. We can work around it if it's possible to detect a Firefox on Android webapp.

**Comment by kumar303** [comment]
@seanmonstar interesting, what do you think the exact bug is in Firefox for Android? @wesj can probably help see if it's a known issue or not.

**Comment by seanmonstar** [comment]
@wesj @kumar303 We use Cross-Window Communication with postMessage. So, a window created with window.open() should have property of `window.opener` point at the originating window. Then we can communicate back to it doing `window.opener.postMessage(message)`.

window.opener does not appear to exist, or else it never would have tried the redirect flow, since it checks for opener first.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
