### ISSUE TITLE
b2g: mozId.watch onlogin fires two times when previous user signed in

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3883]
I'm writing a test for b2g and notice that onlogin fires 2 times, once with the prior signed in account, then the new one.  The prior user should not be logged in till 'sign in' is clicked.
1. pull down my branch, then try python setup.py develop to pick up framework change.
2. run this test:
   https://github.com/edmoz/gaia-ui-tests/blob/persona-apptest/gaiatest/tests/persona/test_persona_app.py
   with something like this:
   gaiatest --testvars=wifi_info.json --address=localhost:2828 test_persona_app.py
3. run again

result: 
Two onlogin events occur, the previous run and the current run.

expected: 
onlogin should only fire one time.

https://github.com/mozilla-b2g/gaia/blob/master/test_apps/uitest/js/identity.js#L63-L66

**Comment by eholk** [comment]
I noticed this issue when I was debugging a Persona login issue last week.

**Comment by jedp** [comment]
Just to make sure I'm understanding the sequence:  First, in a run of a test, you sign in as user A.  Then you go to the test page again to sign in as user B ("run again").  When you arrive at the test page this time, you get an automatic assertion for user A when `watch` is called.  Then you click sign-in and get an assertion for user B.  Is that what's happening?

I think that's the correct behavior for persona, isn't it?  Unfortunately, it's terrible for testing.  I ran into this problem back when I was working on these tests (which you have so helpfully picked up!).  Basically, there's no way to clear persona's state on the device - i.e., there's no way from gaia to reach into the system app and flush localStorage - so the tests pollute each other.

The way I got around this was to see if the persona dialog had a 'not me' link on it.
https://github.com/jedp/gaia-ui-tests/blob/identity-rp-tests/gaiatest/tests/identity/test_identity.py#L68-L70

Not great when you want a deterministic test suite, but I couldn't think of anything else to do. :(

**Comment by edwindotcom** [comment]
I think you're right - when you run the test the second time, once the trusted UI comes up it signs you in, since you didn't log out previously.  Thus the previous assertion is list in li.login on page.  The best way would make sure we're logged out before we run the test.  I'll close this.
