### ISSUE TITLE
Create a FiraSans font pack

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3887]
@shane-tomlinson remarked in [this PR for FirefoxOS fonts](https://github.com/mozilla/browserid/pull/3885) that we ought to create a FiraSans font pack

**Comment by ryanfeeley** [comment]
@jedp @shane-tomlinson Would love to see semi-bold on the RP name (i.e. "Sign into _RP_ with…") without increasing load too much.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I am out of Persona land for a couple of months to work on metrics, @seanmonstar and @6a68 are the ones to hit up for this.

**Comment by shane-tomlinson** [comment]
@jedp - yo, by adding `Fira Sans` to the list of fonts, do the font related CSP errors from #3579 go away? If they do, I'm tempted to let Firefox OS use `Fira Sans` and all other mobile devices use `Fuera Sans` so the errors are avoided.

**Comment by shane-tomlinson** [comment]
Font packs created:

https://github.com/shane-tomlinson/connect-fonts-firasans
https://github.com/shane-tomlinson/connect-fonts-firamono

@jedp, if we need to replace Feura Sans with these, lemme know. One of us can open a new issue for it. 

Closing.
