### ISSUE TITLE
Event on checking localStorage

### ISSUE THREAD

**Issue by gausie** [mozilla/persona#3889]
At the moment I have a login button that:
1. Starts saying "Log in"
2. At the beginning of onlogin (before the XHR request) says "Checking"
3. If the result is successful, says "Log out" else goes back to "Log in".

This is great, except for a brief moment while the DOM loads and before the XHR request has begun, it says "Log in" which may concern users. I would have the button begin by saying "Checking" but there is no event to then change it to "Log in" if onlogin is not called.

Could there be an event made that satisfied this requirement?

**Comment by seanmonstar** [comment]
If you're setting the `loggedInUser` of watch(), then you don't have to wait for `onlogin` to trigger. You already know the user is logged in.

We'll still check to be sure it's the same user, and if so, the `onmatch` event will be called. If it's not correct (user logged out of Persona), we'll trigger the `onlogout` event.

After everything, the `onready` event should always be triggered.

https://developer.mozilla.org/en-US/docs/Web/API/navigator.id.watch

Does that solve your requirements?

**Comment by gausie** [comment]
Well I'd like to have something happen if we confirm that there is no logged in user.

As far as I see it, it seems to be that the process is:
1. Does the localStorage say we have someone logged in?
2. If not, do nothing. If so, do navigator.id.request() with the credentials.
3 etc etc

I would like to know when the localStorage is checked and there's noone logged in.

**Comment by jaredhirsch** [comment]
@gausie please take a look at the MDN docs for watch() and take a closer look at @seanmonstar's comment above, you've got your answer. closing.
