### ISSUE TITLE
new-skool ephemerals http-proxy is getting saturated to MAX_FILES when running real browsers.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3899]
On the new-skool ephemeral's I'm seeing sockets leaked on the http-proxy until the proxy hits MAX_FILES, and stops accepting connections (causing run-all.js to start failing). 

This is not the same as https://github.com/mozilla/browserid/issues/3851. I see that the upgrade to http-proxy@0.10.3 is in place. 

While upgrading 123done.org to http-proxy@0.10.3 (using nodejs@0.10.7) solved the problem in that case, it's not solving things here. 

(Note the previous problem (GH-3851) was about hitting maxSockets of 100 in the socket pool (which would then take 2 minutes to expire); this is different.

On the new-skool ephemerals, there are sockets that get to ESTABLISHED state on the http-proxy process, and then they never goes away (which means we are not getting a FIN, RST, etc.? (or dropping the event socket events in node land))). 

I've tried switching up nodejs versions, http-proxy versions, and Connect versions, on an ephemeral box, but I'm not finding the root problem. But this is something about 304 responses. **curl/uncached requests for include.js are 200 OK; IMS requests hang**. 

But I'm done for the day; later.

(relate to https://github.com/mozilla/browserid/issues/3895 and https://github.com/mozilla/browserid/issues/3851)

**Comment by lloyd** [comment]
hmmm.  at one point I did some serious tuning to up all limits on awsbox's image.  Don't know if that was lost and this is not a regression in application code, or if socket leaking is a new behavior...  

what are STR here?  just hammer an ephemeral deployment till it falls over?  Do I even need persona to repro this problem or can I repro with an awsbox running hello world - IOW - is this a persona specific issue, or an awsbox issue?

**Comment by jrgm** [comment]
So, I tried to reduce this to just simple curl, but it's about real browsers running with caches. 

But, I put this script in place on current login.dev.anosrep.org at `~ec2-user/proxy_svr_est_watch.sh`:

```
#!/bin/sh                                                                                                           

PROXY_PID=$(ps -efww | grep /home/proxy/proxy_server.js | grep -v grep | awk '{ print $2 }')

while [ 1 ]; do 
    echo -n "`date`    "
    sudo lsof -P -n -p $PROXY_PID | grep ESTABLISHED | wc -l
    sleep 10
done
```

Then, from some client box, run `./scripts/run-all.js -e dev -p 6 --platform all` (taking note of https://github.com/mozilla/browserid/issues/3895#issuecomment-24714443, where you'll need to hack automation-tests/package.json to use vows@0.7.0, and other fun).

Anyways, as you run the tests, you'll see the ESTABLISHED count grow. Stop the tests, wait as long as you want, and the count does not go down. (If the count hits ~1024, you'll hit MAX_FILE, and will need to restart ~/proxy/proxy_server.js; but before you restart, try to use a real browser in that state, and the server will not respond).

**Comment by jrgm** [comment]
To answer your original questions:
- I don't think this is about any `ulimit` changes in previous awsbox AMI; maybe if you tweaked TCP or other kernel settings, but this feels more like app level. 
- it could be the app that receives the connections from the http-proxy (via nat). 123done.org seemed to be solved by just updating node-http-proxy when 123done.org was moved to nodejs 0.10.7. But the stale ESTAB connections are between the  client and http-proxy (i.e., nothing appears to be hanging in router, static, browserid daemons).

**Comment by lloyd** [comment]
well, it may be the case that the application (proxy) behavior has changed with the node and version upgrades.  it would be satisfying to have a clear understanding of exactly what's going on.  OTOH, there is a significant difference in max open file limits between proxy user and app user.  I could probably tweak the max open file limit for proxy and put all this to rest - though we might be sweeping a real issue under the rug:

```
[lloyd@crepe awsbox]$ diff -u {app,proxy}.limits.txt
--- app.limits.txt  2013-09-19 15:21:52.000000000 +0300
+++ proxy.limits.txt    2013-09-19 15:21:58.000000000 +0300
@@ -5,7 +5,7 @@
 pending signals                 (-i) 13385
 max locked memory       (kbytes, -l) 64
 max memory size         (kbytes, -m) unlimited
-open files                      (-n) 999999
+open files                      (-n) 1024
 pipe size            (512 bytes, -p) 8
 POSIX message queues     (bytes, -q) 819200
 real-time priority              (-r) 0
```

**Comment by jrgm** [comment]
The proxy process on login.dev.anosrep.org. Not sure why.

**Comment by lloyd** [comment]
parse error.

**Comment by jrgm** [comment]
Actually, nevermind my comment. I was wrong about something (and didn't explain it in actual grammatical sentences in the first place).

**Comment by jrgm** [comment]
Gurgle. On Tuesday this week, the node-http-proxy README was updated to state:

```
"node-http-proxy is <= 0.8.x compatible, if you're looking for a >= 0.10 compatible version 
 please check caronte https://github.com/nodejitsu/node-http-proxy/tree/caronte"
```

**Comment by jrgm** [comment]
So, it seems to me, given the above, that the most expedient path would be to build a new AMI with both nodejs 0.8.x and 0.10.x, with ~proxy configured to run with 0.8.x, and ~app with 0.10.x.

**Comment by lloyd** [comment]
I took the hard road.  Give https://worky.personatest.org a whirl.  it's based on awsbox-0.6.0-beta1 (nginx instead of http-proxy)

lloyd

**Comment by jrgm** [comment]
Seems stable there, (although I can't ssh to that instance to look). Ship it!

**Comment by lloyd** [comment]
added all the keys to the instance so you can take a look around, criticize, and audit.

will ship it monday after implementing the few features we lost, and updating docs!  woot!

**Comment by jrgm** [comment]
Actually, I just pushed my own build with this and noticed that the browserid is not created in the database from this ami (tried amis from us-east-1, us-west-2 and eu-west-1). However, the browserid user does exist on `worky`.

**Comment by jrgm** [comment]
(To be clear, I was using the nginx branch of awsbox).

**Comment by jrgm** [comment]
And also the `browserid` database does not exist. (Easy for me to work around; just needs to added to the AMI, of course).
