### ISSUE TITLE
navigator.id.getVerifiedEmail gives error from pages loaded using file:///

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#39]
browserid returns an error saying "Payload audience does not match provided audience."

**Comment by lloyd** [comment]
update error message "you may not use getVerifiedEmail from local page

**Comment by shane-tomlinson** [comment]
@lloyd - Persona shows an error on startup, but it is more accidental than intentional.

```
    Action: error in null

    improper usage of API: invalid url: missing scheme
```

When loading from a file:/// URL, WinChan passes the origin as the string "null".  This is because extractOrigin in WinChan only looks for https?, if the scheme does not match either http or https, it returns null for the origin.

Should we look for the "null" origin in the dialog and display an error message?

**Comment by shane-tomlinson** [comment]
1*. Over a year old. Closing it down. If we need further action, reopen.

**Comment by mounirlamouri** [comment]
Does that bug being closed means that there is no intention to fix this?

**Comment by shane-tomlinson** [comment]
@mounirlamouri - not particularly, it meant we didn't have a solid use case and champion who would fight to get it done. Want to be that dude?
