### ISSUE TITLE
not well-formed script error on login popup

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#390]
The following error is thrown when clicking Sign-in:

Error: not well-formed
Source File: https://diresworb.org/wsapi/session_context
Line: 1, Column: 1
Source Code:
{"csrf_token":"50cb4de043d169c4146cd5c727e80727","server_time":1318222634807,"authenticated":false}

Repro:
1) goto beta.myfavoritebeer.org
2) Click Sign-in
3) when sign in popup window full loads, verify script error in Error Console window

Expected;
- no script error

Actual:
- not well-formed error

**Comment by shane-tomlinson** [comment]
@lloyd, I can verify this, but it does not seem to affect usability.

What I am trying in the javascript console is to take the above string and run it through JSON.parse, take the result of that and run it through JSON.stringify, which gives a different string all together.

`JSON.stringify(JSON.parse('{"csrf_token":"50cb4de043d169c4146cd5c727e80727","server_time":1318222634807,"authenticated":false}'))`

 results in:

`"{\"csrf_token\":\"50cb4de043d169c4146cd5c727e80727\",\"server_time\":1318222634807,\"authenticated\":false}"`

Is node's JSON.stringify function not returning valid JSON?

**Comment by ghost** [comment]
Verified on Win 7 + Fx 7.0.1.

No errors are displayed in the Error Console when logging in anymore.
