### ISSUE TITLE
What happens when primary IdP becomes available for an adress that's already registred at persona.org?

### ISSUE THREAD

**Issue by omigeot** [mozilla/persona#3902]
Simple case : I've been testing Persona (then BrowserID) with my email adress few months ago, and back then I didn't have a primary IdP. So I got my email address registered at persona.org.

Now I'm trying to run my own IdP, and everything seems fine (esp. according to checkmyidp.org), but wsapi keeps on telling me I'm using a secondary IdP.

Thing is : what's the (expected) path of migration between secondary IdP and primary Idp?

**Comment by callahad** [comment]
Are you comfortable mentioning the name of your domain here?

**Comment by jrgm** [comment]
@shane-tomlinson can you answer here?

**Comment by callahad** [comment]
@omigeot Generally, when you see issues like this it's related to the SSL certificate you're using.

What does this say:

https://login.persona.org/wsapi/address_info?email=foo@YOURDOMAIN.COM

Does this look different?

https://login.dev.anosrep.org/wsapi/address_info?email=foo@YOURDOMAIN.COM

**Comment by callahad** [comment]
(Obviously swap in your domain at the end, there.)

**Comment by omigeot** [comment]
Ok, thanks everyone for your answers, I'll try to be precise.

First off all, I don't mind giving my domain name : migeot.org

Right now, address_info gives me : 

{"type":"secondary","issuer":"login.persona.org","disabled":false,"state":"unknown"}

and 

{"type":"secondary","issuer":"login.dev.anosrep.org","disabled":false,"state":"unknown"}

Guessing which line is from what server is left as an exercise to the reader ;)

Regarding my SSL cert, it's a StartSSL one and shouldn't be a problem. But I'd like to point I'm using SNI - but then I've recently read it's not a problem anymore. Or is it?

**Comment by ozten** [comment]
I don't think node likes the SSL cert (?).

```
./scripts/check_primary_support migeot.org
info: process type is check_primary_support
debug: migeot.org is not a browserid primary: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
debug: migeot.org is not a browserid primary: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
error: migeot.org is not a browserid primary: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
```

**Comment by omigeot** [comment]
Is this the SSL cert, or the BrowserID {private,public} key ?

**Comment by callahad** [comment]
SNI should not be a problem anymore. Looks like your server may not be sending the "StartCom Class 2 Primary Intermediate Server CA" intermediate certificate? At least, as per: https://www.ssllabs.com/ssltest/analyze.html?hideResults=on&d=migeot.org

**Comment by omigeot** [comment]
Well, https://migeot.org/ is recognized by Firefox without extra root certificates, that's as far as I can tell.

**Comment by callahad** [comment]
Yeah. `UNABLE_TO_VERIFY_LEAF_SIGNATURE` would make sense in terms of something being missing in the cert chain. Can you try adding that and checking the address_info endpoints again?

**Comment by omigeot** [comment]
Sure, though maybe not in the next eight hours. Should I see an immediate result on address_info afterwards, or do I need to wait some time (and if so : how long) before re-trying?

**Comment by callahad** [comment]
Dev should should show up effectively immediately. Production may take a few minutes.

Get the cert up, double-check on the ssllabs test page, go hang out for 15 minutes, then test :)

**Comment by omigeot** [comment]
So, it works. For some reason, I had to tell Apache to use a separate sub-ca cert rather than cat'ing it into the certificate file. Since I also renewed said certificate, I'm not even sure that's why it worked.

But it works, and what's more important, it worked almost instantly, even on the production server. Less than five minutes. Myself I consider it closed. Thanks all for your help.

**Comment by callahad** [comment]
Great! Thanks! Let us know if you run into any other bumps.
