### ISSUE TITLE
returnTo URLs are being re-encoded redirecting from email confirmation link.

### ISSUE THREAD

**Issue by rlr** [mozilla/persona#3903]
If I pass `http://example.com/?q=don%27t` as the `returnTo` parameter to `navigator.id.request()`, after confirming my new persona account in the email (fallback auth provider), I am redirected to `http://example.com/?q=don%2527t`. It basically looks like the URL was sent through another pass of encoding which converts the `%` into `%25`.

On SUMO, we pass a lot of URLs that look like this because we support other languages with non-ascii characters. This is messing up the questions they are about to post which is bad. Please fix? :)

For reference, see https://bugzilla.mozilla.org/show_bug.cgi?id=918393

**Comment by seanmonstar** [comment]
Yuck. So, we run the full URL through `encodeURI` to strip bad characters (`<script>`)...

Though, I wonder... if we never display (I can't remember if we do), and only ever do `window.location = storage.getReturnTo(origin)`, then maybe we don't need to encode it?

**Comment by rlr** [comment]
@seanmonstar yeah, I can't think of a reason we need to encode the url if you never display it. Thanks for looking into it!

**Comment by callahad** [comment]
According to #sumodv, this is blocking SUMO's deployment of Persona. That deployment is one of their Q3 goals.

**Comment by callahad** [comment]
**TODO:** Please notify Topal and r1cky in #sumodev once this is resolved.

**Comment by callahad** [comment]
This was merged into dev for the 2013.09.25 train, scheduled to reach production on October 9th.
