### ISSUE TITLE
Let applications request the redirect flow in any environment

### ISSUE THREAD

**Issue by aravindet** [mozilla/persona#3907]
Perhaps through a preferRedirect option on navigator.id.request(); @lloyd suggested I create a new issue for this.

My application (Scrollback) is an IRC widget embedded on third party sites, and I'd like to open a popup to sign users in; if I use Persona there would now be two popups.

As an analogy, imagine if Gmail or Yahoo decided that their OAuth sign in pages wouldn’t support a redirect flow - the Persona identity bridges would have to spawn additional popups, and the experience would be terrible.

We're currently working around this issue by opening our login screen in an iframe on the third-party sites; this still results in three layers showing up: The host site, the scrollback login iframe, and the persona popup. You can see this happen on http://mozillaindia.org (which uses Scrollback).

**Comment by callahad** [comment]
Thanks for the report, @aravindet! I just moved this issue over to our user stories repo, where we track new feature requests.
