### ISSUE TITLE
Persona logs out after page refresh on Safari 6.1 beta on Mtn Lion

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3916]
I downloaded "Safari 6.1 Seed 8" from https://developer.apple.com/downloads/index.action and installed it on Mtn Lion (10.8.5).
After successfully logging in to 123done.org and hitting refresh, I'm logged out and promoted to log in again. Probably the same 3rd party cookies issue as iOS7.

I didn't change any default settings, but it looks like Safari 6.1 is blocking cookies and other website data from third parties and advertisers.

![image](https://f.cloud.github.com/assets/557895/1211221/175a468c-2606-11e3-9249-c0a1a5f63d6e.png)

**Comment by callahad** [comment]
Good lord. Really, Apple? The iOS fix was sufficiently generic that It should also fix this, AFAIK.

Ooh! In IRC @pdehaan confirmed that this is fixed on an ephemeral instance which included the iOS 7 fix.

Of course, this still breaks our ability to do things that require session management (SSO Realms, etc.) in Safari... but at least we're not truly broken.
