### ISSUE TITLE
Old dialog theme displays when signing in with Google/Yahoo 

### ISSUE THREAD

**Issue by zaach** [mozilla/persona#3917]
STR:
1. Go to 123done.org on FxOS
2. Sign in with Gmail address
3. Auth with Google
4. Observe what's seen in the screenshot as the dialog transitions back from Google

Expected:
A style consistent with the current dialog style.

![screen shot 2013-09-25 at 1 18 15 pm](https://f.cloud.github.com/assets/3903/1212928/69e1666e-2620-11e3-8051-8b051ccfce34.png)

**Comment by zaach** [comment]
Also appears with Yahoo, but not with any first-class IDPs.

**Comment by seanmonstar** [comment]
Yep, they were made before the dialog changed styles. Those styles are being loaded from sideshow (and bigtent for yahoo).

**Comment by jrgm** [comment]
This issue exists in sideshow and bigtent:
https://github.com/mozilla/browserid-sideshow/issues/110
https://github.com/mozilla/browserid-bigtent/issues/261

**Comment by shane-tomlinson** [comment]
This is a dup of the other two that @jrgm noted, closing as a dup.
