### ISSUE TITLE
CSRF verification failed. Request aborted. 403 error when signin into Mozillians.org

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3919]
1. goto mozillians.org
2. sign in with persona - using an email ( i tried mozilla.com and gmail.com addresses)

result:
CSRF verification failed. Request aborted. 403 error

looking at http fox, after we authenticate,  i see a ton of redirects, which results in the 403 error.  If i refresh, I'm logged in. 

![screen shot 2013-09-25 at 8 48 58 pm](https://f.cloud.github.com/assets/3698618/1215303/a12a85ea-265e-11e3-8c10-d210c52af051.png)

**Comment by edwindotcom** [comment]
This could be this issue, in which mozillians.org should be contacted:
https://github.com/wbamberg/persona-mdn/blob/master/csrf-problems.md

**Comment by shane-tomlinson** [comment]
@edmoz - Is this a dup of #3074? Secondly, this seems like it belongs in the mozillians.org bugtracker.

**Comment by edwindotcom** [comment]
dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=919472 , closing

**Comment by edwindotcom** [comment]
decrease priority - as this only happens if  you have 2 mozillians.org tabs open
