### ISSUE TITLE
b2g: unable to sign in with gmail or yahoo accounts with cross domain error

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3927]
1. on b2g, browser, goto beta.123done.org
2. attempt to sign on b2g with user@gmail or user@yahoo
   actual: you'll get a
   failed to verify assertion: issuer 'yahoo.login.persona.org' may not speak for emails from 'yahoo.com'

doesn't happen on PROD

**Comment by jrgm** [comment]
"Doesn't happen on PROD" - you mean when you use 123done.org (no beta), right?

**Comment by jrgm** [comment]
If you change you're tollkit uri in prefs to use firefoxos.anosrep.org, beta.123done.org will work (but 123done.org will not). b2g doesn't work like desktop (or am I wrong).

**Comment by callahad** [comment]
Closing. @edmoz please re-open if jrgm's suggestion doesn't fix it for you.
