### ISSUE TITLE
Frontend unit tests output is confusing.

### ISSUE THREAD

**Issue by mohit-agarwal** [mozilla/persona#3928]
When I run the Frontend unit tests against Phantomjs, I get the following output:

![screenshot from 2013-09-28 03 16 50](https://f.cloud.github.com/assets/2356369/1231128/1c492e62-2834-11e3-880e-a253cab8a23a.png)

Is it means it has passed the tests..or still there's some problem?

**Comment by shane-tomlinson** [comment]
@mohit-agarwal - Thanks for filing! Those are expected warnings. Phantom has no way to actually focus an element, so we skip the focus check and display output to the user. We should add a message to the warning that says the warning can be safely ignored under Phantom.

Updated title to be "frontend unit tests output is confusing."

**Comment by es** [comment]
@shane-tomlinson - I've added the following basic message that prints out before the Phantom tests:

NOTE: Warnings PhantomJS throws pretaining to focusing on elements can be safely ignored

**Comment by seanmonstar** [comment]
merged, closing
