### ISSUE TITLE
Form autocomplete popup displayed on wrong page 

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#3934]
Samsung Galaxy SII (Android 4.0.3)
Firefox release (2013-09-30)
123done.org
beta.123done.org

Steps:
1. open www.123done.org
2. press on sign in
3. make sure you have at least one form autocomplete popup entry available
4. tap on the email field
5. form autocomplete pops up 
6. while the form autocomplete popup is displayed, tap on the url bar, enter www.123done.org and hit go

Actual: Form autocomplete popup is displayed on www.123done.org

Expected: Form autocomplete popup is dismissed when exiting the sign in dialog

please see the video:  http://www.youtube.com/watch?v=FhVsSSew54o

Not reproducible on Chrome mobile browser.

**Comment by callahad** [comment]
Wow! That's super crazy! Looks like it may be a Fennec bug?

**Comment by edwindotcom** [comment]
@csuciu persona doesn't have any control over the auto complete display, we believe this is a fennec issue, can you log it there.
