### ISSUE TITLE
[intermittent] not able to sign in on iOS7 to summit.mozilla.org

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3945]
Logging on behalf of #firehug channel, I'm not able to repro this myself.
1. goto summit.mozilla.org
2. tap 'healthy dialog or 3 questions'
3. click sign in
4. in persona form - enter user@mozilla.com
5. enter LDAP passoword, click sign in

Actual: Persona fails with "We are sorry, but currently your browser is not supported. Persona works with Firefox and other modern browsers."

Happens sporadically for iPhone/iOS7 users. For some constantly.

**Comment by edwindotcom** [comment]
@pdehaan said: 
I am UTR on iOS7 (iPhone 4S) on latest Safari and Chrome after 3 attempts using my -moz-ldap email.

**Comment by pdehaan** [comment]
UTR on both Safari/Chrome on iOS7 on iPad 2. :/

**Comment by edwindotcom** [comment]
@digitarald can you paste the results of this page here: http://people.mozilla.org/~fmarier/troubleshoot.html

**Comment by callahad** [comment]
Are these users potentially in Safari's Private Browsing Mode?

**Comment by lloyd** [comment]
utr on both.  I'll bet logging out and logging in will fix it.

try removin a cert from local storage manually to test if this is reprovisioning related?

**Comment by edwindotcom** [comment]
You will definitely get the 'not supported browser' if you're in private browsing mode.

**Comment by digitarald** [comment]
Can messaging improve here? It is a supported browser, but it an unsupported mode; and the the user might be unaware of it.

**Comment by seanmonstar** [comment]
Probably. The assumption was made that if `localStorage` isn't accessible, then it's probably an old browser.

**Comment by shane-tomlinson** [comment]
Relate to #3220 which talks about better messaging for Safari in Private Browsing Mode.

**Comment by callahad** [comment]
Closing. As far as we can tell, this is due to accidental triggering of Private Browsing Mode, and 3220 captures what we need to do to help users in that case.
