### ISSUE TITLE
b2g: signing in doesn't close the trusted UI upon login

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3946]
1. on b2g 1.1 goto 123done.org
2. tap sign in
3. enter user name, then password etc.., click sign in

actual: trusted UI spins with signing in spinner and never closes
user manually closes it and is signed in.

expected: it should close

unable to repro on b2g 1.2

**Comment by pdehaan** [comment]
UTR on B2G 1.2 (inari)
UTR on B2G 1.0 (retail ZTE Open)

Flashing to 1.1 right now.

**Comment by pdehaan** [comment]
UTR on latest 1.1 nightly w/ personal email and gmail/yahoo accts.

**Comment by edwindotcom** [comment]
closing due to @pdehaan !!!
