### ISSUE TITLE
Yahoo login issue: Sorry, we are unable to log you in as alex_mayorga@yahoo.com

### ISSUE THREAD

**Issue by ryanseys** [mozilla/persona#3949]
Forwarded from [Bugzilla 923350](https://bugzilla.mozilla.org/show_bug.cgi?id=923350)

Created attachment [813412](https://bug923350.bugzilla.mozilla.org/attachment.cgi?id=813412)
Log from "Browser Console"

For the past few days, I've kept getting "Sorry, we are unable to log you in as alex_mayorga@yahoo.com" whenever I try to login with Persona into any of the following URLs:

https://login.persona.org/
https://mozillians.org/
https://bugzilla.mozilla.org/
https://webmaker.org/

Attached find the log from "Browser Console".

Please let me know if there's anything I need to provide to solve this.

I've already tried clearing cache, deleting cookies, restarting browser.

**Comment by ryanseys** [comment]
Seems there might be a cross-domain issue  (see the attachment link)

21:53:20.648 Security Error: Content at https://yahoo.login.persona.org/ may not load data from https://login.persona.org/sign_in.

**Comment by seanmonstar** [comment]
It'd be cool to check the logs to see what the exact error is in rejecting the auth. Sounds possibly related to our recent hotfixes.

**Comment by jrgm** [comment]
As fate would have it, I sat down this morning beside Alex ;-)

I think I see the bug. @ozten or @callahad, you guys around? (Probably at dinner right now).

**Comment by callahad** [comment]
@jrgm napping before dinner, but can look tonight. what's up?

**Comment by jrgm** [comment]
@callahad sorry for not updating here earlier. From working with Alex, the claimed_id param in the querystring for the 
return (/auth/yahoo/return) has a pattern that does not have a '/a/' path segment, so it fails the test here:
https://github.com/mozilla/browserid-bigtent_private/blob/train-2013.05.29-hotfix-9-24v3/server/lib/openid-tool.js#L27

**Comment by ozten** [comment]
I made a mistake, looking at [outbound connections](https://github.com/mozilla/browserid-bigtent/issues/23)

```
if (params['openid.claimed_id'].indexOf('https://me.yahoo.com/a/') !== 0) {
```

should be

```
if (params['openid.claimed_id'].indexOf('https://me.yahoo.com/') !== 0) {
```

So that Yahoo can very the rest of the URL.

I'm offline until the 16th, can someone grab this?

**Comment by lloyd** [comment]
@seanmonstar you got this?

**Comment by edwindotcom** [comment]
just to add detail to who this affects: we think this may affect some subset of users who defined their openID identity at a specific point in time.  Doesn't affect all users.

**Comment by jrgm** [comment]
I have filed https://bugzilla.mozilla.org/show_bug.cgi?id=926633 to get this deployed to stage (and from there to production).

**Comment by jrgm** [comment]
Okay, after a delay with DNS issues, this went live at about 'Tue Oct 15 16:38:40 PDT 2013'.

**Comment by alex-mayorga** [comment]
¡Muchas gracias @jrgm! =)
