### ISSUE TITLE
TypeError in the navigator.id.watch() onlogin

### ISSUE THREAD

**Issue by remaerd** [mozilla/persona#3951]
I'm creating an app using CoffeeScript + Backbone + RequireJS. Here's the sample code which do not work. It'll pop out a TypeError {} when onlogin triggered:

``` coffeescript
class Application

      constructor: ->

        navigator.id.watch
            onlogout: -> console.debug 'Logged out'
            onlogin: (assertion) =>
                @login(assertion)

    login: (assertion) ->
        console.debug(assertion)
```

This is the generated JS code.

``` javascript
var Application;
Application = (function() {
      var _this = this;

      function Application() {}

      navigator.id.watch({
        onlogout: function() {
          return console.debug('Logged out');
        },
        onlogin: function(assertion) {
          Application.login();
          return console.debug(assertion);
        }
      });

      return Application;

    }).call(this);
    ({
      login: function() {
        return console.debug('Hello');
      }
    });
    return Application;
```

When I try to use window.login() instead of a Class method. Problem solved. But I still prefer code it in a Class method.

**Comment by seanmonstar** [comment]
That generated Javascript looks wrong. It looks like you might have some
indentation issues in the coffescript, cause the navigator.id.watch call is
being called in a static context, instead of in the constructor.

**Comment by remaerd** [comment]
@seanmonstar You are right! Oh CoffeeScript, This is not the first time I meet this issue. This issue have spend me one day already. Thank you very much.

**Comment by remaerd** [comment]
Sorry to bother you guys again. The Code doesn't work again. Here's the sample code and I don't think it's a CoffeeScript indentation issues. **Do this include.js have an uncompress version so I can learn what is actually happening?** Thank you.

``` javascript
(function() {


  define(['backbone', 'app/router', 'app/views/layout', 'app/models/distributor', 'cookie'], function(Backbone, Router, AppView, Distributor) {
    var Application;
    return Application = (function() {
      function Application() {
        var appView, router;
        appView = new AppView();
        router = new Router();
        Backbone.history.start();
        $.ajaxSettings.beforeSend = function(xhr) {
          return xhr.withCredentials = true;
        };
        if ($.fn.cookie('distributor')) {
          new Distributor({
            cookie: $.fn.cookie('distributor')
          });
        } else {
          this.appView.welcome();
        }
        navigator.id.watch({
          onlogin: function(assertion) {
            return new Distributor({
              'assertion': assertion
            });
          },
          onlogout: function() {
            return console.debug('Hello');
          }
        });
      }

      return Application;

    })();
  });

}).call(this);

```

**Comment by remaerd** [comment]
I figured out that navigator.id.watch() onlogin is too strict about returning type. We can only return a function like $.ajax(). When I copy the $.ajax() codes which was previously belonged to the Distributor Class into the Application Class. It's works fine again.

**Comment by seanmonstar** [comment]
You can see here that we don't do anything with the return value: https://github.com/mozilla/browserid/blob/dev/resources/static/include_js/_include.js#L246

I can't tell you what the problem is. What does the Distributor code look like?

**Comment by remaerd** [comment]
I have to change the Distributor Class so the previous code is deleted. I just simply parse the assertion value so the Distributor Class interact with the server by using $.ajax(). It will return an Object but a function.

**Comment by remaerd** [comment]
I try to rewrite the Distributor Class an upload the code here. And It seems like I made another mistake... There maybe some other indentation issues created in the previous Distributor Class. It's working now.
I'm so sorry to cause you so much trouble... Thank you, again.

**Comment by remaerd** [comment]
P.S: It's quite weird that there were errors in my code. But Chrome Dev Tools keep telling me that error was from include.js. Which make me think that error was generated by include.js. Thanks again.

**Comment by callahad** [comment]
> _It's quite weird that there were errors in my code. But Chrome Dev Tools keep telling me that error was from include.js_

Consider switching (back?) to Firefox. :wink: The performance is great these days, and the built-in dev tools are absolutely fantastic.

Good luck with your project!

**Comment by seanmonstar** [comment]
I'd at least recommend using an editor that shows you whitespace. So you
can tell if those are spaces or tabs, and that things line up correctly.
Many editors have options to do that.
