### ISSUE TITLE
localStorage access blocks Firefox rendering when dialog is embedded into native code.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3955]
Persona's use of localStorage causes a performance hit when embedded in desktop Firefox. @dougt suggests using indexeddb for browsers that support it.

**Comment by callahad** [comment]
1. Is this a non-negotiable blocker to integrating into Desktop, or a wishlist item?
2. Couldn't a native implementation of the APIs do whatever it wanted?

**Comment by callahad** [comment]
(Given all of the fire-drills and inconsistencies around third party access to localStorage, I'm not keen to endure the combinatoric explosion of possibilities and corner cases by using IndexedDB in addition to localStorage.)

**Comment by shane-tomlinson** [comment]
@callahad - 1. fwiu - blocker. 2. context needed

**Comment by callahad** [comment]
@shane-tomlinson Regarding 2: The BrowserID spec wouldn't ever specify that you have to use localStorage -- it'll just state that you have to store the user's keys, and leave the specific mechanism up to the integrator. A compiled, fully-native implementation of Persona in Fx could solve this by using whatever datastore it wanted, right?

**Comment by shane-tomlinson** [comment]
@callahad - The key to this is in the title - "when dialog is embedded into native code" which is what @ozten is working on doing as he tickles out the fallback IdP. He is creating a hybrid part-native part-embedded-in-a-popup Persona. The embedded portion uses all of our client code, which uses localStorage and blocks rendering.

**Comment by callahad** [comment]
@shane-tomlinson Hypothesis: Implementing Goldilocks fully natively is what we'll do long-term, anyways, and it completely avoids complexifying the shim. Am I being too crazy / optimistic?

**Comment by shane-tomlinson** [comment]
@callahad - Goldilocks will affect the communication iframe only, but it won't help out the embedded portion of the dialog. For more context, contact @dougt or @ozten.

**Comment by ozten** [comment]
Dietrich had raised this concern before. The shim as well as the B2G implementation should not use localStorage as it blocks the main thread. This is a change we can make now to help all of our platforms. [IndexedDB](http://caniuse.com/#search=indexeddb) would work for many platforms and fallback to the current working localStorage code for non-modern browser platforms.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
