### ISSUE TITLE
email verfication not working on localhost (in windows)

### ISSUE THREAD

**Issue by Pomax** [mozilla/persona#3964]
After successfully installing browserid using `npm install` and running it through `npm start`, I can start the login procedure and fill in an email address and password, after which the login window tells me to check that email for a verification link. However, no email appears to get sent out. The stdout lists the verification token that it mailed out, but I don't see any email sent, nor any email in the inbox, from browserid/localhost (neither in the main inbox, nor the spam filter box).

Is there something that needs to be set up aside from the general install processing that enables the mail-out service? (or, is there a way to tell browserid that it's running in localhost debug mode and it should just accept the username/password instead of using a verification link?)

**Comment by seanmonstar** [comment]
So, the `run_locally` script sets an environment variable to output the token in the terminal, instead of emailing it (so that we don't need to setup smtp when testing locally.) Simply copy the link out of terminal and paste it into the browser.

**Comment by Pomax** [comment]
for manual work that's pretty useful but I'm trying to run this for an "offline" copy of mozilla's webmaker.org, in order to make life as low-threshold as possible for contributors, so I was hoping there was also some way to get that token without having to scrape a spawned process's stdout (technically easy enough to add, but if there's a bypass, I'll take it! =)

**Comment by seanmonstar** [comment]
You'd want to set this to `false` then: https://github.com/mozilla/browserid/blob/dev/config/local.json#L14

And you would also need to add an smtp property that matches https://github.com/mozilla/browserid/blob/dev/lib/configuration.js#L131

**Comment by Pomax** [comment]
nice, thanks! now to see if this ISP is blocking port 25, which I remember being a hilarious policy in some countries to (unsuccessfully) stop mail spamming.

**Comment by Pomax** [comment]
with an account verified, I'm also seeing rejection objects when trying to auth, of the type:

```
reason: "can't get public key for 127.0.0.1: 127.0.0.1 is not a browserid primary - non-200 response code to /.well-known/browserid"
status: "failure"
```

I have `SHIMMED_PRIMARIES` set to `127.0.0.1:10002|http://localhost:10002|example/primary/.well-known/browserid`, did I forget something else here?

**Comment by seanmonstar** [comment]
I don't think you actually want to set shimmed_primaries. Trying to auth how? Going to htt://localhost:10001/index.html you can test the full sign in process. Port 10001 hosts an example RP.

**Comment by Pomax** [comment]
here's the setup I have now:
- browserid is running seemingly fine, on http://localhost:10002
- the webmaker.org services are running on a number of ports, but all require `include.html` from the main webmaker.org instance running on http://localhost:7777 (loaded in an iframe) -- this file has the actual browserid include.js script, using `<script src="http://localhost:10002/include.js"></script>`
- the include.html contains the persona signin button, it gets clicked, the persona popup happens asking to sign up
- I fill in email address and a password, click okay, and am asked to check my email address
- browserid log shows `http://127.0.0.1:10002/verify_email_address?token=......` which I can curl and effect authentication
- with this valid login, trying to log into webmaker through a `/persona/verify` route that redirects to the real verification URL then results in a verification error:

```
Object {
reason: "can't get public key for 127.0.0.1: 127.0.0.1 is not a browserid primary - non-200 response code to /.well-known/browserid"
status: "failure"
__proto__: Object
}
```

I think what's happening is that the express-persona package we're using is still pointing to verify.login.persona.org instead of the localhost link... would you happen to know the verify url when running locally? I tried to make the express-persona package use `http://localhost:10002/verify` as its verification URI but that doesn't seem to make any difference.

**Comment by seanmonstar** [comment]
Can be found here: https://github.com/mozilla/browserid/blob/dev/scripts/run_locally.js#L76

By default, it'd be localhost:10000/verify

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
