### ISSUE TITLE
Bug 924707 - wrong domain given in error message about third-party cookies

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3966]
via https://bugzilla.mozilla.org/show_bug.cgi?id=924707

---

When logging into Persona with a mozilla.com address with third-party cookies disabled, you get an error message which states you need to enable third-party cookies for "mozilla.com" in order to use Persona.  This is incorrect, and adding this domain to your third-party cookies exceptions does not work.

The correct domain that needs an exception is "login.mozilla.org"

I'm pretty sure this also only applies to mozilla.com and mozillafoundation.org email addresses.  Hopefully this message is specific to the domain (I'm sure google logins need some google domain to be whitelisted, for example).

![Screen Shot 2013-10-08 at 9.06.45 PM.png](https://bugzilla.mozilla.org/attachment.cgi?id=814667)

**Comment by pdehaan** [comment]
OK, as this screenshot demonstrates, it appears to be putting the user's domain-part of their email address as the domain that needs an exception.  This is not correct in either case.  It should be the domain of the IDP that gets used for this message, not the domain part of the email address.

![ Screen Shot 2013-10-08 at 9.20.18 PM.png](https://bugzilla.mozilla.org/attachment.cgi?id=814668)

**Comment by jaredhirsch** [comment]
I could _swear_ this is a known bug but I cannot find it.

**Comment by jaredhirsch** [comment]
@justdave Pinging you here to link this bug to the closed bugzilla bug [924707](https://bugzilla.mozilla.org/show_bug.cgi?id=924707).

**Comment by nickdesaulniers** [comment]
Yes I also ran into this in the past, but after a profile got wiped, I can't seem to find the right domain.  The one listed in the error message is definitely not right.

**Comment by nickdesaulniers** [comment]
Bump and reference #3693 & #4022 & [temp soln](https://github.com/mozilla/persona/issues/3693#issuecomment-21391411).

**Comment by seanmonstar** [comment]
This is fixed in https://github.com/mozilla/persona/commit/43ed85c30f65aafe668ff21f1495e6461f2cdfee but hasn't rolled to production yet.

The trains seem to have run into a dogpile.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
