### ISSUE TITLE
Offer ways to create an email for new Internet users

### ISSUE THREAD

**Issue by nukeador** [mozilla/persona#3967]
We expect a lot of new people to get online thanks to projects like Firefox OS, and for that reason it's likely to happen that a user that wants to log in with Persona doesn't have an email account yet.

For that reason I think it would be useful to have a bottom link "I don't have an email yet" where we can offer ways or services to create one, such as Thunderbird does right now on first run. (It would be awesome to have an API to create the email without having to leave Persona site)

Email providers should be chosen carefully to be just services that respect Mozilla's user values and privacy.

**Comment by shane-tomlinson** [comment]
Closing in favor of mozilla/browserid-roadmap#61 . Will re-open here if this becomes part of the road map.
