### ISSUE TITLE
Explore using `mozbrowser` on ToS/PP in native persona to allow JS to run

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3987]
Our ToS/PP are still broken on native persona because we use JS to load them (and the way we do L10n means it'll be really terrible to change that). Can you guys experiment with `mozbrowser` or something like that to allow those documents to load with scripts? Surely there's a way to pull it off, otherwise hosted apps wouldn't be able to run JS ;)

**Comment by shane-tomlinson** [comment]
@mattbasta - is there some documentation on mozbrowser? I can give it a try once I have some info.

**Comment by shane-tomlinson** [comment]
Some links around the webs:

https://github.com/mozilla-b2g/gaia/pull/7178
https://groups.google.com/forum/#!msg/mozilla.dev.webapi/LFuVuUvqT6Q/pcOcvXIo6sIJ
https://bugzilla.mozilla.org/show_bug.cgi?id=714861

**Comment by mattbasta** [comment]
It's pretty straightforward. You just add the mozbrowser attribute to an
iframe. The only stipulation is that you need to request the permission for
it, but that shouldn't be an issue for persona.

**Comment by lloyd** [comment]
@mattbasta because in firefox os persona is remote content, we can't actually do that.

**Comment by mattbasta** [comment]
Can you explain the risk of allowing JS in the ToS/PP iframe? If Peraona is
remote content then I don't understand how it has any privileges which
could be compromised.

**Comment by lloyd** [comment]
because your private key lives in local storage in the domain, the attack would be identity compromise.

**Comment by mattbasta** [comment]
How exactly could the iframe extract information from the parent's localStorage? That would violate the same origin policy.

**Comment by shane-tomlinson** [comment]
@mattbasta - IIRC in the flurry of last minute FFOS activity, we chose to sandbox the iframe to avoid bad acting RPs from frame busting and taking over the trusted UI. I am not sure if we ever experimented to see our worries were well founded, but we took the cautious approach to avoid shooting ourselves in the foot.

**Comment by mattbasta** [comment]
I've filed a pull request (as you can see above).

A few notes:
- If you don't specify `allow-top-navigation`, it shouldn't be possible to frame-bust the page.
- Even if the page did, it's effectively the same as if they called `window.open`, yeah?
- Everything should be running in its own origin anyway

Please let me know if I'm making faulty assumptions.

**Comment by shane-tomlinson** [comment]
@mattbasta - Using the code in this commit: https://github.com/shane-tomlinson/browserid/commit/f05bf776eafd92621b1cbeea19757b776b8e1e2c which is based off of your PR, I am able to frame bust out of the TOS/PP iframe and take over the trusted UI.

**Comment by mattbasta** [comment]
I'm curious how you tested that. Is it possible that this is
https://bugzilla.mozilla.org/show_bug.cgi?id=785310

That bug seems like it should have much higher priority.

Failing the ability to use `allow-scripts`, could you simply `window.open`
the ToS/PP url instead of showing it inline? It seems like buggering up the
page for the sake of having the content in the trusted ui seems non-ideal.

As far as the ability to take over the trusted UI, what does that actually
mean? What does that do that someone couldn't otherwise do by simply
calling `window.open`?

**Comment by shane-tomlinson** [comment]
@mattbasta - I tested by loading your PR onto my local dev machine, updating my phone's user.js to fetch its resources locally, and open the modified TOS.html link from https://github.com/shane-tomlinson/browserid/commit/f05bf776eafd92621b1cbeea19757b776b8e1e2c.

```
pref('toolkit.identity.uri', 'http://192.168.1.89:10002');
```

As far as calling window.open, we try that first before resorting to the iframe - you can see the code we are using here: https://github.com/mozilla/browserid/blob/e9e99230d12d78bb4739fe28fe762888116cc47a/resources/static/dialog/js/modules/inline_tospp.js#L69-L74

What does it mean to take over the trusted UI? At a minimum, it means you can take over the window that Persona is loaded in. Past that, somebody more experienced with Gecko hacking would know much more.

**Comment by clouserw** [comment]
We have a workaround in place to fix the legal concerns.  It sounds like in the next 3-6mos this will be a non-issue for Mozilla since we're moving to Firefox Accounts.  I'll leave it to the browserid team to decide when this should be closed.

**Comment by lloyd** [comment]
:bomb:

**Comment by jaredhirsch** [comment]
:beers: way to resolve this quickly, y'all
