### ISSUE TITLE
Improve the user experience during key generation (progress bar, lock overlap).

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#399]
This needs UX input.

@lloyd suggests a progress indicator.
@jbonacci notes the delay in #397.
@michaelrhanson notes the lock overlap of the site text in #366.

**Comment by clarkbw** [comment]
hmm, it would be nice to not have a progress bar at all.  What I read from #397 was that we need to generate the key once a person clicks the sign in button and this could take some time on certain platforms like phones/tablets.  Assuming there's no way to get this done in the background I think should go with a progress bar and likely some kind of indication of the average time required for longer times.

On a decent Desktop running Firefox I'm assuming you won't really see this at all.  However with the iPad I think it might make sense to have a moment where we call out "This typically takes 10 seconds" with even an infinite progress bar showing.

The site text was supposed to be locked down so it couldn't grow out of a certain size and wouldn't overlap the lock icon.  We should look into this again.

**Comment by lloyd** [comment]
maybe for now a simple infinite progress bar?  The time and location of the delay will change significantly over the next several weeks as we fiddle crypto code, so I'd suggest to least work possible to visually suggest to the user that work is being done, and this thing isn't stuck :)

**Comment by clarkbw** [comment]
Yeah, lets do that.  Perhaps if we just say something like: "This could take a couple seconds" that's simple enough and will work for most cases.

**Comment by shane-tomlinson** [comment]
@clarkbw - I am in the process of a couple of experiments on this, first is showing the "wait" type screen (like you'd see for "verify your email") - but this looked terrible.  The screen appeared, went away, and then the arrow did its animation.  Not nice at all.

A second simpler approach was to replace the "pick email" email section with text that said something along the lines of "we are authenticating you, this could take a few seconds", but even this looked a bit ghetto on fast machines, as it flashed up really quickly and then went away.  Ideas? 

Should we intentionally show one of those screens for 2-3 seconds even if the keygen finishes before that so that it does not appear too "flashy"?  Unfortunately, we cannot interrupt the keygen after 2-3 seconds to display the screen, or else this might look a bit better.

**Comment by clarkbw** [comment]
Awesome!  I don't mind either one, if the second approach is simpler lets go with that.

On either one can you do a $(".wait").delay(3 \* 1000).fadeIn();  and in your kegen code just call a $.clearQueue() so the fadeIn() never happens if the keygen is done?  Something so the animation doesn't show unless it takes 3 or maybe 5 seconds.

**Comment by shane-tomlinson** [comment]
@clarkbw - unfortunately I can't do _anything_ during keygen, as it never yields back to the main event loop, meaning fading in the delay screen while keygen is happening won't work.  MEH.

I'm going to hold off on this until DSA is in and we can see the performance characteristics.

**Comment by shane-tomlinson** [comment]
closing as #706 has usurped this.  Checkin 35d0e108c002c905bcc3be6737f94c18cc373fd8 initially does clarkbw's idea using CSS transitions - not the smoothest on Android browsers, but it does work.
