### ISSUE TITLE
 login with unverified email is not working on Android

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3991]
@kumar303 reports in [Bug 924985](https://bugzilla.mozilla.org/show_bug.cgi?id=924985):

In Marketplace we use experimental_allowUnverified=true and experimental_forceIssuer=firefoxos.persona.org so that a user on a mobile device can sign in without doing verification.

Should we do the same thing on Android? Since it's mobile, I think yes.

This currently does not work on Android.

STR:
- Install Firefox Nightly on an Android device
- Open https://marketplace.firefox.com
- Tap the gears icon for settings
- Tap Sign In
- Enter a unique email
- When prompted to create/verify a password do so

What happens:

Persona gets stuck in a loop asking you to verify your email. While this is visually jarring it does work. After verifying the email you are logged in.

What should happen:

Persona should honor the allowUnverified/forceIssuer flags and let you log in without verification. I think.

**Comment by seanmonstar** [comment]
Erhm... does this have to do with some server config? B2G loads from firefoxos.persona.org, that allows forceIssuer, where as login.persona.org doesn't?

**Comment by callahad** [comment]
firefoxos.persona.org is just a CNAME to login.persona.org, so that's not it...

**Comment by shane-tomlinson** [comment]
@kumar303 - looking at the compress/minified code on marketplace.firefox.com, I see this line:

navigator.id._shimmed||(r.experimental_allowUnverified=!0)

I am guessing this says, if navigator.id is shimmed, set experimental_allowUnverified to `true`. This looks like it would be causing your issue.

**Comment by shane-tomlinson** [comment]
@kumar303 - after digging in a bit more, it looks like the following lines may be causing the issue:

https://github.com/mozilla/fireplace/blob/master/hearth/media/js/login.js#L65-L74

It looks like if there is a native implementation, experimental_forceIssuer is set to true. If not, experimental_forceIssuer is only set of settings.persona_unverified_issuer is set.

**Comment by jaredhirsch** [comment]
Looks like this is a fireplace bug; closing.
