### ISSUE TITLE
%s placeholder in the check email message

### ISSUE THREAD

**Issue by dodi-br** [mozilla/persona#3994]
Hi,

I'm using Mozilla Persona for authentication, and I've found a strange behaviour, when I use a browser forcing the language for en_US, it works just perfect, when I use the default browser language (that in my case is pt_BR), the message "Click the link in the confirmation email sent to dodi@imdt.com.br to immediately be signed in to webconf.mprs.mp.br." has a %s placeholder instead of the user's email address.

see english step-by-step (that works):
Step 1:
![persona-001](https://f.cloud.github.com/assets/2463703/1392261/c50672f2-3c08-11e3-80fc-4813a91f2775.jpg)
Step 2:
![persona-002](https://f.cloud.github.com/assets/2463703/1392263/c9d19942-3c08-11e3-9a02-fb30739c3828.jpg)
Step 3:
![persona-003](https://f.cloud.github.com/assets/2463703/1392275/e0b646da-3c08-11e3-9dcb-f01358c6aeb3.jpg)
Step 4:
![persona-004](https://f.cloud.github.com/assets/2463703/1392287/0ce1f4ca-3c09-11e3-8b82-44259989108c.jpg)

see portuguese step-by-step (that doesn't work):
Step 1:
![persona-005](https://f.cloud.github.com/assets/2463703/1392290/1a453b86-3c09-11e3-851a-2dbddbbdd883.jpg)
Step 2:
![persona-006](https://f.cloud.github.com/assets/2463703/1392291/2721665e-3c09-11e3-9cb5-572fab446f8b.jpg)
Step 3:
![persona-007](https://f.cloud.github.com/assets/2463703/1392329/9b6f76e0-3c09-11e3-8b78-78013155c958.jpg)
Step 4:
![persona-008](https://f.cloud.github.com/assets/2463703/1392333/a05465c6-3c09-11e3-9dcd-6ac26cfe0d58.jpg)

**Comment by jaredhirsch** [comment]
@mathjazz any thoughts on this bug?

**Comment by mathjazz** [comment]
PT-BR translation is not at 100%, so we must have changed the original strings, but they didn't follow up with translaitons, which makes them "fuzzy".

I just checked that and they actually did translate both of the strings, but didn't commit files to SVN. It should be fixed now.

**Comment by shane-tomlinson** [comment]
Thanks @mathjazz - I'm going to close this as "fixed."

**Comment by dodi-br** [comment]
It's still not working. Is the fixed version available?

**Comment by callahad** [comment]
It generally takes us 2-4 weeks to go from "bug fixed" to "fixed version is tested and online."

**Comment by callahad** [comment]
Screenshot of fix to the first dialog:

![screen shot 2013-10-31 at 11 45 05 am](https://f.cloud.github.com/assets/24193/1447741/46ce3f38-424c-11e3-9633-660b428109c9.png)

**Comment by callahad** [comment]
In deference to QA, reopening until the fix is visible in the staging environment.

**Comment by mgedmin** [comment]
This bug also exists in the lt_LT translation:
![ekrano nuotrauka i 2014-01-30 17 44 48](https://f.cloud.github.com/assets/159967/2041482/a194c2c8-89c5-11e3-8060-4a128a4c8bb4.png)

**Comment by mgedmin** [comment]
The email message I got is also full of '%s', in addition to HTML tags in the text/plain portion:

```
Spustelėkite, kad patvirtintumėte šį el. pašto adresą ir būtumėte prijungti prie %s
https://login.persona.org/verify_email_address?token=XxxxXxxxXxxxXxxxXxxxXxxxXxxxXxxxXxxxXxxxXxxxXxxx

Svarbu: jeigu Jūs NEBANDĖTE prisijungti prie šios svetainės, tiesiog ignoruokite šį laišką.

:::„Mozilla Persona“: %s
:::&lt;strong&gt;Mozilla Persona.&lt;/strong&gt; Supaprastintas prisijungimas, sukurtas, nesiekiant pelno. &lt;a %s&gt;Plačiau&rarr;&lt;/a&gt;
:::Learn more at https://login.persona.org/about
```

(The text/html part also has a `%s` in it.  Just one.)

**Comment by mathjazz** [comment]
LT is at 100%:
https://localize.mozilla.org/lt/browserid/

At least since Nov 2:
http://viewvc.svn.mozilla.org/vc/projects/l10n-misc/trunk/browserid/locale/lt/LC_MESSAGES/?view=log

So this shouldn't be happening.

Is it possible that we didn't have a release for almost 3 months now and latest translations didn't get included?

**Comment by callahad** [comment]
> Is it possible that we didn't have a release for almost 3 months now and latest translations didn't get included?

That is correct. We do not currently have a schedule for when a new release will ship.

**Comment by mathjazz** [comment]
O look, new GH comments! :-)

@callahad Would it be possible to only update translations?

**Comment by callahad** [comment]
I'd leave decision to @gene1wood and @jrgm at this point. We're looking at keeping the current version ("train-2013.10.09") in production for the foreseeable future, so we may need to re-extract the strings and do another localization pass. I believe the current strings in Verbatim are from the train-2013.10.23 branch.

**Comment by gene1wood** [comment]
I defer to @jrgm to make the call. @fmarier also probably has thoughts on it.

**Comment by mathjazz** [comment]
@callahad The latest translations we have in SVN and Verbatim are for train-2013.10.09.

**Comment by callahad** [comment]
Oh, great!

**Comment by jrgm** [comment]
We will not be changing the svn revision in this re-ship of train-2013.10.09. It will stay at r121508.

**Comment by jaredhirsch** [comment]
Hey @mathjazz! Bumping this bug, we should figure out what to do for the next release. I'll ping you on list as well.

**Comment by mathjazz** [comment]
Hey, as soon as we get to ship new trains and localizations, we can fix this bug.

**Comment by jaredhirsch** [comment]
Hi guys, since we just shipped a train and @callahad wants to ship another one with smaller goldilocks-related fixes, maybe we can also rev the l10n stuff for the next release?

**Comment by mathjazz** [comment]
Hey @6a68, Let's do this! ;)

When do you plan to ship the next release? When do you plan to have the strings ready?

Please note that I'll be on vacation until June 24, so it might take a day or two before I respond. If you need something more urgent, please ping l10n-drivers:
https://wiki.mozilla.org/L10n:Mozilla_Team

**Comment by jaredhirsch** [comment]
@mathjazz We haven't really figured out our new release cadence, though monthly is a good guess.

Right now, we are having problems with the personatest.org domain (which has traditionally hosted the localizations). Once we have the test domain back in working order, how about we resume the old process: I'll set up the translate environment as part of branching the train, and I'll be sure to CC you on that email to the dev-identity list, then you can notify l10n-web that Persona is back :-)

**Comment by mathjazz** [comment]
Sounds great!

(Sorry for belated response, I was on vacation until last week.)

**Comment by jaredhirsch** [comment]
@mathjazz no worries, we seem to be a few days away from getting personatest.org back up and running. hope your time off was nice :)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
