### ISSUE TITLE
Cannot sign in - perhaps a GMail or Yahoo address.

### ISSUE THREAD

**Issue by AnimeAlex321** [mozilla/persona#3999]
Whenever I try to log in to a website with Persona, a big problem occurs.
I log into the website and it makes me verify my email address. When i verify the email that I want, it takes me to another page that says that Persona would like to: View my email address, and it won't let me hit the "Accept button". I don't know why it does that, maybe the link is broken or something? I would at least like a reply as to why it would do this. I have seen people do it before and it worked perfectly for them but it is not working for me. So please can someone fix this.

**Comment by callahad** [comment]
@AnimeAlex321 Who is your email provider? What browser (and version!) are you using? Do you have any add-ons installed, and if so, which ones?

**Comment by shane-tomlinson** [comment]
@AnimeAlex321 - are you using either a GMail or a Yahoo address?

**Comment by shane-tomlinson** [comment]
I suspect this is either a GMail or Yahoo address since there is an "accept" button, indicating OAuth or OpenID.

**Comment by callahad** [comment]
I'm going to close this -- Alex, please re-open if you come back with more information.
