### ISSUE TITLE
Consider mentioning the dangers of using https in Python

### ISSUE THREAD

**Issue by toolness** [mozilla/persona#40]
I'm working on a Python-based browserid auth mechanism, and realized that all the major built-in ways of doing HTTPS in Python--via `httplib`, `urllib`, and `urllib2`--offer no way to check the server's cert. This is terrible, and effectively means the communication occurs over HTTP.

Some searches on google yield two particularly interesting links:
- http://bugs.python.org/issue1114345
- http://stackoverflow.com/questions/1087227/validate-ssl-certificates-with-python

Anyhow, it seems doing HTTPS the right way in Python is nontrivial, so it'd be nice if we provided a bit of guidance here, so that folks don't accidentally introduce vulnerabilities into their apps.

**Comment by lloyd** [comment]
+1, this warrants a line or two in step 3 of the tutorial, and as we evolve myfavoritebeer.org we should call it out again.

**Comment by benadida** [comment]
Atul: you're concerned about the call to the verifier, right?

Agreed that this is a significant problem for Python. I think we may want to shell out to curl or, if the user is willing to install pycurl, use that:

http://pycurl.sourceforge.net/

**Comment by paulosman** [comment]
Might be worth mentioning Joe Gregorio's [httplib2](http://code.google.com/p/httplib2/) library which does certificate validation by default.

**Comment by benadida** [comment]
now addressed in https://github.com/mozilla/browserid/wiki/Security-Considerations-when-Implementing-BrowserID
