### ISSUE TITLE
The Signing in dialog hangs until the user manually closes it when trying to log in to a deleted email

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#401]
Environment:
Win 7 + IE9
Mac 10.6 + Firefox 7.0.1

STR:
1. Open http://beta.myfavoritebeer.org.
2. Click on the sign in button, enter an email and a password and log in.
3. After the dialog with the list of emails is displayed, load "https://diresworb.org" in another tab/window.
4. Sign in with the same account on diresworb.org and delete an email associated to it.
5. Go back to the dialog with the list of emails.
6. Select the deleted email and click on the "sign in" button.

Expected Results:
 An error message reminding the user know that he removed that email is displayed. The emails list on the dialog is afterwards refreshed.

Actual Results:
 The Signing in dialog gets grayed out and it just hangs until the user manually closes it.

**Comment by ghost** [comment]
Apparently this issue has not been completely fixed for the case when the user has only had one email address associated to BrowserID and deleted it at step 4.

In this case: an error message is displayed, then the emails list dialog is refreshed but a wrong page is opened after the refreshing. Considering that the user deleted his only email address (or all of them if they were more), the signing in dialog with the email textbox should be displayed after the refresh.

Currently, the email list dialog is still displayed after the refresh but with no emails on it. Whenever the user clicks on the Sign in button, the page is refreshed and the same page is opened. The only workaround for the user is to manually close the dialog, then reopen it (same problem as initially).

Please reopen the bug based on this (I don't have the rights to do it myself).

The fix seems ok when the user has multiple emails associated with BrowserID and only deletes one/some of them.

**Comment by shane-tomlinson** [comment]
this brings up a larger point of how to do we deal with accounts that are deleted via the main page while the dialog is open?  This could happen at any stage after authentication, something we need to know about.  

We need to know at any point of the user is no longer authenticated.

Deferring to Needs Discussion.

**Comment by csuciu** [comment]
Test case added  https://moztrap.mozilla.org/manage/caseversion/23754/
