### ISSUE TITLE
attempting to insert text in trusted UI resuts in OOM error and black screen

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#4015]
I'm on a Buri with today's 1.2 eng build
STR:
1. Open Tools > App Manager (in FF nightly) (might have to install adb helper)
2. Add http://download.atlasct.com/evernav/manifest.webapp as a hosted app
3. Connect to device, accept prompt on phone, push, then run Evernav
4. Go through sign in flow
5. you may have to logout, then sign in again

Expected:
able to type into field

Actual:
screen goes black when i click in the text field.  I've tried restarting and clearing all other running apps.

here's lolcat:

```
D/wpa_supplicant(  385): RX ctrl_iface - hexdump(len=11): 53 49 47 4e 41 4c 5f 50 4f 4c 4c
D/wpa_supplicant(  385): nl80211: survey data missing!
E/QCALOG  (  187): [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
E/QCALOG  (  187): [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
E/QCALOG  (  187): [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
E/memalloc(  140): /dev/pmem: No more pmem available
E/msm7627a.gralloc(  140): gralloc failed err=Out of memory
W/GraphicBufferAllocator(  140): alloc(320, 480, 1, 00000133, ...) failed -12 (Out of memory)
E/memalloc(  140): /dev/pmem: No more pmem available
E/msm7627a.gralloc(  140): gralloc failed err=Out of memory
W/GraphicBufferAllocator(  140): alloc(320, 480, 1, 00000133, ...) failed -12 (Out of memory)
D/wpa_supplicant(  385): RX ctrl_iface - hexdump(len=11): 53 49 47 4e 41 4c 5f 50 4f 4c 4c
D/wpa_supplicant(  385): nl80211: survey data missing!
```

**Comment by seanmonstar** [comment]
Er, so did b2g 1.2 break something? Is this an upstream bug?

**Comment by callahad** [comment]
Sounds like an upstream issue -- tagging as 4-stars and handing over to @jedp

**Comment by edwindotcom** [comment]
I'm guessing that the EverNav app uses a lot of memory, and when the trusted UI launches - we hit OOM

**Comment by edwindotcom** [comment]
On 1.3 with Inari - i started repro'ing this and crashing all over marketplace- but then after restarting (and pushing "identity.debug", true) I can't repro this anymore.

**Comment by jedp** [comment]
It just bit me.  Steps:
1. Sign in with Persona
2. Enter a mozilla.com email address
3. Delegates to mozilla's LDAP sign-in iframe
4. Screen goes black, apparently right when password field gets focus

Note that it's not the Trusted UI (Persona's container) that goes black - it's the entire screen.

So this can't be a Persona bug; it's affecting drawables outside of our iframe.

**Comment by edwindotcom** [comment]
I'll log a bugzilla bug now and reference this

**Comment by jedp** [comment]
I'm using a nightly 1.2 build on hamachi.

Oh wow.  `adb` no longer sees the device.

Screen goes black, phone is unreachable.  Perfect security through the Sign-in screen! :)

**Comment by jedp** [comment]
More info - when the phone wakes up again, I pass the unlock screen and go back to sign-in.  Password field is still in focus.  I start typing, and the phone flickers like crazy, flashing to black with every keystroke, and periodically going black for a few seconds.

**Comment by edwindotcom** [comment]
logged a gaia bug: https://bugzilla.mozilla.org/show_bug.cgi?id=942331

**Comment by jaredhirsch** [comment]
the gaia bug (942331) was closed as invalid, closing.
