### ISSUE TITLE
Windows Phones with Persona

### ISSUE THREAD

**Issue by satdav** [mozilla/persona#4016]
it seems on bugzilla what their is a issue with windows phone using persona when you login on bugzilla it keeps you logged out 

I would like QA to verify this

steps to repoduce it 

goto bugzillla.mozilla.org
Click on login 
press the persona button
enter your persona details then click login 
it takes you back to the main screen not logged in 

this was done on a mozilla.org.uk email address on windows phone 8

**Comment by satdav** [comment]
this issue happened on windows phone 8 on the internet explorer browser

**Comment by callahad** [comment]
Upstream issue. Bugzilla is neutering the Observer API by ignoring all automatic invocations of the `onlogin` callback. Thus, when the redirect flow returns to Bugzilla and tries to pass in an assertion, the login callback ignores it.

Relevant snippet from Bugzilla's code:

``` javascript
var persona_ignore_login = true;

function persona_onlogin(assertion) {
  if (persona_ignore_login)
    return;
    var form = document.createElement('form');
    form.action = 'https:\/\/bugzilla.mozilla.org\/index.cgi?GoAheadAndLogIn=1';
    form.method = 'POST';
    form.style.display = 'none';

    createHidden('token', '1383815312-d64fe2f99f15860be6ad647efa3b0a2c', form);
    createHidden('Bugzilla_remember', 'on', form);
    createHidden('persona_assertion', assertion, form);

        createHidden('GoAheadAndLogIn', '1', form);

    document.body.appendChild(form);
    form.submit();
}

YAHOO.util.Event.on(window, 'load', persona_init);
function persona_init() {
  navigator.id.watch({

    loggedInUser: null,
    onlogin: persona_onlogin,
    onlogout: function () {

    }
  });
}

function persona_sign_in() {
  persona_ignore_login = false;
  navigator.id.request({ siteName: 'Bugzilla\x40Mozilla' });
}
```

**Comment by callahad** [comment]
We should file an upstream bug once the Goldilocks API lands in production.

**Comment by satdav** [comment]
@callahad  when is that planned for production

**Comment by callahad** [comment]
We've run into unexpected issues deploying. Given other QA / Ops constraints, it will likely not happen until February. :(

**Comment by satdav** [comment]
@callahad Hi Dan do you know if this has been added yet as still not working for bmo

**Comment by jaredhirsch** [comment]
@satdav We certainly hope to get a release out in the next 1-2 weeks, but there's no firm timeline, because Persona maintenance is now only done outside work time. If you want to keep up-to-date on our progress, maybe subscribe to the dev-identity list :-)

**Comment by darkwing** [comment]
Has there been any action here?  Is there a fix outside of upgrading persona for MDN?

**Comment by jaredhirsch** [comment]
@darkwing we've gotten a few releases out since my last comment, but I don't have a windows phone to try to repro the bug. Is there a corresponding bug against MDN?

**Comment by jaredhirsch** [comment]
@darkwing Ah, I should have finished reading the rest of my bugmail ;-)

Looks like #2009 got bumped, corresponding to mozilla/kuma#2826.

I'm not actively working on Persona right now, maybe @callahad has other info

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
