### ISSUE TITLE
Persona is not working with Konqueror Browser

### ISSUE THREAD

**Issue by ohawk** [mozilla/persona#4018]
While trying Personal with Konqueror Browser , then I was getting following error
Site: https://bugzilla.mozilla.org/

---

Error
 Please close this window and try again. 
 See more info 
Action: error in localStorage 
 Now: Fri, 08 Nov 2013 01:34:22 GMT 
##  could not decode localStorage: ReferenceError: Can't find variable: sessionStorage

Sorry for report if it not supported browser.

Detail for Konqueror
## http://konqueror.kde.org

Konqueror
Version 4.11.3

**Comment by fmarier** [comment]
The problem is that konqueror doesn't have support for localstorage and sessionstorage and these technologies are required for Persona to work:

https://people.mozilla.org/~fmarier/troubleshoot.html
