### ISSUE TITLE
https://diresworb.org/about should contain the sign up and adding emails processes

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#402]
OSs: All
Browsers: All

STR:
1. Go to "https://diresworb.org/about" (can be opened from the "Take the tour" and "How it works" links on the server and the "learn more" link from the client).

This page should also contain the sign up and adding emails processes. The current information on it leaves the user wondering how his email addresses can get in the "Sign in using" section. 

A user that only found out about BrowserID after getting to a page using BrowserID and clicking on the "learn more" link might even think it simply collects the emails used in the browser or something similar. This might raise privacy/security concerns and lead him not to use it.

**Comment by lloyd** [comment]
the current about page is a place holder until dan gets off his butt and does the screen cast, which will make it better.
