### ISSUE TITLE
"too busy' behaviour triggered too easily

### ISSUE THREAD

**Issue by karlht** [mozilla/persona#4027]
This is blocking deployment of train-2013.10.23; see https://bugzilla.mozilla.org/show_bug.cgi?id=939961#c5

Paging @6a68, @seanmonstar, @callahad ...

Excerpted from http://irclog.gr/#show/irc.mozilla.org/identity/336253:

``` bash
<kthiessen> jrgm: Any word on the reduced-limit load tests?
<jrgm> kthiessen: still there? 
<jrgm> So, I ran at 100K, down from 250K, and still had errors, but much less than @250. 
 But then I went back to @250 and the error rate was much less than it had been. 
<jrgm> kthiessen: but here's the real bottom line. 
<jrgm> I don't need to use a load test to trigger a 'too busy'. I can just run selenium tests (e.g., a few users can cause spurious 'too busy'). 
 But _6a68, you around? 
<kthiessen> jrgm: Ack!  Yes, I'm still here.
 jrgm: That makes me wonder why I didn't see badness when I ran the automation, though.
<jrgm> kthiessen: heisenbug. You get the random 503 loading a gif, and I get it when calling session_context? 
<kthiessen> jrgm: So is this likely to be a completely spurious 'too busy' (i.e. an error in measuring the threshold event) or an increase in load per request?
<kthiessen> Anyhow, I'm thinking we're going to need dev help to dig our way out of this.  seanmonstar, _6a68, callahad: Anybody around?
 jrgm: Meanwhile, do you want to file the Github issue, or shall I?
```

**Comment by jaredhirsch** [comment]
@callahad / @seanmonstar / @fmarier: can one of you own this?

10/23 was an enormous train. logging changes, additional metrics, app routing changes: [here's](https://github.com/mozilla/persona/compare/train-2013.10.09...train-2013.10.23) the unified diff vs the previous train, "Showing 119 changed files with 2,414 additions and 996 deletions."

looking a bit now at the logs on stage, i'll put everything in the bug, and plan to hand this off as soon as one of the active persona devs jumps in here.

**Comment by seanmonstar** [comment]
I'm on PTO for another week. However, that train adds a bunch of logging
logic, and sends data to kpi backend. If that's clogging resources much,
I'd consider making a dedicated log process. I started one a while ago, but
it's not far along.

**Comment by jaredhirsch** [comment]
@seanmonstar derp, I didn't think to check your availability on the calendar, sorry! As you were :-)

I guess I'll switch focus to help get this train deployed.

**Comment by jaredhirsch** [comment]
So, I didn't see anything in the logs, but didn't really know quite what to look for.

I spent some time running load_gen against a micro instance on Friday, noticed it was always hitting toobusy when I kicked off load_gen (which starts by trying to create 100 users against the API). Sadly, I discovered a bit late in the afternoon that micro instances _always_ freak out when you hit them with load_gen (including the previous 10-09 train).

I'm not sure how to repro outside the stage environment, I'll work on that next.

**Comment by shane-tomlinson** [comment]
I have been trying to look into this on a c1.medium instance and unfortunately cannot push to any instance that I create. :/ Can someone with load_gen foo do me a favor and comment out lines 38-40, where StatsdTransport to MetricsKpiggybankTransport are added as transports? If the load tests pass, then we have pinpointed the problem.

**Comment by jrgm** [comment]
So like lines 38-40 of every file, or just one in particular? ;-)

**Comment by jrgm** [comment]
Obviously, 30-40 of lib/logging/logging.js. Sorry, was lazy and didn't grep first.

**Comment by jaredhirsch** [comment]
@shane-tomlinson I'm working with @gene1wood right now to spin up a stage-like stack, we're talking through how I can make code changes and rsync them out to the cluster. I'll be tweaking that shortly.

@jrgm if there are special incantations I'll need to repro the toobusy problems, would you mind pasting them in here or linking to whatever doc holds them?

**Comment by gene1wood** [comment]
Stack 1125 is up and usable now.

**Comment by jaredhirsch** [comment]
right now, @jrgm is running some load tests in stage to see what happens if some of the logging code is disabled. more to come.

**Comment by lloyd** [comment]
spent a couple hours with @shane-tomlinson searching for regressions which might explain this data.  We uncovered issue #4030 and issue #4031.  Both regressions make me nervous. 

As unlikely as it sounds, the statsd upgrade (#4031) is introduced between train-2013.10.09 and train 2013.10.23 which is where this regression seems to be relevant.  Best theory, if this change is in fact the culprit, would be resource leakage.  

I am not completely clear the ultimate culprit is named in these two issues.  Look forward to more data that lets us understand whether this load test regression is significant.

**Comment by callahad** [comment]
Leading theory (especially since we've now seen this in current production with #4039) is that AWS performance goes crappy over the holiday shopping season.

Mitigation plan: dramatically increase the `maximum_event_loop_lag` config variable to effectively disable toobusy.

**Comment by jaredhirsch** [comment]
Hmmmmmm, this is interesting. @jrgm @gene1wood some questions:
- Are we seeing any indications of degraded performance in Opsview?
- If AWS is handing us degraded instances, should we have seen toobusy errors with the previous train?
- Or are we thinking the problem is that new instances are crappier than usual? (If that's the case, we could test it by spinning up a new cluster running the previous train, and looking for toobusy errors.)

**Comment by ozten** [comment]
+1 to jrgm's patch, instead of disabling this feature.

Also, it would be interesting to monitor Node event loop latency to see AWS QoS degrade.
