### ISSUE TITLE
received expired assertions

### ISSUE THREAD

**Issue by dustin** [mozilla/persona#4028]
I've got an application that uses persona and recently was unable to process logins.  This is a custom authenticator written in go with the following piece of relevant code:

```
    if time.Now().Unix()*1000 >= int64(resdata.Expires) {
        glog.Infof("browserId assertion had expired as of %v (current is %v)",
            resdata.Expires, time.Now().Unix())
            showError(w, r, "Browserid assertion is expired", 500)
            return
    }
```

This yielded the following log entry:

```
Nov 22 18:42:52 console 2013-11-23T02:  44:56Z ip-10-165-41-197 consolio[29213]: I1123 02:44:56.369251 29215 auth.go:189] browserId assertion had expired as of 1385174689687 (current is 1385174696)
```

`current` is in seconds, so that'd be 1385174696000ms.  The difference between current and expires is -6313, or an expiration date about 6 seconds ago.

1385174689000 is about Sat Nov 23 02:44:49 2013, so the times make sense.

In the meantime, I've stopped considering this an error and allow users with expired sessions in.

**Comment by fmarier** [comment]
Could it be due to some clock skew between your server and ours?

**Comment by dustin** [comment]
I did set up ntp on these boxes after this, but it was only a couple minutes off at most -- you can see the `42:52` vs. `44:56` there which should represent the difference between my machine and papertrail.

Also, the two timestamps (expiration from the response and my local time) are very near each other.  Closer than the overlap gap here:

```
1385174689 Sat Nov 23 02:44:49 2013  # from persona
1385174696 Sat Nov 23 02:44:56 2013  # local
```

I assumed this expiration would be some distance in the future.  How far from synchronized UTC should I expect an expiration to be?

**Comment by callahad** [comment]
The assertions we generate are only valid for two minutes: https://github.com/mozilla/persona/blob/c8bbf013de28bd46536e908d7981ba8c0d23e095/resources/static/common/js/user.js#L1302-L1304

**Comment by callahad** [comment]
@dustin Sorry for the delay, I didn't see this thread. I think things are behaving as intended. If you're doing local verification, you need a reliably synchronized local clock. Depending on your needs, you may want to locally add tolerance for a small amount of skew.

(Also, please make sure you're subscribed to the [persona-notices](https://mail.mozilla.org/listinfo/persona-notices) mailing list. We're going to be defining some changes to the assertion format in the next 6-8 weeks, and you'll want to keep your verifier up to date. :))
