### ISSUE TITLE
Bad Gateway returned when sending assertion

### ISSUE THREAD

**Issue by BitPuffin** [mozilla/persona#4029]
Hey Mozilla!

I am trying to implement persona in a webapp and I get to the stage where I post away the assertion+audience to persona for verification. But, what I get back is a 502 Bad Gateway response. The thing that is puzzling is because I am currently only testing on my local machine so the audience would be localhost in this case, and I have tried various different forms, such as "localhost" "http://localhost" and "https://localhost" (with ":5000" at the end of each variation). I can't for the life of me figure out what I am doing wrong as I am basically just doing exactly what the quick start guide tells me except adapted to the programming language I am using (Nimrod).

Here is the relevant code:

``` nimrod
const
  hostname        = "localhost"
  port            = 5000
  personaVerifier = "https://verifier.login.persona.org/verify"
  userCookie      = "useremail"

post "/user/personalogin":
  let ass = request.params["assertion"]
  if ass == "":
    halt(Http400, "assertion was not found in the request")

  let data: PJsonNode = %{"assertion": %ass, "audience": %("https://" & hostname & ":" & $port)}
  echo "yes we have arrived"
  echo ($data)
  let response  = httpclient.post(personaVerifier, body=($data))
  # This is never printed as the above line 502s.
  echo "got here"

  if response.status == "OK":
    let verificationData = parseJson(response.body)

    if $verificationData["status"] == "okay":
      # TODO: Set this to a secure cookie (an hmac)
      let email = $verificationData["email"]
      setCookie(userCookie, email, daysForward(7))
      if not isUser(email):
        redirect("/signup")
      else:
        # TODO: Redirect to current page instead
        redirect("/")

  else:
    halt(Http500, "Something went wrong when authenticating")
```

And a sample assertion sent would be the following:

``` json
{ "assertion": "eyJhbGciOiJSUzI1NiJ9.eyJwdWJsaWMta2V5Ijp7ImFsZ29yaXRobSI6IkRTIiwieSI6ImI5OTE3MjBmNTg5NmY0ODM2YzQyYzQxNmQ3NGUzMzRkZTc5MDcwNzljZDJlNGExNTdjM2Y4MDMwNTFmODJjNjAyZDZkYjNhZWI1MTcxNWE0NTFiODNlMzJlYmExMjM2NGVmZDBlZGQ4MjFiYmM3NjRjMzBjOTM1YTMzNGFlODA4MGE2YzAzZWIzOWI2YTY0Njc1MmEwOGZmODUzY2M3ZDg0ODQwZThmNzk4MDZlY2U0YWYzNTk2ODlhMWZkOTMzMzY0ODUwZDc3MWY0ZTg4YjQ2MjFkY2Y5ZDFjNzJiMzQ5NjkzOWQxZmJkNDJlNmVmOWE3ZTExZTlkMWM5NTg3NzUiLCJwIjoiZmY2MDA0ODNkYjZhYmZjNWI0NWVhYjc4NTk0YjM1MzNkNTUwZDlmMWJmMmE5OTJhN2E4ZGFhNmRjMzRmODA0NWFkNGU2ZTBjNDI5ZDMzNGVlZWFhZWZkN2UyM2Q0ODEwYmUwMGU0Y2MxNDkyY2JhMzI1YmE4MWZmMmQ1YTViMzA1YThkMTdlYjNiZjRhMDZhMzQ5ZDM5MmUwMGQzMjk3NDRhNTE3OTM4MDM0NGU4MmExOGM0NzkzMzQzOGY4OTFlMjJhZWVmODEyZDY5YzhmNzVlMzI2Y2I3MGVhMDAwYzNmNzc2ZGZkYmQ2MDQ2MzhjMmVmNzE3ZmMyNmQwMmUxNyIsInEiOiJlMjFlMDRmOTExZDFlZDc5OTEwMDhlY2FhYjNiZjc3NTk4NDMwOWMzIiwiZyI6ImM1MmE0YTBmZjNiN2U2MWZkZjE4NjdjZTg0MTM4MzY5YTYxNTRmNGFmYTkyOTY2ZTNjODI3ZTI1Y2ZhNmNmNTA4YjkwZTVkZTQxOWUxMzM3ZTA3YTJlOWUyYTNjZDVkZWE3MDRkMTc1ZjhlYmY2YWYzOTdkNjllMTEwYjk2YWZiMTdjN2EwMzI1OTMyOWU0ODI5YjBkMDNiYmM3ODk2YjE1YjRhZGU1M2UxMzA4NThjYzM0ZDk2MjY5YWE4OTA0MWY0MDkxMzZjNzI0MmEzODg5NWM5ZDViY2NhZDRmMzg5YWYxZDdhNGJkMTM5OGJkMDcyZGZmYTg5NjIzMzM5N2EifSwicHJpbmNpcGFsIjp7ImVtYWlsIjoiY29udGFjdEBiaXRwdWZmaW4uY29tIn0sImlhdCI6MTM4NTIxNTQyNTc2MywiZXhwIjoxMzg1MzAxODI1NzYzLCJpc3MiOiJsb2dpbi5wZXJzb25hLm9yZyJ9.Xt8UCPKTsQA_FTpcgesxpHED_mZNqdy9kalhFl_TEXqElH0mtdAQjaVZcMcpsJauY1k0y-ZujLg3J2_nZf5NBMCn_qc0fMRB2Bee1BuXmP5b2ZDfFr0sCuhMiMyqVyI0B13pFOONn0ZboXIApWPcTR4ywwaufoI6cxYluWkwETnb3_ShsYyC8-wq8lXk2Rp6Uys12oRdduZbWqkVRXQWACQ3W-K0zKgPuIPYt3dH0fejEnv3OMPLMaD0FCKQCrUg4yPlIHN3XyhJcXcj5gbpti2eDCBBw92E04bXvt9gXqwvrnnQwrGvKJz4DPhXJnHbaGzXh97TRTYFZbSUZ85I-A~eyJhbGciOiJEUzEyOCJ9.eyJleHAiOjEzODUyMjg3MjQ1ODUsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJ9.VJdartPC8rtcgiAPCZkaIURk5tQli7ZEkVQIQdaujw0hRYkg2yL5qw",  "audience": "https://localhost:5000"}
```

I wish the documentation was a little bit more clear about what to put for audience when testing on localhost..

Thanks!

**Comment by fmarier** [comment]
If you're visiting your site on `http://localhost:5000`, then that's what the audience should be as well.

I've never seen that `502` error before. If you want to make sure that the problem is in your code (as opposed to your server/computer config), you could try running the [PHP cookbook example](https://github.com/mozilla/browserid-cookbook/tree/master/php). If that works, then there's something wrong with your application. If it doesn't work, then there's something wrong outside of your app.

**Comment by BitPuffin** [comment]
Hi fmarier

Thank you for your answer, I'll give it a try when I get home and see if I can figure out what's going wrong.

**Comment by BitPuffin** [comment]
Ugh, figured it out, I had to compile my application with -d:ssl. Good thing to keep in mind for anyone else writing Jester applications in Nimrod planning to use Persona! Thanks for the help, Mozilla is great!
