### ISSUE TITLE
The "This is not me" and "Use a different email" links should be rearranged on the Signing in dialog

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#403]
OS: All
Browser: All

STR:
1. Open http://beta.myfavoritebeer.org.
2. Click on the Sign in button.
3. Enter and email address and a password on sign in.
4. Observe the dialog with the list of emails.

The "This is not me" and "Use a different email" links:
- could be larger
- should be displayed closer to the line separating the footer from the rest of the page
- should the aligned with the email addresses list

**Comment by benadida** [comment]
assigning this to @skinny97214

**Comment by skinny97214** [comment]
http://cl.ly/1R0i0I3r1o3D0c2O1Q0b
- rename "use a different email" to "add another email"
- move "this is not me"

**Comment by ozten** [comment]
I've done this work and submitted for review:
https://github.com/mozilla/browserid/pull/1252
