### ISSUE TITLE
3x more computation used with newer winston

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#4030]
In sha 22d26c440ba74ac2103072cf8dd064a4bde842b9 we updated winston to fix logging on node 0.10.  See issue #3892 

Along the way, we added a significant performance regression.  STR:
1. ENABLE_STATSD=1 NODE_ENV=test_mysql npm start
2. ab -n 10000 -c 300 http://127.0.0.1:10002/wsapi/session_context

try this at the sha and after the sha.  Notice the processor usage difference.  After the winston upgrade there is a period of 100% cpu usage in the router process that proceeds for 3x the amount of time the initial ab run takes.

/cc @jrgm

**Comment by shane-tomlinson** [comment]
Link to flatiron/winston#227

**Comment by seanmonstar** [comment]
I have a branch that converted all of this to use intel, will run
benchmarks against it when I get back to see if I can improve things.

**Comment by lloyd** [comment]
love it, @seanmonstar.  now, go be on PTO.

**Comment by shane-tomlinson** [comment]
I have tracked the problem down to these lines in winston:

https://github.com/flatiron/winston/blob/2c93353df7dd85a2b27fc3ca07e5294ff0c04097/lib/winston/transports/file.js#L168-L175

I can drastically increase performance (to ~former levels) by changing line 168 to:

```
  return this._stream.write(data, callback);
```

**Comment by shane-tomlinson** [comment]
Also link to flatiron/winston#296

**Comment by lloyd** [comment]
@shane-tomlinson fantastic find!  the explanation of why this is as it is is here: https://github.com/flatiron/winston/blob/2c93353df7dd85a2b27fc3ca07e5294ff0c04097/lib/winston/transports/file.js#L165-L167

So... to get a patch that would be accepted upstream then we would need to determine whether the stream supported internal buffering.

It seems like the internal buffering in fs.WriteStream is a hell of a lot more efficient than handlers waiting for drain.  I believe the .drain game means we have a shit-ton of event handlers inovked in a tight loop writing tiny lil' bits of info.

More heavy handed, we could invoke chunking of some sort inside winston as a possible patch.

**Comment by seanmonstar** [comment]
So, benchmarking this on my machine doesn't bubble up anything noticeable to me. Or perhaps I don't know what I'm looking for.

**Comment by benmoss** [comment]
Did you ever resolve this? I am experiencing the same problem.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
