### ISSUE TITLE
[mobile]"next" button not enabled if user not authed and experimental_emailHint specified

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#4032]
STR:

1) Load up the dev RP
2) Specify an email hint
3) Open the dialog
4) If signed in, sign out.
5) Resize screen to see mobile view.
6) Why is the "next" button disabled?

MORE!

7) add one character to email address - BAM - next is enabled.

Reported originally in https://bugzilla.mozilla.org/show_bug.cgi?id=940023

**Comment by jaredhirsch** [comment]
@shane-tomlinson @andymckay @callahad I don't have full context here, but I think it's probably best to merge this diff back into 10-23 and try to lump it into our release for next week. Thoughts?

**Comment by callahad** [comment]
We believe this is resolved. Closing. :shipit:
