### ISSUE TITLE
The user should be warned that he is canceling his BrowserID account when removing the last email

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#404]
OS: All
Browser: All

STR:
1. Go to http://diresworb.org and sign in.
2. Click on the "edit" button, then remove all the email addresses listed on the page.

The "Remove svtester123@gmail.com from your BrowserID?" message is displayed for all the email addresses. When trying to remove the last email, the user should be warned that he is canceling his account.

**Comment by shane-tomlinson** [comment]
Duplicate of #394 and #252, closing.
