### ISSUE TITLE
testidp cert expiration causes automated-tests to fail

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#4042]
thanks to @jrgm who figured out that https://testidp.com cert has expired which causes automated tests to fail.

**Comment by edwindotcom** [comment]
@lloyd can you renew the cert

**Comment by lloyd** [comment]
crapsticks.  On it.

**Comment by lloyd** [comment]
certificate purchased on gandi, waiting for DNS verification details - t minus 1 hr.

**Comment by lloyd** [comment]
DNS verification in progress - t minus 6 hours.

**Comment by lloyd** [comment]
resolved.

**Comment by edwindotcom** [comment]
confirmed fixed, thanks!

**Comment by edwindotcom** [comment]
uh oh - looks like www is set but the wildcard subdomain isn't.  for example - try this url:
https://yellow-txrrw6li.testidp.org/.well-known/browserid

health-check-tests fail due to this

**Comment by callahad** [comment]
@lloyd ping? We needs the wildcard cert!

**Comment by lloyd** [comment]
DAMNIT!

**Comment by jrgm** [comment]
@lloyd Do you have that dagnum wildcard cert, dagnabbit?

**Comment by lloyd** [comment]
:sadface:, I will do this in 12 short hours.

**Comment by lloyd** [comment]
how about now!?

**Comment by jrgm** [comment]
Hmm. While this works on chrome, safari, opera, and IE, Firefox is reporting 'The certificate is not trusted because no issuer chain was provided.'

**Comment by lloyd** [comment]
which firefox version?

**Comment by jrgm** [comment]
Something changed; it works now (even looks different on ssllabs).

**Comment by lloyd** [comment]
I believe this was my error.  it seems gandi updates their intermediate certificate at some frequency, and I attached an old version of the intermediate.  Yay.  the bug that would die, has!

sorry for the fumbling.

**Comment by jrgm** [comment]
Cool. Thanks.
