### ISSUE TITLE
Implement recaptcha

### ISSUE THREAD

**Issue by glacorSoul** [mozilla/persona#4044]
I opened this issue as a request to your future implementations. Would you consider to implement [recaptcha](http://www.google.com/recaptcha) for Mozilla Persona? This would avoid attacks that try to use a dictionary of (most) used passwords to try login as a user (of course this only applies to the cases that your fallback comes to solve the login).

**Comment by fmarier** [comment]
We did discuss showing a CAPTCHA when there are too many failed password attempts in #2656 but in the end we decided to simply force a password reset when that happens.

You can see the details of it here: https://github.com/mozilla/persona/commit/a0f89c4c306e765c0c84b255a70d407ca9d79d42

**Comment by glacorSoul** [comment]
It seems that your implementation is not working properly. I attempted my log in so many times and it never requests a password reset.

**Comment by fmarier** [comment]
@brunoss the error message doesn't change, but it does lock the account down as far as I can tell.

Try typing in 11 bad passwords, then try logging into your account with the real password. You won't be able to and you'll have to click "Forgotten password".

If you're able to type a bad password lots of times and then still get in with the real password, that's a bug.

**Comment by glacorSoul** [comment]
Oh okay that's true. I was expecting to see (at least) a new message saying that I have made to many attempts. Sorry for the trouble! Still I had a lot of fun making a javascript code that tries to generate passwords and make login with it.
