### ISSUE TITLE
persona popup not opening on nightly 29.0a1 (2013-12-11)

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#4048]
STR
1. open nightly
2. surf to login.persona.org
3. click 'sign in' at top right
4. nothing happens, even if popup blocker is disabled

No errors thrown in the console, not sure what's up.

**Comment by seanmonstar** [comment]
Lies! https://cloudup.com/cYACKbwuGOi

**Comment by jaredhirsch** [comment]
wat! maybe it's Mavericks specific, can anyone else try? The click does nothing. First discovered because I can't log into etherpads :-\

**Comment by edwindotcom** [comment]
i ran into this a week ago, then upgraded and it was ok again.  does this happen on other sites with pop ups?

**Comment by jaredhirsch** [comment]
@edmoz Yeah, I can't log into Mozillians, Bugzilla, or etherpads.

I tried setting the debugger in Bugzilla, and the click is being handled. From there, the `navigator.id.request` call doesn't seem to do anything.

Looking at the console in nightly, I see that we're using the native Persona, not the shim. Is this maybe a warning sign related to the recently-landed gecko bits?

```
> navigator.id.request.toString()
"function () {
    [native code]
}"
```

**Comment by seanmonstar** [comment]
wat.

```
> navigator.id.request.toString()
"function (a){if(this!=navigator.id)throw new Error("all navigator.id calls must be made on the navigator.id object");if(!l.login)throw new Error("navigator.id.watch must be called before navigator.id.request");a=a||{},o(!1),z="request",a.returnTo||(a.returnTo=document.location.pathname);return B(a)}"
```

**Comment by jrgm** [comment]
@6a68 - do you have dom.identity.enabled set to true?

**Comment by edwindotcom** [comment]
I'm unable to repro.  6a68 is cool to close. :cactus:

**Comment by jaredhirsch** [comment]
@jrgm well done. yes, dom.identity.enabled is set to true, I forgot I was testing with the b2g simulator.

owe you a :beer: for sure :-)
