### ISSUE TITLE
missing ability to set a different email at any websites which use Persona

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#4053]
Hi,

This includes marketplace and mdn for example. 

I have an account at MDN which uses an old e-mail address (which I can access, but no longer actively check). The old e-mail is also listed with Persona so I can log in. But I find myself unable to change the e-mail. There is no interface to do so. This is a problem.
Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=835462
I would expect Persona's account manager to have a list of websites the account is attached to with a drop-down for me to set a different email for them.

This issue tracker, unlike Bugzilla, has no big fat 'search' button, so I apologize in advance for filing a duplicate.

Thank you.

**Comment by fmarier** [comment]
While I understand your frustration with the common problem of websites that don't provide an easy way to change your email address, it's not a problem we can fix in Persona itself.

Instead, we provide guidelines for sites that use Persona to let them easily provide that facility themselves: https://developer.mozilla.org/en-US/Persona/The_implementor_s_guide/Enabling_users_to_change_their_email_address

Persona itself is concerned with giving sites verified email addresses. It doesn't link email addresses together even though it looks like it from the current account manager.

So what I would suggest is that you file bugs with MDN and marketplace separately.
