### ISSUE TITLE
"Sign-in with Persona" popup Window stuck with "Mozilla" animation

### ISSUE THREAD

**Issue by ILMostro** [mozilla/persona#4056]
## What did you do?

1.visited https://developer.mozilla.org/en-US/Apps?redirectlocale=en-US&redirectslug=Apps 
2. clicked on "Sign-in with Persona" button
3. popup window opens up prompting for username/e-mail
## What happened?

"Mozilla" animation 'zooms in' and stays enlarged, blocking the view of the rest of window contents after clicking on the "Sign in with Persona" button on developer.mozilla.org
## What should have happened?

animation should've completed, resulting in "Mozilla" text 'zooming out' to its original size; allowing user to see prompt for username/e-mail and the rest of the window contents.
# Note:

I filed a [bug-report](https://bugzilla.mozilla.org/show_bug.cgi?id=948018) with Mozilla, initially; however, I was advised to file bug here, since the issue is with Persona, not the Mozilla website.

**Comment by shane-tomlinson** [comment]
@ILMostro - I just tested MDN without a problem, we need some more info to be able to reproduce.

1) What browser/OS combination are you using?
2) If Firefox, does the problem go away if you disable all extensions?
2a) If yes, have you tried disabling each one, one at a time, to see what is causing the problem? If so, can you let us know which?
3) Does the same problem occur if you are using a fresh profile?
4) Is MDN zoomed in or out?

**Comment by callahad** [comment]
Thank you for filing the bug report! Screenshots would also be really useful, if you can take some.

**Comment by ILMostro** [comment]
I'm having difficulty reproducing it now, as the "animation" seems to have changed; whereas before, the "Mozilla" letters would zoom in and (hopefully)out, now the animation is a "sideway arrow"(for lack of a better term) that displays properly.

As for my system:
-    Fedora19(64bit)
-    Firefox 26 (haven't had chance to test w/out extensions); though, adblocker _does_ cause some trouble on a few sites.  I would've liked to have had the opportunity to test that.  As of right now, I'm gonna go ahead and close this, seeing that I'm not able to reproduce the problem.  If anyone else comes across the same issue, they can use this posting as a platform.
