### ISSUE TITLE
Pressing Ctrl+C with the email field focused returns the user to a previous BrowserID Signing in dialog

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#406]
OS: Windows 7
Browser: Firefox 7.0.1, IE9, Chrome 14.0.835.202

STR:
1. Load http://beta.myfavoritebeer.org in a browser.
2. Click on the "Sign in" button.
3. Enter an email address and click on the "next" button.
4. Click in the email field and press Ctrl+C.

The dialog returns to the previous page, where the user entered the email and clicked "next". This behavior makes sense when the uses presses Ctrl+V and replaces the email address in the field or Ctrl+X and removes it, but copying the address should not produce any other behavior than the address being copied.

**Comment by shane-tomlinson** [comment]
@ioanab - great find.

**Comment by ghost** [comment]
thank you, @shane

More cases this behavior reproduces and it shouldn't:
1. The user presses Ctrl+X without having selected anything (in this case the email address is not modified so the current behavior doesn't make sense).
2. The user presses Ctrl+V without any data to be pasted (the email address is not modified in this case either).

**Comment by ghost** [comment]
Verified on Firefox 7.0.1 (Win 7).

The issue doesn't reproduce anymore when pressing Ctrl+X/V but it still reproduces when pressing Ctrl+C.

**Comment by shane-tomlinson** [comment]
@ioanab - Thanks for the verify - I'm unable to reproduce the ctrl+c problem using FF7.0.1 on Windows 7 Ultimate, which version are you running on?  Is there a particular sequence that reproduces?

**Comment by ghost** [comment]
@shane-tomlinson - I am using Windows 7 Professional with service pack1. The steps are the initial ones:

STR:
1. Load http://beta.myfavoritebeer.org in a browser.
2. Click on the "Sign in" button.
3. Enter an email address and click on the "next" button.
4. Click in the email field and press Ctrl+C.

**Comment by shane-tomlinson** [comment]
@ioanab - I am unable to reproduce this.  

@lloyd, @jbonacci, @benadida - anybody have access to Windows 7 Professional to verify this?

**Comment by ghost** [comment]
@shane-tomlinson, @jbonacci - I tried reproducing the issue from my previous comment again on Win 7 Professional and it doesn't reproduce anymore.

The whole initial issue (Ctrl+C/X/V) does reproduce on https://diresworb.org/signup though.

**Comment by shane-tomlinson** [comment]
@ioanab - are you still able to reproduce the Control +C/X/V in the signup page?  There was another bug filed - #840 that had a similar issue.

**Comment by ghost** [comment]
@shane-tomlinson - I verified this issue on Windows 7 with Firefox (9.0.1, 10.0 beta4, latest nightly), IE9, Chrome 16.0.912.75 m and Opera 11.60. It only reproduces on dialogs opened from the client in Firefox(all versions) now.

Two things I noticed different this time:
1. The issue reproduces regardless to what key the user presses together with Ctrl (e.g. Ctrl+A/B/C.../Shift).
2. When the user clicks "next" again after the issue reproduced, it doesn't reproduce again until reopening the dialog.

**Comment by shane-tomlinson** [comment]
@ioanab - I'm not seeing this problem so I think that I am not following the same steps.  Can you list the steps to reproduce?

**Comment by ghost** [comment]
@shane-tomlinson - I am using the same steps that were listed twice before in this bug:

STR:
1. Load http://beta.myfavoritebeer.org in a browser.
2. Click on the "Sign in" button.
3. Enter an email address and click on the "next" button.
4. Click in the email field and press Ctrl + any other key, except Enter.

**Comment by shane-tomlinson** [comment]
@jbonacci, @lloyd, @jrgm - can anybody reproduce this?  I'm so far unable to which leads me to believe something else is going on here.

**Comment by ghost** [comment]
@jbonacci - no, Sticky Keys were not enabled when reproducing this issue. What I did notice though, is that this issue is intermittent. With the same steps (start OS, launch browser + steps from my previous comment) I managed to reproduce it tens of times in a row but then it stopped reproducing when opening the browser for the N-th time.

**Comment by shane-tomlinson** [comment]
@ioanab, @jbonacci - I am still unable to reproduce this in either a VM or a laptop with native Win7.

**Comment by ghost** [comment]
I tried to reproduce this issue again on Windows XP with Chrome 17.0.963.56 m and Firefox 11.0 (beta3). It reproduced all the time when I used the mouse to enter the email address for signing in (mouse or mouse+keyboard), but it never reproduced when using only the keyboard to enter it.

STR:
1. Load http://beta.myfavoritebeer.org in a browser.
2. Click on the "Sign in" button.

CASE 1 - the issue reproduces:
3. Start entering an email address you entered before.
4. Use the mouse to select an email address from the auto-complete list.
5. Click on the "next" button.
6. Click in the email field and press Ctrl + any other key.

CASE 2 - the issue reproduces:
3. Without entering anything from the keyboard, click on the email textbox.
4. Use the mouse to select an email address from the auto-complete list.
5. Click on the "next" button.
6. Click in the email field and press Ctrl + any other key.

CASE 3 - the issue doesn't reproduce:
3. Start entering an email address you entered before.
4. Use the Down and Enter keys to select an email address from the auto-complete list.
5. Click on the "next" button.
6. Click in the email field and press Ctrl + any other key.

CASE 4 - the issue doesn't reproduce:
3. Enter an email address in the textbox (ignore the auto-complete).
4. Click on the "next" button.
5. Click in the email field and press Ctrl + any other key.

**Comment by shane-tomlinson** [comment]
@ioanab, @jbonacci - I can reproduce this now!  Thanks for the detailed instructions ioana.

**Comment by jrgm** [comment]
verified train-2012.08.17
