### ISSUE TITLE
logging into RP on stage logs out immediately after

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#4067]
Goldilocks came home, breaking everything. You big jerk.

Problem:
`if (!observers.onlogout) rp_api = 'stateless';`

It's supposed to be `logout`, without the `on`, and so all requests converted to goldilocks, and so everyone's onlogout() was being called. Blocks train-2013.10.23 deployment: https://bugzilla.mozilla.org/show_bug.cgi?id=958719

**Comment by jaredhirsch** [comment]
I can't repro on stage, and it looks like a fix was merged months ago. Closing.
