### ISSUE TITLE
Account manager styling broken on Safari

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#4077]
1. Go to http://123done.org/
2. Sign in with `<whatever>@mockmyid.com`
3. Open a new tab, go to https://login.persona.org

Observe the broken CSS:

![screen shot 2014-01-22 at 17 08 34](https://f.cloud.github.com/assets/24193/1980068/6e775826-83ba-11e3-90b7-289f50482b2f.png)

Resizing the window even slightly causes a re-flow and everything looks great:

![screen shot 2014-01-22 at 17 11 14](https://f.cloud.github.com/assets/24193/1980076/80563922-83ba-11e3-8d80-d8f14e46f443.png)

**Comment by seanmonstar** [comment]
This only started today? Or could it be a bug in a recent Safari update?

**Comment by jaredhirsch** [comment]
Hmm. I cannot repro.

Safari Version 7.0.1 (9537.73.11)
Mac: Version 10.9.1 / Build 13B42
(click the OS version number in About This Mac to see the build number)

Note that we've had problems with page layout in Safari private mode long ago, eg #3219 (wontfixed) and #3929 (lingering, open, two star). Maybe this is a clue to why layout looks funny now for some people under some circumstances.

**Comment by callahad** [comment]
Strange, I can reliably repro with identical builds of Safari and OS X.

As long as I have an active Persona session, regardless of tabs are open, all I have to do is:

Cmd-T, login.persona.org, Return.

Sometimes it's less bad than others:

![screen shot 2014-01-23 at 8 01 56](https://f.cloud.github.com/assets/24193/1985000/0a031f6a-8437-11e3-9880-120c10f97250.png)

**Comment by callahad** [comment]
(Triaging as 1-star. It's purely cosmetic, the account manager is rarely used, and Francois is actively working to further reduce its use.)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
