### ISSUE TITLE
Move the server-side email associations to the client

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#4079]
Currently the Persona shim and fallback IdP are integrated in several ways. One of these is the fact that the shim is storing email associations server-side instead of in local storage.

There are a few reasons to get rid of these associations and go to a "one email per account" model:
1. native implementation in Firefox shouldn't have to ping the server to get a list of emails, it should be stored locally
2. users who share browsers end up creating accounts with other people's email addresses: https://groups.google.com/d/topic/mozilla.dev.identity/Wm0Cd-rjczc/discussion
3. having accounts with many emails (which can be primary or secondary) increases code complexity and has caused security bugs in the past

Here's a breakdown of what needs to happen:
- [ ] "add an email" is removed from the UI and the API (but existing multi-email accounts continue to work)
- [ ] the session cookie with the fallback IdP needs to keep track of the login email
- [ ] listing the emails from an account should only return the login email
- [ ] the fallback IdP sessions need to support being authenticated against multiple accounts?
- [ ] a client-side (local storage-based) email picker needs to be written
- [ ] primary emails should be removed from the database
- [ ] accounts with multiple email addresses should be split somehow

**Comment by fmarier** [comment]
I've started working on the first item from this branch: https://github.com/fmarier/browserid/tree/no_accounts

**Comment by husayt** [comment]
Thanks for dealing with this. I will just say this is so critical, that puts our entire business in risk. We are working on getting an alternative to persona, in case if that becomes necessary. But I hope it doesn't get to that, you guys have done amazing work with Persona and we love using it.

**Comment by callahad** [comment]
(Triaging as 4-star)

**Comment by jcea** [comment]
I think that implementing issue #4099 would be easier and the way to go.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
