### ISSUE TITLE
global logout

### ISSUE THREAD

**Issue by husayt** [mozilla/persona#4080]
What would be very useful is to have a way to do global logout. our users keep asking for this, when they are using our system from shared pc. otherwise they have to log out from our system and then go to persona website to log out from there too.

https://groups.google.com/d/topic/mozilla.dev.identity/x7YdVKpCCVs/discussion

**Comment by fmarier** [comment]
Also mentioned on https://github.com/mozilla/persona-roadmap/issues/45

**Comment by fmarier** [comment]
The hard thing about this feature is the way it would work with primary identity providers. We could easily provide a logout API for the fallback IdP, but it would be incomplete.

**Comment by husayt** [comment]
You see, that would be fine. Our users who have gmail accounts don't have the problem above. They still have to use their gmail passwords to login.

**Comment by callahad** [comment]
Closing in favor of the roadmap entry -- @husayt Thank you for the report + suggestion. We don't have an estimated timeline to addressing the issue -- it's likely that any change we make would confuse people in a different way. :) I'm not sure what the right trade-off is. Further limiting the duration of public sessions might be a good place to start...
