### ISSUE TITLE
Internal Server Error when hitting /sign_in

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#4082]
This is intermittent.

![screen shot 2014-01-28 at 10 47 57](https://f.cloud.github.com/assets/848085/2018414/2d25b306-880e-11e3-9bc8-c703fa046179.png)

![screen shot 2014-01-28 at 10 49 46](https://f.cloud.github.com/assets/848085/2018416/2f4d1b06-880e-11e3-88bb-054771af5e1a.png)

**Comment by callahad** [comment]
Resolved by gene. Update on http://personastatus.org/. TL;DR: Same log rotation problem; same failure of our monitoring and alerting platform.
