### ISSUE TITLE
We need to finish Goldilocks

### ISSUE THREAD

**Issue by djc** [mozilla/persona#4086]
Per @callahad:

Goldilocks solves urgent end-user pain points and paves the way for a dramatic reduction in server-side state.

**Comment by callahad** [comment]
(It's effectively done, but we don't have a tracking bug, and we haven't branched a train with it.)

**Comment by zimbatm** [comment]
![goldilocks_and_the_three_bears](https://f.cloud.github.com/assets/3248/2158835/ecc375da-9499-11e3-9fa8-ea888eadf631.jpg)

**Comment by jaredhirsch** [comment]
I'm inclined to close this bug, I think it's really saying, "we need to figure out how to do releases in the new era."

Reopen if I'm wrong :-)

**Comment by callahad** [comment]
I like having this open as a tracking bug that we can point people to. Suggest reopening.

**Comment by jaredhirsch** [comment]
Sounds great :beers:

**Comment by callahad** [comment]
:beers:
