### ISSUE TITLE
Forced use of gmail authentication requires a break in the privacy wall for all users with gmail.com addresses

### ISSUE THREAD

**Issue by makyen** [mozilla/persona#4087]
One of the key points of Persona is privacy. The current required use of gmail authentication breaks that privacy wall by forcing the user to authenticate with Google. Having Persona integrated with gmail is probably something that is desired by many, probably most, users. However, it should be offered to the user as an option, not as a requirement. All email addresses should, by default, be treated with the simple send email/verify receipt method of authentication. Using gmail authentication should be an _option_ for users with the user being informed that using such authentication provides Google with some information on their activity (the authentication and/or required logout of non-associated gmail identities). Beyond the use of gmail authentication for the first use of an gmail.com email account with Persona, forcing the use of gmail authentication _every_ time the Persona is logged in results in a considerably lower standard of privacy for users of gmail.com accounts.

As it currently stands signing in to Persona using a gmail.com email account, or at least adding a gmail.com email account _requires_ using gmail account authentication. This results in Google being informed of the activity every single time. Doing so is contrary to the concept that Persona enables privacy by not informing any other entity, other than Persona, about the user's activity. Using such integration should not be required of the user.

In addition to the reduction in privacy, this is very inconvenient at times when a user is in a situation where there are multiple gmail accounts which they specifically do not desire to have linked. Each time logging in to Persona requires that a user log out of any alternate, non-linked, gmail account and to log into the one which is associated with a particular Persona account. There are times when a user wants to keep gmail accounts completely separate, not informing even Google that the accounts are owned by one single person/entity. In such cases, the user has chosen not to associate the gmail accounts with each other. Forced use of gmail authentication results in  

Basically, _forcing_ the use of gmail integration results in a break in the privacy wall which Persona is supposed to be enforcing. While gmail integration is probably desired by many/most users, it currently _requires_ a reduction in privacy for anyone using a gmail account. Using gmail authentication should be a non-default option which requires specific confirmation from the user as it informs a third party of Persona activity. One of the goals of Personal is privacy. It should not _force_ a reduction in privacy for users to have a email account from a particular domain associated with their Persona account. 

At an absolute minimum, the user should have the option to disable the use of gmail authentication and use basic email sent/verify receipt authentication. However, even having the use of gmail authentication as the default is contrary to the privacy philosophy behind Persona. It, or anything like it, should only be used upon the end-users explicit request (e.g. a checkbox).

**Comment by seanmonstar** [comment]
Thanks for your concern and explaining it out to us!

> This results in Google being informed of the activity every single time. Doing so is contrary to the concept that Persona enables privacy by not informing any other entity, other than Persona, about the user's activity.

Actually, Gmail is informed of your sign in action _to_ Persona, but never told where Persona will be sending an assertion, and so won't ever know which site you're really signing in to. Plus, authenticating with Gmail is only needed every so often, to create a certificate that is used to sign assertions for individual sites. If you login to multiple sites in a short period of time, we can generate an assertion for each site, only having authenticated to Gmail once and re-using the certificate until it expires.

> At an absolute minimum, the user should have the option to disable the use of gmail authentication and use basic email sent/verify receipt authentication. However, even having the use of gmail authentication as the default is contrary to the privacy philosophy behind Persona. It, or anything like it, should only be used upon the end-users explicit request (e.g. a checkbox).

We cannot do that. Persona offers sending an email to do verification if the domain provider does not support Persona. When it does (like Gmail does through our bridge), it would be a security violation for Persona to assert a Gmail identity without Gmail's consent. This is how the Verified Email Protocol works. Each provider generates a certificate for a user, and then browser (Persona for browsers without native support) uses that certificate to sign in elsewhere.

**Comment by callahad** [comment]
This is one of the most thorough issue reports I have ever seen. _Thank you._

> this is very inconvenient at times when a user is in a situation where there are multiple gmail accounts which they specifically do not desire to have linked. Each time logging in to Persona requires that a user log out of any alternate, non-linked, gmail account and to log into the one which is associated with a particular Persona account.

This will be partially addressed by switching the Gmail bridge to OAuth, which lets us pre-fill the desired address. https://github.com/mozilla/persona-gmail-bridge/pull/114

> There are times when a user wants to keep gmail accounts completely separate, not informing even Google that the accounts are owned by one single person/entity.

I believe this is best addressed outside of Persona by using multiple browser profiles. Anything less is certain to leave cookies and other state that can be correlated.

I'm going to suggest closing this as wontfix. As Sean explained above, the Persona/Gmail bridge acts as an anonymizing layer, so Google learns nothing of where you go on the web. At most, Google can learn that you are using Persona, but a confirmation email leaks similar information.

**Comment by makyen** [comment]
From what I have been able to determine in a brief investigation, the issue is that the authentication requests come from the IP address of the user's computer whereas an email sent/verify is not associated with the user's initiating IP address. This leaks much more information than just the standard email send/verify process.  In that process, email is sent once from persona.org and is not associated with the user's IP address at all. All that can be collected is that the user has, once, requested the authentication of email address ownership by Persona.

As currently set up (as I understand it), Persona, from the user's machine, authenticates with Google both at the time the email address is added to the Persona account, and every time the user logs into the Persona account. This associates the IP address of the user's computer with the Persona authentication _every_ _single_ _time_ that the authorization occurs. This is vastly more information than the email send/verify. It permits Google, or other authenticator, to track the usage of Persona by a specific identity, and to have any such tracking regularly associated with each IP address used by the end user without giving the user the option to have this not happen.

Even if different browser profiles are used, this still provides the IP address of the user's machine. In many situations this allows the potential for a tracker to assign a high probability to the correlation of multiple accounts.

While I have not looked at it, I also wonder if this punches a hole through any attempt at using a private browsing mode.

I would not have as big a problem with this if the authentication was not done every single time one logs into Persona. If the user was able to just enter their separate Persona password instead of authenticating with Google (or some other authenticator) then this would not be such a significant issue. [NOTE: I have not actually verified that Persona does this authentication each time, or how often it does.  I am basing this on comments I have seen made by others].

The point is that in an effort to make the user's life a bit easier (automatic authentication with Google without the need to enter a separate password into Persona), Persona has chosen to _force_ users to significantly reduce the privacy that is available through the use of an email account from provider's that do not have such authentication.  This would be OK, if the user was A) informed that this was happening, and B) had the option of not leaking such information by verifying the email once through the same process that is used for email accounts from domains that to not have an authenticator.

Persona is touted as being about privacy. This is a situation where Persona has _forced_ the user to give up some level of privacy, compared to other users, merely based on the fact that the user has an email address in a specific domain.

**Comment by callahad** [comment]
> This leaks much more information than just the standard email send/verify process.

I disagree. The confirmation email refers to the site that the user is trying to log into, which is a far more sensitive datum, and which is unavoidable for mass-market usability. Plus, your email provider can still log your IP when you retrieve that message.

> Persona, from the user's machine, authenticates with Google both at the time the email address is added to the Persona account, and every time the user logs into the Persona account.

Actually, the user only re-auths with Google once every few hours, regardless of the number of login attempts during that interval. :)

> If the user was able to just enter their separate Persona password instead of authenticating with Google (or some other authenticator) then this would not be such a significant issue.

True, but a system like that requires centralization. Decentralization is a foundational aspect of Persona, and we're unwilling to change that. Note that any decentralized system will require some degree of phoning home. Persona is designed to limit the frequency and content of those contacts.

With all due respect, making these changes would violate Persona's principles of decentralization, and require would deep, invasive changes to the current architecture.

Thank you (sincerely) for advocating for user privacy and taking the time to engage here. We believe Persona offers better security and privacy than any other common authentication system, barring traditional username/password forms when used in strict accordance with best practices. Unfortunately, providing a centralized username/password system violates decentralization, so it is not a viable option for Persona. Closing as wontfix.
