### ISSUE TITLE
The diresworb.org "remove" buttons are clipped on the right side on Android phones

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#409]
Device: Motorola Droid2
Android versions: 2.3.3
Browser: Firefox 7.0.1

STR:
1. Load https://diresworb.org in Firefox and sign in.
2. Click on the "edit" button.

The "remove" buttons are clipped in the right side: the last "e" from "remove" is missing together with the button margin.

**Comment by shane-tomlinson** [comment]
this affects iOS as well.
