### ISSUE TITLE
Use Gravatar on login.persona.org

### ISSUE THREAD

**Issue by PanderMusubi** [mozilla/persona#4096]
Please use Gravatar on http://login.persona.org to quickly identify with which account you are logged in.

**Comment by seanmonstar** [comment]
Considering #1589 says we won't focus on name/photo, I'm thinking this won't happen either.

Hopes are that experimentation in [FxA attached profiles](https://github.com/mozilla/fxa-profile-server) maybe deliver better ideas here.

**Comment by PanderMusubi** [comment]
Well, retrieving a Gravatar can be done from the front-end, in the browser. This does not concern the back-end in any way. Please see https://en.gravatar.com/site/implement/ and reconsider this request. I will help users to visually see that they have been logged in with their proper account.

**Comment by callahad** [comment]
Hi @PanderMusubi -- thank you for the suggestion. I like the idea of adding profile images to the account picker as a visual aid. I've added it to the backlog of feature ideas at https://github.com/mozilla/persona-roadmap/issues/71

I'd be happy to review a pull request implementing this.

**Comment by PanderMusubi** [comment]
Thanks. (Un)fortunately I am not a JavaScript developer so I will leave it to someone else.
