### ISSUE TITLE
Remove account system

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#4099]
Various discussions on the list have suggested we remove the password from Persona. That our usage of password contradicts our message of "killing the password".

Instead, we should send an email verification each time someone wants to use an email address, and then store the verification in "session" or localStorage for a month (if they click the "I trust this computer" option). If an email address is backed by a primary, then they can likely offer a better experience.

The work in #4079 will help, but this issue takes it a step further and essentially drops the password column from our database. (If we were really clever with verification codes and use of client-sessions, could we even completely remove the need for a db?).

_(I searched and searched, and couldn't find a previous issue for this. Excuse if it's a dupe somewhere.)_

**Comment by jcea** [comment]
I guess the localStorage data should be digitally signed by Persona server. How is that private key protected?. Maybe refreshing key pair frequently (each 15 minutes), delete old secret keys and keep only the public keys list of last month?.

Storing a token in the client (lets say 256 random bits), referring to an email in the server should be simple enough. The server just expires those tokens locally after a month.

Think too about people having several Persona identities in the same browser. Browser should send all tokens it has, and let users to choose.

**Comment by jamesshore** [comment]
This sounds like a terrible user experience! Who is going to want to revalidate their email every time they delete cookies, or every month? Especially when you consider that the email often won't come through for several minutes, or the user might want to use a work machine that doesn't have access to personal email (or vice versa). What a terrible disruption for someone who just wants to log in and get something done. Please don't do it. :-1:

**Comment by djc** [comment]
"Removing the account system" should IMO be separate from "email verification only".

**Comment by wrr** [comment]
Another approach to consider is to keep Persona password, but remove an option to associate multiple email addresses with a single Persona account. From the mailing list threads it seems like this option is often a source of confusion and can lead to problems when unrelated accounts of different users are accidentally merged.

**Comment by seanmonstar** [comment]
@djc what good is an "account" if you have to verify it every time you want to use it?

@wrr that's the premise of #4079 

@jamesshore with yahoo and gmail, the majority of users don't use this password anyways. Plus, we get messages all the time that having a password for Persona sucks. Do you have an alternative?

**Comment by luckyrat** [comment]
Why not make the password optional? Default to email verification but include an option in the email to associate a password with the account.

**Comment by jamesshore** [comment]
@seanmonstar On my site, 39.8% of subscribers do not have a Google or Yahoo account. That's a huge percentage to inconvenience. (Yahoo: 2.5%; Gmail: 57.8%.)

Just because you're getting complaints about the current situation doesn't mean this is better.

**Comment by jcea** [comment]
Maybe send a verification email if last verification is a month old, but allow the email to stay valid for, lets say, seven days even if the user doesn't click the link.

**Comment by jaredhirsch** [comment]
This is a cool idea. I'd love to see a prototype and maybe we can take the discussion to the list?

**Comment by FindYourCloud** [comment]
Please don't remove passwords. We use it, very effective. Check out www.findyourcloud.com to see what I mean. Users like it. Your not removing the password anymore than cloud removes the data center; you're abstracting the password. There's always a password at the end of the day, making it easy to use is what I thought Persona was all about.

**Comment by callahad** [comment]
We hear you.

Within the Persona team, we believe that the fallback account system is doing more harm than good, but we're not going to remove something so fundamental unless we can demonstrate that doing so is the right thing for usability.

Stay tuned to the [mailing list](https://lists.mozilla.org/listinfo/dev-identity) for more discussion. :)

**Comment by jaredhirsch** [comment]
@seanmonstar we've got the backlog released. any interest in prototyping this/submitting a PR?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
