### ISSUE TITLE
Clickable link area is way too wide for "Forgot your password?" link, on mobile-friendly Persona UI

### ISSUE THREAD

**Issue by dholbert** [mozilla/persona#4102]
(originally filed as a [bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=978586) )

STEPS TO REPRODUCE:
1. [Prerequisite -- if you're already logged in to Persona, log out: visit https://login.persona.org/ , click "Sign In", and then "This is not me"]
2. Visit https://login.persona.org/ (or any site that uses persona for login
3. Type in the email address for your Persona account.
4. In the password prompt, resize the window so it's skinnier (approximately phone-width), to trigger the Mobile UI.
5. Hover over (or click) the area far to the right of the "Forgot your password?" link.

ACTUAL RESULTS: The area is linked -- the clickable link-area covers **an entire horizontal strip of the page** including **all the blank space to the right of "Forgot your password"**.

EXPECTED RESULTS: Only the text should be linkified. (or if a larger hit target is desired, it should be made clearer what the bounds of that hit-target is)

This bug means if you accidentally tap the wrong chunk of empty space on a mobile device (as I did just now, to dismiss the keyboard after I typed in my password), then you'll unintentionally invoke the "Forgot your password" link, which takes you to a different page. [and when you go back, anything you typed in the password field will have been cleared, so you have to type it all over again]

![screenshot](https://f.cloud.github.com/assets/426803/2318520/922d4ce8-a369-11e3-8eff-a87637c4c13b.png)

**Comment by dholbert** [comment]
The problem is that the `<a>` element...

```
<a class="isMobile forgotPassword" href="#"></a>
```

has "display:block", because https://static.login.persona.org/v/4ad6e4debb/production/en/dialog.css has this style rule (inside of the mobile-detection media query):

```
.isMobile,.returning .isReturning,.start .isStart,.addressInfo .isAddressInfo{display:block}
```

This is a problem because a `display:block` element (with default `width:auto`) will expand to the width of its container, which in this case is the width of the whole page. So the `<a>` element gets the width of the page, and that whole area is clickable / tappable.

This `<a>` should be `display:inline`. If I make that change with devtools, it fixes the linkable region to be the correct size, without affecting the rendering of the page.

**Comment by jaredhirsch** [comment]
@dholbert pull requests welcome :-)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
