### ISSUE TITLE
The background of the email removing confirmation pop-up message doesn't match the rest of the client

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#411]
Phone: Motorola Droid2; Android version: 2.3.3; browser: Firefox 7.0.1
Tablet: Acer A500; Android version; 3.2; browser: stock

STR:
1. Load https://diresworb.org/ in the browser and sign in.
2. Click on the "edit" button.
3. Click on the "remove" button displayed next to an email address.
4. Observe the displayed confirmation pop-up.

The background of the confirmation pop-up message is black while on desktop is light gray. The buttons bar at the bottom of the  pop-up has the right background.

**Comment by shane-tomlinson** [comment]
@ioanab - we are using the browser native "confirm", which causes this.

**Comment by shane-tomlinson** [comment]
do we want to change the behavior of these confirmations so that we use some home grown solution or should we keep the browser native confirm dialogs?

**Comment by shane-tomlinson** [comment]
Closing this as we are using the browser native confirm dialog.
