### ISSUE TITLE
Update the "meet the identity team" wiki page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#4112]
https://wiki.mozilla.org/Identity#Meet_the_Identity_Team

A few names that may need to be added/removed.
I don't see an "Edit" button, so not sure if I have permissions to change that page.

**Comment by jaredhirsch** [comment]
Good idea, doesn't belong in the Persona repo. :beers:

**Comment by pdehaan** [comment]
![and like that, it is gone](http://31.media.tumblr.com/tumblr_lioxkid0Kv1qhd0uho1_500.gif)

**Comment by callahad** [comment]
@pdehaan If you log into WikiMo, you should see an edit button.
