### ISSUE TITLE
privacy page shows old MV address

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#4118]
### Steps to reproduce:
1. Search this repo for "Castro"; https://github.com/mozilla/persona/search?q=castro&ref=cmdform
### Actual results:

Three results:
1. [resources/views/pl/privacy.ejs:300](https://github.com/mozilla/persona/blob/dev/resources/views/pl/privacy.ejs#L300)
2. [resources/views/en/privacy.ejs:91](https://github.com/mozilla/persona/blob/dev/resources/views/en/privacy.ejs#L91)
3. [resources/views/es/privacy.ejs:187](https://github.com/mozilla/persona/blob/dev/resources/views/es/privacy.ejs#L187)
### Expected results:

0 results. We should probably update to the new MV address on Evelyn or the SF address.

**Comment by callahad** [comment]
FWIW, according to http://www.mozilla.org/en-US/contact/spaces/mountain-view/, the new MV address is:

331 E. Evelyn Avenue
Mountain View, CA 94041
USA

Adding the "Good First Bug" tag.

**Comment by yesyayen** [comment]
I have modified the old MV to new MV and created a pull request. #4122 
Please verify and merge.

**Comment by jaredhirsch** [comment]
Looks like the PR has been merged. Closing.
