### ISSUE TITLE
perf issues in dialog

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#4126]
The dialog is super sluggish right now on production.

I suspect this is due to the additional logging we're doing, but we need to sit down and take some measurements.

Given the current state of things, definitely not the top priority - but it does suck and should be addressed at some point.

**Comment by Lennie** [comment]
Just wondering: if it's slow, do you write to disk or console ? Have you considered doing statsd-style statistics or logging over UDP like syslog does ?

**Comment by jaredhirsch** [comment]
@Lennie - It's too early to start digging into any particular optimization; we really need to start by doing some performance analysis on the client-side. Good questions though ^_^

**Comment by jaredhirsch** [comment]
apparently this slowness (roughly 5-7 seconds between email and password, and password to "<email> verified!" screens) is just my local network, jrgm cannot repro. Closing.
