### ISSUE TITLE
There should be a "Home" button/link that would allow the user to return from Privacy/TOS to the Account Manager page

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#413]
OS: All
Browser: All

STR:
1. Load https://diresworb.org/ in the browser and sign in.
2. Click on the "Privacy" (or "TOS") link at the bottom of the page.

The user can only return to the Account Manager by deleting the "privacy" string from the URL. There should be a "Home" button/link that would allow the user to return to the Account Manager page.

**Comment by shane-tomlinson** [comment]
The "BrowserID" button at the top does this, but I see the value in this.  Could use use the page's Referrer header to determine whether the user came from the main page and give a back button accordingly?  I know the Referrer header is frequently stripped, but it is one way of remembering. A potential problem is how we would handle Main->TOS->Privacy, at which point we would have to keep multiple levels, at which point it seems easiest to let the browser's history handle this.

**Comment by shane-tomlinson** [comment]
@jbonacci - there should not be any difference whether the user is logged in or not.

**Comment by shane-tomlinson** [comment]
Reference issue #380

**Comment by ghost** [comment]
@jbonacci, @shane-tomlinson - the "BrowserID" button is all grayed out so the user might not think it's actually a button, but suppose from the start it's just an image (as I did at first). In this case, when the user is signed out, the Sign in link gets him on the Home page. When the user is signed in, the Sign in link becomes "Sign out" so the user may not see any obvious ways to get back to the Home page.

Still, the behavior is in fact the same. In this case, I think the BrowserID button should be somehow enhanced so the users would notice it much easier.

**Comment by lloyd** [comment]
bryan, can you suggest how we can make it more obvious the the BrowserID logo at the top will take you back?  or should we add a back link?

**Comment by skinny97214** [comment]
We can add a small "home" under the logo on hover a la amazon.

**Comment by shane-tomlinson** [comment]
@skinny97214 - Any plans on this or can we shut this down?

**Comment by skinny97214** [comment]
The redesign made the Persona logo much more prominent. Closing as fixed.
