### ISSUE TITLE
Persona is blocked by the Privacy Badger extension

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#4130]
If you install the EFF's latest privacy add-on, [Privacy Badger](https://www.eff.org/privacybadger) then it break Persona completely:

![persona-troubleshoot](https://cloud.githubusercontent.com/assets/167821/2983049/2589d862-dc1d-11e3-8f55-81c337b71b91.png)

Also filed upstream at https://github.com/EFForg/privacybadgerfirefox/issues/98 and fixed in pull request #4129.

**Comment by jaredhirsch** [comment]
#4129 has been merged, closing. Please reopen if this isn't fixed post-deploy.
