### ISSUE TITLE
Mistakenly forcing RPs to stateless ("Goldilocks") API instead of normal Observer

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#4131]
We tried to deploy 90e48d0, but had to roll back due to issues with Goldilocks.

Sites like https://voo.st, https://mozillians.org, and https://air.mozilla.org would accept a login, then immediately log the user back out.

http://123done.org does _not_ exhibit this issue.

There's evidence that we were treating them as using the stateless ("Goldilocks") API before logging in: I still had a few tabs open that had initially loaded with 90e48d0 as login.persona.org. When I called .request() in one of those, after rolling back, the popup reported: "improper usage of API: Error: invalid value for rp_api: stateless"

Hypothesis: We're incorrectly identifying sites as using the stateless API.

**Mechanism of action:**

Page load / login works normally, but because we think the RP wants to be stateless, we clear the email -> RP association (from which `loggedInUser` is derived) right before login finishes and we send the assertion.

When the RP page reloads after login, we (correctly) treat it as classic Observer and check what the site says `loggedInUser` should be (`foo@example.com`) against our local email -> RP association (`undefined`).

Persona then triggers `onlogout` to rectify the mismatch between the RP and its own belief.

**Comment by gene1wood** [comment]
Will there be a way to test for this in stage (as opposed to prod)?

**Comment by callahad** [comment]
Bug is here: https://github.com/mozilla/persona/blob/90e48d00cd58712a37857e1304cb3f7a0278612f/resources/static/include_js/_include.js#L345

We're testing for the presence of `observers.onlogout` instead of `observers.logout`. I could've sworn we fixed this before. Maybe on a branch that got lost.

**Comment by callahad** [comment]
I believe this is fixed in https://github.com/mozilla/persona/commit/583d13595ed037493b1179459c3c43110ed153c2, which is included in `train-2014.05.23`.

**Comment by gene1wood** [comment]
@callahad is there a way to reproduce this bug in the current stage (which has the old code) so that we can validate that this fixes the bug once we update stage?

**Comment by callahad** [comment]
Any Persona RP that does not register an `onready` handler will trigger
this issue.

I can whip up a jsfiddle when I get home if you'd like, but I have
experimentally verified this fix by using the Firefox debugger and stepping
through `getRPAPI` on 123done, Air Mozilla, and Mozillians.
