### ISSUE TITLE
Users cannot sign in to Persona

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#4147]
Reported in [bug 1024385](https://bugzilla.mozilla.org/show_bug.cgi?id=1024385) by Al Tsal (:atsal):

As a user, I cannot login Persona from Flame (Firefox OS). Worse than that, we cannot login from B2G desktop build as well, and it blocks automation testing.

STR:
1. Visit a website with Persona login, click on persona login button
2. Type valid e-mail and tap on "Continue"
3. Tap on "Sign in"

**Expected Result**:

*. user can login by persona and logout

**Actual Result**:

On B2G desktop, user stuck at step 2 and see "checking with your e-mail provider" and never got response.

On real device (Flame), user stuck at step 3 and see a loading bar running infinitely

**Comment by jedp** [comment]
I cannot reproduce this on desktop.

I can sign in on desktop with both a primary email (my @mozilla.com address) and a secondary email (one generated by personatestuser.org)

On device, sign-in works perfectly for me with a secondary email address (my persona email domain), including creating a new password.

However, on device, it is a [known issue](https://github.com/mozilla/persona/issues/4144) that sign-in with a primary email address (such as mozilla.com, gmail.com, yahoo.com, eyedee.me), fails.

Al, can you give more information?  What email domain were you using?  Same on desktop and device?

Thanks
j

**Comment by zacc** [comment]
@jedp, the test case we were using was for a user from:
http://personatestuser.org/email/

**Comment by edwindotcom** [comment]
this looks the very much related to https://github.com/mozilla/persona/issues/4144

**Comment by jaredhirsch** [comment]
personatestuser accounts are not primary accounts. If it's a valid issue, it's likely something besides #4144

**Comment by jaredhirsch** [comment]
@zacc are you still having problems getting personatestuser.org to work?

**Comment by callahad** [comment]
Closing, please comment if this is still an issue.
