### ISSUE TITLE
Primary support broken in my firefox profile (no addons)

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#4152]
When trying to log into AirMo for example using my `mozilla.com` email, I get the following:

![error_without_addons](https://cloud.githubusercontent.com/assets/167821/3296188/51d4faa6-f5d5-11e3-9122-1a583904aad7.png)

I do have cookies and third-party cookies enabled and I don't have any addons, I restarted in safe-mode.

In a new profile, it works fine. Diffing the `prefs.js` for these two profiles didn't really highlight anything dodgy.

**Comment by fmarier** [comment]
Even weirder: overwriting my `prefs.js` with the one from a new profile that works doesn't help.

It's not addons, it's not prefs, wtf!?

**Comment by fmarier** [comment]
I finally found the culprit while "bisecting" the contents of my profile: `permissions.sqlite`.

This pointed in the direction of the "cookie exceptions" settings:

![cookie_exceptions](https://cloud.githubusercontent.com/assets/167821/3298195/68261712-f5fe-11e3-9012-a985b43defaf.png)

while provided the solution: deleting the `login.mozilla.org` entry.

No idea how it got there, I don't even know how to add it back without using the sqlite3 client!

**Comment by ozten** [comment]
Ugh, nice find!
