### ISSUE TITLE
username field is not showing when i try to sign up

### ISSUE THREAD

**Issue by silviudon** [mozilla/persona#4155]
hi
i try to create an account on developer.mozilla.org/ but username field is not showing after login with persona.. 

![username](https://cloud.githubusercontent.com/assets/6437135/3366153/044df82c-fb3f-11e3-919f-dd43311fd0b2.jpg)

**Comment by jaredhirsch** [comment]
The screenshot shows that you have logged in with Persona, and need to pick a public MDN username and click the 'create a new profile' button to complete signup. I think you are doing just fine ^_^

If you continue to have problems with the MDN signup flow, you can ask for help in #mdn or #introduction on Mozilla IRC, or file a bug against [the mdn project on github](https://github.com/mozilla/kuma).

Good luck!
