### ISSUE TITLE
No confirmation on creating Persona account or warning message for deleting Persona account

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#4160]
1.Go to https://login.persona.org/ to create a persona account 
2. Click on the sign in button appears on the right hand corner of the page
3. Enter your email address and click next button, enter all login credentials to get verified
4. Wait for verification on the screen
5. Check your mail box for email from persona.  
1. Sign in to your persona account
2. Go to your Account Manager and cancel the account
3. Confirm it and check your mail box for confirmation mail.

**Comment by jaredhirsch** [comment]
Thanks for filing this bug. You've listed some steps here, but you don't explain what happened vs what you expected to happen. Would you mind adding a bit more information?

**Comment by jaredhirsch** [comment]
Haven't heard anything, closing. Feel free to reopen if you can add additional information.
