### ISSUE TITLE
Cannot log in because login form is missing in Persona popup window

### ISSUE THREAD

**Issue by cvan** [mozilla/persona#4162]
I'm using Chrome. I had logged in with Persona many times to the Marketplace in this same browser profile (and browser session).

For some the login form is missing!

![](http://i.imgur.com/ZqAJSZq.png)

And the template looks like it didn't even get rendered:

![](http://i.imgur.com/6iOiore.png)

Not sure if it's related and it's probably not, but I had just signed in to FxA on a different origin (https://marketplace-altdev.allizom.org/). And this issue started right after that.

I tried reproducing (with and without doing a FxA login in the same browser profile) in Firefox and Chrome private browsing, but I was unable to reproduce.

**Comment by jaredhirsch** [comment]
Thanks for the bug report. If you are still able to repro this, please visit [this page](https://people.mozilla.org/~fmarier/troubleshoot.html) and add a comment with a screenshot, so we can start to debug.

It would be helpful to see any errors in the JS console, if you're still able to repro.

**Comment by cvan** [comment]
I can't reproduce anymore. Will do; thanks.

**Comment by jaredhirsch** [comment]
Closing. Reopen or file a new bug if you can repro.
