### ISSUE TITLE
create a new train with the broken primaries fix

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#4164]
We have merged the fix for #4144, so we should cut a new train and let QA bang on it a bit.

As a reminder, we have [documentation](https://github.com/mozilla/persona/wiki/How-to-Branch-The-Trains) for this process.

If somebody doesn't grab this ticket and beat me to it, I will cut a release branch tonight/tomorrow/this weekend.

_Edited to be a wee bit more realistic about how soon I'll be able to cut a train_

**Comment by jaredhirsch** [comment]
OK, I'm on it.

**Comment by jaredhirsch** [comment]
train-2014.07.19 has left the station. I've opened mozilla/identity-ops#168 to track releasing this code to production (since QA has already tested the code on staging).

**Comment by edwindotcom** [comment]
test pass on 123done.org flame with b2g 2.0
