### ISSUE TITLE
persona.org looks like an afterthought

### ISSUE THREAD

**Issue by woutervddn** [mozilla/persona#4177]
There are some things about the persona.org website that just don't seem to make total sense. In a way it feels as if the actual website was just an afterthought.
- The dark(er) color scheme doesn't really breath out "security"
- "Connect with Mozilla Persona, the safest & easiest way to sign in." is a nice tagline, but it doesn't give enough clarification to new users about what it actually does and if it can be trusted. It should be more re-assuring and informational towards non-tech users. The front page should make clear that persona is better because "security" is the only thing it does, it's their main focus. While most startups have a lot on their mind and it's hard to give security the attention it deserves.
- Overall the content seems to target developers and (tech savvy) early adopters more than mainstream users. (The only call to action on the take a tour / about page is "Implement Persona on your site")
- When logged in, the notification bar on top (.newsbanner) has the most hideous color and is very hard to read.
- The account manager doesn't really put any space between your email addresses and password and alignes everything left. This makes it takes away from the overview.

There are several reasons why this should change in my opinion: 
- For one, users need to feel like they can trust Persona. It's important to give them a sense of ease when they visit the Persona website. 
- A second reason is that for developers, users and Mozilla itself, it's important to raise brand awareness. The whole experience should be seamless, but only if a users knows he's using Persona he'll reason: "Hah, this new website is also using that secure Persona tool from Mozilla, my credentials are safe here". 
- Reason 3 is that it's already hard to justify the use of Persona over Google, Facebook or Twitter as a means of login. A company that uses 3rd party authentication makes sure that they are not responsible for storing a users credentials. Users already have an account there, they know the authentication services. If their passwords leak, they'll be mad at either Google, Facebook or Twitter, not at the 3rd party webservice. If Persona leaks credentials the 3rd party will still take the blame from their userbase. The users don't have any affinity or connection to Persona because they don't use the service as a platform on it's own. Therefor it's crucial to let users know that Persona is just the safest in a more "active" way. Then the users understand that Persona is safer, they know Persona as a seperate entity and the 3rd party developers know that their users would, in case of problems, blame Persona and not their webservice.

**Comment by woutervddn** [comment]
Note: the above needs sub-tasks, but discussing the general idea seemed more appropriate then just making 7 or 8 sub-tasks with not real story behind it.

**Comment by seanmonstar** [comment]
Just to keep things clear, there's 2 sites here. www.persona.org is a
static site, in its own repo (mozilla/persona.org). It's just a landing
page.

The page at login.persona.org is powered by this repo.

> Overall the content seems to target developers and (tech savvy) early
> adopters more than mainstream users. (The only call to action on the take a
> tour / about page is "Implement Persona on your site")

This was the intent. Teaching developers is the only way it would expand. A
user who loves Persona can't do much if the site doesn't implement it.
Instead, most users will use what is available, which we'd hope is Persona.

The eventual goal was to do targeted marketing at developers, such as with
ads, but the money wasn't approved.

**Comment by woutervddn** [comment]
hah, strange, when you want more info you get sent to http://persona.org which automatically redirects you to login.persona.org instead of www.persona.org... That also should be fixed imho.. :/

**Comment by woutervddn** [comment]
I understand that developers are key, and developers might like it, but management might not... There should be an awesome way to attract developers, but if users won't like it, why would the developer start using it in the first place?

**Comment by jaredhirsch** [comment]
If you want to discuss stuff, take it to the list. Closing.
