### ISSUE TITLE
auth_with_assertion tests failing in travis

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#4192]
![screen shot 2014-09-08 at 10 01 46](https://cloud.githubusercontent.com/assets/848085/4183005/f5163c5a-3736-11e4-9475-25c3c72b86a9.png)

![screen shot 2014-09-08 at 10 01 56](https://cloud.githubusercontent.com/assets/848085/4183007/f88280d8-3736-11e4-8dfa-83c79bd70c76.png)

**Comment by jrgm** [comment]
@shane-tomlinson - actually https://github.com/mozilla/persona/issues/4179

**Comment by shane-tomlinson** [comment]
Closing as dup of #4179
