### ISSUE TITLE
confusion in link context on https://www.mozilla.org/en-US/persona/

### ISSUE THREAD

**Issue by baptistem** [mozilla/persona#4193]
the link on : https://www.mozilla.org/en-US/persona/#signin-example
"Test yourself :"  "Go to Voost and sign in." is confusing me.
I understand this as a " you can test persona on Voost"
and I think I'm suppose to understand this as "highlighted projects" or "They use it, why not you?" or even "Watch it in action!"
that's why I think it might be helpfull to change a bit those labels.

**Comment by callahad** [comment]
I'm going to close this and open a broader bug to review all of the places in which Persona is mentioned (MDN, mozilla.org, wiki.mozilla.org, etc.)

We'll review example RPs and presentation as part of that.

Thanks for reporting!
