### ISSUE TITLE
The throbber is broken on FF Android Nightly (35.x)

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/persona#4194]
The loading screen animations look broken in FF Android Nightly.

STR: 
- Go to marketplace in FFA Nightly
- Sign-in

What happens:
- During the sign-in process notice the throbber flash up briefly with broken styling.

What should happen:
- Throbber should appear normally.

Works fine on FFA 32.x Stable.

**Comment by edwindotcom** [comment]
This sounds like a FF Android issue, if it works with Stable, persona doesn't have any FF logic.  moving here: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1072579
