### ISSUE TITLE
Unable to sign in to firefox marketplace

### ISSUE THREAD

**Issue by kzahel** [mozilla/persona#4195]
![screenshot 2014-09-30 at 11 54 27 am](https://cloud.githubusercontent.com/assets/158352/4464381/3e39813c-48d3-11e4-9323-018884b7d6f1.png)

Using chromebook pixel on stable channel, Chrome 38.

**Comment by kzahel** [comment]
Ah, once I checked my email and verified my persona email, it did indeed work. It looks like a case of th error message not being correct. I was able to sign in after confirming my email address with mozilla persona.

**Comment by callahad** [comment]
Glad you got that working. [Marketplace it moving to Firefox Accounts](http://www.agmweb.ca/2014-10-03-fxa/), so I'm going to go ahead and close this.

Once their transition is complete, we'll be removing the code path that causes these kinds of issues. :)
