### ISSUE TITLE
 error browserid@1.0.0-b2 preinstall: `node ./scripts/lockdown`

### ISSUE THREAD

**Issue by parmeshwor11** [mozilla/persona#4199]
did git clone
npm install
and the log is
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@1.4.14
3 info using node@v0.11.14-pre
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ '/home/pthapa/me/elance/persona',
5 verbose install   [ 'JSONSelect',
5 verbose install     'async',
5 verbose install     'bcrypt',
5 verbose install     'cef',
5 verbose install     'compute-cluster',
5 verbose install     'connect',
5 verbose install     'convict',
5 verbose install     'cjson',
5 verbose install     'client-sessions',
5 verbose install     'connect-cachify',
5 verbose install     'connect-fonts',
5 verbose install     'connect-fonts-opensans',
5 verbose install     'connect-fonts-feurasans',
5 verbose install     'connect-logger-statsd',
5 verbose install     'cover',
5 verbose install     'ejs',
5 verbose install     'etagify',
5 verbose install     'express',
5 verbose install     'gobbledygook',
5 verbose install     'hood',
5 verbose install     'i18n-abide',
5 verbose install     'lockdown',
5 verbose install     'jwcrypto',
5 verbose install     'mkdirp',
5 verbose install     'mysql',
5 verbose install     'nodemailer',
5 verbose install     'node-statsd',
5 verbose install     'optimist',
5 verbose install     'postprocess',
5 verbose install     'rimraf',
5 verbose install     'semver',
5 verbose install     'temp',
5 verbose install     'toobusy',
5 verbose install     'uglify-js',
5 verbose install     'uglifycss',
5 verbose install     'underscore',
5 verbose install     'urlparse',
5 verbose install     'useragent',
5 verbose install     'validator',
5 verbose install     'winston',
5 verbose install     'vows',
5 verbose install     'awsbox',
5 verbose install     'irc',
5 verbose install     'jshint',
5 verbose install     'which',
5 verbose install     'htmlparser' ] ]
6 info preinstall browserid@1.0.0-b2
7 verbose unsafe-perm in lifecycle true
8 info browserid@1.0.0-b2 Failed to exec preinstall script
9 error browserid@1.0.0-b2 preinstall: `node ./scripts/lockdown`
9 error Exit status 1
10 error Failed at the browserid@1.0.0-b2 preinstall script.
10 error This is most likely a problem with the browserid package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node ./scripts/lockdown
10 error You can get their info via:
10 error     npm owner ls browserid
10 error There is likely additional logging output above.
11 error System Linux 3.8.0-19-generic
12 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
13 error cwd /home/pthapa/me/elance/persona
14 error node -v v0.11.14-pre
15 error npm -v 1.4.14
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by jrgm** [comment]
> 14 error node -v v0.11.14-pre
> 15 error npm -v 1.4.14

So, we do not run on nodejs 0.11.x. Use nodejs 0.10.32.

**Comment by parmeshwor11** [comment]
thanks
