### ISSUE TITLE
Initial Manage page does not show newly auth'd email

### ISSUE THREAD

**Issue by jrconlin** [mozilla/persona#42]
I have no previous account or interaction with the site. 

I registered an email, performed the verification, but when the verification switched to the manage page, the newly auth'd id was not listed. Refreshing the page showed the email.

**Comment by lloyd** [comment]
more context and a proposed fix: 

```
15:02 < jrconlin> Going to try to reproduce. If I find anything in the code I'll add it to the bug.
15:03 < lloyd> jrconlin: I think I know what's going on
15:04 < lloyd> jrconlin: the dialog is adding to local storage, the manage page does not detect changes.  the latter loads before the former occurs.
15:05 < jrconlin> yeah, that would do it.
15:05 < lloyd> best fix is probably just to register for localstorage events on the manage page.
```

**Comment by shane-tomlinson** [comment]
This is no longer an issue, we are not redirecting to the manage page when the user verifies an email address or account.  Closing.
