### ISSUE TITLE
transferred from bugzilla: user having trouble logging into MDN with Persona

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#4200]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1087829.

Screenshot from bug: ![](https://bug1087829.bugzilla.mozilla.org/attachment.cgi?id=8510000)

Description from bug:
# What did you do?
1. Recalled my GitHub u/p combination.
2. Created/recognized my Persona u/p combination.
3. Attempted to authenticate using GitHub and Persona.
# What happened?

In Mozilla, got an error message, a screen capture is available.

In Internet Explorer, worked fine.
# What should have happened?

In Internet Explorer, worked fine using both GitHub and Persona.
# Is there anything else we should know?

**Comment by jaredhirsch** [comment]
The usual troubleshooting procedure is to make sure that you don't have third-party cookies disabled. Also, please visit this page in FF and screenshot the output: https://people.mozilla.org/~fmarier/troubleshoot.html

**Comment by callahad** [comment]
Closing this pending more information.

From the screenshot, it looks like the user has a bunch of add-ons installed. It's possible that one of these is interfering with Persona. Can you please try creating a fresh profile and seeing if the bug still exists there? https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

Thanks!

**Comment by callahad** [comment]
(Oh, and as an aside, it looks like this error is cropping up on the Yahoo bridge, rather than the main Persona fallback...)
