### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#4203]
Testing the mass issue closing script on this issue before unleashing it on the whole repo...

**Comment by callahad** [comment]
hello
world

**Comment by pdehaan** [comment]
![](http://weknowmemes.com/wp-content/uploads/2012/04/release-the-kraken-lobster-dog.jpg)

**Comment by callahad** [comment]
The kraken is having issues being unleashed :( Hooray for not using Ruby in a really long time...

**Comment by callahad** [comment]
Oh, damnit.

**Comment by callahad** [comment]
So, I did something stupid and accidentally closed 29 issues that should have remained open, and missed this one. Software is hard.

I've reopened those 29, and tagged them with cleanup-2014-oops. Closing this while I go back to re-review those...

**Comment by pdehaan** [comment]
I... should have un-watched that repo before you started this. Now I have 250+ emails and growing.
