### ISSUE TITLE
Functionality for adding emails should also be added in the Account Manager

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#421]
Functionality for adding emails should also be added in the Account Manager on https://diresworb.org.

This would be very useful for a user that found out about BrowserID by opening a page using it, then clicking on the "learn more" link. The user might want to set up an account with multiple emails from the server so he doesn't have to do any more from clients but log in.

**Comment by ghost** [comment]
@jbonacci - you may be talking about issue #386. This issue was added as a comment on that bug, but Lloyd wanted to separate them.

**Comment by lloyd** [comment]
+1

**Comment by groovecoder** [comment]
+1

**Comment by kumar303** [comment]
Without this feature I am currently locked out of https://mozillians.org/en-US/ because my primary browser ID account was not attached to my mozilla email :( I will patiently await account manager enhancements.

To clarify, I created a mozillians account before they adopted browser ID. Now I can't log in with my primary browser ID account. I could create a _new_ browser ID account using my mozilla email but then I wouldn't achieve true global federation (one browser ID account for all sites).

**Comment by groovecoder** [comment]
kumar: you can click "sign in with browserid" and click the "Use a different email" link. that should add another email address to your existing browserid.org account.

**Comment by kumar303** [comment]
_facepalm_. Thanks Luke :) In my defense, I worked on AMO's new-profile completion feature which required me to use the "this is not me" link many times repeatedly while manually testing. It apparently damaged my brain.

**Comment by skinny97214** [comment]
Agreed that the button wording and placement in the layout is odd. I'm still pondering on the right solution.

**Comment by satdav** [comment]
can we get this added as it would be good

**Comment by briandorsey** [comment]
FWIW, I also ran into this while learning about BrowserID. Seems like a natural fit for the Account Management page. It never occurred to me to attempt to log into a site to add another email address.

**Comment by jedp** [comment]
+1 for being able to add new emails in the Account Manager

**Comment by callahad** [comment]
Another +1. I'm reviewing the SUMO docs for Persona, and we point people to login.persona.org if they want to create an account ahead of time. Except they can't add more than one address on login.persona.org.

**Comment by skinny97214** [comment]
@callahad Can you point me to the SUMO doc so I can review it?

**Comment by callahad** [comment]
@skinny97214 https://support.mozilla.org/en-US/kb/what-browserid-and-how-does-it-work/

(Check the [article history page](https://support.mozilla.org/en-US/kb/what-browserid-and-how-does-it-work/history) on SUMO -- there are newer, unapproved drafts pending)

**Comment by csuciu** [comment]
Testcase created here: https://moztrap.mozilla.org/manage/caseversion/10569/

**Comment by jaredhirsch** [comment]
Bumping this aged bug from Beta 2 to Beta 3, as we're out of Beta 2 dev time.

**Comment by skinny97214** [comment]
Assigning to me for a mock.

**Comment by jaredhirsch** [comment]
@callahad can we turn this into a user story in the stories repo?

**Comment by jedp** [comment]
@callahad, @skinny97214 or is the account manager enough of its own beast that it should be tracked outside the main browserid repo?  (Just a question)

**Comment by callahad** [comment]
We're using `.get()` on login.persona.org. Should be relatively trivial to just call `.get()` again to add another address.

**Comment by callahad** [comment]
Roadmap story created. Closing this -- we can track / prioritize there.
