### ISSUE TITLE
OpenID 2.0 for Google accounts is going away

### ISSUE THREAD

**Issue by homerjam** [mozilla/persona#4210]
From https://developers.google.com/accounts/docs/OpenID#shutdown-timetable

> OpenID 2.0 for Google accounts is going away. As there is no developer registration in OpenID 2.0 and we have no way to alert developers to this fact, we are making user-visible changes to the OpenID 2.0 approval page. So that more people see this page, we will also slowly turn-down the auto-approval feature as the deadline approaches.

It'd be great if someone were able to update the identity bridge for gmail accounts (if that makes sense/is actually whats needed).

**Comment by xeor** [comment]
This is important. Every login via Google is now displaying a warning as well. Please put `&openid_shutdown_ack=2015-04-20` in the request (to suppress the warning) when you have a migration plan.
Here are some dates-of-interest from the link provided by homerjam
- November 18, 2014: User-facing warning message may be shown on consent dialogs, directing users to this help article. Developers may suppress deprecation warnings by adding the openid_shutdown_ack parameter, as specified above.
- December 1, 2014: Auto-approval is disabled for a small number of requests on an intermittent basis, some users will be forced to re-consent.
- January 12, 2015: Auto-approval is progressivly disabled for more and more users, these users will be forced to re-consent. Developers passing openid_shutdown_ack are unaffected.
- February 23, 2015: Auto-approval is turned off, users must consent on each request. Developers passing openid_shutdown_ack are unaffected.
- March 23, 2015: Grace period for developers using the openid_shutdown_ack parameter ends, warning is shown and auto-approval turned off for all applications.
- April 20, 2015: OpenID is shut down. A static error page will be displayed on all requests. Make sure you have migrated well before this date.

**Comment by PaulMougel** [comment]
Does anyone have an idea of what is needed to transition?

**Comment by callahad** [comment]
We have an open issue to pass the `openid_shutdown_ack` parameter at https://github.com/mozilla/identity-ops/issues/171, which will go live as soon as @relud has time to hack on getting a staging stack online.

That gives us until February 23rd to switch to OpenID Connect before we see user-visible changes again.

Any help hacking on https://github.com/mozilla/persona-gmail-bridge is appreciated :)

**Comment by jaredhirsch** [comment]
Filed on Bugzilla as https://bugzilla.mozilla.org/show_bug.cgi?id=1109664

**Comment by jaredhirsch** [comment]
See related discussion on dev-identity list: https://groups.google.com/d/topic/mozilla.dev.identity/69kti-UM-hY/discussion

**Comment by djc** [comment]
@relud just deployed a new persona-gmail-bridge to staging that fixes this issue, hopefully it can move to prod soon.

**Comment by homerjam** [comment]
Any news on this? Will everything be ok come April 20th?

**Comment by relud** [comment]
this should be fixed in then next week or so. the fix is currently in
staging at `gmail.login.anosrep.org`. the only delay is finding a good time
to deploy.
- Daniel Thornton
  Mozilla Services Operations Engineer

**Comment by homerjam** [comment]
Excellent. Much appreciated

On 11 March 2015 at 18:04:53, Daniel Thornton (notifications@github.com) wrote:

this should be fixed in then next week or so. the fix is currently in
staging at `gmail.login.anosrep.org`. the only delay is finding a good time
to deploy.
- Daniel Thornton
  Mozilla Services Operations Engineer

**Comment by xfq** [comment]
Is this issue fixed now?

**Comment by djc** [comment]
Yup!
