### ISSUE TITLE
Persona not working (?)

### ISSUE THREAD

**Issue by hanxue** [mozilla/persona#4211]
I am using Firefox Developer Edition 36.0a2, and when I attempt to access a site that authorizes with Persona, I got a message that says 

```
We are sorry, but currently your browser is not supported. 
```

![screen shot 2014-12-24 at 12 03 09 pm](https://cloud.githubusercontent.com/assets/760008/5545645/f5ff9c42-8b64-11e4-9a04-1b6fa53d0105.png)

**Comment by seanlinsley** [comment]
For reference, what is the useragent?

**Comment by k-bx** [comment]
Stable firefox doesn't work for me, seeing same window.

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0"

**Comment by ghost** [comment]
This is is maybe just a issue for mac as it seems, I checked this for Linux with the Firefox Developer Edition build and it seems to work perfectly fine. Until then, I'd highly recommend using the default build of Firefox and see where that'll lead you.

**Comment by k-bx** [comment]
Login is now working for me.

**Comment by ghost** [comment]
@hanxue @k-bx hmm, I've looked into this more but I can't quite completely see why this may be since I don't have a mac at this time.

**Comment by jrgm** [comment]
This works on osx with Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:36.0) Gecko/20100101 Firefox/36.0

Please add more steps to reproduce.
