### ISSUE TITLE
bug in log rotation naming in new stage stacks

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#4215]
Haven't looked further, but popped onto what I think is a current webhead and saw a logfile name `/var/persona/log/verifier-compute.log.1.1.1.1.1.1.1.1.1.1.1`, which is, wut?

**Comment by relud** [comment]
yeah, that was my bad. i fixed it recently, but the deploy to stage didn't
go perfectly last night.
- Daniel Thornton
  Mozilla Services Operations Engineer

**Comment by pdehaan** [comment]
Not sure if this is related to anything, or if it's worthy of a new bug, but I'm seeing errors when I try and load the 'ver.txt' on anosrep.

---

#### https://login.persona.org/ver.txt

> dc417ae Merge pull request #4166 from mozilla/train-2014.07.19-rpm_version
> locale svn r130450

---

#### https://login.anosrep.org/ver.txt

> Cannot GET /ver.txt

**Comment by relud** [comment]
that is intentionally blocked
- Daniel Thornton
  Mozilla Services Operations Engineer

**Comment by jrgm** [comment]
> that is intentionally blocked

huh?

**Comment by relud** [comment]
our nginx configs deny requests to /ver.txt, i thought

**Comment by relud** [comment]
nevermind, i was quite wrong.

**Comment by relud** [comment]
anyways, the reason ver.txt is gone is because it isn't packaged into the rpm deployed to anosrep.org right now.

**Comment by relud** [comment]
_fixing_

**Comment by relud** [comment]
`ver.txt` thing is fixed.

**Comment by pdehaan** [comment]
thanks @relud!

**Comment by relud** [comment]
logs are also fixed.
