### ISSUE TITLE
Persona delivers the domain of an EMail-Address always with small letters

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/persona#4218]
Please have a look at:
https://bugzilla.mozilla.org/show_bug.cgi?id=1148789

Verified with Socorro and Mozillians.

**Comment by djc** [comment]
As is discussed in that bug, the domain of an email address is case-insensitive. Therefore, I don't agree that this is a bug.

**Comment by jrgm** [comment]
Yeah, if a relying party is considering foo@bar.com and foo@Bar.com to be two distinct email addresses, that is a bug in the relying party's code. DNS domain names are and have always been case insensitive.

**Comment by Tobias-B-Besemer** [comment]
Yes, that is also a bug in the relying party's code.
But there is also nowhere the rule, that a domain have to be in small letters - so why Persona change it?
I think this is the bug in Persona.
I also think - and have the experience - that a user want to have his Email displayed as he have entered them.
Please reopen the bug and fix it.
