### ISSUE TITLE
Sign-in popup has no scrollbars → confusing when zoomed in

### ISSUE THREAD

**Issue by aleksejrs** [mozilla/persona#423]
If the zoom in ratio for the browserid.org is big, some content of the pop-up window is not visible. That’s very confusing, because there are no scrollbars.

**Comment by lloyd** [comment]
firefox seems to not add scrollbars, chrome does.

**Comment by lloyd** [comment]
for the record, what browser and OS were you on?

**Comment by aleksejrs** [comment]
Firefox (probaby 8.0 Beta) on GNU/Linux.

**Comment by lloyd** [comment]
I too can repro this on Linux, arch Linux Firefox.  This really sounds like a platform specific browser bug.  Let's look for this upstream in bugzilla...

**Comment by shane-tomlinson** [comment]
@lloyd - in include.js, we have scrollbars=0 - suppressing scrollbars.

In MDN's window.open article under Notes on Scrollbars - https://developer.mozilla.org/en/DOM/window.open#Note_on_scrollbars, it notes 

```
user sets a minimum font size for pages which is bigger than the font-size the 
web author requested. People over 40 years old or with particular viewing habit 
or reading preference often set a minimal font size in Mozilla-based browsers.
```

Under the scrollbars option description, it notes 

```
Tip: For accessibility reasons, it is strongly encouraged to set this feature always to yes.
```

I experimented with setting `scrollbars=1` in OSX, Windows and Linux and all current browsers act sane w.r.t. when it displays the slider within the scrollbar.  All browsers show a scrollbar placeholder if the scrollbar is not needed, but show the slider when necessary.

I think we should enable the scrollbars for users who have their browser zoomed in.

**Comment by lloyd** [comment]
If we don't have scrollbars in the default (non-zoomed) view in any of the browsers we support, then I'm +1

**Comment by shane-tomlinson** [comment]
Screen shots:

https://skitch.com/set117/8n1pu/win7-firefox-unzoomed
https://skitch.com/set117/8n1qm/win7-firefox-zoomed

https://skitch.com/set117/8n1qh/safari-osx-unzoomed
https://skitch.com/set117/8n1xi/safari-osx-zoomed

https://skitch.com/set117/8n1tb/ubuntu-chrome-unzoomed
https://skitch.com/set117/8n1tx/ubuntu-chrome-zoomed

**Comment by shane-tomlinson** [comment]
Update on this:

Testing various combinations of
resizable=0/1
scrollbars=0/1

In OSX

In Windows:
- Safari and Chrome always a show minimum of placeholders
- Firefox, Opera, and IE with scrollbars=0 do not show scrollbar even if resizable=1 and zoomed in.  All show the placeholder if scrollbars=1
- IE does not allow resizing unless resizable is set to true.

In OSX:
- Safari and Chrome always a show minimum of placeholders
- Opera - Dialog is always full screen
- Firefox with scrollbars=0 does not show the placeholder no matter what the zoom or the resizable setting.

In Ubuntu:
- Opera and Chrome always a show minimum of placeholders
- Firefox with scrollbars=0 does not show the placeholder no matter what the zoom or the resizable setting.

**Comment by lloyd** [comment]
I want our dialog to scroll when the user zooms, but not display placeholders when not neccesary.  I think this is possible with CSS changes, based on this:

https://skitch.com/lloydhilaiel/8n197/skitch

**Comment by shane-tomlinson** [comment]
Closing as fixed with pull request 1149

**Comment by jrgm** [comment]
looks good to me for osx(opera,safari,chrome,FF), winxp(opera,safari,IE8,chrome,FF), win7(opera,safari,IE9,chrome,FF), 
ubuntu(opera,chrome,FF). The scrollbars are not shown by default, but are shown as the text size is increased; scrollbars
also shown as the window is shrunk in both directions. Opera,IE9 and FF all switch to an alternative display as text size
increase; chrome and safari (webkit) do not, but all switch on window resize. IE8 is IE8. I'm assuming the change is moot
for mobile.
