### ISSUE TITLE
Undefined index: data in persona_verify()

### ISSUE THREAD

**Issue by solarchemist** [mozilla/persona#4233]
Having an issue with Persona on Drupal, and can't solve it. Haven't changed Drupal config, Persona worked fine previously, but stopped. Running latest version of [Drupal's Persona module](https://www.drupal.org/project/persona). Drupal 7, Apache 2.4.10, Debian 8.4.

My Drupal log shows one notice:

```
Notice: Undefined index: data in persona_verify() (line 293 of /var/www/html/drupal/doktorandnamnden/sites/all/modules/persona/persona.module).
```

followed by the error:

```
Bad response: NULL; HTTP status: 0
```

The site has the same Persona settings as ever (from Drupal's status page):

```
Persona audience: http://dn.uppsalastudentkar.se:80
Persona verifier: verifier.login.persona.org
```

The `persona_audience` variable is set in Drupal's config file, which is also confirmed by Drupal's status page (cf above).

I'm not sure what to make of this. Everything was working fine for a long time, and now suddenly no longer. I can still login fine at `login.persona.org`, which suggests that the error is on my end.

But I can't figure out what. I've checked my Apache conf for this site, I've checked Apache's logs, but nothing has helped so far. I hope I'm not bringing this up in the wrong forum.

BTW I'm aware that Persona is shutting down later this year, but I was hoping to squeeze a few more months out of it before switching the site to some other auth system :-)

**Comment by djc** [comment]
Can you somehow get at the request that is being sent to the verifier in persona.module:283, and ideally also the response? That would probably go a long way toward clarifying what's going on here.

**Comment by solarchemist** [comment]
Well, it's my server, so theoretically I should be able to see anything I want, but I'm not an expert in this area. I'm not sure how to see what's being sent to `persona_verify()`, but I can read Apache's logs. Please let me know if the following is not what you're asking for, and I'll try to dig some more.

So when the user starts the sign-in process (the Persona window opens per usual), and this is logged (IP addresses masked):

```
130.000.00.00 - - [26/May/2016:11:14:08 +0200] "GET /user/persona/token HTTP/1.1" 200 594 "http://dn.uppsalastudentkar.se/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
```

So the log confirms that this step works as expected.
Next step, when the user clicks "sign in" and stuff is submitted to Persona, I observed the following lines:

```
130.000.00.00 - - [26/May/2016:11:18:28 +0200] "POST /user/persona/sign-in HTTP/1.1" 401 347 "http://dn.uppsalastudentkar.se/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
130.000.00.00 - - [26/May/2016:11:18:28 +0200] "GET / HTTP/1.1" 200 9571 "http://dn.uppsalastudentkar.se/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
130.000.00.00 - - [26/May/2016:11:18:29 +0200] "GET /misc/message-24-error.png HTTP/1.1" 200 1017 "http://dn.uppsalastudentkar.se/modules/system/system.messages.css?o7qvjz" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
```

So I got a `401 Unauthorized` response. Any ideas on how to pinpoint the cause of the error much appreciated.

**Comment by djc** [comment]
The 401 you see here is probably the result of the problem you reported. If you can figure out how to print to the Apache error log, you could inject some code to that effect into the persona.module file.

**Comment by solarchemist** [comment]
The error has been fixed with the [release of Drupal Persona](https://www.drupal.org/project/persona/releases/7.x-1.17) v 7.x-1.17.
