### ISSUE TITLE
add the existing "Sign in" link to browserID home page

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#424]
When a user goes directly to https://browserid.org/, the centered content doesnt offer the user an existing sign-in account link.   They would need to click "Sign Up" first, or move to the corner to "Sign In" in order to get to existing user screen.   

I propose adding the "Existing account? Sign in." link to the bottom of the welcome screen.   It's an expected option that most sites asking users to sign in should be looking for.

Repro:
1) goto https://browserid.org/
2) verify there is no link in the main content body on existing sign in accounts

Expected:
- have the added line to include existing sign in accounts below the main content

**Comment by lloyd** [comment]
fixed with rebrand.
