### ISSUE TITLE
Create a medium-technical FAQ page 

### ISSUE THREAD

**Issue by aleksejrs** [mozilla/persona#426]
Currently the immediately available information about BrowserID (e.g. https://browserid.org/about ) is
- for the end user only, explaining how to register and log into sites using BrowserID (which, for its current state, is similar to OpenID),
- or is spread through the blog ( http://identity.mozilla.com/ ), which contains both posts with that end-user info and posts with object names. Also, the blog’s design (fonts, colors, plugins I don’t have) makes searching information in it inconvenient.
# How I couldn’t find what I wanted

I already used OpenID, so I was interested in the difference between it and BrowserID. I am not a developer, so I skipped the paragraph about JavaScript, and tried to watch videos. But some videos are also end-user-oriented, although being videos they take time and are not well-seekable. So I didn’t bother to read through the whole blog to find the right post mentioning certificates. However readable though, a blog wouldn’t be a good place for a just-came-there newbie’s introduction, IMO (unless its top post is an FAQ itself).
# What the FAQ should explain
- How BrowserID is different from OpenID, and/or how it _will_ be different
  *\* Be clear on which is which of the current state and are the future plans; current browserid.org Privacy Policy appears to state the opposite of the privacy intent: “As part of the normal operation of the BrowserID service, Mozilla will retain a log of which sites you have disclosed your email to.”).
  *\* The phrase “Trusted 3rd party signs a certificate that you store in your browser” at https://wiki.mozilla.org/Identity/Verified_Email_Protocol explained the difference from OpenID to me, because I have used GnuPG before.
- If a browser extension is needed, and what the provided extension does.
- Which browsers work, and which don’t (and why not all do).

**Comment by lloyd** [comment]
+1 We aggregate this material, all three suggestions in the FAQ section above sound right to me.  The which browsers are supported needs to be both on SUMO for end users, and referenced and expanded on from our developer facing FAQ.

Suggest we use the github wiki to start.

**Comment by ozten** [comment]
We're starting to address this material in the Field Guide.

OpenID comparison: 
http://mozilla.github.com/browserid-field-guide/browserid_for_sys_admins.html

We'd love more issues or patches with prose.

**Comment by callahad** [comment]
I'm stealing this and assigning it to me.

**Comment by callahad** [comment]
I believe now we cover these on MDN:

How does Persona differ from other solutions? https://developer.mozilla.org/en-US/docs/Persona/Why_Persona

What is required / what browsers work? https://developer.mozilla.org/en-US/docs/persona/Browser_compatibility
