### ISSUE TITLE
Opening BrowserID from an Android WebView gives HTML5 error

### ISSUE THREAD

**Issue by jmathai** [mozilla/persona#428]
Steps to reproduce:
1. Launch OpenPhoto app
1. Click settings button
1. Click "log in"
1. In the web view, click Log In button
1. See attached

_This is being tracked on the OpenPhoto side here: https://github.com/openphoto/mobile-android/issues/13_

![](http://i.imgur.com/OqXXh.jpg)

**Comment by pboos** [comment]
I investigated a little in the BrowserID Javascript.
If I saw correct, it gets checked if the browser supports local storage (i did enable this), and postMessage. Sadly I do not find any way to enable postMessage. I guess that is not supported in Android.

Any idea how we can get that to work in Android WebView so we can support BrowserID from within an application?

**Comment by jmathai** [comment]
@pboos, is there any reason why we're loading the OpenPhoto URL inside of a webview instead of launching the browser? That's the flow we're using on iOS (though we have a separate issue with iOS5).

**Comment by lloyd** [comment]
the dev team is meeting up in the next week to agree on a strategy for native mobile apps

**Comment by jmathai** [comment]
@lloyd, awesome.

**Comment by shane-tomlinson** [comment]
Closing in favor of #2034
