### ISSUE TITLE
The diresworb.org "remove" button is not displayed fine in IE9 and Opera

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#435]
OS: Windows 7, Ubuntu 11.04
Browser: IE9, Opera 11.51

STR:
1. Open https://diresworb.org in a browser and sign in.
2. Click on the "edit" button.

The "remove" buttons are red with white text in Firefox and Chrome. In Opera and IE9, the buttons are light blue with a red outline. The text is also outlined with red in Opera.

**Comment by shane-tomlinson** [comment]
We are using linear gradients on these buttons and the styles are not correct for IE and Opera.

**Comment by ghost** [comment]
Verified on Win 7 using IE9 and Opera 11.51.

On Opera, the Remove button looks now as in Firefox.
On IE9, the button is now a very light red with a dark red outline. There is a quite big difference between the shade of red on the button in IE9 and the one in Firefox/Opera/Chrome.
