### ISSUE TITLE
Verification mail sender host does not have a reverse DNS entry

### ISSUE THREAD

**Issue by dc7kr** [mozilla/persona#456]
NOQUEUE: reject: RCPT from unknown[63.245.208.223]: 450 4.7.1 Client host rejected: cannot find your hostname, [63.245.208.223]; 

Claims to be browserid1.vm1.labs.sjc1.mozilla.com - as this is a common SPAM check it prevents many SPAM protected mail servers from delivering the email...

**Comment by lloyd** [comment]
The fix for this is already in beta.  to verify, sign up for browserid via http://beta.myfavoritebeer.org and inspect the email that is sent to you - this fix is scheduled to roll into production on thursday (2 days from now).

**Comment by dc7kr** [comment]
confirm that it works in the beta.myfavoritebeer.org - thanks :)

**Comment by lloyd** [comment]
yay, thank you!
