### ISSUE TITLE
Coherent dialog link colors and contrast

### ISSUE THREAD

**Issue by digitarald** [mozilla/persona#459]
The link colors in the dialog vary between black, gray and blue. As a coherently applied color, the blue might provide a good contrast.

Adding to better contrast, the watermark logo style is a nice idea but might be hard to read with bad light or sight; but it should as it identifies/brands the whole process.

ref: https://bugzilla.mozilla.org/show_bug.cgi?id=695560

**Comment by lloyd** [comment]
+1

**Comment by clarkbw** [comment]
Hey, thanks for the report!

I'm going to take this on when redesigning how the "This is not me" and "Use a different email" links.  I think the location of those links is the larger problem right now but I'll try to address link color at the same time.

I did a quick change of color to show how when we use all blue it ends up degrading the quality of all the links.  The sign in button uses the same blue so links that are blue can't be around that button or they become harder to read.
http://cl.ly/1b2m1x332Y3g2e392x24

Currently we have 3 colors for links, blue: #549FDC, gray: #62615F, and the standard black: #222222 which is pretty basic but we don't want to have to many variations unless we're on backgrounds that demand it. 

The prototypes I have so far move the links to better locations and try to use a little background highlight to make a difference. http://cl.ly/1J3P0K3a3W0G3n3E260x

Also thanks for bringing up the concerns about the BrowserID watermark logo.  Branding might change in the near future so I'll keep this in mind but I'm not going to act on it just yet.

Is your ultimate concern a goal of consistency or contrast?

Thanks!

**Comment by digitarald** [comment]
I'd say consistency of link styles on the page is important, but styling the links so the user knows that they are clickable is even more important.

p.s. On the screenshot you posted, another issue I see is that the users email address needs to pop a bit more, maybe even as big as the bold and dark app-name on the right side; to show the 1:1 relation of _user-email_ signs into _app_

**Comment by clarkbw** [comment]
Ok, thanks that's good to know.  We definitely want to strike a balance between pleasing design and jakob nielsen design. :)

re: email pop.  Yes, I think that's from the crowding effect.  Previously the email address was fine because it was mostly alone but now that I'm crowding it with links it doesn't stand out as much.  Still a work in progress...

**Comment by shane-tomlinson** [comment]
@clarkbw - I like the placement you suggest in the second image, but one problem with the wording is that "use a different address" can be interpreted similarly to ""this is not me."  I have been going over this in my head a lot and I know why "use a different email address" makes sense, but from just that wording it is not clear whether you are signing into a different account or using a different email address for the current account.  And then "Add a new email address" does not give the impression that you will be signed in with that address as soon as it is verified.  Ideas?  User testing needed?
