### ISSUE TITLE
new email address field is automatically capitalized on iOS.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#464]
add the autocapitalize=off attribute to the input field.

**Comment by ghost** [comment]
Verified on an iOS 4.2.1 iphone using Safari 5.0.2.

This issue doesn't reproduce anymore in the BrowserID dialogs opened from the client, but it does reproduce when opening https://diresworb.org manually and signing in to BrowserID there.

**Comment by shane-tomlinson** [comment]
@jbonacci - excellent catch.  Time to fix that.
