### ISSUE TITLE
Show user an error message if communication relay cannot be found

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#465]
This can happen if the user bookmarks the dialog's URL before the hash has been cleared.  If the user opens that URL a second time, it will no longer function correctly.

**Comment by shane-tomlinson** [comment]
ae88f7ed440c9a35ae9eaa9d3e5ec1b2c038911b fixes this.

**Comment by ghost** [comment]
Verified bug on Windows 7 + Firefox 7.0.1.The following error message is now displayed:
"We are very sorry, there has been an error! 
To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below."
