### ISSUE TITLE
break include.js into distinct components (for testing), combine in build script

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#483]
This is to facilitate unit testing.

**Comment by ianb** [comment]
FWIW, here's what I use to include the JSChannel code into OWA's include.js: https://github.com/mozilla/openwebapps/blob/develop/site/tools/inline_code.py

(though I check in the result)

**Comment by shane-tomlinson** [comment]
thanks @ianb

**Comment by shane-tomlinson** [comment]
Closing as won't fix.

**Comment by shane-tomlinson** [comment]
Re-opening with @callahad's push to make this happen.

**Comment by callahad** [comment]
Closing back down -- include.js is now broken out into its constituent components and combined at build time. We just have to do some cleaning to make it awesome...
