### ISSUE TITLE
specifying IP_ADDRESS from the command line no longer works

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#488]
The main RP shows, but the dialog never appears.

**Comment by shane-tomlinson** [comment]
@lloyd, I am labeling this 4 star because I often use IP_ADDRESS from the command line to specify a non-localhost IP address so I can test from either tablets, other laptops, or phones.

**Comment by lloyd** [comment]
I'll take a look first thing

--lloyd

**Comment by shane-tomlinson** [comment]
@lloyd - this is working again, was the fix the change for #486?

**Comment by shane-tomlinson** [comment]
@lloyd, I can confirm that this works now.  Do you want to shut it, or want me to?
