### ISSUE TITLE
Contrast on grey 'sign in' button is way too low

### ISSUE THREAD

**Issue by gijsk** [mozilla/persona#49]
On https://browserid.org/developers.html, there's a grey sign in button that's promoted for use. However, its foreground and background color have a very small contrast ratio.

Ref: http://juicystudio.com/services/luminositycontrastratio.php

The button has text in #aeaeae, and a background gradient from #9a9a9a to #757575. Even on the darkest side, that's a contrast ratio of 2.08:1, under the 3:1 minimum for big text, and way under the 4.5:1 minimum for small text, like on this button. In less analytical and more human terms, this means it's really hard / impossible to read for people with less-than-perfect eyesight.

Could this button please be replaced with a version with brighter text and/or a darker background? Thanks! :-)

**Comment by clarkbw** [comment]
Updating the link: https://github.com/mozilla/browserid/wiki/How-to-Use-BrowserID-on-Your-Site

I think that button was intended to be used when the dialog is open and not as a regular button, however you wouldn't get that from the docs; only from it's usage on the myfavoritebeer site.
