### ISSUE TITLE
Email addresses with uppercase letters in the domain are rejected by registration.

### ISSUE THREAD

**Issue by MisfitGeek** [mozilla/persona#501]
When registering an email address, functional email addresses that contain upper case alphabetic characters are rejected as invalid addresses.

Example: MarkBrown@Mozilla.org is illegal.

**Comment by JoeStagner** [comment]
Yes - it's the upper case in the domain name that causes the rejection.

**Comment by shane-tomlinson** [comment]
@MisfitGeek & @JoeStagner - thanks for the input here!
