### ISSUE TITLE
The following assertion returns an Internal Server Error; also, server should return JSON errors, not HTML

### ISSUE THREAD

**Issue by gerv** [mozilla/persona#506]
POST to https://browserid.org/verify with Content-Type'application/x-www-form-urlencoded, and content as follows:

assertion=eyJjZXJ0aWZpY2F0ZXMiOlsiZXlKaGJHY2lPaUpTVXpFeU9DSjkuZXlKcGMzTWlPaUppY205M2MyVnlhV1F1YjNKbklpd2laWGh3SWpveE16SXdNVFUyTWpBNU5EVXpMQ0p3ZFdKc2FXTXRhMlY1SWpwN0ltRnNaMjl5YVhSb2JTSTZJbEpUSWl3aWJpSTZJamMzT0RRM09ESXhOems0TmpZd09EVXdOVEV6TmpnNE9UQTJNamt5TkRjeE1qUTJOekUwT0RReE9USTFNVFV4T0RJd01UTXpORFU1TlRVM016SXlORGd3TlRJeU5UVTVOakV5TXpBM05qTTNNekUwTURJek1qZ3lNVFV6T0RFek9EYzBNekEwTWpJM01UVTFNelUwTXpnM05qRXhOall5TURNd016TXpPVEF4T0RVNU1ESTJPRGczTlRNMk1UVTNPVGc1TkRZME56Z3pPRGNpTENKbElqb2lOalUxTXpjaWZTd2ljSEpwYm1OcGNHRnNJanA3SW1WdFlXbHNJam9pWjJWeWRrQnRiM3BwYkd4aExtOXlaeUo5ZlEuTWhLR3Z5Nk9mVzMzRzctaDkwZUIwRjVTbjZRYmRCNGJkSjhlOGJJOGRXUzJPZlpLQ0tTUndGVDNnejBvaDJwbjZiVVBJaXBfOWVIVEFadURPaVNTU3ZBQkFjZmx6ZURlOVJTb3JvLVJZRjFHakNWNDBZWFJEMVNHS0UxcTVXMzdDWHpTdEJMV2t1U1dKczdwQXdRVEd2VTJmeVZ0M0Nka0FobmdGWU00NWhBIl0sImFzc2VydGlvbiI6ImV5SmhiR2NpT2lKU1V6WTBJbjAuZXlKbGVIQWlPakV6TWpBd056ZzBOVFUzTWprc0ltRjFaQ0k2SW1oMGRIQTZMeTlpYlc4dE5DNHdMbXh2WTJGc2FHOXpkQ0o5LkJpMW1hV3ZKbFM5UFowaWV1d25lRlN5VlZXZ28xT3BWVnZXb1NVNDlORjI2emNPRkhDLUthM0dPeWpHYW9lZXgtd1c2T0pDTW9jSzRwWks4bnZDZE9BIn0%3Fbrowserid_assertion%3DeyJjZXJ0aWZpY2F0ZXMiOlsiZXlKaGJHY2lPaUpTVXpFeU9DSjkuZXlKcGMzTWlPaUppY205M2MyVnlhV1F1YjNKbklpd2laWGh3SWpveE16SXdNVFUyTWpBNU5EVXpMQ0p3ZFdKc2FXTXRhMlY1SWpwN0ltRnNaMjl5YVhSb2JTSTZJbEpUSWl3aWJpSTZJamMzT0RRM09ESXhOems0TmpZd09EVXdOVEV6TmpnNE9UQTJNamt5TkRjeE1qUTJOekUwT0RReE9USTFNVFV4T0RJd01UTXpORFU1TlRVM016SXlORGd3TlRJeU5UVTVOakV5TXpBM05qTTNNekUwTURJek1qZ3lNVFV6T0RFek9EYzBNekEwTWpJM01UVTFNelUwTXpnM05qRXhOall5TURNd016TXpPVEF4T0RVNU1ESTJPRGczTlRNMk1UVTNPVGc1TkRZME56Z3pPRGNpTENKbElqb2lOalUxTXpjaWZTd2ljSEpwYm1OcGNHRnNJanA3SW1WdFlXbHNJam9pWjJWeWRrQnRiM3BwYkd4aExtOXlaeUo5ZlEuTWhLR3Z5Nk9mVzMzRzctaDkwZUIwRjVTbjZRYmRCNGJkSjhlOGJJOGRXUzJPZlpLQ0tTUndGVDNnejBvaDJwbjZiVVBJaXBfOWVIVEFadURPaVNTU3ZBQkFjZmx6ZURlOVJTb3JvLVJZRjFHakNWNDBZWFJEMVNHS0UxcTVXMzdDWHpTdEJMV2t1U1dKczdwQXdRVEd2VTJmeVZ0M0Nka0FobmdGWU00NWhBIl0sImFzc2VydGlvbiI6ImV5SmhiR2NpT2lKU1V6WTBJbjAuZXlKbGVIQWlPakV6TWpBd056ZzBPRE00TmpVc0ltRjFaQ0k2SW1oMGRIQTZMeTlpYlc4dE5DNHdMbXh2WTJGc2FHOXpkQ0o5LmpHeFhxVHIzRE5hUjVUdHRYQVlJUl9UbHJGV2hOdFNfclhEQWRvWjVyMURoaVJwVnVRbmZQVmJPZHdzQW1seEhTV3JMeGJuNjNycXhva2M4YnRseC1BIn0&audience=http%3A%2F%2Fbmo-4.0.localhost%3A80

The server should try very hard never to return an ISE, because many people (like me) pipe the return straight into a JSON parser. Your 500 error page should be some static error JSON, not an HTML page.

Gerv

**Comment by lloyd** [comment]
a fix may be required to close issue #525

**Comment by gerv** [comment]
I would strongly argue that returning errors in JSON is a very high priority. Unless you are going to make the server bulletproof enough to never, ever return an error (!) for the 1.0 release, it means that every client is going to have to do a sniff test on the returned data to see if it's even JSON. (And that procedure isn't even illustrated by the sample code.)

Gerv

**Comment by lloyd** [comment]
I would strongly agree with you, @gerv.

This is fixed in d25f4df88f55793c692fefa09ac8ec8ef33ba419, and you can test on dev now (https://dev.diresworb.org/verify)

We also grew extensive tests of the verifier and as any case comes up where input can cause a non-json response we'll add a test and resolve:

https://github.com/mozilla/browserid/blob/dev/tests/verifier-test.js
