### ISSUE TITLE
Assertion uses base64-encoding twice

### ISSUE THREAD

**Issue by gerv** [mozilla/persona#507]
I can't work out the exact format of the "assertion" parameter, but it looks like it's a base64 encoding of a JSON object which itself contains base64 data (or a dotted contatenation of the same). This is really inefficient - each time you base64-encode, you waste 2 bits per octet. You have to do it once for ASCII-armouring, but twice is surely unnecessary?

Gerv

**Comment by benadida** [comment]
yes, this bit of ugliness is courtesy of yours truly as I haven't found a better way to encode a couple of parameters where one is already base64-encoded due to specifications. If you have suggestions, let me know! We can still change the format of the assertion for a little bit longer....

**Comment by gerv** [comment]
Is there any documentation on exactly how it's constructed at the moment? I'd rather read that than reverse-engineer it :-))

Gerv

**Comment by benadida** [comment]
@lloyd has proposed a very nice way to fix this, by having the format be:

rootcert~intermediate1~intermediate2~assertion

using the ~ character, which isn't used in JWTs. Upping the priority on this so we do it soon.

**Comment by lloyd** [comment]
Propose we update the verifier to accept either in time for the 12.22 train, then we would start generating the new format in time for the 01.08 train.

**Comment by benadida** [comment]
proposal accepted. High Five!

**Comment by lloyd** [comment]
High five!

--lloyd

**Comment by lloyd** [comment]
upstream patch to allow generators of assertions generate either format explicitly, and parsers of assertions parse both: https://github.com/mozilla/jwcrypto/pull/7

If we merge that and publish jwcrypto 0.1.1 and then upgrade to that for the 12.22 train, we have a verifier that accepts either format.  If we pass true into bundleCertsAndAssertion for the 2012.01.05 train, then we have code that generates the new format.
