### ISSUE TITLE
Tooltip should display for a reasonable amount of time based on text.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#508]
I found the tooltip displayed for "we have just sent an email to this address" to be displayed for a very short period of time for the amount of text.  If the amount of time displayed was based on the amount of text and some base amount for an average users reading speed (include some fudge factor), it would be much more usable.

Tied to #430

**Comment by ghost** [comment]
Verified on Windows 7 with Firefox 7.0.1 and Chrome 14. The tooltip is displayed for 8 seconds (enough for the user to read the text).
