### ISSUE TITLE
set explicit email max length limits on the client

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#513]
http://en.wikipedia.org/wiki/Email_address

The format of email addresses is local-part@domain where the local-part may be up to 64 characters long and the domain name may have a maximum of 253 characters - but the maximum 256 characters length of a forward or reverse path restricts the entire email address to be no more than 254 characters.[1] - formally defined in RFC 5322 (sections 3.2.3 and 3.4.1) and by RFC 5321.

**Comment by ghost** [comment]
Verified this in the BrowserID dialogs opened from beta.myfavoritebeer.org and on diresword.org. The user can now only enter 254 characters in the email text boxes.
