### ISSUE TITLE
running tests freezes at various points

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#530]
no symptom other than tests freeze, no error message. Could be related to process thing.

**Comment by lloyd** [comment]
works for me reliably on all the machines I own, virtual and otherwise.  Please try with latest dev, and define `LOG_TO_CONSOLE`.  If you can reproduce, re-open with the last log messages you see, and with the output of `ps auxww | grep node`

**Comment by lloyd** [comment]
reproduced on OSX twice - first time in list emails, second time in forgotten email test.  last output on console is a verification URL.  theory is that verification url handling isn't working properly . specifically there's a race condition.  reopening!

**Comment by lloyd** [comment]
indeed, it is a timing problem.  When a token is generated by the browserid process before the testing process has had a chance to listen for it, things break.  fix underway...
