### ISSUE TITLE
remove 'need help?' link and add help to the bid/about page

### ISSUE THREAD

**Issue by clarkbw** [mozilla/persona#533]
I'd like to simplify the dialog a bit more.  While I think we do want to offer help to people I think having only 2 possible actions "next" and "learn more" creates a nicer world in our popup.  The learn more link is a more natural link color and if it's the only other action besides going to the next step I think people are likely to use it if they are confused.  Currently the "need help" link just jumps to support and I think we can / should offer that from the about page anyway.

My plan is to add a single line below the instructions and offer a "need help" link at the bottom of the page.

**Comment by clarkbw** [comment]
The "learn more" link takes you there and it would be the only link resource on the popup.  Even with the help link as it is now you'd have to know to use it or leave the popup and go to browserid.org

**Comment by shane-tomlinson** [comment]
@clarkbw - I have removed the "need help" link from the dialog and added it to the same location on the main site.  Is this more along the lines of what you had in mind?

**Comment by clarkbw** [comment]
Yeah, if you can add a small section to the bottom of the about page as well that would be awesome so we have a larger callout in that space.

Something like this is just an `<hr>` plus another`<div class="row" style="text-align:center;">`
http://cl.ly/1N461t0b1L2b272W3f1j

**Comment by ghost** [comment]
Verified on Windows 7 + Firefox 8.0.

"If you need some help with BrowserID, head over to our support center. " is now displayed on diresworb.org/about, "support center" being a link to https://support.mozilla.com/en-US/kb/what-browserid-and-how-does-it-work.
