### ISSUE TITLE
assess what it would take to port to nodejs 0.6.0

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#535]
given nodejs 0.6.0 comes with basic debugging support, and with improved primitives for multiprocessor support (useful for distributing crypto over multiple cores), we should take a look at what a port would take.

**Comment by benadida** [comment]
sounds like we all need to update then?

**Comment by lloyd** [comment]
let's decide whether we want to upgrade on wed.  For now, the code will run either under node 0.4.x OR 0.6.0.
