### ISSUE TITLE
Need a way to handle fallbacks without third-party scripts

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#54]
Currently, the proposed fallback code for browsers without native BrowserID support requires a script tag referencing a third-party script.  This will not work for sites which care about security and do not want to trust third-party scripts.  Ideally, the fallback code should have the option of hosting the fallback script natively on the same domain as the site.

**Comment by lloyd** [comment]
you can copy the script but you then have to make sure it stays up to date, and it can change as frequently as once a week, though in practice much less often
