### ISSUE TITLE
Tab order on browserid.org login form

### ISSUE THREAD

**Issue by jsocol** [mozilla/persona#544]
The tab order on the browserid.org login form is, starting from the username: username, password, remember me, _forgot password_, sign in. I think the expected tab order would be: username, password, sign in, remember me, forgot password. Or possibly remember me, sign in, forgot password.

**Comment by shane-tomlinson** [comment]
@jsocol - thanks for the tip, it is now fixed!

@jbonacci, @ioanab - when verifying fix, please use Chrome as this does not affect Firefox.
