### ISSUE TITLE
static resources served with improper headers

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#546]
all resources need content type.  static resources need proper cache headers.

example:

```
curl -i https://browserid.org/css/browserid.min.css | egrep -i '^content'
```

**Comment by lloyd** [comment]
we suspect this may be preventing IE8 from working too.  see https://skitch.com/markmayo/g8da7/scout-internet-explorer-8-sauce-labs

**Comment by vmunix** [comment]
Result, otherwise, in IE8:  https://img.skitch.com/20111109-f7q82e81q33eru7xmi9sswg9b5.jpg

**Comment by lloyd** [comment]
resolved in dev.  please regress.  (IE8 fully functional in dev)

We need to figure out cache headers and invalidation, but that's a different issue.
