### ISSUE TITLE
Document the rationale for email providers needing BrowserID support

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#55]
The BrowserID spec proposes that both browsers and email providers should have native BrowserID support, rather than just relying on the email-me-a-crypto-token approach.  Getting the email provider involved in this process, rather than simply relying on sending an email and confirming receipt of that email, seems suboptimal (and prone to various abuses by email providers).  Please document the rationale for involving the email provider in any way other than processing an email.

**Comment by shane-tomlinson** [comment]
Since @callahad is now our document master, re-assigning to him. - Is this being taken care of with the new doc push?

**Comment by callahad** [comment]
@joshtriplett Do you still feel the same about email providers being involved in the BrowserID protocol?

> Getting the email provider involved in this process, rather than simply relying on sending an email and confirming receipt of that email, seems suboptimal (and prone to various abuses by email providers).

Offloading identity certification to the email providers is kind of the point of the protocol :) If we relied on mailing a token to people, we wouldn't have a decentralized protocol, since we would have to do the mailing.

**Comment by joshtriplett** [comment]
> Offloading identity certification to the email providers is kind of the point of the protocol :)

That doesn't seem at all obvious given the descriptions of the protocol, which seems designed to offload identity certification to _browsers_.  Email verification just seems like a step taken to ensure that the site using BrowserID^WPersona can actually rely on the email address as something other than an opaque unique ID.

I don't mean to suggest that email verification has no purpose in the protocol; however, the rationale seems subtle enough that further clarification would help.

**Comment by callahad** [comment]
@joshtriplett Gotcha. Thanks for the update. If you don't mind going back and forth with me for a few more comments, I'd love to get a fleshed out idea of what you're thinking and how to best explain the system.

The central idea is for the browser to hold and show credentials _issued by_ the email provider: if I want to use `foo@example.com`, then I need a certificate from example.com attesting to my identity. As a temporary measure, Mozilla is willing to issue certificates for domains that can't issue their own, but before it does so, it sends a verification email for assurance that you really do control that address.

But that part is completely temporary -- as soon as a domain can issue its own certificates, the protocol uses those. The validity of a certificate can be verified without allowing the email provider to track the user around the web.

What abuses / concerns do you see with the above system?
