### ISSUE TITLE
Buttons should have a visual indication when hovered over or focused.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#553]

**Comment by shane-tomlinson** [comment]
@clarkbw - I made the change pretty subtle, are there any best practices for how much of a change is reasonable?  This is to primarily give users who use the keyboard a visual indication that a button is selected - which Firefox does not currently do nearly as well as some of the competition.

**Comment by ghost** [comment]
@shane-tomlinson - In Firefox, the color change might be too subtle for some users - this is visible especially when 2 buttons are displayed on the page (e.g. Reset Password & Cancel) and one of them gets selected by pressing the Tab key. It looks better in Chrome and much better in Opera.

Another issue is that this change was implemented for the dialogs opened from the client but not also for diresworb.org manually opened in a tab by the user. In Chrome and Opera, the buttons are also displayed as selected with a outline so there is no problem there. In Firefox though, there is no visible feedback when the user selects a button on this page by pressing Tab.

**Comment by clarkbw** [comment]
We can merge the two styles that Chrome has and Firefox has for focus rings, we couldn't make this happen originally.

Chrome Button Focus
http://cl.ly/1B0d3j1B022G2G3g2u2b

Firefox Button Focus
http://cl.ly/0p0n3X3f2w0b2o3X150I

Though I'd like to have the button focus eventually be different than just the link focus ring as it's a bit weird to have a focus ring around a button.  I'd like to work on a darker blue color with a bit of an animated color pulse.

**Comment by shane-tomlinson** [comment]
Closing this issue, all buttons now have hover states.
