### ISSUE TITLE
chrome: Unable to post message to http://127.0.0.1:10002. Recipient has origin http://localhost:10001.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#555]

**Comment by lloyd** [comment]
http://www.whatwg.org/specs/web-apps/current-work/multipage/web-messaging.html#web-messaging

I believe this is an innocuous error message.  it sure is annoying.

I believe when the RP pings the relay frame with a postmessage before it's setup, the browser emits this message.

easy to reproduce and observe by adding console messages right before postMesage is invoked in include.js

I guess we could delay chan build, but this seems potentially risky...

**Comment by lloyd** [comment]
resolved in dev.  test at dev.myfavoritebeer.org
