### ISSUE TITLE
y u so hard, concurrency?

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#556]
test harness sporadic async errors and hard errors when dead node processes.

**Comment by lloyd** [comment]
this issue should address sporatic test failures.  for bind failures I'll improve the error output, but will not do the ephemeral binding.  that's probably a 4 star issue.

**Comment by lloyd** [comment]
sporatic errors are due to:

```
12:22 < lloyd> benadida: I'm launching all of these processes and then calling __heartbeat__ to check the health of the browserid (webhead)  process
12:22 < lloyd> that process goes and makes sure it can talk to the dbwriter and the keysigner
12:22 < lloyd> if the dbwriter is slow to initialize and bind, then the healthcheck fails
```
