### ISSUE TITLE
"keep me signed in" feature is in an inconsistent state

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#559]
In current dev, the keep me signed in feature doesn't not support an `allow_persistent` flag to provide the user with the option to "stay signed into this site".  we've agreed that the proper way to roll out the feature is subtly, by keeping it optional.  

The feature needs to be pulled from the current beta _or_ we must add a persistent flag.

**Comment by shane-tomlinson** [comment]
@benadida, @lloyd - I have started work on the front end to only display the "remember this selection" checkbox if "allow_persistent" makes its way to the pick_email_controller.  I can continue with this work we want to add this field to `navigator.id.get`.  

I also propose that we change the interface to the dialog_controllers getVerifiedEmail.  Right now its three parameters are "origin, onsuccess, onfailure", I propose that we standardize this with navigator.id.get and have it be "onsuccess, onfailure, options" where origin is an option in the options block.  This will allow us to pass additional flags such as allow_persistent.

**Comment by benadida** [comment]
@shane-tomlinson sorry didn't see this comment before finding you on irc. so after a few more minutes of thinking...
- let's leave getVerifiedEmail unmodified for now so as not to break existing code like pancake and the add-on, let's assume its options block is empty.
- let's add a get() method with params as you mentioned _plus_ explicit origin. origin has to be trusted, so best not to get into a situation where we have to inspect the options block from the page and make sure it doesn't contain an origin field, etc.

**Comment by lloyd** [comment]
In most of this discussion it sounds like you're focusing on the case where a user has multiple browserid accounts with different emails associated with them.  This is not a desired normal user behavior.  If you take that part away, and have a single browserid account per user generally, does the confusion subside? 

I've verified that the feature is functioning as designed, but I won't claim that it's not confusing.  Can we break this comment up into concrete different issues and open more granular issues?  I don't want to piggy back on this bug.
