### ISSUE TITLE
move bcrypt to webhead

### ISSUE THREAD

**Issue by fetep** [mozilla/persona#560]
bcrypt cycles should happen on the browserid process on the webhead, not the dbwriter process.  (in prod, we will have more cpu cores on the webheads than the secure webheads).

**Comment by lloyd** [comment]
taking ownership, 4 stars.

proposed implementation tactic:  

handle _update password_ api on the secure webhead, handle _auth_ api on the webhead.  in the case we have to migrate a bcrypt hash (#rounds), we'll forward to the secure webhead.  so a small fraction of bcrypt will run on sec webhead - only when we're _changing_ or _setting_ the password.

acceptable?

**Comment by fetep** [comment]
perfect.
