### ISSUE TITLE
Getting error on login post - on local and live sites

### ISSUE THREAD

**Issue by codeprogression** [mozilla/persona#563]
Has there been a change in the assertion?  I am getting the following errors when trying to log in...

Unable to post message to https://browserid.org. Recipient has origin http://[URL].

XMLHttpRequest cannot load https://browserid.org/verify?assertion=[HASH]&audience=[URL]. Origin http://[URL] is not allowed by Access-Control-Allow-Origin.

**Comment by benadida** [comment]
ah, we stopped allowing cross-origin request since that pattern doesn't really help you do the right thing (your browser could lie to you if there's greasemonkey or firebug installed). You should verify the assertion from your server, not client.

**Comment by codeprogression** [comment]
Makes sense. Thanks for the quick response. 

I have updated my code to process the assertion via my server, but I still get the _Unable to post message to https://browserid.org. Recipient has origin http://[URL]_ when opening the browserid login.

**Comment by lloyd** [comment]
hey @codeprogression - I believe that message is ugly, but harmless - it's tracked in issue #555

**Comment by codeprogression** [comment]
Great..thank you both!
