### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by Repox** [mozilla/persona#564]
I would really love to use this, but I believe that it would help me gain my users trust for this, if the service is presented to them in their own language.

Will browserid be localized at any point? And if so, where can I/we sign up to help translating?

**Comment by lloyd** [comment]
yo Repox!  yes it will be localized, but our first goal is a focus on finalizing features and scaling the infrastructure up.

If you'd like to help, please open an issue like `i18n: <locale you'd like to help translate into>` - here are some other volunteers:

https://github.com/mozilla/browserid/issues?milestone=12
