### ISSUE TITLE
i18n: da_DK

### ISSUE THREAD

**Issue by Repox** [mozilla/persona#565]
I can translate the project to danish.

**Comment by ozten** [comment]
@mathjazz can you create da_DK?

**Comment by mathjazz** [comment]
@Repox please let me know if you're still interested in localizing BrowserID to da_DK and I'll get you on board.

**Comment by lloyd** [comment]
closing down all internationalization issues.  l10n has begin, @mathjazz is coordinating the show, contact him directly to learn about contributing.

For now you can inspect current progress by updating your browser settings and visiting http://temporary_preview.myfavoritebeer.org/.  (click sign in to see the localized dialog)

NOTE: this url is temporary, and we will transition to "test.myfavoritebeer.org" in the coming weeks.

**Comment by Repox** [comment]
@mathjazz I'm still interested in localizing to da_DK.

**Comment by mathjazz** [comment]
@Repox Writing you an email...
