### ISSUE TITLE
heartbeat should not check backend servers

### ISSUE THREAD

**Issue by fetep** [mozilla/persona#566]
/**heartbeat** is intended to only check the local health of an individual server. The browserid process currently healthchecks dbwriter & keysigner to return a safe /**heartbeat**. 

If **heartbeat** fails, zeus won't route traffic to that node. If one of our backends are down (dbwriter or keysigner), we still want to accept traffic and gracefully handle a broken backend (showing some kind of maintenance/error page).

**Comment by lloyd** [comment]
Ok, I can make this change Monday.  @shane-tomlinson - we'll Need to coordinate and make sure the Frontend  code properly handles error responses from affected apis when keysigner, dbwriter, or database is sick.  

Also, we should have unit tests which ensure at the API level we're properly handling each possible scenario.

--lloyd

**Comment by lloyd** [comment]
@fetep so you don't even want me to ping the database?
