### ISSUE TITLE
User Profile info needed.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#569]
Start with name and photo.

**Comment by lloyd** [comment]
do you feel like this should be an issue against browserid?

**Comment by shane-tomlinson** [comment]
depends on whether it becomes part of the BrowserID codebase/dialog/flow.

**Comment by shane-tomlinson** [comment]
removing this from here, goes into separate repo.

**Comment by davereid** [comment]
For those looking for where issue is headed, the link to the repo is https://github.com/shane-tomlinson/browserid-profile
