### ISSUE TITLE
Document the cryptographic details, particularly in the browser-native case

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#57]
Firefox Sync has extensive documentation on its use of cryptography, explaining precisely how that cryptography allows the user to store data on the Sync server without allowing the Sync server to access that data.  BrowserID needs comparable documentation on its use of cryptography to keep the user's identity secure without relying on any third party.  This documentation should also explain where the various keys live, how the user recovers if they lose those keys (presumably by re-verifying their email address with a new key), how the user's browser gets involved, how multiple browsers with BrowserID handle the same email address, and other such issues.

**Comment by lloyd** [comment]
I think our new id-specs repo covers this:

https://github.com/mozilla/id-specs
