### ISSUE TITLE
improved file based configuration

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#582]
currently browserid is completely configured via environment variables.  There is a mechanism that allows a javascript file to be added to a deployment that will be evaluated in the context of `configuration.js`, however this method is error prone as the author of the file must understand the intricacies of configuration.js, and is prone to break upon updates.  Further, the author of the javascript file must duplicate information (like supply a URL and the corresponding hostname).

Ideally we would support an optional configuration JSON file that would be validated at runtime and could overlay settings.  Along with this we might choose to simplify configuration JS to more concisely express what ENV vars, and JSON variables are relevant, along with documentation of what they are intended to do.

**Comment by ozten** [comment]
via email

Fix browserid configuration.  Unlike the previous two projects, this is more into core code.  A key problem we have right now is managing software configuration on different deployments.  We have a programatic abstraction which extracts system configuration from the environment and server specific javascript configuration code that is directly eval'd by the configuration abstraction.  It's ugly,  here it is:

https://github.com/mozilla/browserid/blob/dev/lib/configuration.js

A better solution may be to have a configuration abstraction that holds all system configuration in a data structure.  This data structure perhaps includes:
- the name of the configuration parameter as referenced by code `config.get('some.config.param')`
- the name of the environment variable that can be used to specify the parameter
- documentation for what the parameter does
- a default value

This is perhaps a node reusable, perhaps it also allows:
- inclusion of a deployment specific json file that overlays the default configuration
- ability to output a fully functional configuration file with all params with their default values
- robust validation of configuration overlay ("no such parameter!")

It should be a drop in replacement for the existing api exposed by configuration.js
