### ISSUE TITLE
Design is not adapted to mobile on Android

### ISSUE THREAD

**Issue by digitarald** [mozilla/persona#584]
Tested on emulator and Nexus One, using our popup implementation in soup.

http://dl.dropbox.com/u/1864007/Screen%20Shot%202011-11-15%20at%204.06.35%20PM.png

I steal a few pixels for the popup layout. Landscape works fine.

**Comment by benadida** [comment]
yes, this looks fine for me on my nexus one. Are you doing anything special?

**Comment by digitarald** [comment]
As you see, the popup has some padding; which breaks the design. I will change the popup layout to accommodate for the expected width.

Close at will.

**Comment by shane-tomlinson** [comment]
@digitarald - the Android emulator is absolutely horrible at rendering, for some reason the font sizes in the emulator are about 50% larger than they should be.

**Comment by benadida** [comment]
so I _think_ some android native browsers changed behavior here. I'm seeing this behavior on myfavoritebeer.org on my phone, hadn't seen it before.

**Comment by shane-tomlinson** [comment]
@benadida, @digitarald - can you get this reproducing reliably on myfavoritebeer.org?  My phone is acting quite normal.

**Comment by benadida** [comment]
@shane-tomlinson yes I get this clipping reproducing regularly on my 2.3 phone.

**Comment by dclarke** [comment]
just as a thought the popup seemed larger than it needed to be, would it be better to err on the side of caution and go with something smaller that resembles a login box ?

**Comment by dclarke** [comment]
i thought the login pane could do with being much smaller in size.  It feels like it is trying to occupy the whole screen, which i wasn't really for.

**Comment by shane-tomlinson** [comment]
@dclarke I'm confused what you mean by the popup box seems larger than it needs to be?  On my phone, if I made the popup any smaller, it would be too small to be really usable.

**Comment by dclarke** [comment]
so the popup box has a lot of extraneous information in it, i feel that it just needs to have username, password and if you don't have those it resizes, or pops a new window where you can do initiate more complex actions, but the default window size feels like it's trying to take over the entire browser UI.

**Comment by shane-tomlinson** [comment]
Closing this in favor of #882
