### ISSUE TITLE
in dev, inclusion of include.js causes 8 transactions costing 300k

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#585]
That's 8 http transactions, including 300k of resources, at page load. 

This is a regression, down from 1 http transaction costing 11k.

https://img.skitch.com/20111116-jsen36a7pgiiwwn2ew4cfd6ata.png

I think this should block us from moving into beta with this.  thoughts? /cc @ozten @benadida @stomlinson @jbonacci

**Comment by benadida** [comment]
what happened there? Is there a reason this changed so significantly?

**Comment by lloyd** [comment]
Loading the relay frame at RP page load time is what triggers the inclusion of all these resources - the change made to support ios5.

There are plenty of ways to approach this, but the high level question remains, should this change in rp facing cost block us?  

I think the answer is yes -- and we need to figure this out before new features (which Shane and I should be able to do in the morn).

**Comment by benadida** [comment]
gotcha. Yeah the relay frame should be shrinkable to very minimal stuff.

**Comment by lloyd** [comment]
this is not nearly as severe as I made it out to be, apologies.  

I was looking at an RP that tries to get an immediate assertion - which requires pulls in _all our code_.  That happens at load time.  We do have a significant amount of optimization to do, but it's not right no the main codepath.

The full impact for RPs is instead 2 additional HTTP transactions for a cost of about 5k over the wire.  Not enough to raise the red flag for, and instead we can handle resource delivery optimizations in separate issues with lower priority.

Sorry for the pig little act, dudes.
