### ISSUE TITLE
Sign in window clips text on Android Devices Landscape view

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#586]
See screenshot.   Instantiating the sign in screen will clip text instead of wrapping it.

Ignore the custom font.

http://i.imgur.com/7hetc.png

Repro:
1) install android app that uses browserID for sign in (eg. Soup.apk)
2) click Sign in
3) Verify popup clips text on sign in window

Expected:
- text does not get clipped.   instead should be wrapped if too long

ActuaL:
- screen clips text in portrait mode.

**Comment by tonychung** [comment]
yep, does sound like a dupe of 584.

**Comment by benadida** [comment]
it's a dupe, and I've just recreated it on my phone, I'm not sure why it's showing up as a popup now, rather than a whole new window. Closing this one, duplicates #584.
