### ISSUE TITLE
Opera and Opera Mobile in Android "Relay frame could not be found" Problem.

### ISSUE THREAD

**Issue by ripulbd** [mozilla/persona#590]
Hi,

I have been testing BrowserID. My test stie works perfectly well with Firefox, Firefox Mobile, Chrome and Android Stock Browser. However, Opera and Opera Mobile seems to cause troube with both showing the following error:

"We are very sorry, there has been an error!

 To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below. 

Action: Establishing Relay 

Relay frame could not be found"

I tried closing the BrowserID window and closing the browser several times with no Result.

Any idea why it might cause?

Thanks,
Ripul

**Comment by benadida** [comment]
@ripulbd which version of Opera on which OS? It's working for me on dev.myfavoritebeer.org on opera 11 on mac os.

**Comment by ripulbd** [comment]
@benadida, Opera Version 11.52 Build 1100 on Windows 7. Cheers.

**Comment by benadida** [comment]
@jbonacci - so I'm confused because in #586 it says that it works in Android stock browser but design is clipped. Here you say it doesn't work. On my nexus s this works, but clipped design. Can you confirm exact behavior on android stock browser from your pov?

**Comment by shane-tomlinson** [comment]
Related to #596.

**Comment by lloyd** [comment]
we are unable to reproduce any problems in opera desktop OR opera mobile against current production (https://browserid.org/) or current development (https://dev.diresworb.org/)

please re-test and if you are able to produce any problems in either of these environments open a new bug with the specific browser version, the site that you were testing against, and the precise error you're seeing.

Thanks for contributing!
