### ISSUE TITLE
Stock Android 2.3 browser cannot find relay frame on dev.myfavoritebeer.org

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#596]

**Comment by benadida** [comment]
from my testing, it appears that things work fine on android 2.2 and 2.3 stock browser on dev server as long as the stock browser is set to be the default. If you have to pick another browser, on android 2.2 at least the popup replaces the main rp window, and you're out of luck. I'm wondering if I can recreate this problem in 2.3 by not having a default browser... let me try.

**Comment by benadida** [comment]
it appears that this is due to not having a default browser set, which then leads the popup to _replace_ the relying party window.

resolution: set a default browser.

**Comment by shane-tomlinson** [comment]
@benadida - ahhh, interesting.  Because earlier today, I did not have a default browser set on Android, and then when I set the default browser is when I went "hey, this is working now."

**Comment by lloyd** [comment]
@jbonacci - why were you able to reproduce this issue on 3 / 3 of your test devices?

Is it the case that this is 100% common in our QA environments but doesn't happen with actual users?  Pardon my ignorance of typical android user behaviors.

It sounds like we're saying this is a regression, but not one we care to fix?

**Comment by benadida** [comment]
I have a theory as to why this might be happening, but I need to test it out. I _think_ that I'm adding the iframe after document.body is ready but before onload has fired, which may mean that the browser considers the page not loaded, so when it exits out to the "choose browser" dialog, and the same browser is selected to load the iframe content, the browser may assume "i have no loaded page, I'm going to just load this in window.top".

Crazy theory, but that's really the only difference between production and beta: when the iframe is loaded.

I'm going to try and see if I can fully wait until onload event, which we should do anyways.
