### ISSUE TITLE
Submitting wildly invalid assertions to /verify causes a 500 server error

### ISSUE THREAD

**Issue by ianb** [mozilla/persona#598]
I accidentally pointed my mock assertions at BrowserID (things like the literal string "test@example.com", which isn't base64, JSON, JWT) and I get a 500 error.  It should return a proper error message.

**Comment by lloyd** [comment]
this is lame.  in general the verifier needs hardening and love.  it should return extremely helpful errors to end users, given this will affect our cost of supporting it significantly.

I say 4 stars.

**Comment by ianb** [comment]
Do the unit tests submit something that isn't valid JWT, or once
JWT-decoded is not valid JSON?
On Dec 5, 2011 8:07 PM, "jbonacci" <
reply@reply.github.com>
wrote:

**Comment by lloyd** [comment]
Both.

--lloyd

**Comment by ianb** [comment]
This breaks on browserid but works on diresworb: 

```
curl https://browserid.org/verify -d 'assertion=xxxx&audience=localhost'
```

I'm guessing that means it is fixed.

**Comment by lloyd** [comment]
Will roll into prod on thurs

--lloyd
