### ISSUE TITLE
Need to decide on algorithm and keylength for domain key

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#600]
currently our domain keys are all RSA 1024.  We should decide if we want to stick with RSA or move to DSA and what the keylength should be.  I've run the numbers and here is the cost on an example machine: 

RSA2048 - certification 419ms - verification 137ms

DSA2048 - certification 69ms - verification 248ms

These times are on a 2.5ghz linux box under node 0.6.0.

Given this, I suggest DSA 2048.

/cc @benadida @vmunix

**Comment by benadida** [comment]
some more info on this: from some pre-print of a paper I've seen, the library we're using becomes a somewhat inefficient around 1300-1400 bits for the modulus. So moving to node-bigint should provide us with a significant improvement, especially on RSA2048 certification, which is a full exponent operation (whereas DSA exponents are 256 bits.)

I need to think of the easiest way to patch in node-bigint when it's available.

My recommendation, given that verification is really our choke-point, is to go with RSA2048 and ensure that we use node-bigint ASAP.

**Comment by lloyd** [comment]
verification is something we can and should aggressively move to RPs.  This is interesting in its interplay with your claim that verification is the choke-point.

what sort of native optimizations do you expect would be most effective in reducing the cost of certification, either with RSA or DSA?

**Comment by benadida** [comment]
I guess I'm just not sure we're going to move verification to RPs very quickly. If we manage to do that, then it's the other way around. But in any case there are _far_ fewer certifications than verifications, right?

I think moving to node-bigint or a similar library that does big-integer math in C is going to be our biggest win. Moving the whole verification to JS will probably gain us 10-20% more, but I don't think much more.

**Comment by lloyd** [comment]
based on the estimates I did, we can assume 8 certifications and 40 assertions per active users per day (assuming we have serious uptake on the short lived cookie move - which my intuition and experience tells me is a pipe dream).

Further assuming we get zero uptake on RP verification of assertions we're looking at DSA2048 costing us 85% of RSA2048.

I make two assumptions here in favor of RSA and don't consider here any further native optimization on either side.

That's the full reasoning that went into my original suggestion, but you make the call.  Maybe there are factors to consider other than compute cost and you're in a better position to make those.

**Comment by lloyd** [comment]
oh, "estimates I did" are here: https://github.com/mozilla/browserid/wiki/Scaling-to-1M

**Comment by lloyd** [comment]
oh, and given the hardware we've thrown at the problem, I suggest that native bigint ASAP might be premature, let's wait for actual load testing to prioritize.

**Comment by benadida** [comment]
Interesting, thanks for the numbers.

There is a slight crypto reason to prefer RSA over DSA for the high-value key, which is that DSA appears to a bit weaker if we're not super careful with our randomness. RSA is more forgiving.

So if we're within 10% of the performance, I would probably favor RSA. Your numbers are a bit over that, so I think it's worth trying what happens with node-bigint, because I think the improvement in RSA will be more than that in DSA.

**Comment by benadida** [comment]
@lloyd sounds good, we can wait.

**Comment by lloyd** [comment]
@benadida k.  note here that I'm quoting numbers with node 0.6 - @vmunix suggested that this move might not be too high risk.  That may be the zero work optimization that we want to prioritize.  cost is significantly higher with 0.4 - which lacks modern V8

RSA2048 it is.  do you agree with the dependant issue?  GH-599 ?

**Comment by benadida** [comment]
I do agree, absolutely, great point regarding #599. I think that's high priority for the next train. My recommendation is to have a creation_date on the key, and have a server-issue cutoff: all certs before X need to die.

**Comment by lloyd** [comment]
domain_key_creation_date in session context sounds fine.

**Comment by vmunix** [comment]
My only comment is that we'd need to heavily test use of node 0.6.x or node-bigint, but at least with 0.6.x that testing effort opens up a bunch of niceties aside from _just_ improved V8 performance.

**Comment by lloyd** [comment]
again, given hardware, I'm okay with leading with loadgen.  The more low risk optimizations we have in our back pocket, the better.  We'll be on 0.6 at some point, the only question is when, and I'll leave that one to @vmunix.

RSA2048 on 0.4.x will give us a good worst case, and that's what we need right now to make testing meaningful.

If I had a nickel for everytime "optimize later" paid off...
