### ISSUE TITLE
build pagemod-ready API

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#601]
we need to expose a JS API in the BrowserID dialog that lets chrome-level apps do what they need to do, including fully control BrowserID functions. This API, if well defined, can then be stable.

Specifically:
- navigator.id.channel can be defined by the chrome to provide an alternative message-passing channel. This is already done and should stay.
- navigator.id.internal.getSilent(origin, email, {options}, callback): generate an assertion for the given origin and email, with options, and the callback to be called with the assertion.
- navigator.id.internal.setPersistent(origin, email): set the persistent login for this email address at this origin.

The first (navigator.id.channel) should be exposed by the chrome to browserid.org, while the other two (internal.*) should be exposed by the browserid.org to the chrome.

**Comment by shane-tomlinson** [comment]
@benadida - I am implementing this API with the following modifications:

navigator.id.internal.getSilent has no `options` block. Are there currently any additional options that can be passed in?  If there are, I will pass add the options block, but if not, I will wait until we need that functionality to add it.

navigator.id.internal.setPersistent has no `email` field.  The email associated with a site is associated whenever the user gets an assertion, the only additional functionality needed that is normally provided by the dialog is the ability to set the persistent flag.

finally, adding

navigator.id.internal.get(origin, {options}, callback) - The name I am not tied to.  Get an assertion using the dialog.  This is for the case such as Soup where navigator.id.channel may not be injected in to the DOM in time, but the site still needs the ability to start the dialog process.

The pull request will follow.

**Comment by shane-tomlinson** [comment]
@benadida - I was not clear on the reason reason we do not want to mirror the navigator.id.get API and augment it with setPersistent.  That API is already well defined and from the point of view of the native app or addon, the requirements are the same.  The only thing that changes is the channel, which is an abstraction that should be hidden from the user anyways.

**Comment by benadida** [comment]
@shane-tomlinson if we make it the same API, there is a very strong chance that we confuse internal and external API. Also, there are a number of checks that our external API should do that our internal API need not do. In particular, I don't think we should be tying the internal API to the navigator object.

Regarding the options block: requiredEmail is probably an option we want to pass to getSilent.

**Comment by shane-tomlinson** [comment]
@benadida - ah, I think we crossed thoughts, I do not want to recreate a new "navigator.id" with ".get" and ".getVerifiedEmail" for use by addons or native clients, but have those two functions with the same signature/semantic meaning living in a separate namespace.  Your suggestion above of using navigator.id.internal works, I was also thinking we could remove it completely from the navigator object and place it under BrowserID.internal or something similar.

**Comment by benadida** [comment]
oh I suggested navigator.id.internal, didn't I? duh. So yeah, I would recommend BrowserID.internal.

As for mirroring the calls... I think you're right that it makes sense. Just assume silent:true.
