### ISSUE TITLE
Nintendo 3DS browser unsupported

### ISSUE THREAD

**Issue by AntoineTurmel** [mozilla/persona#618]
When trying the sign in button at myfavoritebeer.org, I got the message "We're sorry, but currently your browser isn't supported."

There is more information on the 3DS Browser here :
http://3dbrew.org/wiki/Internet_Browser

**Comment by shane-tomlinson** [comment]
@GeekShadow - Thanks for the feedback - the minimum requirements for BrowserID to run include window.postMessage and window.localStorage.  If the 3DS' browser does not support these HTML5 features, we cannot offer support for it at this time.
