### ISSUE TITLE
use RFC3339 formatted timestamps

### ISSUE THREAD

**Issue by max-mapper** [mozilla/persona#62]
In the Verified Email Protocol documentation timestamps are described as `<format TBD>`. I'd highly recommend using RFC3339/ISO8601 formatted timestamps for a few reasons:
- Lexicographically sortable
- Easy to read
- Easy to parse in JavaScript
- Easy to create in JavaScript: `JSON.stringify(new Date())` 
- Supported in many other newer RFCs (like OStatus)

**Comment by benadida** [comment]
We can't do this without breaking the current JWT/JWS spec, so I'm going to close this issue for now and leave this as part of our Spec Issues: https://github.com/mozilla/browserid/wiki/Spec-Issues
