### ISSUE TITLE
"Relay frame could not be found" Problem in Opera and Opera Mobile in Android 

### ISSUE THREAD

**Issue by ripulbd** [mozilla/persona#621]
Hi,

I am re-submitting the error with a more detailed explanation on what caused the error and hope to get help from you to resolve the problem.

I am using Opera Version 11.52 Build 1100 on Windows 7 and Opera Mobile Version 11.50.ADR-1111101157 on Samsung Galaxy S2 with Android 2.3.3. I have tested with myfavoritebeer.org on both browsers and it worked well enough. Now I've set a local site and wants to integrate it with the BrowserID. I used the following code: 

---

<html>
<head>
<title>
SP1 with BrowserID Support
</title>
<link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

<style type="text/css">

</style>

</head>
<body>

<div class="intro">
  <h2> Click the following image to sign in using BrowserID</h2>
  <p/>
  <a id="partyStarter" href="#"> <img src="sign_in_blue.png" alt="BrowserID"/></a>
</div>

<script src="jquery-min.js"></script>

<script src="https://browserid.org/include.js"></script>

<script>
  $(function() {
    $("#partyStarter").click(function(event) {
      event.preventDefault();
      navigator.id.getVerifiedEmail(function(assertion) {
      
        if (!assertion) {
          alert("couldn't get the users email address!");
        } else {
          // Now we'll send this assertion over to the verification server for validation

          var url = "https://browserid.org/verify"
          var data = {
            assertion: assertion,
            audience: window.location.protocol + "//" + window.location.host
          };

          $.ajax({
            url: "https://browserid.org/verify",
            type: "post",
            dataType: "json",
            data: data,
            success: function(data, textStatus, jqXHR) {
              //do something....
            },
            error: function(jqXHR, textStatus, errorThrown) {
              //do error thing.....
            }
          });
        }
      });
    });
  });
</script>

## </html>

This worked perfectly well with Firefox, Firefox Mobile, Chrome and Android Stock Browser. However, Opera and Opera Mobile seems to cause troube with both showing the following error:

"We are very sorry, there has been an error!

To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below.

Action: Establishing Relay

Relay frame could not be found"

I tried closing the BrowserID window and closing the browser several times with no Result.

Any idea why it might cause?

Thanks,
Ripul

**Comment by alchemycs** [comment]
I'm also getting this on desktop Opera.

Was testing using [browser stack](http://browserstack.com) and getting the same error. I thought it might be something to do with them, so downloaded Opera 11.52 build 1100 onto my mac (snow leopard 10.6.8) and still getting the same error.

The sites use SSL if that makes a difference.

**Comment by ghost** [comment]
I got the same issue on Opera, but only from https://beta.myfavoritebeer.org/ (it went ok while using this client with http or other clients).
The displayed error is:
"We are very sorry, there has been an error!
 To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below. 

Action: Establishing Relay 
 Relay frame could not be found"

**Comment by wfwalker** [comment]
this is duplicated by https://bugzilla.mozilla.org/show_bug.cgi?id=708086

**Comment by lloyd** [comment]
please retest against dev.diresworb.org or dev.myfavoritebeer.org

**Comment by lloyd** [comment]
closed - We've tested dev against opera and opera mobile.  Please re-open if you still find issues.
