### ISSUE TITLE
Erred dialog flickered when selecting the "This is not me" link

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#622]
OS: Windows XP
Browser: Firefox 8.0.1

STR:
1. Open http://beta.myfavoritebeer.org in the browser.
2. Click on the Sign In button.
3. Sign in with a BrowserID account.
4. Click on the "This is not me link".

If the account has less than 5 emails associated to it, the "Use a different email" string is displayed in plain format for 1 second, then the right dialog is opened.

If the account has 5 or more emails associated to it, the "Use a different email" string is displayed in plain format, the scroll bar from the emails list disappears and the whole emails list is displayed on the dialog. The right dialog is opened after 1-1.5 seconds.

**Comment by ghost** [comment]
On http://beta.myfavoritebooze.org, the "Always sign in using this email" option stays still in that flicker where the other elements are changed. In the 5 emails or more case, this looks quite badly.

**Comment by shane-tomlinson** [comment]
I fixed this today with the fix for #850.

**Comment by shane-tomlinson** [comment]
Checkin c6837a6822fd49a96fd57ca0d34126defce55808 takes care of the flickering when hitting "this is not me"
