### ISSUE TITLE
BrowserID popup is blocked by Firefox

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#628]
reproducible on: Firefox 9/ Nightly

steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/ in FF 9
2. Click on Login/register link

expected behavior:
browserID popup opens

actual behavior:
Firefox blocks the browserID popup.

screencast: http://screencast.com/t/MadMFhlM0

Error console:  

Error: b is null
Source File: https://browserid.org/include.js?_=1321919917885
Line: 37

http://screencast.com/t/PC6ZIXfZvMK

**Comment by krupa** [comment]
This is blocking all QA efforts on Android for AMO :(

**Comment by andymckay** [comment]
I'm pretty sure this is the CSRF fetching code in AMO.

**Comment by clouserw** [comment]
Sounds like this is an AMO thing.

**Comment by sebilasse** [comment]
will this be corrected?
all our browserid windows are blocked by ff popup blocker (which is activated by default)
