### ISSUE TITLE
Safari LocalStorage

### ISSUE THREAD

**Issue by mtaksrud** [mozilla/persona#63]
Hi,

It seems the file https_browserid.org_0.localstorage in Safari/LocalStorage on OS X 10.6.8 is being set to -rw-r--r-- (644) which could potentially make it possible for other users than <user> to access the sqlite database and get the generated private key from the ItemTable. Shouldn't this file have a -rw------- (600) setting?

-morten

**Comment by lloyd** [comment]
You scared me there for a second.  It looks like the LocalStorage directory itself has 700 set:

```
[lth@lloydpro ~]$ ls -ld ~/Library/Safari/LocalStorage
drwx------@ 53 lth  staff  1802 Jul 14 21:37 /Users/lth/Library/Safari/LocalStorage
```

Closing this issue, if it were really possible for unpriv'd users to get at each other's local storage it would be a pretty serious bug in Safari!

**Comment by mtaksrud** [comment]
ah,... I forgot to check the parent directory, I just noticed that most files in the directory used 600. I'm sorry I scared you for no goof reason, but it looked like a serious bug at first glance. :) Good luck with everything. It looks great!!! ...and it is really needed!
