### ISSUE TITLE
Inconsistent behavior when logging into beta.myfavoriteshow.org multiple times

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#637]
OS: Windows XP
Browser: Firefox 8.0.1

STR:
1. Open http://beta.myfavoriteshow.org/ in the browser.
2. Log in several times with both emails that are already associated to BrowserID and that aren't (I did this for about 40-50 minutes).
3. Log in with the same email that is associated to BrowserID several consecutive times.

At step 3 I encountered 3 different behaviors (listed in the order they reproduced in):
Behavior 1: A verification email was sent to the used email address and the user had to click a verification link and enter a new password to sign in (I suppose behavior would be expected if the email wasn't already associated to BrowserID).
Behavior 2: The user is requested to enter his password and log in (I suppose this is the right behavior, isn't it?).
Behavior 3: The user is directly signed in when clicking the "sign in" button without having to enter a password (might be expected since it reproduced after behavior 2).

**Comment by lloyd** [comment]
this is desired behavior!  closing out
