### ISSUE TITLE
http_forward doesn't handle get params

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#644]
http_forward is only getting exercised for POST requests.  When one tries to use it for a request with get params (like a verifier POST with get params funkily stuffed in the path), then it fails.

**Comment by zaach** [comment]
I had to make this [change](https://github.com/zaach/browserid/commit/e6bfd5d70b0feede2ebf2ce76d5e43c6ccb2c0a3#L4R41) for the router branch (along with some header forwarding.)

**Comment by zaach** [comment]
Get params are now handled since the rounter was merged into dev.
