### ISSUE TITLE
browser.id/dialog takes too long to load

### ISSUE THREAD

**Issue by globau** [mozilla/persona#65]
https://browserid.org/dialog/dialog.html takes over 8 seconds to load for me - see http://i.imgur.com/eMx6d.png

**Comment by lloyd** [comment]
We're shipping development resources right now, we need to add a publishing step to combine and minify.  Forthcoming!

**Comment by M66B** [comment]
Maybe there should be a message displayed in the dialog that the performance will be improved in the meantime. Before you know it people have the perception that BrowserID is slow.

**Comment by lloyd** [comment]
Fix by monday

--lloyd

**Comment by lloyd** [comment]
3c5adc69f468036c2a432b8d52b1f9e722ef70dc repairs the jmvc compress step, a prerequisite to fixing this.

**Comment by lloyd** [comment]
fixed, in production.  give it a test?  better?

**Comment by M66B** [comment]
Yes, I already noticed it got a lot better! Thanks.

**Comment by lloyd** [comment]
w00t.
