### ISSUE TITLE
SEC7111 error on beta.myfavoritebooze.org in Win7/IE9

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#664]
Because beta.myfavoritebooze.org is http and the communication frame is https, ie9 is having a fit.

"SEC7111: HTTPS security is compromised by https://diresworb.org/communication_iframe 
beta.myfavoritebooze.org"

**Comment by benadida** [comment]
Didn't we see this issue in the past and you found a way to resolve it? There isn't any actual issue with embedding HTTPS inside HTTP. It's the other way around that sucks, and we don't do it.

**Comment by shane-tomlinson** [comment]
@benadida - we saw it when we were using StealJS inside of the relay frame.  The solution there was to remove StealJS.  Are we adding scripts via a document.write or appending script tags dynamically inside of the communication_iframe?

**Comment by benadida** [comment]
@shane-tomlinson is it possible that we're still using stealjs for the comm iframe? It looks like it's possible given /resources/views/communication_iframe.ejs.

**Comment by shane-tomlinson** [comment]
@benadida - I've completely removed StealJS altogether, it is no longer even in the repo.  I'll do some digging and see what I can find.
