### ISSUE TITLE
browserid login process can get wedged if you close window before content load

### ISSUE THREAD

**Issue by gerv** [mozilla/persona#668]
Steps to reproduce:

1) Go to a site implementing BrowserID using browserid.js from browserid.org. E.g. https://bugzilla-stage-tip.mozilla.org, if you have access to that
2) Click "Sign in" button
3) As soon as window pops up, and before content is loaded, close pop-up window (e.g. with Ctrl-W)
4) Click "Sign in" button again

Expected: new popup window appears
Actual: nothing happens; no JS errors either

People can easily accidentally close popup windows. The code in browserid.js which runs when I click "Sign in" should be able to cope with this.

**Comment by lloyd** [comment]
what browser, @gerv?

**Comment by globau** [comment]
i can reproduce on firefox nightly 2011-11-30, chrome 15, and opera 11.

**Comment by gerv** [comment]
I was using Firefox 9 beta, I think. But as globau says, it's widely reproducible.

Gerv

**Comment by jrgm** [comment]
Just noting this is still an issue. I was using FF13 on osx and can easily reproduce this, but not as easily with Chrome 20/osx. I was using dev.123done.org as the RP.

**Comment by jrgm** [comment]
@seanmonstar put in a fix here, and it covers this case.
