### ISSUE TITLE
welcome email for new users

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#672]
I'm scheduling some time with Mary Trombley to work on some value statements to explain BID to new users. I'll post a draft here.

@benadida - What's the process of getting new issues starred?

**Comment by benadida** [comment]
@skinny97214 we do bug triage every Thursday and assign priorities. You are welcome to attend, or if you feel strongly about an issue, star it yourself and we'll only change it if we must prioritize other issues. I think I need to grant you privileges, so I'll do that now....

**Comment by lloyd** [comment]
four stars.  I'd like to widen this to consider all of the emails that we send out.  Especially the verification emails could use some design and thought.  Perhaps the two goals can be combined...

**Comment by skinny97214** [comment]
Here's a quick rewrite of the verification email. One problem of our current text is that too many things are automatically linkified. It's too visually busy and makes it hard for the user to quickly see which one should be clicked. I'm proposing we remove the user's email address and the second instance of the RP's URL.

http://cl.ly/0z3x312G3w071A1H1I1L

## New copy

Thanks for verifying your email address. This message is being sent to you to complete your sign-in to
http://dev.myfavoritebeer.org.

Finish registration by clicking this link:
https://dev.diresworb.org/add_email_address?token=N3WSH08SnHtR1lkcojwLeiSeKLbN1tnReo73JrgpOalWiwsi

If you are NOT trying to sign into this site, just ignore this email.

Thanks,
BrowserID
(A better way to sign in)

**Comment by lloyd** [comment]
How's this grab you:

```
Thanks for verifying your email!  This message is being sent to you to complete your sign-in to {{site}}.

To finish, open this link: {{link}}

If you are NOT trying to sign into this site, just ignore this email.

Thanks,
BrowserID
(A better way to sign in)
```

**Comment by lloyd** [comment]
btw: you can also provide an HTML version if you feel this could be better (we send both and the client chooses what to display)

**Comment by skinny97214** [comment]
@lloyd Do you know why gmail wouldn't be showing the HTML version?

**Comment by lloyd** [comment]
@skinny97214 cause there isn't one yet!  it's yours to design :)

**Comment by max-mapper** [comment]
@skinny97214 (it felt good to type that zip code -- i miss PDX) you can get nodemailer to send multipart/mixed messages (e.g. text + html) by setting the `html` property on the message (right now ya'll are just setting the `body` property) 

example: https://github.com/andris9/Nodemailer/blob/master/examples/example_smtp.js#L25

also here is a ruby mail generation thingy that works in gmail for reference https://github.com/codeforamerica/aedmapper/blob/d10a72bd964554a5f4af9a0de644fb6868f47b79/mail_fetcher/aed_response.rb

**Comment by skinny97214** [comment]
@lloyd Works for me.

**Comment by skinny97214** [comment]
Hey there @maxogden I went and searched the internal phonebook to see if we'd hired you yet!

**Comment by jessevondoom** [comment]
Going through the fun of HTML mail and gmail now — fair warning a lot of the CSS will be stripped out in the gmail interface so It's good to test in native gmail as well as a few different mail clients if possible. A few decent bookmarks I grabbed:

http://kb.mailchimp.com/article/how-to-code-html-emails
http://www.campaignmonitor.com/templates/

You're probably hip to all this already, but they've been helpful here...

**Comment by ghost** [comment]
Verified by signing up from beta.myfavoritebeer.org. This is the email currently sent to the user:
"Thanks for verifying your email address. This message is being sent to you to complete your sign-in to
http://beta.myfavoritebeer.org .

Finish registration by clicking this link:
https://dev.diresworb.org/add_email_address?token=N3WSH08SnHtR1lkcojwLeiSeKLbN1tnReo73JrgpOalWiwsi

If you are NOT trying to sign into this site, just ignore this email.

Thanks,
BrowserID
(A better way to sign in)"

**Comment by shane-tomlinson** [comment]
@skinny97214, @lloyd, @sawyerh - is this now taken care of with the new emails?
