### ISSUE TITLE
Adopt a "no trailing whitespace" policy?

### ISSUE THREAD

**Issue by jrburke** [mozilla/persona#673]
This is partly a style thing, so it is understandable if you want to just close it out:

It would be useful if the project adopted a policy of not committing files with trailing white space. If someone is working on just one project, it probably is not an issue, but for some of us open source hackers, other projects have a "no trailing whitespace" policy, and to conform have set up environment tools to avoid it, and the end result is that tooling may be applied to browserid code.

I ran into this recently since my editor automatically trims trailing whitespace on file save, so the code diff was bigger than it needed to be. If the files were already white-space trimmed then this would not have been an issue.

Here are some resources to configure this:
- [in git](http://stackoverflow.com/questions/591923/make-git-automatically-remove-trailing-whitespace-before-committing)
- [in vim](http://vim.wikia.com/wiki/Remove_unwanted_spaces) see near bottom for autoconfig
- if using Komodo/Komodo Edit, go to Preferences, Editor, Save Options and check "Clean trailing whitespace and EOL markers".

If you need me to research info for a particular dev setup, please let me know.

**Comment by shane-tomlinson** [comment]
@jrburke - I am all for it, I've set up both git and vim as in those instructions.  @benadida, @lloyd?

**Comment by benadida** [comment]
sounds good, set up my emacs with a pre-save hook as per http://www.emacswiki.org/emacs/DeletingWhitespace#toc3

what's the git way to make this warning a repo-stored config param? Any way to do that?

**Comment by lloyd** [comment]
+1

**Comment by lloyd** [comment]
many ways to skin this cat.

**Comment by jrburke** [comment]
@benadida: github allows setting up a service hooks after a push to github, mostly for notifying on commits, but AFAIK, not a way to do a pre-commit hook, since it is just receiving pushes of commits. A pre-commit needs to be configured locally by the developer in their clone or maybe even their global config.

From what I can tell in my global git config, if I have [color] diff = auto, then I seem to get some nice red blocks when i do a git diff showing trailing whitespace.

So it may just fall to document in a style guide or "how to contribute" page on what is expected, and hopefully caught in pull requests first to help enforce the behavior.

**Comment by lloyd** [comment]
I suggested writing a unit test and @benadida and @shane-tomlinson _freaked out_.  it was fun.

**Comment by MarcusPope** [comment]
Don't mean to bother you all, but I found this thread while googling for a way to DISABLE the clean eol whitespace setting in Komodo IDE.  I use markdown for documentation on my projects and MD uses two whitespace characters at the EOL to signify a hard return (br tag) so I needed to disable the setting for my environment.

As an alternative suggestion, you might want to use this instead - `git diff --ignore-space-at-eol`

This will make your diffs cleaner and you can add it to your gitrc.  I realize you all don't use markdown, and I totally appreciate clean line endings in a code file, just thought I'd throw in that alternative way to "skin the cat."

Cheers!

**Comment by shane-tomlinson** [comment]
Closing since this has become the de facto mode of operation.
