### ISSUE TITLE
provide guidance on how to fall back if browserid.org is down

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#674]
maybe have devs check

```
if (navigator.id)
```

after loading the library?

**Comment by lloyd** [comment]
This would be catastrophic.  Given that we are committing to more than 3 9s of uptime, is it worth calling out in our documentation "what to do when the service is down?"  The service shouldn't go down, smart devs could handle this if they wanted...

closing this down, re-open if you think this is unfair.
