### ISSUE TITLE
Getting Access-Control-Origin-Access error

### ISSUE THREAD

**Issue by codeprogression** [mozilla/persona#68]
When verifying assertion, I am getting the following error:

> `XMLHttpRequest cannot load https://browserid.org/verify?assertion=[assertionstring]&audience=[mysite] Origin http://[mysite] is not allowed by Access-Control-Allow-Origin.`

I was able to verify assertions until about 11pm MDT.  I am assuming it has to do with this [commit](https://github.com/mozilla/browserid/commit/965054bd2ceefa4d717605c5dd5be014e2f7367d) but I may be wrong.

**Comment by codeprogression** [comment]
Duplicate of #67. Seems to be fixed now.

**Comment by lloyd** [comment]
thanks for the report, codeprogression!
