### ISSUE TITLE
statsd binds too many ephemeral UDP ports under load

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#680]
@fetep and I observed consuming > 500 fds when under load.  this is crazy.

**Comment by fetep** [comment]
this is actually fixed in node-statsd master, but the sha we're pointing at in package.json doesn't include it (because it's of a fork with a patch we need).

**Comment by lloyd** [comment]
Can we rebase the patch on top of orig and break down the upstream authors door with a pull request, using our own fork in the meantime?

--lloyd

**Comment by fetep** [comment]
oh, interesting, it's not quite that simple.  re-read the description of this pull request:  https://github.com/sivy/node-statsd/pull/6  and we're using that version of the code.

if we use the released 0.0.2, we can pass in a socket in connect-logger-statsd, but we have to figure out where we need to close the socket (so node exits during the unit tests, for example) in the connect middleware.

**Comment by lloyd** [comment]
This branch needs testing and cleanup, but may be what we want.

https://github.com/lloyd/node-statsd
