### ISSUE TITLE
analyze and maybe implement mysql connection pooling

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#683]
now that we can generate real load, it looks like we've finally uncovered a bottleneck in our query serialization imposed by using a single mysql connection.  We should take an hour and slip this round robin into stage to see an actual difference:

https://gist.github.com/1414568

If we do see a favorable change (and it should be _significant_ if initial data is correct), then we should extend that implementation a bit and include it.

@fetep++ /cc @vmunix @benadida

**Comment by shane-tomlinson** [comment]
@lloyd, @gene1wood, @benadida  - Has this been done already?  If not, should it still be labelled 4*, it has been open for 9 months.

**Comment by lloyd** [comment]
not a useful issue.  when we want to switch and focus on scaling we'll do it, and we'll make careful data driven performance enhancements.  shutting her down.
