### ISSUE TITLE
Login sessions inconsistency

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#689]
OS: Windows 7
Browser: Firefox 8.0 (default settings)

STR:
1. Open https://diresworb.org/ in the browser and log in.
2. Open http://beta.myfavoritebeer.org/ in a second tab in the same browser and log in.
3. Open http://beta.myfavoritebooze.org/ in a third tab in the same browser.
4. Log in without checking the "Always sign in using this email" checkbox.
5. Open http://beta.myfavoriteshow.org/ in another tab of the same browser and add an email to the newsletter list.
6. Open http://carrera.databits.net:9999/ in a new tab of the same browser and log in.
7. Restart the browser.

The user is logged out of http://beta.myfavoritebeer.org/, http://beta.myfavoritebooze.org/ and http://beta.myfavoriteshow.org/. The log ins to https://diresworb.org/ and http://carrera.databits.net:9999/ are kept though.

**Comment by benadida** [comment]
closed, now covered by #760.
