### ISSUE TITLE
Mismatched passwords work on myFavoriteBeer

### ISSUE THREAD

**Issue by johnjbarton** [mozilla/persona#69]
Go to http://myfavoritebeer.org/
Click the signin button
create a new login
enter mismatched passwords
click return on the mac keyboard
Surprise! you are logged in. you don't feel very confident of this new service....

**Comment by lloyd** [comment]
@benadida Did we loose proper disabling of commit button until passwords are identical in port to jmvc?

@johnjbarton Thanks for the report!

**Comment by johnjbarton** [comment]
I got an email from browserid.org:

Error encountered while attempting to confirm your address. please try again. (error message: unknown)

Obviously the email should not be sent, the dialog should not close while the passwords don't match.

**Comment by benadida** [comment]
fixed in checked in code, to be released soon.

**Comment by lloyd** [comment]
@benadida reading between the lines, shall I do some testing and take this live?

--lloyd

**Comment by benadida** [comment]
yes, I won't commit my half-baked CSRF protection yet :)

**Comment by lloyd** [comment]
Oh yeah, next time, include "issue #69" in your commit msg and the big will be updated automatically.  Unlike "closes #69" the issue won't actually be _closed_

--lloyd

**Comment by lloyd** [comment]
K, do csrf on feature branch and I'll push to prod in the next 16 hrs.

--lloyd

**Comment by lloyd** [comment]
let's not close issues until they're live in production (or as soon as we get beta servers stood up, it'll be on beta).

**Comment by lloyd** [comment]
and now, live in production.
