### ISSUE TITLE
too many links in emails

### ISSUE THREAD

**Issue by clarkbw** [mozilla/persona#692]
Hey, I wasn't sure if I should jump in on #672 or open a new one.

Our emails need to be a bit more action oriented and assume that people aren't reading any of the text.  Right now we include a couple of links in the email (where you were signing up from) when we should really only have a single obvious link for people to click on.  I'd suggest making all the other information non-links or have a different style (assuming HTML).

If we wanted to have extra information about where you tried to log in and other text that explains the email I'd suggest we put that "below the fold".

**Comment by lloyd** [comment]
any concrete suggestions for the new emails sent on beta?  Just go to beta.myfavoritebeer.org and add an email address or create a new account.

**Comment by lloyd** [comment]
to be resolved in issue #696
