### ISSUE TITLE
Clicking an older password reset message gives a confusing error

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#695]
Steps:
1) Click the forgot password link, send a reset email
2) Wait a couple of minutes
3) Click forgot password again, send another reset email
4) In your email client, click the _older_ message and open that link

The error message that appears is:

"There was a problem with your signup link. Has this address already been registered?"

Which is very confusing. It should ideally say something like:

"The password reset link you used is expired, and another one was sent to your email. Please check your email again and click on the newer link"

**Comment by shane-tomlinson** [comment]
@vthunder - From the information that I receive from the backend, I do not know whether the link has been previously used, whether a new link has been sent out, or whether the link is just plain invalid.  From my understanding, we do not keep a list of previously used links anywhere, so this information may not even be available to us (@benadida, @lloyd, am I correct in this?)

**Comment by callahad** [comment]
Update: Clicking the link twice now just strands me on an empty page.

**Comment by vthunder** [comment]
Btw... what are the possibilities?

a) you have an old code,
b) you have a code that's not that old, but was invalidated by a newer one,
c) you're copying and pasting the URL and typoed it somehow,
d) you're mucking around trying to screw up the service (or maybe just poking around for fun).

I'd assume (a) or (b) since they seem much more likely than the other two. You could say something like:

"The password reset link you used is expired (or invalid). Do you have multiple email confirmations in your inbox? use the newest one! Or [get another email][] sent to you."

Except say it with half the words.

It'd be nice if you could track code invalidations for some time to distinguish (a) from (b) (and have different messages based on that). People on slow connections/slow email relays are might try a few times, and only the last email (which they might not have received yet) is the valid one.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
