### ISSUE TITLE
Reset password truncates email

### ISSUE THREAD

**Issue by andymckay** [mozilla/persona#699]
On the thank you screen for reset password, only the first two characters of my email address is shown.

OS: 10.7.2
Fx: 9.0

Screencast: http://screencast.com/t/z1jClfuu6f

**Comment by jrgm** [comment]
I bumped into this myself, and that screencast was awesome in noticing how to do it. 

Question for andy: you did get the confirmation email to the address you selected, right?

Anyways, how to reproduce:
1) go to https://browserid.org (or diresworb.org)
2) if you're logged in, then log out.
3) click sign in
4) click "forgot your password"
5) type the beginning for an address you've used before (so form history will bring up a select list)
6) type down arrow; hit TAB; click on 'Reset Password'
7) the beginning of the address before "down arrow" is shown as the "confirmation email to <begin match>"

This was also 10.7.2, and Fx: 10.0a2 (I can do this on browserid.org or diresworb.org).

**Comment by andymckay** [comment]
Yes I got the email.

**Comment by shane-tomlinson** [comment]
@andymckay - thanks for the screen cast, and @jrgm, thanks for the precise steps, I've seen this and did not know what caused it.  Excellent.
