### ISSUE TITLE
migrate to mysql

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#71]
port db.js over.

**Comment by tj** [comment]
:(

**Comment by ghost** [comment]
I don't get it... shouldn't this be a library, not a project with a blessed database backend?

**Comment by tj** [comment]
I think it's more app than it is library. I hate open id because of all the different sites, so this caught my eye. With open id I couldn't even remember which damn site I created my account on because they are all so insignificant

**Comment by lloyd** [comment]
Ok, this bug is an odd place to talk about this, but it's where the party is at, so whatever.

The browserid repository contains a couple different things:
- _the browserid server_ - a node.js server which implements a web services api, stores a record of users, the email addresses they've verified, a bcrypted password, outstanding verification tokens, etc
- _the verifier_ - a stateless node.js server which does cryptographic verification of assertions.  This thing is hosted on browserid.org as a convenience, but people using browserid can choose to relocated it if they want to their own servers.
- _sample and test code_ - to test the above
- _the browserid.org website_ - the templates, css, and javascript that make up the visible part of browserid.org
- _the javascript/HTML dialog & include library_ - this is include.js and the code that it includes, the bit that someone using browserid will include.

This bug is specifically about moving the browserid server from sqlite to mysql.  The reason we'll start with mysql is cause' it's a trivial move from what we have now, and has mature and well understood replication and performance.  We might consider something else (mongo? riak?) at a later point, but given all the interest in browserid, the goal right now is to harden and scale up the system so folks can use it, their users can be happy, and we can learn, iterate, and refine.

good?

**Comment by tj** [comment]
mysql just makes it annoying to contribute, that's why the frown. A little abstraction layer should take care of that though.

**Comment by lloyd** [comment]
Yeah, agree, I loathe loosing the near zero config setup we've got now.  I'll shoot for preserving a no config persistence impl for local dev.  Stay tuned.

**Comment by lloyd** [comment]
the proposed approach: http://irclog.gr/#show/irc.mozilla.org/identity/1176

**Comment by tj** [comment]
cool man sounds good, depending on the abstraction layer it doesn't even need to be SQL really if it's just arbitrary stuff like `User.get(id, fn)` blah blah
