### ISSUE TITLE
iOS5.0.1: can't validate email into diresworb.org

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#711]
I'm having issues signing into stage and production on Iphone IOS5.0.1, safari.

See screenshot: http://i.imgur.com/OwRf5.png.  
unfortunately, no helpful console data from xcode.

repro
1) launch iphone safari on iOS5.0.1
2) visit www.myfavoritebeer.org or beta.myfavoritebeer.org
3) sign in with an existing account
4) Verify after typing in password, error is thrown  (url shows diresworb.org/sign_in#)

Expected
- successful sign in and redirect to RP

**Comment by tonychung** [comment]
setting to 3 stars, since no one can seem to reproduce on their iOS 5.0.1 devices

**Comment by tonychung** [comment]
Reset password breaks also for the same reason.

**Comment by shane-tomlinson** [comment]
@tonychung - are you still having this problem?

**Comment by tonychung** [comment]
yes, i still have this problem on my iphone 4, iOS 5.0.1 (9A405).  client quickly throws an error saying

Action: Authenticating User
Network Info: POST: /wsapi/authenticate_user
Response Code - error
Error Type: Bad Request

**Comment by shane-tomlinson** [comment]
@tonychung - is this still still a problem?  I just a shiny new iPod with 5.0.1 and have no problem.

**Comment by tonychung** [comment]
I'm consistently hitting a CSRF violation on my iphone 4 now.    This is after clearing cache, history, cookies on safari, and visiting any RP that uses dev, stage, or prod browserid servers.   

Action: Authenticating User
Network Info: POST: /wsapi/authenticate_user
Response Code - error
Response Text: Bad Request: CSRF violation
Error Type: Bad Request

**Comment by shane-tomlinson** [comment]
This is caused by #835 - cookies being disabled.  Closing as duplicate.
