### ISSUE TITLE
When trying to access http://diresworb.org from Opera, it doesn't get redirected to https

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#712]
OS: All
Browser: Opera 11.6

STR:
1. Try to load http://diresworb.org/ in the browser.

Expected Results:
 It gets redirected to https://diresworb.org/.

Actual Results:
 "Could not connect to remote server" is displayed.

**Comment by shane-tomlinson** [comment]
It appears that redirects are not yet set up on diresworb.org:

```
Shanes-MacBook-Pro:dialog stomlinson$ curl http://diresworb.org
curl: (7) couldn't connect to host
```

**Comment by ghost** [comment]
Forgot to mention: the redirect went fine in Chrome 15 and Firefox 8.0/8.0.1.

**Comment by shane-tomlinson** [comment]
@petef has taken care of this.
