### ISSUE TITLE
The BrowserID dialog can be scrolled vertically unnecessarily

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#715]
OS: All
Browser: All

STR:
1. Open a BrowserID client in the browser.
2. Click on the Sign In button to open the BID dialog.

The dialog can be scrolled vertically although there is no hidden information for which the scrolling might be necessary.

**Comment by shane-tomlinson** [comment]
@ioanab - I am unable to reproduce this, is it any particular browser, mobile, etc?

**Comment by ghost** [comment]
@shane-tomlinson - This seems to be an intermittent issue. I reproduced it several times on 
Opera 11.6 + Windows XP
Chrome 15 + Ubuntu 11.10 x64
Chrome 15 + Windows 7. 

I am not sure what stops it from reproducing but what did it a few times was restarting the OS.

**Comment by lloyd** [comment]
WFM
