### ISSUE TITLE
Android: Submit button not working, second tap results in empty assertion

### ISSUE THREAD

**Issue by digitarald** [mozilla/persona#717]
Environment: android (soup).

Pre-requirement: When `registerController` was called before and soup falls back using `$('body').controller('dialog')`

**User stories**:

Logged out:
- Open fresh browserid popup without any cache/cookies
- Input email, press _Go (Enter)_, input password, press _Go (Enter)_
  - _Expected result_: Email confirmation step
  - _Actual result_: Nothing changes
- Press submit button
- `getAssertion` gets called **without** assertion

Logged in:
- Open popup logged in, getting the _"Sign in using"_ step
- Press _Sign in_
  - _Expected result_: Finish process
  - _Actual result_: Nothing changes, styles slightly adjust (link style)
- Second tap on submit
- `getAssertion` gets called **without** assertion

**Comment by tonychung** [comment]
blocks the Soup Application.

**Comment by digitarald** [comment]
Other errors popping up from time to time:

After submitting a second time, the animation fades (which does not work in the stories above)and my logs start to fill with: `Uncaught Pickemail controller instance has been deleted at https://browserid.org/dialog/production.js:35`

The whole issue might be related to my fallback to re-registering the controller the controller on the channel when my JS is injected too late.

**Comment by digitarald** [comment]
More logs as it might help to find the issue. This is for story 1.

`12-06 15:50:09.720: E/Web Console(3558): Unsafe JavaScript attempt to access frame with URL https://apps-preview-dev.allizom.org/en-US/firefox/users/login from frame with URL https://browserid.org/sign_in. Domains, protocols and ports must match.
12-06 15:50:09.720: E/Web Console(3558):  at null:1
12-06 15:50:09.720: E/Web Console(3558): Uncaught relay frame not found at https://browserid.org/dialog/production.js:38
12-06 15:50:09.760: E/Web Console(3558): Uncaught TypeError: Cannot read property 'method' of null at https://browserid.org/include.js:37`

**Comment by digitarald** [comment]
Calling `controller.stateMachine();` fixes it.

Full revive snippet for reference:

```
var controller = '$' in window && $('body').controller && $('body').controller('dialog');
// Script might got injected after load
if (controller) {
    console.log("getVerifiedEmail channel.registerController restarted");

    // added via stomlinson
    try {
        controller.stateMachine();
        console.log("getVerifiedEmail stateMachine success");
    } catch (e) {
        console.log("getVerifiedEmail stateMachine failed " + e);
    }

    channel.registerController(controller);
}
```

**Comment by shane-tomlinson** [comment]
closing since https://github.com/mozilla/browserid/pull/736 addresses this.
