### ISSUE TITLE
diresword.org returns "You are offline" (Stock browser, Android 2.3.4)

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#719]
Steps to reproduce:
1) ensure that stock browser is set as default
2) got to http://beta.myfavoritebeer.org
3) Sign in (popup goes to https://diresworb.org

Expected:
Dialog to either sign up (if not already) or to pick browserid to use;
RP window switches to logged-in state after that is done.

Actual:
Browser shows error message: "You are offline". [But on a few very
rare occasions, this has worked correctly, but ~1 in 25 times].

Phone:
  Galaxy S II
  Internet (stock browser) 2.3.4
  Android 2.3.4 GINGERBREAD XWKI4

**Comment by lloyd** [comment]
I saw this while trying to dev locally last night.  i also saw this in google chrome when starting the browser up while offline, then switching to online.

Maybe this disabling is too aggressive.

What is this check designed to catch?  the case where include.js is in your browser cache, lots of resources are there, but you are offline?

Would handling a failure to get session_context be a more effective means of providing good user feedback when bid servers aren't reachable?

**Comment by lloyd** [comment]
stomlinson, shall we just remove the offline check and close this issue?

**Comment by shane-tomlinson** [comment]
@lloyd - I think that is a prudent choice for now.

**Comment by lloyd** [comment]
stealing

**Comment by jrgm** [comment]
not seeing with issue anymore with browser 2.3.4 on android 2.3.4 Galaxy II SE (which was showing me the offline UI before).
