### ISSUE TITLE
Mozilla Security Review of browserid

### ISSUE THREAD

**Issue by ygjb** [mozilla/persona#72]
The security review is in progress, tracker bug at https://bugzilla.mozilla.org/show_bug.cgi?id=644776

**Comment by csuciu** [comment]
The tracker bug is still open.

**Comment by ygjb** [comment]
Indeed; the security review is ongoing.  There is content located at https://wiki.mozilla.org/Security/Reviews/Identity/browserid and we currently have a 3rd party performing a security review of the BrowserID implementation, and the cryptographic components.  Once that is completed we will update the security review documentation!  If you have any questions or concerns, please feel free to contact us at security@mozilla.com

**Comment by lloyd** [comment]
we've started and will continue reviewing the software, this bug isn't useful.  woohoo.
