### ISSUE TITLE
Sign in doesn't work on Android devices

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#723]
Device: Motorola Droid2
OS: Android 2.3.3
Browser: Native (set as default)

STR:
1. Load http://beta.myfavoritebeer.org in the browser.
2. Click on the Sign In button.
3. Enter your credentials and sign in.
4. Select an email and sign in.

After the user selects an email and clicks the Sign In button, the BrowserID dialog is closed but the user is not actually signed in. When the user tries to click the Sign In button again, the dialog is opened for less than a second than it disappears. 

Notes:
I noticed bug 708 has almost the same title, but I decided to file a separate bug since this behavior is completely different from what is described there.

This issue is intermittent: I used the device for an hour before seeing it happen.

**Comment by ghost** [comment]
After reproducing this issue on the same environment with http://beta.myfavoritebooze.org/ (keep me signed in was checked), I restarted the device to tried to log in again. When opening the client in the same browser after the restart, I was logged in with the email I was trying to log in with before the restart. When clicking "This is not me" then logging in with credentials for a second, the email list from the first account was displayed.

I could only reproduce this once, so it will probably be very difficult to reproduce it again.

**Comment by shane-tomlinson** [comment]
@ioanab - Does this problem still occur if you select the Android browser to be the default browser?

**Comment by ghost** [comment]
@jbonacci , @shane-tomlinson - I followed James' steps and tried to reproduce this issue again but it didn't reproduce. Still, if you read the bug description and the following comment, I mentioned there that when I first reproduced the bug, the native browser was set as the phone's default browser and that this is an intermittent issue reproducing very rarely.

**Comment by shane-tomlinson** [comment]
@ioanab - thanks for re-checking, I'm going to label this a 2 star for now and if it happens again, we'll bump it up.  I am wondering if any of this whack behavior had to do with setting up the new hardware for the beta servers last week.
