### ISSUE TITLE
The user is sometimes asked to confirm his email although it is already associated to BrowserID

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#724]
STR:
1. Open http://beta.myfavoriteshow.org.
2. Enter an email address already associated to BrowserID and click on "next".
3. Click on "verify".
4. Click on the "verify email" button in the opened dialog.

The "Check your email" dialog is displayed and a confirmation email is sent to the user although his email is already associated to BrowserID. 

This issue reproduced 4 times in 3 days of testing BrowserID, 3 times on Android 2.3.3 with the native browser and once on Windows 7 with Firefox 8.0.1.

**Comment by ghost** [comment]
@jbonacci - I didn't re-verify through the email because I didn't want to loose the initial account. What I did was refresh the page and try again. At the third try, the right dialog was displayed and I could log in with that same email without re-verifying it.

**Comment by shane-tomlinson** [comment]
@ioanab - can you give this a try again to see if this still occurs?

**Comment by ghost** [comment]
@shane-tomlinson @jbonacci  - I have tried to reproduce this issue several times, both on http://beta.123done.org/ and on http://123done.org/, and it didn't reproduce at all.

You can mark it as closed and if Catalin or I see it again at some point, we'll just reopen it.
