### ISSUE TITLE
email verification link should ask for confirmation

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#73]
and be a POST with CSRF protection.

(thanks Noah Mendelsohn)

**Comment by lloyd** [comment]
are you suggesting adding another click into the sign up flow?  How about we move password selection onto the landing page, entry of a password can be implicit confirmation.

**Comment by benadida** [comment]
@lloyd sure, we could do that, although that seems like a larger change than what we strictly need to secure that process. Let's add the confirm click to secure the system first, and then I'm happy if, in our UX redesign, we put the password selection on that latter page.

**Comment by lloyd** [comment]
@benadida - you referred to this issue in a recent email.  I think it was mistakenly closed.

If we don't move password selection after link click and we don't add a confirmation risk, I'm having a little trouble understanding exactly how much risk that adds to the system.  With my limited creativity for black hat thinking, I really don't see this as a significant hole.  

What attack exactly does a verification link without CSRF protection allow?
