### ISSUE TITLE
Signing in already known email will prompt to confirm your mail address

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#732]
the screen that tells you an email was sent to your address flashes and goes away in these steps.     Im guessing its a timing thing.

Reproduces on any Desktop browser and Mobile browser.  More apparent when testing on stock android though.

repro:
1) goto beta.myfavoritebooze.org
2) sign in with a working account (me@email.com)
3) logout of site, then sign in again
4) dialog box recognizes your previous account (me@email.com).  click "Use a different email"
5) type in a completely bogus email (thisisabogusemail@email.com).  click Add
6) dialog changes to "Check your email".  click the link in "If this is a mistake, just ignore the sent email and use another email address."
7) enter in your first, approved email (me@email.com), and Add.
8) watch the dialog box, and verify it will flicker the "check your email" message before signing in.  

Expected:
- Does not show the "Check your email" account message since you are already a approved account

**Comment by ghost** [comment]
Verified as fixed on Windows XP + IE 8.

**Comment by jrgm** [comment]
This works for on all browsers. Using the STR that tchung notes at the beginning of this bug, when I try to re-add 
my address, I get the "You already own that address!" tooltip on Win7 or Win32 current Safari, Chrome, FF, Opera, IE
and Mac Safari, Chrome, FF, Opera. 

However, a javascript error is thrown on at least IE8/WinXP, Chrome16/Mac, FF9/Mac (probably all):

 function addEmail(email, callback) {
    var self=this;
    if(user.getStoredEmailKeypair(email)) {
      // User already owns this address
      tooltip.showTooltip("#already_own_address");
-->   callback(false); // exception thrown on this line
    }
    else {
      ....

where 'callback' is 'undefined'.

Chrome dev tools report it as 

helpers.js:128Uncaught TypeError: undefined is not a function
  addEmail                      helpers.js:128
  addEmail                      addemail.js:52
  onSubmit                      page.js:52
  f.event.handle               jquery-1.6.2.min.js:17
  f.event.add.i.handle.k   jquery-1.6.2.min.js:16

**Comment by shane-tomlinson** [comment]
nice catch @jrgm!
