### ISSUE TITLE
Justify asking for a password

### ISSUE THREAD

**Issue by eevee** [mozilla/persona#733]
Both browserid.org and myfavoritebeer.org proclaim that BrowserID spells the end of passwords.

But after clicking the first email confirmation link, I'm asked to invent a password.

I understand why this happens (though it's unclear how often I'll need to enter it, or if a password is meant to be part of the native browser implementation), but it's a bit misleading to anyone who doesn't know or care about federated auth.

A few words explaining the need for a password on my passwordless login would do wonders.  :)

**Comment by benadida** [comment]
fair point @eevee, thanks for prodding us on this. We'll think about the best wording to set up the right expectation. And to answer your question: you'll need to type the password once every 2 weeks right now. When this goes native, that will probably be a longer period without password typing.

**Comment by eevee** [comment]
Sure thing; I threw myfavoritebeer at a few non-tech friends and they all noticed this.  I see subsequent emails don't require more passwords, though, which is fantastic.

(Expanding on the native thought: I wouldn't really expect to need a password at all for the native implementation.  The status quo is for password manager to remember my passwords _and_ synchronize them everywhere indefinitely, no reconfirmation ever needed.  Could reuse the master password for BrowserID, or take a page from SSH keys and allow an optional passphrase per key, with the choice to type it either every time or once per browser launch?)

**Comment by skinny97214** [comment]
I see exactly where you're going with your comment @eevee  and I'm fighting for the users happiness with every engineering decision.

Here's the way I'm thinking about the problem: Auth makes use of two things: something you have and something you know. We're looking into how we can make use of both of those.

Logging on from the same hardware (the thing you have) will give us a certain level of certainty that you are who you say you are. This is the most common case and the one we're optimizing for. I'm hoping to improve our security in such a way that re-entering the password is a very infrequent task.

We have a couple of cases:

1) Even in the case of only logging in from one computer, we'll need to look ahead to RPs that need a reauth before checkout. This is to prevent a child from buying themselves a nice new ipad without your consent. Or, someone who steals your computer could do the same. Reauth is dependent on having a key. Password is the most familiar of the options.

2) Users will be entirely dependent on BrowserID as your only method of accessing accounts. Therefore, you must be able to log in from other computers and mobile phones, not all of which you'd be willing to sync e.g. a public computer. We're thinking about rolling Sync and BrowserID into one coherent product with one set of credentials.

So, the value is more one password to rule them all. Still, this is a vast improvement and there are other good features coming down the pike.

**Comment by eevee** [comment]
Oh, I understand the problem of a shared or stolen computer; I was just making the point that the Firefox experience _right now_ is to let me choose if passwords are remembered forever.  For what it's worth I'd be much more comfortable with the ssh-agent style of entering a master password once at startup.

But this ticket is really about the state of browserid right _now_, where a password is requested for password-less login, and it may not be immediately obvious what that password is _for_.  I had a hard time even explaining it aloud to a friend, as I kept tripping up and saying "email password".

**Comment by skinny97214** [comment]
Looks like I misunderstood your comment then. Apologies.

What are you looking for when you say "justify the password?" An explanation of how the system works?

**Comment by eevee** [comment]
Yeah, something as brief as possible to explain what the password is actually for.

Consider having no idea how BrowserID works, and going to try it out on myfavoritebeer.  You provide an email address, click a confirmation link, have to select a password, and then are logged in.  On the surface this doesn't look any different from a traditional password login, and conflicts with the footer, which describes the system as "a snazzy _passphraseless_ login flow".  It only starts to make a difference on your _second_ login—but if you're underwhelmed then you might not get that far.

**Comment by eevee** [comment]
Worth reopening, then?  :)
