### ISSUE TITLE
Registering a new BrowserID account throws an error

### ISSUE THREAD

**Issue by ragavanmoz** [mozilla/persona#737]
I can't reproduce this now, but this is what happened.

Tried to create a new account. Clicked on the verification email in my email. Landed on a page that asked me to enter a password for the account. Hit Enter and got the following error:

Action: Completing User Registration
   Network Info: POST: /wsapi/complete_user_creation

   Response Code - error

   Error Type: Bad Request

Reloaded the page and tried it again and it worked just fine.

**Comment by ragavanmoz** [comment]
https://browserid.org

**Comment by lloyd** [comment]
can't reproduce, let's keep an eye on it and reopen with high prio if it shows up again
