### ISSUE TITLE
adding a second email to browserid can fail.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#74]
I was adding the browserid plugin to my wordpress blog just now and came across an issue adding a new email to my browserid account.  I am able to replicate this on both myfavoritebeer.org and shanetomlinson.com, same error.

When adding a new email address to the account, the dialog says:

"One Moment Please...
We're adding this email to your account, this should only take a couple seconds."

But it stays there.

Looking at the network request for this, the following happens:

GET request:

https://browserid.org/wsapi/add_email?email=set117%40gmail.com&pubkey=-----BEGIN%20PUBLIC%20KEY-----%0AMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALuRLmcr8XxBoa530LXyAC7qcLHEmtlQ%0AhLyEfuhgf29sO0nfZq0%2BnwWH937%2BmTRUjKOYF6fAVAuJx5g0tjbF7VMCAwEAAQ%3D%3D%0A-----END%20PUBLIC%20KEY-----%0A&site=myfavoritebeer.org

response:

400 Bad Request

response body

"Bad Request: requires authentication"

Now, the bizzare thing was, it said that I was logged in.  It showed my email address in the browserid.org as being logged in, it showed "stomlinson@mozilla.com" as my login in the dialog, but I should have had two more logins shown.

When I logged out and said "this is not me" and then re-logged in, it showed all three of my logins.

I am thinking this is probably originally a bug in the wordpress login, but it seems that it is possible to put browserid in an inconsistent state.

To fully replicate, try using the wordpress browserid plugin from (obviously) a wordpress blog.  Log in to browserid.org.

**Comment by lloyd** [comment]
I can definitely reproduce this.  wtf?  /me digs.

**Comment by lloyd** [comment]
ok, did some digging and I think I have a simplified way to reproduce the problem:
1. go to myfavoritebeer.org and click signin
2. if you do not have local keypairs set up (no emails in the list) log in
3. select an email and click the blue sign in button which dismisses the dialog and signs you in successfully
4. go into your browser and delete the cookie (`browserid_state`) for browserid.org
5. got to myfavoritebeer.org and click signin
6. click the _add a new email_ link
7. type an email
8. notice you're stuck!  notice you get a `400` response to the add_email wsapi

Analysis and proposed fix:

This happens with the cookie set with browserid expires, or is invalidated.  In the dialog we should detect this and vary the screen transition at the time the user clicks on _add a new email_.  If not authenticated, they'll get redirected to a screen which asks for the new email address and browserid password, if they _are_ authenticated, they'll get just asked for the email.

that'll solve the problem for now, and we should include this flow in our big ol' UX diagram for when we get more of faaborg's attention on this.

**Comment by benadida** [comment]
@lloyd we should think about whether we want to let the user go ahead if they're not signed in. I understand why we're doing it, but it feels a bit odd that, after clearing your cookies, you can still sign in to sites with the keys in there. For multi-user computers, that could be problematic.

**Comment by shane-tomlinson** [comment]
I agree with Ben, esp with regards to the multi-user computers, which is still very common in developing countries (Argentina for instance has an internet cafe on every 2nd block in the major cities).  Quite frequently, the user logs out of the machine, the cookies are all cleared for the browser, but I am not sure if this includes localStorage or not.  Is this something that we could enforce, where if the user opens a browserID dialog and the appropriate cookies are not there, we clear their localStorage?  

An alternative and I feel it would be much safer from a security perspective - Is there a way where instead of automatically putting all keypairs in localStorage, if we ask the user on login if they are on a shared machine, and if they are, put their keys in sessionStorage instead?  That way when they log out, their key pairs are automatically deleted and there is no way some third party could come in and steal their credentials.

**Comment by lloyd** [comment]
In order to have this discussion I think we need to know how frequently must users re-authenticate to BrowserID?

**Comment by lloyd** [comment]
bump.  

What's the longest we'll let a user continue to use browserid without re-typing their password?

I suggest for first run, 24 hours.  Subsequently, 2 weeks.

thoughts?

**Comment by lloyd** [comment]
bump.

**Comment by shane-tomlinson** [comment]
@lloyd, are you suggesting for the first login, make this 24 hours and any subsequent login, 2 weeks?  I think this is great if we know the device is a personal/non-shared device.  Re-entering a password after 24 hours will help the user remember what their initial password selection, and perhaps on a weekly basis afterwards.  I am worried that 2 weeks may be too long, but is there any research on this?  What I am most worried about though is just assuming that the user will be on a private device - this is definitely not the typical case outside of the first world.  My personal thoughts is that there should be some sort of way to explicitly state that the user is on a shared/private device and take action accordingly.

**Comment by lloyd** [comment]
Yeah, the 24 hour requirement was to make users eat their peas and re-type their password within a day to help memory.

re 2 weeks vs 1 week?  I don't care, let's let someone else make this decision.  If its > 1 week, I don't mind forcing the user to be authenticated all the time (type in their password more often).  

w.r.t. shared computers, we should move this to a separate issue.  I think our solution should simply be a _opt in_ checkbox that says "keep me signed in on this computer".  In the case it's not checked, we issue an uber-short lived cert (5min max) and send a bit to the RP inside the assertion.  we need to move this off to a separate issue.

**Comment by lloyd** [comment]
let's leave things at 2 weeks, let's force the user to relogin when cookie is gone
