### ISSUE TITLE
get include.js takes 832ms to complete

### ISSUE THREAD

**Issue by Marlena** [mozilla/persona#742]
Initially this looked like an intermittently occurring problem with writing an addon review.  I now think it happens when someone changes their email for browser id.  
1. Open amo while logged into browserid as marlena.compton
2. Logged into browser id with amo.testing
3. searched for adblock plus
4. clicked write review
5. wrote the review and was redirected to this page
   https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/reviews/add
6. added a title and star
7. clicked "submit review"
8. The page hangs for a while after clicking submit the review
   https://skitch.com/marlenacompton/gxi9f/add-a-review-for-adblock-plus-add-ons-for-firefox

So I opened firebug to get more info about the request:
https://skitch.com/marlenacompton/gxsyk/while-waiting

Here's info from after the page completed.  include.js took 832ms to load:
https://skitch.com/marlenacompton/gxsyh/adblock-plus-reviews-add-ons-for-firefox

Link to the old bugzilla bug.  https://bugzilla.mozilla.org/show_bug.cgi?id=708970

**Comment by Marlena** [comment]
This screenshot has a bit more information about the timeline of the request: https://skitch.com/marlenacompton/gx296/includejsrequest

**Comment by lloyd** [comment]
vmunix can we get worldwide monitoring of include.js response times?

**Comment by vmunix** [comment]
yes, yes we can.

**Comment by vmunix** [comment]
Setting up Watchmouse monitoring of https://browserid.org/include.js explicitly. Will report back once we have some data collected.

**Comment by stephendonner** [comment]
I've seen this take as long as _13 seconds_, while debugging why our Selenium tests are timing out.  Is there any hope of putting this and other assets on a CDN?

**Comment by shane-tomlinson** [comment]
@vmunix - do we have any monitoring on this now?

**Comment by callahad** [comment]
Is this still an issue? @gene1wood does ops have a plan for our move to AWS that would let us go ahead and close this?

(Whoops, didn't mean to close just then.)

**Comment by gene1wood** [comment]
@callahad Do you mean do we have a plan to ameliorate the response time or to monitor include.js once we're running out of AWS?

**Comment by callahad** [comment]
@gene1wood Just interested in the monitoring bit right now.

**Comment by gene1wood** [comment]
I don't have any specific plan to change our monitoring of include.js in relation to the AWS move. We can establish whatever monitoring is useful either now or after the move.

**Comment by jedp** [comment]
We have a number of specific bugs filed in [type:performance](https://github.com/mozilla/browserid/issues?labels=type%3Aperformance&page=1&state=open).  Let's pursue those and bring down load times, especially for mobile.
