### ISSUE TITLE
IE9/Win7 - Logout of beta.myfavoritebooze.org then page refresh shows previous login info.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#752]
Logging out of beta.myfavoritebooze.org seems to have no effect in IE9.  

Steps to reproduce:
1) Go to beta.myfavoritebooze.org
2) Sign in, clicking on "always sign in using this email"
3) Enter a booze
4) Click signout
5) Refresh the page - presto, still signed in!

**Comment by shane-tomlinson** [comment]
@lloyd - after logout and page refresh in IE9, the browser is calling /api/whoami and getting a 304 (not modified) response, which makes IE9 always think it is logged in.  Can we set the API requests to be non-cachable?

Marking 5 star as this is a regression.

**Comment by lloyd** [comment]
fixed: https://github.com/lloyd/myfavoritebooze.org/commit/d1461a2790b83a671ddcd02623af4fbe785f8ded
