### ISSUE TITLE
cancel forgot password is not working on required email flow.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#754]
As this is a regression, marking 5 stars.

**Comment by shane-tomlinson** [comment]
Steps to reproduce

1) go to diresworb.org, log out.
2) go to beta.myfavoriteshow.org, enter in one of your already registered email addresses.
3) click buttons to get browserid dialog.
4) click "forgot password"
5) click "cancel" - oops, nothing happens!

**Comment by shane-tomlinson** [comment]
@lloyd - I was able to cherry pick the above commit into both beta and prod to fix the problem.

**Comment by lloyd** [comment]
now this issue is really closed.  merged into current production (train-2011.12.01) and beta (train-2011.12.08)

**Comment by jrgm** [comment]
Verified on stage environment (beta.myfavoriteshow.org,diresworb.org):
Windows XP: (Safari 5.1.2, Firefox 9.0.1, Chrome 16, Opera 11.6, IE 8)
Windows 7 32-bit: (Safari 5.1.2, Firefox 9.0.1, Chrome 16, Opera 11.6, IE 9)
OSX 10.7.2: (Safari 5.1.2, Firefox 9.0.1, Chrome 16, Opera 11.6)
Ubuntu 11.10: (Firefox 9.0.1, Chrome 16)

Change password link works, and cancelling out of that dialog returns
to previous email/password entry screen. Cancelling all the way out
of the dialog shows the "Oops! looks like ..." message in beta.myfshow.org
