### ISSUE TITLE
encourage picking strong, unique passwords

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#755]
Since we (the internets) have trained users to use the same password for everything, they will likely use that when they make the browserID account the first time. We need two things
-  big prompts 
- a password strength indicator.

**Comment by skinny97214** [comment]
Some mockups of a color coded password strength indicator. I've grayed out the button and made it unclickable until the password passes at least into the yellow stage.

red http://cl.ly/3P09421y2f0U0M2R0O2v
Password strength: too weak

yellow http://cl.ly/1T18461R1v0n1x380I3s
Minimally secure password

green http://cl.ly/0v381e361l2P2G200n1i
Good job! That's a secure password.

**Comment by skinny97214** [comment]
This is the finely-tuned password interaction from Simple. Let's talk about what our standards for A-D, and F unacceptable are.

http://www.youtube.com/watch?v=xwDcaOQlqLs

**Comment by BYK** [comment]
Changing the border color of the password field is a good idea though it doesn't provide the necessary emphasis in my opinion. It should be something more visible than that.

**Comment by sawyerh** [comment]
I have a working prototype of this on my password-strength-ux branch (https://github.com/sawyerh/browserid/commit/c1e9c233a98004ce08f1e2cad10560a0481c34dc)

Right now it's only checking the length — wasn't sure what standards you want for each level (weak/minimal/strong).

**Comment by sawyerh** [comment]
Here's a quick video demo of what I have at the moment - http://www.screenr.com/rtl8

**Comment by shane-tomlinson** [comment]
This should be added to browserid-stories. Closing here.
