### ISSUE TITLE
myfavoritebeer.org 500 Internal Server Error on all get/set requests

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#757]
Affects dev, beta, and prod.

**Comment by shane-tomlinson** [comment]
Using firefox 8.0.1

Reproducible steps:

1) go to myfavoritebeer.org
2) Open network console
3) sign in using BrowserID
4) Watch /api/get request - 500 Internal Server Error with XML message - "XML Parsing Error: no element found Location: moz-nullprincipal:{5eb3797b-6b67-8a45-9d30-2c4d11086416} Line Number 1, Column 1:

^"
5) Try setting beer name
6) Watch /api/set request - 500 Internal SErver Error with XML message - "XML Parsing Error: no element found Location: moz-nullprincipal:{78e5a984-e6f7-a040-a8fc-5657827a5ac5} Line Number 1, Column 1:

^"

**Comment by lloyd** [comment]
restarted the heroku process.  fixed for now.  hmmm.
