### ISSUE TITLE
make "logout" work better

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#760]
There is plenty of confusion about what logging out means on an RP.  Let's rethink this and solve it once and for all.

**Comment by skinny97214** [comment]
@lloyd Where do we stand on this now that the feature triple play is out? Do we lack anything that would keep us from closing this bug?

**Comment by shane-tomlinson** [comment]
@lloyd - can we mark this as fixed with the new logout feature?

**Comment by lloyd** [comment]
I think we can close this, we now have a consistent implementation.  @skinny97214 has opened a separate issue to add a "logout everywhere" feature.

**Comment by ericelliott** [comment]
> @skinny97214 has opened a separate issue to add a "logout everywhere" feature.

Can you reference that issue?
