### ISSUE TITLE
detect browser speed and downgrade keysize if needed

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#762]

**Comment by shane-tomlinson** [comment]
I'm digging this approach, it could mean that we could support some older devices like my ancient iPod Touch that always times out when generating a key - even using DSA.

**Comment by benadida** [comment]
after some discussion with bsmith, I'm starting to think we may be able to move to 1024-bit keys for everyone, given how short-lived our keys are, and given that they're only signing keys.

**Comment by benadida** [comment]
barring issues raised on mailing list, action here is to downgrade all keys to 1024-bit, which should be plenty.

**Comment by lloyd** [comment]
done in train `2012.04.11`
