### ISSUE TITLE
do crypto in web worker

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#763]

**Comment by lloyd** [comment]
if we do do this we should start key gen right when dialog opens.  This will help on ios and android quite a bit.

--lloyd

**Comment by benadida** [comment]
oooh, very interesting. For all email addresses?

**Comment by lloyd** [comment]
That said, I would prefer that we start by analyzing the tradeoffs, then go implement...

--lloyd

**Comment by lloyd** [comment]
re pre-emptive keygen - yah, do it when we expect we'll have to generate one anyway.  if we don't need it (user cancels or uses an email we didn't expect), we cancel webworker and throw it away.  if we do need it, and we didn't expect to, we do inline keygen.

we can fiddle the heuristics later, and start with something simple now (are there any emails here that don't have up to date certs?  if so, pre-emptively keygen)

**Comment by benadida** [comment]
there is no good way to cancel a web worker in the browser, but other than that I'm happy with this direction. We'll have to be careful about potential race conditions. If we launch X workers for X email addresses, we can probably just wait for the one we need to come back when a given email is selected. Of course we start the preferred email one first.

**Comment by lloyd** [comment]
Ah, we don't need X workers for X email addresses.  We need to generate a max of one certificate per dialog session.  Once the keypair is generated, we then can get it certified for the email address chosen.

So this is a _non-specific_ keypair.  We can even cache the keypair in local storage for some period of time if it ends up not being needed.

I don't like that we cannot cancel web workers, but there seems to be lots of interesting tools at our disposal here...  think think think...

**Comment by benadida** [comment]
so you're saying generate the keypair, but wait until the selection of the email address to go get it certified? I _think_ the network latency is noticeable too, but I guess during that part we can do a spinner without any trouble. OK, that makes sense. So launch a worker for a keypair if at least one email is uncertified. I like it.

Don't worry about not canceling web workers: they do die if you close the page :)

**Comment by lloyd** [comment]
"Don't worry about not canceling web workers: they do die if you close the page :)"

that is perfect.

**Comment by benadida** [comment]
downgrading this issue, considering WONTFIX since we are thinking about key downgrade.

@lloyd thoughts?

**Comment by lloyd** [comment]
+1

--lloyd

**Comment by benadida** [comment]
ok, marking WONTFIX.
