### ISSUE TITLE
don't load css file from third-party domain

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#769]
on browserid.org, we load a CSS file from Google for a font. It would be better if we didn't load third-party content in general. Crystal, can you see if there's a way to get what we want without doing a third-party include?

**Comment by callahad** [comment]
Looks like you're using Droid Serif, which is available under the Apache 2 license, so it should be pretty straightforward to re-host it locally.

The easiest way to handle it would probably be to grab the "@font-face Kit" from Font Squirrel at http://www.fontsquirrel.com/fonts/Droid-Serif

That'll already have usable CSS, as well as conversions of the font into the various formats necessary for good cross-browser support.

**Comment by shane-tomlinson** [comment]
dup of #1695, closing this.
