### ISSUE TITLE
The user is not logged out of http://beta.myfavoritebooze.org after clearing all the browsing data

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#773]
OS: Windows 7
Browser: IE 9

STR:
1. Launch http://beta.myfavoritebooze.org in the browser.
2. Sign in to a BrowserID account.
3. Select an email and finish the sign in process.
4. Delete all the browsing data (history, cookies etc).
5. Reload http://beta.myfavoritebooze.org or close the tab and load the page in another tab.

The user stays logged in until restarting the OS no matter if the "Always sign in ..." option was checked when signing in or not.

**Comment by ghost** [comment]
This issue also reproduces on Windows XP with IE 8.

**Comment by ghost** [comment]
@jbonacci - i don't think it is expected not to be logged out with a refresh after deleting the browsing history with the "keep me signed in" checked. On Firefox, with "keep me signed in" checked, when clearing your recent history and refreshing, the user is  logged out.

Either way, the behavior should be consistent between browsers.

**Comment by shane-tomlinson** [comment]
@jbonacci, @ioanab does this have to do with the "preserver favorites website data"?  If you unselect that, does the problem go away?  If I deselect that, I am not signed in anymore.

**Comment by ghost** [comment]
@shane-tomlinson - I verified this issue with the "preserve favorites website data" option deselected on Win7+IE9 and it still reproduces for me. I am still displayed as signed in. 

If I click on "logout", I can see that I am completely logged out from my BID account (both when "preserve fav..." is selected and when deselected).

**Comment by shane-tomlinson** [comment]
@jbonacci , @ioanab - http://support.microsoft.com/kb/224304 outlines this - "Per-session cookies are not cleared until you close your browser."  This is Internet Explorer behavior that we can do nothing about.  Tagging as "upstream" and closing.
