### ISSUE TITLE
prioritize research questions

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#774]
We need to give UR time to do some studies for us, so let's look ahead at the features we want to build soon. Here are a few of the questions I have in mind. Please feel free to add if there are other assumptions you'd like to see validated.

Ethnographic - How do people use email?
- How are families using shared email accounts? What happens if they no longer want to share the account?
- How do people obscure their "real" or "primary" email address from sites they don't trust or want to receive email from?
- How many accounts do people have and what type are they?
- Where do people access their email from?

User testing of profile prototypes
- first run experience
- "this is not me" effectiveness in preventing two people sharing a browser id account

User testing of logout prototypes for the public computer experience

User testing of asking for a backup email

metrics -
a/b testing email drip campaign effectiveness

**Comment by vthunder** [comment]
I think we should start to set up the ethnographic study, and plan to run it in Q1 if possible. That is hopefully its own thread to some extent.

Of the other tests, I'd do them in the order you wrote them in: profiles, then logout, then backup email. For profiles, I think we need to know whether it makes sense in general, as input to you to [re-]design the UI (not just the first-run experience I mean).

I'm not sure I understand the last one, can you explain more? Maybe it's the funnel question I mention below?

Some other questions/topics I think we need data for:
- User pain points when a site switches from an existing system to BrowserID (from email/pw, username/pw, Fb, Tw, G, etc).
- User pain points when a site adds BrowserID to existing options, but does not switch wholesale.
- What does the funnel look like for the first time setup? What about signing in again after your BrowserID session has expired? (i.e., what % of users that see the first screen move to the second, then what % of those move to the next step, etc).
- Sharing via BrowserID -- see David Ascher's proposals for ideas.

**Comment by marytrombley** [comment]
Name and photo testing in March-- should have a prototype.
Testing site switching to BrowserID: paper prototype testing in January
Passwords: first collect a list of features to compare; meet in a small group to evaluate, THEN test. Deadline March.
Sign in to browser: Zhenshuo is designing; Jinghua will help to test.
Closing the loop: usertesting.com???? [Red flag]
