### ISSUE TITLE
Additional step for Vagrant box: npm install

### ISSUE THREAD

**Issue by johnnyt** [mozilla/persona#775]
I just fired up the Vagrant box, and after sshing in, I needed to run:

npm install

before npm start would work.

**Comment by shane-tomlinson** [comment]
@jbonacci - @ozten is heading up Vagrant, I've never used it.

**Comment by ozten** [comment]
@johnnyt: Sorry, yes. Unless we cut a new VM with each new package, that will have to happen.

It's not clear how useful the Vagrant VM has been. I don't think many people are using it. Should we remove it? @johnnyt would you participate in the project with or without the Vagrant VM?

**Comment by ozten** [comment]
I've posted http://groups.google.com/group/mozilla.dev.identity/browse_thread/thread/f6523a4d0e9c06bb# to gauge interest levels for the Vagrant VM. @johnnyt please add your thoughts.

**Comment by ozten** [comment]
No one is maintaining the Vagrant scripts and per discussion in groups, they have been removed. Closing issue.

We can always create a Vagrant script in an external project.
