### ISSUE TITLE
BrowserID doesn't allow login at all from Native Fennec 

### ISSUE THREAD

**Issue by jammink** [mozilla/persona#777]
Repros on latest nightly fennec (12/19)

To repro:

Using an email account already connected to BrowserID, try to login to myfavoritebeer.org

NOTE:  when, once in browserID field,  trying to select the "password" field, you are redirected to logged-out myfavoritebeer.org.  Clicking "login" reinvokes the login screen, but, alas, when trying to select password field, you are again redirected back to logged out state.

**Comment by shane-tomlinson** [comment]
Duplicate of #778, closing.
