### ISSUE TITLE
BrowserID hangs on "Communicating with server" on iPad (iOS5)

### ISSUE THREAD

**Issue by jmathai** [mozilla/persona#779]
On an iPad the BrowserID popup hangs on "Communicating with server".

Version: 5.0.1 (9A405)
Model: MB294LL

Reproduce:
1. Go to http://current.openphoto.me
2. Click sign in
3. Witness hanging on "Communicating with server"

Expected:
1. Go to http://current.openphoto.me
2. Click sign in
3. See sign in form

**Comment by jmathai** [comment]
We're doing User Agent detection (I know) and iPhones get a mobile version and iPads get the full site. You'll need to either spoof a non iPhone user agent or visit it on your iPad.

The iPad should get the desktop version.

**Comment by lloyd** [comment]
I need an ipad.

**Comment by lloyd** [comment]
works in ios simulator - 5.0 9a334

**Comment by jmathai** [comment]
Works in ios simulator 4.3.2. But still reproducible on the iPad itself.

The url in the address bar is `browserid.org/sign_in#` --- if that helps

**Comment by lloyd** [comment]
@jbonacci you can haz ipad?

**Comment by benadida** [comment]
@jmathai I'm not able to reproduce this on ipad 5.0.1 here. Can you check if this is still an issue? Are you able to reproduce this on more than one ipad (I know, tough question if you only have one.)

**Comment by jmathai** [comment]
@benadida Unfortunately, said laptop didn't belong to me. I tried it a second time and was able to replicate it but it very well maybe an anomaly. If I can get my hands on it again in the next few days I'll give it another try. Besides OS version is there anything that might help isolate why it wasn't working on that tablet?

**Comment by benadida** [comment]
@jmathai wait, laptop or ipad?

Since we're not able to replicate this at all, it's not clear what parameters could be at stake.... maybe a wedged localStorage? But we're pretty aggressive about clearing that when things go wrong. We'll keep an eye on this. I'll leave this bug open a few more days to see if we can reproduce it.

**Comment by jmathai** [comment]
Sorry, I meant iPad. Sounds good to keep it open for a few days else just chalk it up as an anomaly. I'll try to reproduce it if I can.

**Comment by benadida** [comment]
unable to reproduce, we suspect this is related to caching, see issue #226, please reopen if this happens again!
