### ISSUE TITLE
UX on first page with regards to edit/remove buttons

### ISSUE THREAD

**Issue by lookfirst** [mozilla/persona#797]
I went to the browserid homepage after having already created an account with an email. 

Maybe it is just me, but it seems kind of silly to make me click Edit just to get a Remove button. 

Not only that, but I was expecting that Edit would allow me to edit my email address, not remove it.

Thoughts?

Here are two screen shots detailing what I'm talking about.

![step1](https://img.skitch.com/20111222-jsntiik78tuxqwf7a8h29gmgat.jpg)

![step2](https://img.skitch.com/20111222-dkfud5tjkpaanhuju3gitqpnjw.jpg)

**Comment by skinny97214** [comment]
as designed

**Comment by lookfirst** [comment]
Ugh. @jbonacci sure, after @skinny97214's truly unhelpful and dismissive response above and the total lack of response on #809, I'm kind of disheartened to think that it is possible for even basic standard UX practices to be followed around here.

We've integrated BrowserId into our webapp, but only as a fallback to people who refuse to use FB. In my eyes, because of this, BrowserId will always be a second thought. If BrowserId wants to play with the big boys and be a real project, someone is going to have to give up the attitude that somehow this project is 'special' and deserves to make up their own UX.

I could go on; even things like the silly slider animation when you log in through BrowserId. Really, it is totally unnecessary fluff that only delays the amount of time till the BrowserId window closes and the person gets to their destination. FB clearly doesn't do it, why does this project feel the need to?
