### ISSUE TITLE
l18n: BR-pt

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#80]
translate the site and dialog into Brazilian Portuguese.

**Comment by faustort** [comment]
Here I am. Will be a pleasure to help when it could be possible .
The correct term is:
pt-BR - Brazilian Portuguese 
pt - European Portuguese

**Comment by ozten** [comment]
Fantastic. Please coordinate with @mathjazz.
Here is the overall progress:
https://localize.mozilla.org/projects/browserid/

**Comment by mathjazz** [comment]
@zarausto please let me know if you're still interested in localizing BrowserID to pt and pt_BR and I'll get you on board.

**Comment by faustort** [comment]
Ok for sure, what should I do?
I've never been on a project, but I really like to help.

Regards

Fausto

2012/1/31 Matjaž Horvat <
reply@reply.github.com

**Comment by mathjazz** [comment]
Localization started, please close this issue.

**Comment by lloyd** [comment]
ok
