### ISSUE TITLE
UX with regards to button capitalization

### ISSUE THREAD

**Issue by lookfirst** [mozilla/persona#809]
I'm talking about the buttons on https://browserid.org/

Not a definitive source, but it seems that the Apple UX guidelines suggest that you use "Use title-style capitalization for the button title and add an ellipsis if necessary. "

http://developer.apple.com/library/mac/#documentation/UserExperience/Conceptual/AppleHIGuidelines/Controls/Controls.html#//apple_ref/doc/uid/TP30000359-TPXREF186

Here is the Windows take on it (Use sentence-style capitalization):

http://msdn.microsoft.com/en-us/library/windows/desktop/aa511453.aspx

I'd appreciate it if you decide to close this issue with 'as designed', that you explain why you choose to not follow platform UX guidelines, which basically state the first letter should be capitalized.

**Comment by skinny97214** [comment]
Apple HIG are not intended to be a general design pattern. It's specific to their needs for the OS and not always applicable for websites. 

Are you concerned that title case causes usability problems? Or is it a visual design concern? The UX best practice is to be consistent in capitalization. Apple had to chose a case and they chose title case. We chose lower case. This was a visual design decision. If you have studies that show an advantage to title case, please send them along.

**Comment by lookfirst** [comment]
> Are you concerned that title case causes usability problems? Or is it a visual design concern? The UX best practice is to be consistent in capitalization.

You are absolutely right, the UX best practice is to be **consistent**.

The fact is that the vast majority of all other major websites out there (Mozilla, Facebook, Amazon, Apple, Yahoo, Microsoft, CNN, Google, Github, Chase, Bank of America, etc., etc., etc.), all use title case as their buttons everywhere. It is the same with all of the operating systems and devices (iPhone) that I use. The key word here is **consistency**.

Think of it this way. 99.9999% of the use case of BrowserID is to have 3rd party sites integrate with it. So, your UX should stay **consistent** with the sites which are integrating with it. On my site, I also follow those same guidelines in order to be **consistent** with what everyone else is doing.

When someone clicks the Sign In button on my website and it opens up the BrowserID dialog window (and possibly the BrowserID website), I'd like the experience to be as **consistent** and seamless as possible. I don't want people to feel like they are thrown for a loop when they go to the BrowserID flow. I want them to feel like it is just an extension of my own site. That is why I'm bringing this issue up.

> We chose lower case. This was a visual design decision. If you have studies that show an advantage to title case, please send them along.

Care to detail why you are not being **consistent** with everything else out there? It isn't about there being an advantage or disadvantage to title case. It is about being **consistent**. When you go and make up your own rules, which are totally different from every other major site out there, and claim that it is a `visual design decision`, you aren't being **consistent**.

**Comment by lookfirst** [comment]
Please give this more than one star and fix this before this gets even more out of control... there is all sorts of different variations of case in the documentation and screen shots:

https://support.mozilla.org/en-US/kb/what-browserid-and-how-does-it-work

![bahahahah](https://support.mozilla.org/media/uploads/gallery/images/2011-10-19-16-48-01-5cdac5.png)
![bahahahha](https://support.mozilla.org/media/uploads/gallery/images/2011-10-19-16-46-33-e30429.png)

**Comment by lloyd** [comment]
@lookfirst - So we've given the site a complete paintjob, led by one of the hottest designers at mozilla and a high touch copy editor.  

How did we do in your opinion?

**Comment by lookfirst** [comment]
why did you close this issue? nothing has been resolved.

lowercase edit/remove/done. I'd also argue that it is difficult to tell that the done button is 'indented'.

http://www.evernote.com/shard/s178/sh/62c993de-b3b0-40b7-8836-63f4b2fb9361/83d97c1796ecfc4cfcc42604612c03a1

'cancel your account' should be a button. http://uxmovement.com/buttons/the-button-vs-link-debate/

http://www.evernote.com/shard/s178/sh/d16da373-1601-4adb-ba69-31a69114adf5/13208936fc794ce72f1d693a7ddaaec1

i can keep going if you like...
