### ISSUE TITLE
l18n: FR-fr

### ISSUE THREAD

**Issue by clochix** [mozilla/persona#81]
Ping me when the project will be ready for I18n, I can help for the french translation

**Comment by lloyd** [comment]
w00t

**Comment by solisoft** [comment]
Hi, I can help too if needed

**Comment by ozten** [comment]
Fantastic. Please coordinate with @mathjazz.
Here is fr progress:
https://localize.mozilla.org/fr/browserid/

**Comment by mathjazz** [comment]
French is at 100% right now, but I'm sure it needs proof-reading & testing. We'll add new strings soon, so stay in touch.

**Comment by lloyd** [comment]
closing down all internationalization issues. l10n has begin, @mathjazz is coordinating the show, contact him directly to learn about contributing.

For now you can inspect current progress by updating your browser settings and visiting http://temporary_preview.myfavoritebeer.org/. (click sign in to see the localized dialog)

NOTE: this url is temporary, and we will transition to "test.myfavoritebeer.org" in the coming weeks.
