### ISSUE TITLE
package.json is missing a few dependencies

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#816]
After running "npm install" to install the browserid dependencies, I had to install these:

  npm install pkginfo
  npm install colors
  npm install stack-trace
  npm install async
  npm install qs
  npm install mime
  npm install mersenne

before I could successfully run it with "npm start".

**Comment by benadida** [comment]
which version of node are you running?

**Comment by fmarier** [comment]
That was on my 0.7.0-pre install where I had to add these:

  https://github.com/fmarier/browserid/commit/fc8baafaf580b4390f2169b432aca6d3ab2b3714

but it works fine on 0.6.7-pre, so you can probably ignore this bug. It seems to have other problems on 0.7...

**Comment by benadida** [comment]
@fmarier ahah, you're running on the bleeding edge :) Will close this for now, feel free to reopen if you notice this on a released version of node!

**Comment by salty-horse** [comment]
I'm running node 0.6.8 and experiencing the same missing dependencies as above, except mersenne.

for "npm test", "vows" is missing. It can be added to package.json as "devDependencies"

**Comment by salty-horse** [comment]
Correction: mersenne is required, and so do iconv and mimelib-noiconv

**Comment by salty-horse** [comment]
It seems like these are all dependencies of dependencies. According to https://github.com/isaacs/npm/issues/1336 "npm update" should resolve all missing dependencies.
