### ISSUE TITLE
limit the size of POST body

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#822]
Defend against this attack:

http://www.cs.rice.edu/~scrosby/hash/CrosbyWallach_UsenixSec2003.pdf

**Comment by vmunix** [comment]
The ZXTMs can, IIRC, be of assistance in the short term via the SPC feature, but we should absolutely put a limit on whatever is listening to the "data" event right in the app and return a 413 to a client that exceeds said limit.  /cc @fetep

**Comment by lloyd** [comment]
+1 - we need to do this as bytes are read off the wire - not after they get through the body parser.  Someone must have written this or it might be part of express already??  I'll gladly take it

--lloyd

**Comment by benadida** [comment]
I would love some defense in the app code, too, before (or using a modified) bodyParser. Go for it and take it.

**Comment by lloyd** [comment]
https://github.com/senchalabs/connect/blob/master/lib/middleware/json.js

can't see any provision at all for post body limiting.  I think we can attach middleware before body parser that also subscribes to data events and half closes then sends an error response...

**Comment by tj** [comment]
we have middleware named `limit()` for generic body limits in Connect, but nothing specific to query() / json() / urlencoded() yet. I think it would be good to add sensible defaults to query() and urlencoded(), json() is the one that would vary the most but we can still have some form of default

**Comment by tj** [comment]
actually i'm not sure you could really effectively limit keys for json, it would be a pretty gross hack, even urlencoded would be pretty difficult since we allow nesting

**Comment by lloyd** [comment]
hip hip horray, tj saves the day: https://github.com/senchalabs/connect/blob/master/lib/middleware/limit.js

that should do nicely...  this bug becomes a 1 line fix.

**Comment by jrgm** [comment]
Shouldn't the verifier also have this limit? /cc @fetep

**Comment by benadida** [comment]
yes, verifier should do this.

**Comment by lloyd** [comment]
Nice catch

--lloyd

**Comment by jrgm** [comment]
Opened https://github.com/mozilla/browserid/issues/878 to fix verifier same way.
