### ISSUE TITLE
Small trace left in checkbox on Firefox (linux) in e-mail list screen

### ISSUE THREAD

**Issue by DVirgil** [mozilla/persona#828]
This occurs on Linux (Ubuntu 11.10) in Firefox 9.0.1.
1. Log in to http://myfavoritebeer.org/ with an account with at least two e-mails listed.
2. Make sure the first e-mail from the list is selected.
3. Select the second e-mail's checkbox.

A small trace (half circle) is left on the checkbox of the first e-mail.

The trace disappears when the window loses focus.

**Comment by shane-tomlinson** [comment]
Thanks for the report @DVirgil, could you attach a screen shot so that I can get to the exact problem a bit quicker?

**Comment by DVirgil** [comment]
Still trying to get used to github.

I can't print the issue, as the trace disappears as soon as the Firefox window loses focus or with any print screen. 
I've linked it nonetheless. It has to do with the design of the checkbox marker. other browsers use a different style on Linux (Ubuntu 11.10).

http://bit.ly/rqyJSC

**Comment by shane-tomlinson** [comment]
@DVirgil - I am testing this in both KDE and Gnome on Ubuntu 12 without being able to reproduce.  Are you still seeing this problem?

**Comment by DVirgil** [comment]
I'll close this. 
Can't reproduce using moztrap.mozilla.org (used two e-mails). This is Ubuntu 12.04 and Firefox 14 beta 11.

**Comment by shane-tomlinson** [comment]
@DVirgil - Thanks for checking again!
