### ISSUE TITLE
l18n: nl_NL & nl_BE

### ISSUE THREAD

**Issue by M66B** [mozilla/persona#83]
Just give me a yell ...

**Comment by ozten** [comment]
Fantastic. Please coordinate with @mathjazz.
Here is the overall progress:
https://localize.mozilla.org/projects/browserid/

**Comment by mathjazz** [comment]
Hey, you can track progress for nl here:
https://localize.mozilla.org/nl/browserid/

If you'd like us to add any other locale for you, please let me know.

**Comment by lloyd** [comment]
closing down all internationalization issues. l10n has begin, @mathjazz is coordinating the show, contact him directly to learn about contributing.

For now you can inspect current progress by updating your browser settings and visiting http://temporary_preview.myfavoritebeer.org/. (click sign in to see the localized dialog)

NOTE: this url is temporary, and we will transition to "test.myfavoritebeer.org" in the coming weeks.
