### ISSUE TITLE
Unable to post message to https://browserid.org. Recipient has origin http://localhost:8888.

### ISSUE THREAD

**Issue by lookfirst** [mozilla/persona#830]
I'm running my server on localhost:8888 and on every page load, I see this error in the Chrome console window. I'm not sure if it something that I'm doing wrong or what. My integration of browserID works fine from localhost, but I do see this all the time anyway. Is there a way to suppress this message for localhost users?

**Comment by lloyd** [comment]
this should be fixed in train-2011.12.28 - you can confirm on diresworb.org (our beta environment) - to test against beta, just change browserid.org to diresworb.org

please reopen if what I say is a lie.

**Comment by lookfirst** [comment]
No lie, confirmed that it works on diresworb.org (cute name).
