### ISSUE TITLE
Generic error message when authenticating with cookies disabled.

### ISSUE THREAD

**Issue by chrismore** [mozilla/persona#835]
See more here:

https://bugzilla.mozilla.org/show_bug.cgi?id=715017

**Comment by chrismore** [comment]
Bug contents:

Created attachment 585597 [details]
BrowserID error with cookies disabled on iOS

If you have cookies disabled when you try to authenticate on BrowserID, you get an ambiguous error message.

To reproduce:

1) Disable cookies in your browser
2) Log in to Mozillians or Affiliates with BrowserID

Expected:

Error message about needing cookies to log in.

Actual:

Generic error message. (https://bugzilla.mozilla.org/attachment.cgi?id=585597)

**Comment by shane-tomlinson** [comment]
@lloyd, @benadida - Since all of our cookies are HttpOnly, is there a way we can know if cookies have been enabled on the user's device?

**Comment by shane-tomlinson** [comment]
Also related to #374

**Comment by benadida** [comment]
@shane-tomlinson the way would be to set a flag cookie on first resource load and check that flag cookie on session_context, which could return a hasCookies: false if the flag cookie is not there.

**Comment by benadida** [comment]
@shane-tomlinson another solution is to set a flag cookie that is not http-only, since it's just a flag, and check that in JS.

**Comment by shane-tomlinson** [comment]
Firefox with cookies disabled does not even get the popup - it throws an exception in include.js when trying to see if window.localStorage exists.

https://skitch.com/set117/8yqhs/browserid-cookies-disabled-exception

**Comment by shane-tomlinson** [comment]
Chrome with cookies disabled opens the popup, but blows up when trying to check authentication - QUOTA_EXCEEDED_ERR when trying to sync to localStorage.

See https://skitch.com/set117/8yq92/chrome-cookies-disabled

**Comment by shane-tomlinson** [comment]
Fennec with cookies disabled acts like Firefox desktop, the dialog never appears.

Safari Desktop, Opera Desktop, and Safari iOS work as expected.

**Comment by shane-tomlinson** [comment]
@lloyd - While testing cookies disabled support IE, I had the following exception thrown by the server:

```
browserid (22327): info: GET /wsapi/address_info?email=testuser%40testuser.com 200 1ms
browserid (22327): info: forwarding request: /wsapi/stage_user -> http://172.16.84.106:10004/wsapi/stage_user
dbwriter (22322): info: POST /wsapi/stage_user 200 3ms
browserid (22327): info: POST /wsapi/stage_user 200 6ms
dbwriter (22322): VERIFICATION URL:
dbwriter (22322): http://172.16.84.106:10002/verify_email_address?token=2CiamGO3mX0gu43QS3JVct0Lp5Qc4VEDSGF1ViSTJkS0ARhC
browserid (22327): info: GET /dialog/views/confirm_email.ejs 200 1ms
browserid (22327): info: GET /wsapi/user_creation_status?email=testuser%40testuser.com 200 1ms
browserid (22327): warn: POST calls to /wsapi require a cookie to be sent, this user may have cookies disabled
browserid (22327): error: uncaughtException pid=22327, uid=501, gid=20, cwd=/Users/stomlinson/development/browserid, execPath=/usr/local/bin/node, version=v0.6.6, argv=[node, /Users/stomlinson/development/browserid/bin/browserid], rss=33431552, heapTotal=17627008, heapUsed=12296168, loadavg=[1.2255859375, 1.05126953125, 0.81787109375], uptime=237097, trace=[column=13, file=/Users/stomlinson/development/browserid/node_modules/postprocess/index.js, function=ServerResponse.write, line=69, method=write, native=false, column=10, file=/Users/stomlinson/development/browserid/lib/httputils.js, function=Object.forbidden, line=40, method=forbidden, native=false, column=36, file=/Users/stomlinson/development/browserid/lib/wsapi.js, function=null, line=185, method=null, native=false, column=5, file=/Users/stomlinson/development/browserid/node_modules/client-sessions/lib/client-sessions.js, function=null, line=290, method=null, native=false, column=13, file=/Users/stomlinson/development/browserid/lib/wsapi.js, function=null, line=179, method=null, native=false, column=9, file=/Users/stomlinson/development/browserid/node_modules/connect/lib/middleware/bodyParser.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=IncomingMessage.emit, line=64, method=emit, native=false, column=23, file=http.js, function=HTTPParser.onMessageComplete, line=137, method=onMessageComplete, native=false, column=22, file=http.js, function=Socket.ondata, line=1374, method=ondata, native=false, column=27, file=net.js, function=TCP.onread, line=348, method=onread, native=false], stack=[TypeError: Object Forbidden has no method 'copy',     at ServerResponse.write (/Users/stomlinson/development/browserid/node_modules/postprocess/index.js:69:13),     at Object.forbidden (/Users/stomlinson/development/browserid/lib/httputils.js:40:10),     at /Users/stomlinson/development/browserid/lib/wsapi.js:185:36,     at /Users/stomlinson/development/browserid/node_modules/client-sessions/lib/client-sessions.js:290:5,     at /Users/stomlinson/development/browserid/lib/wsapi.js:179:13,     at IncomingMessage.<anonymous> (/Users/stomlinson/development/browserid/node_modules/connect/lib/middleware/bodyParser.js:74:9),     at IncomingMessage.emit (events.js:64:17),     at HTTPParser.onMessageComplete (http.js:137:23),     at Socket.ondata (http.js:1374:22),     at TCP.onread (net.js:348:27)]
browserid exited(1)  
dbwriter (22322): warn: SIGTERM received.  closing 0 connections and shutting down.
verifier (22320): warn: SIGTERM received.  closing 0 connections and shutting down.
keysigner (22321): warn: SIGTERM received.  closing 0 connections and shutting down.
dbwriter (22322): info: graceful shutdown complete...
example_primary exited(1)  
example exited(1)  
proxy exited(1)  
verifier exited(0)  
keysigner exited(0)  
dbwriter exited(0)  
all daemons torn down, exiting...
```

This has happened several times across several different browsers, exact STR unknown at this point.

**Comment by lloyd** [comment]
The chrome error is different.  it's because chrome conflates two things - disabling cookies and disabling local storage.  So we should detect the different failure cases on the front end and display user meaningful messaging.  In the chrome case, it's because you have "Block sites from setting any data" set.  Note again, while this preference is under "Cookies" it also disables local storage (by saying you've exceeded your storage quota).

**Comment by lloyd** [comment]
The server error is my problem.  I'm on it.

**Comment by shane-tomlinson** [comment]
@lloyd - w.r.t. Chrome, both Firefox and Chrome blow up when trying to access/write to localStorage.  Firefox throws an exception when trying to check window.localStorage for existence, Chrome lets you check for localStorage's existence but does not let you write to it.

**Comment by shane-tomlinson** [comment]
Closed with pull request 1106 - https://github.com/mozilla/browserid/pull/1106

Thanks for the feedback @chrismore!

**Comment by lloyd** [comment]
this is now live in our staging env: https://diresworb.org - testable via http://beta.myfavoritebeer.org
