### ISSUE TITLE
Shortened email displayed in browserid.org/signup page

### ISSUE THREAD

**Issue by hannosch** [mozilla/persona#840]
I'm trying to create a new browserid.org account. After entering my email address hschlichting@mozilla.com, I get a new page telling me about the confirmation email I should receive (url: https://browserid.org/signup).

That page contains: "We sent a confirmation email to hsch. To finish signing up just click the verify link we sent to your email address."

Note how my email address was shortened to the first four characters. This left me wondering if this is an obscurity feature to avoid showing my full email. If that's the case, it's not obvious and at least something like an ellipsis should be shown. But I don't see why showing the full email should be a problem here and so maybe this is just a bug :)

[first reported at https://bugzilla.mozilla.org/show_bug.cgi?id=715324 and moved here]

**Comment by hannosch** [comment]
I tried to reproduce this with two other email addresses of similar length, but those worked fine. And window.localStorage.signInEmail was set correctly. I did visit https://bipostal.diresworb.org/ before, but I don't see how that could have interfered, as it's a different domain.

**Comment by hannosch** [comment]
I could reproduce this now in both FF 10 and Chrome 16 beta.

The trick is to use auto-complete, type hsch, then use the down-key to select something from the list and hit enter to confirm the auto-complete choice. I then used the mouse to click the submit button. The second page only shows what I actually entered into the field, not the result from the auto-complete.

**Comment by jrgm** [comment]
Yes, hannosch has it right. It is down to the auto-complete. This is also https://github.com/mozilla/browserid/issues/699

**Comment by shane-tomlinson** [comment]
@hannosch - nice debugging!  Thanks, that is a huge help.

**Comment by ghost** [comment]
Verified on diresworb.org and browserid.org on Firefox 13.0 + Windows XP.
