### ISSUE TITLE
Present site's TOS and privacy policy to user

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#841]
Some sites require the user to agree to their terms of service and/or privacy policy. There is interest in having the user be aware / agree to them during the sign-in flow.

Note that some sites require explicit agreement (checking a box), so we should allow for that.

I don't think we need to present the actual TOS/PP, links to them (that open in new pages) should be sufficient.

**Comment by vthunder** [comment]
Crystal - we'll need some UX help here to make this not suck :-)

In particular, we want to make it as clear as possible that the TOS/PP are for the site the user is signing into, _not_ for BrowserID itself.

**Comment by benadida** [comment]
OK, we have a path forward here:
- design API for RPs to send privacy and ToS URLs to the dialog
- dialog shows "by clicking sign-in, you agree to the ToS and privacy policy" with two links (or just one if only one is provided by RP)
- when we prompt the user for a password, we also note agreement to BrowserID ToS and privacy policy (not the RP).

That is all for now, should do this in time for the next train.

**Comment by skinny97214** [comment]
Popup type email http://cl.ly/1M3x3q1d1i432L1p1T3m
Popup select email http://cl.ly/3k1S3v431N3o0Q2L1C3Y

Page http://cl.ly/0X1a3l381m3B0o0v1K2Z

**Comment by fligtar** [comment]
Looks great to me, as long as legal is okay with it. My understanding was that EU requires a checkbox assent. Thanks!

**Comment by benadida** [comment]
@lloyd this is closed right?
