### ISSUE TITLE
Add "add email" button to manage page

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#843]
I've heard multiple times from confused users that they'd like to be able to add an email from the manage page on browserid.org.

I know it's not the common case for most users, but for the ones that go exploring (and currently that's a lot, since a lot of web devs are trying it out and exploring the tech) it's sometimes a bit confusing that there's no way to add an email from there.

**Comment by shane-tomlinson** [comment]
Closing as duplicate of #421.

**Comment by ghost** [comment]
Verified as duplicate of #421.
