### ISSUE TITLE
BrowserID logo in header of dialog_layout an image

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#844]
The header of [dialog_layout.ejs](https://github.com/mozilla/browserid/blob/dev/resources/views/dialog_layout.ejs#L23) is styled with an image in the background. 

This image contains text and isn't suitable for localization, assuming BrowserID may need to be localized in 1 or more locales.

**Comment by shane-tomlinson** [comment]
@ozten - as a logo I don't mind keeping the main visual in an image.  I will add "BrowserID Home" to the link and set its text-indent to something off the screen so we are still screen reader friendly.
