### ISSUE TITLE
Safari 5.1.2 doesn't display the address bar of the browserid popup

### ISSUE THREAD

**Issue by davidbgk** [mozilla/persona#847]
This is currently a security/trust issue. You can reproduce it on the MDN website.

**Comment by shane-tomlinson** [comment]
Thanks @davidbgk - I have updated the window opening code to ensure that the address bar is displayed in Safari.

**Comment by shane-tomlinson** [comment]
@davidbgk - barring any major blockers, this will make its way into production in 2 weeks.
