### ISSUE TITLE
Provide a more explicit "change email address" workflow

### ISSUE THREAD

**Issue by stickfigure** [mozilla/persona#852]
When a user authenticates with browserid, the relying website gets an email address.  The website needs a way to change this email address.  Right now all the text on the login dialog says "login with this email address", which may confuse nontechnical users who are expecting to change their email address, not log in with a new account/email.

To some extent this may be mitigated with explanatory text on the page which contains the Change Email Address button, but this will be easy to miss and suddenly being in a "Login in with..." dialog may be jarring.  It will be especially jarring in dual-login systems where the initial authentication may not have been BrowserID.

One possibility is a call like this:

navigator.id.get(assertHandler, {changeEmail:true});

More in this thread:

https://groups.google.com/forum/#!topic/mozilla.dev.identity/L-C7WjGkb-Y

**Comment by skinny97214** [comment]
Agree 100%. Closing this for the general case bug I just filed.
