### ISSUE TITLE
npm: command not found

### ISSUE THREAD

**Issue by jstrimpel** [mozilla/persona#854]
I am not sure what I am doing wrong here. I got vagrant running and ssh'd in, but then...

vagrant@lucid32:~$ npm start
No command 'npm' found, did you mean:
 Command 'dpm' from package 'dpm-postgres' (universe)
 Command 'dpm' from package 'dpm-mysql' (universe)
 Command 'apm' from package 'apmd' (main)
 Command 'rpm' from package 'rpm' (main)
 Command 'gpm' from package 'gpm' (universe)
 Command 'pm' from package 'powerman' (universe)
 Command 'nm' from package 'binutils' (main)
 Command 'nm' from package 'binutils-multiarch' (universe)
 Command 'fpm' from package 'fpm2' (universe)
 Command 'npg' from package 'netdisco-backend' (universe)
 Command 'epm' from package 'epm' (universe)
npm: command not found

**Comment by sonnyp** [comment]
http://npmjs.org/
Note that with node 0.6 npm is now shipped built-in.

**Comment by benadida** [comment]
We are killing the Vagrant option because we haven't seen much usage of it and it's fairly easy to install BrowserID on your own. Closing this issue.
