### ISSUE TITLE
Mozillians: first time sign-in dialog provides confusing copy/labels with sign-in vs. new password

### ISSUE THREAD

**Issue by tantek** [mozilla/persona#855]
When using BrowserID for the first time to attempt to sign-into Mozillians.org with an existing account email, the dialog provided (see link) is sufficiently confusing that I don't know what is expected, nor am I comfortable proceeding (not knowing what is going on)

Screenshot of confusing dialog:

http://farm8.staticflickr.com/7159/6670209021_e64faea211_o.png

The text "Finish _signing into_" [_emphasis_ mine] makes it sound like I just need to enter my old mozillians password.

However, the form label reads "New Password"

which results in cognitive dissonance.

A "sign-in" form sets the expectation of the user entering in an _old_ existing password.

So when you see "New Password" - it's like huh?

Why a new password, what was wrong with my old password? 

Is this a new password for something else?

Am I entering a new password for mozillians.org (as it looks like from the form labeling "signing into: mozillians.org") ?

Or am I creating a new password for BrowserID? Or BrowserID.org?

Tried clicking the "Need Help?" link in the lower right of the page and it did not answer any of these questions nor point to an FAQ for any of them. The "Need Help?" link appears to go to a generic BrowserID marketing page (that might be a more appropriate for a "Learn more about BrowserID" link, not a "Help" link).

So I'm truly confused as to what to enter, and not having access to the old login flow, I don't know how to proceed.

From my user perspective, the relying party (mozillians.org) that I had an existing account with just "broke".

**Comment by skinny97214** [comment]
Can someone speak to why in @tantek screenshot it shows the "Finish signing into mozillians.org"?  This doesn't appear when I create an account through myfavebeer. I think it's adding to the confusion.

I think the solution is a (?) icon next to the New Password input that on hover has further explanation.

Also, the password strength indicators should help reinforce that you're creating a brand new password.

**Comment by skinny97214** [comment]
#886 should fix this issue

I agree that "sign in" is confusing for the first run experience. If we can have a custom experience for the first time a user goes through the legacy account conversion, we can use "create account" as the button label.

**Comment by tantek** [comment]
jbonacci - typo - wrong issue #.

This is a dependency relationship between bugs, not a duplicate.

You can make 855 dependent on 886 but please do not label as duplicate because it certainly isn't.

Please Reopen (as it says I don't have permission to do so).

**Comment by lloyd** [comment]
check out new copy in our staging environment (anosrep.org visible via beta.123done.org)
