### ISSUE TITLE
"Error encountered trying to complete registration" displayed when registration seems to be fine on Android 2.2.2

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#857]
Device: HTC Desire A8181
OS: Android 2.2.2
Browser: Native

STR:
1. Launch a BrowserID client in the browser.
2. Click on the Sign In button (if not on beta.myfavoriteshow.org).
3. Enter an email address not associated to BrowserID and click on the Next button.
4. Click on the Verify Email button.
5. Open the confirmation email in the same browser and click on the confirmation link.

After the user enters a password, the "Thank you for signing up with BrowserID..." page is displayed with the following message written on red above the thank you text:
"Error encountered trying to complete registration"

**Comment by jrgm** [comment]
I could not reproduce @ioanab's STR with a verizon droid 2.2 android with stock browser,

**Comment by ghost** [comment]
@jbonacci - When I reproduced this issue, it also reproduced when signing in from another browser/device and confirming the email address from the Android 2.2.2 native browser. 

I tried to reproduce the issue again but everything seems to be working fine now. @jbonacci, I think you were right in your previous comment.
