### ISSUE TITLE
delegation of authority

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#864]
one major missing feature from in-dev primary implementation is "delegation of authority" - this allows a domain owner to implement browserid primary support by delegating the job to someone else.  Documentation here: http://lloyd.io/primary-identity-authorities-in-browserid

**Comment by ryazwinski** [comment]
Yes, this is super important for any company (like Tucows, us :) ) who offer hosted email, but don't host the customer's corporate domain.

Foo.com has a web presence, but we host their email.
bob@foo.com wants to use browserid, but foo.com doesn't know anything about how to authenticate bob and, frankly, we want to offer the IdP as a service.

Absolutely need a lightweight way to delegate bob's browserid auth to us.

**Comment by ryazwinski** [comment]
dns would be a cheap and cheerful way to do this:  browserid.somedomain.tld  CNAME ...

**Comment by lloyd** [comment]
done!  see issue #1271

For the DNS suggestion, seems like sending it to dev-identity@lists.mozilla.org would be a Good Thing to do - https://lists.mozilla.org/listinfo/dev-identity

**Comment by lloyd** [comment]
this feature should make it to production 2012/03/28
