### ISSUE TITLE
buttons on hover

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#868]
Remove button underline on hover.
Red buttons and depressed blue buttons need hover gradient color change.

**Comment by shane-tomlinson** [comment]
@skinny97214 - do you want the hover colors to be the same as the depressed buttons?

**Comment by shane-tomlinson** [comment]
@skinny97214  - keep underlines on normal anchors?

**Comment by skinny97214** [comment]
Keep underlines on normal anchors. 

Not sure I understand the depressed button question. The main blue button brightens up on hover. The red and darker blue buttons never got that level of polish, so let's add it. I still have to get the new hex values for those to you.

**Comment by skinny97214** [comment]
http://people.mozilla.org/~smartell/persona/

**Comment by sawyerh** [comment]
@shane-tomlinson - I've updated the styles and this issue should be fixed now. Pull request sent. (https://github.com/sawyerh/browserid/commit/3e5ad5dc875e0e07e9a4d88dbec8dd3330eed961)

**Comment by jrgm** [comment]
verified stage train-2012.07.06
