### ISSUE TITLE
add type to <link rel="public-key" ... />

### ISSUE THREAD

**Issue by steelman** [mozilla/persona#87]
The link tag with rel="public-key" looks as if it was very useful for distributing any public keys including PGP and X509 (I know they are certificates). To avoid problems it seems quite reasonable to add a type like e.g. "application/x-browserid-publickey" or something like it in the primary/lib/webfinger_template.xml file. And of course make the relaying party look for keys of exactly this type.

**Comment by lloyd** [comment]
This issue will be made obsolete by the certification migration in progress now.

**Comment by steelman** [comment]
Do you mean browserid would X.509 certificates anchored in a PKI? Can you point some details?
