### ISSUE TITLE
Weird UI behaviour after cancelling account that has a pending 'add email' request

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#870]
This is admittedly a weird corner case, but seems to me (if I'm reading this
right) account cancellation should also cancel any pending requests to add an
email to the now-cancelled account.

0) Probably best to do this in a clean/new browser profile

1) Go to https://beta.myfavoritebeer.org. Click 'Sign in', and add an email
   not ever used. Click 'next'. Then click 'Verify email'.

2) Open the verify_email_address URL from email in the same browser, new
   tab/window. Fill in the 'New/Verify' passwords and click 'finish'. 
   Close this tab/window.

3) You should now be logged into myfavoritebeer. So click 'logout'.

4) Click 'Sign in', and in the popup window, click 'Use a different email',
   fill in another email address, and submit. IGNORE THE EMAIL THAT IS SENT (or 
   pretend it is lost in SMTP-land). 

5) Close the popup window, and in a new tab/window go to
   'https://diresworb.org'.

6) On diresworb, the first email you verified should be displayed. Click on
   'Your email addresses' 'edit' button, then click on 'remove'.

7) An alert is displayed "Removing the last address will cancel your BrowserID
   account. Are you sure you want to continue?".

8) Click OK. https://diresworb.org now shows a page with only the header and
   footer. Nothing in the central content area.

9) Go back to https://beta.myfavoritebeer.org. Click 'Sign In'.

The popup window comes up. It contains:
'''<b>Sign in using</b>           <a><small>This is not me...</small></a>

   <a><small>Use a different email</small></a>
                                               +---------+
                                               | sign in +
                                               +---------+          '''

Note that no email addresses are in the dialog above. (Clicking
'sign in' throws up an alert that the email is invalid or deleted.)

Presumably because the request to add an email to the account has 
not been acknowledged yet, the account cancellation is in a bit
of a state of limbo.

**Comment by skinny97214** [comment]
I'm fine with this throwing a generic server error along the lines of "Something went wrong."

**Comment by shane-tomlinson** [comment]
@lloyd - this is an odd one, on diresworb.org this can be distilled down into the following steps:

1) Open an account
2) Go to the diresworb.org manage page.
3) Cancel your account.
4) Go to beta.myfavoritebeer.org
5) Click login
6) Look at the response to session_context - it says you are still logged in.

{"csrf_token":"zZPIBTNF0sOILiu20N1TqQ==","server_time":1327070324707,"authenticated":true,"domain_key_creation_time":1322071714847,"random_seed":"HiLJ/bIuveSoQQ0H77EBt3Rb27wbvh25IfYuqBLUoG0="}

@lloyd - is it reading the cookie, see that it is still valid, and saying the user is authenticated?  Looking in lib/wsapi.js->isAuthed, it looks like the authed field is true if the user has a session, the session has a userid and an auth_level.  In lib/wsapi/account_cancel, it calls db.cancelAccount, does that take care of clearing the session info?

I cannot reproduce this in local development.

**Comment by shane-tomlinson** [comment]
@lloyd - this also happens on dev.diresworb.org - would this have to do with the difference in database drivers?

**Comment by shane-tomlinson** [comment]
@lloyd - here is a screen shot of this happening after doing the above steps.

https://skitch.com/set117/g7s6r/no-emails-but-authenticated

**Comment by lloyd** [comment]
can no longer repro!  please reopen if you can.

**Comment by jrgm** [comment]
I can't repro with either shane's STR nor my original STR using the staging environment. verified.
