### ISSUE TITLE
Progress animation should be BIDI aware

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#873]
When we're transitioning back to a website from the dialog, we have an awesome animation of an arrow from left to right.

In locales that have a right to left page layout, this layout should probably be reversed (website on the left) and the animation reversed (RTL).

We don't need this until we're close to having our first RTL language ('ar', 'fa', 'he').

I'm making our debug locale RTL, so we get a feeling for these various issues.

**Comment by shane-tomlinson** [comment]
@ozten +1 - I want to do this animation using CSS transitions and width instead of JS.  Would this be BIDI aware?

**Comment by ozten** [comment]
Ya, so the CSS would be relative to the dir attribute of the html element and your CSS transitions would be flopped in ltr.

psuedo CSS

html[dir=ltr] div.slider {
   // today's version
}

html[dir=rtl] div.slider {
   // today's version, but mirrored
}

The html would output
<html lang="en-US" dir="ltr">

If it makes it easier, we could add a new class to the body tag html-ltr or html-rtl which is how AMO works.
https://addons.mozilla.org/en-US/firefox/
https://addons.mozilla.org/he/firefox/

**Comment by shane-tomlinson** [comment]
@ozten - I'm giving this 3 star until we start on those languages.

**Comment by zaach** [comment]
@ozten has the time come for this?

**Comment by ozten** [comment]
Yes!

**Comment by shane-tomlinson** [comment]
Closing as less general case of #1066.  Thanks @zaach for pointing this out!
