### ISSUE TITLE
help text for creating a strong, memorable password

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#874]
Add a sidebar on the create password page to educate users on picking a great password. (In concert with #755)

These are a few of the techniques I'm aware of. I'd like to get security folk to weigh in on what works best.

Start With a Base Word Phrase.

A good password starts with a base word phrase. This means: choose a memorable catchphrase, quotation, or easy-to-remember saying Choose a phrase that is memorable to you. You might use a favorite quotation, song lyric, or the advertising slogan you despise most (preferably six words long or more). Examples of some base word phrases:

```
Can't See the Forest Through the Trees
```
- Long phrase:  Can'tSeetheForestThroughtheTrees *note you'll have to use a salt listed below
- Acronym of first letters: cstfttt
- Remove the Vowels: cntsthfrstthrghthtrs

Salts for extra security
- memorable number at the end such as a friend's phone number or birthdate: Don't use your own, children's or spouse's, as that's easy for a hacker to find.
- (need some suggestions about how to add special characters)

**Comment by skinny97214** [comment]
@warner Love to get your suggestions on ^^

**Comment by shane-tomlinson** [comment]
There are several bugs on this:

#443
#755

**Comment by shane-tomlinson** [comment]
Closing until we decide to handle this. Re-open if we want to immediately. Largly a dup of #755.
