### ISSUE TITLE
privacy and ToS in BrowserID popup

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#877]
A number of web sites have a legal requirement that users opt into the privacy and ToS. The UX is goofy if they have to do that after having already received the user's email. We've seen this from Mozilla properties in particular (since Mozilla follows European guidelines on this).

We should explore a potential API optional parameter to specify privacy policy and ToS, have the user opt into this in the dialog (but not on re-logins), etc. Needs discussion!

**Comment by benadida** [comment]
whoops, duplicate of #841

**Comment by skinny97214** [comment]
I'd favor making the button indicate agreement. Asking users to click the checkbox is annoying to users.

http://cl.ly/3u1e3Z1w1J3x3h1H022k

**Comment by benadida** [comment]
not doable, legal reasons, checkmark required.
