### ISSUE TITLE
basic profile (name+avatar) UI 

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#880]
Sketch out and test name + avatar
- first-run experience
- pull from gravatar/gmail/etc
- cloning info to other emails
- is optional or required?
- redesign popup to vcard-like picker

**Comment by skinny97214** [comment]
The only change to the flow is to add this lightboxed over the RP.
MOCK http://cl.ly/2S100O470l0R2N1e3t3f

It shows only for these cases
- first run for each new email added
- migrating old users to add name and photo (Q3 feature)

For the second email, the name and photo will be prefilled. If the user closes the dialog, those values should not be associated with that account.

**Comment by lloyd** [comment]
to confirm, for a MVF (minimum viable feature), would we have a way to update photo and name on the manage pagE?

**Comment by skinny97214** [comment]
I would prefer that we did. Uno momento, i'll open another bug...

**Comment by shane-tomlinson** [comment]
Closing this until we actually decide whether we are going to tackle this. We can re-open then.
