### ISSUE TITLE
shared computer challenges

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#883]
- What are the challenges for shared, home computers? 
- How can we encourage family members not to combine emails into one persona?

**Comment by lloyd** [comment]
baby step proposal: http://groups.google.com/group/mozilla.dev.identity/browse_thread/thread/666a24a5db19fde3?fwc=1

**Comment by lloyd** [comment]
The Question That We Will Ask At Smart Moments: http://cl.ly/2n3r2d3E0r0u3x0V3b0L
