### ISSUE TITLE
copy/branding of sign in buttons on RPs

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#885]
Finalize recommendations for sign in buttons for RP and update documentation.

Need to test copy and button layout.

Proposed copy from matej, feel free to comment.
- Say bye to passwords with xxxxx
- It's faster with no passwords. Sign in with xxxxx.
- No passwords, no problems. Sign in with xxxxx.

**Comment by folletto** [comment]
In order of preference:
1. Say bye to passwords with xxxxx
2. No passwords, no problems. Sign in with xxxx.
3. It's faster with no passwords. Sign in with xxxxx.

My reasoning here is that I heard many times people bothered by their passwords, but not much by the speed of it: of course, it's slow, but I never felt it as a problem in their mind.

The second one is cool, but feels on one side a bit too negative "no, no" and on the other "no problems" seems too wide.

That said, this is just personal preference. ;)

**Comment by skinny97214** [comment]
Example from kickstarter of how this is placed 
http://cl.ly/2z3W3J0I0C052E1N0A16

**Comment by callahad** [comment]
I believe this is done, as per "Sign in with your Email" recommended on MDN: https://developer.mozilla.org/en-US/docs/persona/branding
