### ISSUE TITLE
auth with primaries

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#887]
Can we rely on the primary enough that we don't need to have a BID password? Please let the answer be yes. :D Explaining what password to use when is a wicked problem.
- Nail down primary security to prevent that as an attack vector.
- Notify when email is added and give user mechanism to disable that account if it's fraudulent.
- If a user is adding another address to their account and already has set up a BID password, do we ever ask them for that one again or do we then auth via primary?
- Is better to send users out to the primary for auth or should we do it in the popup UI?

**Comment by lloyd** [comment]
I dunno if this issue is relevant.  shall we close it down given we've implemented passphraseless primary auth and open more discrete issues where we need to improve ux?

**Comment by skinny97214** [comment]
That's why I tagged it meta. Can we use this as tracking bug?

**Comment by lloyd** [comment]
No problem here,  other than us meeting and walkng through primary support, whatcha need from me?

**Comment by skinny97214** [comment]
A note about these meta bugs. The way I use issues is necessarily different than the way devs use them. UX is a systems discipline, so my day to day work is thinking and pondering big chunks. Bugzilla, Github and the like are typically optimized for tasks that are small in granularity because that's appropriate for coding work. But by the time I've distilled the problem down into something you would recognize as a bug, my work is already done.

I'd like to keep these open as placeholders so that we can all track the big chunks that I'm working on.

Hope this helps.

**Comment by lloyd** [comment]
Got it, I'm cool with tracking bugs.  If the body of the initial report was more general "this is a tracking bug to capture the task of a full UX review of the new primary feature", I would have been less confused.

**Comment by lloyd** [comment]
this is done! woohoo.
