### ISSUE TITLE
When getting address_info, show a wait indicator

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#888]
A user may have to wait for up to 30 seconds after entering their email address in the dialog while BrowserID goes out and checks whether their address is a primary or secondary - this is painful.

Add some sort of wait indicator.

**Comment by skinny97214** [comment]
Make it faster!!!!

**Comment by shane-tomlinson** [comment]
@skinny97214 - obviously that's the optimal solution!  The technical piece of how this is work (@lloyd - want to weigh in on this?) - When a user first enters their email into the authentication screen, if the BrowserID backend knows nothing about the domain the user enters, it has to go look at a certain location on that domain to see if it supports primaries.  If the call to the domain completes instantly, the user is none the wiser.  There is a problem though if the domain does not respond immediately, or is on a slow connection on the other side of the planet, or if the site is just plain down.  The TCP connection appears to currently be timing out after 30 seconds, but @lloyd says this is a TCP timeout - it is not a hard timeout set by BrowserID.  Now, once the response (or non-response) is received, the BrowserID backend tries to be smart about this and caches the info for 6 hours.  After 6 hours, the process starts all over.

So, yes, making it faster would be ideal.  But handling domains on slow connections on the other side of the planet needs to be dealt with as well.
