### ISSUE TITLE
Cannot log in using registered browserID email

### ISSUE THREAD

**Issue by cvan** [mozilla/persona#898]
So I have two email addresses with which I've registered/logged in on apps-preview.mozilla.org:
- hearcomestreble+cvan
- hearcomestreble

Using Chrome (successful):
1. Log in using hearcomestreble+cvan.
2. Select hearcomestreble+cvan.
3. Successfully logged in.

Using Firefox (unsuccessful):
1. Log in using hearcomestreble+cvan.
2. Select hearcomestreble+cvan.
3. Successfully logged in.

I cannot reproduce this in a new Firefox profile, but even upon clearing my cookies I still cannot log in (using hearcomestreble+cvan) from my main Firefox profile. Other BrowserID accounts work fine.

I don't have reliable STR but here is a screencast showing this behavior: http://www.screencast.com/t/mEwrgzcxBqHR

**Comment by lloyd** [comment]
@jrgm can't reproduce, can you @jbonacci ?

**Comment by cvan** [comment]
you can override the registration limit with https://apps-preview.mozilla.org/en-US/firefox/users/login?ro=mozillians

**Comment by cvan** [comment]
Sorry, my cookies got cleared and I can't reproduce this anymore.
