### ISSUE TITLE
Consider changing "sign in" screen on main site to use dialog.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#900]
Referencing #383.  I think that the BrowserID main site should act as an RP and use the dialog to sign in, ditching the sign in screen.

**Comment by zaach** [comment]
Are we still considering this?

**Comment by skinny97214** [comment]
We are. :D

**Comment by jaredhirsch** [comment]
#3253 merged in, closing this ticket accordingly.
