### ISSUE TITLE
IE9: myfavoritebooze.org will not display correctly because of font-face error

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#902]
When loading any of the myfavoritebooze.org sites, I get the following error and am unable to use the RP:

CSS3111: @font-face encountered unknown error. 
clhLqOv7MXn459PTh0gXYOb62E_zbtdBeaf9nLDgIoU.eot

**Comment by zaach** [comment]
We no longer use this site for testing, right? (looks like it hasn't been updated in many months)

Reopen if still relevant.
