### ISSUE TITLE
The Sign In button becomes unresponsive when loosing your internet connection

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#905]
OS: Windows 7
Browser: Firefox 10.0

STR:
1. Load http://beta.myfavoritebeer.org in the browser.
2. Click on the Sign In button and sign in to a BID account.
3. Leave the dialog with the emails list open.
4. Close your internet connection.
5. Select an email from the Sign In dialog and click on the Sign In button.

Actual Results:
The button is unresponsive and it stays like that until re-establishing the internet connection and closing and reopening the dialog.

Expected Results:
An error message that lets the user know he has no internet connection is displayed.

**Comment by shane-tomlinson** [comment]
@skinny97214 - I have implemented a basic dialog whenever a request takes more than 10 seconds, but it could use some serious UX love.  This should be considered along side of #888 as the buttons do nothing until the "this request is taking too long" screen and can be re-pressed.  I am thinking we should do something to the buttons while requests are completing - perhaps hide them and show a spinner, or disable the buttons visually and change the cursor (like Zimbra).

**Comment by shane-tomlinson** [comment]
@skinny97214, @ioanab - I have made this a two part system.  The first is, whenever there is an XHR request, grey out the form buttons.  In the dialog, this should all be good, on the main site, there are some areas where the buttons will be greyed out, but they will still be responsive - I have to fix those yet.  The second is, if a request takes more than 10 seconds, flip up the "this request is taking too long" screen - language needs modified, but I feel this is at least a step in the right direction for informing a user.  The code is rather flexible on what we can do, so any suggestions welcomed.

These can be tested/seen on dev.diresworb.org and dev.myfavoritebeer.org

**Comment by ghost** [comment]
@shane-tomlinson - I have tried to test this on dev but I didn't see the grayed out buttons at all, nor the request taking too long message with the steps from the bug description. Can you please give me some steps I could see them with?

**Comment by zaach** [comment]
Current results:
The dialog closes after pressing "sign in". On http://beta.myfavoritebeer.org, the sign in button is translucent and unresponsive. After a minute or so, if there is still no connection, a "login failure" alert shows and the sign in button remains translucent and unresponsive. If the connection returns before the timeout, the user is logged in.

**Comment by csuciu** [comment]
Tested on http://beta.myfavoritebeer.org and the 'login failure' popup is displayed immediately after pressing on sign in button. (less than 5 seconds). 
The Sign in button remains grayed out until reconnecting and reloading the page

Is this the correct behavior? If so, we can close this issue.

testcase - https://moztrap.mozilla.org/manage/caseversion/3651/

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
