### ISSUE TITLE
Wrong Sign In dialog opened after the client is set as Home page and the user cancels his BID account

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#906]
OS: Windows 7
Browser: Firefox 10.0, IE9

STR:
1. Set http://beta.myfavoritebeer.org as your Home page (for Fx, you can also just select the "Show my windows and tab from last time" option).
2. Open http://beta.myfavoritebeer.org.
3. Click on the Sign In button and sign in to a BID account.
4. Close the dialog with the emails list without finishing the sign in.
5. Close the browser.
6. Cancel your BID account from another browser/device.
7. Reopen the initial browser/device (http://beta.myfavoritebeer.org is loaded automatically).
8. Click on the Sign In button.

The Sign In dialog with the email list is opened but the emails list is empty. The "Enter your email address to sign in to beta.myfavoritebeer.org" dialog should be opened.

**Comment by seanmonstar** [comment]
closing this. if it's still a problem, please reopen.
