### ISSUE TITLE
include.orig.js missing

### ISSUE THREAD

**Issue by anantn** [mozilla/persona#911]
https://browserid.org/include.js says that the uncompressed source for itself can be found at https://browserid.org/include.orig.js, but the latter returns a 404.

**Comment by shane-tomlinson** [comment]
This is fixed in https://github.com/mozilla/browserid/pull/922

**Comment by lloyd** [comment]
fixed on dev: https://dev.diresworb.org/include.orig.js

**Comment by jrgm** [comment]
This is now available on stage for train-2012.02. https://diresworb.org/include.orig.js
