### ISSUE TITLE
add event-based RP API

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#912]
I propose moving to an event-based API for web sites.

```
// this event is guaranteed to fire after window.onLoad
// so it's best if this event listener should be registered before window.onLoad
navigator.id.addEventListener('login', function(event) {
  // do things with event.assertion
});

navigator.id.get({options});
```

Advantages:
- we do away with <tt>allowPersistent</tt> and <tt>silent</tt>, as those become entirely user-controlled now. The only option for that remains for now is <tt>requiredEmail</tt>.
- firing the <tt>login</tt> event can be done in a number of cases where the reference to the callback has otherwise been lost, e.g. when returning from having verified an email if the RP page was unloaded.

**Comment by lloyd** [comment]
suggesting 3 stars given other open issues.

**Comment by lloyd** [comment]
A proposal which fleshes out ben's original ideas is here: http://lloyd.io/a-new-api-for-browserid

**Comment by lloyd** [comment]
'Observer' API introduced experimentally `train-2012.04.11`: https://gist.github.com/2287552
