### ISSUE TITLE
add email broken in dev

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#913]
Steps to Reproduce:
1) Login via http://dev.myfavoritebeer.org/
2) Click "use a different email"
3) Add an email Click Add

Expected:
Email is sent, message shown

Actual: 
Nothing.
No interesting logs. No JS errors. I see XHR requests continue in background...

@shane-tomlinson I could use your help, did I break this with recent commit? qUnit and CLI tests pass... Do you see why this is failing?

Note: I'm going to commit more code, wanted to note that this was broken before my next commits...

**Comment by shane-tomlinson** [comment]
@ozten - something is goofy right now, in the "Pick email" screen, the "this is not me" button has no text inside the link and the "add an email" button says "pick email".  I think some string substitution has gone haywire.

**Comment by shane-tomlinson** [comment]
@ozten - I'm seeing this issue on dev.myfavoritebeer.org - has this made beta yet?

**Comment by shane-tomlinson** [comment]
@ozten - this has not made beta, so it is a regression in dev.  Removing the in-beta tag, will investigate.
