### ISSUE TITLE
XHR Delay screen will overwrite any wait screens already shown.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#915]
This can happen if the user is at the "waiting for email validation" screen and there is a > 10 second delay in the XHR request that checks the email's status.  When the XHR request completes, the wait screen will be taken away and the user will be shown an incorrect screen that is not active.  Related to #913.

**Comment by jrgm** [comment]
confirmed with osx/FF10 on stage train-2012.02.02, and this ipfw trick:

   # This does effective 10 second packet RTT on http,https  
sudo ipfw add pipe 1 tcp from me to any 80,443 out;
sudo ipfw add pipe 2 tcp from any 80,443 to me in;
sudo ipfw pipe 1 config delay 5000ms;
sudo ipfw pipe 2 config delay 5000ms;
sudo ipfw list;

I get the Looong message, and still can complete the verify_email_address flow.
