### ISSUE TITLE
dev: json_locale_data not available exception thrown from "/"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#916]
@ozten - I found this when trying to add a new "xhr delay" screen today.

Steps to reproduce on local dev:
1) Sign in to browserid from main site.
2) In the Firefox toolbar, click "work offline"
3) Try to logout.  "json_locale_data" not found exception in Renderer.js

**Comment by ozten** [comment]
Good find. The top level layout.ejs doesn't include the i18n file nor the gettext scripts.

Fixing...

**Comment by ozten** [comment]
Attempted fix
https://github.com/mozilla/browserid/compare/8a84e6e...1d500e3#L0L5
