### ISSUE TITLE
Add routes for include.js and include.orig.js so that symlinks are not overwritten

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#921]
Currently whenever we run the compression script, the symlink to include.js is overwritten, frequently leading to an incorrect checkin.  Instead of updating the symlink, we could add routes that point to to these files.

include.js should be served from:

development: include_js/include.js
production: production/include.js

include.orig.js should always be served from include_js/include.js

Also, remove the symlink from the repo, remove the symlink creation step from the compression script.

**Comment by lloyd** [comment]
merged to dev.
