### ISSUE TITLE
https policy

### ISSUE THREAD

**Issue by sebilasse** [mozilla/persona#923]
amazing, but
- I wonder...
  We recommend the "clients" in our setup to use https !
  We verify by php and I put this example under a "normal" http ...
  http://tools.atto.be/browserid/

We can not force our clients to use "https" but BrowserID
works from http as well ...
--->
So: What exactly is your https "policy" ???
- We need bigger buttons and some CC elements to have
  a strong BrowserID "Corporate Identity"

**Comment by lloyd** [comment]
BrowserID branding is by design.

Now, while we recommend using HTTPS, some of our demos are lazy and use HTTP.  If you think we could document this more clearly, please open another more focused issue!

Thanks for droppin' by,
lloyd
