### ISSUE TITLE
broken: Sign in to browserid.org with two different browsers

### ISSUE THREAD

**Issue by cheery** [mozilla/persona#927]
This is what I tried:
- use chromium
- go to http://myfavoritebeer.org/
- sign in fresh using gmail.com (gmail.com isn't a primary at the moment I'm writing this)
- verify through gmail by checking your email
- write up your favorite beer
- next. use firefox
- go to the same favorite beer site
- try sign in using gmail again

What happens:
- oh wait it asks to verify again, okay verify, it asks you to check your email like before.
- the email doesn't have a new post there.

**Comment by cheery** [comment]
Just tried: The browserid.org works well in chrome's incognito window.

Reversing this with the same firefox and then trying in chrome works too.

**Comment by cheery** [comment]
Firefox version 9.0.1, Mozilla Firefox for Ubuntu canonical - 1.0
Chrome version 15.0.874.106 (Developer Build 107270) Ubuntu 11.10

**Comment by jrgm** [comment]
Hi Cheery, 

I can't reproduce this with FF and Chrome on Ubuntu, or on OSX.

A couple of questions to clarify:
- you said "use chromium", but later say 'chrome'. Did you mean you were using a chromium build downloaded from, e.g., http://www.chromium.org/getting-involved/download-chromium in comment #0? Or using a Google Chrome build in both those comments.
- which browser(s), at what times in these steps to reproduce were you using to interact with gmail.com. We know there are issues with mixing signup dialog in one browser with completing the signup email in a second browser. Is that the sort of case you may have run into?

**Comment by cheery** [comment]
It's chromium, but not the build downloadable from there. I could try it with the newest build though.

I first tried it with chromium, then with firefox. At the time when I started firefox, chromium was down and firefox had not logged into gmail.com

Appears it's not very common bug anyway though.

**Comment by cheery** [comment]
@jbonacci yes. it still happens.

Mozilla Firefox 11.0
17.0.963.79 (Developer Build 125985 Linux) Ubuntu 11.10

**Comment by zaach** [comment]
I cannot reproduce this. The recent work on testing multiple browsers likely fixed this issue.
