### ISSUE TITLE
i18n - build script needs updated for main site.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#931]
the build script has been updated for i18n for the dialog only, the main site has not been given this treatment - compression is causing problems.

@ozten - We still use client side gettext in the main site for error and wait strings, so we have to add gettext and the JSON files to the main site build.  This will at first not seem to cause any problems, problems will only appear if an error or wait screen is shown.

**Comment by ozten** [comment]
Can you give me steps to repro?

**Comment by ozten** [comment]
STR

1) https://dev.diresworb.org/

Expected:
No Errors

Actual:
In JS Error console 'Uncaught ReferenceError: gettext is not defined'

**Comment by ozten** [comment]
First stab at fixing this http://git.io/mNaeJA

**Comment by ozten** [comment]
Looks fixed.
