### ISSUE TITLE
problems using stage environment

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#932]
Sorry, incomplete description or STR (still debugging). But various attempts to signup or signin or add and email via the 
popup on betamyfavoritebeer.org are leaving the UI in a non-responsive (or not proceeding) state. 

e.g., for a new account, the stage_email is sent and the email received but the popup doesn't proceed past the Add button.

More in a bit.

**Comment by lloyd** [comment]
one concrete problem, I tried logging in with a new email and after clicking 'verify' I did not get a transition to the "check your email" screen.

though everything else worked properly. (polling started, email sent, verification successful)

**Comment by lloyd** [comment]
This issue discussed above looks a lot like GH-913. @shane-tomlinson is it possible that the "check email" screen was broken at the time we rolled the last train?  Is it possible your fix for 913 fixes it in dev?

**Comment by lloyd** [comment]
1. In this case, I don't see the `check your email` page come up in the dialog, though it seems to work correctly.  this is a five star bug that's reproducible.  I believe GH-913 fixes it in dev
2. clicking on the 'add' button does not refresh the dialog and send you to the `check your email` page.  Very similar symptoms to #1.  This is a reproducible 5 star bug.  I believe GH-913 ALSO fixes this in dev
3. clicking on "forgot my password" in dialog, followed by "reset pass" does not referesh the dialog and send you to the `check your email` page.  very similar symptoms to #1 and #2.  This is a reproducible 5 star bug.  I believe GH-913 ALSO fixes this in dev

**Comment by lloyd** [comment]
broken into three specific issues, GH-933, GH-934, GH-935.  closing down this as we now have specific user flows that are broken enumerated into their own issues.
