### ISSUE TITLE
"Check Your Email" not displayed on new-user sign in

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#933]
on beta train-2012.01.18 the dialog is not properly transitioning to the "Check your email" page upon attempt to create a new account in the dialog.  STR:
1. go to beta.myfavoritebeer.org
2. click login
3. enter an email address you've never used before
4. click `next`
5. click `verify`

Notice that there's a quick transition to `Check your email` (sometimes you can't even visually detect it), followed by returning to the screen with the `verify` button.

**Comment by lloyd** [comment]
this is one specific manifestation of issue #932

**Comment by jrgm** [comment]
looks okay to me in dev using IE9/win7...

**Comment by lloyd** [comment]
hotfixed in train 2012.01.18 - in stage now
