### ISSUE TITLE
"Check Your Email" not displayed on email addition

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#934]
on beta train 2012-01.18 when adding an email to an existing account via the dialog, the "Check Your Email" screen is not displayed.  STR:
1. go to http://beta.myfavoritebeer.org
2. click `login`
3. you should already be logged in with an existing browserid acct with any number of emails associated with it.
4. click `use a different email`
5. type in an email you've never used before
6. click `add`

You may see some flicker, and the end result is you're left at the `add new email` screen, and not transitioned to the `check your email` screen.

**Comment by lloyd** [comment]
This is a specific manifestation of issue #932

**Comment by jrgm** [comment]
looks ok to me on dev with IE9/win7...

**Comment by lloyd** [comment]
hotfixed in train 2012.01.18 - in stage now
