### ISSUE TITLE
"Check Your Email" not displayed on in-dialog "forgot your password"

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#935]
an issue on train-2012.01.18 - STR:
1. go beta.myfavoritebeer.org
2. click `login`
3. click `this is not me` if you're already signed in
4. type in the email address of an existing browserid acct
5. click `next`
6. click `forgot your password`
7. click `reset password`

Notice flicker (the buttons) and that you are not successfully transitioned to the "Check Your Email" page.

**Comment by lloyd** [comment]
This is a specific manifestation of issue #932

**Comment by jrgm** [comment]
This flow works (mostly) in dev for IE9/win7, but it has some unusual pauses (long enough that a user would think something had gone wrong) or in one try it moved from the check your email screen back to the cancel/reset-password
screen and just stuck there. Trying other win7 browsers now....

**Comment by jrgm** [comment]
Ok, so I tried the STR at the beginning of this bug several times, alternating
IE9/Chrome16/FF9. I was also running the windows 'Resource Monitor' while
doing this ('Start > Accessories > System Tools > Resource Monitor' or from
cmd.exe '%windir%\system32\perfmon.exe -res').

After loading the confirmation link from the email sent out, IE9 would show a
~90% spike in CPU for several seconds; FF and Chrome did not.

Anyways, I'll split out my comments above to a separate issue, as it appears
this is an IE9 specific thing.

**Comment by jrgm** [comment]
Split off the IE9 sluggishness to GH-954.

**Comment by lloyd** [comment]
hotfixed in train 2012.01.18
