### ISSUE TITLE
Dev: dbwriter dies on `stage_email` call

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#936]
on current dev we've witnessed dbwriter dying on a `stage_email` API call.  This manifests to the user as an "internal server error" at the time the user attempts to add a new address to an existing account.

Inspecting logs we see a dbwriter restart and connection failures from the webhead forwarding requests to dbwriter.

/cc @shane-tomlinson @ozten - could this be related to i18n changes?  I'll dig, but feel free to poach.

**Comment by ozten** [comment]
It could be related, but I can't reproduce dbwriter dying in dev with in English or Esperanto by adding email addresses.

**Comment by ozten** [comment]
Do we have monit logs to see how often this happends? Maybe we can correlate them with the browserid logs to get steps to reproduce?
