### ISSUE TITLE
Add Vary HTTP header for Accept-Language and Accept-Encoding

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#938]
We should set Vary: Accept-Encoding,Accept-Language for requests.

Fixes:
1) server side gettext won't be cached for all locales
2) properly serving static resources to clients that can consume different representations (gzib, etc)

**Comment by jrgm** [comment]
Verified on stage for train-2012.02.02. All static requests respond with 'Vary: Accept-Encoding,Accept-Language'; /wsapi/..
calls do not contain this header.
