### ISSUE TITLE
Think of cleaner ways to do form validation, including for IE7.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#94]

**Comment by lloyd** [comment]
ie7 is just a nice to have...  I wonder if @vthunder can get us some numbers / weigh in.

--lloyd

**Comment by shane-tomlinson** [comment]
merge e4cfc151d147fd197bab3a82e732c04f5620d9b2 addresses this.  Doing client side validation, removing HTML5 native validation.  this will fix IE7/IE8/ other browsers that have HTML5's localStorage and postMessage but not form validation.
