### ISSUE TITLE
Should be able to hit enter to start verifying a primary email

### ISSUE THREAD

**Issue by Mardak** [mozilla/persona#946]
Right now, nothing happens when hitting enter on "Verify With Email Provider" dialog.

**Comment by Mardak** [comment]
Enter "ed@eyedee.me" for an email address and hit enter. The next dialog to appear should be "Verify With Email Provider" and hitting enter does nothing.

**Comment by jrgm** [comment]
@markdak you mean that the 'verify' button should be focused in that dialog (so hitting Enter is the same as clicking 
on that button). Right?

**Comment by jrgm** [comment]
Okay, verified on win7/winxp/osx/ubuntu (android moot). This flow (apart from having to click sign in on e.g., myfavoritebeer.org) is navigable with the keyboard.

**Comment by jrgm** [comment]
Note to @mardak: this fix will be in production next week sometime.
