### ISSUE TITLE
scroll bar appears in required email flow when verifying with primary

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#947]
Steps to reproduce:

1) Open dev.myfavoriteshow.org
2) Enter in a "primary" supported email address - something at eyedee.me
3) Check out the scroll bar.

Check out screen shot:
https://skitch.com/set117/g5882/browser-id

**Comment by shane-tomlinson** [comment]
Labeling 5 star though it is a new feature just because it is such an ugly ugly user facing blemish on an otherwise awesome feature.

**Comment by lloyd** [comment]
hotfixed in 2012.12.18.02

**Comment by shane-tomlinson** [comment]
This is back with longish email addresses.

https://skitch.com/set117/g7say/verify-required-primary

**Comment by jrgm** [comment]
verified on stage for multiple browser/os including android 2.1 stock.
