### ISSUE TITLE
IE9/win7 showing some pauses (CPU spikes) when doing STR in GH-935

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#954]
See the initial STR in GH-935, and followup comments reproduced here:

Llloyd:
an issue on train-2012.01.18 - STR:
1. go beta.myfavoritebeer.org
2. click `login`
3. click `this is not me` if you're already signed in
4. type in the email address of an existing browserid acct
5. click `next`
6. click `forgot your password`
7. click `reset password`

Notice flicker (the buttons) and that you are not successfully transitioned to the "Check Your Email" page.

jrgm:
This flow works (mostly) in dev for IE9/win7, but it has some unusual pauses (long enough that a user would think something had gone wrong) or in one try it moved from the check your email screen back to the cancel/reset-password
screen and just stuck there. Trying other win7 browsers now....

Ok, so I tried the STR at the beginning of this bug several times, alternating
IE9/Chrome16/FF9. I was also running the windows 'Resource Monitor' while
doing this ('Start > Accessories > System Tools > Resource Monitor' or from
cmd.exe '%windir%\system32\perfmon.exe -res').

After loading the confirmation link from the email sent out, IE9 would show a
~90% spike in CPU for several seconds; FF and Chrome did not.

Anyways, I'll split out my comments above to a separate issue, as it appears
this is an IE9 specific thing.

**Comment by shane-tomlinson** [comment]
@jrgm - I just did some tests on this and it is due to the way we are fading in the elements.  We are using Javascript to do the fade in effect and it is causing a CPU spike in IE, if I remove the animation and do a straight "show", CPU usage hits ~18%, which is consistent with other sites.

**Comment by shane-tomlinson** [comment]
@jrgm - I am closing this as 'won't fix'.  I retested both IE8 and IE9 on Win7 using dev.myfavoritebeer.org, both show two short bursts of high CPU usage.  IE8 shows a short spike of 100% while generating the assertion and another when myfavoritebeer is doing its transition.  IE9 goes up to ~90% while the assertion is being generated and 70% while myfavoritebeer does its transition.  Neither of these cause the "this script is taking too long" error message.

**Comment by jrgm** [comment]
@jbonacci I had a quick look an the flow with now asking for a password first invalidates the original STR. If I do pick up the email and do /verify_email_address I see a sub-second spike in CPU to 98%, but not visible to the end user. So verified; not a problem anymore.
