### ISSUE TITLE
IE8: Using the URL hash when redirecting from IdP to dialog breaks WinChan.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#957]
When the user returns from the IdP, WinChan can no longer find its relay window because the URL hash no longer contains the name of the relay frame.  Instead, the URL hash contains meta information about whether to add the email address to the current account or whether to create a new user.

**Comment by lloyd** [comment]
that doesn't make sense.  winchan doesn't embed relay frame names in url hashes, ever.   https://github.com/lloyd/winchan/blob/master/winchan.js#L50-65

What's the user facing bug you observed here?

**Comment by lloyd** [comment]
@shane-tomlinson can you add STR?

**Comment by lloyd** [comment]
5 star - suggests IE8 is broken for primary support

**Comment by shane-tomlinson** [comment]
Closing, this was a code path that was exercised because of other errors.  No longer a problem.
