### ISSUE TITLE
Incorrect IdP address shown when user needs to authenticate with IdP

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#964]
Steps to reproduce:

1) Log out of eyedee.me
2) Go to beta.myfavoriteshow.org
3) Enter your eyedee.me email address.
4) Open dialog
5) Check out the address that is displayed for where the user will be redirected to.  It always displays "http://192.168.1.88:10005/sign_in.html" which is my local machine.

Expected:
Show the URL the user will be redirected to.

**Comment by lloyd** [comment]
merged into 2012.01.18
