### ISSUE TITLE
When the user cancels a log in of an unauthenticated primary account, the email is still marked as most recently used

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#968]
STR:
1. Launch http://beta.myfavoritebeer.org.
2. Sign in with a BID with multiple emails from a primary (eyedee.me).
3. Select an email and log in.
4. Log out, the click on the Sign In button again.
5. Select another email address, then click on the Sign In button.
6. Click on the Cancel button.

The user is returned to the dialog with the emails list and the email selected at step 5 is marked as most recently used. The email selected at step 3 should be the marked one since this is the last email the user logged in with.

**Comment by jrgm** [comment]
verified on stage train-2012.04.27 using FF 12 and an account with 3 primary eyedee.me addresses
