### ISSUE TITLE
IE8: Cannot log out of sample IdP

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#970]
Steps to reproduce:

1) Load up IE8
2) Go to sample local IdP
3) Sign in.
4) Try signing out.  It never works.

**Comment by lloyd** [comment]
resolved in eyedee.me, and deployed.  fix: https://github.com/lloyd/eyedee.me/commit/9fa42b8a6604b6d81eb13884d65317a50f9b1f67
