### ISSUE TITLE
IE8: In local sample IdP, after authenticating as new user, /api/whoami thinks you are the old user.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#971]
Steps to reproduce:

1) load up IE8
2) Go to local sample IdP
3) Log in as a user1
4) load up sample RP
5) Try signing in as user2@example.domain.
6) When redirected to IdP, hit "OK".
6) After redirect back to BrowserID, it thinks you are still not authenticated.

More info.  After the first verification, you can open up the IE8 debugger and set a breakpoint in provision.html.  /api/whoami always returns "user1" as the currently logged in user.

Setting a breakpoint is a bit tricky because you have to open the dialog, then open the debugger using F12.  Press "Start Debugging"  This will cause the dialog window to close.  Re-open the dialog window, hit F12 again.  Press "Start Debugging" again.  The window will not close this time.  Now you can set a breakpoint and go on your merry way.

**Comment by lloyd** [comment]
resolved in eyedee.me, and deployed. fix: https://github.com/lloyd/eyedee.me/commit/9fa42b8a6604b6d81eb13884d65317a50f9b1f67
