### ISSUE TITLE
IE8: &apos; not supported

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#981]
Bug for another Mozilla project:

https://bugzilla.mozilla.org/show_bug.cgi?id=661815

`&apos;` not supported by IE8, but `&#39;` is

@ozten - Is `&#39;` supported by gettext? Will it cause any problems with translations?

@jbonacci, @jrgm, @ioanab 

Steps to reproduce:
1) Fire up IE8
2) Go to an RP
3) Try to sign up using a new account.
4) Look for the &apos; in "This email looks new, so let's get you set up."

**Comment by ozten** [comment]
&#39; should be fine in gettext.

**Comment by shane-tomlinson** [comment]
@ozten - in my i18n directory, the changes I made for `&apos;->&#39;` are not reflected - all the client.json files still have `&apos;`.  Can we manually update any `&apos;`'s in the finished files so that IE8 can display correctly?

@jrgm - thanks for finding this.

**Comment by ozten** [comment]
@shane-tomlinson - bummer. I'll edit all the po files that haven't gotten around to updating their strings. thanks for calling this out.

**Comment by ozten** [comment]
Sending        cs/LC_MESSAGES/client.po
Sending        de/LC_MESSAGES/client.po
Sending        en_US/LC_MESSAGES/client.po
Sending        fy/LC_MESSAGES/client.po
Sending        ga/LC_MESSAGES/client.po
Sending        it/LC_MESSAGES/client.po
Sending        lij/LC_MESSAGES/client.po
Sending        nl/LC_MESSAGES/client.po
Sending        pl/LC_MESSAGES/client.po
Sending        rm/LC_MESSAGES/client.po
Sending        ro/LC_MESSAGES/client.po
Sending        ru/LC_MESSAGES/client.po
Sending        sl/LC_MESSAGES/client.po
Sending        sr/LC_MESSAGES/client.po
Sending        zh_TW/LC_MESSAGES/client.po
Transmitting file data ...............
Committed revision 101249.

**Comment by ozten** [comment]
Ugh, this caused a bunch of duplicate strids.

Fixed:
Sending        cs/LC_MESSAGES/client.po
Sending        de/LC_MESSAGES/client.po
Sending        en_US/LC_MESSAGES/client.po
Sending        fy/LC_MESSAGES/client.po
Sending        ga/LC_MESSAGES/client.po
Sending        it/LC_MESSAGES/client.po
Sending        lij/LC_MESSAGES/client.po
Sending        nl/LC_MESSAGES/client.po
Sending        pl/LC_MESSAGES/client.po
Sending        rm/LC_MESSAGES/client.po
Sending        ro/LC_MESSAGES/client.po
Sending        ru/LC_MESSAGES/client.po
Sending        sl/LC_MESSAGES/client.po
Sending        sr/LC_MESSAGES/client.po
Sending        zh_TW/LC_MESSAGES/client.po
Transmitting file data ...............
Committed revision 101252.

CC @mathjazz

**Comment by mathjazz** [comment]
I've updated all locales in Verbatim.

Question: what if we just use ' instead of &#39 as we do here?
https://github.com/mozilla/browserid/blob/dev/resources/static/shared/wait-messages.js

**Comment by ozten** [comment]
'nuff said!

**Comment by jrgm** [comment]
Text looks fine (no apos) for en-US on IE8/WinXP, IE9/Win7, {opera,chrome,firefox} on {osx,ubuntu,winxp/win7}, safari on {osx,winxp,win7}, and android 2.1 stock browser.
