### ISSUE TITLE
cancel button on browserid dialog doesn't seem to do anything

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#983]
While failing to sign in to myfavoritebeer (see issue #982), I hit the cancel button on the browserid dialog and it didn't actually cancel anything.  Not sure they're hooked up :)

**Comment by shane-tomlinson** [comment]
@dria - is this after authenticating with eyedee.me and being redirected back to the BrowserID content?

**Comment by ghost** [comment]
Yeah, while I had 3rd party cookies disabled.

**Comment by shane-tomlinson** [comment]
Note for me:

The cancel button is shown, but the state machine does not know how to handle it because there is nothing in its history at this point.

**Comment by shane-tomlinson** [comment]
Closing this - the "cancel button not doing anything" has been fixed, 3rd party cookies related issues are re-opened in #982 and #989
