### ISSUE TITLE
disabling 3rd party cookies will break persistent/silent sign in.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#989]
Relating this to #982

**Comment by shane-tomlinson** [comment]
Link to #1181

**Comment by jaredhirsch** [comment]
Work in progress here but not going to get done prior to Beta 2. Bumping to Beta 3.

**Comment by shane-tomlinson** [comment]
We have decided that we will always call the .onready callback if 3rd party cookies are disabled and we are unable to divine the user's state. This got merged with #3116. Closing.
