### ISSUE TITLE
any bad account name crashes node on login

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#99]
Any bad account name causes a node crash on login.

/Users/moco/development/browserid/browserid/lib/wsapi.js:150
      var success = bcrypt.compare_sync(req.body.pass, hash);
                           ^
Error: Params must be strings.
    at /Users/moco/development/browserid/browserid/lib/wsapi.js:150:28
    at /Users/moco/development/browserid/browserid/lib/db.js:271:16
    at Statement.<anonymous> (/Users/moco/node_modules/sqlite/sqlite.js:130:11)

**Comment by lloyd** [comment]
fixed by c1f4efb619b66e1eee9199d3026dc47816b9eabc
