### ISSUE TITLE
Tracking - technical jargon in strings

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#992]
This bug will list strings in po files that are hard to translate.

If there is an action, we can spin off a separate issue.

For  each sting we should do one of these:
1) Tell localizers to treat as technical jargon
2) Remove gettext if message isn't exposed to users
3) File a bug to rewrite copy - this must be done in the next release train, since we're past string freeze

**Comment by ozten** [comment]
http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/en_US/LC_MESSAGES/client.po

via IRC Besnik_b: client.po has something like "This window will be redirected to" I'd suggest to reword that in something like "This action will be redirected to" or "This window will redirect you to"

**Comment by ozten** [comment]
via IRC Besnik_b: Also, could someone give a hint how to translate the strings about Assertion?

#: resources/static/shared/error-messages.js:26
msgid "Authenticating with Assertion"
msgstr ""

#: resources/static/shared/error-messages.js:59
msgid "Getting Assertion"
msgstr ""

**Comment by ozten** [comment]
via IRC Besnik_b: The last thing: "Relay frame" is misspelled for "Frame relay" or am I missing something. I must confess that my knowledge of networks' working is null.

#: resources/static/shared/error-messages.js:104
msgid "Relay frame could not be found"
msgstr ""

**Comment by ozten** [comment]
@mathjazz please provide guidance.

@shane-tomlinson are any of the strings mentioned here not actually shown to users?

@skinny97214 these can feed into existing or new UX focused issues.

**Comment by mathjazz** [comment]
We usually try to add comments when string are hard to translate. Relay frame and Assertion are both very technical terms that should probably be explained in a couple of words. Is anyone good at explaining them? :-)

**Comment by skinny97214** [comment]
My guidance for these sorts of technical errors is to say

"Something with the system went wrong." and then whatever their resolution is, i.e. "try again in a few minutes"

You can still say "Relay frame could not be found" in a div set to display:none so our devs and QA can inspect the element and see the detailed error.

**Comment by shane-tomlinson** [comment]
@ozten, @skinny97214 - the technical jargon @lloyd and I kept in with the hopes that we could get users to Tweet this info in English and give us some good clues as to catastrophic failures happening.

Other ideas we had were to not display the info but to auto-submit it to a BrowserID error logger, but this will only work if BrowserID is actually online.

**Comment by skinny97214** [comment]
@shane-tomlinson ahh... ok. I didn't realize that was a concern. It seems like that's a pretty spotty feedback loop. Do we have other options for logging the error? Pushing it into the UI is no bueno.

**Comment by shane-tomlinson** [comment]
@ozten, @lloyd - have we decided to remove gettext from these strings for now?

**Comment by ozten** [comment]
I need help. Can we make a public etherpad or wiki and list all the strings which **do not** need to be translated?

This release - the will be wrapped with gettext and we'll give localizers that url as a guideline on what they can ignore
Next release - we'll remove the strings from po files, by removing gettext around these strings
Future release - We'll file bugs with improved language for user facing strings with too  much jargon.

@shane-tomlinson can you make that wiki page? I don't know the code well enough to know what is a hidden message and what isn't.

**Comment by shane-tomlinson** [comment]
@ozten - https://id.etherpad.mozilla.org/18 - public to the world.

**Comment by ozten** [comment]
Here is some good feedback
http://groups.google.com/group/mozilla.dev.l10n.web/browse_thread/thread/6ca0e91878fc4ffa#

**Comment by ozten** [comment]
Let's use 1062 for https://id.etherpad.mozilla.org/18

**Comment by ozten** [comment]
Closing as dup of 1062.
